### ISSUE TITLE
Floating grid items

### ISSUE THREAD

**Issue by browniefed** [STRML/react-grid-layout#10]
Here is an image that will show the scenario that I describe. [http://i.imgur.com/MHcoaCW.png](http://i.imgur.com/MHcoaCW.png) 

In the event that a large left side grid item exists and a large bar is brought to full width when attempting to drag an item it will only provide slots where the dragging item touches another grid item above it. However it'd be great to be able to drag to any available slot and not necessarily "float to the top".

I was just curious about the feasibility in implementing this or if this is something you see in this library?

Edit: After doing some digging I realized utils.compact is forcing this behavior. Seems like modifying the activeDrag to display anywhere, and also adding `compact` as a boolean is doable.
Also have to think about resizing and how that would be handled. 

I guess a possible other idea would additionally be to "allowOverlap", however that seems more useful on a per-item basis, but not compacting and setting a specific layout that causes overlapping would theoretically work.

**Comment by STRML** [comment]
Hey; so you mean, defining items that selectively aren't compacted?

This would be possible if you defined a separate property on the item for this. It would be very similar to the existing `static` property, but with resizability and draggability still left on.

To be honest, I don't really see a good use case for it; could you explain what you are trying to accomplish? Do you have a fixed-size layout that doesn't need compacting?

**Comment by browniefed** [comment]
I wasn't super clear about my goals. My intention is to build a roadmap and utilize as much of react-grid-layout as possible. So each lane separate would be static elements.
Say you have this scenario [http://i.imgur.com/uPx5u5w.png](http://i.imgur.com/uPx5u5w.png) and you want to place something on the bottom (because an item being on the bottom far right  means something to you). Currently it would float up to the then rest on the swim lane. You would need to add items all the way across just to be able to have an item on the bottom.

I think it'd be great if it worked like things do now, define compact globally but can also turn on/off compact flag on each layout element if you saw fit.
