### ISSUE TITLE
Dynamic rowHeight and fixed aspect ratio on resize

### ISSUE THREAD

**Issue by stha** [STRML/react-grid-layout#100]
Hi there,

i'm struggling with changing the rowHeight of the grid on a window resize event. I want to keep a fixed aspect ratio of the grid elements, even when the window changes size.

Does anyone have a good idea how to solve this? My first idea was to apply a callback to the window resize event and compute the rowHeight based on the current width of an element.

Any help or suggestion is appreciated.

**Comment by stha** [comment]
I added a PR, which solves the problem for me: #101

**Comment by STRML** [comment]
Thanks for that PR.
