### ISSUE TITLE
[onLayoutChange] - callback for onLayoutChange => (layout)

### ISSUE THREAD

**Issue by carlomnop** [STRML/react-grid-layout#1001]
Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

as i defined a property in the layout array...
i get a different callback for onLayoutChange

the callback for it is 
```js
h: 1
i: "Example Name"
isDraggable: undefined
isResizable: undefined
maxH: undefined
maxW: undefined
minH: undefined
minW: undefined
moved: false
static: false
w: 1
x: 0
y: 0
```

while i defined my layout as...
```js
displayName: "Example Name 1"
h: 1
i: "Example Name"
key: 0
name: "Example Name"
w: 1
x: 0
y: 0
```

**Comment by carlomnop** [comment]
I tried mutating the value using useEffect.. however its not mutating at all :(

**Comment by n1ghtmare** [comment]
Can you setup a [codesandbox](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to illustrate the issue perhaps, so that we can take a look at it?

**Comment by js1599** [comment]
I'll help out, will look into this as well.

**Comment by carlomnop** [comment]
Hello all,

As per the issue states that the response of the onLayoutChange is different on the layout that has been rendered.

However i check for a minimal solution which is i declare the I (in the layout) as an Identifier for the reponse data(our) so basically i'm mapping it thru to our side.

Thank you!
