### ISSUE TITLE
example 16 drag from outside 404 not found

### ISSUE THREAD

**Issue by VishalJadhaoCTS** [STRML/react-grid-layout#1003]
Below link for example 16 drag from outside is not accessible and throws 404 error

https://strml.github.io/react-grid-layout/examples/16-drag-from-outside.html

**Comment by daynin** [comment]
@VishalJadhaoCTS it'll be fixed here https://github.com/STRML/react-grid-layout/pull/997

**Comment by n1ghtmare** [comment]
@daynin Sergey, apart from merging the commit, is there anything else we have to do for the github pages to take the new HTML file in the examples? /cc @STRML

**Comment by n1ghtmare** [comment]
@daynin Ok, so I was digging around, and found the [following](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages), I also see a `gh-pages` branch in the repo which is from there the gh-pages read (I think). Do we merge those changes there?

**Comment by daynin** [comment]
@n1ghtmare
> Do we merge those changes there?
yes, of course. I've done it. But we still need to publish new version in npm to allow users use new API. @STRML could you help use with it?

**Comment by daynin** [comment]
@VishalJadhaoCTS now you can find the example here https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html

**Comment by STRML** [comment]
LGTM
