### ISSUE TITLE
drag from outside doesn't work in firefox

### ISSUE THREAD

**Issue by daynin** [STRML/react-grid-layout#1004]
this example doesn't work https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html in firefox (version: 68.0.1 (64-bit))

**Comment by daynin** [comment]
This is an old Firefox issue https://bugzilla.mozilla.org/show_bug.cgi?id=568313. We can fix it by adding `ondragstart="event.dataTransfer.setData('text/plain', '')"` in a tag with `draggable` attribute. But it works not properly in our case. I'll try to find out how to fix it

**Comment by soundyogi** [comment]
Hi,
The example works for me but I cant reproduce it in my react app.
draggable='true' is not working.

Is this a react issue?

**Comment by daynin** [comment]
@soundyogi draggable='true' doesn't work in firefox for now. It should work in chrome

**Comment by daynin** [comment]
@soundyogi and you should set `isDroppable` in your ReactGridLayout/ResponsiveReactGridLayout

**Comment by kenakaiser** [comment]
Doesn't work in Chrome for me - The onDrop function does not run - I dropped your source code into my react project and it doesn't work - is there something   missing from this example https://github.com/STRML/react-grid-layout/blob/master/test/examples/15-drag-from-outside.jsx

**Comment by kenakaiser** [comment]
never mind realized not released yet

**Comment by soundyogi** [comment]
I cant get draggable=true to work in any app on any browser. (only the example runs yes,)
I feel like I am loosing my mind I have to setup a codepen tomorrow o.O

**Comment by soundyogi** [comment]
> @soundyogi and you should set `isDroppable` in your ReactGridLayout/ResponsiveReactGridLayout. Without this prop it won't work

I cant even get the element to be draggable at this point. And yes I set up the properties on RGL.
Atm we are using a hackish solution with react-dnd.

**Comment by kenakaiser** [comment]
@soundyogi - they have't released it yet - you would have to use master at this point - not the npm package - also draggable part works on element outside of Responsive - use draggable = {true}. hopefully they will cut a new release version soon

**Comment by trunks1993** [comment]
how to fix it, it dosen’t work in chrome,too

**Comment by soundyogi** [comment]
Ok I removed all react-dnd code from the app, now I can drag elements with draggable=true.

But RGL does not recognize something being dropped.

DO I understand correctly that this feature is NOT in the current npm package 0.16.6 ?

Thanks

**Comment by trunks1993** [comment]
> (I cant get it to work)
is it can work in chrome?

**Comment by trunks1993** [comment]
@soundyogi Can it work in chrome?

**Comment by soundyogi** [comment]
The last npm release is 2 years old (v 0.16.6)

I need to know if this release includes the ```isDroppable``` already.

I cant get the ```onDrop``` handler to be fired.
@kenakaiser is this what you were saying? Its not in the npm release? (thanks)

**Comment by kenakaiser** [comment]
Yes - that is correct - it is not in the 16.6 release - if you npm install off the last commit hash on master - you can get it to work - but it won't have the build directory - so you have to handle that yourself

**Comment by trunks1993** [comment]
how to handle that @kenakaiser

**Comment by kenakaiser** [comment]
you can fork the branch

**Comment by soundyogi** [comment]
It should be as simple as adding the repo via yarn 
```yarn add https://github.com/STRML/react-grid-layout``` 
and executing the build, I will try that this week.

**Comment by daynin** [comment]
I've fixed it
