### ISSUE TITLE
Вynamic add item

### ISSUE THREAD

**Issue by foxter111** [STRML/react-grid-layout#1006]
Hello. How i can add new item in beginner?

**Comment by marnett-git** [comment]
This example may help you.
https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html

There is a link to the source code at the top.

**Comment by n1ghtmare** [comment]
@foxter111 Did the example that @marnett-git linked helped you?

**Comment by foxter111** [comment]
@n1ghtmare No exactly. I combined example https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html with https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html . First example don`t can add item in beginner. My cards overlap. After adding card, i generate new layout, as in the second example.

**Comment by n1ghtmare** [comment]
Did I understand you correctly that you want to add an item in the beginning (start) of your grid? Can you take a look at this #968? Or more specifically, the [codesandbox](https://codesandbox.io/s/react-grid-layout-d9n8q) that @daynin prepared. Is this what you're looking for?

**Comment by foxter111** [comment]
Thank you! Yes, i wanted add an item in the start my grid. #968 this is that i need, but i solved my problem)

**Comment by n1ghtmare** [comment]
Great, I'm glad to hear that.
