### ISSUE TITLE
Regarding "onlayoutchange" event is not getting correct result on rearrangement of items

### ISSUE THREAD

**Issue by Uma19** [STRML/react-grid-layout#1007]
As of documentation of "ReactGridLayout", 
        /**
         * Callback so you can save the layout.
         * **Calls back with (currentLayout) after every drag** or resize stop.
         */
        onLayoutChange?(layout: Layout[]): void;

Issue is : react grid layout onlayoutchange is not called on rearranging of items
Can you help me to understand which event is used to capture the same ?

**Comment by TheImpressionist** [comment]
Could you provide a repo or codemirror, or perhaps even a snippet of your implementation?

**Comment by Uma19** [comment]
Hey Team,
Sorry I could able to figure out the issue related with the same. 
The issue is : onLayoutChange event internally uses "isEqual" method to compare the old and new object.  So in my case it no. of properties to which we added to the new one was always differing due to which the event was continuously getting trigged
so fixed the no. of properties binded to the same

Thanks you
