### ISSUE TITLE
Tips for next release?

### ISSUE THREAD

**Issue by yuanwind726** [STRML/react-grid-layout#1008]
Thx for the excellent work!! Being looking forwards to the next release, would like to know a little bit about the time point... i see extra nice features merged into master already...

Regards!

**Comment by daynin** [comment]
I think the next release will be after this issue https://github.com/STRML/react-grid-layout/issues/1004 will be fixed. I'm working on it

**Comment by yuanwind726** [comment]
> I think the next release will be after this issue #1004 will be fixed. I'm working on it

Thx a lot, seem "tons" of people waiting for the draging feature from outside to be shipped, lol

**Comment by Gzbox** [comment]
looking forward to publishing

**Comment by daynin** [comment]
The new version has been released!

https://github.com/STRML/react-grid-layout/releases/tag/0.17.0
