### ISSUE TITLE
Re-upload package to NPM to publish drag from outside feature

### ISSUE THREAD

**Issue by pheggeseth** [STRML/react-grid-layout#1009]
Hello, please re-upload to NPM to incorporate the new "drag from outside" feature into the Node Module. This would be incredibly useful for a project I am developing. Thanks.

**Comment by organy110** [comment]
PLEASE DO THAT 🙏🙏🙏. I need it for a project as well.

**Comment by daynin** [comment]
The new version has been released! 

https://github.com/STRML/react-grid-layout/releases/tag/0.17.0
