### ISSUE TITLE
Update Lifecycle method names

### ISSUE THREAD

**Issue by NiamhGilligan** [STRML/react-grid-layout#1014]
Hi im getting a console warning about changing the lifecycle method names for ReactGridLayout , is there an update coming for this or could i make a pr ? 

Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

Please use the [CodeSandbox Template](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to demonstrate your bug. It is much easier for us to help you if you do.

**Comment by n1ghtmare** [comment]
Hi, thanks for submitting an issue, we've already fixed that and merged it in our master branch. It will be sorted out in the next release.

**Comment by NiamhGilligan** [comment]
Ah super thank you.
