### ISSUE TITLE
onDragStop should not be called when item clicked

### ISSUE THREAD

**Issue by gfafei** [STRML/react-grid-layout#1015]
Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

Please use the [CodeSandbox Template](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to demonstrate your bug. It is much easier for us to help you if you do.

onDragStop should not be called when item clicked
here is the demo [demo](https://codesandbox.io/embed/frosty-thunder-zcezp)

**Comment by mert-duzgun** [comment]
Why did you think that it shouldn't call onDragStop when the item is clicked? Because it fires onDragStart. I couldn't find any valid reason for that, I'd love a clearer description if you have time @gfafei. Thanks.

**Comment by gfafei** [comment]
I think you are right. At that time, I thought a click action without mouse movement should not be considered as a drag action. But it's ok to take it as drag. @mert-duzgun
