### ISSUE TITLE
Grid Items not Re-Rendering when Component Props Update

### ISSUE THREAD

**Issue by AlanBreck** [STRML/react-grid-layout#102]
I have an app that displays a grid of widgets using react-grid-layout. Each widget is dependent upon external data and is set up to display a loader until the data has been retrieved and the its props have been updated whereupon the component is re-rendered with the appropriate data. For some reason, though, the grid items aren't re-rendering after the props are updated. Any idea why?

Here's the block of code that calls the react-grid-layout component (see code comments):

```javascript
<ResponsiveReactGridLayout
	className="layout qtDashboard_widgets"
	layouts={{lg: col4, md: col4, sm: col2, xs: col2, xxs: col2}}
	breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
	cols={{lg: 4, md: 4, sm: 2, xs: 2, xxs: 2}}
	onLayoutChange={this.onLayoutChange}
	isResizable={false} isDraggable={false}
	rowHeight={290} margin={[10, 10]}>
	{this.widgets().map( function ( widget, i ) {
		return (
			<div className="qtDashboard_widget_container" key={i}>
				{/*THIS BLOCK RE-RENDERS PROPERLY*/}				
				<DashboardWidget {...widget} appState={this.props.appState} />
			</div>
		);
	}, this )}
</ResponsiveReactGridLayout>
```

...and here's the DashboardWidget component render block:

```javascript
render: function() {
	return (
		<div className="qtDashboard_widget">
			{/*THIS BLOCK DOES NOT RE-RENDER*/}
			<SingleMetric metrics={this.props.appState.metrics} />
		</div>
	);
}
```

When I removed react-grid-layout from the equation, the re-renders took place as expected with the prop updates, but once re-inserted, the DashboardWidget component ceased re-rendering with prop updates.

Thanks, in advance, for your help!

**Comment by mattquinn4** [comment]
You may need to use immutable data structures.  I'm guessing GridItem's shouldComponentUpdate is returning false when it compares props and nextProps because it is actually comparing a reference to the same object.  Have a look at this link for more info:

https://facebook.github.io/react/docs/advanced-performance.html#shouldcomponentupdate-in-action

**Comment by AlanBreck** [comment]
Ahh... that makes sense. ImmutableJS solved it. Thanks so much!

**Comment by benmosher** [comment]
FWIW, looks like `GridItem` is using [a deep comparison of props and state](https://github.com/STRML/react-grid-layout/blob/c540f534682e2a30baee4b7c0ab8bbdcc9d3af00/lib/mixins/PureDeepRenderMixin.js#L7) via `PureDeepRenderMixin`.

**Comment by morgs32** [comment]
Can someone here share an example?
