### ISSUE TITLE
Regarding providing value for "h" unit below 1

### ISSUE THREAD

**Issue by Uma19** [STRML/react-grid-layout#1024]
Hi Team,

**Setting height "h" unit = 1 sets the height of the item as 150px**

But as per our requirement, the height of the item can be below that

So When we give h unit below 1 unit, and try to drag the items,
it goes out of the container 

please find the sample e.g below

{
            **"h": 1,**
            "i": ".$9840a913-983c-44cd-a60d-eadc911ac368",
            "isResizable": true,
            "moved": false,
            "static": false,
            "w": 4,
            "x": 0,
            "y": 2
          }

can you please help to understand how we can solve the above issue
let me know if the question is not clear

**Comment by TheImpressionist** [comment]
Have you set the `rowHeight` property on the layout container itself?
You can specify any rowHeight in pixels there,

Pseudo example:

```javascript
// Here's your RGL container
<Responsive rowHeight={1}>
</Responsive>
// The allowed height by which the elements can increase in size now is by 1px
```

**Comment by Uma19** [comment]
Oh yes tried using the same
pretty much it fixes the problem

Thank you
