### ISSUE TITLE
onDrop missing?

### ISSUE THREAD

**Issue by tomc278** [STRML/react-grid-layout#1025]
Having some issues getting **onDrop** to work. I am passing a function down, if I do with any other callbacks e.g. **onDragStop** it works but not for **onDrop**.

I can see that onDrop is refered to in the docs and it is used in **/lib/ReactGridLayout.js** on GitHub. 
However when I install the package it is not used in node_modules/**/build/ReactGridLayout.js**

**Comment by Jacob-Grafenstein** [comment]
Seeing the exact same issue. The build of ReactGridLayout does not contain onDrop at all:
![image](https://user-images.githubusercontent.com/13575108/66275053-f52f7080-e852-11e9-977b-1c19b85e15a7.png)

**Comment by Jacob-Grafenstein** [comment]
Ran the build myself locally, and onDrop can be found in `ReactGridLayout.js`. So I checked out the commit from the most recent release (0.16.6) and ran the build. Lo and behold, onDrop is missing from all the build files. @STRML We need a release with the newest features!

**Comment by Jacob-Grafenstein** [comment]
@tomc278 Looks like this feature was only recently added to the project. See https://github.com/STRML/react-grid-layout/pull/997

**Comment by n1ghtmare** [comment]
I'm closing this issue because it will be fixed in the next release as noted by @Jacob-Grafenstein
