### ISSUE TITLE
Is it possible to limit the grid layout to a specific number of rows?

### ISSUE THREAD

**Issue by madtag** [STRML/react-grid-layout#1027]
I would like to limit the layout to 1 or 2 rows.  Is this possible?

I have tried to set translateY to 0 in teh onDrag function but it still creates a new row.

 onDrag = (layout, oldItem, newItem, placeholder, e, element) => {
        const grid = document.getElementsByClassName('react-grid-layout')[0];
        const translateXMaxValue = grid.offsetWidth - element.offsetWidth;
        const translateValues = window.getComputedStyle(element).transform.split(',');
        let translateX = parseInt(translateValues[translateValues.length - 2]);
        let translateY = 0;
        if (translateX > translateXMaxValue) {
            translateX = translateXMaxValue;
        }
        if (translateX < 0) {
            translateX = 0;
        }
        element.style.transform = `translate(${translateX}px, ${translateY}px)`;
    };

**Comment by danilockthar** [comment]
I wish they could answer this in some issue :/

**Comment by danilockthar** [comment]
> I would like to limit the layout to 1 or 2 rows. Is this possible?
> 
> I have tried to set translateY to 0 in teh onDrag function but it still creates a new row.
> 
> onDrag = (layout, oldItem, newItem, placeholder, e, element) => {
> const grid = document.getElementsByClassName('react-grid-layout')[0];
> const translateXMaxValue = grid.offsetWidth - element.offsetWidth;
> const translateValues = window.getComputedStyle(element).transform.split(',');
> let translateX = parseInt(translateValues[translateValues.length - 2]);
> let translateY = 0;
> if (translateX > translateXMaxValue) {
> translateX = translateXMaxValue;
> }
> if (translateX < 0) {
> translateX = 0;
> }
> element.style.transform = `translate(${translateX}px, ${translateY}px)`;
> };

were you able to make it work?
