### ISSUE TITLE
Failed prop types on ResponsiveGridLayout

### ISSUE THREAD

**Issue by mei33** [STRML/react-grid-layout#1031]
Accordingly to documentation, ResponsiveGridLayout can receive `cols` property as an object with numbers related to each breakpoint, but it thows an Error:

Warning: Failed prop type: Invalid prop `cols` of type `object` supplied to `ReactGridLayout`, expected `number`.
    in ReactGridLayout (at App.js:20)
    in MyFirstGrid (at src/index.js:7)
console.<computed> @ index.js:1375

Warning: Failed prop type: Invalid prop `cols` of type `object` supplied to `GridItem`, expected `number`.
    in GridItem

**Comment by damiangreen** [comment]
Either the documentation is wrong or the types are wrong
