### ISSUE TITLE
horizontal units as percentages

### ISSUE THREAD

**Issue by benmosher** [STRML/react-grid-layout#104]
Would you be open to a PR that changes all the width calculations from pixel values to percentages?

Also: any obvious gotchas to a percentage-based column width system? I think it might remove the dependency on the window `resize` event and would empower the browser to animate width changes as necessary.

I am not sure what sort of server-side rendering you're trying to preserve, but assuming the end client is still a browser, I don't see any issues there. 

AFAICT the `transform` styles accept mixed units (i.e. `translate(5%, 14px)`) so I don't think there is any gotcha there, either.

I may need to fork and provide this functionality anyway. Just curious if you'd consider merging it back in and/or you've tried it and it fails for [x reason].

Thanks! 😄

**Comment by STRML** [comment]
I would be 100% open to this as it also makes server-side rendering much more predictable. 

The issue I've found with it is that percentages in `translate()` are relative to the element itself (!), not the viewport, so some fancy math would be necessary in order to ensure that the offset is correct.

See my notes here: https://github.com/STRML/react-grid-layout/blob/master/lib/GridItem.jsx#L174

**Comment by STRML** [comment]
`<Draggable>` would need to be adapted to work with percentages as well. This would require knowledge of the parent's dimensions and a `'resize'` handler to recalculate it on drag.

When we get the drag event, we only get its offset in pixels. We simply add that to its current offset. A `top` / `left` percentage based layout would be impossible to do (AFAIK) without a `'resize'` handler so we know where it's actually going to go. A `translate()`-based layout would work, but would require knowing the width of the element.

**Comment by benmosher** [comment]
Ah, interesting points. I forgot about the `translate` percentage scope. That should just be something like `width of 1 column (%) * x column position * (total columns / item column width)`, right? A little weird, but doable. i.e. item at x=2, w=2 on a 4-wide grid is thus positioned at 100%.

Margins are a loose end. `calc([margin]px + [position]%)` seems to be viable as a `translate` unit (in Chrome beta, at time of writing), though it's pretty crazy looking.

It can be assumed the window won't resize during any grid item drag/resize event--right?--so any relevant pixel width info (be it for the item or the full grid) could be requested at the start of the mutation.

I'm not sure when I might dig into this, but I'll let you know if I get anywhere with it.

**Comment by STRML** [comment]
Yeah, re: resizes while dragging that seems like a good assumption.

Margins will have to be calculated as percentages only. We can't rely on `calc()`.

It looks like the `transform` property is good to go in IE9 (as `-ms-transform`) so browser compat shouldn't be a problem.

Let me know how it goes - thanks for offering to take a look at this.

**Comment by anatolikurtsevich** [comment]
Hi there,

I found this code https://github.com/STRML/react-grid-layout/blob/master/lib/GridItem.jsx#L265

```
// This is used for server rendering.
if (usePercentages) {
    style.left = perc(pos.left / containerWidth);
    style.width = perc(pos.width / containerWidth);
}
```

where `usePercentages` is set to `true` until the ReactGridLayout component is mounted. Thus, the `if` statement is called even when it's not a server side rendering. When the GridItem is being rendered it gets `width` as percentage first and after mounting it gets `width` in pixels.

What do you think about making this `if` statement more sophisticated? According to the thread https://stackoverflow.com/questions/32216383/in-react-how-do-i-detect-if-my-component-is-rendering-from-the-client-or-the-se what could be done here is using the package https://www.npmjs.com/package/exenv and do the following `ExecutionEnvironment.canUseDOM`. Another option would be https://stackoverflow.com/a/42009294.
