### ISSUE TITLE
Why npm package of this project last published was two years ago?

### ISSUE THREAD

**Issue by gfafei** [STRML/react-grid-layout#1040]
Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

Please use the [CodeSandbox Template](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to demonstrate your bug. It is much easier for us to help you if you do.

**Comment by dennisvankekem** [comment]
Personally I would like to use the "onDrop from outside" functionality. This is not yet available in 0.16.6 but is already available in the documentation and even has an example to it. When can we expect this feature to become available in a new package?

**Comment by Zwieks** [comment]
The documentation showing "onDrop from outside" functionality is already available but it is not in the package.. an update about this would be nice indeed
