### ISSUE TITLE
Bug resolving collisions with items when compact mode is "null"

### ISSUE THREAD

**Issue by eddyw** [STRML/react-grid-layout#1045]
When adding a new item to layout `{ x: 0, y: 0 }` with existing items if it collides, the layout seems to kind of randomly move the items away from collisions.

I made a code sandbox that demonstrates the issue: https://codesandbox.io/s/rgl-bug-resolving-collisions-rh1dv
Just click on `Insert new` for about 10 times and see that items are moved down kind of randomly creating unnecessary gaps. Once you have inserted 2 items, you can see that the first item was moved after all static ones leaving a gap. I implemented my own solution (may not be perfect) using CSS grids that displays on the sandbox the expected result.

Additionally, if you change this line `setLayout(nextLayout);` to `setLayout(layoutWithoutCollisions);`, you'll see that RGL correctly moves the items away. However, that's not always the case, I found certain cases when items that don't collide but close to statics seem to also be moved away.

I don't know if this is a "feature" or a "bug" since the logic to move away items doesn't make much sense to me.

I'd like to help solving this issue since it's very problematic. For instance, if you have a colliding item that has a big height, you'll see a very huge gap on your screen.

**Comment by eddyw** [comment]
🙄

**Comment by alon24** [comment]
Can this bug be addresses/opened? 
I am seeing same issues, where the resize does not work as expected
