### ISSUE TITLE
You seem to do not care about this repo!

### ISSUE THREAD

**Issue by TimSusa** [STRML/react-grid-layout#1048]
Please give 57 open Pull Request a chance to make this cool piece of software better. Even more I would suggest to migrate over to React Hooks. 

Thanks!

**Comment by vaheqelyan** [comment]
>  Even more I would suggest to migrate over to React Hooks.

In terms of performance, I would not recommend this

**Comment by adberard** [comment]
> In terms of performance, I would not recommend this
Sauce ?

**Comment by eddyw** [comment]
> In terms of performance, I would not recommend this
Could you elaborate?

@TimSusa 
A few days ago there was a reply in this thread: https://github.com/STRML/react-grid-layout/issues/1040
It was mentioned that next release would happen "soon". As per milestone, there seems to be one issue open for that to happen:
https://github.com/STRML/react-grid-layout/milestone/1

However, I do agree that progress is slow and 56 open PRs just doesn't give enough trust or confidence on the projects' future.

**Comment by wkhatch** [comment]
I have this working with hooks, retrieving a layout via an api call. Works with both the latest version and the previous.

**Comment by hegelstad** [comment]
Re-open?
