### ISSUE TITLE
isDroppable Prop is still not available

### ISSUE THREAD

**Issue by pwrUserPro** [STRML/react-grid-layout#1055]
The isDroppable prop is not available in the latest 0.17.0 package that's hosted on NPM. There is documentation for the prop on the homepage and there is even a linked demo showing how the isDroppable prop works. Please add isDroppable to the package hosted on NPM.

**Comment by flashtheman** [comment]
Just noticed as well. Are you using Typescript? I no expert at all but it seems to me the type definitions seem to be from 0.16 --> current version is 0.17.

**Comment by flashtheman** [comment]
Ok, speaking for Typescript: I learned that the type definitions are hosted here: https://www.npmjs.com/package/@types/react-grid-layout.

However, the version is 16.3 which is 8 months old. Does anyone know who the maintainer of these definitions is?

**Comment by flashtheman** [comment]
Now tested to just edit the type definitions file of Typescript. It works now. Simply add isDroppable under node_modules/@types/react-grid-layout/index.d.ts in the same way as it is already included for isDraggable.

**Comment by pwrUserPro** [comment]
I am using TypeScript and I did also notice the type definitions are from 0.16. 

Great idea editing the type definitions! Thank you for the tip!

**Comment by flashtheman** [comment]
You'll also need to add the onDrop event.
Please consider the bug (https://github.com/STRML/react-grid-layout/issues/1058) I opened today.

**Comment by pwrUserPro** [comment]
Not stale.
