### ISSUE TITLE
0.17.0 is checking for navigator even if there is no window

### ISSUE THREAD

**Issue by alexvision** [STRML/react-grid-layout#1056]
The Firefox check here should only occur in a context where window exists: https://github.com/STRML/react-grid-layout/blob/master/lib/ReactGridLayout.jsx#L100

**Comment by DylanJu** [comment]
Here is the same error for me. I fixed temporarily by fixing the version down to 0.16.6.

**Comment by alexvision** [comment]
This change fixes it for me if you wanted to try it  https://github.com/STRML/react-grid-layout/issues/1057
