### ISSUE TITLE
onDrop callback not returning event

### ISSUE THREAD

**Issue by flashtheman** [STRML/react-grid-layout#1058]
The drop property is documented as follows:
`onDrop: (elemParams: { x: number, y: number, e: Event }) => void`

However, as you can see in the demo provided (https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html), it does not return the event property. However, it returns the width and height.

Therefore it's not possible to retrieve data from the dropped element using getData.

**Comment by Jacob-Grafenstein** [comment]
This issue is affecting my application as well. The current implementation only seems to support the narrow use case defined in the examples, instead of an extensible solution that allows you to drag and drop any node from a palette onto the canvas.

**Comment by Jacob-Grafenstein** [comment]
@flashtheman see my PR. I believe this will solve the use case. Can you confirm?

**Comment by n1ghtmare** [comment]
This issue is now fixed, thanks @Jacob-Grafenstein great job.
