### ISSUE TITLE
Bug: droppable doesn't work on mobile (clarify on docs?)

### ISSUE THREAD

**Issue by eddyw** [STRML/react-grid-layout#1061]
Probably this issue will never have a response as the previous one I filled 🙈  but maybe will help others to think if they really want to implement the droppable feature. It just doesn't work on mobile:

https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html

The easiest way to test it is just to use Chrome dev tools to switch to a mobile device preview.

**Comment by Marius8881** [comment]
I wonder if this will be fixed...I already implemented on drop, and saw the same issue you described, if it will not be fixed, I will have to drop the whole thing from the companies projects.
