### ISSUE TITLE
Can only resize grid items to a particular width

### ISSUE THREAD

**Issue by kartik2014** [STRML/react-grid-layout#1071]
Is it only possible to resize grid items to a particular width? For e..g in the basic demo:
https://strml.github.io/react-grid-layout/examples/1-basic.html

...on dragging the bottom right corner of an item, it shows a pink/orange background, which seems to determine the width to which item can be resized to. Is there a way to resize the item to a random width(within minW and maxW) at all?

**Comment by lebbe** [comment]
This is a function over how many columns you have, which is divided on the width of the whole grid layout. If these numbers are the same, they should behave like pixels. But then, make sure that margins are set to 0!

`<GridLayout width={1024} cols={1024} margin={[0, 0]} ...`

should work, for instance.

**Comment by Hari-Shankar-3296** [comment]
It seems like you need to set custom width / height on resizing the grid item
( Ignore this reply if I am wrong )
RGL has a prop in which we will be passing a function
```javascript
onResize={ onCustomResize }
```
where the onCustomResize function will be like
```javascript
function onCustomResize( layout, oldLayoutItem, layoutItem, placeholder ) {
    let customHeight, customWidth;
    // write whatever condition you want
    // set whatever customWidth / customHeight you want 
    // mutate the layoutItem and placeholder obj directly ( their recommended way )
    layoutItem.h = customHeight;
    layoutItem.w = customWidth;
    placeholder.h = customHeight;
    placeholder.w = customWidth;   
}
```
This worked for me... :100:
