### ISSUE TITLE
Add id prop to RGL

### ISSUE THREAD

**Issue by carole-bennett-enosix** [STRML/react-grid-layout#1072]
Trying to follow directions regarding submitting pull request from forked repo; adding this issue to request the addition of an id prop to RGL, which enables the use of multiple RGL components on a single page. This is especially helpful when using RGL in combination with external source drag-and-drop elements.

**Comment by JohnDDuncanIII** [comment]
While not absolutely necessary, this would also help us with a product we're launching soon that utilizes `react-grid-layout`.
