### ISSUE TITLE
Horizontal autosize

### ISSUE THREAD

**Issue by jvarada** [STRML/react-grid-layout#1073]
I have a use case that requires horizontal autosizing (i.e. the parent container expanding when an item is stretched past the horizontal boundary), similar to what happens in the vertical case. As far as I can tell, there is no way to do this right now.

Is there a particular technical or library design reason for this, or some other subtlety I should be aware of if I implement this feature myself?

**Comment by Fled8617** [comment]
@jvarada sizeme
![image](https://user-images.githubusercontent.com/35049517/68659904-192d5280-0573-11ea-82d7-3e78536e1407.png)
