### ISSUE TITLE
How to pass array object into react-grid-layout. Items show up vertically and do not form a grid

### ISSUE THREAD

**Issue by manavpandya** [STRML/react-grid-layout#1076]
Googled it the same but there is no specification about how to use dynamic data or arrays inside the GridLayout, and none of the information is provided into the docs.

Here it is the question raised by someone few months back.

https://stackoverflow.com/questions/54348311/how-to-pass-array-object-into-react-grid-layout-items-show-up-vertically-and-do

Hope @STRML will dig into it and rescue me some day, Thanks.

**Comment by manavpandya** [comment]
The issue is still there so won't be closed now

**Comment by Kakomis** [comment]
Hi, Could you solve it?
