### ISSUE TITLE
How to achieve horizontal wrapping of tiles? 

### ISSUE THREAD

**Issue by nitesh619** [STRML/react-grid-layout#1082]
If using horizontal compaction type, then tiles doesn't move/shift to the previous row. 

How to pack the grid, so that no space in the end. Please suggest.

**Comment by yuanzhiheng1993** [comment]
update layout's x and y in onLayoutChange function

**Comment by nitesh619** [comment]
I have implemented the solution, please find the details here: https://github.com/STRML/react-grid-layout/issues/1100#issuecomment-583741129
