### ISSUE TITLE
Cols update doesn't reflect changes in version 0.17.1

### ISSUE THREAD

**Issue by minotogna** [STRML/react-grid-layout#1083]
Hello,

I noticed that in version 0.17.1 if cols is dynamically update, the grid doesn't reflect the change.
It used to work in version 0.16.6.

I have create a test case here:
https://codepen.io/drusus-uttarayananda-minor/pen/KKKEKvY

Thank you.
Mino

**Comment by lebbe** [comment]
I also experience this problem, updating cols doesn't update the GridLayout.

**Comment by lebbe** [comment]
I found kind of like a workaround. We don't need the moved flag in the layout, so I just flip this boolean every time cols is updated, and the grid is redrawn with the new cols.

```
this.setState({
	layout: [{...a, moved: !a.moved}, ...rest],
	cols: cols
});
```
