### ISSUE TITLE
Infinity throws type error

### ISSUE THREAD

**Issue by hanhansen** [STRML/react-grid-layout#1087]
I currently have a responsive grid layout where a user can add and remove items. According to the `Adding\Removing demo`, the added item's `y` value is set to `Infinity`. When I do this, my grid works as expected; however, I get a warning in the console: `Failed prop type: ReactGridLayout: layouts.sm[0].y must be a number!`. Infinity is of type number.

Is this a known issue?

**Comment by yuanzhiheng1993** [comment]
You can calculate item‘s y
