### ISSUE TITLE
OnClick event on touch devices

### ISSUE THREAD

**Issue by janhalama** [STRML/react-grid-layout#109]
Hi,
setting isDraggable = true prevents OnClick handlers inside GridItem from being fired on touch devices. Tested in GC emulator as well on real device.

I have react-grid-layout ver. 0.8.5.

I have not found any workaround yet.

Jan

**Comment by STRML** [comment]
A lot of touch issues were fixed in the underlying `<Draggable>` a few months ago. Please reopen if you are still experiencing this.

**Comment by masureshho** [comment]
The issue still persists on Touch devices.
