### ISSUE TITLE
preventCollision not working when dragging an element from outside the grid

### ISSUE THREAD

**Issue by violabg** [STRML/react-grid-layout#1093]
if you drag an element from outside the grid, and you enter the grid by hovering the item that is at x:0, y:0, you see a shift on the layout, even if you have set compactType={null} and preventCollision={true}.

Instead if you drag it into the grid, by going on the right of the first item, everything it behaves as aspected.

this is a sample code:
https://codesandbox.io/s/react-c58k1

**Comment by sterzhakov** [comment]
Same problem! I tried to set static true for all grid elements on drag & drop event, but this caused rerender for all grid elements.

**Comment by JPNZ4** [comment]
I'm also getting this issue. Any luck without re-rendering all the grid elements?

**Comment by qqjiandj123** [comment]
setting allowOverlap=true; preventCollision=true; compactType=null;   
when drag from outside, all items reload, do not overlap
