### ISSUE TITLE
Can you specify a part of the component as a drag handle?

### ISSUE THREAD

**Issue by szt19980425** [STRML/react-grid-layout#1094]
Can you specify a part of the component as a drag handle?
I added a component, and found that dragging conflicts with events inside the component, making the component unusable. I want to be able to specify that only a certain part of the component can be dragged inside the component

**Comment by Doesntmeananything** [comment]
Yes, take a look at [grid-layout-props](https://github.com/STRML/react-grid-layout#grid-layout-props):

```javascript
// A CSS selector for tags that will act as the draggable handle.
// For example: draggableHandle:'.MyDragHandleClassName'
// If you forget the leading . it will not work.
draggableHandle: ?string = '',
```

You should be able to target an element with a CSS selector in order to make it a drag handle.
