### ISSUE TITLE
Possible to drag only along single axis and remove elasticity?

### ISSUE THREAD

**Issue by pratikguru** [STRML/react-grid-layout#1098]
I've been using the package for a long time and I find it very useful. I was trying to implement a drag only feature which but I wanted to be able to drag only along a single axis ( ie either x or y ). 

Is there a way to drag this only along a single axis and also turn off the elastic animation?

**Comment by dherbolt** [comment]
Hi, there is my PR to define resize in one direction only: https://github.com/STRML/react-grid-layout/pull/1102
