### ISSUE TITLE
Drag grid-items between grid-layouts

### ISSUE THREAD

**Issue by ericgibb** [STRML/react-grid-layout#11]
It would be awesome if you could drag an item from one layout to another layout.

**Comment by STRML** [comment]
Woof. Definitely possible, lots of work. Would be happy to accept a PR!
I don’t foresee this within the general use case but it could be
implemented via a wrapper around |<ReactGridLayout>| that handles the
detection. The only modification I can foresee to the existing code
would be a raw callback from a |<GridItem>|‘s underlying |<Draggable>|
that reports the page x & y as it moves.

On 1/7/15 8:23 PM, ericgibb wrote:

> It would be awesome if you could drag an item from one layout to
> another layout.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STRML/react-grid-layout/issues/11>.
>
​

**Comment by browniefed** [comment]
This seems like a much better thing to occur outside of react-grid-layout. I'm working on a PR at the moment to add in a few calls to allow you to do stuff on drag/resize to possibly modify layout, or cancel those actions.
It would require some additional passthrough from GridItem as @STRML mentioned but theoretically if `onDrag` you detected you were hovering over another gird you could pop off the item from one ReactGridLayout and move it to another, may need to expose some utils for X/Y coord translation to grid layout positions.

**Comment by STRML** [comment]
This is out of the scope of this component but could likely be done with an external grouping component. if you make one, please post a link to it as a comment as I'd like to see it. Thanks for the idea.

**Comment by benmosher** [comment]
FWIW: I intend to attempt something like this with [React-DnD](https://github.com/gaearon/react-dnd), soon.

Won't be between layouts, but I may allow dragging from a list of items onto a layout, which would add the item and (hopefully) put it immediately into drag mode.

**Comment by cmelion** [comment]
Did anyone get dragging from an external grid/list working and willing to share?

**Comment by jozsi** [comment]
I would also be interested in this.

**Comment by vincenzocaruso** [comment]
same for me, it could be interesting

**Comment by JimVercoelen** [comment]
Any updated on this issue? Did someone manage it in the meantime?

**Comment by benmosher** [comment]
I was not able to get it working but I don’t recall how much effort I gave it.
