### ISSUE TITLE
How to achieve horizontal + Vertical compacting together?

### ISSUE THREAD

**Issue by nitesh619** [STRML/react-grid-layout#1100]
Can we have both horizontal and vertical compacting together?

**Comment by Hari-Shankar-3296** [comment]
We can achieve that but the grid packing will be very weird.
Set the props compactType = "horizontal" and verticalCompact = true
FYI Check all possible arrangements.

**Comment by nitesh619** [comment]
@Hari-Shankar-3296 Yes, I tried setting the verticalCompact prop and it is super weird.

But my goal is to always move tiles from right to left. If i drag a tile from the top row to the bottom row. Then the spot vacated by this tile should be occupied by tile to its right and the tile from the beginning of next row should come up and so on. Like text in paragraph, if we delete letters then next line character will come up.

**Comment by Hari-Shankar-3296** [comment]
@nitesh619 I got your point now. The thing you are expecting ( even I need the same behaviour ) is not possible with react-grid-layout currently. But there are other library in which you can achieve this.

Here is the link. 
https://ourcodeworld.com/articles/read/663/top-5-best-draggable-droppable-and-resizable-grid-layout-designer-jquery-and-javascript-plugins
and up to me Muuri is the best.
```Note :```
```
In Murri we can't resize grid items ( Can be done by adding React-Resizable ).
Some libraries are done using jQuery.
Up to my knowledge Muuri doesn't use jQuery
```
If you find any other good libraries, Please do let me know. :+1:

**Comment by nitesh619** [comment]
Thanks @Hari-Shankar-3296, Murri is really good. But I am not sure how it will work with react and also I can't afford to revert my changes and start with murri, I guess I have passed that stage. So I have decided to modify react-grid-layout codebase for the behavior I need. Wish me luck, looks like a tough task ahead. I will keep you posted.

**Comment by JoshRozin** [comment]
@nitesh619 Hey, Did you end up getting that working? I've seen react-wrappers for muuri, not sure if they're still up to date.

**Comment by nitesh619** [comment]
Hey,

Yes, actually I was able achieve this behavior by easily overriding few util methods of the grid.

**Comment by amrsalama** [comment]
@nitesh619 May you share your solution with us ?

**Comment by IvoBeneStudio** [comment]
@nitesh619 Little reminder if you would please share your solution. Much needed here as well :)

**Comment by nitesh619** [comment]
### How to do horizontal + vertical compaction combined,  also maintain ordering while dragging tiles on the grid
Hey @IvoBeneStudio @amrsalama,

Please find the solution below to achieve "Horizontal + Vertical" alignment.

Create a gridUtil.js or gridUtil.ts file in your project with following imports:
```import * as RGL_UTILS from 'react-grid-layout/build/utils'
  import {
     sortLayoutItems,
     getLayoutItem,
     cloneLayoutItem,
     validateLayout,
     correctBounds,
     getAllCollisions,
     bottom
  } from 'react-grid-layout/build/utils
```

1. To **compact tiles horizontally and vertically** when you add or remove tiles to the gird array, override 'compact' method with following code:

``` 
RGL_UTILS.compact =  function compact(
  layout: Layout,
  compactType: CompactType,
  cols: number
): Layout {
  // We go through the items by row and column.
  const sorted = sortLayoutItems(layout, 'vertical');
  // Holding for new items.
  const out = Array(layout.length);

  for (let i = 0, len = sorted.length; i < len; i++) {
    let l = cloneLayoutItem(sorted[i]);

    // Don't move static elements
    if (!l.static) {
      l.y = Math.floor(i / cols)
      l.x = i % cols
    }
    // Add to output array to make sure they still come out in the right order.
    out[i] = l;
    // Clear moved flag, if it exists.
    l.moved = false;
  }
  return out;
}
```

_Logic:_  
- sort the tiles in the grid row wise i.e [tiles_of_row1, tiles_of_row2, .... ]
- Now pop tiles from sorted array and add to output array with correct x and y without gaps.

**Note:** After overriding the above method, also override the 'synchronizeLayoutWithChildren' like below:
```
/* No code is added here. It's just copied from library otherwise grid wont call our overrided compact method */
RGL_UTILS.synchronizeLayoutWithChildren = function synchronizeLayoutWithChildren(initilaLayout, children, cols, compactType) {
  ....
  // copy the exact code from the utils.js 'synchronizeLayoutWithChildren' method
   .....
} 
```
2. To keep the order i.e **ordering of tile while dragging** it around, override with following: 

```
RGL_UTILS.moveElement =  moveElement(
  layout: Layout,
  l: LayoutItem,
  x: ?number,
  y: ?number,
  isUserAction: ?boolean,
  preventCollision: ?boolean,
  compactType: CompactType,
  cols: number
): Layout {
  // If this is static and not explicitly enabled as draggable,
  // no move is possible, so we can short-circuit this immediately.
  if (l.static && l.isDraggable !== true) return layout;

  // Short-circuit if nothing to do.
  if (l.y === y && l.x === x) return layout;

  log(
    `Moving element ${l.i} to [${String(x)},${String(y)}] from [${l.x},${l.y}]`
  );
  const oldX = l.x;
  const oldY = l.y;

  // This is quite a bit faster than extending the object
  if (typeof x === "number") l.x = x;
  if (typeof y === "number") l.y = y;
  l.moved = true;

  // If this collides with anything, move it.
  // When doing this comparison, we have to sort the items we compare with
  // to ensure, in the case of multiple collisions, that we're getting the
  // nearest collision.
  let sorted = sortLayoutItems(layout, compactType);
  const movingUp =
    compactType === "vertical" && typeof y === "number"
      ? oldY >= y
      : compactType === "horizontal" && typeof x === "number"
      ? oldX >= x
      : false;
  if (movingUp) sorted = sorted.reverse();
  const collisions = getAllCollisions(sorted, l);

  // There was a collision; abort
  if (preventCollision && collisions.length) {
    log(`Collision prevented on ${l.i}, reverting.`);
    l.x = oldX;
    l.y = oldY;
    l.moved = false;
    return layout;
  }
 if(isUserAction) {
    isUserAction = false;
    if(oldX === x) isLeftShift = oldY - y <= 0;
    if(oldY === y) isLeftShift = oldX - x <= 0;
 }
  // Move each item that collides away from this element.
  for (let i = 0, len = collisions.length; i < len; i++) {
    const collision = collisions[i];
    log(
      `Resolving collision between ${l.i} at [${l.x},${l.y}] and ${collision.i} at [${collision.x},${collision.y}]`
    );

    // Short circuit so we can't infinite loop
    if (collision.moved) continue;

    // Don't move static items - we have to move *this* element away
    if (collision.static) {
      layout = RGL_UTILS.moveElementAwayFromCollision(
        layout,
        collision,
        l,
        isUserAction,
        compactType,
        cols,
        isLeftShift
      );
    } else {
      layout = RGL_UTILS.moveElementAwayFromCollision(
        layout,
        l,
        collision,
        isUserAction,
        compactType,
        cols,
        isLeftShift
      );
    }
  }

  return layout;
}
```

```
RGL_UTILS.moveElementAwayFromCollision =  moveElementAwayFromCollision(
  layout: Layout,
  collidesWith: LayoutItem,
  itemToMove: LayoutItem,
  isUserAction: ?boolean,
  compactType: CompactType,
  cols: number,
  isLeftShift,
): Layout {
  const compactH = compactType === "horizontal";
  
  const preventCollision = collidesWith.static; // we're already colliding (not for static items)
  const isTileWrapping = isLeftShift
      ?  itemToMove.x - 1 < 0
      :   itemToMove.x + 1 >= cols;
  const deltaShift = isLeftShift ? -1 : 1
  const x = isTileWrapping ? (isLeftShift ? cols - 1 : 0) : itemToMove.x + deltaShift
  const y = isTileWrapping ? itemToMove.y + deltaShift : itemToMove.y

  return moveElement(
    layout,
    itemToMove,
    compactH ? x : undefined,
    y,
    isUserAction,
    preventCollision,
    compactType,
    cols,
    isLeftShift
  );
}
```

_Logic:_
- isLeftShift : tells if user moved the tile should be shifted to left after user dragged a tile
- isTileWrapping : tells, if tile needs to be shifted to the next row

**Please let me know, if you face any problems while implementing it.** Also, If anyone wants to volunteer to create a pull request with this feature then I would be happy to guide.

**Comment by nitesh619** [comment]
Closing this issue, as above solution will provide the needed feature. Also tested this and fond OK with all test cases.

**Comment by JohnThomson** [comment]
I made some changes based on the above, but making the new behavior conditional on a new compactType "wrap". The full PR is at https://github.com/STRML/react-grid-layout/pull/1188.

**Comment by bradleyDouglas** [comment]
@nitesh619 Do you mind checking out this CodeSandbox? I'm missing something with your implementation, I just can't figure it out. Thanks!

https://codesandbox.io/s/react-grid-layout-double-compaction-z1kwo?file=/src/App.js

**Comment by JohnThomson** [comment]
I took a quick look. It's not doing what I need yet.
For example, starting with
abc
def
ghi
and dragging d to where h started out, I want
abc
efg
hdi
but I get
abc 
gef
hdi

**Comment by JohnThomson** [comment]
That's not to say what you have may not be useful to someone. I'm not really clear what you were aiming at.

**Comment by bradleyDouglas** [comment]
@JohnThomson I probably should have been more specific. What I'm trying to accomplish is the ability to re-arrange the gird without it creating more rows. Currently, when I drag A to I's spot, F jumps down to a new row.

**Comment by JohnThomson** [comment]
I don't think you're there yet. When I tried dragging A to I's spot as directly as I could, things jumped all over the place during the drag, and I ended up with
f b c
e f
d g a
h
Trying again along a slightly different path, I got
b c
d e
g h a
f i
I tend to think that the result of dragging a card to a particular destination should be independent of the route

**Comment by bradleyDouglas** [comment]
@JohnThomson I agree, I'm not there yet. That's why I posted the CodeSandbox. It reads as if @nitesh619 solved this problem, so I tried implementing his solution up top, but I'm not getting the results. 

What you got is my issue. I want a grid of 3 columns and 3 rows at all times. No matter what gets dragged where. Currently, there are times (when dragging any item to the lower right), that a new row is created, opposed to just shuffling the items around the 3x3 grid.

**Comment by nitesh619** [comment]
Hey Guys,

Its almost a year since I worked on it. I will try to recall and look at your sandbox solution. Give me sometime. 

Best Regards
Nitesh Jain

**Comment by bouncydragon** [comment]
Looking forward to the solution, I'm encountering the same issue for weeks now and can't find a proper solution. 

Cheers!

**Comment by nelsieborja** [comment]
I also need this feature and found this [React version of Muuri](https://paol-imi.github.io/muuri-react/showcase) which seems to provide almost all of what RGL has including this feature mentioned here. Unfortunately, the library seems not actively maintained

**Comment by bung87** [comment]
This is feature I wanted, when you have static size grids layout just wanna exchange position double directions by user interaction.

**Comment by mechivk** [comment]
Hi! I am having the same problem. Is there a way to merge this solution into the code? 
I don't understand how I can implement it if the library code is read-only. I can't override functions from my own code. Or can I?

**Comment by Mohamed-Raid** [comment]
I am having the same problem. Is there a way to merge this solution into the code or to have a sandbox working copy please ?

**Comment by HarutyunyanDavo20** [comment]
Please share codeSandbox example how can we do it !

**Comment by garciaguillermoa** [comment]
Thanks @nitesh619 for posting the code! It works great!

@mechivk yes you can override code by importing the gridUtil.js file like `import  "@/utils/gridUtil";`.

Posting my working code in case it helps somebody else. It is almost the same code that @nitesh619 posted (I added a missing parameter to one function), plus part of a React component making use of it.

**gridUtil.js**

```
import React from 'react';
import * as RGL_UTILS from 'react-grid-layout/build/utils'
import {
   sortLayoutItems,
   getLayoutItem,
   cloneLayoutItem,
   validateLayout,
   correctBounds,
   getAllCollisions,
   bottom,
   compact,
   moveElement
} from 'react-grid-layout/build/utils';

RGL_UTILS.compact =  function compact(
  layout,
  compactType,
  cols
) {
  // We go through the items by row and column.
  const sorted = sortLayoutItems(layout, 'vertical');
  // Holding for new items.
  const out = Array(layout.length);

  for (let i = 0, len = sorted.length; i < len; i++) {
    let l = cloneLayoutItem(sorted[i]);

    // Don't move static elements
    if (!l.static) {
      l.y = Math.floor(i / cols)
      l.x = i % cols
    }
    // Add to output array to make sure they still come out in the right order.
    out[i] = l;
    // Clear moved flag, if it exists.
    l.moved = false;
  }
  return out;
}

/* No code is added here. It's just copied from library otherwise grid wont call our overrided compact method */
RGL_UTILS.synchronizeLayoutWithChildren = function synchronizeLayoutWithChildren(initialLayout, children, cols, compactType, allowOverlap) {
  initialLayout = initialLayout || [];

  // Generate one layout item per child.
  const layout /*: LayoutItem[]*/ = [];
  React.Children.forEach(children, (child /*: ReactElement<any>*/) => {
    // Child may not exist
    if (child?.key == null) return;
    const exists = getLayoutItem(initialLayout, String(child.key));
    const g = child.props["data-grid"];
    // Don't overwrite the layout item if it's already in the initial layout.
    // If it has a `data-grid` property, prefer that over what's in the layout.
    if (exists && g == null) {
      layout.push(cloneLayoutItem(exists));
    } else {
      // Hey, this item has a data-grid property, use it.
      if (g) {
        if (!isProduction) {
          validateLayout([g], "ReactGridLayout.children");
        }
        // FIXME clone not really necessary here
        layout.push(cloneLayoutItem({
          ...g,
          i: child.key
        }));
      } else {
        // Nothing provided: ensure this is added to the bottom
        // FIXME clone not really necessary here
        layout.push(cloneLayoutItem({
          w: 1,
          h: 1,
          x: 0,
          y: bottom(layout),
          i: String(child.key)
        }));
      }
    }
  });

  // Correct the layout.
  const correctedLayout = correctBounds(layout, {
    cols: cols
  });
  return allowOverlap ? correctedLayout : compact(correctedLayout, compactType, cols);
} 

/* All code is re-used from the original method except the 'isLeftShift' related code. */
RGL_UTILS.moveElement = (
  layout,
  l,
  x,
  y,
  isUserAction,
  preventCollision,
  compactType,
  cols,
  isLeftShift // overriden - nitesh
) => {
  // If this is static and not explicitly enabled as draggable,
  // no move is possible, so we can short-circuit this immediately.
  if (l.static && l.isDraggable !== true) return layout;

  // Short-circuit if nothing to do.
  if (l.y === y && l.x === x) return layout;

  console.log(
    `Moving element ${l.i} to [${String(x)},${String(y)}] from [${l.x},${l.y}]`
  );
  const oldX = l.x;
  const oldY = l.y;

  // This is quite a bit faster than extending the object
  if (typeof x === "number") l.x = x;
  if (typeof y === "number") l.y = y;
  l.moved = true;

  // If this collides with anything, move it.
  // When doing this comparison, we have to sort the items we compare with
  // to ensure, in the case of multiple collisions, that we're getting the
  // nearest collision.
  let sorted = sortLayoutItems(layout, compactType);
  const movingUp =
    compactType === "vertical" && typeof y === "number"
      ? oldY >= y
      : compactType === "horizontal" && typeof x === "number"
      ? oldX >= x
      : false;
  if (movingUp) sorted = sorted.reverse();
  const collisions = getAllCollisions(sorted, l);

  // There was a collision; abort
  if (preventCollision && collisions.length) {
    console.log(`Collision prevented on ${l.i}, reverting.`);
    l.x = oldX;
    l.y = oldY;
    l.moved = false;
    return layout;
  }
// overriden - nitesh
 if(isUserAction) {
    isUserAction = false;
    if(oldX === x) isLeftShift = oldY - y <= 0;
    if(oldY === y) isLeftShift = oldX - x <= 0;
 }
  // Move each item that collides away from this element.
  for (let i = 0, len = collisions.length; i < len; i++) {
    const collision = collisions[i];
    console.log(
      `Resolving collision between ${l.i} at [${l.x},${l.y}] and ${collision.i} at [${collision.x},${collision.y}]`
    );

    // Short circuit so we can't infinite loop
    if (collision.moved) continue;

    // Don't move static items - we have to move *this* element away
    if (collision.static) {
      layout = RGL_UTILS.moveElementAwayFromCollision(
        layout,
        collision,
        l,
        isUserAction,
        compactType,
        cols,
        isLeftShift // overriden - nitesh
      );
    } else {
      layout = RGL_UTILS.moveElementAwayFromCollision(
        layout,
        l,
        collision,
        isUserAction,
        compactType,
        cols,
        isLeftShift // overriden - nitesh
      );
    }
  }

  return layout;
}

RGL_UTILS.moveElementAwayFromCollision = function moveElementAwayFromCollision(
  layout,
  collidesWith,
  itemToMove,
  isUserAction,
  compactType,
  cols,
  isLeftShift,
) {
  const compactH = compactType === "horizontal";
  
  const preventCollision = collidesWith.static; // we're already colliding (not for static items)
  const isTileWrapping = isLeftShift
      ?  itemToMove.x - 1 < 0
      :   itemToMove.x + 1 >= cols;
  const deltaShift = isLeftShift ? -1 : 1
  const x = isTileWrapping ? (isLeftShift ? cols - 1 : 0) : itemToMove.x + deltaShift
  const y = isTileWrapping ? itemToMove.y + deltaShift : itemToMove.y

  return moveElement(
    layout,
    itemToMove,
    compactH ? x : undefined,
    y,
    isUserAction,
    preventCollision,
    compactType,
    cols,
    isLeftShift
  );
}
```


**React component**
```
import { useContext, useEffect, useRef, useState } from "react";
import GridLayout, { Layout, WidthProvider, Layouts } from "react-grid-layout";

// IMPORT OVERRIDE FUNCTIONS
// Update path to your App
import  "@/utils/gridUtil";

const WidthProvidedGridLayout = WidthProvider(GridLayout);

const ApplicationsList = () => {

  ....

  return (
    <WidthProvidedGridLayout
      layout={gridState.layout}
      cols={gridState.columns}
      rowHeight={gridState.rowHeight}
      maxRows={gridState.maxRows}
      useCSSTransforms={true}
      onLayoutChange={handleOnLayoutChange}
      preventCollision={false}
      margin={[20, 20]}
      onDragStart={handleOnDragStart}
      onDragStop={handleOnDragStop}
      isResizable={false}
      allowOverlap={false}
      autoSize={true}
      verticalCompact={true}
      compactType="horizontal"
    >
      {(data || []).map(item => (
        <div
          key={item.id}
        >
          ....
        </div>
      ))}
    </WidthProvidedGridLayout>
  );
};
```

**Comment by nitesh619** [comment]
@garciaguillermoa I'm glad this solution worked for you. :)

**Comment by nlevos** [comment]
@garciaguillermoa this works great, but I have a problem with resizing.. Is there a solution for this?

**Comment by shipurjan** [comment]
Hello, I implemented nikesh's solution in my repo, but it only worked for 1x1 cells, so I extended it a little to work with resizing

Here's the demo https://buddy-grid-layout.eu.buddy.cloud/react-grid-layout/examples/0-showcase.html

Here's the code branch https://github.com/shipurjan/buddy-grid-layout/tree/1.4.4-compact-left-dev

To use it either copy the code from the repo above, or get it with npm:

```bash
npm add https://github.com/shipurjan/buddy-grid-layout#1.4.4-compact-left
```

or change `react-grid-layout` version in package.json to 
```json
    "react-grid-layout": "github:shipurjan/buddy-grid-layout#1.4.4-compact-left"
```

and it should work

Be careful, because with this method you're trusting that I won't change the branch, so it's better if you fork it or copy the code yourself, but I don't plan on changing the branch

Some problems at this moment are that dragging is kind of janky, especially at the end of the row, maybe it's possible to fix somehow

**Comment by rlyfun** [comment]
i was about to ditch this library altogether til i found this. thanks <3

**Comment by rlyfun** [comment]
god bless @shipurjan it just works now

**Comment by arthur-lama** [comment]
Thank you so much @shipurjan this saved me! This behavior should be available in the main package as its very common in my opinion

**Comment by Kaustubh355** [comment]
@shipurjan, Thanks for the solution. Both horizontal and vertical scaling working fine. But now I am unable to drag the first item in first row. can you look into it?

**Comment by Cristy94** [comment]
> Hello, I implemented [@nitesh619](https://github.com/nitesh619)'s solution in my repo, but it only worked for 1x1 cells, so I extended it a little to work with resizing
> 
> EDIT: updated from v2 to v3
> 
> Here's the demo https://buddy-grid-layout.eu.buddy.cloud/react-grid-layout/examples/0-showcase.html
> 
> Here's the code branch https://github.com/shipurjan/buddy-grid-layout/tree/1.4.4-compact-left-v3-dev
> 
> To use it either copy the code from the repo above, or get it with npm:
> 
> npm add https://github.com/shipurjan/buddy-grid-layout#1.4.4-compact-left-v3
> or change `react-grid-layout` version in package.json to
> 
>     "react-grid-layout": "github:shipurjan/buddy-grid-layout#1.4.4-compact-left-v3"
> and it should work.
> 
> I made it for my needs, so it doesn't support some things like static elements, so extend it if you like.
> 
> Be careful, because with this method you're trusting that I won't change the branch, so it's better if you fork it or copy the code yourself, but I don't plan on changing the branch
> 
> Branch `1.4.4-compact-left-v3-dev` is for code and branch `1.4.4-compact-left-v3` is for built files (for usage in package.json)
> 
> There might still be some bugs, so try to spot and report them

Thanks for this, it works quite well!

One issue I have, is that now I can not fill all the empty space.
Is there any way to disable the order enforcing? Having a param like maintainOrder={false} should allow to fill up the empty spots:https://github.com/react-grid-layout/react-grid-layout/issues/1154#issuecomment-2656908936

**Comment by nitesh619** [comment]
Wow!! Awesome. @Cristy94 

Thanks for providing the demo link and mentioning me in credit's on top. I am glad I could help here. 

This feature is actually required by dev's at some point in time while working on a project with this library. 

Request @STRML and community to include this as a feature PR.
