### ISSUE TITLE
the total container height is not equal to content height

### ISSUE THREAD

**Issue by vorobievik** [STRML/react-grid-layout#1103]
why if I set the height of the container h: 20, and rowHeight: 1, then the total block height with the class "react-grid-item" is not 200px, but 210 ??

**Comment by madnai** [comment]
I guess because there is a space between the blocks and this space equals 10px

**Comment by pwrUserPro** [comment]
It is probably due to a margin being set on the grid item. Search the issues tab for "margin". This has been discussed many times. https://github.com/STRML/react-grid-layout/issues/978

**Comment by vorobievik** [comment]
> Я думаю, потому что между блоками есть пробел, и это пространство равно 10px



> I guess because there is a space between the blocks and this space equals 10px
if the content is 128 pixels, the total height is 131px )

**Comment by vorobievik** [comment]
> I guess because there is a space between the blocks and this space equals 10px

if the content is 128 pixels, the total height is 131px )

**Comment by vorobievik** [comment]
> It is probably due to a margin being set on the grid item. Search the issues tab for "margin". This has been discussed many times. #978

I do not use other variables to set the height. only number h:20. rowHeight:1
