### ISSUE TITLE
Can we define a maximum height of grid?

### ISSUE THREAD

**Issue by madnai** [STRML/react-grid-layout#1104]
I know we can define a rowHeight and in GridItem limit maxH.

So for example i want grid with maximum height of 300px. I set rowHeight to 100px and maxH to 3.
Thats the only thing I can do.
Now I can resize a gridItem only to 300px height, but unfortunately I can place another gridItem under the first gridItem and in consequences the overall height will be bigger then 300px.
Is there any way to prevent it, so I can have grid with fixed height?

**Comment by akshaygoyal88** [comment]
have you got the answer? or have you managed it anyhow?
I am also struggling to do same.

**Comment by akshaygoyal88** [comment]
I think you can use maxRows https://github.com/STRML/react-grid-layout/issues/30

**Comment by madnai** [comment]
maxRows do not prevent from dragging second element under the first one

**Comment by akshaygoyal88** [comment]
You could likely implement it yourself using the onDragStop and onResizeStop handlers.

**Comment by akshaygoyal88** [comment]
Do you know way how to use callbacks like onDragStart,onResizeStart ?

**Comment by madnai** [comment]
I know how to use them, but you can't stop user from dragging one element below the other.

**Comment by akshaygoyal88** [comment]
I am also struggling in same ploberm
I think if we can get x,y position at dragStop and resizeStop than we can check y offset of layout and stop propogation if y >3.
I will post solution if I could get it done or let me know if you done .

**Comment by madnai** [comment]
do you know go to stop dragging?
I mean when user starts to drag an element, do you know how to stop him from placing an element and  bring the element to the start position?

**Comment by akshaygoyal88** [comment]
you can try below code

```
onDrag = (layout, oldItem, newItem, placeholder, e, element) => {
const grid = document.getElementsByClassName('react-grid-layout')[0];
const translateXMaxValue = grid.offsetWidth - element.offsetWidth;
const translateValues = window.getComputedStyle(element).transform.split(',');
let translateX = parseInt(translateValues[translateValues.length - 2]);
let translateY = 0;
if (translateX > translateXMaxValue) {
translateX = translateXMaxValue;
}
if (translateX < 0) {
translateX = 0;
}
element.style.transform = translate(${translateX}px, ${translateY}px);
};
```

**Comment by akshaygoyal88** [comment]
@madnai Have you figure it out?

**Comment by madnai** [comment]
> No but you can try below code
> I am also trying to achieve the same but did not get success yet
> 
> ```
> onDrag = (layout, oldItem, newItem, placeholder, e, element) => {
> const grid = document.getElementsByClassName('react-grid-layout')[0];
> const translateXMaxValue = grid.offsetWidth - element.offsetWidth;
> const translateValues = window.getComputedStyle(element).transform.split(',');
> let translateX = parseInt(translateValues[translateValues.length - 2]);
> let translateY = 0;
> if (translateX > translateXMaxValue) {
> translateX = translateXMaxValue;
> }
> if (translateX < 0) {
> translateX = 0;
> }
> element.style.transform = translate(${translateX}px, ${translateY}px);
> };
> ```

its not working :(

**Comment by CefBoud** [comment]
Hello, 
Reviving this old thread. I ran into the need of setting a maximum height for the grid. I found a hacky solution that worked for me but it still hasn't been well tested. 

To ensure that the grid doesn't exceed the predefined max value, the idea is as follows :

  on `onResizeStart `and `onDragStart `callbacks, we save the current layouts (supposed to respect the height limit) somewhere. 
  Once the resize or drag is done, the `onLayoutChange` is called. At its end, we call `resetOldLayoutIfNewHeightTooBig `  which will do the following:
  get the new grid height which is computed automatically if autoSize is true (this is the default currently)
  if the new  height exceeds the predefined max, we reset the layouts to the value we saved in `onResizeStart `or `onDragStart `i.e. the one that respects the height limit.

This of course requires the use of some sort of state to save the layouts for the methods `setLayoutsInState` and `getLayoutsFromState` using React state or Redux for instance.

`this.maxAllowedGridHeight` is to be defined based on the max height requirement.

 I noticed that it is necessary to let the _layouts_ state change to the new forbidden value before resetting the old correct one.


```js


  onLayoutChange(currentLayout, allLayouts) {
    this.setLayoutsInState(allLayouts);
    this.resetOldLayoutIfNewHeightTooBig();
  }
  resetOldLayoutIfNewHeightTooBig = () => {
    const newHeight = document.querySelector(".react-grid-layout").offsetHeight;
    if (newHeight > this.maxAllowedGridHeight) {
      this.setLayoutsInState( this.lastLayoutsThatRespectMaxHeight );
    }
  };

  saveCurrentLayouts = (layout, oldItem, newItem, placeholder, e, element) => {
    this.lastLayoutsThatRespectMaxHeight= { ...getLayoutsFromState() };
  };

  render() {
    var layouts = getLayoutsFromState();
    return (
      <ResponsiveGridLayout 
           className="layout" layouts={layouts}
           breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
           cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}   
           onResizeStart={this.saveCurrentLayouts}
           onDragStart={this.saveCurrentLayouts}>
      {this.generateGridItems()}
      </ResponsiveGridLayout>
    )
  }

```

**Comment by spxis** [comment]
> Hello, Reviving this old thread. I ran into the need of setting a maximum height for the grid. I found a hacky solution that worked for me but it still hasn't been well tested.
> 
> To ensure that the grid doesn't exceed the predefined max value, the idea is as follows :
> 
> on `onResizeStart `and `onDragStart `callbacks, we save the current layouts (supposed to respect the height limit) somewhere. Once the resize or drag is done, the `onLayoutChange` is called. At its end, we call `resetOldLayoutIfNewHeightTooBig ` which will do the following: get the new grid height which is computed automatically if autoSize is true (this is the default currently) if the new height exceeds the predefined max, we reset the layouts to the value we saved in `onResizeStart `or `onDragStart `i.e. the one that respects the height limit.
> 
> This of course requires the use of some sort of state to save the layouts for the methods `setLayoutsInState` and `getLayoutsFromState` using React state or Redux for instance.
> 
> `this.maxAllowedGridHeight` is to be defined based on the max height requirement.
> 
> I noticed that it is necessary to let the _layouts_ state change to the new forbidden value before resetting the old correct one.
> 
> ```js
>   onLayoutChange(currentLayout, allLayouts) {
>     this.setLayoutsInState(allLayouts);
>     this.resetOldLayoutIfNewHeightTooBig();
>   }
>   resetOldLayoutIfNewHeightTooBig = () => {
>     const newHeight = document.querySelector(".react-grid-layout").offsetHeight;
>     if (newHeight > this.maxAllowedGridHeight) {
>       this.setLayoutsInState( this.lastLayoutsThatRespectMaxHeight );
>     }
>   };
> 
>   saveCurrentLayouts = (layout, oldItem, newItem, placeholder, e, element) => {
>     this.lastLayoutsThatRespectMaxHeight= { ...getLayoutsFromState() };
>   };
> 
>   render() {
>     var layouts = getLayoutsFromState();
>     return (
>       <ResponsiveGridLayout 
>            className="layout" layouts={layouts}
>            breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
>            cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}   
>            onResizeStart={this.saveCurrentLayouts}
>            onDragStart={this.saveCurrentLayouts}>
>       {this.generateGridItems()}
>       </ResponsiveGridLayout>
>     )
>   }
> ```

Curious how this has worked for everyone? I see 9 likes, and curious if there was any implementation based on this... cheers!

**Comment by anantmittal** [comment]
@spxis It works.

**Comment by yewcm123** [comment]
Just commenting here in case it can help someone. This is what I did referring to @CefBoud solution. I am using functional component in my work so I converted it to functional component. Just sharing it here in case anyone wants to refer. I hope it helps.

`const ResponsiveGridLayout = WidthProvider(Responsive);

const maxAllowedGridHeight = 6;

const DashboardComp = (props: any) => {
    const [currentLayouts, setCurrentLayouts] = useState<Layout[]>([
        { i: 'item1', x: 0, y: 0, w: 2, h: 3, minW: 2, minH: 3 },
        { i: ''item2', x: 2, y: 0, w: 3, h: 4, minW: 2, minH: 3 },
        { i: ''item3', x: 5, y: 1, w: 2, h: 3, minW: 2, minH: 3 }
    ]);
    const lastLayoutsThatRespectMaxHeight = useRef<Layout[]>([]);

    const saveCurrentLayouts = (layout: Layout[], oldItem: Layout, newItem: Layout, placeholder: Layout, e: MouseEvent, element: HTMLElement) => {
        lastLayoutsThatRespectMaxHeight.current = layout;
    };

    const resetOldLayoutIfNewHeightTooBig = async (currentLayout: ReactGridLayout.Layout[]) => {
//FInding all any elements that exceed max height
        currentLayout.forEach((element) => {
            if (element.y + element.h > maxAllowedGridHeight) {
                setCurrentLayouts(lastLayoutsThatRespectMaxHeight.current);
                return true;
            }
        });
        return false;
    };

    useEffect(() => {
        //Delay is set here as sometimes if the item is dragged too fast, it does not reset to the old layout even if it exceeds the max height
        setTimeout(() => {
            resetOldLayoutIfNewHeightTooBig(currentLayouts);
        }, 50);
    }, [currentLayouts]);

    return (
        <>
            <ResponsiveGridLayout
                className="layout"
                layouts={{ lg: currentLayouts }}
                breakpoints={{ lg: 768, sm: 0 }}
                cols={{ lg: 12, sm: 4 }}
                rowHeight={80}
                onDragStart={saveCurrentLayouts}
                onResizeStart={saveCurrentLayouts}
                onLayoutChange={(currentLayout: ReactGridLayout.Layout[], allLayouts: ReactGridLayout.Layouts) => {
                    setCurrentLayouts(currentLayout);
                }}
                compactType={null}
            >
               
                    <div key={'item1}> </div>
                    <div key={'item2}> </div>
                   <div key={'item3}> </div>
                ))}
            </ResponsiveGridLayout>
        </>
    );
};`

**Comment by chris-godinho** [comment]
For what's worth, there's a "maxRows" prop now that does the job.

**Comment by parth-chovatiya** [comment]
But it will not work, when we drop from outside.

**Comment by bhamlin98** [comment]
> For what's worth, there's a "maxRows" prop now that does the job.

The OP mentioned maxRows, it does not prevent the user from stacking widgets that would increase the size of the grid.

For example, if there is a widget with a height of 5 cells and another with 3, but the maxRows is 5, the user is not able to resize widgets greater than 5, but they can take the size-3 and move it above or below the size-5 widget and therefore increasing the height of the grid.
