### ISSUE TITLE
onDrop has no event property

### ISSUE THREAD

**Issue by egorguscha** [STRML/react-grid-layout#1112]
Just compare code from a repository [this](https://github.com/STRML/react-grid-layout/blob/master/lib/ReactGridLayout.jsx#L805) and what npm provide me below, therefore i can't use `dataTransfer`

``` js
   _defineProperty(_assertThisInitialized(_this), "onDrop", function () {
      var droppingItem = _this.props.droppingItem;
      var layout = _this.state.layout;

      var _ref2 = layout.find(function (l) {
        return l.i === droppingItem.i;
      }) || {},
          x = _ref2.x,
          y = _ref2.y,
          w = _ref2.w,
          h = _ref2.h; // reset gragEnter counter on drop


      _this.dragEnterCounter = 0;

      _this.removeDroppingPlaceholder();

      _this.props.onDrop({
        x: x,
        y: y,
        w: w,
        h: h
      });
    });```

**Comment by n-dragon** [comment]
waiting for the release!

**Comment by pitops** [comment]
i hope its coming soon - the fix its been like 2 months in master branch

**Comment by jordanparker6** [comment]
I can see that this has been fixed in the GitHub repo but the npm pull doesn't have the fix?

Is it just awaiting an update to the npm repo?

**Comment by n-dragon** [comment]
@jordanparker6 waiting for a release.
however you can pull directly the master branch with npm:
https://docs.npmjs.com/cli/install

**Comment by jordanparker6** [comment]
@n-dragon Do you have to then build the repo?

**Comment by pitops** [comment]
if you want something temporary I have made a fork,

https://github.com/pitops/react-grid-layout/commit/c985e62470b8b3d9c7d1a7d95579c5fb68804365

**Comment by lbtien1990** [comment]
Waiting for release. It's 4 month ago
