### ISSUE TITLE
Drag and drop issues on firefox (react-grid-layout)

### ISSUE THREAD

**Issue by ngovanbon16** [STRML/react-grid-layout#1114]
I found an error using the new drag and drop feature on firefox. Sometimes react-grid-layout does not catch the drop event when I used on firefox. You can check this issue by opening the link https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html on firefox.
Demo Video: https://youtu.be/qVh2ivKYyQk

**Comment by sterzhakov** [comment]
same problem!

**Comment by jandufek** [comment]
We have the same problem
