### ISSUE TITLE
Can't access grid layout ref in responsive grid layout

### ISSUE THREAD

**Issue by eric-burel** [STRML/react-grid-layout#1116]
Hi,

The `ResponsiveReactGridLayout` do not allow to forward a ref to the underlying `ReactGridLayout`.
This prevents keeping track of the number of columns and size of the layout for example.

To give a use case, I wan't to display a placeholder grid behind the layout during edition, so I need to know precisely it's size. I could compute it from a parent component, but the most straightforward solution is using a "ref" to access the `rowHeight`, `cols` and `width` props.

I've implemented a working version for RRGL 1.16 but I should probably open a PR for new versions with forwardRef.

I will need to implement this sooner or later anyway when I update my project to React 16.

Thanks again for your work on RRGL, it's been running strong for years in our project and provides an excellent user experience.

**Comment by eric-burel** [comment]
Stalebot is a bit too eager to close issues btw

**Comment by alekseyBatuhtin** [comment]
The same issue.

@eric-burel Did you solve this problem?
