### ISSUE TITLE
Implementing Multiple selection and multi Item drag/resize

### ISSUE THREAD

**Issue by storylens** [STRML/react-grid-layout#1118]
Hi there,

I am trying to implement a multi selection feature for RGL. However, I believe there isn't an easy way to do that without making relatively significant changes to the package.  Alternatively, nested Grid would work, but I'd have to generate new absolute grid item values for the child grid and then convert it back after deselection.

Before I move into that direction, can anybody suggest anything else? We'd love to have your input.

**Comment by eric-burel** [comment]
Hi, I've opened a similar issue, I think I am trying to implement the same thing.
It seems mostly doable, except I did not manage to force a layout during render. The idea was to preview the movement of a whole group of items.
See https://github.com/STRML/react-grid-layout/issues/1132 for more details.
