### ISSUE TITLE
Child shifting from position on mousedown event.

### ISSUE THREAD

**Issue by ramsgei** [STRML/react-grid-layout#1121]
Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

Please use the [CodeSandbox Template](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to demonstrate your bug. It is much easier for us to help you if you do.
[screenshot.zip](https://github.com/STRML/react-grid-layout/files/4052850/screenshot.zip)

**Comment by carceri** [comment]
Try to remove paddings/margins from container that wrapping `<ResponsiveGridLayout />`
Or wrap it with div block with `position: relative` style:
```
      <div style={{ position: 'relative' }}>
        <ResponsiveGridLayout
          breakpoints={{ ... }}
          cols={{ ... }}
          ...
        >
          {children}
        </ResponsiveGridLayout>
      </div>
```

At least this works for me

**Comment by ramsgei** [comment]
Thanks  for your support, actually is issue was related with transformation. i have find the way to fix this.
