### ISSUE TITLE
Can't scroll page on mobie view.

### ISSUE THREAD

**Issue by carceri** [STRML/react-grid-layout#1126]
The problem is - I can drag blocks on special button (drag-handle). And i can scroll page by clicking on empty space. BUT i **can't** scroll page by clicking on blocks.

Demonstration: https://imgur.com/vusO6OH

You can try this with mobile view in chrome https://chk75.csb.app/

codesandbox: https://codesandbox.io/s/adoring-chebyshev-chk75

p.s.
`isDraggable={false}` on `ResponsiveReactGridLayout` will not fix this problem for me

**Comment by yogesh45** [comment]
I am also having this problem in gridlayout

**Comment by yogesh45** [comment]
Just add the static classname in the gridlayout div, make isDraggable flag to **false**

**Comment by carceri** [comment]
I was using `isDragging={false}` on mobile view to prevent this bug. But in 0.18+ it doesn't work anymore.
I mean, i cannot scroll on mobile at all. 😕

**Comment by Whyseverythingtaken** [comment]
This seems to happen because of  `touch-action: none;` on `.react-grid-item` class.

I fixed it by adding the following css

```
.react-grid-item {
  touch-action: auto !important;
}
```

This may not be the solution for you if you use the drag and drop feature

**Comment by lazarnikolic1983** [comment]
> .react-grid-item {
>   touch-action: auto !important;
> }

This solved the issue for me. Thank you.
