### ISSUE TITLE
Request feature: compactFunc

### ISSUE THREAD

**Issue by amrsalama** [STRML/react-grid-layout#1130]
There is `compactType` prop that supports only `vertical` or `horizontal` compact. But sometime we need both of them or even a custom compact way. For example as described in #1100.

So it would be helpful if we have `compactFunc` that describe how compaction should work.

**Comment by nitesh619** [comment]
@amrsalama 
Implementation for feature request can be found here: https://github.com/STRML/react-grid-layout/issues/1100#issuecomment-583741129

If possible, please create a PR with test cases.
cc @STRML

**Comment by melloc01** [comment]
+1 on this one, this is a good feature to have
