### ISSUE TITLE
Programmatically adding static to state does not update to static

### ISSUE THREAD

**Issue by dsiddharth2** [STRML/react-grid-layout#1131]
I am trying to make an element static on click of a button, similar to how the element is deleted by updating the state.

Following is the code,
[Link](https://codesandbox.io/s/agitated-keller-kkgur).

But its does not work.

Any help would be appreciated.

**Comment by phowat** [comment]
Encountered the same issue. As a workaround, I changed the key of the element when changing the static property and it updates correctly.
