### ISSUE TITLE
Applying a temporary offset to some items when one item is dragged

### ISSUE THREAD

**Issue by eric-burel** [STRML/react-grid-layout#1132]
Hi,
I am trying to implement a grouping feature. a few items should move together when one item of the group is moved.
 Basically, I am dragging item "A", and I want to move item "B" and "C" accordingly.

I've managed to compute the final position of all widgets in the `onDragStop` callback.
However I did not yet manage to implement a temporary preview during the `onDrag` events. I can compute the correct positions, but not display them.

If I update the layout manually, it will trigger `onLayoutChange` events, which in turn trigger a save of the layout in my system. I've tried to apply `data-grid` props instead, with no luck. The items of the group do not move at all. Maybe I could just ignore layoutChange events and just listen for resize/drag stop my data (not tested yet)?

I may have missed something, do you think it is currently doable to temporarily move/offset some items without actually changing the layout?

Edit: I've managed to cancel `onLayoutChange` when I am dragging, but updating the `layouts` manually props seems to have no effect during the drag.

Edit2: might related to [`activeDrag` state](https://github.com/STRML/react-grid-layout/blob/master/lib/ReactGridLayout.jsx#L328). It seems to prevent derived state computation during drag and drop, so I can't force a new layout. This condition might be too agressive and may prevent legitimate update.
Edit 3: actually I am using an old version that did not check on `activeDrag`, so I still don't understand why updating the `layouts` prop does nothing.

**Comment by eric-burel** [comment]
Just a thought but could we imagine a "Recipes.md" page where we could contribute to help answering to questions like "how to track the breakpoint", "how to offset an item", "how to change the initial size of an item", "how to move a multiple items at once" etc.?

We are implementing advanced use cases with React Grid Layout, and sharing our progresses on such questions may help reducing the amount of issues. Some feature do not deserve a PR but are not trivial to implement either, documentation could be the right intermediate.

**Comment by arigon** [comment]
Has there been any progress on this feature yet? I was looking for the same function (grouping widgets and dragging them).
