### ISSUE TITLE
Add support for canDrop prop ala react-dnd

### ISSUE THREAD

**Issue by mateja176** [STRML/react-grid-layout#1139]
Use it to specify whether the drop target is able to accept the item. If you want to always allow it, just omit this method. Specifying it is handy if you'd like to disable dropping based on some predicate over propsor monitor.getItem(). Note: You may not call monitor.canDrop()inside this method.

Source [react-dnd](https://react-dnd.github.io/react-dnd/docs/api/use-drop)

**Comment by mateja176** [comment]
One workaround is to determine if a drop is allowed in retrospective, in `onDragStop` so that you undo a drop which should not be allowed. This is far from optimal, hence I'd love to hear more ideas.

**Comment by pohsiu** [comment]
@mateja176 would you mind to share your solution about this ?
