### ISSUE TITLE
Input lose focus inside grid 

### ISSUE THREAD

**Issue by MohanadI** [STRML/react-grid-layout#1148]
Hello , 

Input inside grid has multiple bugs : 
- Losing focus 
- select text will do drag-drop 

[Demo](https://codesandbox.io/s/react-grid-layout-bug-with-text-area-me0z8)

**Comment by ayushjain94** [comment]
I am also facing the same issue. Anyone can help on how to resolve this?

**Comment by MohanadI** [comment]
@ayushjain94  I solved the problem using draggableHandle
use custom icon for moving the div.

`<ResponsiveGridLayout draggableHandle='.MyDragHandleClassName' ... >
</ResponsiveGridLayout >

<div className={'MyDragHandleClassName'}>
    <icon ...>
</div>
`
