### ISSUE TITLE
PureComponent loading state

### ISSUE THREAD

**Issue by apuntovanini** [STRML/react-grid-layout#1150]
Hi, with the newest 0.18.0 version my dashboard doesn't work anymore: I load data asyncronously, and pass down a loaded prop to my dashlets. While loading blocks in react-grid-layout show a loading spinner, then (in previous versions) when receiving a new `loaded=true` props, they render their content. Now it's not working anymore and I think it may be related to PureComponent. Do you have any clue on how to deal with this? I'll explore as well and write down any insights I may encounter
Thanks
Andrea

**Comment by STRML** [comment]
Thanks, fixed in 0.18.2, see https://github.com/STRML/react-grid-layout/blob/master/CHANGELOG.md#0182-feb-26-2020 for more detail.
