### ISSUE TITLE
Drag from outside is missing placeholder

### ISSUE THREAD

**Issue by motherwaym** [STRML/react-grid-layout#1152]
Run /examples/15-drag-from-outside.html using version 0.18.x and note that the placeholder doesn't show up at all like it does in v0.17: https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html

**Comment by grahammcculloch** [comment]
I'm also experiencing this problem.

**Comment by violabg** [comment]
me too

**Comment by Hannah17Hui** [comment]
me too

**Comment by Anwardo** [comment]
I have the same issue. This also means that the rest of the layout doesn't shift in response to dragging it over items.

**Comment by paul-sachs** [comment]
Also running into this, it seems to me that this [line](https://github.com/STRML/react-grid-layout/issues/1152) should triggering a update to state (probably activeDrag or something like it) but instead, it just modifies a local variable, which doesn't trigger any render. I might dig in later to try to understand what the appropriate response should be, if i get some time.

**Comment by paul-sachs** [comment]
I would assume these changes are due to the performance improvements in 0.18, so I'd like to figure out a way to maintain performance but also get the placeholder working.

**Comment by paul-sachs** [comment]
I've submitted a PR to fix this. @STRML let me know if there are any changes, I know this issue is blocking me from using this library entirely.

**Comment by paul-sachs** [comment]
@STRML any idea when this might be released? Just want to know if I should fall back to 0.7 or wait for the newest 0.8.

**Comment by STRML** [comment]
Good call. Released `0.18.3`
