### ISSUE TITLE
onDrop event is not invoking on ResponsiveReactGridLayout

### ISSUE THREAD

**Issue by hmudimi** [STRML/react-grid-layout#1153]
I am new to react-grid-layout, To know more about the project I have created a sample example with drag and drop. I have created a sandbox https://codesandbox.io/s/old-star-y3xb1. 

I have gone through the example in link  https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html, here drag and drop is working fine. While I am trying to use the same, the onDrop event is not firing (https://codesandbox.io/s/old-star-y3xb1).

**Comment by ImAbdullahJan** [comment]
Update your packages to latest:
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-grid-layout": "0.18.2",

and then test again.

**Comment by hmudimi** [comment]
Thanks @ImAbdullahJan 
I have tried with the versions you suggested, Here onDrop event working fine but y value is always 0. Here it's considering only the x & y values of the entry-stage after that x & y values not changing. check URL https://codesandbox.io/s/old-star-y3xb1

So I tried react-grid-layout with 0.17.0 version, It's working as expected.

**Comment by cs-miller** [comment]
yeah, there is an interesting problem where things work on 0.17.0, but you don't receive the event in onDrop, and in 0.18.2 you receive the event, but x and y are wrong and there is no placeholder element.

**Comment by neilbryson** [comment]
It works properly on 0.17.1 too. 
I noticed on 0.18.2, onDrag and onDragStart do not get triggered when dragging an element from the outside. No placeholder and wrong coordinates, same with cs-miller's experience.

**Comment by cedeber** [comment]
Fixed in 0.18.3.

**Comment by hmudimi** [comment]
> Fixed in 0.18.3.

Yes, now it's working as expected.
