### ISSUE TITLE
ReactGridLayout mutates props on widget resize

### ISSUE THREAD

**Issue by darekkay** [STRML/react-grid-layout#1155]
When adding a new item to the dashboard and resizing it immediately, props will be mutated [here](https://github.com/STRML/react-grid-layout/blob/master/lib/ReactGridLayout.jsx#L401). When using a library like [immer](https://github.com/immerjs/immer), the app will crash with the following exception:

```
Uncaught TypeError: Cannot assign to read only property 'w' of object '#<Object>'
  at ReactGridLayout.onResize (ReactGridLayout.js:614)
```

This is very similar to #1063 , but it's affecting another part of the code base (and is triggered by a different user action).

I will have a look into this and provide another fix.

**Comment by darekkay** [comment]
I've created a PR with a fix: https://github.com/STRML/react-grid-layout/pull/1156

**Comment by darekkay** [comment]
The issue isn't stale. I'll try to look back into my PR in the next days.

**Comment by DWboutin** [comment]
Any news on this?

**Comment by jaguardo** [comment]
Still an issue.
