### ISSUE TITLE
React does not recognize the `transformScale` prop on a DOM element

### ISSUE THREAD

**Issue by nodeworks** [STRML/react-grid-layout#1159]
Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

Getting an error about transformScale:

```
Warning: React does not recognize the `transformScale` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `transformscale` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

![Screen Shot 2020-03-05 at 8 52 21 PM](https://user-images.githubusercontent.com/5272855/76042646-5bfca700-5f23-11ea-8411-9cfde5a8eb6b.png)

I don't have anything special under ResponsiveGridLayout, just a div:

```
<ResponsiveGridLayout
  isDroppable={false}
  draggableHandle='.draggable-item'
  draggableCancel='.no-drag'
  onWidthChange={onWidthChange}
  onBreakpointChange={onBreakpointChange}
  margin={[16, 16]}
  containerPadding={[0, 0]}
  rowHeight={20}
  layouts={buildModeLayouts || {}}  
>
  <div
    key='test'
    data-grid={{
      x: element.x,
      y: element.y,
      w: element.w,
      h: element.h
    }} 
  >
     ...
  </div>
</ResponsiveGridLayout>
```

**Comment by nguymin4** [comment]
This is related to issue yarn.lock file in your code base because it still uses the old react-resizable 1.9 which will pass `transformScale` to DOM element.

A work around is re-generate yarn.lock but I don't like that idea, so I created the PR to fix this issue.
