### ISSUE TITLE
Demos not working in IE11

### ISSUE THREAD

**Issue by ProsperDevelopment** [STRML/react-grid-layout#1160]
I can't get none of the demos to load properly in IE 11.

Reproduce steps

1) Go to https://strml.github.io/react-grid-layout/examples/0-showcase.htm
2) Try to load any of the demo page

Result:
The header of the demo shows, but the actual demo doesn't load.
In the console I get an error message

[![Screenshot from 2020-03-06 13-26-25](https://user-images.githubusercontent.com/6404440/76084412-1d60fe00-5fb0-11ea-8ad4-8f2dda0a6a01.png)
](url)

**Comment by paul-sachs** [comment]
Probably missing the IE11 polyfill for Array.includes

**Comment by STRML** [comment]
The demos were out of date and still used `String#includes` from 0.16.x, I have updated them.

**Comment by eqqe** [comment]
The demo at
https://strml.github.io/react-grid-layout/examples/0-showcase.html
does not work for IE11
The error is:
```Promise is undefined```
