### ISSUE TITLE
Drag from outside doesn't work in Firefox 74

### ISSUE THREAD

**Issue by paul-sachs** [STRML/react-grid-layout#1175]
Firefox: 74

URL: https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html

Try to drag the external element onto the layout. If you place it on top of another object and release, nothing happens. If you drag to the background between the elements (gutter) it triggers properly.

**Comment by gaurav-pantelwar** [comment]
Can be fixed if this pull request get merged [#1053](https://github.com/STRML/react-grid-layout/pull/1053)

**Comment by akshaygoyal88** [comment]
How can we access source element attr onDrop?
