### ISSUE TITLE
Tiles not snapping

### ISSUE THREAD

**Issue by polskais1** [STRML/react-grid-layout#118]
Hey there, I'm trying to render a simple grid following the guidelines from the demos and cannot seem to get the tiles to render properly. They are stacking on top of each other and not snapping to the grid at all. If I disable draggability the tiles snap to the correct spots just fine. Here's my code. React-rails is calling the render function.

```javascript
var ResponsiveReactGridLayout = ReactGridLayout.Responsive;
var PureRenderMixin = React.addons.PureRenderMixin;

var BooksContainer = React.createClass({
  mixins: [PureRenderMixin],

  propTypes: {
    onLayoutChange: React.PropTypes.func.isRequired
  },

  getDefaultProps() {
    return {
      className: "layout",
      rowHeight: 30,
      cols: 12,
      isResizable: false,
      //isDraggable: false,
      rowHeight: 20
    }
  },

  getInitialState() {
    var layout = this.generateLayout();
    return {layout: layout};
  },

  generateLayout() {
    return this.props.books.map(function(book, i) {
      return {x: i * 2 % 12, y: Math.floor(i / 6) * i, w: 2, h: 2, i: i};
    });
  },

  generateDOM() {
    return this.props.books.map(function(book, i) {
      return (<div key={i}><span className="text">{book.name}</span></div>);
    });
  },

  render: function() {
    var bookNodes = this.generateDOM();
    return (
      <ReactGridLayout layout={this.state.layout} onLayoutChange={this.onLayoutChange} {...this.props}>
        {this.generateDOM()}
      </ReactGridLayout>
    );
  }
});
```

**Comment by fwextensions** [comment]
I have the same problem.  The examples look nice, but trying to figure out how they're actually built is impossible, given all the Webpack magic.

**Comment by STRML** [comment]
This was an issue while `0.10` was still in flux. Please reopen if you are still experiencing it with the latest version.

**Comment by ssolders** [comment]
I'm experiencing this problem, both with the latest version (0.11.0) and the previous (0.10.11).
Got it to render out according to my layout but it requires me to set a width on the ResponsiveReactGridLayout-component, something that isn't required according to any examples I've seen. If I don't set a with, the children get stacked on top of each other in the top left corner.

But I still can't get my children to be draggable or Resizable.

My code: 
```
`<ResponsiveReactGridLayout
         width={this.state.windowWidth}
         isResizable={true}
         isDraggable={true}
         useCSSTransforms={true}
         className='layout'
         layouts={generateLayouts(inputs.length)}
         margin={[20, 20]}
         breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
         cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}>

         { hubInputs }
</ResponsiveReactGridLayout>`
```

Children created and stored in hubInputs:

```
<Card key={this.props.key} initiallyExpanded={true} rounded={true} className={className} style={style}>
    <CardHeader title={input.sensor.name} subtitle="My subtitle" actAsExpander={false} showExpandableButton={false} />
     <CardText expandable={false}>
          <div>
             <ChartComponent data={chartData} options={CHART_OPTIONS} width='800px' height='300px'/>
          </div>
     </CardText>
</Card>`

```

**Comment by STRML** [comment]
Hey @ssolders,  re: width, this used to be built-in to RGL, but we now allow providing a width yourself, or using the `WidthProvider` to automatically get it. To use it: ([Example](https://github.com/STRML/react-grid-layout/blob/master/test/examples/0-showcase.jsx))

```javascript
var WidthProvider = require('react-grid-layout').WidthProvider;
var Responsive = require('react-grid-layout').Responsive;
ResponsiveReactGridLayout = WidthProvider(Responsive);
```

If you're having issues with them not being draggable or resizable, make sure that you're including the CSS properly, and check your console for errors.

**Comment by ssolders** [comment]
Okay thank you for the Width-fix, although the snippet above threw the following error:

> `Module build failed: SyntaxError: /Users/userName/Documents/Development/src/components/views/HubView.js: "ResponsiveReactGridLayout" is read-only`

Had to store it in a variable and mutate that one with WidthProvider for it to work.

```
import { Responsive as ResponsiveReactGridLayout } from 'react-grid-layout';
import { WidthProvider } from 'react-grid-layout';

var ResponsiveGrid = ResponsiveReactGridLayout;
ResponsiveGrid = WidthProvider(ResponsiveGrid);
```

I don't have any errors in console. 
Guessing you're referring to the style.css in the module. Do I need to do something for it to be included?

**Comment by STRML** [comment]
Yeah, if you're using `import` statements it's slightly different.

As for the styles, you need to copy/paste it into your own styles - much like any other lib, there's still no good story for automatically including styles.

**Comment by ssolders** [comment]
Okay thanks!
Great respons time :)

**Comment by ssolders** [comment]
Okay, so my real problem was how the child-components were created and inserted.

In the same file that I included my **ResponsiveReactGridLayout**, I had a loop that added instances of my child components into a variable. ChildComponent is a separate component in a different file.
```
const children = listOfValues.map((value, index)=> {
   return (
        <ChildComponent key={index} value={value} index={index} />
    );});
```

I then inserted them in ResponsiveReactGridLayout by

```
<ResponsiveReactGridLayout isResizable={true} isDraggable={true} ...props >
   {children}
</ResponsiveReactGridLayout>
```

By this approach, my child components were not draggable nor resizable.

In order to achieve this I had to wrap each instance of <HubInputDisplay /> in an element that carried a key, like this:

```
const children = listOfValues.map((value, index)=> {
   return (
       <div key={index}>
            <ChildComponent value={value} index={index} />
       </div>
    );});
```

**Comment by STRML** [comment]
Ah - the issue is that `<GridItem>` applies styles and classnames to whatever it's wrapping. If the component it's wrapping silently ignores the `style` and `className` property. it will break.

Wrapping in a `<div>` is the correct approach.

**Comment by ssolders** [comment]
Ok! :) Thanks for your help anyway!
