### ISSUE TITLE
Drop from outside doesn't work on iPad

### ISSUE THREAD

**Issue by josesaranda** [STRML/react-grid-layout#1180]
At first, thanks for your support and your incredible work in this awesome library...

The problem (maybe bug):

onDragStart and onDragStop events currently is not fired on iPad under iOS 13.3 and this functionality doesn't work.

It considers like a bug? I think so.

What can I do?

Thanks in advance.

**Comment by akshaygoyal88** [comment]
How can we access source element attr onDrop?

**Comment by josesaranda** [comment]
You can find more about data transfer [here](https://developer.mozilla.org/es/docs/Web/API/DataTransfer)

```Typescript
onDragStart={e => {
          e.stopPropagation();
          this.dragImage = this.createDragPreview(this.props.text);
          // you need line below in your droppable outside element
          e.dataTransfer.setData("text/plain", JSON.stringify(this.props.transfer));
          e.dataTransfer.setDragImage(this.dragImage,0,0);
        }}
onDragEnd={e => {
          e.stopPropagation();
          e.dataTransfer.setData("text/plain", "");
          e.dataTransfer.clearData("text/plain");
          if(this.dragImage)
            document.body.removeChild(this.dragImage);
}}
```
And then retrieve data in onDrop property

```Typescript
onDrop={(value : any) => {
    // TODO on drop
    let drop : any = {
      x : value.x,
      y : value.y,
      h : value.h,
      w : value.w,
      // this is what you need
      transfer : JSON.parse(value.e.dataTransfer.getData('text/plain'))
    }
}}
```

Hope it goes well for you. But the main problem of this topic continues working bad, I mean, drag from outside doesn't work on ipad! Please someone can help me?

**Comment by josesaranda** [comment]
In addition I tried to use a Polyfill that handles this event properly on iPad but it seems to produce another error... It can retrieve x, y, h, w after apply Polyfill.

Someone solve this with another solution? Maybe this awesome library must consider fix this on iPad?

**Comment by josesaranda** [comment]
Someone could say something about?

**Comment by josesaranda** [comment]
Nobody with the same issue?

**Comment by josesaranda** [comment]
I can't believe nobody has the same problem here! Please @STRML say something about...

**Comment by akshaygoyal88** [comment]
Your problem is that the "drag n' drop" feature native in HTML5 (with a bit of JavaScript) is not supported by most mobile browsers. Click [here](https://caniuse.com/#feat=dragndrop) for a list of what is supported.

I suggest using an alternative approach that supports all mobile browsers. See this link with more explanation: https://medium.com/@deepakkadarivel/drag-and-drop-dnd-for-mobile-browsers-fc9bcd1ad3c5

**Comment by josesaranda** [comment]
> Your problem is that the "drag n' drop" feature native in HTML5 (with a bit of JavaScript) is not supported by most mobile browsers. Click [here](https://caniuse.com/#feat=dragndrop) for a list of what is supported.
> 
> I suggest using an alternative approach that supports all mobile browsers. See this link with more explanation: https://medium.com/@deepakkadarivel/drag-and-drop-dnd-for-mobile-browsers-fc9bcd1ad3c5

Thanks for your response, but...

This feature would be part of this library because it implements onDrop Prop which actually takes and transform dataTransfer property from a draggable HTML5 element. That means is the only way to reorganize the grid. If you use an external library to handle drag and drop, from outside, the grit will not reorganize according where you dropped the new element.

I suggest this library may support drag and drop functionality to all browsers. Or reimplement his onDrop Prop in order to handle dropped element position and reorganize grid.

**Comment by STRML** [comment]
You are welcome to submit a PR if this is something you would like.

**Comment by phongtran-uit** [comment]
same issue :( not working in mobile

**Comment by phucluke** [comment]
I'm having same issue. I have applied a Polyfill here https://github.com/timruffles/mobile-drag-drop but iit's not compatible with this react grid library. @josesaranda did you overcome it?

**Comment by polyrain** [comment]
> > Your problem is that the "drag n' drop" feature native in HTML5 (with a bit of JavaScript) is not supported by most mobile browsers. Click [here](https://caniuse.com/#feat=dragndrop) for a list of what is supported.
> > I suggest using an alternative approach that supports all mobile browsers. See this link with more explanation: https://medium.com/@deepakkadarivel/drag-and-drop-dnd-for-mobile-browsers-fc9bcd1ad3c5
> 
> Thanks for your response, but...
> 
> This feature it would be part of this library because it implements onDrop Prop which actually takes and transform dataTransfer property from a draggable HTML5 element. That means is the only way to reorganize the grid. If you use an external library to handle drag and drop, from outside, the grid will not reorganize according where you dropped the new element.
> 
> I suggest this library must support drag and drop functionality to all browsers. Or reimplement his onDrop Prop in order to handle dropped element position and reorganize grid without use dataTransfer.

How large of a task would this realistically be to reimplement onDrop to not use dataTransfer? I'd be interested in making a PR for this but want to get a guess for the size.

**Comment by SkrewEverything** [comment]
> In addition I tried to use a Polyfill that handles this event properly on iPad but it seems to produce another error... It can't retrieve x, y, h, w after apply Polyfill.
> 
> Someone solve this with another solution? Maybe this awesome library must consider fix this on iPad?

For anyone coming here for the solution, 

As said above, whenever polyfill is used, the dropped item has coordinates as `x: NaN` and `y: NaN`.

Just add default dropping coordinates in `onDrop` handle like `x: 0` and `y:0` before updating your layout array.

**Comment by hugolgst** [comment]
> > In addition I tried to use a Polyfill that handles this event properly on iPad but it seems to produce another error... It can't retrieve x, y, h, w after apply Polyfill.
> > Someone solve this with another solution? Maybe this awesome library must consider fix this on iPad?
> 
> For anyone coming here for the solution,
> 
> As said above, whenever polyfill is used, the dropped item has coordinates as `x: NaN` and `y: NaN`.
> 
> Just add default dropping coordinates in `onDrop` handle like `x: 0` and `y:0` before updating your layout array.

@SkrewEverything Could you elaborate a bit more? I am unsure about the way to proceed.
Is there a way to make it work on iOS/iPadOS?
