### ISSUE TITLE
Incompatible with create-react-app ?

### ISSUE THREAD

**Issue by Exanis** [STRML/react-grid-layout#1184]
Hello there,

I have a strange problem. I'm trying to use react-grid-layout on my app and it's doing basically nothing, so I thought that I should try something smaller to isolate what I'm doing wrong.

So I've created a brand new app, empty, using create-react-app. Then I did the following changes :

- Install react-grid-layout using npm
- Copy both stylesheet in a single one located in the public folder (I'll explain why later)
- Put this code in the index.js file :

```jsx
import React from "react";
import ReactDOM from "react-dom";
import GridLayout from "react-grid-layout";

class MyFirstGrid extends React.Component {
  render() {
    // layout is an array of objects, see the demo for more complete usage
    const layout = [
      { i: "a", x: 0, y: 0, w: 1, h: 2, static: true },
      { i: "b", x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4 },
      { i: "c", x: 4, y: 0, w: 1, h: 2 }
    ];
    return (
      <GridLayout
        className="layout"
        layout={layout}
        cols={12}
        rowHeight={30}
        width={1200}
      >
        <div key="a">a</div>
        <div key="b">b</div>
        <div key="c">c</div>
      </GridLayout>
    );
  }
}

const contentDiv = document.getElementById("root");
ReactDOM.render(React.createElement(MyFirstGrid), contentDiv);
```

As you can see, I've basically copy/pasted the very first example of the readme. Now when I use `npm start` to try and test my application... nothing works. Like, there is an "a", "b" and "c" div displayed, one above the other, and the usual logging when I try to drag them, but no grid whatsoever.

Now you may ask, why copying the two css files in one and include them in my html file ? Well, that's because when I started writing this issue, I tried to reproduce it in a codesandbox... and overthere everything is working fine. I checked the versions of react / react-grid-layout / react-dom in codesandbox and set them to the one in a fresh out-of-the-box install, still working fine.

So I don't really know what's going wrong here. As I said, the code is basically the simpler example I can think of, nothing was changed at all from following the doc after creating a fresh app, so my guess is there is something I'm missing in the documentation that I should do to make it works, but I can't think of what is could be...

Since I can't reproduce on codesandbox, I created a repository to demonstrate the issue here : https://github.com/Exanis/react-grid-layout-strange 

The second commit let you outline all my changes (I did a few tests so there are some files in addition to what I mentionned here but they shouldn't change anything).

Any idea ? :s

Thank you !

**Comment by dospolov** [comment]
@Exanis try with 0.17.1 version

**Comment by Exanis** [comment]
> 
> 
> @Exanis try with 0.17.1 version

Using version 0.17.1 seems to fix at least a part of the issue, thank you ! :)

**Comment by JPNZ4** [comment]
I'm using this very extensively with CRA and it works fine. Currently on the latest version 0.18.3.
