### ISSUE TITLE
Fly-in load effect is delayed

### ISSUE THREAD

**Issue by taxidermied-potato** [STRML/react-grid-layout#1185]
Items within the grid appear as expected in a defined layout, but upon an attempt to move an item, the load effect (where the items appear and fly in from the top left corner) occurs once and only once before behavior returns to normal. Per the examples, this should only occur on page load and refresh, so it should be expected on the grid-layout component mounting. This is a bit confusing, since the component ostensibly does mount, but said effect only occurs on interaction.

**Comment by raygerrard** [comment]
@taxidermied-potato you can workaround this by setting the following properties:

```jsx
<GridLayout measureBeforeMount={true} useCSSTransforms={false}></GridLayout>
```
