### ISSUE TITLE
RGL in print, clipping

### ISSUE THREAD

**Issue by Puffton** [STRML/react-grid-layout#119]
I'm using RGL as an WYSIWYG editor for templates used in print. With dynamic content, there may be spillover, i.e. the RGL stretches outside of the physical page in print, onto a new page. This is not a problem on the site, I can just stretch the containing div. In print it does continue on the next page, but it is clipped rather harshly.

Using page-break does not help, since the items are absolute positioned. I'm open for any suggestions on how to make RGL work better in print.

**Comment by STRML** [comment]
Not sure how you might tackle this, to be honest. The only idea I have is to set the row height to be exactly an even division of the page height, and then to use the callbacks to forbid placing items that would span a page barrier.

**Comment by Puffton** [comment]
That's a good idea, but my items can stretch, potentially covering multiple pages. I'm considering using something like http://weasyprint.org/.

I'll keep you posted here, if anyone else would think of printing their RGL's.

**Comment by STRML** [comment]
Please reopen if you have a concrete plan for this, but this won't be officially supported. This would require essentially creating immovable barriers (page breaks) in the layout.
