### ISSUE TITLE
Drag from outside not much smooth in firefox

### ISSUE THREAD

**Issue by Arif-un** [STRML/react-grid-layout#1192]
drag from outside in react-grid-layout is working but its not much smooth as chrome,
is there any hack for it?

example: [codesandbox](https://codesandbox.io/s/react-grid-layout-drag-and-drop-5tizk?file=/src/App.js )

**Comment by JamesRamm** [comment]
@Arif-un 
Just came across this issue. Did you discover the reason why?

**Comment by Arif-un** [comment]
@JamesRamm  No, I can't figure it out.
