### ISSUE TITLE
Bug nested drop placeholder useCSSTransforms

### ISSUE THREAD

**Issue by djmisterjon** [STRML/react-grid-layout#1197]
Hi , i have a weird bug here when use `isDroppable`
![bug rgl](https://user-images.githubusercontent.com/24865815/80080753-0a829880-8520-11ea-8c9b-754ba2286a83.gif)

As you can see if we drag a drop element from outside inside a nested layout, the placeholder  dont comput correcly the transform distance.

The only way work is disable 
```js
					useCSSTransforms={useCSSTransforms}
					isDroppable={nestLevel === radioLayers}
					onDragStart={(layout, oldDragItem, l, placeholder, e, node) => {
						if (l) {
							set_useCSSTransforms(false);
						}
					}}
```
Any way to allow good positioning in nested layout dragdrop with `useCSSTransforms` true ?

**Comment by djmisterjon** [comment]
ok fixed with `pointer-events: none;` , all bug related to this.
Somebody need fix this in the release.

**Comment by rasmusgadensgaard** [comment]
Where exactly did you add` pointer-events: none;` ? Im having this issue too

**Comment by djmisterjon** [comment]
@rasmusgadensgaard 
```css
.react-grid-item.react-grid-placeholder {
	pointer-events: none;
}
```
they have forget to add this, so when placeholder  follow the cursor, it will blink and going crazy.
also we need add a `e.stopPropagation();` for nested
```js
	onDragStart={(layout, oldItem, newItem, placeholder, e, element) => {
		// stuff
		e.stopPropagation();
		e.preventDefault();
	}}
```

**Comment by johnsoncherian** [comment]
Was this bug fixed? I have a use case where user can drop inside the grid also in a nested grid. Both are droppable. In the inner grid the placeholder placement is wrong
