### ISSUE TITLE
When layout is an empty array, We are unable to drag and drop and External element

### ISSUE THREAD

**Issue by hmudimi** [STRML/react-grid-layout#1198]
I have recreated the issue in link https://codesandbox.io/s/hopeful-lamarr-4dy10?. 

I have considered my layout as [] and I wanna created layout element on the drop of `an external element`. For some reason when empty layout I am not able to see grid-layout to drop an external element.

**Comment by josesaranda** [comment]
Why is the reason to have an empty layout?

**Comment by hmudimi** [comment]
@josesaranda I wanna create layout only on drag and drop. Initially, I don't have any layout elements on load. I will save the layout in DB and from next time onwards. I will load previously created elements.

**Comment by hmudimi** [comment]
And also Is it possible to pass some data from the draggable element and receive it on Drop method?

**Comment by hmudimi** [comment]
> @josesaranda I wanna create layout only on drag and drop. Initially, I don't have any layout elements on load. I will save the layout in DB and next time onwards I will load previously created elements.

On load I have created a layout with {x:0, y:0, w:0, h:0} from there I am able to di drag and drop.

**Comment by josesaranda** [comment]
What about this? It may help you I think...

```typescript
// on drop function

private onDrop = (value : any) => {
    let drop : Drop = {
      x : value.x,
      y : value.y,
      h : value.h,
      w : value.w,
      transfer : JSON.parse(value.e.dataTransfer.getData('text/plain'))
    }

    let boxes = this.state.boxes;
    boxes.push({...drop, id : v4()});
    this.setState({boxes});
}

// render method below

<ResponsiveReactGridLayout
  width={width || 0}
  style={{height: '100%', overflow: 'auto', width}}
  containerPadding={[10,10]}
  isResizable={true}
  isDraggable={true}
  compactType={'vertical'}
  onDrop={this.onDrop}
  isDroppable={true}
  droppingItem={{i : 'new',h : 3 , w : 3}}
>
this.state.boxes.map((box) => {
  return (
  <div style={{background : 'white'}} className="box-shadow-1" key={box.id} data-grid={{...box, i : '1'}}>
    Hello box              
  </div>)}
</ResponsiveReactGridLayout>
```

**Comment by hmudimi** [comment]
> What about this? It may help you I think...
> 
> ```ts
> // on drop function
> 
> private onDrop = (value : any) => {
>     let drop : Drop = {
>       x : value.x,
>       y : value.y,
>       h : value.h,
>       w : value.w,
>       transfer : JSON.parse(value.e.dataTransfer.getData('text/plain'))
>     }
> 
>     let boxes = this.state.boxes;
>     boxes.push({...drop, id : v4()});
>     this.setState({boxes});
> }
> 
> // render method below
> 
> <ResponsiveReactGridLayout
>   width={width || 0}
>   style={{height: '100%', overflow: 'auto', width}}
>   containerPadding={[10,10]}
>   isResizable={true}
>   isDraggable={true}
>   compactType={'vertical'}
>   onDrop={this.onDrop}
>   isDroppable={true}
>   droppingItem={{i : 'new',h : 3 , w : 3}}
> >
> this.state.boxes.map((box) => {
>   return (
>   <div style={{background : 'white'}} className="box-shadow-1" key={box.id} data-grid={{...box, i : '1'}}>
>     Hello box              
>   </div>)}
> </ResponsiveReactGridLayout>
> ```

Thanks,... I have used something like this `let id = parseInt(elemParams.e.dataTransfer.getData("id"));`, It works.

**Comment by hmudimi** [comment]
Thanks for the support guys
