### ISSUE TITLE
Issue with dropping and adding different widgets on to the grid

### ISSUE THREAD

**Issue by AA9-YG** [STRML/react-grid-layout#1200]
I have been having issues trying to add different widgets on to the grid. I'm trying to incorporate a sidebar that has different items in it to which I can drag and drop them anywhere on the grid. I've been looking over the examples provided such as the toolbox example and the drag from outside example but they don't really help me understand how I can use multiple widgets. The issue that I keep getting is that no matter which widget I drag from the outside, the same one will appear on the grid. I just need a clear explanation on how to add different widgets that are outside of the grid because I'm still new at this. One example that I would like to sort of imitate is the gif @daynin posted on #980

**Comment by mikefordweb** [comment]
This is exactly what I am looking to do!!  Drag an item from an external list and have it appear as a new item in the grid.

**Comment by AA9-YG** [comment]
It's good to know that I'm not the only one with this problem. It would be great if a solution could be shared to help us out. I've tried other packages like react-beautiful-dnd but that is generally for creating and rearranging lists which isn't what I am aiming for. I've also been trying to find examples on codepen and codesandbox that might have something similar to what I'm trying to accomplish but I have yet to find one.
