### ISSUE TITLE
Sometimes after the dragging, the transform-translate of the element gets negative when using a dragable responsive layout

### ISSUE THREAD

**Issue by romanpastu** [STRML/react-grid-layout#1202]
During the dragging of the items in a responsive layout, if you drag it too far away from its initial position, and then stop dragging it. It will go back to its original position but with a negative height
Being it negative transform-translate, or negative top if 
`useCSSTransforms={false}`

Initial positioning
![image](https://user-images.githubusercontent.com/43568511/80695614-75127600-8ad6-11ea-92d4-026902871daf.png)

Position after dragging to the bottom and dropping the element

![image](https://user-images.githubusercontent.com/43568511/80695454-3bda0600-8ad6-11ea-89b4-7954f6849380.png)

As you can see the first element, the one dragged and then unclicked for it to return to its original position. It returns to a negative position instead of staying in the previous one

**Comment by ugurdalkiran** [comment]
I have the same problem.
