### ISSUE TITLE
react-draggable Super Expression issue

### ISSUE THREAD

**Issue by BoazKG93** [STRML/react-grid-layout#1203]
According to https://github.com/STRML/react-resizable/issues/128 we need to fix our react-draggable to 4.2.0. Could you please update your package.json accordingly until this issue is resolved? My server builds and installs react-grid-layout 0.18.3 automatically and with it it's package.json and with react-draggable ^4.0.0.  This causes the above issue to appear.

**Comment by iamhimadri** [comment]
I am facing the same issue. @BoazKG93 How did you resolve this?
