### ISSUE TITLE
Initial grid render next to sidebar is oversized and causes horizontal scroll bar

### ISSUE THREAD

**Issue by JoelArmendariz** [STRML/react-grid-layout#1204]
When rendering a grid of cards next to a side bar element (the summary controls is not part of the grid), the grid renders with a full width as if the summary controls card was not there causing a horizontal scroll to see the rest. On resizing the window however, the grid 'wakes up' and resizes to properly display on the page.

![grid-layout-oversized](https://user-images.githubusercontent.com/53092833/80752335-f0812100-8af0-11ea-8da5-95c50148926a.png)

This seems to be the same problem as the one found in this closed issue: https://github.com/STRML/react-grid-layout/issues/879

**Comment by josesaranda** [comment]
Use a Resizer observer and set size to React-grid-layout component i.e https://www.npmjs.com/package/react-resize-detector. That works for me.

**Comment by sughanpandita** [comment]
Can you give an example using Resizer observer ?
