### ISSUE TITLE
onDrop

### ISSUE THREAD

**Issue by mikefordweb** [STRML/react-grid-layout#1205]
I have a list of droppable items next to the grid, that I can drag items from and drop into the grid.  But I can't figure out a way to pass information about the new item I am dropping in.  There is a callback, but I can't pass information in it to update the contents of the new item.

Code from ReactGridLayout.js:

onDrop = (e: Event) => {
    const { droppingItem } = this.props;
    const { layout } = this.state;
    const { x, y, w, h } = layout.find(l => l.i === droppingItem.i) || {};

    this.dragEnterCounter = 0;

    this.removeDroppingPlaceholder();

    this.props.onDrop({ x, y, w, h, e });
  };

**Comment by flashtheman** [comment]
Haven't tried but the documentation says that in addition to x, y, w and h, on drop also returns e:
onDrop: (elemParams: { x: number, y: number, w: number, h: number, **e: Event** }) => void.

Please check if the information in e is helpful.

**Comment by akshaygoyal88** [comment]
I am having 1 issue onDrop feature works only with Responsive Grid Layout not with react-grid-layout

**Comment by stheobald** [comment]
@mikefordweb how did you solve this issue? I'm trying to build something which sounds similar to what you describe, and am stuck with the same problem,

`droppingItem` doesn't seem to contain anything useful for us either.

@flashtheman `e` is an Event, evidently triggered by the grid being dropped onto, it appears to contain a reference to the target grid destination, but nothing about the element being dropped.

**Comment by stheobald** [comment]
This is the answer: https://github.com/STRML/react-grid-layout/issues/1180#issuecomment-612812656
