### ISSUE TITLE
Dragging a element doesn't swap positions with another element (like ZOHO Project Mgmnt Tool)

### ISSUE THREAD

**Issue by IAmRC1** [STRML/react-grid-layout#1207]
I have a react grid layout consisting of draggable divs, like ZOHO. Whenever i drag the div and drop it on another div, they doesn't swap positions just like zoho instead the div that is being dragged pushes the placed div to bottom.

**Comment by flashtheman** [comment]
Not sure but I don't think this feature is supported.
