### ISSUE TITLE
Resize nested items

### ISSUE THREAD

**Issue by AndreyZavarin** [STRML/react-grid-layout#1210]
Hello.
I use a library to create nested elements.
There was a problem resizing nested elements.
Before resizing:
![image](https://user-images.githubusercontent.com/15002874/81932826-0b758a00-95f5-11ea-9f95-16de166525a1.png)
After resizing:
![image](https://user-images.githubusercontent.com/15002874/81932926-31029380-95f5-11ea-8d62-a15a6b84fab2.png)
To display nested elements, expanded the object, added **children**.
Possible solution to update state in onResizeStop.
I would like to implement this in onResize.

**Comment by Marginy605** [comment]
Have the same problem. Did you find any solution?
