### ISSUE TITLE
"moved" property is empty in onDragStop when using compactType null

### ISSUE THREAD

**Issue by flashtheman** [STRML/react-grid-layout#1212]
There are 4 possible configurations in regards to compactType:
- vertical
- horizontal
- null
- undefined

When using null as compactType it means that you can move items around freely.

The bug I want to report, is that when using onDragStop, the "moved" property of the returned object, shows always false for all items. For vertical and horizontal the moved property is set correctly.

Please the console output of this sandbox after having dragged an item:
https://codesandbox.io/s/xenodochial-bartik-sntuu?file=/src/ShowcaseLayout.js

**Comment by flashtheman** [comment]
How do I remove the stale tag?

**Comment by arclogos132** [comment]
Seems like null as compactType setting is in no one's interest..
