### ISSUE TITLE
Is it possible to give multiple selectors to draggableCancel prop ?

### ISSUE THREAD

**Issue by DhanaSekharM** [STRML/react-grid-layout#1214]
The data being passed to a RGL wrapper in my code is not uniform. Hence some of grid items may render a different widget based on the data given. So is it possible to provide more than one css selectors to `draggableCancel` so that all the widgets are considered?

**Comment by tourshi** [comment]
It's possible to achieve this yourself by creating an array of multiple selectors and passing this array to your draggableCancel prop. Eg.  
`
const PREVENT_DRAG_DEFAULTS = ['.chicken','.beans'];
<RGL draggableCancel={PREVENT_DRAG_DEFAULTS .join(',')} />
`
