### ISSUE TITLE
Help implementation on TypeScript

### ISSUE THREAD

**Issue by marcoaureliovrs** [STRML/react-grid-layout#1217]
I am implementing the library with TypeScript, but I have an error that I am not able to solve

![Captura de Tela 2020-05-31 às 11 56 32](https://user-images.githubusercontent.com/12548136/83355437-db88ef00-a335-11ea-9081-37a9db76e274.png)

my code example

```ts

import React, { Component } from 'react';
import GridLayout from 'react-grid-layout';

class Grid extends Component<any, any>  {
    constructor(props: any) {
        super(props)

        this.state = {

        }
    }

    componentDidMount() {

    }

    render() {

        let layout = [
            { i: 'a', x: 0, y: 0, w: 1, h: 2, static: true },
            { i: 'b', x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4 },
            { i: 'c', x: 4, y: 0, w: 1, h: 2 }
        ];


        return (
            <div >
                <GridLayout className="layout" layout={layout} cols={12} rowHeight={30} width={1200}>`
                    <div key="a">a</div>
                    <div key="b">b</div>
                    <div key="c">c</div>
                </GridLayout>
            </div>
        )
    }
}


export default Grid;

```

my library versions:

"typescript": "^3.9.3"
"react-grid-layout": "^0.18.3",
"react": "^16.13.1",

**Comment by c2r0b** [comment]
I think you should avoid having typescript compiling the files in the `node_modules` folder.
You should change the settings in your `tsconfig.json`.
Try the solutions referenced here: https://stackoverflow.com/questions/51634361/how-to-force-tsc-to-ignore-node-modules-folder
