### ISSUE TITLE
Uncaught Error: Cannot find module 'react/lib/emptyFunction'

### ISSUE THREAD

**Issue by gbmhunter** [STRML/react-grid-layout#122]
I get the message `Uncaught Error: Cannot find module 'react/lib/emptyFunction'` when calling `var ReactGridLayout = require('react-grid-layout');`.

![image](https://cloud.githubusercontent.com/assets/2396869/10771333/01a5307e-7d55-11e5-9faa-9712fe97bca5.png)

I am running npm v2.11.2 and opening the page in electron-prebuilt v0.32.3 (the Electron app).

**Comment by benjie** [comment]
This issue seems to make react-grid-layout incompatible with React 0.14

**Comment by benmosher** [comment]
FYI: I was able to hack around this in the published version by adding an `externals` entry in my webpack config, defining it as `function(){}`.

YMMV. Also, if you look at master, this is fixed in the tip. Just hasn't been released.

**Comment by gbmhunter** [comment]
Thanks for the info guys, I guess this can be closed then.

**Comment by tomasztomys** [comment]
Can you change it in code?

**Comment by boui** [comment]
Hi! When do you plan to release the fix? That is one thing that blocks react 14 for us.

**Comment by akullpp** [comment]
+1

**Comment by aweber1** [comment]
See this issue/thread: https://github.com/STRML/react-grid-layout/issues/117
