### ISSUE TITLE
RGL isn't responsive when resizing from small to larger breakpoints

### ISSUE THREAD

**Issue by tourshi** [STRML/react-grid-layout#1222]
Thank you guys for all your great work, I just have an issue I'm not able to overcome. I feel I'm missing some understanding as to why this is occurring.

**Problem**: When you resize the RGL from large to smaller breakpoints, the grid is responsive and responds accordingly. However, when you resize from small to larger, it seems to get stuck at that smaller breakpoint. I'm using WidthProvider, but I've also tried other ways of passing width prop to the grid, but to no avail. 

**Sandbox code**: https://codesandbox.io/s/rgl-responsive-issue-0g807

**To reproduce**: Resize the preview pane, making it narrower. Once it's at the smallest breakpoint, now start resizing the preview pane back to how it was.

Thank you

**Comment by zackkrida** [comment]
Having the same issue in my app

**Comment by jerdbo** [comment]
same too

**Comment by josesaranda** [comment]
Same

**Comment by abhisheksharmas04** [comment]
same issue i m having..

**Comment by tourshi** [comment]
any updates on this? I was hoping it was just matter of setting the right props. Any help would be appreciated! Thanks

**Comment by hachtman** [comment]
I've noticed this since changing from setting the `layouts` prop as the `Responsive` level to using `data-grid` on each grid item.

**Comment by shiva2035** [comment]
Any fixes for this?

**Comment by valtism** [comment]
A (not good) workaround is to change the key when you want the change to apply.

**Comment by Arsh1a** [comment]
Still no fix?

**Comment by moazzam-ali** [comment]
Any updates on this???

**Comment by moazzam-ali** [comment]
> A (not good) workaround is to change the key when you want the change to apply.

Can you explain this a bit more?

**Comment by dev-khoi** [comment]
This is what I have founded out: 
```
// The main problem is the layout change conflict between breakpoint and 
// onlayoutChange
        const onLayoutChange = (layout: Layout[], allLayouts: Layouts) => {

        // lastSavedLayout ref is used for saving the last layout before changing,
        // in this case it is used for saving the layout before a breakpoint change        
        lastSavedLayout.current = layout;

        // ignoreLayoutChange ref is used for ignoring the layoutChanges 
        // when a breakpoint is made
        // It is for the problem in the attached
        if (!ignoreLayoutChange.current) {
            setLayouts(allLayouts);
        }
    };

    const onBreakpointChange = (newBreakpoint: string) => {
        // onbreakpoint -> rerender -> onlayoutchange
        // during rerender, ignoreLayoutChange will be 
        // set to default value (false)
        ignoreLayoutChange.current = true;

        // Save current layout before switch
        // using lastSavedLayout ref
        // Update currentBreakpoint after saving
        setLayouts((prevLayouts) => ({
            ...prevLayouts,
            [currentBreakpoint]: lastSavedLayout.current,
        }));
        setCurrentBreakpoint(newBreakpoint);
    };
```
