### ISSUE TITLE
Cannot determine correct breakpoint from onDrop

### ISSUE THREAD

**Issue by dantman** [STRML/react-grid-layout#1224]
When using ResponsiveGridLayout and onDrop there is no way to identify what the current breakpoint is. onDrop's params do not include a breakpoint, but include item props `{x, y, w, h}` which are associated with the breakpoint at the time the user dropped the external item (the current breakpoint). And the current breakpoint is managed by RGL and cannot easily be extracted.

This is an issue because the basic idea of `onDrop` is to add an item to the layout but it is unknown which of the breakpoints the item should be added to the layout of.

RGL should override the onDrop event to include breakpoint information in the callback's args, just like it does with onLayoutChange.

I have a few ideas on potential API, thoughts?

- `(elemParams: { x, y, w, h, e, breakpoint = currentBreakpoint }` - Easy and backwards compatible
- `(elemParams: { [breakpoint]: { x, y, w, h, e } })` - Fits with `layouts` etc.
- `(elemParams: { x, y, w, h, e }, allElemParams: { [breakpoint]: { x, y, w, h } }` - Fits in with onLayoutChange and is backwards compatible

**Comment by josesaranda** [comment]
Create a React.RefObject to obtain current breakpoint from RGL Component. That's all.

**Comment by dantman** [comment]
How do you suggest getting the current breakpoint from a ref? There is no public property/method for getting the current breakpoint?

**Comment by josesaranda** [comment]
```typescript
import { Responsive as ResponsiveReactGridLayout } from "react-grid-layout";

class MyComponent extends Component {
  private ref : React.RefObject<any> = React.createRef();

  componentDidMount(){
    console.log('breakpoint',this.ref.current.state.breakpoint); // breakpoint here
  }

  render(){
    return(
     <ResponsiveReactGridLayout ref={this.ref}>
      ...
     </ResponsiveReactGridLayout>
    );
  }
}
```

This sample is using .tsx.

I hope it will be useful for you. =)

**Comment by dantman** [comment]
`component.state.breakpoint` is a private interface, it's not part of the API. That would be a hack rather than a solution.

**Comment by josesaranda** [comment]
I don't think so. But, I suppose, if you create a PR with this feature it will be welcome to this project.

**Comment by hluedeke** [comment]
I ran into this exact issue - I was really hoping to use onBreakpointChange to maintain the breakpoint state separately in a containing component, however onBreakpointChange does not appear to fire on initialization (react-grid-layout 1.3.0, React 16.8.6).

Oddly the "Drag from Outside" example seems to be able to correctly display the initial breakpoint, so I'm not sure what I'm missing. If I can get that initial breakpoint, I think I can easily work around the above issue.

**Comment by hluedeke** [comment]
I found my issue - we were using a different HOC from WidthProvider that behaved slightly differently, causing the initialization issue.

With that solved, if you run into the above issue, I recommend maintaining the breakpoint state using onBreakpointChange in your component state. Then you will be able to tell which breakpoint you need to replace onDrop.

Hope this helps someone!

**Comment by yurec133** [comment]
const handleOnLayoutChange = (layout: Layout[], layouts: any) => {
      setLayouts((prev:any) => {
        return { ...prev, ...layouts };
      });
  };
