### ISSUE TITLE
Allow DragOver events to be ignored

### ISSUE THREAD

**Issue by JamesRamm** [STRML/react-grid-layout#1226]
I am using the 'drop from outside', functionality, which works very well. 
I would like to drag and drop different type of element *on to* the element I just dropped onto the grid.

For this to work, I need a way to inform react-grid-layout to ignore 'drag over' events for these elements, otherwise the collision logic kicks in and I cant actually drag my 2nd element onto the previously dropped element.

Is such a thing already possible? If not, could some kind of check in the 'onDragOver' event handler for a certain property/string/etc in the DataTransfer object work?

Then in our application onDragStart handler we can set this property for elements we wish to ignore.

**Comment by JamesRamm** [comment]
Here is a GIF showing what I mean using a 'static' grid (CSS grid). The first element is dropped into the space, then a 2nd element is dropped onto the first element, triggering different behaviour:

![drag_over](https://user-images.githubusercontent.com/2784823/84508589-cd868700-acc2-11ea-9d7c-4ad0bbac11ad.gif)


As shown in the gif below, using RGL, the collision logic prevents me from dropping onto my existing element:

![drag_over_rgl](https://user-images.githubusercontent.com/2784823/84508755-12122280-acc3-11ea-86c8-93732351ceef.gif)

**Comment by treyholt** [comment]
did you figure this out @JamesRamm
