### ISSUE TITLE
Quick version question

### ISSUE THREAD

**Issue by swirlycheetah** [STRML/react-grid-layout#123]
Hey, I noticed the version of react-grid-layout published to npm is 0.8.5 yet the version mentioned in the `package.json` in master is 0.9.2.

Just wondering if the latest version will be published to npm?

**Comment by STRML** [comment]
It was published but had some major bugs discovered after publishing. I am working on finishing up some major revisions to the underlying libraries, then `0.10` with React 0.14 support will be released.

**Comment by swirlycheetah** [comment]
Ah that makes sense. That sounds great, I'm currently starting a new project with 0.14 and react-grid-layout so looking forward to the updates.
