### ISSUE TITLE
Container's `margin` property affects resizing element's height

### ISSUE THREAD

**Issue by forest-shadow** [STRML/react-grid-layout#1239]
# Bug Report
Container's `margin` property affects the vertically resizing element's height by adding extra `margin`px on each vertical resize step.
I think that is the wrong behavior, but obviously don't know about all implementation details. 

Reproduced here:
https://codesandbox.io/s/patient-sky-rsgrv?file=/src/ShowcaseLayout.js:2349-2440

**Comment by Ilaiwi** [comment]
@forest-shadow have you figured out a workaround other than setting margin to `[0,0]`?

**Comment by hsuna** [comment]
I also encountered this problem. I couldn't set it to [0,0] because I needed to dynamically set the` margin`.

https://github.com/react-grid-layout/react-grid-layout/blob/e4e2b8b054d247ab696bb4e7d6199415b2f45d32/lib/calculateUtils.js#L33

```
export function calcGridItemWHPx(
  gridUnits: number,
  colOrRowSize: number,
  marginPx: number
) {
  // 0 * Infinity === NaN, which causes problems with resize contraints
  if (!Number.isFinite(gridUnits)) return gridUnits;
  return Math.round(
    colOrRowSize * gridUnits + Math.max(0, gridUnits - 1) * marginPx
  );
}
``` 

Why `Math.max(0, gridUnits - 1) * marginPx`?
