### ISSUE TITLE
Incorrect ordering

### ISSUE THREAD

**Issue by jasecoop** [STRML/react-grid-layout#124]
Hi

I'm trying to get my head around RGL and was hoping somebody might be able to help.

I am trying to implement a simple layout in which the items are ordered in order horizontally e.g. https://strml.github.io/react-grid-layout/examples/1-basic.html

My layout currently looks like this: 

![](https://s3.amazonaws.com/f.cl.ly/items/1a1L0t3J0l3z3R08300Y/Image%202015-10-28%20at%2010.00.49%20pm.png)

With this code defining the layout:

```
  _generateLayout() {
    winWidth  = window.innerWidth - 40;
    itemWidth = winWidth / this.props.cols;

    return this.props.images.map(function (image, i ) {

      ratio = image.width / image.height
      var w = itemWidth;
      var h = itemWidth/ratio;

      return {x: i % 4, y: 0, w: 1, h: h, i: i};
    });
  }
```

How do I calculate Y correctly so the items render in the correct order.

I see this a lot in the examples, could somebody please explain what is happening here to calculate y, I haven't been able to get my head round it:

```
      var y = _.result(p, 'y') || Math.ceil(Math.random() * 4) + 1;
      return {x: i * 2 % 12, y: Math.floor(i / 6) * y, w: 2, h: y, i: i};
```

Thanks for your help. RGL is the best layout component I've come across so far for React. It's really nicely done.

**Comment by STRML** [comment]
Closing as there has bee no followup - this should be easy to calculate on your end if you already know the w/h of your items.
