### ISSUE TITLE
Custom Component

### ISSUE THREAD

**Issue by woland7** [STRML/react-grid-layout#1241]
Hello, how do I use a custom component as grid item? I couldn't find anything  on the guide and I'm quite new in the react world. 
Thank you in advance.

**Comment by dreukrag** [comment]
`const OcurrencesWidget = ({ ...rest }) => {
  const styles = WidgetsStyle();
  return (
    <Paper {...rest} className={[styles.widget, styles.square].join(' ')}>
      <Typography variant="h6" align="center">
        Ocorrências
      </Typography>
      <div style={{ flex: 1, display: "flex", alignItems: "center" }}>
        <Typography variant="h5" align="center">
          21
        </Typography>
      </div>
    </Paper>
  );
};

//Add the component to an array, must have the wrapper div

content = [
<div key={i} data-grid={{ ...others }} className={styles.griditem}>
    <OcurrencesWidget />
</div>
]


`

**Comment by dreukrag** [comment]
Found the solution, you need to render the components children too, this allows the resize widget to render, like this:
```

    <Paper {...rest} className={[styles.widget, styles.square].join(' ')}>
      <Typography variant="h6" align="center">
        Ocorrências
      </Typography>
      <div style={{ flex: 1, display: "flex", alignItems: "center" }}>
        <Typography variant="h5" align="center">
          21
        </Typography>
      </div>
      {children}
    </Paper>
```

When calling the component you can do it like this:

`<OcurrencesWidget key={i} data-grid={{ ...others }} className={styles.griditem}/>`

**Comment by ProggerPete** [comment]
I'm having similar difficulties.  I attempted to replicate dreukrag's solution but couldn't make it work.   I do get the app to render, but the grid is not functional.

Demo code;
```
function App() {
    const cols = 6;
    const items = ['one', 'two', 'three'];
    const layout = items.map((item, index) => {
        return {
            i: item,
            x: index % cols,
            y: Infinity,
            w: 1,
            h: 1
        }
    })

    return (
        <div className="App">
            <GridLayout className="layout"
                        layout={layout}
                        cols={cols}
                        rowHeight={100}
                        width={1200}>
                {
                    // TODO : This one works
                    // items.map((item, index) => <div key={item}>{generateItem(item)}</div>)
                    // TODO : This one doesn't
                    items.map((item) => generateItem(item))
                    // TODO : This one also doesn't
                    // items.map((item) => <Evaporate key={item}>{generateItem(item)}</Evaporate>)
                }
            </GridLayout>
        </div>
    );
}

function generateItem(val: string) {
    return <TestItem key={val} val={val}/>;
}

function Evaporate({children} : {children: React.ReactNode}) {
    return <>{children}</>;
}

function TestItem({val}: { val: string; }) {
    return <div style={{border: '1px solid black'}}>Test Item {val}</div>;
}
```

**Comment by dreukrag** [comment]
So after fiddling with it I think I found the solution.

There are 3 props you need to handle in your component: children, styles and classname
If your component already sets one of those props then you to merge them.

This won't work, it sets the style and className props to a fixed value and doesn't implements children
```
function TestItem({val}) {
  return (
    <div style={{ border: "1px solid black"}} className="class" key={val}>
        <p>this is a simple component</p>
    </div>
  );
}
```
This should work:
```
function TestItem({style, className, key, children, ...restOfProps}) {
  return (
    <div style={{ border: "1px solid black", ...style}} className={["class", className].join(' ')} key={key} {...restOfProps}>
        <p>this is a simple component</p>
        {children}
    </div>
  );
}
```

**Comment by woland7** [comment]
I also managed to make it work. Still I would like to the grid layout item to have the same height as the child container. Have you also solved this issue? The docs said to use react-size-me, so I think I'll have a look at it.

Basically I have this.

`<div key={l.i} style={{height:'100%',width:'100%'}} className={l.static ? "static" : "mobile"}>
                    <div className="hide-button" onClick={this.onPutItem.bind(this, l)}>
                        &times;
                    </div>
                    {getWidget(l.i)}
                   {/*<CustomHeader className="react-grid-item mobile react-draggable cssTransforms react-resizable"/>*/}
                </div>`

Let's suppose the widget resolve to something like this.

`  let table;
    if(data.length !== 0)
        table = <Styles>
            <button onClick={resetData}>Reset Data</button>
            <Table
                columns={columns}
                data={data}
                updateMyData={updateMyData}
                skipPageReset={skipPageReset}
            />
        </Styles>;
    else
        table = <p>There are no tax claims.</p>;
    return (
        <div className="taxclaimstable-section">
            <h3 className="taxclaims-heading">Tax Claims</h3>
            {table}
        </div>
    )`

Now, I can drag and resize the table or paragraph. However, resizing works only on the width. As for the height, I can resize it for parent div basically without any constraints, but I'd like to be set at the height of the widget.

**Comment by woland7** [comment]
I also managed to make it work. Still I would like to the grid layout item to have the same height as the child container. Have you also solved this issue? The docs said to use react-size-me, so I think I'll have a look at it.

Basically I have this.

`<div key={l.i} style={{height:'100%',width:'100%'}} className={l.static ? "static" : "mobile"}>
                    <div className="hide-button" onClick={this.onPutItem.bind(this, l)}>
                        &times;
                    </div>
                    {getWidget(l.i)}
               </div>
`

Let's suppose the widget is something like this.

`  let table;
    if(data.length !== 0)
        table = <Styles>
            <button onClick={resetData}>Reset Data</button>
            <Table
                columns={columns}
                data={data}
                updateMyData={updateMyData}
                skipPageReset={skipPageReset}
            />
        </Styles>;
    else
        table = <p>There are no tax claims.</p>;
    return (
        <div className="taxclaimstable-section">
            <h3 className="taxclaims-heading">Tax Claims</h3>
            {table}
        </div>
    )
`

Now, I can drag and resize the table or paragraph. However, resizing works only on the width. As for the height, I can resize it for parent div basically without any constraints, but I'd like to be set at the height of the widget.

**Comment by dreukrag** [comment]
I think that's a css problem.

Have this style on the components outermost container, the one that is the parent to the resizing widgety icon

```
    display: flex;
    overflow: hidden;
```

**Comment by ProggerPete** [comment]
Thanks druekrag!

For those interested, the TypeScript version that worked for me is:

```
function Component({val, className, style = {}, children, ...otherProps}: { val: string; className?: string, key?: string, style?: {[x:string] : string}, children?: React.ReactNode[]}) {
    return <div {...otherProps} style={{border: '1px solid black', ...style}} className={className}>
        Test Item {val}
        {children}
    </div>;
}
```

This allows me to use the Component normally or in the Grid.

**Comment by sadviramana** [comment]
I want to render a grid of iframes for my app. I was able to render the app but resize and drag don't seem to work. 

From the above, I wasn't able to figure out how to call the custom component from GridLayout i.e how to pass all the styles and className you mentioned above. 

It would be helpful if you could clarify the same

**Comment by dreukrag** [comment]
Check if the classes for react draggable were added to the div containing "key"

**Comment by sadviramana** [comment]
Yes, classes for react-draggable and react-resizable were added to the div.

**Comment by ProggerPete** [comment]
You might want do a test to see if event propagate from the iframe to the parent.  I suspect not.  You might need to stick a handle you can grab above the iframe and use that to move it.

**Comment by sadviramana** [comment]
But still, I have the iframe wrapped in a div. Shouldn't that work since I am not directly using an iframe @ProggerPete

**Comment by VLaD0S** [comment]
@sadviramana I've been working on a HOC to wrap an element into a grid item. 
I found that I needed to ensure that the following props end up applied:

{
  key?: string;
  "data-grid"?: Layout; // e.g. {x: 1, y: 2, minH: 3 etc...}
  className?: any;
  style?: React.CSSProperties;
  children?: React.ReactNode[];
  onMouseDown?: (e: React.MouseEvent) => {};
  onMouseUp?: (e: React.MouseEvent) => {};
  onTouchEnd?: (e: React.TouchEvent) => {};
};

**Comment by luisiacc** [comment]
So i did this, draggableHandle shows correctly but when trying to drag an item it shows this:
`DraggableCore.js?fae5:158 Uncaught Error: <DraggableCore> not mounted on DragStart!`

**Comment by STRML** [comment]
You have to use `React.forwardRef()` here. 

```js
const GridItem = React.forwardRef((props, ref) => {
  return (
    <div {...props} ref={ref}>
      {props.l.static ? (
        <span
          className="text"
          title="This item is static and cannot be removed or resized."
        >
          Static - {props.i}
        </span>
      ) : (
        <span className="text">{props.i}</span>
      )}
      {props.children}
    </div>
  );
});
```

I will make sure this gets added to the docs.

**Comment by STRML** [comment]
bab3c79

**Comment by chenzhutian** [comment]
Still dont know how to customize the draggable handler...
I forward to the child, but it is not draggable.
Should I forward the ref both the root element of the child and the customized handler?

**Comment by chenzhutian** [comment]
Ok I got it. You must pass `...restOfProps` to the Child component for event handlers such as `onMouseDown`, `onMouseUp`

**Comment by RT-Tap** [comment]
Hey, by using what's in the documentation and @STRML answer I am able to get this working for the most part however the resize handle in the corner is missing, any idea what may be causing this issue?  I also passed the ref down to ResponsiveGridLayout but yea I can't seem to get the resize working.

**Comment by mavoi09** [comment]
So I have the following component: 

export const Widget = React.forwardRef(({style, className, key, children, ...props}, ref) => {
  return <div className={className}   style={{...style}} key={'d1_w1'} ref={ref} {...props}>
        {children}
    </div>
})

Adding data-grid on the div it didn't worked, but adding data-grid on the Component it did worked:

<Widget  data-grid={{ x: 0, y: 0, w: 6, h: 3 }}/>

**Comment by beautyfree** [comment]
> codeandbox.io/s/eloquent-sammet-7bhfq?file=/src/ShowcaseLayout.js



> I want to render a grid of iframes for my app. I was able to render the app but resize and drag don't seem to work on iframes.
> 
> I have wrapped my iframe with a custom component. Here is the code: `<ResponsiveGridLayout className="gridLayout" layouts={{sm: this.props.layouts, md: this.props.layouts, lg: this.props.layouts, xs: this.props.layouts}} cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }} breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}} onLayoutChange={this.onLayoutChange} rowHeight={100} width={800}> {this.props.layouts.map((value, index) => { return( <div key={value.i}> <ImmersiveIframe srcUri={src} miniappId={uuid()}/> </div> ); })} </ResponsiveGridLayout>`
> 
> From the above comments, I wasn't able to figure out how to call the custom component from GridLayout i.e how to pass all the styles and className you mentioned above.
> 
> It would be helpful if you could clarify the same

For me this question remains relevant. I need to retain the ability to drag an element with an iframe inside

**Comment by brijesh-imemori** [comment]
I was trying to add role for the test but it is not accepting showing error

Error:
Type '{ children: any[]; role: string; key: string; className: string; layouts: { [x: string]: any; }; onLayoutChange: (lay1: any) => void; isDraggable: boolean; isDroppable: boolean; containerPadding: [number, number]; ... 8 more ...; style: { ...; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ResponsiveProps & WidthProviderProps, any, any>> & Readonly<...>'.
  Property 'role' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ResponsiveProps & WidthProviderProps, any, any>> & Readonly<...>'.ts(2322)
(property) role: string

```
<ResponsiveReactGridLayout
                role={`dashboardItem_${ci}`}
                onDrag={handleDrag}
                onDragStop={handleDragStop}
                onDrop={(event: any, tt: any, e: any) => handleDropWidget(event, tt, e, ci)}
                onBreakpointChange={onBreakpointChange}
              >
              <box></box>
              </ResponsiveReactGridLayout>
```

Can you guys please help me to resolve the issue.
