### ISSUE TITLE
Grid Items are stuck using css percentages on first render.

### ISSUE THREAD

**Issue by TimothyBJacobs** [STRML/react-grid-layout#1243]
When the grid is first rendered, the grid's `mounted` state is `false`. When grid items are rendered in this state, they use `usePercentages`. For some reason, after the grid has mounted, the grid items don't get re-rendered and so they are stuck in "percentages" mode until a user interacts with the grid.

This was not the case in 0.16.x

Sandbox: https://codesandbox.io/s/react-grid-layout-stuck-percentages-j75gm

You'll need to use the in-app browser refresh button to see the issue.

![Screen Shot 2020-07-15 at 6 12 44 PM](https://user-images.githubusercontent.com/3460448/87605575-0604f080-c6c7-11ea-842b-a8aac5c86090.png)

**Comment by rhgb** [comment]
I've encountered same problem. I've made a PR for this issue: #1246
