### ISSUE TITLE
Change opacity of components on dragging 

### ISSUE THREAD

**Issue by nicolabortignon** [STRML/react-grid-layout#1249]
How would you go about changing opacity of all the components while one is being dragged (and kept at 100% opacity).

I wonder if there is an event listener I can work with to get:
- start Drag (with the target element)
- stop Drag (with the target element)

Thank you

**Comment by STRML** [comment]
Hi, this is not a bug report, you are asking for general programming support. That is not what this issue reporting system is for.

Please try stackoverflow for this type of question.
