### ISSUE TITLE
Fractionary `transform: translate` in grid-items

### ISSUE THREAD

**Issue by queimadus** [STRML/react-grid-layout#125]
Applying fractionary values on `transform: translate(x, y)` on a `grid-item` which has a child with a property that forces hardware acceleration will result in a fuzzy element in Chrome `46.0.2490.80 (64-bit)`.

This is presented in RGL when calculating the `grid-item`'s translate given the position in the layout and the grid's width.

Here is a simplified example (Retina displays will mitigate this issue; in non-retina displays the fuzzy text is evident):
https://jsfiddle.net/wtvdq4ep/

Would you consider adding a flag to round these values or make this the default behaviour?

**Comment by slavik-m** [comment]
+1

**Comment by STRML** [comment]
These are now rounded by default in `0.10`.
