### ISSUE TITLE
drag form outside doesn't work in antd Carousel

### ISSUE THREAD

**Issue by zhujinrui** [STRML/react-grid-layout#1250]
when drag from outside to a div, it works, but if i use it  in antd Carousel ,the red  placeholder doesn't follow the mouse.i console log the layerX in onDragOver in source code file ,it to be a negative value

**Comment by STRML** [comment]
Sorry, this is not nearly enough information for anybody to be able to debug this issue. I have no idea what your Carousel component is or how it's coded. Please replicate in codesandbox.io via [this link](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js), which was in the issue template.

**Comment by zhujinrui** [comment]
this is my [issue template ](https://codesandbox.io/s/drag-from-outside-z19np?file=/src/ShowcaseLayout.js), my problem is the red placeholder doesn't follow the mouse，thank u so much
