### ISSUE TITLE
onLayoutChange is triggered with error layout when a new item is added

### ISSUE THREAD

**Issue by sparkle777** [STRML/react-grid-layout#1251]
I have a basic layout initially `[{ h: 1, i: "1595477408540", w: 6, x: 0, y: 0, }, { h: 5, i: "1595477412733", w: 3, x: 0, y: 1, }, { h: 3, i: "1595477409651", w: 3, x: 3, y: 1, }]`

and then i added a new item which has a layout `{i: "1595478129992", x: 0, y: 0, w: 3, h: 5}`

After adding the new item to the layout it will be
`[{i: "1595478129992", x: 0, y: 0, w: 3, h: 5}, { h: 1, i: "1595477408540", w: 6, x: 0, y: 5, }, { h: 5, i: "1595477412733", w: 3, x: 0, y: 6, }, { h: 3, i: "1595477409651", w: 3, x: 3, y: 6, }]`

But the onLayoutChange call back function is triggered immediately after adding the new items and the result is a different object in the fourth place in our case.
`[{
  h: 5,
  i: "1595477812640",
  w: 3,
  x: 0,
  y: 0,
}, {
  h: 1,
  i: "1595477408540",
  w: 6,
  x: 0,
  y: 5,
}, {
  h: 5,
  i: "1595477412733",
  w: 3,
  x: 0,
  y: 6,
}, {
  h: 3,
  i: "1595477409651",
  w: 3,
  x: 3,
  y: 0,
}]`

Why is it after inserting, the fourth item's y is 0 but not be 6?

I am using redux to store the widgets/items data. Even when i am passing the data to layouts it is fine. But the onLayoutChange is triggered automatically with a new data.

@STRML

**Comment by sparkle777** [comment]
[https://drive.google.com/file/d/1ZHvgGiqo9jw9NHM_W5sp8n-YTYe0Wfst/view?usp=sharing](url)

**Comment by STRML** [comment]
I'm sorry, this description doesn't make sense to me. You say you added an item with ID "1595478129992", but you end up with an item with ID "1595477812640". 

This sounds like an application-side bug and not a bug with the library. If you can clarify your question, you may have some luck on StackOverflow.

**Comment by sparkle777** [comment]
> I'm sorry, this description doesn't make sense to me. You say you added an item with ID "1595478129992", but you end up with an item with ID "1595477812640".
> 
> This sounds like an application-side bug and not a bug with the library. If you can clarify your question, you may have some luck on StackOverflow.

sorry，i wrote a mistake ID，i have chaned the question.
I want to add a new grid item to the above grid，so i used array.unshift to add a item

**Comment by sparkle777** [comment]
> I'm sorry, this description doesn't make sense to me. You say you added an item with ID "1595478129992", but you end up with an item with ID "1595477812640".
> 
> This sounds like an application-side bug and not a bug with the library. If you can clarify your question, you may have some luck on StackOverflow.

https://codesandbox.io/s/youthful-goldberg-knde1?file=/src/ShowcaseLayout.js
this demo is my issue

**Comment by sparkle777** [comment]
![Kapture 2020-07-23 at 13 08 59](https://user-images.githubusercontent.com/7789908/88357236-29056380-cd9d-11ea-84df-147701c627d6.gif)

**Comment by sparkle777** [comment]
![Kapture 2020-07-23 at 13 08 59](https://user-images.githubusercontent.com/7789908/88357374-9dd89d80-cd9d-11ea-84c6-e1cc1880bf9b.gif)

Dragging has the same problem

**Comment by sparkle777** [comment]
@STRML can you help me?

**Comment by sparkle777** [comment]
@STRML

**Comment by sparkle777** [comment]
i solved it by upgrading from 0.14.7 to 1.0.0
