### ISSUE TITLE
Drag and drop behavior

### ISSUE THREAD

**Issue by brandon-kenshoo** [STRML/react-grid-layout#1252]
Is it possible for this project to have the following drag and drop behavior? 
https://codesandbox.io/embed/gracious-wozniak-kj9w8

If so, then how?
If not, I am interested in expanding this project. But first I want to make sure that it cannot be achieved with current implementations.

**Comment by lazarnikolic1983** [comment]
I was wondering the same thing. I have DnD container where one of the elements is another DnD container. I was trying to implement behavior where it would be possible to drag and drop element from outside to inner container and it works, but was not able to put dropped element from the inner DnD container to the outer one. I believe this sort of functionality is not supported by this library.
@STRML
