### ISSUE TITLE
Cannot read property 'key' of null when conditional rendering for children

### ISSUE THREAD

**Issue by fredericvilcot** [STRML/react-grid-layout#1254]
Hello,

I use your library in my project to render a responsive grid, but I am encountering a problem with `ResponsiveReactGridLayout`.

In my parent component, I want to use conditional rendering (based on props) to render or not **first** component on the grid.
Others component are **always** displayed.

If first component is displayed, everything is Ok because component exists in DOM and key is present. 
But if I decide to not render it (for exemple : `{this.props.mustBeDisplayed ? <div key="child1">Child1<div> : null}`, application crashes because `ResponsiveReactGridLayout` needs to have only existing components with existing keys.

When we want to render a null child passed to component props, there is an error : 
`TypeError: Cannot read property 'key' of null`

The error occurs in `synchronizeLayoutWithChildren` method because there is nothing here implemented that handles nullable `React.Node` passed as `React.Children`.

There is a codesandbox below which reproduces this issue :
https://codesandbox.io/s/objective-visvesvaraya-yoo7x?file=/src/ShowcaseLayout.js

Thanks a lot for your help

**Comment by sabarasaba** [comment]
@fredericvilcot were you able to fix it? im facing the same issue now :(

**Comment by fredericvilcot** [comment]
@sabarasaba nope ... the only way is to keep empty div with a key and modify layouts to not render it...

**Comment by kennyt6** [comment]
> @sabarasaba nope ... the only way is to keep empty div with a key and modify layouts to not render it...

How do you get the layouts to not render it?

**Comment by sepehr500** [comment]
I'm also facing this issue

**Comment by huckym** [comment]
I had to hack it with this:
`<div key={'empty'} data-grid={{x:0, y:0, w:0, h:0, static:true}} />`

**Comment by rishabh-17** [comment]
I already faced same issue. I used <div key="c" style={!tilesVisibilityStatus?.Alerts && { display: 'none' }}> for fix this.
