### ISSUE TITLE
Resize the grid when the parent changes?

### ISSUE THREAD

**Issue by Pixelatex** [STRML/react-grid-layout#1257]
Seems like this doesn't work. You can resize the parent container all you want, the grid only responds to the size changes of the window. Is there no built-in way to handle this?

**Comment by sakhibgareevrr** [comment]
Also interested to hear on parent resize

**Comment by BruceWheaton** [comment]
Same problem. My Responsive grid layout is inside another React component that changes size sometimes, and the grid layout ignores it (in fact it seems to ignore its container entirely. It also gets larger vertically on its own, but that's not a deal-breaker.

**Comment by Pixelatex** [comment]
We have resorted to manually calling resize triggers after a delay of x-amount of time.  But this is quite dirty. Any maintainers who can chime in here to help us get a cleaner solution?

**Comment by BruceWheaton** [comment]
How are you doing that? Right now, only a full window resize does anything, and it's always a huge jump. 

Anyone tried rolling their own responsive version?

**Comment by BruceWheaton** [comment]
The docs recommend using react-sizeme instead of the default (basic) widthprovider. I'm trying to get that working but no luck so far - I'll report back when I have anything

**Comment by Pixelatex** [comment]
> How are you doing that? Right now, only a full window resize does anything, and it's always a huge jump.
> 
> Anyone tried rolling their own responsive version?

We forcibly update the layout again when the user takes an action that would cause the container to change size.. Far from ideal but it's what we came up with

**Comment by ShankzPatil** [comment]
any updates??
