### ISSUE TITLE
`onDragStart` triggered on item click but `onDragEnd` Doesn't

### ISSUE THREAD

**Issue by Ilaiwi** [STRML/react-grid-layout#1259]
When implementing the `onDragStart` and `onDragEnd`. A click on an item (not an actual drag) would trigger `onDragStart` but doesn't trigger `onDragEnd`. 

Please check this gif

![2020-08-05 12 28 16](https://user-images.githubusercontent.com/10817089/89396576-65c74800-d717-11ea-8cf4-375a2894032f.gif)

I am not sure if the fix here would require not triggering `onDragStart` on click or triggering `onDragEnd` after the click is done.

reproduce steps

1- https://codesandbox.io/s/zealous-drake-q3ube?file=/src/ShowcaseLayout.js:1923-1932
2- click on an item and check the logs

**Comment by nathantech1990** [comment]
I'm also running into this.

**Comment by ContiGabriel** [comment]
Weird, I am not getting this behaviour

**Comment by dseliukov** [comment]
Same here. My workaround is to set another event handler on handle's onClick, in which I set isDragging = false.

**Comment by nathantech1990** [comment]
> Same here. My workaround is to set another event handler on handle's onClick, in which I set isDragging = false.
> I think the issue is not directly related to react-grid-layout lib, but rather [react-draggable](https://github.com/STRML/react-draggable)

Nice. I came to a similar workaround, just using `onDrag` and `onDragStop`. In my case, I'm using it to prevent clicks on links when dragging so a user doesn't accidentally open a link when they are trying to rearrange the grid.

1. Declare `isDragging` state
`const [isDragging, setIsDragging] = useState(false);`

2. Create handlers for `onDrag` and `onDragStop`. Conditional in `handleDrag` is to ensure it is not called continually
```
const handleDrag = () => {
    if (!isDragging) {
        setIsDragging(true);
    }
}

const handleDragStop =() => {
    setIsDragging(false);
}
```

3. Use `useEffect` to do the work
```
useEffect(() => {
    if (isDragging) {
        // Do one thing
    }
    else {
        // Do a different thing
    }
}, [isDragging]);
```

**Comment by dseliukov** [comment]
> > Same here. My workaround is to set another event handler on handle's onClick, in which I set isDragging = false.
> > I think the issue is not directly related to react-grid-layout lib, but rather [react-draggable](https://github.com/STRML/react-draggable)
> 
> Nice. I came to a similar workaround, just using `onDrag` and `onDragStop`. In my case, I'm using it to prevent clicks on links when dragging so a user doesn't accidentally open a link when they are trying to rearrange the grid.
> 
> 1. Declare `isDragging` state
>    `const [isDragging, setIsDragging] = useState(false);`
> 2. Create handlers for `onDrag` and `onDragStop`. Conditional in `handleDrag` is to ensure it is not called continually
> 
> ```
> const handleDrag = () => {
>     if (!isDragging) {
>         setIsDragging(true);
>     }
> }
> 
> const handleDragStop = () => {
>     setIsDragging(false);
> }
> ```
> 
> 1. Use `useEffect` to do the work
> 
> ```
> useEffect(() => {
>     if (isDragging) {
>         // Do one thing
>     }
>     else {
>         // Do a different thing
>     }
> }, [isDragging]);
> ```

This is way clearer than what I was doing, thanks!

**Comment by buggedcom** [comment]
I found this due to the same problem, however I think the solution is a lot easier than above.

```
   const handleDragStart = useCallback((layout, oldItem, newItem, placeholder, e) => {
        window.addEventListener('mouseup', handleDragEnd);
        // rest of the code
    }, []);

    const handleDragEnd = useCallback(() => {
        window.removeEventListener('mouseup', handleDragEnd);
    }, []);
```

**Comment by agg23** [comment]
Whether or not `onDragEnd` should fire, the `GridItem` definitely needs to reset the `draggable` state.

`GridItem.jsx#L414`:
```
    this.setState({ dragging: newPosition });

    // Call callback with this data
    const { x, y } = calcXY(
      this.getPositionParams(),
      newPosition.top,
      newPosition.left,
      this.props.w,
      this.props.h
    );

    return onDragStart.call(this, this.props.i, x, y, {
      e,
      node,
      newPosition
    });
  };
```

However, if `onDragStart.call` returns `false`, denoting a cancellation of the drag event, the `dragging` state is not reset. This has the side effect of breaking grid resizing (as the tile is being "dragged" during the resize events).

**Comment by agg23** [comment]
As stated in my previous comment, there is an actual bug here, regardless of the decision behind the callback issue in the title.

**Comment by jmtimko5** [comment]
Can we reopen, I am also seeing this bug.

**Comment by viktorrudi** [comment]
Bump - I am also stuck on this bug.

**Comment by w3ichen** [comment]
I found a workaround for this by using a custom component and separating out the dragging to a drag handle, such that clicking on the rest of the grid item will not cause dragging. Although clicking on the drag handle without dragging will still cause a `onDragStart` event

**Image of grid items with the drag handle**
![image](https://user-images.githubusercontent.com/57570491/154857211-9635a7e4-dcdc-47cf-af92-3066a40b7ca0.png)

**Parent component**
```
import React, { useState } from "react";
import ReactGridLayout from "react-grid-layout";
import AppInput from "./AppInput";

const COLS = 10;
export default function InputsSection() {
  const [isDragging, setIsDragging] = useState(false);
  console.log("isDragging", isDragging);

  return (
    <ReactGridLayout
      className="layout"
      cols={COLS}
      rowHeight={70}
      width={1000}
      onDragStart={() => setIsDragging(true)}
      onDragStop={() => setIsDragging(false)}
    >
      {["one", "two", "three"].map((key) => (
        <AppInput key={key} />
      ))}
    </ReactGridLayout>
  );
}
```

**Child Component**
```
import { DragIndicator } from "@mui/icons-material";
import { IconButton } from "@mui/material";
import React, { forwardRef, ReactChild } from "react";
interface Props {
  children?: ReactChild | ReactChild[];
  onMouseDown?: (e: any) => void;
}

const AppInput = forwardRef(({ children, onMouseDown, ...rest }: Props, ref) => {
  return (
    <div {...rest}>
      <IconButton onMouseDown={onMouseDown} sx={{ cursor: "move !important" }}>
        <DragIndicator />
      </IconButton>
      HELLO
      {children}
    </div>
  );
});
export default AppInput;
```

In the child component, `react-grid-layout` passes a number of props into `rest`, all of those props are passed to `div` except for `onMouseDown`, which is passed to the drag handle (IconButton)

**Comment by briansotodo** [comment]
I'm also running into this.

**Comment by lexnim** [comment]
Looks like this issue is caused as a result of this fix https://github.com/react-grid-layout/react-grid-layout/pull/1023

**Comment by pxim** [comment]
![image](https://github.com/user-attachments/assets/0b8b47e5-8d24-4390-95ee-2c7c49c7e05a)
![image](https://github.com/user-attachments/assets/73475763-10f9-43ef-a236-458ce3471045)

I have the same error

react-grid-layout   "version": "1.5.0",

**Comment by chetanbaghel1996** [comment]
Stuck at this, Same for resize as well

**Comment by chetanbaghel1996** [comment]
Used something like


isEqual from lodash

  const onResizeStop = (layout: Layout[], oldItem: Layout, newItem: Layout) => {
    if (isEqual(oldItem, newItem)) return;
