### ISSUE TITLE
Drag distance to move an item isn't equal in all directions

### ISSUE THREAD

**Issue by tom-james-watson** [STRML/react-grid-layout#126]
I think this is best explained with a gif:

![movement](https://cloud.githubusercontent.com/assets/3852719/11168743/59f3cc3a-8b9d-11e5-9ee5-e417322fe602.gif)

As you can see, I only need to move a few pixels (which is too little) to move the item upwards, but to move it down I have to move it much further (which is too much). Thoughts? Is this something that is going to be worked on? I can look into making a fix myself if you like?

**Comment by tjphopkins** [comment]
I am also having this issue with version 0.9.2. Has there been any progress?

**Comment by tjphopkins** [comment]
It seems that this is caused by item heights being 1 unit. If the heights are doubled, and the widths, rowHeight and number of cols are adjusted accordingly, the problem is fixed and an item is repositioned when it is dragged half-way over the new position, as in the demos.

**Comment by STRML** [comment]
@tom-james-watson Could you check this with `0.10`? A lot of code has changed since then and I'm not seeing this issue in the demos.
