### ISSUE TITLE
Drop new item does not work when grid is empty

### ISSUE THREAD

**Issue by pikkoui** [STRML/react-grid-layout#1261]
When there are no items i cannot drop a new one. But when there is at least one then you can add. 
steps: 
1)Try to Drag Me into grid when empty: Not working
2)Add New item with button
3) Try to drag new item works

Sandbox example below:
`https://codesandbox.io/s/react-grid-layout-ggefu`

**Comment by lazarnikolic1983** [comment]
I had the same issue. You need to give to a grid some height. You can do it with paddings or by some initial grid height. Then it will work
