### ISSUE TITLE
isBounded is not working?

### ISSUE THREAD

**Issue by Taymindis** [STRML/react-grid-layout#1262]
I am trying to do isBounded={true} in react grid layout but it's not working.

**Comment by ContiGabriel** [comment]
It is working for me, are you on version 1.0.0?

**Comment by Taymindis** [comment]
yup, my all library, but no luck, it always out of the box

```json
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "lodash": "^4.17.19",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-grid-layout": "^1.0.0",
    "react-hotkeys-hook": "^2.2.2",
    "react-scripts": "3.4.1",
    "styled-components": "^5.1.1"
```

**Comment by phongtran-uit** [comment]
> I am trying to do isBounded={true} in react grid layout but it's not working.

i'm too, my version is 1.0.0 but it not working. anybody helpp!

**Comment by bhas1322** [comment]
Can anyone help me with the usage of isBounded in 'react-grid-layout' ? What is this used for?

**Comment by Mossarella** [comment]
> Can anyone help me with the usage of isBounded in 'react-grid-layout' ? What is this used for?

3 years late but https://react-grid-layout.github.io/react-grid-layout/examples/16-bounded.html. Basically it prevent the draggable box to go outside main space.
