### ISSUE TITLE
Resize width of the grid when free space appears

### ISSUE THREAD

**Issue by watermellon2018** [STRML/react-grid-layout#1264]
How change width of the grid when sidebar close/open? Now the content of the grid is simply shifted to the side, but does not change the size and there is free space in the grid

**Comment by watermellon2018** [comment]
Edit: In ResponsiveGridLayout

**Comment by pohsiu** [comment]
Same issue

**Comment by watermellon2018** [comment]
Maybe exist altertanive component for this target (also supported the graggable)?

**Comment by watermellon2018** [comment]
I use react-sizeme. It work for me

**Comment by BruceWheaton** [comment]
Can you please explain how you used react-sizeme? It doesn't seem to be a drop-in replacement for a WidthProvider.

**Comment by iamjoshua** [comment]
The HOC provided by react-sizeme just returns a "size" prop (I think) but react-grid-layout needs a "width" prop. 

This post worked for me: 
https://github.com/STRML/react-grid-layout/issues/212#issuecomment-210468938
