### ISSUE TITLE
[Drag from outside] Terrible performance

### ISSUE THREAD

**Issue by ggcatu** [STRML/react-grid-layout#1265]
From 0.8.13 seems like the dragging from outside actually allows you to move the component in the grid before dropping it, but sadly it performs really laggy and sometimes even crashes? Tried 1.0.00 but same thing happens

https://codesandbox.io/s/distracted-pascal-hdyqv?file=/src/ShowcaseLayout.js

https://codesandbox.io/s/react-grid-layout-forked-6dhk8?file=/src/index.js

**Comment by yasotnik** [comment]
Hey, @ggcatu I have the same issue. 
![RGL Example](https://user-images.githubusercontent.com/5897195/90247426-d3215a00-de36-11ea-9492-37a9376a77b7.gif)

The performance drops dramatically when I try to drag item from the outside. 
Can someone from dev team @STRML take a look please?

**Comment by PhilSchwerttraeger** [comment]
Having the same issue here. It does not even accept the final drop-off-event.
Only occurs in Firefox (v80.0.1), Chrome is fine.

**Comment by ggcatu** [comment]
@STRML Do you have any tips here? Are you successfully using the drag from outside functionality?

**Comment by STRML** [comment]
Slowness on one browser but not another is really quite odd. I can replicate this in Firefox, but I don't know the cause and don't have the time to get down to it. 

I've attached a Firefox trace for someone who wants to take a deeper look, but of course it's trivial to record your own.

[slow-drag-from-outside.json.zip](https://github.com/STRML/react-grid-layout/files/5219741/slow-drag-from-outside.json.zip)

These very long dragover events seem to be the culprit, 52ms is an eternity.

<img width="1197" alt="Screen Shot 2020-09-14 at 12 25 01 PM" src="https://user-images.githubusercontent.com/1197375/93111960-6099d900-f685-11ea-8f0d-5b3dcaa3ae34.png">

**Comment by jumpjili** [comment]
Is there any update on this thread
