### ISSUE TITLE
Items shuffle when you drag items over each other, for horizontal compact grid layout

### ISSUE THREAD

**Issue by vinojv** [STRML/react-grid-layout#1271]
When the grid item occupies 50% of the screen width, there is a weird behaviour while you drag over other items.
it starts to shuffle items.

You can reproduce it in [CodeSandbox](https://codesandbox.io/s/silly-sunset-kt4wx?file=/src/ShowcaseLayout.js
).
![Screen Recording 2020-08-25 at 1 34 09 PM](https://user-images.githubusercontent.com/7531234/91174390-d224de00-e6fc-11ea-99cb-7e2b0c944edc.gif)

**Comment by elleveldy** [comment]
Also struggling with this, did you figure out a solution?
