### ISSUE TITLE
Port for VueJS

### ISSUE THREAD

**Issue by timothymarois** [STRML/react-grid-layout#1272]
Is it possible to have this ported over to vuejs?

I have been through many grid systems, most jQuery related, but they are all either out-dated or abandoned.

This one looks very feature-rich, and wondering if it could be ported over to vuejs? 

Thanks

**Comment by youthereSun** [comment]
> Is it possible to have this ported over to vuejs?
> 
> I have been through many grid systems, most jQuery related, but they are all either out-dated or abandoned.
> 
> This one looks very feature-rich, and wondering if it could be ported over to vuejs?
> 
> Thanks
you can use vuera to archive it
