### ISSUE TITLE
Resizable handlers incorrectly resizing 

### ISSUE THREAD

**Issue by LorenzHenk** [STRML/react-grid-layout#1276]
![resize](https://user-images.githubusercontent.com/10603631/92234041-a0a4d300-eeb1-11ea-8fa7-31e861a00749.gif)

As you can see in the gif above, resizing with handles on the top or right do not work as expected. They should also edit the `x` and `y` properties of the item, not just the `width` and `height`.

See the new example (17, resizable handles). Seems like the following link (https://strml.github.io/react-grid-layout/examples/17-resizable-handles.html) is not working, I believe you have to upload the built examples.

**Comment by MarkyDeParky** [comment]
I'm experiencing the same issue as @LorenzHenk . I've set the resizeHandles to "sw" and "se" and in my case "sw" is not behaving like I expect it to. I would expect it to 'expand' to the left when I move my mouse to the left. Also, the mouse cursor on Mac isn't correct (and different from what @LorenzHenk shows in his animation). On Mac it's the same arrow pointing to bottom right as with the SE handle.

![Sep-22-2020 12-09-34](https://user-images.githubusercontent.com/16799069/93869935-cf51e480-fccc-11ea-999e-ba36105cca3c.gif)

Another thing that would be nice, but maybe this is more of a feature request, is that handles only appear if expanding is possible in that direction. So "SE" would only appear if the item isn't already 'docked' to the far right, and "SW" would only appear if the item isn't docked to the far left. 

![Sep-22-2020 12-11-35](https://user-images.githubusercontent.com/16799069/93870328-5b640c00-fccd-11ea-92b0-844454325871.gif)

**Comment by LorenzHenk** [comment]
> Also, the mouse cursor on Mac isn't correct (and different from what @LorenzHenk shows in his animation). On Mac it's the same arrow pointing to bottom right as with the SE handle.

I do have this problem as well. It doesn't appear in my recording, because for the recording I modified an official example. The examples have different styles applied. In [the example styles](https://github.com/STRML/react-grid-layout/blob/master/examples/resizable-styles.css), the cursor is set correctly.
In the [actual styles](https://github.com/STRML/react-grid-layout/blob/master/css/styles.css#L45), the other cursors are not styled differently.

I'll create a PR for the cursor styles problem.

> Another thing that would be nice, but maybe this is more of a feature request, is that handles only appear if expanding is possible in that direction. So "SE" would only appear if the item isn't already 'docked' to the far right, and "SW" would only appear if the item isn't docked to the far left.

Don't forget about shrinking. This would only make sense if the item size was the minimum allowed size. Else you could still use the handle to shrink the item.

Excerpt from the issue template:
> Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

So let's please keep the focus of this issue on the original bug I've reported :grin:

**Comment by MarkyDeParky** [comment]
> > Also, the mouse cursor on Mac isn't correct (and different from what @LorenzHenk shows in his animation). On Mac it's the same arrow pointing to bottom right as with the SE handle.
> 
> I do have this problem as well. It doesn't appear in my recording, because for the recording I modified an official example. The examples have different styles applied. In [the example styles](https://github.com/STRML/react-grid-layout/blob/master/examples/resizable-styles.css), the cursor is set correctly.
> In the [actual styles](https://github.com/STRML/react-grid-layout/blob/master/css/styles.css#L45), the other cursors are not styled differently.
> 
> I'll create a PR for the cursor styles problem.

That's awesome!
> 
> > Another thing that would be nice, but maybe this is more of a feature request, is that handles only appear if expanding is possible in that direction. So "SE" would only appear if the item isn't already 'docked' to the far right, and "SW" would only appear if the item isn't docked to the far left.
> 
> Don't forget about shrinking. This would only make sense if the item size was the minimum allowed size. Else you could still use the handle to shrink the item.

You're absolutely right. It's more than just looking at growing, it's also about shrinking which probably makes it more complex to solve this.
> 
> Excerpt from the issue template:
> 
> > Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.
> 
> So let's please keep the focus of this issue on the original bug I've reported 😁

Thanks for pointing that out. To be honest, I wasn't exactly sure if this could be part of the bug. I was hoping that maybe this was already implemented but somehow failed due to the issue you described. 
Thanks for your reply! And by the way to all the devs: awesome library...

**Comment by STRML** [comment]
Hi everyone. This is going to be a difficult bug to tackle, as resizing was never meant to change the *position* of an item, which is always determined by top-left grid units. Fixing this requires a rework of resizing entirely. Perhaps there is an elegant way to do so, perhaps there is good impetus here to refactor resizing and dragging and compacting into *Interfaces* that can then be pluggable as in #346.

**Comment by LorenzHenk** [comment]
As the plugin system you mentioned does not yet exist (correct me if I'm wrong), I guess focusing on fixing the bug has priority over creating said plugin system.

**Comment by sdeepsec** [comment]
Can anyone tell if there is any update on this issue ? I am experiencing the same thing.

**Comment by ztb42** [comment]
I'm having the same issue. Was this never taken care of?

**Comment by miryam1003** [comment]
Is there a solution for this problem? 🤔
Thank you in advanced!

**Comment by RegiByte** [comment]
lol it's december 27 and I just got a ticket open for this exact same bug 😅

**Comment by STRML** [comment]
Top and left resizing was fixed in #1917
