### ISSUE TITLE
Wrong height for elements

### ISSUE THREAD

**Issue by ben-elsen** [STRML/react-grid-layout#1281]
Hello, 

The height of my element in the grid isn't what I am expecting. I have a rowHeight of 3 and the element has 10 as h in it's layout but the element is rendered with height 120px.. 
I would expect a height of 30px? 

Please see the following link for the example code: https://codesandbox.io/s/musing-cdn-74p60?file=/src/App.js

What I am missing? 

Thanks! 
Ben

**Comment by sachinkreeti** [comment]
Hi, @ben-elsen I am also facing a similar problem, after going through the library code a bit I see that the formula used for the calculating height of a grid item is 
```
colOrRowSize * gridUnits + Math.max(0, gridUnits - 1) * marginPx        // react-grid-layout/lib/calculateUtils.js
```

where
```
gridUnits = h
colOrRowSize = rowHeight
marginPx = 10 // default margin={[10, 10]} and marginPx = margin[1]
```

so in your case, it is becoming
```
colOrRowSize * gridUnits + Math.max(0, gridUnits - 1) * marginPx
= 3 * 10 + Math.max(0, 10-1) * 10
= 30 + 9*10
= 120
```

I don't understand why this has been done. I am thinking of reopening a new issue.
