### ISSUE TITLE
Dragging items that contains images in the grid buggy

### ISSUE THREAD

**Issue by OZZlE** [STRML/react-grid-layout#1282]
First of all, thank you a lot for an awesome module!

When you try to drag on an image inside the grid for example then browsers usually starts dragging the image, like if you want to drag it into another application and save it there etc. This makes the actual dragging of items in the grid very buggy. At least half of the time when I tried to drag on top of an image in Chrome on my Mac it started dragging the image only + then I let go of mousedown and the item starts moving, but it also makes `onLayoutChange` not even fire.

Example:
https://codesandbox.io/s/nice-butterfly-imomg

A have a PR fix below :-)

**Comment by mderkach** [comment]
Possible solution: add `pointer-events: none;` on img.

**Comment by OZZlE** [comment]
@mderkach that is what my linked PR below does.. although on the entire element but CSS => Cascading .. so it will apply to img element as well, perhaps I should change it to only img though since some people use forms with this lib apparently
