### ISSUE TITLE
react-grid-layout doesn't match position of pointer when drop from outside??

### ISSUE THREAD

**Issue by phongtran-uit** [STRML/react-grid-layout#1287]
i see the mouse pointer doesn't match the css position in the grid -layout when i have two grid-layout, one is parent and one is inside it, when i drop drop-element into the child grid-layout, the pointer is not work correctly.
please help, i have a project using your library and i have to fix it in week. :(

**Comment by phongtran-uit** [comment]
becuz i use cssTransfrom, transform is a attribute of css3 and it change the position of item in Grid only by UI, the true position of the Grid-item is on the top of the grid. If anyone have the same problems, just change the props cssTransfom: false. when it's false, the grid layout set the item the css of position, top: ...px, left: ..px. So it will work :)

**Comment by jessegpt** [comment]
Some problem. Did you resolve it?
