### ISSUE TITLE
How can i draggable item in mobile?

### ISSUE THREAD

**Issue by phongtran-uit** [STRML/react-grid-layout#1288]
I can't drag item from outside when i use my phone, what should i do now?
seem like in mobile, draggable={true} isn't work. How could i solve it?

**Comment by phongtran-uit** [comment]
is anybody hereeee, please helppp.

**Comment by phongtran-uit** [comment]
@STRML can you help me with this problems?

**Comment by youthereSun** [comment]
I have the same problem.what should i do

**Comment by youthereSun** [comment]
> I can't drag item from outside when i use my phone, what should i do now?
> seem like in mobile, draggable={true} isn't work. How could i solve it?
did you get the solution bro?

**Comment by phongtran-uit** [comment]
> > I can't drag item from outside when i use my phone, what should i do now?
> > seem like in mobile, draggable={true} isn't work. How could i solve it?
> > did you get the solution bro?

no, still not have solution. I found that, the grid define the postion x y base on html5 attribute draggable={true}, when change to mobile, all method of drag n drop is disable, and it change to touch. But touch event doesnt fire ondrop method, so that why it's not work. You can use drag-drop-touch polyfill to change touch event into drag event. But, i try, but my project still error with polyfill...

**Comment by code31415926535** [comment]
I'm facing the same issue. Anyone found a solution for it?

**Comment by sberney** [comment]
No, I was hoping I had done something wrong. I have this issue too.

**Comment by Ndn1618** [comment]
Has anyone found a solution?

**Comment by Ndn1618** [comment]
> Has anyone found a solution?

@sberney @code31415926535 @phongtran-uit @youthereSun

**Comment by sberney** [comment]
I was going to manually implement the touch logic with absolute positioning, I had a malfunctioning prototype, but then product deprioritized it and I got a new job.

**Comment by NityaJ-Hexaware** [comment]
> I can't drag item from outside when i use my phone, what should i do now? seem like in mobile, draggable={true} isn't work. How could i solve it?

Hi,
I am also facing the same issue. If you have the solution for it, it will be great if you can share it.

**Comment by NityaJain1099** [comment]
> I can't drag item from outside when i use my phone, what should i do now? seem like in mobile, draggable={true} isn't work. How could i solve it?

Hi,
I am also facing the same issue. If you have the solution for it, it will be great if you can share it.

**Comment by calm-prog** [comment]
The [polyfill](https://github.com/Bernardo-Castilho/dragdroptouch) that was mentioned above has a fix for this, but they haven't published a new version on npm that would include it. Currently, the only option to include the fix is to download it from the master branch / use a direct link to the file on the repo as it's suggested [here](https://github.com/Bernardo-Castilho/dragdroptouch) (the latter I would not recommend though).
