### ISSUE TITLE
isResizable prop not hide resize icon and not change cursor from resize shape

### ISSUE THREAD

**Issue by endovitskayaV** [STRML/react-grid-layout#1291]
I upgraded from ^0.17.1 to ^1.0.0 version. 
Previously when isResizable prop of ResponsiveReactGridLayout was false resize icon was not present and cursor was not resize of  shape, but after upgrade even if isResizable is false, resize icon is present  (see pic), and cursor is of resize shape.
Could you please fix this behavior so that it is as before?<br>
![Capture](https://user-images.githubusercontent.com/19566575/93338663-46056280-f833-11ea-8a94-aacce9872660.PNG)

**Comment by arvindkumarpal** [comment]
Facing same issue

**Comment by gknapp** [comment]
Playing with the [sandbox example](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js), when upgrading to 0.18 and up, the resize handle is no longer hidden on grid items when `isResizable: false`.

**Comment by STRML** [comment]
Relates to #892

**Comment by ZimNovich** [comment]
Use this CSS:
```
.react-resizable-hide .react-resizable-handle {
    display: none !important;
}
```
