### ISSUE TITLE
the draggable item outside the container can't be draggale in mobile

### ISSUE THREAD

**Issue by youthereSun** [STRML/react-grid-layout#1295]
the draggable item outside the container can't be draggale in mobile,what should i do

**Comment by code31415926535** [comment]
I am also facing this issue. I have a requirement to implement drag from outside on touch devices as well. What should I do?

**Comment by youthereSun** [comment]
> I am also facing this issue. I have a requirement to implement drag from outside on touch devices as well. What should I do?

i just use ontouchmove / ontouchstart/ ontouchend to implement it.but there is some flaws to be fixed

**Comment by Ndn1618** [comment]
Has anyone found a solution?

**Comment by Ndn1618** [comment]
> Has anyone found a solution?

@youthereSun @code31415926535
