### ISSUE TITLE
ReactGridLayout children are rendered on top of each other by x coordinates 

### ISSUE THREAD

**Issue by ratnev** [STRML/react-grid-layout#1301]
The problem is that the layout object as:

const gridLayout = [
  { i: '1', x: 0, y: 0, w: 1, h: 2 },
  { i: '2', x: 1, y: 0, w: 1, h: 2 },
  { i: '3', x: 0, y: 1, w: 1, h: 2 },
  { i: '4', x: 1, y: 1, w: 1, h: 2 }
];

is rendering items 1, 2 on top of each other 
and 3, 4 as well. But items 1,2 and 3,4 are positioned correctly vertically. 

The container with class name "react-grid-layout" has 0 width and correct height. 

I can drag items vertically but can't horizontally

**Comment by ratnev** [comment]
I've managed to render the items without overlaying each other, but all the items are placed vertically. Changing the 'x' in the array doesn't affect the position of each child horizontally. The transform property for each child has the same coordinates for 'x' axis: '10px'.

**Comment by leevimatias** [comment]
I'm also facing the same issue.

**Comment by anhba817** [comment]
I'm also facing the same issue. Does anyone know how to fix this?
