### ISSUE TITLE
Grid gaps despite margin and padding set to [0, 0]

### ISSUE THREAD

**Issue by FrederikStenberg** [STRML/react-grid-layout#1305]
Despite setting margin={[0, 0]} and containerPadding={[0, 0]}, sometimes a 1px gap will appear between items. 

Example: https://lkpzy.csb.app/

There's a gap between 3rd and 4th column. 

First I thought this was related to my own project and working with decimal calculations, but after also finding this issue in the sandbox, I can confirm it is a bug.  

The issue does seem to differ depending on window size, so I've attached an image to show my view.
![Skærmbillede 2020-10-02 kl  14 21 42](https://user-images.githubusercontent.com/16336824/94922499-a4307780-04ba-11eb-944f-52ce9c84fa96.png)

**Comment by FrederikStenberg** [comment]
Still an issue

**Comment by usercao** [comment]
@STRML This problem still exists, he should not be closed.

**Comment by STRML** [comment]
@usercao on 1.4.1?

**Comment by usercao** [comment]
@STRML Yes. I'm glad you're still following this project. I will provide a minimum repo tomorrow to reproduce this issue.

**Comment by usercao** [comment]
@STRML The issue has been updated, please check #1939 .
