### ISSUE TITLE
react-grid-layout - when width change,grid items dosn't auto correct the width

### ISSUE THREAD

**Issue by TrickTrackers** [STRML/react-grid-layout#1314]
If we minimize the browser window,grid items are aligned properly.
But if we change width of react-grid-layout using toggle button,grid systems is overlapped with toggled element.
Tried with setstate,but not working. Any solution please?

**Comment by phongtran-uit** [comment]
i did it and it work ok my friend. you just defind maxRow, col, when reszie width of react-grid-layout, you just caculate the rowheight, w ,h of grid-item. so it will work.

**Comment by OwaisRaza98** [comment]
@phongtran-uit can you please show a code example of how to do it?

**Comment by phongtran-uit** [comment]
> @phongtran-uit can you please show a code example of how to do it?

My code is in company's project, so i cant show to you.
RGL has pure component so if you want to setState layout, make the difference reference layout and setState it, it will work. Becuz Shouldcomponentupdate just compare shallow code.
