### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by master117** [STRML/react-grid-layout#1316]
I assume IE11 is supposed to be supported? The showcase page does not work in IE11.

**Comment by redArcherr** [comment]
求支持ie10 11

**Comment by master117** [comment]
ie10还有意义吗？它只有0.02%的浏览器份额。

**Comment by master117** [comment]
Bump because issue isn't stale

**Comment by master117** [comment]
Hunh? Why did this get closed? I can't change labels or remove the stale comment.
