### ISSUE TITLE
resizeHandle prop does nothing

### ISSUE THREAD

**Issue by kylesureline** [STRML/react-grid-layout#1317]
The `resizeHandle` prop (as mentioned [here](https://github.com/STRML/react-grid-layout#grid-layout-props)) doesn't appear to exist on the ReactGridLayout component. It does seem to be implemented on the GridItem component and ReactGridLayoutPropTypes, however.

Also, I noticed that this example is producing a 404: https://strml.github.io/react-grid-layout/examples/17-resizable-handles.html

**Comment by typeetfunc** [comment]
version with this changes not released yet https://github.com/STRML/react-grid-layout/pull/1303

**Comment by kylesureline** [comment]
🤦 my bad. Well, I'll patiently wait for the release. Thanks!!

**Comment by dwb1994** [comment]
shouldn't appear on readme.md if the changes not released 😡

**Comment by davidbejarcaceres** [comment]
Any news?  resizeHandle is doing nothing
resizeHandle: resizeHandle={axis => {
      return <TdIcon axis={axis} medium iconName={'arrowDown'} />;
    }}

**Comment by curtislin7** [comment]
+1, a new release with this feature would be much appreciated. Thanks guys!
