### ISSUE TITLE
ResponsiveReactGridLayout can not set width prop

### ISSUE THREAD

**Issue by cnvoid** [STRML/react-grid-layout#1320]
Hi, I found the bug. 

```
import { Responsive, WidthProvider } from 'react-grid-layout'
const ResponsiveReactGridLayout = WidthProvider(Responsive)

<ResponsiveReactGridLayout
  width={1000}     //  this prop will not work

>xxxx</ResponsiveReactGridLayout>
```

The __width__prop can not set,  and the default with is 0,  and the item inside will not can be resized.

**Comment by leevimatias** [comment]
I second this. When I try to use the responsive layout the grid items will set to width 1 and rendered on top of each other on the first render.

**Comment by gph5003** [comment]
I am experiencing this issue as well. Has anyone found a solution or work around?
