### ISSUE TITLE
Toggling static mode for grid items resets the positions and sizes of grid items

### ISSUE THREAD

**Issue by RATIU5** [STRML/react-grid-layout#1322]
I am not sure if I did something wrong, but I created a button to toggle between static and non-static mode of the grid items. When they are not static, I move and resize them around to where I want. Then I toggle static mode on. They move around, change their size, and then become static. When I toggle the static back off, they move back to their original positions with their original sizes, not where I left them. 

I re-created this in [a codepen here](https://codesandbox.io/s/optimistic-violet-fhlk5?file=/src/ShowcaseLayout.js) to show it happens in other cases, not just my code here:

```jsx
import React, { useState } from "react";
import Head from "next/head";
import GridLayout from "react-grid-layout";

export default function Home() {
	let [layout, setLayout] = useState([
		{ i: "a", x: 0, y: 0, w: 10, h: 4, static: false },
		{ i: "b", x: 1, y: 0, w: 3, h: 2, static: false },
		{ i: "c", x: 4, y: 0, w: 1, h: 2, static: false },
	]);

	function toggleStaticMode() {
		setLayout(
			layout.map((l) => {
				console.log(!l.static);
				return { ...l, static: !l.static };
			})
		);
	}

	return (
		<div>
			<main>
				<button className={styles.button} onClick={toggleStaticMode}>
					Toggle Static Mode
				</button>
				<GridLayout
					className="layout"
					layout={layout}
					cols={4}
					rowHeight={100}
					width={1200}>
					<div key="a" className={styles.cell}>
						Hello A
					</div>
					<div key="b" className={styles.cell}>
						Hello B
					</div>
					<div key="c" className={styles.cell}>
						Hello C
					</div>
				</GridLayout>
			</main>
		</div>
	);
}
```
I would rather this work or get fixed so I don't have to store the positions in local storage every time the toggle static button is clicked.

**Comment by TikTikTik21** [comment]
Same problem

**Comment by RATIU5** [comment]
I am not entirely sure if it was a problem or what the problem was, but I found a solution that fit all my needs [found here (StackOverflow](https://stackoverflow.com/questions/64597519/toggling-the-static-key-boolean-in-layout-object-of-a-react-grid-layout-causes-a).
