### ISSUE TITLE
Layout Incorrect while Drag-Drop New Element into the Grid

### ISSUE THREAD

**Issue by TreeNewBeeing** [STRML/react-grid-layout#1324]
When I tried to implement a feature that I can drag an element from outside into the grid. 

I used onDrop event to assign the new layout variable to props of the grid. And when I tried to drag the new element from outside and place it on the top of the existing elements, it did not appears there but falls down to the bottom of them. When I am checking the data flow, I found that before I pass the props into the grid, the layout is correct on position with correct x, y. I am not sure what happens inside, causing this behavior. 

Details can be found through the codesandbox page.
[https://codesandbox.io/s/quirky-knuth-u78sp?file=/src/App.js](https://codesandbox.io/s/quirky-knuth-u78sp?file=/src/App.js)

When I drag from 'drag here', and place it on the top of yellow card, it falls down to the bottom of it.

**Comment by vocko** [comment]
I will attach to this one as it seems to be a related issue, create a new one of it is not.

There seem to be multiple issues with dragging items from the outside. One is the placement described above, another is the fact you can't drop the item on the shadowed target area (these two might be actually related, but I'm not sure). Cursor appears to be `not-allowed` and you have to move your mouse out of the shadowed area to drop it, otherwise the `ondrop` handler is not called. This is not very nice user experience.

You can verify this behavior on the link above or also in this demo:
https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html

**Comment by trace59** [comment]
> When I tried to implement a feature that I can drag an element from outside into the grid.
> 
> I used onDrop event to assign the new layout variable to props of the grid. And when I tried to drag the new element from outside and place it on the top of the existing elements, it did not appears there but falls down to the bottom of them. When I am checking the data flow, I found that before I pass the props into the grid, the layout is correct on position with correct x, y. I am not sure what happens inside, causing this behavior.
> 
> Details can be found through the codesandbox page. https://codesandbox.io/s/quirky-knuth-u78sp?file=/src/App.js
> 
> When I drag from 'drag here', and place it on the top of yellow card, it falls down to the bottom of it.

Hello, I also encountered this problem, is there a good solution?

**Comment by trace59** [comment]
> I will attach to this one as it seems to be a related issue, create a new one of it is not.
> 
> There seem to be multiple issues with dragging items from the outside. One is the placement described above, another is the fact you can't drop the item on the shadowed target area (these two might be actually related, but I'm not sure). Cursor appears to be `not-allowed` and you have to move your mouse out of the shadowed area to drop it, otherwise the `ondrop` handler is not called. This is not very nice user experience.
> 
> You can verify this behavior on the link above or also in this demo: https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html
> 
> **EDIT** The drop issue seems to be Firefox only and a fix has been provided in the #1053. Can it be merged into the trunk please?

Hello, I also encountered this problem, is there a good solution?

**Comment by mbrn** [comment]
Hi, I have also this problem too. Is there anyone who fixed this?

@trace59 , @TreeNewBeeing

**Comment by alexpate** [comment]
If anyone else run in to this issue, I managed to fix this in my app by setting the `y` value of the dragging item to -1. I think when there's two items that have the same Y value, the old one wins out. 

Example here: https://github.com/tryglow/glow/blob/main/app/components/EditWrapper.tsx#L93
