### ISSUE TITLE
Height problem 

### ISSUE THREAD

**Issue by ibrghoutn** [STRML/react-grid-layout#1325]
Hi everyone,

how can i make the container of each item to take the height of content.

i hope this image can help you to understand the problem.

![image_2020_11_05T10_25_54_904Z](https://user-images.githubusercontent.com/37867080/98229708-898a6c00-1f5a-11eb-805f-b6dcfe715ff1.png)

**Comment by faizaankhan** [comment]
This is a big need.
1. Letting the content take up height
2. Being able to define the max height
