### ISSUE TITLE
WidthProvider width is initally 0 preventing resizing of grid item width

### ISSUE THREAD

**Issue by gph5003** [STRML/react-grid-layout#1327]
When using WidthProvider(Responsive) the width of the provider component is 0 which puts all items on the left hand side and cannot resize them or drag and drop them horizontally. The interesting thing is that once the window is resized, the WidthProvider acts normally. If my browser session expires or I delete all cookies, the issue returns. This is an issue because I am saving coordinates and width per user on layout change, so every time their session expires the items default back. I have tried hard coding the width and that doesn't help. Also tried setting measureBeforeMount = true. See attached for showing state.width is 0

![gridlayoutIssue](https://user-images.githubusercontent.com/11930329/98570151-1b5ae780-2281-11eb-9d9f-ffa7330d0cf7.png)

**Comment by gph5003** [comment]
Duplicate of #1320

**Comment by gph5003** [comment]
Duplicate of #1338

**Comment by jocon128** [comment]
I am having the same issue. Did you work out the issue @gph5003 ?

**Comment by gph5003** [comment]
I never did find a solution with the width provider and responsive grid. I ended up using react-grid-layout (non responsive version) and that works fine

**Comment by PrieurA** [comment]
I have the same issue, all my items are on the left side, I can't resize them but when using non-responsive everything is working well. I am still looking for a solution.

https://user-images.githubusercontent.com/47487590/103773323-2c2e9c00-502b-11eb-88a0-0e069cb7fd46.mov

**Comment by jocon128** [comment]
@PrieurA What I ended up doing is setting a min width directly on the grid component.

`style={{ minWidth: "100%" }}`
