### ISSUE TITLE
ResizeHandle props

### ISSUE THREAD

**Issue by TikTikTik21** [STRML/react-grid-layout#1334]
The ResizeHandle props is not working properly.
The west and the north handle are doing the opposite of whats it is suppose to do.

Thank you

**Comment by bogoroh** [comment]
Having the same issue.

**Comment by rrggrr** [comment]
Odd, same issue now.

**Comment by HalimMahmoud** [comment]
double-check if you don't import "../../node_modules/react-resizable/css/styles.css";

**Comment by TikTikTik21** [comment]
I have it imported, the east and south handler are working its just the west and north that isn't working.

**Comment by krishna9626** [comment]
getting the same issue

**Comment by TikTikTik21** [comment]
@STRML Help please

**Comment by JPNZ4** [comment]
I'm getting the same issue.

**Comment by Jonastjenix** [comment]
Same issue here.

**Comment by bogoroh** [comment]
friendly bump
