### ISSUE TITLE
[QUESTION]: Dynamic add and remove example

### ISSUE THREAD

**Issue by simplecommerce** [STRML/react-grid-layout#1335]
Hi,

In this example here, https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html I notice that you use the onLayoutChange to update the layout state.

I was wondering, why do you have to call and update the state change with onLayoutChange when you are already doing a setState on the layout when deleting an item?

I noticed this issue in my project, if I don't put the onLayoutChange, the deleted items reappear when deleting the next one.

Is this normal behavior that we have to use onLayoutChange ?

**Comment by benedict-jackson** [comment]
In that example, when adding or removing, setState is updating the list of items being mapped over as children of the grid. The layout (containing the positions of the children elements) is being automatically adjusted by the grid component to match the children then passed to onLayoutChange.

**Comment by simplecommerce** [comment]
@benedict-jackson Thanks for your reply, I was expecting to be able to pass the layout state via the `layout` prop and expect it to update itself like that without having to call `onLayoutChange` again, it just seemed odd to me when I saw the calls in my logs, thanks for the explanation.
