### ISSUE TITLE
Using react-window to optimize performance in large grid layouts

### ISSUE THREAD

**Issue by rbval** [STRML/react-grid-layout#1336]
We have 81 plotly.js elements that are plotted on the grid-layout and it gets buggy when scrolling down. One option to solve this would be to use `react-window` to render only the elements shown on the screen. Is there a way to use `react-window` in conjunction with `react-grid-layout?

**Comment by aditya-padhi-kbl** [comment]
@rbval 
Did you get a solution for this ?

**Comment by nmanikumar-hubilo** [comment]
@rbval Hey buddy
Did you find the solution for this?

**Comment by jihea-park** [comment]
@rbval 
Did you find any solution?
