### ISSUE TITLE
ResizeHandle not working

### ISSUE THREAD

**Issue by Abhijit-H-Kulkarni** [STRML/react-grid-layout#1337]
Upgraded to latest version but still the resizeHandle doesn't seem to work. It doesn't replace the resizeHandle.

CodeBox : https://codesandbox.io/s/resizable-111-forked-1s770

**Comment by JerryLeeCS** [comment]
I am having the same problem.

**Comment by valtism** [comment]
Yeah, getting this too. It seems to work with a custom component if it is give then class name of `react-resizable-handle`, but then the default styles get applied as well.

**Comment by valtism** [comment]
Ok, figured this out. If you specify a classname using the `draggableHandle` prop, then ensure that your custom element has that same classname, it will work.
