### ISSUE TITLE
Save our react-grid-Layout into a MySQL Database ?

### ISSUE THREAD

**Issue by ddubois2** [STRML/react-grid-layout#1339]
Hello

Is this possible to record the react-grid-layout into a MySQL database and restore it trougth this same database ?

Like said here https://github.com/STRML/react-grid-layout/issues/883, it will be possible...

My idea is to use the local storage to store it in my MySQL database.  Is someone did it  yet ?

Do you have any code example please ?

Thank you in advance.

**Comment by yangguansen** [comment]
You can save layout config by JSON.stringify() into your database
