### ISSUE TITLE
onDrop is not called dragging from outside, please suggest

### ISSUE THREAD

**Issue by gaow1423** [STRML/react-grid-layout#1348]
package.json:
![image](https://user-images.githubusercontent.com/25094170/100944031-41a42980-34b3-11eb-9f78-18bf8c10d4a7.png)
I even tried different versions of react-grid-layout and react-draggable, it does not work

try to follow the drag from outside example here: https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html
![image](https://user-images.githubusercontent.com/25094170/100944373-03f3d080-34b4-11eb-80fe-67984a2750b9.png)

The outside element can be dragged, but it just can't be dropped inside the grid( in both chrome and firefox). The 'onDrop' above is not triggered at all. I even use the same example code above, still no luck.  please suggest do I miss anything?

**Comment by TomasKomprs** [comment]
Hi, @STRML 
I can see this is closed but I gess this bug still exist. We start using this library(v1.2.0) for new project. And one of main feature is drag element from outside. 
Mostly works well but sometimes element didint drop. From what I can tell issue is with onDrop props. If I drop element and nothing happend then I can see onDrop wasnt call at all.
We tested this with chromium based (Chrome/Brave) and Firefox browsers so far. We apply Firefox "hack" from docs and from what I can say Firefox works 100% but Chromium around 90%.

Similar works yours demo for Chromium: https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html 
Firefox didint work at all but I gess there is no firefox "hack" included. But the main issue is with Chromium.

 Any ideas how to fix this?

**Comment by conviva-zyang** [comment]
@TomasKomprs  Same issue. Do you have any ideas to fix it?
