### ISSUE TITLE
Nested Dropping

### ISSUE THREAD

**Issue by stuck1233333** [STRML/react-grid-layout#1354]
When I have a grid inside a grid, I want to items from my outside grid to be able to be dropped into an inside grid, while still being draggable in the outside grid. I'm unable to do this. Other libraries support this notion of drop targets https://react-dnd.github.io/react-dnd/examples/nesting/drop-targets. How do I accomplish this with react grid layout?

**Comment by EssamEid614** [comment]
up, this is a pretty decent feature to have.. i tried implementing this by myself by making the grid layout that is being dragged over active however the highlighted element remains as is in the parent container and sometimes the dropping item will be undefined ! im not sure why that is happening ? @STRML

**Comment by CareyToboo** [comment]
Do you have a demo ? I also want to implement nested drag and drop. @EssamEid614 @stuck1233333

**Comment by WakerCN** [comment]
Did you resolve this problem @CareyToboo

**Comment by EssamEid614** [comment]
Hey @CareyToboo @WakerCN I dont have the code atm, but i remember what i did was set the parent i want to drag components into as a `static` one which is not `draggable` and removed the collision property ( i dont remember which one it was ) which would stop elements pushing each other. that way got it to work but it was extremely flaky. sometimes it would work other times it wouldn't so it wasn't extremely reliable.
