### ISSUE TITLE
Can I provide the actual pixel width of grid item?? Need fixed width for each box.. Please help

### ISSUE THREAD

**Issue by gaow1423** [STRML/react-grid-layout#1355]
All boxes are rendered based on the width and height in radio. This brings up the problem that all boxes need to be refreshed to accommodate the new dimension when the width of the browser is changing. This can be resolved if the library allows for the fixed width of each grid item. Please suggest if there is a way or work-around to make the width of the grid item fixed even if windows size is changing.

**Comment by EricRabil** [comment]
I'm trying to make something with a layout similar to https://tweetdeck.twitter.com/, but that also would require fixed widths. Would be very helpful.
