### ISSUE TITLE
data-grid not controllable by state

### ISSUE THREAD

**Issue by hanselsen** [STRML/react-grid-layout#1358]
Thanks for the great project! I see a lot of potential.  
At this moment, I wish to create a dashboard with items and should be editable.
I can't seem to figure out how to set the layout in a controlled way (as in state-controlled).

This pen is a simplified version of what I am using.

https://codepen.io/hanselsen/pen/XWjRXgy

I wish to make the 'reset' button work.

I think it has to do that data-grid is not controlled.

Can i get any help with this?

**Comment by BurtonFeng** [comment]
You can set the layout to look at the state.

    <ResponsiveGridLayout   
            isDraggable
	        isBounded
            breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
	        cols={{ lg: 4, md: 4, sm: 2, xs: 2, xxs: 1 }}
            onLayoutChange={(tiles, layouts) => { setTiles(tiles) }}
	        rowHeight={150}
            layouts={{ lg:tiles, md:tiles, sm:tiles }}>

	            {tiles.map(tile => (<div className="dashboard-item" key={tile.i}> Dashboard ITEM {tile.i} </div>))}

	</ResponsiveGridLayout>

**Comment by simplecommerce** [comment]
@hanselsen this worked for me

https://github.com/STRML/react-grid-layout/blob/master/test/examples/7-localstorage.jsx
