### ISSUE TITLE
componentWillReceiveProps checking props.width instead of props.initialWidth

### ISSUE THREAD

**Issue by codingismy11to7** [STRML/react-grid-layout#136]
in propTypes, there is only an `initialWidth`, but no `width`, however `componentWillReceiveProps` is checking if `lastProps.width != newProps.width`. I'm not sure what the correct fix is, but I'm currently setting both `width` and `initialWidth` to the same value and the grid is finally happy.

**Comment by STRML** [comment]
There is no more `initialWidth` in `0.10`. Thanks for the report.
