### ISSUE TITLE
Restrict dragging outside of parent element

### ISSUE THREAD

**Issue by rin4ik** [STRML/react-grid-layout#1363]
Is it somehow possible to
prevent grid items to go outside of container div?

**Comment by serkononenko** [comment]
@rin4ik look at this sample [React-Grid-Layout Demo 16 - Bounded](https://strml.github.io/react-grid-layout/examples/16-bounded.html)

**Comment by rin4ik** [comment]
@serkononenko thanks

**Comment by soumak-witbybit** [comment]
Updated Link: https://react-grid-layout.github.io/react-grid-layout/examples/16-bounded.html
