### ISSUE TITLE
GridItem height appears in correct - Margin is multiplied by grid height rather than simply added

### ISSUE THREAD

**Issue by iain-b** [STRML/react-grid-layout#1366]
https://github.com/STRML/react-grid-layout/blob/e4e2b8b054d247ab696bb4e7d6199415b2f45d32/lib/calculateUtils.js#L33

I think how the margin is used in `calcGridItemWHPx` is incorrect? For example if my GridItem is say 10 units high then it will add 10x margin to the height which seems incorrect. 

I'm happy to fix this in a PR but I wanted to make sure I hadn't mistaken anything first.

Also, there is a workaround (sort of). I just set the vertical margin to 0 and adjusted the styling of the content accordingly. Not perfect but ok for my use case.

**Comment by iain-b** [comment]
The root of the issue here is I was setting the height of the Grid Items dynamically based on content. So the logic above is correct it's just not the behaviour I need.

**Comment by vikas-0** [comment]
How did you solve it?
