### ISSUE TITLE
How to reset the layout manually?

### ISSUE THREAD

**Issue by WaqqarSuleman** [STRML/react-grid-layout#1370]
Hi, 

I have a requirement where I have to reset the layout on click of a button. I tried to store my data in the state and reset it to the original data on button click, the state updates the but the UI does not. 
Please tell me how to achieve this.

**Comment by jere-co** [comment]
I needed this feature as well and ended up using `key` to force a remount of the whole thing. 

State:
```TS
const [resetKey, setResetKey] = useState<string>(Date.now().toString());
```

Wrapping div: 
```TS
<div key={resetKey}>
```

And run to reset manually: 
```TS
setResetKey(Date.now().toString());
```

Not ideal but works for me.
