### ISSUE TITLE
Horizontal Compaction feels buggy

### ISSUE THREAD

**Issue by Abhijit-H-Kulkarni** [STRML/react-grid-layout#1372]
RGL with vertical compaction feels more rigid when compared to horizontal compaction. When the compaction is horizontal moving elements in the grid results in some weird positioning of elements which is not expected. Also moving the grid items feels buggy compared to vertical compaction. For my use-case I needed both horizontal and vertical compaction, tried to do it with compactType='horizontal' and verticalCompact=true, but seems that the horizontal compaction is causing issues. Basically if there is some space available for a grid to occupy that space is not being utilized rather it will be pushed to the end. Is anyone having a similar use-case as mine and facing this issue?

Codebox Example : https://codesandbox.io/s/currying-water-xvdtn?file=/src/ShowcaseLayout.js

**Comment by monmush** [comment]
I am facing the same problem

**Comment by justin-restoguru** [comment]
I'm facing the same problem, can someone help me please
