### ISSUE TITLE
Multiple copies of React bug, Meteor environment

### ISSUE THREAD

**Issue by john-osullivan** [STRML/react-grid-layout#138]
Hello,

I'm trying to get this library (running `v0.10.0-beta1`) working in my environment and am having some issues.  When I first create the grid and put things in it, the first element gets rendered and then an error gets thrown:

```
React can't find the root component node for data-reactid value `.0.1.0.0.0.0.2.2.0.0:$/=1$5qPNHoKGJziAoBh2j`. If you're seeing this message, it probably means that you've loaded two copies of React on the page. At this time, only a single copy of React can be loaded at a time.
```

When I dug into the stack trace, it seemed to be a call originating from the `componentDidMount` method of Draggable.  I'm using React 0.14 along with Meteor and Webpack, so the React copy is being exposed via the Webpack `externals` option.  It seems like the library tried to create its own version of React rather than use the one provided by Webpack.  Any thoughts on a fix?

**Comment by STRML** [comment]
Hey John, could you check this with `0.10`?
