### ISSUE TITLE
RGL changes the x,y,h,w of the grid item automatically

### ISSUE THREAD

**Issue by WaqqarSuleman** [STRML/react-grid-layout#1381]
Hi,

I have an implementation of the React Grid Layout Library where I have form fields inside of the grid item children. I calculate the grid params `(x,y,h,w,minW and minH)` whenever I have to add a new field to my form. After adding a new field it comes after the last field as it should. However, when I edit a field and save it, my grid params change automatically, i.e. `x becomes 0, y gets incremented, and w & h becomes 1`. I am 100% sure that I am not doing it but it happens somehow.

Can anyone please tell me why this is happeneing? I just cannot seem to figure this out.
Thanks.

**Comment by javanoclaw** [comment]
I have the same problem

**Comment by WaqqarSuleman** [comment]
> I have the same problem

Did you find any solution?

**Comment by GF2595** [comment]
I had kinda same issue. In my case, whenever RGL renders with breakpoint for which it doesn't have previously calculated layout or bigger previously calculated layout, items appear as described above.
Whenever library can't find layout to initialize with is uses [] as initialLayout and gridLayout fills it with items with 1x1 size.
Maybe there is some problem with the way you save layout?

**Comment by CooderHYLee** [comment]
`onDrop = (layout, layoutItem, event) => {
    alert(`Dropped element props:\n${JSON.stringify(layoutItem, ['x', 'y', 'w', 'h'], 2)}`);
    layout[layout.length - 1].i = `${layout.length - 1}`;
    this.setState({
      layouts:{lg:layout}
    });
}`
