### ISSUE TITLE
Bug: Dragging a tile pushes all other tiles away if verticalCompact is set to false

### ISSUE THREAD

**Issue by jantimon** [STRML/react-grid-layout#1382]
As you can see in this video the tiles which colide are moved and don't fallback to their original position:

![ReactGridCleanUp](https://user-images.githubusercontent.com/4113649/104749446-1e77c580-5753-11eb-8efb-94fc9150782a.gif)

Code:

```jsx
<ResponsiveReactGridLayout
            compactType={null}
            layouts={this.state.layouts}
            onLayoutChange={this.onLayoutChange}
>
            {this.generateDOM()}
</ResponsiveReactGridLayout>
```

or:

```jsx
<ResponsiveReactGridLayout
            verticalCompact={false}
            layouts={this.state.layouts}
            onLayoutChange={this.onLayoutChange}
>
            {this.generateDOM()}
</ResponsiveReactGridLayout>
```

CodeSandbox:

https://codesandbox.io/s/quirky-wilbur-7dnys?file=/src/ShowcaseLayout.js

**Comment by jantimon** [comment]
bump

**Comment by clarkd** [comment]
@jantimon Did you get anywhere with this issue? We are seeing the same and it's not the best experience!
