### ISSUE TITLE
What does lg, md, sm, xs, xxs mean?

### ISSUE THREAD

**Issue by zhaozhiming** [STRML/react-grid-layout#139]
hi, I saw the `cols` and `breakpoints` can be given a number or a object value, when given a object value, the format of the value look like this: `lg: 12, md: 10, sm: 6, xs: 4, xxs: 2`.  
My question is: what does these attributes mean and how to give value to them is correctly? Thanks.

**Comment by zhaozhiming** [comment]
I got it. Sorry to bother here.

**Comment by sgsikuga** [comment]
Sorry, I don't get it. Could you explain their meaning to me?

**Comment by zhaozhiming** [comment]
Sorry, I have forgotten it totally.
