### ISSUE TITLE
Receive size from ReactGridLayout

### ISSUE THREAD

**Issue by jardakotesovec** [STRML/react-grid-layout#14]
I need to know what is real size of individual items so I can position them. Divs receive props.width and props.height, but they don't pass it to MyComponent.

```
    <ReactGridLayout className="layout" cols={12} rowHeight={30}>
      <div key={1} _grid={{x: 0, y: 0, w: 1: h: 2}}><MyComponent /></div>
      <div key={2} _grid={{x: 1, y: 0, w: 1: h: 2}}><MyComponent /></div>
      <div key={3} _grid={{x: 2, y: 0, w: 1: h: 2}}><MyComponent /></div>
    </ReactGridLayout>
```

So I tried to move MyComponent to top level like:

```
    <ReactGridLayout className="layout" cols={12} rowHeight={30}>
      <MyComponent key={1} _grid={{x: 0, y: 0, w: 1: h: 2}} />
      <MyComponent key={2} _grid={{x: 1, y: 0, w: 1: h: 2}} />
      <MyComponent key={3} _grid={{x: 2, y: 0, w: 1: h: 2}} />
    </ReactGridLayout>

```

But that does not work, because react-resizable access `this.props.children.props.children`. Which is undefined. 

So I tried to replace the div with simple component which would pass the props to children:

```
var Item = React.createClass({
    render: function () {

        return React.addons.cloneWithProps(this.props.children)
    }
});

    <ReactGridLayout className="layout" cols={12} rowHeight={30}>
      <Item key={1} _grid={{x: 0, y: 0, w: 1: h: 2}}><MyComponent /></Item>
      <Item key={2} _grid={{x: 1, y: 0, w: 1: h: 2}}><MyComponent /></Item>
      <Item key={3} _grid={{x: 2, y: 0, w: 1: h: 2}}><MyComponent /></Item>
    </ReactGridLayout>
```

But after few renders, it goes wrong:

```
 Item.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

I suspect that React gets confused because react-resizable is changing this.children.props.children..

Hope my issue is clear.

Any idea how to get around it?

**Comment by STRML** [comment]
Hi - I'm not sure if I actually understand the problem. For what purpose do you need the size?

The size is [calculated](https://github.com/STRML/react-grid-layout/blob/master/lib/GridItem.jsx#L104) from your column count and rowHeight so it should be very easy to calculate on your own. Use the `onLayoutChange` callback to receive changes (drag/resize) so you can recalculate the sizes.

**Comment by jardakotesovec** [comment]
Hi, thanks for response.

Purpose is very simple. MyComponent needs to know own width and height in `render` method, so it can properly layout itself. I need make some layout decisions based on its size.

You are right.. I could calculate on my own... it just gets bit messy..  as I also need to get containerWidth..   and handle window resize..  Which is all nicely done in react-grid-layout..  

No idea how to just pass it down?

**Comment by STRML** [comment]
Could you just read it straight out of the |style| property sent to each
child?

On 1/22/15 5:09 PM, Jarda Kotěšovec wrote:

> Hi, thanks for response.
>
> Purpose is very simple. MyComponent needs to know own width and height
> in |render| method, so it can properly layout itself. I need make some
> layout decisions based on its size.
>
> You are right.. I could calculate on my own... it just gets bit
> messy.. as I also need to get containerWidth.. and handle window
> resize.. Which is all nicely done in react-grid-layout..
>
> No idea how to just pass it down?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STRML/react-grid-layout/issues/14#issuecomment-71045193>.
>
​

**Comment by jardakotesovec** [comment]
As described in my initial post, <div> gets all the interesting props, but not MyComponent which is div children, so there is no style I could read.

**Comment by STRML** [comment]
Ah, I apologize, I missed that because of the few days lag in this conversation. Let me think about it for a while.

**Comment by STRML** [comment]
I would recommend something like this:

```javascript
var Wrapper = React.createClass({
    render: function () {
      var child = React.Children.only(this.props.children);
      return (
        <div {...this.props}>
          {React.addons.cloneWithProps(child, {
            width: this.props.style.width, 
            height: this.props.style.height
          })}
        </div>
      );
    }
});

<ReactGridLayout className="layout" cols={12} rowHeight={30}>
  <Wrapper key={1} _grid={{x: 0, y: 0, w: 1: h: 2}}><MyComponent /></Wrapper>
  <Wrapper key={2} _grid={{x: 1, y: 0, w: 1: h: 2}}><MyComponent /></Wrapper>
  <Wrapper key={3} _grid={{x: 2, y: 0, w: 1: h: 2}}><MyComponent /></Wrapper>
</ReactGridLayout>
```

**Comment by jardakotesovec** [comment]
Does it actually work for you? I tried what you suggested, but it end up with Invariant violation, because this.props.children becomes array once react-resizable add its handle. So tried to handle this situation

```
var Wrapper = React.createClass({
    render: function () {
        //var child = React.Children.only(this.props.children);
        var children = null;
        if (Object.prototype.toString.call(this.props.children)=='[object Array]'){
            children = [
                React.addons.cloneWithProps(this.props.children[0], {
                    width: this.props.style.width,
                    height: this.props.style.height
                }),
                this.props.children[1]
            ]
        }
        else {
            children = React.addons.cloneWithProps(this.props.children, {
                width: this.props.style.width,
                height: this.props.style.height
            })
        }

        return (
            <div {...this.props}>
                {children}
            </div>
        );
    }
});
```

That does not throw.. but `<MyComponent/>` does not appear. I tried to step render function of `<Wrapper/> and it works as expected, but for some reason it goes wrong. Something weird is going on. I still suspect that its because of the `react-resizable`, but not sure what exactly is happening.

Thanks a lot for your insights.

**Comment by jardakotesovec** [comment]
My bad, my last example works fine.  Thanks a lot for help!

**Comment by kachkaev** [comment]
Unfortunately none of the above examples work for me now for the same problem – width and height do not change as the grid element gets resized. Any thoughts?

This could happen because React API has changed etc. For example, instead of ```React.addons.cloneWithProps``` one should use ```React.cloneElement``` now.

**Comment by Wind4Greg** [comment]
For React 0.14+ the following (based on the above) worked for me (no extra React plugins, or deprecated calls):

```
var Wrapper = React.createClass({
    render: function () {
        var that = this;
        var newChildren = React.Children.map(this.props.children, function(child) {
            return React.cloneElement(child, { width: that.props.style.width,
            height: that.props.style.height})
            });
      return (
        <div {...this.props}>
            {newChildren}
        </div>
      );
    }
});
```
Thanks for the info.
Greg B.

**Comment by STRML** [comment]
I'm especially sensitive to this issue now as I'm running into it in my day job - I want components to be able to read their actual size in grid units so they can adjust their own layouts.

I'm considering passing w/h/x/y down via context and providing a HoC so you can grab it from any descendant of the tree.

**Comment by Wind4Greg** [comment]
Sounds nicer than the wrapper. Let us know what you think the recommended approach should be. I'm happy to test a modified interface. I'm not using a lot of RGL items (2 or 3 right now)  but my items are pretty complex, e.g., components wrapping D3/SVG visualizations.

**Comment by tmaiaroto** [comment]
This seem to work pretty well, thanks!

Any way to prevent this from updating so much? I think it's causing performance problems. I have a D3.js map inside the grid item and it gets very laggy even as I go to click on it. It'd be great if it would only update after dragging or resizing has compeleted.

**Comment by satyasinha** [comment]
ran across this issue a while ago. An alternative solution would be to use [react ref](https://reactjs.org/docs/refs-and-the-dom.html) and [getBoundingClientRect](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) to get the height and width values.

example:

```
class ItemWrapper extends React.Component {
  componentWillReceiveProps() {
    // rect.width & rect.height has width & height of item in pixels
    const rect = this._element.getBoundingClientRect();
  }

  render() {
    return(
      <div ref={element => (this._element = element)}>
      </div>
    );
  }
}
```

**Comment by abelkbil** [comment]
@tmaiaroto Thanks for sharing. How your child component receive the GridItem resize event so that you can re-render the chart. If possible please share the code. My code is something like - https://github.com/STRML/react-grid-layout/issues/702#issuecomment-369492734

**Comment by AmareshB** [comment]
React.createClass has been deprecated and hence, following is the new way React@16 onwards

And yes, this solved my issue and can pass down the props as required.
```
import React, {Component} from 'react';

export default class Wrapper extends Component {
    render() {
        var that = this;
        var newChildren = React.Children.map(this.props.children, function(child) {
            return React.cloneElement(child, { width: that.props.style.width,
                height: that.props.style.height})
        });
        return (
            <div {...this.props}>
                {newChildren}
            </div>
        );
    }
}```

**Comment by tompiler** [comment]
Sorry - I'm new to react and can't figure out how to implement the code above. Can anyone provide some more context?

I've got this error at the moment:

Uncaught Error: React.cloneElement(...): The argument must be a React element, but you passed null.

Here's how I'm doing my grid:
```

  return (
    <GridLayout
      className="layout"
      layout={layout}
      cols={12}
      rowHeight={30}
      width={1200}
    >
      <Wrapper key="a" />
      <Wrapper key="b" />
</GridLayout>
```

**Comment by tompiler** [comment]
This doesn't work anymore. Can someone please explain what needs to be done to make the above wrapper actually work? Tearing my hair out over this.

**Comment by maliky** [comment]
STRML you mention passing w/h/x/y down via context.  Is it implemented yet ?

I'm a newbie in React and I can't figure out (it's been several weeks already) how to get the width and height of the grid item to passe them down to my d3 charts?

Could you please help me ?
