### ISSUE TITLE
The draggable dom structure is diffrent from the sample

### ISSUE THREAD

**Issue by meiroo** [STRML/react-grid-layout#142]
First thank you for this component, it's very useful !

Then I have something confused, when I use this component just as the "basic sample". I got the draggable dom differently.

Normally it should be like:

![image](https://cloud.githubusercontent.com/assets/6859979/12343023/f8eeff1a-bb6a-11e5-82d2-851ec5e058fc.png)
(The .react-grid-item is on the same div with the class .react-draggable)

But actually my page like this:

![image](https://cloud.githubusercontent.com/assets/6859979/12343049/4039fe9c-bb6b-11e5-92ef-69b8f340f7a5.png)

span class="react-draggable"...
+----  div class="react-grid-item" ...

This makes the css is very hard to wirte. 
What should I do about this? Do I have missed some tips?

I use npm installed the "react-grid-layout": "0.10.0-beta1",
and my src:
<pre>
var BasicLayout = React.createClass({
  propTypes: {
    //onLayoutChange: React.PropTypes.func.isRequired
  },
  getDefaultProps() {
    return {
      className: "layout",
      items: 3,
      rowHeight: 30,
      cols: 6,
      isDraggable: true,
      isResizable: true,
      autoResize:false,
      useCSSTransforms:false,
    };
  },
  getInitialState() {
    var layout = this.generateLayout();
    return {
      layout: layout
    };
  },

  generateDOM() {
    var rows = [];
    for (var i=0; i < this.props.items; i++) {
        rows.push(< div key={i}> < span >11111111111< / span > < / div >);
    }
    return rows;
  },

  generateLayout() {
    var rows = [];
    for (var i=0; i < this.props.items; i++) {
        var y = 4;
        rows.push({x: i * 2 % 12, y: Math.floor(i / 6) * y, w: 2, h: y, i: i});
    }
    return rows;
  },

//uncomment this will have error:  Uncaught TypeError: this.props.onLayoutChange is not a function
  //onLayoutChange: function(layout) {
  //  this.props.onLayoutChange(layout);
  //},

  render() {
  	let page_style = {
  		backgroundColor: 'rgba(210, 230, 159, 0.0745098)',
  		marginLeft:'50px',
  		marginRight:'auto',
  		paddingLeft:'20px',
  		paddingRight:'20px',
  		maxWidth:'800px'
  	};

    return (
      < div id="content" {...this.props} style={Object.assign(page_style, this.props.style)} >
      	< ReactGridLayout layout={this.state.layout} onLayoutChange={this.onLayoutChange}
          {...this.props}>
          {this.generateDOM()}
        < / ReactGridLayout>
      < / div>
    );
  }
});
</pre>

**Comment by Puffton** [comment]
I'm also curious about this. For one it's not correct to place a div within a span, for another it broke my layout.

**Comment by STRML** [comment]
The `<span>` is effectively used for grouping, but it could probably be eliminated.

In reality, a `<span>` can certainly contain a `<div>`, and this happens all the time in React projects for one reason of convenience or another.

**Comment by Puffton** [comment]
Yeah, I just heard that inline elements shouldn't contain block elements, perhaps it's puritan. For HTML validation I usually just use the different css display-properties on divs to avoid warnings / errors, but the end result should be the same.

**Comment by cephirothdy2j** [comment]
Do you have any advice on how to go about removing the wrapping `<span>` tags? The presence of the tag is making the draggable functionality very janky. Items can still be rearranged but they snap immediately to the spot of their placeholder instead of moving along with the mouse.

**Comment by Puffton** [comment]
I think this is a known issue, if you look at https://github.com/STRML/react-grid-layout/issues/129.

**Comment by STRML** [comment]
This is what the DOM looks like in `0.10`:

![screen shot 2016-02-10 at 3 26 22 pm](https://cloud.githubusercontent.com/assets/1197375/12962359/b6c1bd58-d00a-11e5-9c40-e9f3ef9d3eb7.jpg)

You should be good to go if you upgrade.
