### ISSUE TITLE
Fixed container height?

### ISSUE THREAD

**Issue by dphaener** [STRML/react-grid-layout#146]
I'm trying to use this library to create a resource schedule calendar, similar to FullCalendar resource scheduler. I can't figure out how to have a fixed container height based on the number of rows. I've tried setting both autoResize and verticalCompact to false, but this doesn't work. Any suggestions?

**Comment by menelike** [comment]
according to 

https://github.com/STRML/react-grid-layout/blob/59fae7b408175b894d1c36b40f2c6c1a612b57b0/lib/ReactGridLayout.jsx#L398-L401

you should be able to pass `style={{height: 1000}}` as prop to RGL.

**Comment by STRML** [comment]
You can technically do this via `maxRows`, but it's not quite complete yet and items can still be pushed beyond the boundary.
