### ISSUE TITLE
Warning: Failed propType: Required prop `containerWidth` was not specified in `GridItem`. Check the render method of `ReactGridLayout`.

### ISSUE THREAD

**Issue by TroyLDay** [STRML/react-grid-layout#159]
I tried to upgrade to 0.10.2 and I see this message in the console:

Warning: Failed propType: Required prop `containerWidth` was not specified in `GridItem`. Check the render method of `ReactGridLayout`.

This is the layout I was using with 0.9.2:
```
module.exports = [{
  "title": "Operation Vigilant Watch",
  "roomType": "group",
  "h":2,
  "w":1,
  "x":0,
  "y":0,
  "i":"0"
},{
  "title": "AOC Ad Hoc",
  "roomType": "group",
  "h":1,
  "w":1,
  "x":1,
  "y":0,
  "i":"1"
},{
  "title": "Cpl Williams",
  "roomType": "one-to-one",
  "h":1,
  "w":1,
  "x":2,
  "y":0,
  "i":"2"
},{
  "title": "DGS-1",
  "roomType": "one-to-one",
  "h":1,
  "w":1,
  "x":3,
  "y":0,
  "i":"3"
},{
  "title": "Inherent Resolve",
  "roomType": "group",
  "h":2,
  "w":2,
  "x":1,
  "y":1,
  "i":"4"
},{
  "title": "DGS-2",
  "roomType": "one-to-one",
  "h":1,
  "w":1,
  "x":3,
  "y":1,
  "i":"5"
},{
  "title": "Kobani SA",
  "roomType": "group",
  "h":1,
  "w":1,
  "x":0,
  "y":2,
  "i":"6"
},{
  "title": "DGS-5",
  "roomType": "one-to-one",
  "h":1,
  "w":1,
  "x":3,
  "y":2,
  "i":"7"
}]
```

Here is the react component I"m working with...
```
var React = require('react');
var ReactDOM = require('react-dom');
var ReactGridLayout = require('react-grid-layout');require('react-grid-layout/css/styles.css');
var Chat = require('./Chat.js');
var NewMessage = require('./NewMessage.js');
var radio = require('radio');
var toastr = require('toastr');require('toastr/toastr.scss');
var layout = require('./data/layout.js');
var jquery = require('jquery');
//var bootstrap = require('bootstrap-sass/assets/javascripts/bootstrap.min.js');

var ChatDashboard = React.createClass({

    componentDidMount: function() {
        this.setState({'layout': layout ? layout : []});

        radio('gridBlock.click').subscribe(this.onGridBlockClick);
    },

    componentWillUnmount: function() {
        radio('gridBlock.click').unsubscribe(this.onGridBlockClick);
    },

    getDefaultProps: function() {
        return {
            //autoSize: false,
            className: "layout",
            items: 20,
            rowHeight: 270,
            cols: 4,
            minW: 1,
            onLayoutChange: function(currentLayout) {
                radio('chatDashboard.layoutChange').broadcast(currentLayout);
            }
        };
    },

    getInitialState: function() {
        return {
            layout: []
        };
    },

    render: function() {
        var self = this;
        return (
            <div className="col-md-12 chat-dashboard vert-fill">
                <div className="row chat-grid scrollable" ref="chat-grid">
                    <ReactGridLayout layout={this.state.layout} {...this.props}>
                        {this.state.layout.map(function(chat) {
                            return (<div key={chat.i}>
                                <Chat title={chat.title} roomType={chat.roomType} onshare={self.props.onshare}/>
                            </div>);
                        })}
                    </ReactGridLayout>
                </div>
                <div className="row chat-footer">
                    <NewMessage broadcast={true} className="minimal" title="Broadcast" contract={false}/>
                </div>
            </div>
        );
    },

    onGridBlockClick: function(data){
        //Scroll to a chat
        var $parentDiv = jquery(ReactDOM.findDOMNode(this)).find('.chat-grid');
        //todo: try to remove jquery: document.querySelectorAll('.chat-grid');
        var $innerListItem  = $parentDiv.find('[title="' + data.title + '"]').parent();
        $parentDiv.scrollTop($innerListItem.position().top);
    }
});

module.exports = ChatDashboard;
```

**Comment by geekjuice** [comment]
I believe you need to use the `WidthProvider` decorator or supply a `width` prop to `ReactGridLayout`.

```javascript
import ReactGridLayout, {WidthProvider} from 'ReactGridLayout';

const DecoratedReactGridLayout = WidthProvider(ReactGridLayout);

...

render() {
  return <DecoratedReactGridLayout ... />;
}

// or

render() {
  return <ReactGridLayout width={1080} ... />
}
```

**Comment by Puffton** [comment]
Is it similarly used with the ResponsiveReactGridLayout?

**Comment by geekjuice** [comment]
Do you mean the `WidthProvider` decorator? Then [yes](https://github.com/STRML/react-grid-layout/blob/master/test/examples/0-showcase.jsx#L5-L7)

**Comment by notionslate** [comment]
Thank you. I misread the docs on that subject. So I added the decorator but can only get the grid to display with my layout when setting the layout as the initial state. If I continue to apply the layout in componentDidMount (as above) then I do not get an erorr but the layout I supply is ignored. 

In addition, my app has an 'inset map' that is a minimized version of the primary grid. If I do not set a layout with the initial state, then it too ignores any layout state provided to it. 

I think this may be a bug.

**Comment by menelike** [comment]
Not sure but this could be related to https://github.com/STRML/react-grid-layout/issues/164.
Lodash `_.isEqual` compares nextProps.layout with this.props.layout which then fires the render in further steps. Could you pass your custom layout with layout.slice(0) so we can be sure that layout references have changed?

**Comment by STRML** [comment]
I believe this is user error, I don't see anything that indicates that this is a bug. If you are still experiencing issues, please fork a [jsfiddle](https://jsfiddle.net/xs2ybywc/) that demonstrates the issue.

**Comment by xReav3r** [comment]
```
Warning: Failed prop type: The prop `containerWidth` is marked as required in `GridItem`, but its value is `undefined`.
```
Warning comes when providing width by react-sizeme (recommended by oficial docs).
https://codesandbox.io/s/serene-fog-vb854v
Warning is not shown in sandbox, but appears in app created by react-scripts.

With default WidthProvider the layout does not allow to drag children to right side.
![image](https://user-images.githubusercontent.com/47347131/178715081-ab866f46-047d-42a1-bf4d-7bf20a7b9856.png)

**Comment by aslan-alt** [comment]
It may be because your outermost component does not pass width, refer to the [source code](https://github.com/react-grid-layout/react-grid-layout/blob/1f1e580b5b275d9585c21f6e4868c0223a5dfa1b/lib/ReactGridLayout.jsx#L581)
`
<ReactGridLayout layout={[{i: 'key1', x: 1, y: 1, w: 1, h: 2}]} width={10} >
</ReactGridLayout>
`
