### ISSUE TITLE
Dragging not working

### ISSUE THREAD

**Issue by zoomclub** [STRML/react-grid-layout#16]
Looks like another great React library! However, in the latest Chrome on OS X the dragging is not working, any idea why? If I try Packery or Gridster the dragging of items works as expected :)

**Comment by STRML** [comment]
Hi @zoomclub, the dragging is working fine for me on Chrome 41 on OS X. Could you please check for errors in your console?

**Comment by zoomclub** [comment]
With an up to date Chrome 40.0.2214.85 beta (64-bit) I get the following console message:

![console](https://cloud.githubusercontent.com/assets/1754062/5788438/35ea6cee-9dfb-11e4-9b9a-bd8009d62864.png)

**Comment by STRML** [comment]
That's strange. Are you running the example locally (cloned repo and opening via file:// url) or just viewing the demo at https://strml.github.io/react-grid-layout/examples/1-basic.html ?

**Comment by STRML** [comment]
I've just repushed the `gh-pages` branch with minification turned off and source maps on, could you repost your console?

**Comment by zoomclub** [comment]
I'm just running the demo online. Here is the console message now:

![console2](https://cloud.githubusercontent.com/assets/1754062/5788613/6ebab96a-9e06-11e4-85a5-b2eb1524ec4e.png)

**Comment by STRML** [comment]
Cool, thanks, that's much better. I'll see what I can do. It appears to be a bug in our dependency `react-draggable`.

**Comment by STRML** [comment]
@zoomclub Could you retry and verify this is fixed?

**Comment by zoomclub** [comment]
Dragging a complete box/div does not work on the laptop and gives no error, while it drags nicely on the iPad. When dragging on the corner resize icon it still gives an error on the laptop, I've included the error message below in case it involves other dependables. Is the demo/API only meant for the mobile touch devices or can I also drag on the laptop in the usual point, click and drag way? 

It would be most excellent if PointerEvents were embraced by all browsers already, its basically something that should of happened last year, meanwhile they are still putting up a fuss about it, at least Google is :)

![console3](https://cloud.githubusercontent.com/assets/1754062/5789011/caa13872-9e1e-11e4-9ef3-c8967286a3c2.png)

**Comment by STRML** [comment]
I think you need to clear your cache or do a hard refresh (shift-cmd-R) because it shouldn't be possible to get that error again.

I've run the demo on my machine (Chrome 41 OS X) both in normal and touch-screen emulation mode and both are working.

**Comment by zoomclub** [comment]
Just cleared cached files and images and restarted Chrome then tried again. Chrome extension settings are in developer mode but I presently have none of the extensions enabled.

After several tries it looks like the dragging of items does not work for me in Chrome. However, it does work in Safari. Whats up with Chrome?

**Comment by STRML** [comment]
No idea, it is working for me in v41.

**Comment by zoomclub** [comment]
Dragging and resizing works fine in Chrome Canary too but still not in the standard Chrome browser. Likely not but would any special Chrome flags need to be set?

**Comment by STRML** [comment]
You might have some weird emulation setting on. Chrome shouldn't be
advertising touch capability to begin with.

**Comment by zoomclub** [comment]
Instead of pecking through all Chrome flags I just reset all of them to default. It then works in standard Chrome. Who knows what the specific flag was, I had set a few for WebGL related projects. Thanks for the help and I'll look further into react-grid-layout next :)

**Comment by STRML** [comment]
Okay great. Glad you got it working.

**Comment by tongtoanbs** [comment]
I have a laptop with touch screen and I'm using react-grid-layout 0.8.5, I could use my finger to drag & drop, but I can't use my mouse to drag & drop, is there any way to work around with this?
