### ISSUE TITLE
setting margin to [0,0] breaks resizing

### ISSUE THREAD

**Issue by maerzhase** [STRML/react-grid-layout#160]
hello. since you are just working so hard on fixing all the bugs on the recent release, i wanted to add this issue. I've tested it with ResponsiveReactGridLayout with v.0.10.2

If you set the margin to [0,0] the resizing behaviour is weird and on ResizeStop set's the items to 0 width.

**Comment by STRML** [comment]
Fixed in `0.10.3`.
