### ISSUE TITLE
Grid item class name not changing

### ISSUE THREAD

**Issue by jomasti** [STRML/react-grid-layout#164]
I'm running into an issue dynamically updating the classname of a grid item. 

I have a button that adds an item to the grid when clicked. When the item is created, I add extra props such as boolean for if it's a new item, a class name to specify that it is true for styling, and a boolean setting edit mode to true. When the item is confirmed, a button click there is meant to update the item setting the booleans to false and changing the class name. The class name on the element stays the same, though. I'm assuming this is because on updates only layout information is cared about. 

Is there any way I can make this work?

**Comment by menelike** [comment]
Hard to answer without code/example. So I 'guess' that `GridItem` does not update because of `ReactGridLayout` does not update. `ReactGridLayout` should update on `nextProps.layout` change.

https://github.com/STRML/react-grid-layout/blob/59fae7b408175b894d1c36b40f2c6c1a612b57b0/lib/ReactGridLayout.jsx#L170-L172

Could you pass in layout.slice(0) to RGL when you mutate the griditem to test if equality fails? This should fire RGL update routines.

**Comment by STRML** [comment]
No, that wouldn't cause it - RGL doesn't have a `shouldComponentUpdate()` at all, so there should never be any problems with change propagation. I would suspect it's something internal to your app, @jomasti.

**Comment by menelike** [comment]
absolutely right. I somehow had in mind that PureRenderMixin was used. Sorry.

**Comment by menelike** [comment]
@STRML are you sure about this? Yes there is no `shouldComponentUpdate` used, but RGL only renders state and never props.

https://github.com/STRML/react-grid-layout/blob/59fae7b408175b894d1c36b40f2c6c1a612b57b0/lib/ReactGridLayout.jsx#L167-L187

I understand: When `nextProps.layout` change, then change state with `this.setState({layout: nextProps.layout})`. But if the change is not detected, state is not updated and therefore the component does not need to update.

**Comment by STRML** [comment]
It doesn't matter, if a render cycle propagates through the tree, RGL will rerender, unless `shouldComponentUpdate` returns false, which it can't because it's not defined. That's just default React behavior.

If you `setState` in `componentWillReceiveProps` you can get a state change into the current render without waiting for the next (and doing unnecessary work). But the rerender is happening, whether or not you set state.

**Comment by menelike** [comment]
The reconciliation is done on comparing the virtual DOM result. But the vDOM equals true since internal state is the components data provider and stays the same when a change is not detected.
I'm only talking about not detected prop change here, as I said before, this is just a 'guess'.

**Comment by jomasti** [comment]
From trying to debug, I think the issue might be with this [line](https://github.com/STRML/react-grid-layout/blob/master/lib/ReactGridLayout.jsx#L360). If the layout never changed previously in `componentWillReceiveProps`, then the layout state is not updated with the non-layout related changes (such as the classname). So when this is called, it's still pulling the old layout information for that child. The content updates fine, though.

Relevant code snippets to help understand my situation:

```
 createElement(el, index) {
    let removeStyle = {
      position: 'absolute',
      right: '5px',
      top: 0,
      cursor: 'pointer'
    };
    let i = el.i;
    let child;

    let innerElement = (
      <div className="custom_dashboard_tile_content">
        <span className="text">{el.content}</span>
        <span className="remove" style={removeStyle} onClick={this.onRemoveItem.bind(this, index)}>x</span>
      </div>
    );

    let popoverElement = (
      <Popover isOpen={true} body={this.getPopoverContent(index)} preferPlace="below">
        {innerElement}
      </Popover>
    );

    if (el.isNew) {
      child = popoverElement;
    } else {
      child = innerElement;
    }

    let element = (
      <div key={i} _grid={el} onMouseDown={this.onMouseDown}>
        {child}
      </div>
    );

    return element;
 },

 getPopoverContent(elementIndex) {
    return (
      <div>
        <p>Test</p>
        <input type="button" className="btn" onClick={this.setTile.bind(this, "test", elementIndex)} value="Test" />
      </div>
    );
 },

 setTile(value, elementIndex) {
    let classname = 'custom_dashboard_tile';
    let items = update(this.state.items,  {[elementIndex]: {$merge: {isNew: false, content: 'Old Tile', className: classname}}});
    this.setState({items, isEditing: false});
 },

onAddItem() {
    let { isEditing } = this.state;
    if (isEditing) {
      return;
    }
    this.setState({
      // Add a new item. It must have a unique key!
      items: update(this.state.items, {$push: [{
        i: 'n' + this.state.newCounter,
        x: this.state.items.length * 4 % (this.state.cols || 12),
        y: Infinity, // puts it at the bottom
        w: 4,
        h: 4,
        minW: 4,
        minH: 4,
        tileType: this.state.tileType,
        isNew: true,
        content: 'New Tile',
        className: 'custom_dashboard_tile new'
      }]}),
      // Increment the counter to ensure key is always unique.
      newCounter: this.state.newCounter + 1,
      isEditing: true
    });
  },
```

I've been reworking  `createElement` several times to try different things to see if it's the way I was specifying the element. I also previously had a `shouldComponentUpdate` method, but I removed it to still have the same issue. Am I doing something wrong here?

**Comment by menelike** [comment]
I don't recognize the update function, but if it returns an array, could you please try 

```javascript
this.setState({
      // Add a new item. It must have a unique key!
      items: update(this.state.items.slice(0), {$push: [{
        i: 'n' + this.state.newCounter,
        x: this.state.items.length * 4 % (this.state.cols || 12),
        y: Infinity, // puts it at the bottom
        w: 4,
        h: 4,
        minW: 4,
        minH: 4,
        tileType: this.state.tileType,
        isNew: true,
        content: 'New Tile',
        className: 'custom_dashboard_tile new'
      }]}),
      // Increment the counter to ensure key is always unique.
      newCounter: this.state.newCounter + 1,
      isEditing: true
    });
```

**Comment by STRML** [comment]
@jomasti Could you post your render() method? It's essential to understand what you're actually instantiating.

**Comment by jomasti** [comment]
@menelike That's `react-addon-update`, which I think should help me avoid needing to do `slice`. I tried it anyway, and I get the same result.

My render method:

```jsx
  render() {
    let elements = _.map(this.state.items, this.createElement);
    return (
      <div className="custom_dashboard_container">
        <div className="custom_dashboard_info">
          <input type="text" placeholder="Dashboard name" />
          <input type="text" placeholder="Dashboard description" />
          <input type="button" className="btn" onClick={this.onAddItem} value="Add Item" />
        </div>
        <ResponsiveReactGridLayout
            onBreakpointChange={this.onBreakpointChange}
            onLayoutChange={this.onLayoutChange}
            {...this.props}>
          {elements}
        </ResponsiveReactGridLayout>
      </div>
    );
  }
```

**Comment by menelike** [comment]
and props.layout exists? because you are talking about state above and passings props here.

**Comment by jomasti** [comment]
No, I'm not passing in layout at all. I'm setting each items _grid property. props.layout(s) is not needed in that situation, right?

**Comment by menelike** [comment]
you are right, did not see that, my mistake.

**Comment by jomasti** [comment]
This is mainly the dynamic add/remove elements demo with the additional methods for editing the tiles after they added.

**Comment by menelike** [comment]
no it isn't because you do not add or remove the children, you update the childrens grid properties. Therefore children.length stays the same and internal state is not set.
We need `synchronizeLayoutWithChildren` in order to map item properties, if this is not fired together with an internal state update, nothing happens. 

One guess:
Try to change the browsers width, this should update some routines which then fire synchronizeLayoutWithChildren.

**Comment by jomasti** [comment]
I can resize the browser window, add another element, delete an element, move the element around, etc. The class name never changes for that item in the internal layout state. If I understand the purpose of `synchronizeLayoutWithChildren`, it only seems to be useful to add new children and recheck bounds.

**Comment by STRML** [comment]
Okay, here's what's going on:

1. Back in the 0.12-0.13 days, when this lib was written, it used `cloneWithProps()` to merge props into `<GridItem>` children.
1. That was deprecated, so we switched to `React.cloneElement()`.
1. At some point, it was forgotten that `style` and `className` have to be manually merged. `cloneWithProps` would do this by default.

If you were passing element props in your layout items to get around this (e.g. `[{w: 2, h: 3, x: 0, y: 0, i: '1', className: 'foo'}, ...]`, don't. Layout should only contain coordinates.

I've pushed a fix and a release at `0.10.7`.

**Comment by jomasti** [comment]
Right, that makes sense. I think I had a fundamental misunderstanding of what could be passed into `_grid`. Everything is good now. Thanks!

**Comment by jomasti** [comment]
I don't think it can be said that the layout object is only coordinates because it seems like the only way to set props like the min/max height/width or `static` is through that object since the `processGridItem` gets those props from the layout state. I think that is what led me to believe I could set `className` in layout/_grid, which would correspond with [this section](https://github.com/STRML/react-grid-layout#grid-item-props) of the README.

**Comment by STRML** [comment]
Ah yes. `min/max` and `static` are also in the layout (technically coordinates, or at least layout properties).

I'll update the documentation, although putting these properties on the layout itself is technically still valid.
