### ISSUE TITLE
ES6 syntax and Mixins

### ISSUE THREAD

**Issue by Ganasist** [STRML/react-grid-layout#165]
I'm working with ES6 and can't seem to get PureRenderMixin / mixins: [PureRenderMixin] working.

This means I am not able to access onBreakPointChange, which makes this difficult. I'd like to get the grid to be 4 by X when over 760px, and then 2 by X under that... so I'm using the responsive component but without 'onLayoutChange' or 'onBreakPointChange' it doesn't seem to work. Is there another way to access these methods without using Mixins?

**Comment by STRML** [comment]
Why is it that you believe you have to use mixins to access them at all? Pass the callback functions as props to `<ResponsiveReactGridLayout>`.

This component does not use mixins whatsoever. Your use or non-use of PureRenderMixin has no bearing on whether or not layout callbacks will fire.

Further, I don't see why you need them at all - just [pass breakpoints](https://github.com/STRML/react-grid-layout#responsive-usage).

**Comment by Ganasist** [comment]
I'm not sure if I'm doing something wrong or if you've never tried using this on an ES6 class.

In the 'showcase' demo example there is this property on the component:
onBreakpointChange={this.onBreakpointChange}

When I add this and log it, nothing ever happens. However, 
onLayoutChange={this.onLayoutChange}
... works fine, it fires whenever the component is resized. Problem is it's not what I need (I just want to adjust cols based on breakpoints).

In the docs it says when using the responsive component you can set props like so:
// # of cols. This is a breakpoint -> cols map, e.g. {lg: 12, md: 10, ...}
cols: React.PropTypes.object

However when I do that I get an error that cols is an object not a number. So I'm not sure what's going on with my imports or what not, but the grid works fine without responsive, seems completely borked with it (and I'm assuming this is an ES6 thing)?... Perhaps you could provide a complete ES6 example in your docs, including some of the stuff you've omitted from the existing docs?

**Comment by STRML** [comment]
Sounds like you're not using `<ResponsiveReactGridLayout>`, you're using `<ReactGridLayout>`. Check your imports.

**Comment by treehau5** [comment]
Not being able to use mixins is not a react-grid-layout issue, it was a purposeful design choice by the react team

> No Mixins
Unfortunately ES6 launched without any mixin support. Therefore, there is no support for mixins when you use React with ES6 classes. Instead, we're working on making it easier to support such use cases without resorting to mixins.

https://facebook.github.io/react/docs/reusable-components.html

**Comment by kubante** [comment]
https://facebook.github.io/react/docs/pure-render-mixin.html is implementing pure render mixinis in es6

**Comment by bardu** [comment]
As  the OP I'm using ES6 and  I'm fairly new to react.

I'm referencing this example 
https://github.com/STRML/react-grid-layout/blob/master/test/examples/8-localstorage-responsive.jsx

I'm stumbling over this event handler:

```
onLayoutChange(layout, layouts) {
    saveToLS('layouts', layouts);
    this.setState({layouts});
    this.props.onLayoutChange(layout, layouts);
  },
```
which throws and error: 

>  this.props.onLayoutChange is not a function

How should I force a layout change?

Here is my code:
```
'use strict'

import React from 'react';
import Content from '../layout/Content';
import { Responsive, WidthProvider } from 'react-grid-layout';
import PureRenderMixin from 'react-addons-pure-render-mixin';

const ResponsiveReactGridLayout = WidthProvider(Responsive);

export default class Home extends React.Component {
    constructor(props, context) {
        super(props, context);
        this.onLayoutChange = this.onLayoutChange.bind(this);
        // prevents unnessesary rerendering on layout change
        this.shouldComponentUpdate = PureRenderMixin.shouldComponentUpdate.bind(this); 
        this.state = {
            layouts: {
                lg: [
                    {i: '11', x: 0, y: 0, w: 1, h: 1, static: true, isResizable: true},
                    {i: '12', x: 1, y: 0, w: 10, h: 1, static: true, isResizable: true},
                    {i: '13', x: 11, y: 0, w: 1, h: 1, static: true, isResizable: true}
                ]
            }
        }
        
    }
    
    static defaultProps() {
        return {
            className: 'layout',
            breakpoints: {lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0},
            cols: {lg: 12, md: 10, sm: 6, xs: 4, xxs: 2},
            rowHeight: 30
        };
    }
    
    onLayoutChange(layout, layouts) {
        console.log('fired on layout change')
        this.setState({layouts});
        this.props.onLayoutChange(layout, layouts);
    }
    
    render() {
    
        return (
            <Content>
                <ResponsiveReactGridLayout
                    {...this.defaultProps}
                    layouts={this.state.layouts}
                    onLayoutChange={this.onLayoutChange}
                >
                    <div key={'11'}></div> 
                    <div key={'12'}><h1>Home View</h1></div>
                    <div key={'13'}></div>
                    <div key={'21'}></div>
                    <div key={'22'}></div>
                    <div key={'23'}></div>
                    <div key={'31'}></div>
                    <div key={'32'}></div>
                    <div key={'33'}></div>
                </ResponsiveReactGridLayout>
            </Content>
        );
    }
}
