### ISSUE TITLE
Button clicks inside ReactGridLayout

### ISSUE THREAD

**Issue by anivas** [STRML/react-grid-layout#166]
I am using ReactGridLayout to host custom component built using material-ui. Any interaction with the components inside the a layout is considered a drag event. i.e If I have a button inside a layout and I try to click the button, the click is considered a drag and rearrange event and the layout is lifted from its current place, getting ready to drag. Is there a workaround for this.

If I set isDraggable={false} the clicks are recognized. But I want drag as well.

**Comment by STRML** [comment]
You'll need to cancel the event yourself, or define a [handle or cancel selector](https://github.com/mzabriskie/react-draggable#draggable-api) on your layout items.

**Comment by anivas** [comment]
Whats a handle is that the id of the element, i.e if I have a header item, I can use that as the handle, instead of the entire layout.

**Comment by STRML** [comment]
It's a standard css selector, please read the docs.

**Comment by adithyavinjamoori** [comment]
@STRML Do you have any example for this?

**Comment by cdeutsch** [comment]
Here's an example of canceling the event. 

It wasn't obvious `onClick` won't work to stop propagation.

```jsx
<button
  onMouseDown={this.stopPropagation}
  onMouseUp={this.stopPropagation}
  onTouchStart={this.stopPropagation}
  onTouchEnd={this.stopPropagation}
>
    My Button
</button>
```

```js
stopPropagation = (event) => {
  event.stopPropagation();
};
```

**Comment by irodger** [comment]
> @STRML Do you have any example for this?

I got what he mean.

```jsx
<ReactGridLayout draggableHandle=".drag-cancel" {...otherOptions}>
  {children}
</ReactGridLayout>
```

then when you need to cancel this action, you can use this selector in any of children and elements, and the items won't be draggable
```jsx
...
<Button className="drag-cancel" {...props} />
...
```
