### ISSUE TITLE
How to add react-grid-layout as plug-in?

### ISSUE THREAD

**Issue by WeiLinCentrify** [STRML/react-grid-layout#167]
Our project uses gulp instead of webpack. Do you have recommendation on how to use react-grid-layout as a library/plugin for my project? I've tried to add react-grid-layout to package.json and copy and paste the sample code into my project. I'm able to render something,  but they are non interactable divs with no borders or color.

**Comment by eMaj-Fr** [comment]
Did you read this on the README: https://github.com/STRML/react-grid-layout#usage-without-browserifywebpack
