### ISSUE TITLE
onLayoutChange never called

### ISSUE THREAD

**Issue by eMerzh** [STRML/react-grid-layout#169]
hi, 
in all of the example, 
we use something like
```jsx
<ReactGridLayout onLayoutChange={this.onLayoutChange}
          {...this.props}>
</ReactGridLayout>
```
but we expect i the component's onLayoutChange, that this.props.onLayoutChange is defined by the parent element.
and so, we the callback override the component's callback that tries to do a setState and is never called.
is it intended ?

in the mean time, if i put the  order like this
```jsx
<ReactGridLayout {...this.props} onLayoutChange={this.onLayoutChange}>
</ReactGridLayout>
```
i got an infinite loop...

am i missing something?

**Comment by Puffton** [comment]
Related to https://github.com/STRML/react-grid-layout/issues/151. If I remove "onLayoutChanged" it loads without the infinite loop.

**Comment by menelike** [comment]
@eMerzh the code from `this.onLayoutChange`is needed for a better understanding of what your are actually doing here.

More code is needed for an appropriate answer. Here is my lucky guess:

https://github.com/STRML/react-grid-layout/blob/d1bf3ab73f6ad69fdff59ad43315623954904d26/lib/ReactGridLayout.jsx#l167-l187

https://github.com/STRML/react-grid-layout/blob/59fae7b408175b894d1c36b40f2c6c1a612b57b0/lib/utils.js#l320-l363

A new layout is detected if lodash's `isEqual` returns false (keep in mind that this also returns false if the ordering changed) or if the length of the children has changed. In both cases the passed layout is synchronized and checked with `synchronizeLayoutWithChildren` where a new layout object (with a new reference) is returned. As a result the passed layout never equals the new layout if deep equality check is not used (`oldLayout === newLayout` returns false).

If your `onLayoutChange` function changes the layout in a way that the above mentioned logic fires, a loop could be the result. Keep in mind that changing the children's length also results in a new layout.

If you do not change the children's length and do not mutate the layout e.g. only store the layout, a loop should actually never happen.

**Comment by eMerzh** [comment]
hi, thanks @menelike  for the help

my code is "simply" 
```js
  onLayoutChange(layout) {
          this.props.onLayoutChange(layout);
          this.setState({layout: layout});
  },
```
so this should have no mutations....
and if i commented out the props.onLayoutChange i got a 
```
Uncaught RangeError: Maximum call stack size exceeded
```
it might be the setState that is somewhat duplicate?

**Comment by Puffton** [comment]
Exactly the same for me...

**Comment by STRML** [comment]
The issue is that the setState() causes a prop change, which calls
onLayoutChange.

**Comment by Puffton** [comment]
@STRML Was this part of a previous workflow which is now obsolete? It used to work before, and it seems @eMerzh used nearly identical pieces of code.

**Comment by STRML** [comment]
I believe it may be an error - if you set a layout that is identical to
a previous one, another callback should not fire.

**Comment by menelike** [comment]
@eMerzh 
in your first example you just pass `{...this.props}`. In your `onLayoutChange` you call the parent's `onLayoutChange` and set the state. I'm not sure if I really understand your scenario, but

Why do you set the state when you actually never pass the stored layout from your state ro RGL?
e.g. something like

```javascript
<ReactGridLayout {...this.props} layout={this.state.layout} onLayoutChange={this.onLayoutChange}>
</ReactGridLayout>
````

In addition, why do you call `onLayoutChange` twice? Where is your layout actually stored?

```javascript
 onLayoutChange(layout) {
          this.props.onLayoutChange(layout);
          this.setState({layout: layout});
  },
``` 

I do not know your logic in `this.props.onLayoutChange`, but after all this should be enough:

**parent:**
```javascript
 onLayoutChange(layout) {
          this.setState({layout: layout});
  },

  render() {
    const {layout} = this.state;

    return (
      <YOURCOMPONENT layout={layout} onLayoutChange={onLayoutChange}/>
    );
  }
````

**YOURCOMPONENT:**
```javascript
<ReactGridLayout {...this.props} >
</ReactGridLayout>
````

or the easy way with no parent involved

```javascript
 onLayoutChange(layout) {
          this.setState({layout: layout});
  },
  render() {
    const {layout} = this.state;

    return <ReactGridLayout {...this.props} layout={layout} onLayoutChange={this.onLayoutChange} />
  }
````

**Comment by eMerzh** [comment]
@menelike thanks a lot for the help...
i'm in the middle of trying to moving to redux at the sametime so i might not grasp everything ....
i tried to do something close to what you described, but now i have the same issue when i try to set the state (store.reduce in fact) on the parent's onLayoutChange....

i got smth like 
```jsx

export default class MyParentComponent extends React.Component {
    onLayoutChange = (layout) => {
        // infinite loooop
        //this.props.store.dispatch(setLayout(layout));
    }
...
...
...
    componentDidMount(params) {
        this.unsubscribe = this.props.store.subscribe(() => {
            this.forceUpdate();
        });
    }
    componentDidUnMount() {
        this.unsubscribe();
    }

    render() {
        let state = this.props.store.getState();
        return (
            <MyParentComponent ref="layout" className="content"
                onLayoutChange={this.onLayoutChange}
                items={state.items}
                >
            </MyParentComponent>
        );
    }
}
````

and in the MyChildComponent's render, smth like:
```jsx
<ReactGridLayoutWidth
        {...this.props}
        onLayoutChange={this.props.onLayoutChange}
     {this.props.items.map(this.createElement)}
</ReactGridLayoutWidth>
```


is it normal? am i missing something?

thanks a lot again for the help

**Comment by Puffton** [comment]
@menelike Thanks for your time! I don't think you are on the right track however. 

The reason I'm calling onLayoutChange is because I have a custom RGL component in my project. Even if I change the code to:

```js
onLayoutChange(layout) {
          this.setState({layout: layout});
},
```

It doesn't work.

**Comment by eMerzh** [comment]
is it possible that  verticalCompact: true might cause the issue?
in another test i ran into issue, and setting   verticalCompact: false somewhat helped (the layout is messy but the code keep going instead of infinite looping)

**Comment by menelike** [comment]
I made an example to reproduce this case: https://jsfiddle.net/6pmrzxoy/

The loop is caused because onLayoutChange fires on every render:

https://github.com/STRML/react-grid-layout/blob/d1bf3ab73f6ad69fdff59ad43315623954904d26/lib/ReactGridLayout.jsx#l167-l187

I haven't tested this, but I think there is a typo in the current master on commit https://github.com/STRML/react-grid-layout/commit/fedae9ba772fb2c11f0212cf07a0a807f4fbdacd, I do not see the reason why the check isn't ```(nextProps.children.length !== this.props.children.length)``` instead.

**Comment by eMerzh** [comment]
yeah! clearly works better for me here... thanks @menelike 

this only issue is when i add an item in the grid ... it loops again

**Comment by menelike** [comment]
@eMerzh first we need to wait for a repsonse from @STRML on this.
We need to be sure that your problem is not solved trough a later version.

**Comment by unodgs** [comment]
I run into the same issue but when I changed:
`onLayoutChange(layout) {
  this.setState({layout: layout});
},`
to
`onLayoutChange(layout) {
  setTimeout(() => {
     this.setState({layout: layout})
  });
},`
the problem of infinite loop was gone. For sure it's not a correct solution but let me to move on

**Comment by eMerzh** [comment]
@STRML, any news on this?

https://github.com/STRML/react-grid-layout/issues/169#issuecomment-188682078
seems to be a pretty good test / resolve case  as the fix looks small :)

**Comment by STRML** [comment]
You are correct that there's a typo in that comparison. I'll fix it.

**Comment by STRML** [comment]
Please try `0.10.9`.

**Comment by eMerzh** [comment]
Thanks works like a charm here !
i think we can close this one :)
