### ISSUE TITLE
Question: Auto calculate initial layout from children "w" and "h"?

### ISSUE THREAD

**Issue by narenranjit** [STRML/react-grid-layout#173]
Currently there's no way to generate the initial layout automatically, correct? 

I wrote a function for my app which takes in an array of `[{ w: 2, h: 3} ...]` + noOfCols and outputs a 'layout' array of the form `[{w:2, h:3, x: <col>, y: <row>]` with values set to make sure everything fits properly initially -- is there an built-in way to do this that I missed from the docs?

**Comment by menelike** [comment]
From https://github.com/STRML/react-grid-layout/blob/d1bf3ab73f6ad69fdff59ad43315623954904d26/README.md

```If no properties are provided for a grid item, one will be generated with a width and height of 1.```

This means, a layout is generated automatically with the default values. 
Most examples show how an initial and customized layout can be done and they all look similar to your solution. 

An easy API like `addItemtoLayout(layout, gridItem)` where collision detection and corrections are done automatically, does not exist. Instead RGL always tries to correct your layout (e.g. https://github.com/STRML/react-grid-layout/blob/d1bf3ab73f6ad69fdff59ad43315623954904d26/lib/utils.js#l359-l360) which may not fit in your case. I had a similar use case and made heavy use of `correctBounds`, `moveElement` and `compact` within my own layout generator before passing it to RGL.

A simple API for that would be a nice feature actually.

**Comment by narenranjit** [comment]
@menelike Thanks! About "one will be generated with a width and height of 1", unless I mis-understood that quote, my problem is the opposite -- "here's this module which should have colspan of 2 and rowspan of 3, go figure out where it fits and put it there". In other words I want to pass in `w` and `h` and have it generate `x` and `y`, more along the lines of your second solution for `addItemtoLayout`.

Is there interest in a PR for to add such a utility function? If not I'll just throw a gist out and link to it form here for others.

**Comment by zekedroid** [comment]
+1 to that feature, @narenranjit

**Comment by STRML** [comment]
I think this would be a nice companion library, but I'm not particularly interested in increasing the size of this library with it. Such a library would be generalizable to grid packing in general. Did you have any luck with it @narenranjit ?

**Comment by narenranjit** [comment]
I have a solution I'm happy with, but haven't spend much effort making it generic to handle other edge-cases. It's a fairly rudimentary algorithm, and the file is about 650bytes gzipped. I'll try to put it in a separate repo over the next  week or so, and maybe you could link to it from here.

**Comment by chjoshan** [comment]
@narenranjit any updates on this one?

**Comment by Lueton** [comment]
Here is a small example of how you could generate layouts based on height and width. With `fillSpaces` you can choose whether free spaces are used or not 

```javascript
const items = [{
        id: "A",
        w: 1,
        h: 1,
    },
    {
        id: "B",
        w: 1,
        h: 1,
    },
    {
        id: "C",
        w: 1,
        h: 1,
    },
    {
        id: "D",
        w: 1,
        h: 1,
    },
    {
        id: "E",
        w: 1,
        h: 1,
    },
    {
        id: "F",
        w: 2,
        h: 2,
    },
    {
        id: "G",
        w: 2,
        h: 2,
    },
    {
        id: "H",
        w: 2,
        h: 2,
    },
    {
        id: "I",
        w: 1,
        h: 1,
    },
    {
        id: "J",
        w: 1,
        h: 1,
    },
];

const cols = {
    lg: 12,
    md: 6,
    sm: 4,
    xs: 3,
    xxs: 1
};

const collides = (layout, item, cols) => {

    const cls = (l1, l2) => {
        if (l1.x + l1.w <= l2.x) return false;
        if (l1.x >= l2.x + l2.w) return false;
        if (l1.y + l1.h <= l2.y) return false;
        if (l1.y >= l2.y + l2.h) return false;
        return true;
    }

    //Check if item collides with another item
    for (let i = 0; i < layout.length; i++) {
        if (cls(item, layout[i])) {
            return true;
        }
    }

    //Check if item overflows, ignore overflow if width is greater than cols
    if (item.x + item.w > cols && item.w <= cols) {
        return true;
    }

    return false
};

const getLastElementPosition = (layout, cols) => {
    if (!layout.length)
        return {
            x: 0,
            y: 0
        };

    const {
        x,
        y
    } = layout[layout.length - 1];
    return {
        x,
        y
    };

}

const addItem = (layout, item, cols, fillSpaces) => {
    if (layout.length === 0) {
        layout.push({
            ...item,
            x: 0,
            y: 0
        });
    } else {

        let {
            x,
            y
        } = fillSpaces ? {
            x: 0,
            y: 0
        } : getLastElementPosition(layout, cols);

        const {
            id,
            w,
            h
        } = item;

        while (collides(layout, {
                ...item,
                x,
                y
            }, cols)) {
            if (x + 1 >= cols) {
                x = 0;
                y++;
            } else {
                x++;
            }
        }

        layout.push({
            ...item,
            x,
            y,
        });

    }
}

const createLayout = (items, cols, fillSpaces) => {
    const layout = [];

    items.forEach(item => addItem(layout, item, cols, fillSpaces));
    return layout;
}

const printLayout = (layout, cols) => {
    const colCount = cols;
    const rowCount = Math.max(...layout.map(item => item.y + item.h - 1));
    const createRow = () => new Array(colCount).fill("0");
    const grid = [];
    for (let i = 0; i < rowCount + 1; i++) {
        grid.push(createRow());
    }
    layout.forEach(item => {
        const {
            id,
            x,
            y,
            w,
            h
        } = item;

        for (let i = y; i < y + h; i++) {
            for (let j = x; j < (x + w) && j < cols; j++) {
                grid[i][j] = id;
            }
        }
    });
    return grid;
}

Object.keys(cols).forEach(colId => {
    console.log("fill=0", colId, printLayout(createLayout(items, cols[colId]), cols[colId]))
    console.log("fill=1", colId, printLayout(createLayout(items, cols[colId], true), cols[colId]));
});
```
