### ISSUE TITLE
Incorrect items position

### ISSUE THREAD

**Issue by antonpaly4** [STRML/react-grid-layout#177]
In some cases one or more grid items sets in wrong positions.
For example, item with layout `{x: 0, y: 2, w: 2, h: 1}` after rendering sets on position of `x: 2, y: 3`
is there some kind of solution to this problem?

**Comment by zekedroid** [comment]
Could you supply some relevant code? It's virtually impossible to fix this without knowing what your setup looks like

**Comment by antonpaly4** [comment]
I saved layout settings on the server, ant then run layout generation, which use saved settings, if they are, or generate new, if item has no layout
`generateLayout: function(widgets) {
return _.map(widgets, function(item, i) {
return {
i: '' + item._id,
x: item.x || i % 4,
y: item.y || Math.floor(i / 4),
w: item.w,
h: item.h
};
});
},`
rendering code:
`<Grid layout={layout} cols={4} rowHeight={this.state.rowHeight} margin={[10, 10]} onLayoutChange={this.changeLayout} onResizeStop={this.resizeWidget} isDraggable={this.state.editingMode} isResizable={this.state.editingMode}>
 {_.map(this.state.widgets, function(widget, i){
  return(
   <div key={widget._id}>
    <Widget {...widget} edit={self.editWidget} remove={self.removeWidget} showSettings={self.showWidgetSettings} ref={'widget-' + widget._id}  isSettingsOpen={self.state.settings} editingMode={self.state.editingMode} />
   </div>
  )
 })}
</Grid>`

**Comment by zekedroid** [comment]
can you post what `widgets` looks like? Also `this.state.widgets`, and maybe edit the post so that it's a code block and not inline? It's hard to read this way.

**Comment by antonpaly4** [comment]
Widgets is an array of objects. It's look like:
```
{
_id:	1456295891243,
h:	1,
w:	2,
x:	0,
y:	0
maxH:	2,
maxW:	4,
minH:	1,
minW:	1,
settings:	Object {...},
type: 	"graphic"
}
```

**Comment by zekedroid** [comment]
Keep going, post an example of the full widgets array and what the grid actually renders.

**Comment by STRML** [comment]
Without *much* more info this is a cat & mouse game. Please take it to Gitter or IRC.
