### ISSUE TITLE
Mutating this.props.layouts

### ISSUE THREAD

**Issue by kibs** [STRML/react-grid-layout#178]
I am maybe doing something wrong, but I am trying to make an editor where i provide the layouts using the "layouts" props from my internal state. I then listen for changes using onLayoutChange, and update my own state.layouts which is then propagated down to the ResponsiveGrid component. Anyway

https://github.com/STRML/react-grid-layout/blob/master/lib/ResponsiveReactGridLayout.jsx#L130-L142

It looks like this code is mutating the props.layouts object, and therefore my state object is mutated in place. Is this by design. It makes it hard to create an "controlled" component.

Does my question even make sense :)

**Comment by olslash** [comment]
+1 -- this issue (mainly the fact that the library depends on holding/managing the current layout in its own state) makes it nearly impossible make a decent implementation using redux or similar. If anyone's done this, I would love to hear how.

belive this was also discussed in #156

**Comment by olslash** [comment]
I managed to get something decent working by 
* not letting my reducer update the modified layout if it hadn't actually changed. The library was firing off tons of useless onLayoutChange calls with identical layouts.
* deep-cloning the layout passed in by onLayoutChange before putting it in state, so the library can't mutate it.

still a bit hacky, and i'd love to see the library take a better approach to state in the future

**Comment by STRML** [comment]
I'm with you on this - would like to do a similar approach to what I did with `<Draggable>`, where we expose a Core component that has no state, or make a breaking change and create a HoC like `WidthProvider` that does the state management.

Then consumers will simply have to listen to `onLayoutChange` and assign it back via state, or modify it... or do whatever they like.

**Comment by olslash** [comment]
great, yeah, i think for nontrivial cases most people are going to want to manage the state themselves -- having a HOC that provides the same "just works" behavior, + a stateless core would be a great approach.

**Comment by kibs** [comment]
Cool, i think it will clean up a lot of code when you don't have to keep state yourself. Making it more stable. And also, "everyone" in the React community is used to and expects components to work this way.

**Comment by jonashartwig** [comment]
Hi, is there anyone working on this?

**Comment by STRML** [comment]
The library shouldn't be mutating the input `layouts` item anymore. It clones it and then goes to town. Please comment if you are still seeing this bad behavior.

**Comment by arunkjn** [comment]
@STRML this is great. Is the change present in release 0.13.7 ?

**Comment by STRML** [comment]
Yeah.

**Comment by jonashartwig** [comment]
so i have been testing this a lot now and it seems to be good :)

**Comment by vasilevach** [comment]
Hi guys, sorry to "reopen" this issue, but 0.17.1 still mutates the state. It adds some new breakpoints when non are defined. I would also love a version, where the component is stateless and we can manage our own state. Outside drag is ideal candidate for such a behavior.
