### ISSUE TITLE
Smoothly change the layout programatically

### ISSUE THREAD

**Issue by zekedroid** [STRML/react-grid-layout#180]
**Use case: minimize item**

Is there a way to hook into the way the resizing happens such that when pressing a button, the height of a button can be reduced to a constant value (not zero since it's important to leave a "header" to maximize) and trigger the smooth motion? As it stands, I update the state of the layout height and on re-render, the new layout is displayed. It would be interesting to instead do it smoothly, much like manually resizing it using the resize handle.

**Comment by kcking** [comment]
Not _sure_ if this would work, but maybe try a css transition on the height of the contents of the grid?

**Comment by zekedroid** [comment]
Mmm yeah i can try mucking around. I was hoping there was a way to mimic the work that's already there since the transitions do happen somehow.

**Comment by STRML** [comment]
Simply updating the layout prop should work fine - in the demos, there is a 'Generate New Layout' button that smoothly animates the items.

Now, the `height` and `width` are not actually animated via CSS, but they could be:

```css
.react-grid-item.cssTransforms {
    transition-property: transform, height, width;
}
```

**Comment by zekedroid** [comment]
Ahhh interesting. I was about to say that maybe I could fake a resize event instead of simply updating the height. That way there's no need to append css transforms. Do you think that would be possible to do cleanly? I'm going to actually read the source code as that's what I should've done to begin with, and default to css tricks if I can't find anything.

**Comment by STRML** [comment]
You're trying to update the height of a single item, not the whole layout, no?

Now, all grid items' width and height need to be in units. If you want to change one's height, you'll have to adjust its `h` from whatever it is, down to `1` (so there's enough room for a header). Alternatively, you can make the widget's height itself smaller without adjusting the layout. This way it will still occupy the same amount of space in the layout, but it will be simply visually smaller.

**Comment by zekedroid** [comment]
Yup, updating a single item by setting its `h` to 4 (perfect to display about 32 pixels of header). It works, it shifts the layout as intended, it's just an instant rather than gradual reduction of the height. It's a purely aesthetic UX feature I'm trying to implement, low priority but nonetheless a cool feature.

**Comment by STRML** [comment]
Cool - so if you have that working, simply adjust the `transition-property` (and be sure to set it off when resizing, which adds the class `resizing`).
