### ISSUE TITLE
Get width and height in pixels

### ISSUE THREAD

**Issue by juliuszc** [STRML/react-grid-layout#181]
Hi, I'm trying to get the height and width of a grid item in pixels so that I can set the height of a data table dynamically. I am using refs inside of handleLayout to accomplish this, but it only works when the user resizes to exactly the size of the column. Is there any hook into the layout after it has calculated the size of the grid item, but before it renders?

**Comment by eMerzh** [comment]
i think you should look arround here.
https://github.com/STRML/react-grid-layout/issues/14#issuecomment-71083733

these might give you a hint

**Comment by juliuszc** [comment]
Could an event be added after the grid has finished calculating the next layout so that doing it a hacky way isn't necessary?
