### ISSUE TITLE
Possible enhancement : Setting a max on the vertical height of the layout

### ISSUE THREAD

**Issue by ctrlaltdylan** [STRML/react-grid-layout#182]
You can define the number of columns, but would it be possible to enforce a height in the layout either in the props or css?

**Comment by STRML** [comment]
At this time, there is not, and it would likely confuse the compactor. I would be very happy to accept any compaction enhancements - for one, it should be possible to swap items horizontally.

In the future the compactor should be able to define multiple possible layouts based on constraints and choose the one that satisfies it best.

**Comment by ctrlaltdylan** [comment]
Ah sorry to hear it's difficult. I may have to take a stab at it because I definitely need the vertical height enforced.
