### ISSUE TITLE
Inifinite Loop when grid item y is Infinite.

### ISSUE THREAD

**Issue by eMerzh** [STRML/react-grid-layout#183]
Hi :)

Some exemples add Y as Infinite, so it seems to handle it ...
(like https://github.com/STRML/react-grid-layout/blob/94bb16e046243f786930991c47f49b09364a53de/test/examples/6-dynamic-add-remove.jsx#L58)

but i got an infinite while playing with it ...
it seems that the infinite loop might come from the vertical compacting logic.
https://github.com/STRML/react-grid-layout/blob/59fae7b408175b894d1c36b40f2c6c1a612b57b0/lib/utils.js#L95

**Comment by STRML** [comment]
Hmm yes. This logic could be amended to be smarter by simply finding the bottom element and comparing with it. Might speed up compaction somewhat else well.
