### ISSUE TITLE
React-Native support?

### ISSUE THREAD

**Issue by polarathene** [STRML/react-grid-layout#184]
Any chance of supporting RN? Still fairly new to React and RN but I think it may be possible, you already make CSS transforms/percents optional (which RN doesn't support), but `className` prop would be a problem and need all styles moved into `style` prop.

There isn't much layout support libs for RN and this looks like it'd be useful!

**Comment by STRML** [comment]
I have no plans to do so for RN - I have no RN projects in flight. I'm not sure how Draggable/Resizable will fare in an RN environment. Would be happy to accept patches to any/all projects.

**Comment by MaxInMoon** [comment]
I think that `react-grid-layout`'s RN support will be the best option to have sortable masonry-lists in RN. Am I wrong?
