### ISSUE TITLE
Question: example on draggableHandler

### ISSUE THREAD

**Issue by chjoshan** [STRML/react-grid-layout#185]
Could you possibly give a very short example on using the draggableHandler? I tried to use it but failed every time. 

eg. my props looks like this

```
props = {
        items: 20,
        rowHeight: 200,
        className: 'layout',
        cols: 3,
        isResizable: true,
        draggableHandle: 'dragHandle'
};
```

and the component
```
<ReactGridLayout {...this.state} onLayoutChange={this.onLayoutChange}>
    <div className="grid" key={i} _grid={layout[i]}>
        <button className="dragHandle">handle</button>
        <span className="text"> Some text </span>
     </div>
 </ReactGridLayout>
```

Isn't this the right way to set a handle for dragging? Or did I misunderstand something?

**Comment by STRML** [comment]
It's a standard query selector, much like what you'd use for jQuery or `document.querySelectorAll()`.

You need to use `.dragHandle`, not `dragHandle`. See https://github.com/mzabriskie/react-draggable#draggable-usage

**Comment by chjoshan** [comment]
ohh stupid me. Many thanks for the quick response. Really cool library btw.
