### ISSUE TITLE
Way of getting current breakpoint name?

### ISSUE THREAD

**Issue by adambowles** [STRML/react-grid-layout#186]
Is there a way of returning the name of the current breakpoint (i.e: `lg`, `md`, `sm`, `xs`, `xxs`, etc.).

I'd like to be able to load tiles in appropriately by knowing the number of cols in each breakpoint
(In [example 8](https://strml.github.io/react-grid-layout/examples/8-localstorage-responsive.html) and [example 6](https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html) the tiles load in the right hand column once the first row is full)

**Comment by STRML** [comment]
The source for [RRGL](https://github.com/STRML/react-grid-layout/blob/master/lib/ResponsiveReactGridLayout.jsx) is relatively simple.

On BitMEX, we accomplish this by defining layouts per breakpoint, and by managing the width/breakpoint above RRGL. So RRGL doesn't do much more than select the correct layout from a map of `{[breakpoint: string]: Layout}`.

This is an indication that RRGL could be improved to be more useful, by, for example, filtering out nodes that don't have a matching layout item, and/or by calling back not only on breakpoint/width change, but on the initial state set.

**Comment by morgs32** [comment]
@STRML you say that you can change rowHeight depending on breakpoint. Not sure how you would do that without a switch statement based on the breakpoint. So is there truly no way of getting the current breakpoint? Or how would you change rowHeight in a responsive grid?

**Comment by richbai90** [comment]
This is an old issue, but from the examples it looks like you can now get the breakpoint name and columns.

```js
 // We're using the cols coming back from this to calculate where to add new items.
  onBreakpointChange(breakpoint, cols) {
    this.setState({
      breakpoint: breakpoint,
      cols: cols
    });
  }
```

**Comment by mcflythekid** [comment]
> This is an old issue, but from the examples it looks like you can now get the breakpoint name and columns.
> 
> ```js
>  // We're using the cols coming back from this to calculate where to add new items.
>   onBreakpointChange(breakpoint, cols) {
>     this.setState({
>       breakpoint: breakpoint,
>       cols: cols
>     });
>   }
> ```

But what happen when the component is load and the onBreakpointChange method was not invoked yet

**Comment by eric-burel** [comment]
Hi, this issue is still valid as far as I know, however it could probably be fixed with a small PR. Breakpoint could be provided in callbacks for example.

**Comment by borys-kupar** [comment]
As a workaround, you can import `getBreakpointFromWidth` util function and calculate it yourself, the same way RGL does, because it's exported:
```
import { Layout, Responsive } from 'react-grid-layout';

Responsive.utils.getBreakpointFromWidth(breakpoints, screenWidth)
```
