### ISSUE TITLE
Check if an item is being resized (isResizing prop)

### ISSUE THREAD

**Issue by kachkaev** [STRML/react-grid-layout#188]
I embedded a leaflet-based map into one of the grid items and would like to differentiate between the states when a component is being resized and when it is ‘stable’. In other words, I would like an item to have something like a `isResizing` prop supplied by `react-grid-layout`.

The reason why this may be useful is the following:

1) When a component is stable (not being resized), I would like to push all the changes in the state of the map (zoom, center, etc.) to some kind of a global state document.

2) When a component is being resized, I would not like these changes to propagate. In case of a leaflet map, the resizing of a container requires calling `invalidateSize()` inside `componentDidUpdate`, which creates a side-effect. The coordinates of the map center slightly change after each `invalidateSize()` because of lat/lon to pixel rounding. This results in too many tiny modifications of the global state per second, which is obviously not desirable.

Debouncing a callback for `onLeafletMoveend` helps a bit, but is not ideal. When I drag the resize handler, stop for a bit without releasing the mouse button and then continue dragging, the change of the map state is being triggered despite that it should not (resizing has not finished yet). If a grid item was supplied with something like `isResizing=true/false`, it would be possible to avoid this issue and all would be perfect.

Sorry for being too specific about the leaflet, but I guess this particular case represents a wider need to have `isResizing` prop or something similar.

Cheers and thanks a lot for such an awesome component!

**Comment by STRML** [comment]
I agree with this, and I'm running into a similar situation with BitMEX.

I've thought about passing the entire layout item along as a prop to the child - that is, `h`, `w`, `x` and `y`, but also max/min, `resizing`, and so on.  It would come down from `<GridItem>` to its child.

Now, here's the rub - a lot of people put `<div>` elements around their grid children so that style and className are cleanly mixed in. So could it make more sense to use `context` here so deeper components can grab it? Are there performance/usability problems if we do?

**Comment by kachkaev** [comment]
Great, thanks for the tip! I've already been using this trick with a wrapped div to gain width and height in the child component, now there's one more prop:
```js
const resizing = this.props.className.indexOf(' resizing ') !== -1;
```
Although the interface now works as expected, I guess it would be a bit more efficient to have a clean solution as you describe. My current implementation requires cloning components [as suggested in issue #14](https://github.com/STRML/react-grid-layout/issues/14#issuecomment-71090336), which may result some extra CPU work and hangs in older browsers.
