### ISSUE TITLE
No transitions on layout change

### ISSUE THREAD

**Issue by giacomorebonato** [STRML/react-grid-layout#189]
Hi, I have successful implemented the component.
I have a responsive layout with breakpoints.
Everything works but when I have a layout change on breakpoints (columns++ or --) the layout changes without animation.
What am I missing?

**Comment by Sunakujira1** [comment]
Transitions aren't there by default, you should have a look at [styles.css](https://github.com/STRML/react-grid-layout/blob/master/css/styles.css) that are used on the examples to create transitions.
