### ISSUE TITLE
Difficulty in Server side rendering

### ISSUE THREAD

**Issue by khankuan** [STRML/react-grid-layout#198]
Hey, there seems to be a way for server-side rendering:

```
// This allows setting the initial width on the server side.
// This is required unless using the HOC <WidthProvider> or similar
width: React.PropTypes.number.isRequired,
```

However, server-side wouldn't be getting the initial width on initial load. Would like to know how others are handling it. Thanks!

**Comment by STRML** [comment]
Unfortunately.... You really don't. You have to choose a width, or find a
way to round-trip it from the client before rendering.

One possible solution is to use percentages throughout the project, but
this makes using translateX and translateY difficult because percentages
there refer to the item itself, not it's container. Could be done, just
fiddly and haven't had the time.

**Comment by khankuan** [comment]
Ah ic. :/

**Comment by khankuan** [comment]
Could we do translate in px but everything else in %?

**Comment by STRML** [comment]
Well, then it'd just be a guess - at that point you're better off just providing a width.

**Comment by STRML** [comment]
The right solution would involve figuring out exactly what percentage of the container's width each item is, but this could be tricky due to margins, which are (and should be) specified in `px` values, not percentages.

**Comment by bravo-kernel** [comment]
Sorry for asking but to prevent all misinterpretations... do I understand correctly that " finding a way to round-trip it from the client before rendering" is required even when using the HOC <WidthProvider>?

In other words, SSR will not work when using responsive-grid-layout out of the box (yet).

**Comment by bravo-kernel** [comment]
Suggestions/example more than welcome so I can add an example to the docs.

**Comment by STRML** [comment]
Try out `0.12.5`. The strategy for a while has been to just use percentages and `top/left` on initial render, then to switch to CSS transforms on mount. This means we should get a seamless transition once we have an actual width, while using percentages to handle any width the user started out at.

This won't work for responsive layouts (we have no idea what breakpoint the user is at), but it should work in most use cases.

**Comment by mrsufgi** [comment]
@STRML so is responsive layout with SSR impossible?

**Comment by STRML** [comment]
@mrsufgi Yes - how would the server know what the client's width is? If you had a way to get it to the layout, you could render the grid properly.

Ideally, I'd like the whole position of the grid to be built by a `<style>` element, but it could be expensive to do properly - modifying global styles causes an app-wide `layout` which is very expensive. It would be a very long & difficult rewrite.

**Comment by mrsufgi** [comment]
@STRML are you saying that every implementation of a responsive layout won't work in SSR, unless we know the width of the client the server is rendering to?

If the grid is based entirely on percentages and mediaquerys, like bootstrap for example, we might be able to get it to work?

**Comment by STRML** [comment]
See my second paragraph above - media queries only work via a global `<style>` element, which could be a performance disaster (although the only way to be sure is to test it). If it were implemented, however, it could work.
