### ISSUE TITLE
Avoid drag for parts of the Grid item

### ISSUE THREAD

**Issue by Niondir** [STRML/react-grid-layout#204]
Hi,
I like to have a button that does something like closing or opening an modal dialog. Whenever I click my button the "onDrag" of the underlying grid item is triggered. Is there any way to avoid that?

I'm playing around with different events and stopping them to propagate, but no luck so far.

**Comment by STRML** [comment]
You can pass a `cancel` or `handle` selector to the grid. See https://github.com/STRML/react-grid-layout#grid-layout-props and the [draggable demo](http://mzabriskie.github.io/react-draggable/example/) for some examples.

**Comment by Niondir** [comment]
I found something in the code that worked:

 // A selector that will not be draggable.
    draggableCancel: PropTypes.string,

You can set it on the GridLayout. Was quite some searching :) But now it works.
