### ISSUE TITLE
Update to react v15.0

### ISSUE THREAD

**Issue by kachkaev** [STRML/react-grid-layout#205]
See https://facebook.github.io/react/index.html

After upgrading to react@15.0.0 and react-dom@15.0.0 npm starts complaining:
```
npm WARN react-grid-layout@0.11.2 requires a peer of react@^0.14.3 but none was installed.
npm WARN react-grid-layout@0.11.2 requires a peer of react-dom@^0.14.3 but none was installed.
```

**Comment by STRML** [comment]
:+1: Going to have to test this to make sure. The peerDep line from [react-intl](https://github.com/yahoo/react-intl/blob/master/package.json#L48) should work. Accepting PRs.

**Comment by STRML** [comment]
`0.11.3` now supports v15.
