### ISSUE TITLE
Limit dragging to x/y axis

### ISSUE THREAD

**Issue by cferrios** [STRML/react-grid-layout#206]
Hello,
Is it feasible to support horizontal/vertical-only dragging like https://github.com/mzabriskie/react-draggable?

**Comment by STRML** [comment]
Technically, no. Would be willing to accept a PR that allows passing arbitrary props to Resizable/Draggable.

**Comment by aphougat** [comment]
Shouldn't it be just possible by keeping the width of the item as 100% for vertical axis dragging and also disabling the resize of the child component. Am i missing something here ?
