### ISSUE TITLE
Interactivity in an RGL item causes layout reset...

### ISSUE THREAD

**Issue by Wind4Greg** [STRML/react-grid-layout#209]
I'm using RGL as part of a networking teaching tool and currently have two resizable items (panels). One of the items contains a collection of tabs with different tables in each tabs and this works fine can move/resize and interact with the tabs without any problem.

The other item includes a D3 based visualization of a network which supports pan/zoom, element selection/highlighting etc... This shows up fine but when I do redraws of the visualization in response to user actions the RGL item containing this jumps back to its original position and size.  Has anyone seen this?  Recommended procedure to avoid this? Some way to save the current layout to state?

Thanks ahead of time.
Cheers
Greg B.

**Comment by RiiD** [comment]
You can pass onLayoutChange callback to RGL. It will be called when layout changes so you can save it.

**Comment by Wind4Greg** [comment]
Thanks for the quick response! Working great now.
