### ISSUE TITLE
Drag on different events

### ISSUE THREAD

**Issue by sunnylittle** [STRML/react-grid-layout#210]
Is there a way to specify which event to drag an item on? Or does it have to always be mousedown, I would like to drag on shift+mousedown specifically. Any reccomendations?

**Comment by STRML** [comment]
Technically, `<Draggable>` supports this via a callback, but it I thought it too complex of an API to propagate that callback all the way to the root.

Here's an idea: you could add a window-level keyDown handler for `shift` (check `e.shiftKey`), and use that to modify the `isDraggable` attribute of the layout.

**Comment by sunnylittle** [comment]
Good idea. I'll try that now.

**Comment by sunnylittle** [comment]
That didn't work. Well, it did work as in the layout became 'draggable' but the children (items) were removed/readded to the dom in the process which messes up my content.

**Comment by STRML** [comment]
Hmm. Okay. That makes sense, as `<Draggable>` itself is a wrapper.

This is nasty, but you could set `draggableHandle` to `.__doesnt_exist`, which effectively tells the draggables only to drag if the mouse clicks something matching that selector.

**Comment by sunnylittle** [comment]
lol, that is what I had originally. 
But how would I then drag the whole element on shift+mousedown? Change the handle to grid-item?

**Comment by STRML** [comment]
Or just remove it entirely.

**Comment by STRML** [comment]
If no handle is specified, `<Draggable>` considers the entire element as draggable.

**Comment by sunnylittle** [comment]
Ah, okay. I'll try that.

**Comment by sunnylittle** [comment]
It kinda worked, except I have to click again to drag, so shift+mousedown enables dragging on the whole element by removing the draggableHandle but i have to click again to actually drag. :-/

**Comment by vividviolet** [comment]
We ran into the same issue and was able to trigger the drag by dispatching a mousedown event to the draggable element.
We did something like var dragEvent = new MouseEvent("mousedown", {
            bubbles: true,
            cancelable: true,
            view: window,
            synthetic: true,
            button: 0,
            buttons: 1,
            screenY: e.screenY,
            screenX: e.screenX,
            clientX: e.clientX,
            clientY: e.clientY,
            pageX: e.pageX,
            pageY: e.pageY
        });

and then element.dispatchEvent(dragEvent);

This allowed dragging to start without having to click again

**Comment by sunnylittle** [comment]
Okay, thanks. Looks like I'll have to do something similar.

**Comment by sunnylittle** [comment]
Did you dispatch the event on the draggable element? I thought dispatching the event on my component (where my handlers are) would work but it doesn't seem to be.
How were you able to get a reference to the draggable element?

**Comment by vividviolet** [comment]
You should be able to do e.target.dispatchEvent(dragEvent) as the event's target should be your draggable element

**Comment by sunnylittle** [comment]
That worked. Thanks!

**Comment by hepiyellow** [comment]
if you want to drag only on Shift+MouseDown,
you can have your component not draggable by default,
and when Shift is pressed you can re-render your component and make it draggable.

I like this method since it also let's me style my component differently when it is draggable, so the user knows he can act on it.
