### ISSUE TITLE
Incorrect margin

### ISSUE THREAD

**Issue by IlyaZaprutski** [STRML/react-grid-layout#211]
When I set margin = [10,10] then I got an incorrect result.

On the first image margin = [0,0] 
![margin 0 0](https://cloud.githubusercontent.com/assets/10133494/14484499/ab4128c6-0159-11e6-8517-37da4db910c5.png)

On the second image (with the same settings except margin ) margin = [10,10] 
![margin 10 10](https://cloud.githubusercontent.com/assets/10133494/14484582/2b518772-015a-11e6-91e5-d65d49e338f6.png)

As you can see the size of the grid items increased significantly in the secind case.

**Comment by STRML** [comment]
Could you provide a jsfiddle or other demo replicating this?

**Comment by IlyaZaprutski** [comment]
I this case margin = [10,10]
https://jsfiddle.net/ilya_zaprutski/69z2wepo/39069/

I this case margin = [0,0]
https://jsfiddle.net/ilya_zaprutski/6jt69wnt/1/

As you can see the block size has changed.

**Comment by STRML** [comment]
Okay - this is expected:

In your fiddle with `[10, 10]`: https://jsfiddle.net/xs2ybywc/

You've defined a row height of `10px`, and each item is 10 rows high. Now, the margin is the margin between *each grid unit*, so if you have an item that's 10 rows high, it's `rowHeight * rows + (marginH * (rows - 1))`, or 190px.

I assume [this fiddle](https://jsfiddle.net/ilya_zaprutski/6jt69wnt/1/) is more what you are expecting.

**Comment by IlyaZaprutski** [comment]
Thank you very much. Your answer really helped me.
