### ISSUE TITLE
Exception when there is no child

### ISSUE THREAD

**Issue by slavikshen** [STRML/react-grid-layout#216]
The grid layout works smoothly.  However, it throw an exception when there is no child.
I load the content dynamically so there is no guarantee of child elements.

utils.js:362Uncaught TypeError: Cannot read property 'key' of undefinedw @ utils.js:362m @ ReactGridLayout.jsx:149ReactGridLayout @ react-grid-layout.min.js:577ReactCompositeComponentMixin.mountComponent @ react-with-

The bug is in the initial state. The layout should check the existence of children before use it.
`
state: State = {
    activeDrag: null,
    isMounted: false,
    layout: synchronizeLayoutWithChildren(this.props.layout, this.props.children,
                                          this.props.cols, this.props.verticalCompact),
    oldDragItem: null,
    oldResizeItem: null
  };
`

**Comment by STRML** [comment]
I don't consider this an RGL bug - plenty of components call `React.Children.only(this.props.children)` and for good reason.

If you have no children, don't render RGL at all.
