### ISSUE TITLE
onWidthChange callback could fire between breakpoints?

### ISSUE THREAD

**Issue by owenhoskins** [STRML/react-grid-layout#218]
Hello, I've just started working with this package and am finding it very promising so far!

One need that concerns my use-case is the ability to maintain the aspect-ratio of the gridItems during window resizing "between" breakpoints. 

I was looking into using the onWidthChange callback to dynamically adjust the rowHeight as I saw discussed in a previous issue. However, the callback only fires on breakpoint change, which doesn't allow me to run any width based logic between breakpoints.

Would there be any issues with firing the onWidthChange callback during all window resize events and onBreakpointChange only at new breakpoints? Or is there another avenue worth exploring?

This would be important for blocks that contain images for example.

Curious to hear your thoughts, thanks!

**Comment by STRML** [comment]
Width listening is provided by `WidthListener` - this is a very simple component. I would suggest having it fire its own events, which you then listen to.
