### ISSUE TITLE
Resize / drag and text select 

### ISSUE THREAD

**Issue by kachkaev** [STRML/react-grid-layout#221]
Looks like [`react-draggable`](https://github.com/mzabriskie/react-draggable) and [`react-resizable`](https://github.com/STRML/react-resizable) attempt to prevent text select. While the mouse is pressed and moving, `-webkit-user-select: none;` is added to `<body`>. Despite all this, I am still able to observe this unwanted effect.

The following workaround partially solves the problem, with not for all cases:

``` js
// New method for component that contains the grid
  _preventTextSelect(a, b, c, d, event) {
    event.preventDefault();
  },

// In render()
      <MyReactGridLayout
        layout={ layout }
        onDrag={ this._preventTextSelect }
        onResize={ this._preventTextSelect }
        onResizeStop={ this._preventTextSelect }
        {...this.props}
      >
```

Attaching `preventTextSelect()` to the three events does not help when the size of a grid item has reached some allowed limit and so mouse movements temporary do not change it. Because `event.preventDefault();` is not called under such conditions, text selection stats to appear and change.

The above was observed in Chrome Version 50.0.2661.86 (64-bit) os OSX (not only in my project, but the examples too).

Anyone else with the same issue? Any thoughts?

**Comment by STRML** [comment]
I can't replicate this on Chrome 51.0.2704.22 beta (64-bit) - OSX.

Could you try Beta/Canary or Firefox and see if you still have the issue there? I noticed a few Chrome regressions in 50, perhaps you're running into another one of them.

**Comment by kachkaev** [comment]
Unfortunately I could observe this in FF 45 on Mac as well:
![screen shot 2016-04-23 at 17 23 21](https://cloud.githubusercontent.com/assets/608862/14762675/4866ccfc-0978-11e6-9d13-81a7d994f3c9.png).

**Comment by kachkaev** [comment]
Interestingly, my hack does not even work in FF

**Comment by AmirMeirbekov** [comment]
@kachkaev did you manage to solve this problem? I am experiencing the same with Chrome 53.0.2785.116 (64-bit)

**Comment by kachkaev** [comment]
@AmirMeirbekov no I'm afraid :–( Haven't been using this grid for a while.

**Comment by rookiebob** [comment]
remember that:
Include the following stylesheets in your application:

`/node_modules/react-grid-layout/css/styles.css`
`/node_modules/react-resizable/css/styles.css`

**Comment by AndrewDaborn** [comment]
I'm getting this on Chrome Version 76.0.3809.87 (Official Build) (64-bit)

I've included the stylesheets files in my project:
```
/node_modules/react-grid-layout/css/styles.css
/node_modules/react-resizable/css/styles.css
```

My fix was to add `user-select: none` to the react-grid-layout DOM container.

**Comment by Kushagra8888** [comment]
For firefox and safari, adding `user-select` and its relevant vendor prefixes prevents selection while dragging, but it creates another problem wherein the scrolling up/down behaviour when an item is dragged up to the edges stops working...

**Comment by lllulianjie** [comment]
I fixed by add 
`.react-draggable-transparent-selection {
  user-select: none;
}`

**Comment by andynemzek** [comment]
For me, the highlighting was happening while using react's strict mode.  DraggableCore appears to add the `react-draggable-transparent-selection` class to the body el on [**_drag start_**](https://github.com/react-grid-layout/react-draggable/blob/v4.4.5/lib/DraggableCore.js#L320) and then removes it either on [**_drag stop_**](https://github.com/react-grid-layout/react-draggable/blob/v4.4.5/lib/DraggableCore.js#L405) or [**_component will unmount_**](https://github.com/react-grid-layout/react-draggable/blob/v4.4.5/lib/DraggableCore.js#L261).  When in strict mode, react does an extra mount/unmount/mount cycle.  So, I could see the class getting added on drag start, but then it would disappear when actually dragging the item...presumably due to extra unmounts during rendering. Since the class only gets added on drag start, it would stay removed during dragging and the highlighting issues would ensue.  

Disabling strict mode and/or using a production build removed the issue. Hopefully this saves someone else some time.

**Comment by lllulianjie** [comment]
你好，邮件已收到，谢谢。。

**Comment by hamidkhaleghi** [comment]
I do this approach inside a Nextjs app using tailwind:

```
onDragStart={() => {
	if (isBrowser) {
		document.querySelector('body').classList.add('select-none')
	}
}}
onDragStop={() => {
	if (isBrowser) {
		document.querySelector('body').classList.remove('select-none')
	}
}}
```

**Comment by lllulianjie** [comment]
你好，邮件已收到，谢谢。。

**Comment by dalalRohit** [comment]
> For firefox and safari, adding `user-select` and its relevant vendor prefixes prevents selection while dragging, but it creates another problem wherein the scrolling up/down behaviour when an item is dragged up to the edges stops working...

is there any solution to the auto-scroll issue?

**Comment by dalalRohit** [comment]
> For me, the highlighting was happening while using react's strict mode. DraggableCore appears to add the `react-draggable-transparent-selection` class to the body el on [**_drag start_**](https://github.com/react-grid-layout/react-draggable/blob/v4.4.5/lib/DraggableCore.js#L320) and then removes it either on [**_drag stop_**](https://github.com/react-grid-layout/react-draggable/blob/v4.4.5/lib/DraggableCore.js#L405) or [**_component will unmount_**](https://github.com/react-grid-layout/react-draggable/blob/v4.4.5/lib/DraggableCore.js#L261). When in strict mode, react does an extra mount/unmount/mount cycle. So, I could see the class getting added on drag start, but then it would disappear when actually dragging the item...presumably due to extra unmounts during rendering. Since the class only gets added on drag start, it would stay removed during dragging and the highlighting issues would ensue.
> 
> Disabling strict mode and/or using a production build removed the issue. Hopefully this saves someone else some time.

This helped for me, thank you so much 🙏🏻 🙌🏻

**Comment by lllulianjie** [comment]
你好，邮件已收到，谢谢。。
