### ISSUE TITLE
Item change does not re-render ReactGridLayout

### ISSUE THREAD

**Issue by ghost** [STRML/react-grid-layout#222]
I just need `ReactGridLayout` to reRender itself when items changed.
In my case `{items}` are generated from props which are updated by parent component. 

`const items = this.getItems();`
`<ReactGridLayout {...this.props.gridProps}>
            {items}
          </ReactGridLayout>`

Also went through [issue 156](https://github.com/STRML/react-grid-layout/issues/156) but didn't help.

PS. work around for this is to assign random key to ReactGridLayout, but I'd rather do it the right way.

**Comment by STRML** [comment]
The issue is that we're not regenerating the layout unless the `length` of the children changes:

```js
    // If children change, also regenerate the layout. Use our state
    // as the base in case because it may be more up to date than
    // what is in props.
    else if (nextProps.children.length !== this.props.children.length) {
      newLayoutBase = this.state.layout;
    }
```

This is because it's generally difficult to effectively diff children so we can avoid expensive recalculations. I'm open to a better solution. Perhaps we need to check their `key`s?

In the meantime, you can fix this by changing the `layout` prop if your items have significantly changed.

**Comment by varandpez** [comment]
Thanks @STRML , the issue is that in my case the components `key`s are immutable. 

I looked at the code and noticed that RGL supposed to rerender when the layout changes (exactly one condition check from what you mentioned) 

```javascript
// Allow parent to set layout directly.
  if (!isEqual(nextProps.layout, this.props.layout)) {
      newLayoutBase = nextProps.layout;
  }
```

This should also be applied to layouts provided inline. such as(and in my case):
```javascript
<div key={c.props.id}
     _grid={{i:c.props.id, x:x, y:y, w:w, h:h, minW:minW, minH:minH}}>
        {c}
</div>
```

I'm sure that (in my case again :) ) the length of items is not changed but the inline layout of each is.
Any suggestion on this?

Thanks.

**Comment by varandpez** [comment]
Another quick hack would be to extract `_grid` from each item right before RGL and assign it to `layout` props so that it becomes state and re-render on layout change.

**Comment by Jero786** [comment]
@varandpez yeap I ended with adding to each GridItem the key attribute some string difference each time that I need to re-render. Additionally I needed too trigger manually `resize` event and call `forceUpdate` the parent component that contain RGL. :(

**Comment by suhabaobaid** [comment]
@Jero786  How are you triggering resize event manually? I am dealing with the same issue

**Comment by Jero786** [comment]
Is very Ugly but just work for me.

```
class YourParentRGLClass extends React.component {

    constructor(props) {
        super(props);
        this._fireResize = this._fireResize.bind(this);
        this.onResize = this.onResize.bind(this);
   }

    onResize() {
        this.forceUpdate();
    }

   componentDidUpdate() {
        if (this.state.needResizeManually) {
             this._fireResizeManually();
         }
    }

     /**
     * Fire resize event in order to repaint dashboard.
     * @private
     */
    _fireResizeManually() {
        this.timeoutResizing = setTimeout(() => {
            const evt = document.createEvent('UIEvents');
            evt.initUIEvent('resize', true, false, window, 0);
            window.dispatchEvent(evt);
        }, 301); // wait just 1 millisecond more than transition open/close dashboard notes animations
    }

    render() {
             const itemsEl = this.drawItemsEl();
             <div className="your-parent-class">
                    <ResponsiveReactGridLayout
                       ..
                        onResize={this.onResize}
                       ..
                    >
                        {itemsEl}
                    </ResponsiveReactGridLayout>
             </div>
    }
...
}
```

I hope that help you! 
Greetings!
Jero

**Comment by CrazyWood007** [comment]
> Thanks @STRML , the issue is that in my case the components `key`s are immutable.
> 
> I looked at the code and noticed that RGL supposed to rerender when the layout changes (exactly one condition check from what you mentioned)
> 
> ```js
> // Allow parent to set layout directly.
>   if (!isEqual(nextProps.layout, this.props.layout)) {
>       newLayoutBase = nextProps.layout;
>   }
> ```
> 
> This should also be applied to layouts provided inline. such as(and in my case):
> 
> ```js
> <div key={c.props.id}
>      _grid={{i:c.props.id, x:x, y:y, w:w, h:h, minW:minW, minH:minH}}>
>         {c}
> </div>
> ```
> 
> I'm sure that (in my case again :) ) the length of items is not changed but the inline layout of each is. Any suggestion on this?
> 
> Thanks.

In my case, the root cause is a type mismatch between `layout.i` and `key`, so that ReactGridLayout can't find the correct grid item to apply changes. The type of `layout.i` is number and the type of react key is string
