### ISSUE TITLE
Item should return to it's initial position when drop didn't happen on its grid

### ISSUE THREAD

**Issue by ghost** [STRML/react-grid-layout#223]
I think this will be a great improvement. When I drag my item(lets call it itemA) around it pushes other items away to adjust itself to grids. Lets say itemB was pushed down to next available grid. I'm still dragging and the mouse button is down and decided continue dragging, moving away from itemB, itemB should return to its original grid. It will be great to have a flag for this.

**Comment by varandpez** [comment]
This is also happening on resize. When an item collides with other items, it pushes them away to make room for itself. But if I continue resizing while holding the mouse key down, and make the item small again, the item that was pushed away should return to its initial position.

Any comment on this would be appreciated.

**Comment by e2raptor** [comment]
And it does. The behaviour you describe only happens when your <ReactGridLayout> has the props verticalCompact as false, which is true by default.

**Comment by varandpez** [comment]
Not exactly the way I described. If you drag diagonally the item that was pushed away does not come to it's place if drag continues. That's because the new layout is persisted on `onDrag` function via `setState`.

**Comment by STRML** [comment]
Yes - this is because the compacting algo is not storing the initial layout when the drag starts. It would be nice if it did, and reverted to it `onDragStop`. Otherwise, some sort of internal concept of 'affinity' (aka I moved here to get out of the way, but if it turns out I can fit back in my original place, do so) would be great.
