### ISSUE TITLE
Inner grid gets default width and not parent grid's width

### ISSUE THREAD

**Issue by zero-** [STRML/react-grid-layout#23]
I'm not sure if this is a bug or feature but in any case, help is appreciated :)

My structure is like this:
```
Grid 1 with 12 columns
    div using all 12 cols
         Grid 12 columns
              ....
```
Now grid 1 gets the full width of the window but grid 2 for some reason defaults to 1280px. However if I resize the window grid 2 correctly sets itself to grid 1's width.

I tried ```initialWidth={window.innerWidth}``` with grid 2 but it politely ignored it and used 1280px.

**Comment by STRML** [comment]
I'll give this a shot - to be honest I haven't tried nested grids but of course there's no reason why it shouldn't work, aside from some potentially weird dragging issues.

**Comment by STRML** [comment]
By the way, this may help you get to the bottom of it - both `ReactGridLayout` and `ResponsiveReactGridLayout` mix in the `WidthListeningMixin`: https://github.com/STRML/react-grid-layout/blob/master/lib/mixins/WidthListeningMixin.js

**Comment by zero-** [comment]
There seems to be some sort of bug here in play but I got it to work with
```
componentDidMount: function(){
	setTimeout(function(){
		window.dispatchEvent(new Event('resize'));
	},1)
}
```
Not pretty but seems to work. I wonder if grid executes before DOM has been properly processed so it can't get width and goes to the default? Btw, jQuery ```$(window).trigger('resize')``` doesn't seem to work for this.

**Comment by STRML** [comment]
Please reopen if this is still an issue for you; these problems should be more or less solved with the new WidthProvider HOC.
