### ISSUE TITLE
How to drag item from nested grid into out grid?

### ISSUE THREAD

**Issue by ivansglazunov** [STRML/react-grid-layout#235]
As in jQuery UI droppable.

**Comment by ayonghosh** [comment]
@ivansglazunov Have you been able to find a solution to this yet? I'm not sure this is supported or even meant to be supported.

**Comment by ivansglazunov** [comment]
At that moment, I did not find a solution. I'll need it again soon and look for it.

**Comment by herbertpimentel** [comment]
+1

**Comment by IamDLY** [comment]
+1
