### ISSUE TITLE
ReactGridLayout component render issue

### ISSUE THREAD

**Issue by kadishay** [STRML/react-grid-layout#236]
When rendering the ReactGridLayout we are receiving the below errors - when removing the ReactGridLayout everything renders well.

Version: 0.12.3.

Can you please advise?

Render Function:
```html
render() {
        var layout = [
            {i: 'a', x: 0, y: 0, w: 2, h: 2, static: true},
            {i: 'b', x: 3, y: 0, w: 3, h: 1},
            {i: 'c', x: 0, y: 1, w: 1, h: 2}
        ];
        return (
            <div className='page-wrapper'>
                Component below:
                <ReactGridLayout className="layout" layout={layout} cols={6} rowHeight={150} style={{position: 'relative'}}>
                    <div key={'a'}>
                    </div>
                    <div key={'b'}>
                    </div>
                    <div key={'c'}>
                    </div>
                </ReactGridLayout>
            </div>
        )
    };
```

Console:
Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `ComponentTestPage`.
invariant.js:39 Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `ComponentTestPage`.

**Comment by STRML** [comment]
This is fixed in `1.4.1` of `react-resizable`, see [this commit](https://github.com/STRML/react-resizable/commit/90635fd5eae5e59761f5bd5c0c92cb69cdc74bc4). Please update and the error will go away. Thanks!
