### ISSUE TITLE
Add 'oldLayout' to onLayoutChange callback params

### ISSUE THREAD

**Issue by larrydahooster** [STRML/react-grid-layout#237]
It would be nice to have access to the 'oldLayout' (layout before change) in the onLayoutChange callback. The problem is that the onLayoutChange callback gets fired even if the layout did not change. This happens for instance when you drag an item and drop it on the same position.

The problem without having the 'oldLayout' available in the onLayoutChange callback is that you can't reproduce if the layout did change. As we need to compute other stuff according to layout changes it would be nice if we could skip the computations when the layout didn't change.

As you keep the layout on the state I think the best idea for solving this would be to create a deep copy of the state before manipulation and also pass it to onLayoutChange. This wouldn't grant shallow compare but a deep equal check would be nice though.

**Comment by lxm7** [comment]
Is there anything in the API now to workaround this? I've looked over the updates and surrounding topics but looks like i'll have to implement a timeout and nullify the onLayoutChange manually, as per https://github.com/STRML/react-grid-layout/issues/558
