### ISSUE TITLE
If className is not explicitly set the grid outputs class='react-grid-layout undefined'

### ISSUE THREAD

**Issue by larrydahooster** [STRML/react-grid-layout#238]
The className merge causes the grid to render class='react-grid-layout undefined'  if no className is provided via props

    const {className, style} = this.props;
    const mergedClassName = `react-grid-layout ${className}`;

https://github.com/STRML/react-grid-layout/blob/0.12.3/lib/ReactGridLayout.jsx#L407

**Comment by STRML** [comment]
Thanks, fixed.
