### ISSUE TITLE
grid layout hangs chrome on touchscreen

### ISSUE THREAD

**Issue by phullphill** [STRML/react-grid-layout#239]
@STRML We're using react-grid-layout@0.12.3 with react@15.0.2 and running it using Chrome 50.0.2661 on a touch screen laptop. Drag and drop and resize work fin as long as we use the mouse. But when using the touch screen drag works OK for a while but after a resize or two chrome just hangs. It also has trouble detecting the resize handle touch event; you sometimes have to touch and drag more than once before it will do a resize action. Should we be using some extra react module or plugin? Or is there some grid-layout configuration property we should be setting? Any help will be much appreciated.

**Comment by STRML** [comment]
This is fixed in 0.12.4.
