### ISSUE TITLE
Small dragging bug

### ISSUE THREAD

**Issue by zero-** [STRML/react-grid-layout#24]
I was playing around with https://strml.github.io/react-grid-layout/examples/0-showcase.html and I noticed that if you scroll to the bottom and start to drag a cell upward so that the window scrolls, the pointer jumps a bit from it's original position in the cell.

Nothing breaking but a cosmetic issue.

**Comment by STRML** [comment]
This is a [react-draggable](https://github.com/mzabriskie/react-draggable) bug - basically, the drag deltas should change if the window scrolls, but there isn't any scroll listener being added while the drag is active.

A solution would be to add a window 'scroll' listener on drag start, and remove it on drag end. If a scroll happens, use the listener to figure out how much it scrolled by, and adjust the drag `y` position by that amount.

**Comment by STRML** [comment]
Please reopen this issue on react-draggable if you would like it fixed. Thanks for reporting.

**Comment by jardakotesovec** [comment]
I just run into this issue. This should be right [cross](https://github.com/mzabriskie/react-draggable/issues/151) reference.  So hopefully this will work fine once react-grid-layout gets updated to use new react-draggable?

**Comment by STRML** [comment]
This is fixed in v0.12.4.
