### ISSUE TITLE
Drag event appears not to respect event bubbling

### ISSUE THREAD

**Issue by tquetano-r7** [STRML/react-grid-layout#241]
When I have something like this:
```
<ReactGridLayout
  ...
  draggableHandle=".drag-handle"
>
  <div
    ...
    className="drag-handle"
  >
    Test
  </div>
</ReactGridLayout>
```
Dragging works correctly, however if that element has nested children:
```
<ReactGridLayout
  ...
  draggableHandle=".drag-handle"
>
  <div
    ...
    className="drag-handle"
  >
    <div>
      Test
    </div>
  </div>
</ReactGridLayout>
```
It does not. Applying padding to the tag with the class applied will let you drag specifically on the padding, which tells me that the click / drag event is not bubbling up to the selector for children. Is there a way to manage this? I doubt this is expected behavior.

**Comment by STRML** [comment]
This is https://github.com/mzabriskie/react-draggable/issues/88 - I need to adjust the handle selector to traverse its parents at least up to the `<Draggable>`.

**Comment by tquetano-r7** [comment]
Wow, that was remarkably fast! Thanks for digging in so quickly.

**Comment by STRML** [comment]
A fix for this is now in `<Draggable>` 2.1.0, but RGL still uses Draggable v1. I'll be sure to upgrade it soon.

**Comment by tquetano-r7** [comment]
Dude, you are my personal hero, thank you so much for jumping on this so quickly.

**Comment by STRML** [comment]
:+1: I should have fixed it long ago - thanks for getting me moving.
