### ISSUE TITLE
Masory style - Dynamic row height per each item?

### ISSUE THREAD

**Issue by Noitidart** [STRML/react-grid-layout#242]
I currently use the jQuery isotope code for my image gallery in my screenshot addon for firefox - 

https://addons.mozilla.org/en-US/firefox/addon/nativeshot/

I fixed the width of each column in my responsive layout. So each image is limitied to 300px in width. Packery calls this, "Masonry" layout, I use the "isotope" jquery version - http://isotope.metafizzy.co/ . Now the height takes whatever it needs when width is 300. Can react-grid handle this? I was playing with it but can't seem to find a way to do things with an unfixed height. This is an example of what my thing looks like right now:

![](http://i.imgur.com/KDLlTBD.png)

In the screenshot above I put a red border around each. Here is one without the red border - http://i.imgur.com/c5SP7dI.png

Notice how the tops don't really line up for anything except the very first row. Is this possible with react-grid?

This is the masonry demo on packery website:

![](http://i.imgur.com/mol8vzl.png)

**Comment by Noitidart** [comment]
Hi there I was still struggling with this.

This is what I pulled off so far:

http://noitidart.github.io/nativeshot-react-grid-layout/demo/demo.htm

You can see the spacing between the rows is not collapsing or expanding. So I had to hide the overflow of the div, here is screenshot of that gh-pages demo above:

![](http://i.imgur.com/jmwwkd0.png)

Can you please advise.

**Comment by Noitidart** [comment]
Solved it! Had to use `rowHeight` of `1` and then in the layout set it to the height of the image. Absolutely superb component you got here! Thank you!

**Comment by hepiyellow** [comment]
The solution of setting rowHeight to 1 doesn't work for me, because it only works well if you set the margin to 0.
If you have a default margin of 10px and you have a h=100 for 100px (rowHeight=1px), then the calculated item height would be around 1000px

**Comment by Noitidart** [comment]
@hepiyellow you are correct. I ended up rolling my own.

**Comment by jrock17** [comment]
@Noitidart did you ever figure out how to have a dynamic height? I'm running into the same issue.

**Comment by Noitidart** [comment]
@jrock17  I actually rolled my own solution. It is actually quite a simple thing to do, I have not packaged it though. You can see it in action here - https://addons.mozilla.org/en-US/firefox/addon/nativeshot/ - take some screenshots and then visit the URL "about:dashboard" in Firefox.

**Comment by jrock17** [comment]
@Noitidart awesome. Any guidance as to how you pulled it off would be appreciated. 

I'm stuck between Packery/Draggabilly which doesn't work with Node/React and this which gives me trouble on the dynamic heights. 😄

**Comment by adamerose** [comment]
Just posting here for anyone still trying to do this, after hours trying out packages I found one that works for drag and drop masonry layouts https://codesandbox.io/s/muuri-react-masonry-demo-cpmqy
