### ISSUE TITLE
React components as children throw error

### ISSUE THREAD

**Issue by tquetano-r7** [STRML/react-grid-layout#243]
When attempting regular HTML as children, I have no issues:
```
<ResponsiveGridLayout {...propsHiddenForConciseness}>
  <div key="1">
    One
  </div>
  <div key="2">
    Two
  </div>
</ResponsiveGridLayout>
```
However, once I make it any kind of component, I get an error:
```
const TestComponent = ({children, ...otherProps}) => {
  <div {...otherProps}>
    {children}
  </div>
};
...
<ResponsiveGridLayout {...propsHiddenForConciseness}>
  <TestComponent key="1">
    One
  </TestComponent>
  <TestComponent key="2">
    Two
  </TestComponent>
</ResponsiveGridLayout>
```
It gives me the following error:

`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `TestComponent`. It was passed a child from Resizable. See https://fb.me/react-warning-keys for more information.`

In my component, if I inject a key into its props, the error goes away:
```
const TestComponent = ({children, ...otherProps}) => {
  const childrenFixed = React.Children.map((child, childIndex) => {
    if (child.ref === 'draggable') {
      return React.cloneElement(child, {
        key: 'unique-key-${Math.floor(Math.random() * 1000)}`
      });
    }

    return child;
  });

  <div {...otherProps}>
    {children}
  </div>
};
```
Is this expected behavior? Obviously I am passing a key to the component child to match up to the layout declaration, but internally it appears the key is turned into `null`.

**Comment by STRML** [comment]
Hey - this is my bug, fixed in `1.4.1` of `react-resizable` ([link](https://github.com/STRML/react-resizable/commit/90635fd5eae5e59761f5bd5c0c92cb69cdc74bc4)). Please update and the error will disappear. Thanks!
