### ISSUE TITLE
Resize on each edge

### ISSUE THREAD

**Issue by codTango** [STRML/react-grid-layout#244]
I'm wondering if I can do resize on all edges, make the panel works like a browser, which I can drag and resize on each edge and corner?

**Comment by acusti** [comment]
At least for corners, that feature is next on the main Readme’s [TODO list](https://github.com/STRML/react-grid-layout#todo-list). That said, not sure where progress on that would be tracked.

**Comment by tthamel** [comment]
there is a way to add it to each corner but creating multiple resize classes, but it gets a little messy

**Comment by connorTang** [comment]
@tthamel can you give an example? not sure I understand how to do it.

**Comment by tauren** [comment]
It's been a few years since this was discussed as being next on the TODO list. In the meantime, does anyone have examples of customized resizing behavior? I specifically need to resize by dragging edges, but any example would help.
