### ISSUE TITLE
Simpler/straightforward examples - I couldn't get any of it to work.

### ISSUE THREAD

**Issue by acroyear** [STRML/react-grid-layout#245]
I just argued with this thing for 30 minutes and could not get anything inside the ReactGridLayout object to ever render. I just gave up. If I can't get something very simple to work "out of the box" with some decent error reporting to explain WHY it isn't rendering anything, it is not worth any more of my time.

**Comment by STRML** [comment]
Thank you for your valuable contribution to this not-for-profit project that is run by volunteers in their free time.
