### ISSUE TITLE
Only draggable on title

### ISSUE THREAD

**Issue by connorTang** [STRML/react-grid-layout#246]
I'm thinking if I can make it draggable only when dragging on the title.

**Comment by STRML** [comment]
See https://github.com/STRML/react-grid-layout#grid-layout-props - `draggableHandle`.

**Comment by connorTang** [comment]
Thanks! I still have a question - the draggableHandle receives a string to use as selector, so if I have a div element with class name "Header", how would I make it select only that?

**Comment by STRML** [comment]
@connorTang `.Header`
