### ISSUE TITLE
I can keep dragging a grid component to a far right in Chrome

### ISSUE THREAD

**Issue by codTango** [STRML/react-grid-layout#248]
This seems only happen in Chrome. I just experienced this, I can drag a grid component, and keep dragging it to very far right, so the whole background page becomes blank, then when I release it, it just suddenly goes back to the page.

**Comment by gpouilloux** [comment]
Is there any update on this annoying issue on Chrome?
Just tried on Firefox and I'm not experiencing the same behavior.
