### ISSUE TITLE
Typos in example

### ISSUE THREAD

**Issue by TrySpace** [STRML/react-grid-layout#25]
`<div key={1} _grid={{x: 0, y: 0, w: 1: h: 2}}>1</div>
          <div key={2} _grid={{x: 1, y: 0, w: 1: h: 2}}>2</div>
          <div key={3} _grid={{x: 2, y: 0, w: 1: h: 2}}>3</div>`

3 of those semicolons should be commas

**Comment by STRML** [comment]
I don't follow this report at all - what are you saying?

**Comment by TrySpace** [comment]
The object literals, the're not valid json or javascript.

**Comment by browniefed** [comment]
@TrySpace I don't see a single semicolon. That all looks like valid React and JavaScript to me.
A lot of these issues would probably be better as pull requests since that is much clearer on what you're saying is wrong.

**Comment by TrySpace** [comment]
Sorry, I meant colons
