### ISSUE TITLE
Another Example page using RGL

### ISSUE THREAD

**Issue by Wind4Greg** [STRML/react-grid-layout#250]
Using RGL as part of a free communications networking teaching/research tool. Up to four movable resizable panels. Three of them can be closed/re-opened (help, network info, path info). Network drawing panel is always open. Thanks for the great library!
<img width="873" alt="comnetviz" src="https://cloud.githubusercontent.com/assets/1444268/15717166/9c8ca59c-27da-11e6-9b32-f224ba13b762.png">

See http://www.grotto-networking.com/ComNetViz/ComNetViz.html.

Cheers
Greg B.

**Comment by STRML** [comment]
Very nice, I'll add it.

I'd also suggest setting the draggableHandle prop so the panels don't move
when scrolling on mobile.

Thanks!

**Comment by Wind4Greg** [comment]
Will do. Thanks again.

**Comment by Wind4Greg** [comment]
Is there an example showing how to set the draggableHandle property? I wasn't sure of what to do with it. 
Cheers

**Comment by Wind4Greg** [comment]
Thanks. I also use react-draggable to make some of my modal dialogs draggable.
