### ISSUE TITLE
process.isBrowser is disabling useCSSTransforms

### ISSUE THREAD

**Issue by mikesurowiec** [STRML/react-grid-layout#252]
I think there needs to be a better isBrowser check in place.
https://github.com/STRML/react-grid-layout/blob/master/lib/ReactGridLayout.jsx#L367

I'm able to log `process` and see that `process.platform === 'browser'`. I've never seen this variable used in a client app, where does it come from?

**Comment by STRML** [comment]
@mikesurowiec That property is from webpack/browserify. It's not a great check anyway - I really want the browser to emulate the server environment on initial mount so it doesn't fail the checksum. To that end, see if `0.12.5` (just released) fixes your issue.

**Comment by mikesurowiec** [comment]
Thanks for the quick reply! It's still not working for me though -- it appears `this.state.mounted` never gets set to true in the component

**Comment by STRML** [comment]
Yikes, that was a dumb mistake on my part. `0.12.6`.

**Comment by mikesurowiec** [comment]
Working perfectly now, thank you!
