### ISSUE TITLE
In RRGL, when using lg and creating layout with Infinity, browser hangs

### ISSUE THREAD

**Issue by codTango** [STRML/react-grid-layout#254]
I just experienced this problem that the browser just hangs when I create a new layout with `y: Infinity` and `layouts={{ lg: myLayouts }}`. It works just fine with `layouts={{ md: myLayouts }}`. My screen width is 1358, so I set it to lg as default. I tried this `layouts={{ md: myLayouts, sm: myLayouts, xs: myLayouts }}`, and it works fine, but the browser will hang if i add the `lg: myLayouts`.

**Comment by connorTang** [comment]
I did a little research, this is caused by that when my RRGL mounted, it has no layout, and then later I added the first one with `y: Infinity`. That runs into an infinite loop in the `utils.js` here: 
```javascript
export function compactItem(compareWith: Layout, l: LayoutItem, verticalCompact: boolean): LayoutItem {
  if (verticalCompact) {
    // Move the element up as far as it can go without colliding.
    while (l.y > 0 && !getFirstCollision(compareWith, l)) {
      l.y--;
    }
  }
...
```
A simple fix would be just adding a check to see if the layout is the first or only one here.

**Comment by dmackerman** [comment]
Ran into this today. Sort of seems that `Infinity` is a weird workaround for "adding items at the end". Almost wonder if `x: null, y: null`, should be supported, and then throw those items at the end by default.
