### ISSUE TITLE
Responsive grid items don't move properly

### ISSUE THREAD

**Issue by karmainside** [STRML/react-grid-layout#255]
Just found out a bug when items in responsive grid disappear in some conditions.
You can reproduce it here: https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html
1. Remove all items except [0] and [1].
2. Resize them both to w=5 h=3.
3. Place [1] to the very right side of the grid.
4. Try to resize browser window.

You can also see in the box up to the "Add button" that dimensions changes to 2x2 size, but items stay 5x3 size.

![screenshot from 2016-06-06 16 30 31](https://cloud.githubusercontent.com/assets/5028875/15825506/542f1e00-2c04-11e6-8db7-1cd14ab75cfe.png)
![screenshot from 2016-06-06 16 29 30](https://cloud.githubusercontent.com/assets/5028875/15825511/5650648c-2c04-11e6-80af-98d6988d08a5.png)
![screenshot from 2016-06-06 16 29 11](https://cloud.githubusercontent.com/assets/5028875/15825513/57b05dd2-2c04-11e6-84f3-91fb5babcd39.png)

**Comment by daumann** [comment]
+1

**Comment by daumann** [comment]
Actually it happens when adding any new item. The layouting on resize is broken after that.

**Comment by daumann** [comment]
This should be closed as duplicate of #247
