### ISSUE TITLE
onLayoutChange call too often

### ISSUE THREAD

**Issue by vinej** [STRML/react-grid-layout#257]
I think that the onLayoutChange is called too often. The event is fired even if the size or the position have not changed. One of the problem is that a simple click inside a widget fired the onLayoutChange ?. Maybe a bug on my side!, but I tested a quick fix (see below) and it's seem to do the job. Do you think that you can do the modification into the main the right way ?

ReactGridLayout.prototype.onDragStop
...
=>   if (oldDragItem.x == x && oldDragItem.y == y) return;
       // Set state
       this.setState({
...
ReactGridLayout.prototype.onResizeStop
    ...
=>   if (oldResizeItem.w == w && oldResizeItem.h == h) return;
       // Set state
       this.setState({

Thanks

**Comment by larrydahooster** [comment]
May this is related to a issue that I reported a couple of weeks ago: https://github.com/STRML/react-grid-layout/issues/237
 
onLayoutChange gets even fired if layout did not change.

**Comment by vinej** [comment]
For your information, the modification I did in the previous example DO NOT work. I had to put the check into my code, because the widget was sometime freezing on the drag stop event.

I hope someone will find the right way to do this modification

Thanks

**Comment by uneart** [comment]
I've got the same problem, running react-grid-layout version 0.12.4. `onLayoutChange` is triggered when I start dragging an item and leave it at the same position. Sometimes it is triggered twice when releasing the mouse. The behaviour seems to be somehow random.

In my application `onLayoutChange` calls a Redux action creator that dispatches a Firebase update. Upon being updated in Firebase, the data is fetched back to the Redux state and from there is plugged directly in the RGL props.

Could the problem be that when the props change again, `onLayoutChange` gets called again even if nothing changed?

**Comment by vickyqiu** [comment]
Same problem running version 0.12.4.

**Comment by luangch** [comment]
Same problem. I suspected that the `onDragStop` calls the `onLayoutChange` before layout have actually changed.

Another problem is the `onDragStop` returns a new modified layout state(not in view) when I drag and put an item at the same position, as it stated by @uneart. Even it has only one item in the layout, the `x` and `y` of the item state could be set to the number other than their original.

I have tested a fix in my fork and it is work. I don't know if it is a proper way to do it. Please review my PR.
`if (!isEqual(oldDragItem, l)) this.props.onLayoutChange(this.state.layout);`

**Comment by STRML** [comment]
Merged #328. This will make it into the next release.

**Comment by uttamsingapura** [comment]
I'm still facing this issue on v0.16.6 What is the fix for this issue?

**Comment by rlgreen91** [comment]
@uttamsingapura what is the context behind this for you?  I know that in my code, it seems that `onLayoutChange` is being called for some reason when programmatically displaying a list of items from a redux store.  Looking through the source code, it seems like `onLayoutMaybeChanged` is returning true instead of false when the component mounts.

**Comment by uttamsingapura** [comment]
@rlgreen91 If I have widgets in more than one row, onLayoutChange event is firing neither when the widget is resized nor the coordinates of the widgets are changed, but just by clicking inside the widget.
This is not the issue if I have widget only in one row.

**Comment by quirinpa** [comment]
Why does onLayoutChange get called when the layout is initially set?

**Comment by STRML** [comment]
Because an initial compact is done on render.

**Comment by pooran-ghafoorian** [comment]
Why is react-grid-layout called multiple times? (without any change)
