### ISSUE TITLE
Is there a drag handle option?

### ISSUE THREAD

**Issue by whatifif** [STRML/react-grid-layout#258]
Thank for sharing this great layout.

One thing I miss is a drag handle.
I want to drag the each item by using handle attached on each item.

Is there a drag handle option in react-grid-layout?

**Comment by STRML** [comment]
Yes, it's called draggableHandle. Please see the docs.

**Comment by whatifif** [comment]
Thanks for your quick reply. I found it in the doc. 
This layout seems very useful for dynamic web sites.
