### ISSUE TITLE
getOrGenerateLayout, getLayoutsFromSomewhere, example missing

### ISSUE THREAD

**Issue by TrySpace** [STRML/react-grid-layout#26]
I really like to use this, but there's one mayor issue with the docs.

The most essential part is left out, being the defining of the grid, and you're refering to fictional functions to generate layout. And the demo page is not showing really what exactly to give to `layouts` on the `<ResponsiveReactGridLayout />` only some parsed coordinates, but not the actual format, which is expecting something like this: 

     var layouts = {
        lg:[
          {h:2, w:2, x: 0, y: 0},
          {h:2, w:2, x: 1, y: 0},
          {h:2, w:2, x: 2, y: 0},
          {h:2, w:2, x: 3, y: 0}
        ],
        sm: [
          {h:2, w:2, x: 0, y: 0},
          {h:2, w:2, x: 1, y: 0},
          {h:2, w:2, x: 2, y: 0},
          {h:2, w:2, x: 3, y: 0}
        ],         
        md: [
          {h:2, w:2, x: 0, y: 0},
          {h:2, w:2, x: 1, y: 0},
          {h:2, w:2, x: 2, y: 0},
          {h:2, w:2, x: 3, y: 0}
        ],        
        xs: [
          {h:2, w:2, x: 0, y: 0},
          {h:2, w:2, x: 0, y: 1},
          {h:2, w:2, x: 0, y: 2},
          {h:2, w:2, x: 0, y: 3}
        ],
        xxs: [
          {h:2, w:2, x: 0, y: 0},
          {h:2, w:2, x: 0, y: 1},
          {h:2, w:2, x: 0, y: 2},
          {h:2, w:2, x: 0, y: 3}
        ]
      };

At least I THINK so, but there's not example anywhere to be found of what to give it, except somewhere in the source there's a method that generates some random numbers.

At least give an simple example of what to give to `<ResponsiveReactGridLayout />` 

Are we supposed to guess what `layout1` should look like in: 

    {lg: layout1, md: layout2, ...}

**Comment by STRML** [comment]
Hi,

Keep in mind that this is a free project with a permissive license that I work on, time permitting, for the benefit of the community. You are now owed anything.

That said, I'm aware of the lapse in the docs, and I have another example in progress. I am working on a more elegant way to specify responsive breakpoints as I am working on integrating them in a production application I am working on.

**Comment by holyboom** [comment]
d

**Comment by ganesh-dks** [comment]
Hi STRML,

Thank you so much for all the hard work. I have a minor issue. When I click on the div elements in responsive layout to grab they shift down, although I am able to get the elements for dragging, it is not an expected behavior can you please shed some light. I will share my code if you want to take a look.
