### ISSUE TITLE
Best way to differentiate between click and drag

### ISSUE THREAD

**Issue by mvanlonden** [STRML/react-grid-layout#263]
I have a child `<a>` tag that is clicked on a drag event. 

Currently I'm handling it by having the state track the `i` of the current child 

``` js
_handleDrag = (layout, child) => {
  this.setState({
    indexOfCurrentDraggedChild: parseInt(child.i)
  })
}
```

then on the mapping function for the children checking if the index equals the key

``` jsx
<Link
  to='path'
  onClick={this.state.indexOfCurrentDraggedChild === key ? (e => e.preventDefault()) : null}
>
  <div>child</div>
</Link>
```

on the drop event I set the index back to `null` but I think the drop event fires before the mouseup event so I had to add a timeout 😤

``` js
_handleDragDrop = (layout, child) => {
  this.props.setTimeout(() => {
    this.setState({
      indexOfCurrentDraggedChild: null
    })
  }, 10)
}
```

Is there a better way of doing this?

**Comment by nitronick600** [comment]
I'd be interested in the answer to this as well.

**Comment by vnikolova** [comment]
This worked for me :

```
onDrag(layout, child, newItem) {
    if (child.x !== newItem.x || child.y !== newItem.y) {
        this.setState({
        indexOfCurrentDraggedChild: child.i,
      });
      }
  }
```

it sets the state only when the x or y coordinates have been changed. And add this for the onClick event so the link can be clicked again after dragging is complete

```
 if (this.state.currentDraggedChild === key) {
      e.preventDefault();
      this.setState({
      inddexOfCurrentDraggedChild: null,
    });
    }
```

**Comment by DigitalMarc** [comment]
I'll post the solution I'm using currently (related to [#293](https://github.com/STRML/react-grid-layout/issues/293)).

I went for the idiomatic hacky way but with the lowest friction to sort this out on both firefox and chrome as event handling behave differently.
I listen for `onDrag` (was not working with `onDragStart`) and on `onDragStop`, setting a flag. Once dragging is done I reset that flag with a bit of delay, otherwise `onClick` is triggered.
Simply put the flag is used to secure `onClick`.
Same logic is used for resize. Hope that can help:

```
import React from 'react';
import { Responsive, WidthProvider } from 'react-grid-layout';
import _ from 'lodash';

const ResponsiveReactGridLayout = WidthProvider(Responsive);

class Exemple extends React.Component {
    constructor(props) {
        super(props)
        this.isDragging = false;
        this.isResizing = false;
    }

    static propTypes = {
        onItemClick: React.PropTypes.func.isRequired
    };

    onItemClick = (e) => {
        // idiomatic way to prevent a click when resizing
        if (!this.isDragging && !this.isResizing)
            this.props.onItemClick(e);
    }

    onDrag = (e) => {
        this.isDragging = true;
    }
    onDragStop = (e) => {
        // HACK: add some delay otherwise a click event is sent
        setTimeout((obj) => { obj.isDragging = false }, 200, this)
    }
    onResizeStart = (e) => {
        this.isResizing = true;
    }
    onResizeStop = (e) => {
        // HACK: add some delay otherwise a click event is sent
        setTimeout((obj) => { obj.isResizing = false }, 200, this)
    }
    createElement = (el) => {
        return (
            <div key={el.datagrid.i} data-grid={el.datagrid} onClick={this.onItemClick.bind(this, el.datagrid.i)} >
                <div>....</div>
            </div>
        );
    }
    render() {
        return (
            <ResponsiveReactGridLayout 
            ... // other props
                onDrag={this.onDrag}
                onDragStop={this.onDragStop}
                onResizeStart={this.onResizeStart}
                onResizeStop={this.onResizeStop}
                >
                {_.map(this.props.items, this.createElement)}
            </ResponsiveReactGridLayout>
        );
    }
}
```

**Comment by jy4618272** [comment]
class GridLayout extends Component {
    constructor(props) {
        super(props)
        this.isDragging = false;
        this.isResizing = false;

        this.state = {
            selected: ''
        }
    }

    static propTypes = {
        onItemClick: PropTypes.func,
        rowHeight: PropTypes.number.isRequired,
    };

    /* 组件属性默认值 */
    static defaultProps = {
        rowHeight: 68
    };

    onItemClick = (e, key) => {
        // idiomatic way to prevent a click when resizing
        if (!this.isDragging && !this.isResizing)
        {
            this.setState({selected: key});

            if(this.props.onItemClick)
                this.props.onItemClick(key);
        }
    }

    onDragStart = (layout, oldItem, newItem, placeholder, e, element) => {
        e.stopPropagation();
    }

    onDrag = (layout, child, newItem) => {
        if (child.x !== newItem.x || child.y !== newItem.y) {
            this.isDragging = true;
        }
    }

    onDragStop = (e) => {
        // HACK: add some delay otherwise a click event is sent
        setTimeout((obj) => { obj.isDragging = false }, 200, this)
    }

    onResizeStart = (e) => {
        this.isResizing = true;
    }

    onResizeStop = (e) => {
        // HACK: add some delay otherwise a click event is sent
        setTimeout((obj) => { obj.isResizing = false }, 200, this)
    }

    getClassNames = (k) => {
        if(k === this.state.selected)
        {
            return "selected";
        }
        else {
            return '';
        }
    }

    render() {
        const {rowHeight, ...otherProps} = this.props;
        return (
            <div>
                <ContextMenuTrigger id="some_unique_identifier">
                    <ResponsiveReactGridLayout
                        onDrag={this.onDrag}
                        onDragStart={this.onDragStart}
                        onDragStop={this.onDragStop}
                        onResizeStart={this.onResizeStart}
                        onResizeStop={this.onResizeStop}
                        rowHeight={rowHeight}
                        margin={[0, 0]}
                        breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
                        cols={{lg: 24, md: 24, sm: 24, xs: 24, xxs: 24}}
                        width={this.props.containerWidth}
                        {...otherProps}
                    >
                        {
                            Children.map(this.props.children, child =>
                                React.cloneElement(child, {
                                    className: this.getClassNames(child.key),
                                    onClick: (e, key = child.key) => this.onItemClick(e, key)
                                })
                            )
                            // this.props.children
                        }
                    </ResponsiveReactGridLayout>
                </ContextMenuTrigger>
                <ContextMenu id="some_unique_identifier">
                    <MenuItem data={{foo: 'bar'}} onClick={this.handleClick}>
                        ContextMenu Item 1
                    </MenuItem>
                    <MenuItem data={{foo: 'bar'}} onClick={this.handleClick}>
                        ContextMenu Item 2
                    </MenuItem>
                    <MenuItem divider/>
                    <MenuItem data={{foo: 'bar'}} onClick={this.handleClick}>
                        ContextMenu Item 3
                    </MenuItem>
                </ContextMenu>
            </div>
        );
    }
}

export default Dimensions()(GridLayout);

**Comment by damiangreen** [comment]
So is there no other way than this delay hack yet then?
