### ISSUE TITLE
How to move according to the handle ？

### ISSUE THREAD

**Issue by zhump** [STRML/react-grid-layout#266]
How to move according to the handle ？
like this
http://gaearon.github.io/react-dnd/examples-customize-handles-and-previews.html

**Comment by zhump** [comment]
draggableHandle 
3ks

**Comment by jason-henriksen** [comment]
Please either un-close this or provide a working example.  I've put about 2 hours into making the draggableHandle property do anything and from my point of view it simply does not work.

Here's what I'm doing:  ( All of this is modifications of the examples )

  getDefaultProps() {
    return {
      className: "layout",
      cols: {lg: 12, md: 10, sm: 6, xs: 4, xxs: 2},
      rowHeight: 100,
      isDraggable: true,
      draggableHandle : 'gridItemDragHandle'
    };
  },

  createElement(el) {
    var removeStyle = {
      position: 'absolute',
      right: '2px',
      top: 0,
      cursor: 'pointer'
    };
    var moveStyle = {
      position: 'absolute',
      right: '17px',
      top: 0,
      cursor: 'pointer'
    };
    var i = el.add ? '+' : el.i;
    return (
      <div key={i} _grid={el}>
        {el.add ?
          <span className="add text" onClick={this.onAddItem} title="You can add an item by clicking here, too.">Add +</span>
        : <span className="text">{i}</span>}
        <span className="gridItemDragHandle" style={moveStyle}>[DRAG]</span>

        <span className="remove" style={removeStyle} onClick={this.onRemoveItem.bind(this, i)}>x</span>        
        <TestResizeChart width={this.state.width} height={this.state.height} {...this.props}/>        
      </div>
    );
  },

  onAddItem() {
    /*eslint no-console: 0*/
    console.log('adding', 'n' + this.state.newCounter);
    this.setState({
      // Add a new item. It must have a unique key!
      items: this.state.items.concat({
        i: 'n' + this.state.newCounter,
        x: this.state.items.length * 2 % (this.state.cols || 12),
        y: Infinity, // puts it at the bottom
        w: 2,
        h: 2
        ,
        draggableHandle : 'gridItemDragHandle'

      }),
      // Increment the counter to ensure key is always unique.
      newCounter: this.state.newCounter + 1
    });
  },


And in the css:

.gridItemDragHandle{
  border: solid 1px;
}


Please provide a working example.

**Comment by STRML** [comment]
As the docs state:

> // A selector for the draggable handler

This is a CSS selector. See the [React-Draggable example](https://github.com/mzabriskie/react-draggable#draggable-usage).

**Comment by cbll** [comment]
@STRML 

Can you provide an example with a basic grid layout? I have to say I don't quite get how to add this to a grid with several panels.
