### ISSUE TITLE
Lock Aspect Ratio

### ISSUE THREAD

**Issue by bradennapier** [STRML/react-grid-layout#267]
Is it possible to lock to an aspect ratio?  For example, I always want a grid item to be a 2/1 aspect (two wide for every one high)

**Comment by mrsufgi** [comment]
https://github.com/STRML/react-grid-layout/pull/323 it seems like this PR is waiting for review, I was looking for exactly that, in the meanwhile, you can build the version from source and add those changes and use the build in your project.   

(until it gets merge..)

**Comment by grrseguin** [comment]
Hello,

I propose a new PR to lock aspect ratio of each `gridItem` with differents aspects ratios.

**Comment by NachoJusticia** [comment]
Any update on that?...

**Comment by buggedcom** [comment]
It's now 2020, and the feature set has updated but I'm not seeing any mention of the locked ratio, does the feature exist now?

**Comment by buggedcom** [comment]
Ignore. For those who end up here, one of the libraries that `react-grid-layout` is based on, [`react-resizable`](https://github.com/STRML/react-resizable) has the option `lockAspectRatio` that can be used.

**Comment by AaronPowell96** [comment]
> Ignore. For those who end up here, one of the libraries that `react-grid-layout` is based on, [`react-resizable`](https://github.com/STRML/react-resizable) has the option `lockAspectRatio` that can be used.

How do you pass the lockAspectRatio prop down to the item from rgl?

**Comment by dthunn** [comment]
Anyone figure out how to pass lockAspectRatio prop down?
