### ISSUE TITLE
 Uncaught Error: ResponsiveReactGridLayout: `cols` entry for breakpoint xxs is missing!responsiveUtils.js:34 getColsFromBreakpoint

### ISSUE THREAD

**Issue by TrySpace** [STRML/react-grid-layout#27]
When `cols={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}`  (This is from the example on github)

So when `xxs: 0` then it gives an error:
  Uncaught Error: ResponsiveReactGridLayout: `cols` entry for breakpoint xxs is missing!responsiveUtils.js:34 getColsFromBreakpoint

When I set it to `xxs: 1`, it doesn't

**Comment by STRML** [comment]
Sorry, this is a typo. This attribute should be `breakpoints`, not `cols`: `cols` is a mapping of breakpoint names to column counts. For example:

```
      breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
      cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}
```

I'll clear up the documentation.

**Comment by STRML** [comment]
The typo is fixed, thanks for reporting.
