### ISSUE TITLE
Check for changed breakpoints and cols must not be based on refference

### ISSUE THREAD

**Issue by Niondir** [STRML/react-grid-layout#270]
I got an issue after the update with this change:

> 0.12.3 (May 3, 2016)
> 
> Bugfix: Rendering with new breakpoints/cols does not refresh the layout. Fixes #208 - thanks @damienleroux 

It caused massive calls on `onLayoutChange` because even though the cols and breakpoints did not changed, my inline notation caused them to be recreated.

If fixed this issue by defining the properties as global constant, so the refference equal check inside the grid layout will not fail anymore - but comparing 2 instances with the same value should als pass the check.

It's about this code that need a better equals implementation for the objects that are compared.

```
if (nextProps.width != this.props.width || nextProps.breakpoint !== this.props.breakpoint || nextProps.breakpoints !== this.props.breakpoints || nextProps.cols !== this.props.cols) {
      this.onWidthChange(nextProps);
    }
```

**Comment by damienleroux** [comment]
Hello! What do you mean by "my inline notation" ?
