### ISSUE TITLE
Responsive grid with item's width fixed

### ISSUE THREAD

**Issue by erwingaitano** [STRML/react-grid-layout#272]
Is it possible to keep the items width fixed while the grid is responsive? For example, a grid of 1000px, 4 columns and items of 250px. The moment the grid is below 1000px, the grid should be of 3 columns but items still 250px. instead of 33% width of the grid.

**Comment by STRML** [comment]
At this time that's not possible, but you could emulate it by fixing the container size to intervals based on breakpoints. If you made the actual grid container 750px wide it would work fine.

If you're trying to get them to justify while remaining 250px, you'd have to add your own resize handler adjust the `margin` prop.

**Comment by erwingaitano** [comment]
Ok, I'll give a try to set the grid's container a fixed width. Thanks!
