### ISSUE TITLE
onWidthChange only triggering when breakpoint changes

### ISSUE THREAD

**Issue by Noitidart** [STRML/react-grid-layout#276]
Is this by design? Because I needed the grid width of my responsive grid as it changed width. But `onWidthChange` is only triggering when breakpoint changes. I had to attach me own `window.onresize` event and keep track of width (of course on `componentDidMount` i am getting the initial width).

I get width like this:

    document.querySelector('.react-grid-layout').offsetWidth

So this is my code:
```
var Gallery = React.createClass({
	componentDidMount: function() {
		this.recalcGridWidth();
		window.addEventListener('resize', this.recalcGridWidth, false);
	},
	componentWillUnmount: function() {
		window.removeEventListener('resize', this.recalcGridWidth, false);
	},
	recalcGridWidth: function() {
		this.grid_width = ReactDOM.findDOMNode(this).offsetWidth;
		console.log('this.grid_width:', this.grid_width);
	},
```

**Comment by STRML** [comment]
Use a custom `WidthProvider` and add a callback on width change.

**Comment by Noitidart** [comment]
Ah thanks very much @STRML - I'll research that. Superb component!
