### ISSUE TITLE
margin property is multipled by w/h

### ISSUE THREAD

**Issue by Noitidart** [STRML/react-grid-layout#277]
I am using this for an image gallery. I have set my rowHeight to `1`. And in the layout I set the `h` to the height of the image. However this multiplies the `margin[1]` value by this `h`. Is there any way to make margin not get multipled by the `h`? I notice that `margin[0]` gets multipled by the `w` too.

**Comment by STRML** [comment]
Ah yes, the issue here is that in order for the grid to work, if an item spans multiple rows, it needs to add the vertical height to each row.

For example:

```
+-----+ +-----+
|     | |     |
|     | +-----+
|     |
|     | +-----+
|     | |     |
+-----+ +-----+
```

I would recommend setting the margin to zero and using some padding in your items' container div.

**Comment by Noitidart** [comment]
Absolutely superb thank you so much! I couldn't add the padding on the div element itself (the immediate child) I had to wrap its contents in a div then give this sub-div the padding. Otherwise it was messing up the layout. Please check out the awesomeness here - https://noitidart.github.io/nativeshot-react-grid-layout/demo/demo.htm

Thank you!
