### ISSUE TITLE
breaking change between 0.12.6 and  0.12.7

### ISSUE THREAD

**Issue by eMerzh** [STRML/react-grid-layout#279]
Hi, 
while trying to update my code i got numerous error after the upgrade,

it seems that the  0.12.7 doesn't pass down extra props to the grid items...
which lead to broken app;
is this a bug or a "feature" ?

**Comment by Puffton** [comment]
Perhaps this is the same issue as the one I'm having? https://github.com/STRML/react-grid-layout/issues/275

**Comment by STRML** [comment]
This is a duplicate of #275. Thanks for reporting.
