### ISSUE TITLE
Uncaught Invariant Violation: addComponentAsRefTo(...)

### ISSUE THREAD

**Issue by ptlinyi** [STRML/react-grid-layout#280]
Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

code:

```

var ReactGridLayout = require('react-grid-layout');

var MyFirstGrid = React.createClass({
  render: function() {
    // layout is an array of objects, see the demo for more complete usage
    var layout = [
      {i: 'a', x: 0, y: 0, w: 1, h: 2, static: true},
      {i: 'b', x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4},
      {i: 'c', x: 4, y: 0, w: 1, h: 2}
    ];
    return (
      <ReactGridLayout className="layout" layout={layout} cols={12} rowHeight={30} width={1200}>
        <div key={'a'}>a</div>
        <div key={'b'}>b</div>
        <div key={'c'}>c</div>
      </ReactGridLayout>
    )
  }
});
```

**Comment by ajmajma** [comment]
Bump! Having same issue...

**Comment by STRML** [comment]
This does not reproduce the issue.

Please create a jsfiddle reproducing, otherwise I cannot debug.

**Comment by BLamy** [comment]
@STRML 

I was able to track the error down to [here](https://github.com/STRML/react-resizable/blob/master/lib/Resizable.jsx#L185):


![image](https://cloud.githubusercontent.com/assets/324928/21566955/495f555c-ce76-11e6-9d72-3b767ffa13d7.png)
![image](https://cloud.githubusercontent.com/assets/324928/21567050/124816ca-ce77-11e6-8fde-d1c3d346e892.png)

**Comment by STRML** [comment]
This still doesn't explain what the problem actually is - do you know what causes the error, rather than just what fixes it?

**Comment by BLamy** [comment]
Still looking.

**Comment by STRML** [comment]
Thanks. I'm going to remove that ref anyway, it's not documented or used.

**Comment by BLamy** [comment]
It was my fault. I had multiple versions of react loaded. Reinstalling all my dependencies and it seems to be working. I'll let you know if I run into the issue again but as it stands right now I can't replicate the issue anymore.

**Comment by STRML** [comment]
:+1: No worries - I've removed the ref regardless, but I'm surprised you were able to even get much of anything running with multiple React copies!
