### ISSUE TITLE
Updating layout and cols in ResponsiveReactGridLayout uses old layout

### ISSUE THREAD

**Issue by maxkostow** [STRML/react-grid-layout#281]
It looks like right here https://github.com/STRML/react-grid-layout/blob/master/lib/ResponsiveReactGridLayout.jsx#L138 the new layout is overwritten with the current layout.

What is the purpose of this? Removing it appears to work for my usecase, but maybe there is some larger purpose? It looks like there are no tests (or at least unclear how to run them) so not sure how to validate the change.

Looking at #232 maybe this code should only be triggered when the breakpoints change?

**Comment by STRML** [comment]
The idea is to save all the changes made to the layout so far - it wasn't built for layout specifications to change. The is definitely a deficiency in the API and I need to define it better (and write some tests).

**Comment by maxkostow** [comment]
Changes being from drag/resize, right? Would I be okay to remove that functionality if I don't use those features?

**Comment by STRML** [comment]
Right, it would be fine to remove that. It's really quite bad tbh because I'm modifying incoming props. I need to work on a better mechanism for this.
