### ISSUE TITLE
Custom print styles

### ISSUE THREAD

**Issue by tquetano-r7** [STRML/react-grid-layout#287]
Was wondering if there was a way to customize the styles for `.react-grid-item` elements specific to printing? There are a number of styles that are injected into the component that I want to modify (`position` and `transform`, specifically), and I'm using `@media print { .react-grid-item { /* whatever */ } }` to do it right now, but just curious if we could leverage Radium to do it instead?

**Comment by STRML** [comment]
Using Radium would be a really roundabout way to do print styles. @media
print is just fine.
