### ISSUE TITLE
Question: Would this library support dragging a new grid item into it?

### ISSUE THREAD

**Issue by ajmajma** [STRML/react-grid-layout#288]
Hello,

I am wondering if I have a drag and drop outside of this library if it would be possible to use it. i.e.- I would like to have a menu of sorts where a user can drag off a box (lets say a 1x1) and drag it into the grid area and drop it in, with the grid reacting to the new item. Would something like this be possible? 

Thanks very much!

**Comment by STRML** [comment]
Addressed in #289.
