### ISSUE TITLE
Question: Is it possible to drag an item from outside of RGL into RGL and making it in dragging state?

### ISSUE THREAD

**Issue by varandpez** [STRML/react-grid-layout#289]
I'd like to know if it's possible to drag an item into RGL and make it in dragging state? I mean once the item enters in RGL it becomes an item in layout and be in dragging status at the same time?

**Comment by ajmajma** [comment]
I am looking for the same thing in #288 , would be great to get something like this working with this library!

**Comment by jzumbrun** [comment]
+1

**Comment by ajmajma** [comment]
Bump!

**Comment by STRML** [comment]
No, it's not - if you want such a feature please submit a pull request.

**Comment by rickyhan** [comment]
Did anyone manage to set a GridItem in dragging state?

**Comment by CareyToboo** [comment]
Many people need this feature. But a few years passed without any progress. I also need this feature. ~

**Comment by STRML** [comment]
@CareyToboo it's in the demo.

**Comment by CareyToboo** [comment]
> @CareyToboo it's in the demo.
Thank you for your reply. I made a mistake.  
What I want is nested drag and drop.  Like drag item "into" another item.  Is there such a Demo ? Or give me some  advice. 
Thanks very much!

**Comment by dengpan1** [comment]
+1 
Many people need this feature. But a few years passed without any progress. I also need this feature. ~

**Comment by taziksh** [comment]
@CareyToboo @dengpan1 check out this code sample: https://github.com/react-grid-layout/react-grid-layout/issues/1893
