### ISSUE TITLE
Question: How to access the width and height values of a Grid item

### ISSUE THREAD

**Issue by ucabaur** [STRML/react-grid-layout#291]
Hi , I have a question relating to how i can access grid item width and height information,

So react-grid-layout makes use of react-draggable and react-resizable. The resizable react class has props of width and height passed down from the draggable react class. However I would like these parameters to be fed at the level of the grid item in my app to be able to re-render graphics with the next width and height. 

Current situation; GridItem -> Draggable ->Resizable (props of w. and h.) -> Graph( doesn't have that information so rendered with arbitrary values (w:400 , h:400) 

Desired situation : GridItem(Knows dimmensions of resizable) -> Draggable -> resizable-> Graph (gets width and height as props from the Griditem).

This seems like an anti-pattern  (as in I'm trying to communicate information from a child to a parent, am I missing something? )
Thanks,
A.L.

**Comment by herodhb** [comment]
try refs，ReactDom.findDOMNode(this.refs[xxx]), then width equals to gridItemNode.clientWidth.
i guess0.0

**Comment by nikolas** [comment]
What object is `this.refs` attached to? Can you describe an example in some context?

I have a similar situation. Here's my DOM:
![2016-08-29-114232_646x162_scrot](https://cloud.githubusercontent.com/assets/59292/18067043/1029bcc8-6e09-11e6-8dbb-74b924025d9f.png)

`DraggableCore` and `ReactGridLayout` both have a `dragging` state attribute. How do I feed this attribute into my `TrackItem` via a prop? I'm generating the custom grid items like this:
https://github.com/ccnmtl/juxtapose/blob/master/src/Track.jsx#L15
