### ISSUE TITLE
Overriding onMouseDown

### ISSUE THREAD

**Issue by nikolas** [STRML/react-grid-layout#292]
How do I override onMouseDown for a GridItem?

I have something like this:

```javascript
class TrackItem extends React.Component {
    onMouseDown(e) {
        this.props.onMouseDown.apply(e);
    }
    render() {
        return <div onMouseDown={this.onMouseDown.bind(this)}>item</div>;
    }
}
```

Which yields the error:
react-draggable.js:1050 Uncaught TypeError: Cannot read property 'button' of undefined

**Comment by STRML** [comment]
That's not how Function#apply works. Please check MDN

**Comment by nikolas** [comment]
MDN says the syntax is: `fun.apply(thisArg, [argsArray])`. Since I'm trying to call onMouseDown with the context of the event as `this`, it's correct as far as I can tell.

Should I be doing something else altogether, or what is the correct syntax?

**Comment by STRML** [comment]
No, you just want to pass the event.

`this.props.onMousedown(e);`

**Comment by nikolas** [comment]
Great, thanks!
