### ISSUE TITLE
maxH and maxW being lost

### ISSUE THREAD

**Issue by gusdaud** [STRML/react-grid-layout#294]
Hey,

For some reason when I add a new item with `maxH` and `maxW` those variables are not passed when `onLayoutChange` is called immediately.

Steps to reproduce:
1. Create a `Responsive` grid using `WidthProvider`
2. Initialize `layouts` property with `{"md":[]}`
3. Add a new div child to the grid with its key `some_id` and change grid `layouts` property to: `{md: [{x: 0, y: 0, w: 1, h: 1, maxH: 1, maxW: 4, i: "some_id"}]}`;
4. Listen to `onLayoutChange`, layouts parameter won't include either `MaxH` or `MaxW`, this is what I'm getting: `[{w: 1, h: 1, x: 0, y: 0, i: "some_id", moved: false, static: false}]` 

Any ideas on how to prevent `MaxH` and `MaxW` being lost ?

**Comment by Jabark** [comment]
I'm getting this issue too, with `minH` and `maxH`.

**Comment by Jabark** [comment]
This appears to be happening within `ResponsiveReactGridLayout.js` on line 60:

`_this.props.onLayoutChange(layout, _extends({}, _this.props.layouts, (_extends2 = {}, _extends2[_this.state.breakpoint] = layout, _extends2)));`

`_this.props.layouts` appears to show the correct values, however it's being overwritten with `layout`, however the `layout` supplied has `null` in all the min and max values, and overwrites them.

**Comment by Jabark** [comment]
Following this back in the stack trace now, and `synchronizeLayoutWithChildren` is called from `utils.js`. 

Unfortunately this appears to be relying on the grid layout being supplied on the `data-grid` property on line 405:
```
var g = child.props['data-grid'] || child.props._grid;

// Hey, this item has a data-grid property, use it.
if (g) {
```

This doesn't compute with responsive grid layout:
> For the time being, it is not possible to supply responsive mappings via the data-grid property on individual items, but that is coming soon.
**_README.md_**

When it doesn't find the `data-grid` property, it just adds it to the bottom of the layout with some default properties (i.e. no max or min):
```
else {
   newItem = cloneLayoutItem({ w: 1, h: 1, x: 0, y: bottom(layout), i: child.key || "1" });
```
