### ISSUE TITLE
Warning about Unknown props with React 15.2.1

### ISSUE THREAD

**Issue by KarelHaruda** [STRML/react-grid-layout#297]
React 15.2 introduced new error/warning about unknown props and react-grid-layout report this warning in console.

Warning: Unknown props `minConstraints`, `maxConstraints`, `onResizeStop`, `onResizeStart`, `onResize`, `handleSize`, `lockAspectRatio` on `<div>` tag. Remove these props from the element. For details, see 
https://fb.me/react-unknown-prop

It is not fatal but it is nagging.

**Comment by georgeke** [comment]
similar to https://github.com/STRML/react-grid-layout/issues/290
