### ISSUE TITLE
Using with React 0.14.8, resize not working

### ISSUE THREAD

**Issue by ajmajma** [STRML/react-grid-layout#298]
I am trying to get this working in a project that is using react 0.14.8, I have set the version of react-grid-layout to 0.10.10. This seems to work (no visible errors), however it looks like the resize library is breaking as I can no longer resize the items in the grid. 

It appears the 0.10.10 versions dependency for the resize library is carroted "react-resizable": "^1.2.0" , and the version it is pulling is dependent on react ^15. I am not sure this is causing the issue, but this is my best guess. I am wondering if there is a way to get the resize working with react 0.14.8 (everything else works great). Much appreciated!

**Comment by STRML** [comment]
I'm sorry, but older React versions are not supported. You could work around this by using a shrinkwrap file to pin the resizable dependency.
