### ISSUE TITLE
Resize event is not fired when we drag the browser down or maximize it.

### ISSUE THREAD

**Issue by viky293** [STRML/react-grid-layout#301]
The responsive grid fails to resize when browser window is dragged down or maximized back again. Is it possible to handle this with available functionality?

**Comment by STRML** [comment]
You need to use [WidthProvider](https://github.com/STRML/react-grid-layout/blob/master/lib/components/WidthProvider.jsx) to provide a width to the grid.

**Comment by viky293** [comment]
I am already using it, everything works fine if I manually click and resize the browser, but if I click on the title bar and drag it down from full-screen mode then you get to see the problem. 
Same is when I am not is full-screen mode but I go full-screen by clicking maximize button on the browser window.

**Comment by STRML** [comment]
Sounds like a browser bug. Have you gotten to the bottom of it? Browser/OS
