### ISSUE TITLE
Element remounted when prop 'static' changes

### ISSUE THREAD

**Issue by uneart** [STRML/react-grid-layout#302]
Hi there,

I am toggling the `static` attribute from a button on the element. The new `static` value is saved to the database (Firebase in my case) and gets pulled from there by a listener to the Redux state. 

Normally, changes of the size or position position of the element do not trigger a complete remount. But changing the `static`value triggers a remount every time. So first `componentWillUnmount` and then `componentDidMount` get executed every time. This leads to problems with an external non-react library I am using for connecting the different grid elements with arrows (jsPlumb).

Any idea how to solve this or why the remount is even happening?

**Comment by STRML** [comment]
This is an unfortunate side effect of how Draggable & Resizable work - because they wrap the GridItem, the tree changes if the item is static (no longer wrapped) and the component remounts.

I am hoping to fix this in a new major by exposing `<GridItem>` for direct use.

**Comment by uneart** [comment]
Alright, so I guess for now there is not much I can do against this behaviour.

**Comment by larrydahooster** [comment]
Has anyone figured out a workaround for this? I need to set static on the smallest breakpoint, but I can't afford a remount.  Any idea how I could work around the remounting?
