### ISSUE TITLE
Warning in React 15.3.0 manually calling PropTypes validation function

### ISSUE THREAD

**Issue by wirmar** [STRML/react-grid-layout#303]
Warning: You are manually calling a React.PropTypes validation function for the `maxH` prop on `GridItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

is printed to console 4 times (for minH, maxH, minW and maxW)

**Comment by yxqme** [comment]
The same

**Comment by umutcetinkaya** [comment]
yes. I have in me the same error. 
How to solve ?
