### ISSUE TITLE
onLayoutChange is not triggers if children's changed, whithout changed children's count.

### ISSUE THREAD

**Issue by Strate** [STRML/react-grid-layout#304]
When children of component changed, but count of children isn't, layout is not recalculated.
It happes due to comparison only lengths of `this.props.children` and `nexProps.children`, completely ignoring children's content. Quick example:

``` jsx
render() {
  <ReactGridLayout>
    <div key="1" />
    {this.state.flag ? <div key="2" /> : <div key="3" />}
  </ReactGridLayout>
}
```

If `this.state.flag` changed, layout should be recalculated. But there is no recalculation.

/cc @javacer

**Comment by javacer** [comment]
fix in commit https://github.com/megaplan/react-grid-layout/commit/ab1c37791aac1cbf46b095d096bd12765e40dbd7

**Comment by Strate** [comment]
@STRML seems that that kind of fix is useless. Because on each render `this.props.children` contains a bunch of react elements created by `React.createElement`. That method on each call returns new instance of `ReactElement`, so, `shallowCompare` will return `false` on each `componentWillReceiveProps`, because `shallowCompare` goes to first deep level, and there would be different objects.
I think that more accurate check - is to compare previous/next bunch of children _keys_, instead of children objects.
Please correct me if I'm missed something.

**Comment by STRML** [comment]
You are correct.

Unfortunately comparing React elements for this purpose is very error-prone. Would be nice if we could eliminate more of the state here.

**Comment by STRML** [comment]
ec8816b seem correct to you @Strate?

**Comment by Strate** [comment]
Thanks a lot, I'll test it tomorrow:)
