### ISSUE TITLE
Rename WidthProvider to widthProvider to keep Eslint happy

### ISSUE THREAD

**Issue by ncuillery** [STRML/react-grid-layout#308]
I'm pretty surprised nobody has ever complained about that.
The module `WidthProvider` is a function returning a component, it's not a constructor so it shouldn't be capitalized.

It breaks the `new-cap` Eslint rule http://eslint.org/docs/rules/new-cap (maybe other linters too).

The React community usually follow this rule. Look at redux (`connect`) or the whole [recompose](https://github.com/acdlite/recompose) package.

It's a huge breaking change, maybe we should start by depreciate the capitalized name.

**Comment by STRML** [comment]
Or just disable `new-cap`.

You're also not forced to name it with a capital letter.

```js
const widthProvider = require('react-grid-layout').WidthProvider;
```
