### ISSUE TITLE
moved flag not setting to true when items are moved around

### ISSUE THREAD

**Issue by mcottingham** [STRML/react-grid-layout#309]
I've provided an onLayoutChange handler to my responsive grid layout and it seems that the 'moved' flag is not being set correctly in either the 'currentLayout', or 'allLayouts' params passed to the handler.

**Comment by tomredman** [comment]
Also seeing this -- `layout.moved` is not being set to true on any layouts returned in `onLayoutChange` callback.

**Comment by morgs32** [comment]
yes is that why my changes aren't persisting after a route change and back?

**Comment by stewartduffy** [comment]
Has there been any progress on this recently?

**Comment by kp2006** [comment]
I am facing same issue, where 'moved' flag always remain 'false'. Did anyone find a solution to this?

**Comment by damiangreen** [comment]
Hmm, still a problem

**Comment by damiangreen** [comment]
So on further investigation it apepars the `moved` is only triggered if it has moved a grid unit, rather than a pixel.
IF you want to know at pixel level granularity you can do the following (in Typescript)
```
 private onDrag = (
    _layout: Layout[],
    oldItem: Layout,
    _newItem: Layout,
    _placeholder: Layout,
    e: MouseEvent,
  ) => {
    if (e.movementX !== 0 || e.movementY !== 0) {
      this.props.onWidgetDragging(oldItem.i);
    }
  };
```

**Comment by tomredman** [comment]
lol that's one way to fix a bug.

**Comment by shughes-uk** [comment]
this is still an issue for me

**Comment by zenahirsch** [comment]
Same issue here, `moved` is always false on the layouts passed to the `onLayoutChange` handler. Using version 0.18.3.
