### ISSUE TITLE
Inconsistent dragging when using JSPM

### ISSUE THREAD

**Issue by activelogix** [STRML/react-grid-layout#31]
I've spent an afternoon trying to resolve with no luck, was hoping someone could give some advice.  I'm trying to use JSPM to install react-grid-layout, my basic installation looks like:

    npm init
    npm install jspm
    jspm install react
    jspm install jsx
    jspm install npm:react-grid-layout

At this point I would expect react-grid-layout to work but jspm seems to load the react-resizable dependency incorrectly since it fails to load.  To fix -
    
    jspm install npm:react-resizable

At this point the console is clear, the grid is created with drag/resize functionality but dragging is inconsistent.  The dragging grid item doesn't stay with the mouse and releasing the mouse doesn't "snap" the grid item into the correct position (it floats).  I've tested multiple browsers, manually installing dependencies, compiling JSX > JS, tweaking CSS, etc.

**Comment by activelogix** [comment]
Figured it out... and learned a lot in the process.  The latest release for react-draggable is 0.1.1 from July which no longer works.  I was able to manually install it from the master branch and it's back to working.  Creating a new release of react-draggable should fix this issue for others.

Thanks for all of your work on this project!

**Comment by tuckwat** [comment]
Thanks for creating a new build of react-draggable, looks like that would have fixed the problem but now it can't find the version in your package.json.  

The message is that it can't find the "v0.3.1" release.  Should the **v** below be removed?
```    "react-draggable": "strml/react-draggable#v0.3.1" ```

**Comment by STRML** [comment]
No, the `v` is intentional, that's the tag name. Is it possible that jspm doesn't understand tags in github urls?

**Comment by tuckwat** [comment]
Yep, you're right.  It's a JSPM bug (they interpreted it as a version, '@') and it was fixed.
