### ISSUE TITLE
How to restrict drag event to title bar of GridItem

### ISSUE THREAD

**Issue by NguyenPhiLong** [STRML/react-grid-layout#310]
Dear all,
I'm making a dashboard, that used React Grid Layout.
Currently, when I select vertical bar or another things at gadget, it draged and I can not select what I want to do.
If it's better if I can restrict draggable area (User can drag&drop a GridItemin spcified area, not all of GridItem) .
But I don't know how to do that. 
Kindly help me for this.
Thank you so much.

**Comment by STRML** [comment]
See the draggableHandle prop.
