### ISSUE TITLE
Dragging within nested parents causes unexpected behavior

### ISSUE THREAD

**Issue by nitronick600** [STRML/react-grid-layout#312]
It looks like this is a known issue, per this comment in GridItem.js: 
https://github.com/STRML/react-grid-layout/blob/master/lib/GridItem.jsx#L293

We've been working on a solution locally, but can't seem to get it quite right.  At the moment, we're adding a new deltaX/deltaY to the calcXY function but it's still not quite right.  

If you recall, did you have any idea how this might be fixed?  We'll be happy to test and submit a pull request once we get it figured out.

**Comment by cnavrides** [comment]
#313 addresses this issue

**Comment by nitronick600** [comment]
Thanks @cnavrides you douche
