### ISSUE TITLE
Scroll vs Drag on touch devices

### ISSUE THREAD

**Issue by cheryllaird** [STRML/react-grid-layout#314]
I have come across an issue whereby I am using React Grid Layout on a touch device and as I try to scroll down the page it is dragging the grid items instead.

Is there a way to delay the grid item move, for instance start a drag after a long click / long touch?

![rgl-scroll-issue](https://cloud.githubusercontent.com/assets/5813850/17518741/08d5d808-5e41-11e6-959a-70a0f05bbb43.gif)

**Comment by JaneCoder** [comment]
Hello there. I had this same issue and put in a fix to the dependent library that can control this. 
See [#338](https://github.com/STRML/react-grid-layout/issues/338)
Hope this is helpful. Perhaps the fix will be accepted soon. Till then my team is using my patched version.

**Comment by harit1234** [comment]
i also have a simillar problem

**Comment by shreyas-jadhav** [comment]
> Is there a way to delay the grid item move, for instance start a drag after a long click / long touch?

have you found the way?

**Comment by shreyas-jadhav** [comment]
@cheryllaird have you found any solution for this?
