### ISSUE TITLE
PropType validation warning on GridItem

### ISSUE THREAD

**Issue by awesley** [STRML/react-grid-layout#315]
Hi - it appears that the validation function for minW, maxW, minH, maxH is causing a false positive against React's "Don't Call PropTypes Warning".

The actual warning I see is - 
> Warning: You are manually calling a React.PropTypes validation function for the `minW` prop on `GridItem`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

I believe that this is a false positive because I do not see GridItem.jsx calling PropTypes in the manner described in the fb.me link.  However, I do not understand the differences between the validation in GridItem.jsx versus the example given and as such have not submitted a pull request.

If there is any more information I can provide please do ask.

**Comment by kimsk** [comment]
I think this is fixed in #303 (`0.13.0`).

**Comment by STRML** [comment]
Fixed in f7d53e5ad53ad331b678309aeccc4b3004e436d1
