### ISSUE TITLE
Error while npm installing on windows (10) 

### ISSUE THREAD

**Issue by DrmArg1983** [STRML/react-grid-layout#316]
Hi , this error happends  after i run npm install inside the project folder downloaded from GitHub.  
Here is the npm-debug-log , i'm posting only the last lines because it's soo large.

93653 verbose lifecycle react-grid-layout@0.13.0~prepublish: CWD: C:\React-Grid\react-grid-layout-master
93654 silly lifecycle react-grid-layout@0.13.0~prepublish: Args: [ '/d /s /c', 'make build' ]
93655 silly lifecycle react-grid-layout@0.13.0~prepublish: Returned: code: 1  signal: null
93656 info lifecycle react-grid-layout@0.13.0~prepublish: Failed to exec prepublish script
93657 warn optional Skipping failed optional dependency /chokidar/fsevents:
93658 warn notsup Not compatible with your operating system or architecture: fsevents@1.0.14
93659 verbose stack Error: react-grid-layout@0.13.0 prepublish: `make build`
93659 verbose stack Exit status 1
93659 verbose stack     at EventEmitter.<anonymous> (C:\Users\romu1\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:242:16)
93659 verbose stack     at emitTwo (events.js:106:13)
93659 verbose stack     at EventEmitter.emit (events.js:191:7)
93659 verbose stack     at ChildProcess.<anonymous> (C:\Users\romu1\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
93659 verbose stack     at emitTwo (events.js:106:13)
93659 verbose stack     at ChildProcess.emit (events.js:191:7)
93659 verbose stack     at maybeClose (internal/child_process.js:852:16)
93659 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
93660 verbose pkgid react-grid-layout@0.13.0
93661 verbose cwd C:\React-Grid\react-grid-layout-master
93662 error Windows_NT 10.0.10586
93663 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\romu1\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
93664 error node v6.3.1
93665 error npm  v3.10.5
93666 error code ELIFECYCLE
93667 error react-grid-layout@0.13.0 prepublish: `make build`
93667 error Exit status 1
93668 error Failed at the react-grid-layout@0.13.0 prepublish script 'make build'.
93668 error Make sure you have the latest version of node.js and npm installed.
93668 error If you do, this is most likely a problem with the react-grid-layout package,
93668 error not with npm itself.
93668 error Tell the author that this fails on your system:
93668 error     make build
93668 error You can get information on how to open an issue for this project with:
93668 error     npm bugs react-grid-layout
93668 error Or if that isn't available, you can get their info via:
93668 error     npm owner ls react-grid-layout
93668 error There is likely additional logging output above.
93669 verbose exit [ 1, true ]

**Comment by STRML** [comment]
Please don't install from GitHub, install from npm.

I regret this bug - unfortunately, `prepublish` hooks run on `postinstall`, which [will be fixed someday, really, we mean it this time](https://github.com/npm/npm/issues/10074).
