### ISSUE TITLE
Getting initial columns count with responsive layout

### ISSUE THREAD

**Issue by thomn** [STRML/react-grid-layout#318]
```onBreakpointChange``` and ```onWidthChanged``` aren't called on grid initialization.
Is there another way of getting the current columns count, allowing me to auto-place my items on the grid ?

Thanks !

**Comment by STRML** [comment]
You're providing the width via WidthProvider - would recommend writing your own simple HOC that renders an empty container, measures it, figures out the breakpoint & then places items.
