### ISSUE TITLE
Localstorage demo not working

### ISSUE THREAD

**Issue by wyaeld** [STRML/react-grid-layout#32]
/w Chrome on Ubuntu 14.04

https://strml.github.io/react-grid-layout/examples/7-localstorage.html

All resizing and dragging operations are just causing the item to fly back to its initial state as soon as release the mouse

**Comment by STRML** [comment]
Odd. Do you see anything in your console? Working fine on Mac with Chrome.

**Comment by wyaeld** [comment]
Nope, nothing in console.

Just tried in Chrome on Windows, same problem.  Tried in Incognito mode to
ensure it wasn't a plugin messing with me, but same result.

**Comment by STRML** [comment]
I can replicate in Windows and on OSX Firefox. I'll figure out a fix shortly.

**Comment by wyaeld** [comment]
yep, working for me now too.
