### ISSUE TITLE
The default layouts prop is being modified (ResponsiveGridLayout)

### ISSUE THREAD

**Issue by maksis** [STRML/react-grid-layout#320]
ResponsiveGridLayout modifies the `layouts` prop object directly, which is an issue if one hasn't been provided by the user causing the default `layouts` prop to be used. Since [default props are shared across component instances](https://facebook.github.io/react/docs/component-specs.html#getdefaultprops), this will make all subsequentially mounted responsive layouts to use the same `layouts` object which may cause strange issues.

Tested with version 0.13.1.

**Comment by maksis** [comment]
https://github.com/facebook/react/pull/7449 :tada:

**Comment by STRML** [comment]
That's interesting. Thanks for this report!

**Comment by erik-sn** [comment]
Thank you for posting this, you have resolved several hours of frustrating debugging.

In my particular case I was unmounting a ResponsiveGridLayout, making other state changes, and then remounting it with the layouts saved. However any other subsequent unmount -> other actions -> remount would have the same layout as the first unmounting.
