### ISSUE TITLE
Multiple items Drag

### ISSUE THREAD

**Issue by ruanmer** [STRML/react-grid-layout#322]
Is there a way of drag multiple items at same time?

Ex: http://threedubmedia.com/code/event/drag/demo/multi

**Comment by pauloschilling** [comment]
That would be amazing for when we have a grid with dozens of elements. +1

**Comment by jen0cide** [comment]
+1

**Comment by mymywang** [comment]
+1

**Comment by Eatwhiterabbit** [comment]
+1

**Comment by viktorrudi** [comment]
+2

**Comment by imranparuk** [comment]
+1

**Comment by creatyvtype** [comment]
+1

**Comment by imranparuk** [comment]
+1

**Comment by ysokol** [comment]
+1

**Comment by navidkhalilian** [comment]
+1

**Comment by 17839359913** [comment]
+111111111

**Comment by 17839359913** [comment]
+1

**Comment by caofuchang** [comment]
+1

**Comment by IT-vkt-22** [comment]
+1

**Comment by IvanTulaev** [comment]
There's a workaround.
Create an element with a grid inside.
Move elements from the parent grid into it.
Move the created element to the desired location.
Move the elements into the parent grid.
Delete the auxiliary element.
