### ISSUE TITLE
accept function for maxH, maxW etc.

### ISSUE THREAD

**Issue by eelkeh** [STRML/react-grid-layout#33]
I need something a bit more complex for max dimensions of the resizable items than numbers. In my case the dimensions are not only globally restricted, but also by the current width/height of the item, i.e. an item with width 2 is allowed but only if the height is less than 3. 
To cover these cases a function could be accepted as one of the max/min props, so that the restrictions can be calculated on the fly by checking the passed props (x, y). For now I solved it like this  in ````GridItem.js````, but this bypasses the proptype number validation. 
```` javascript
maxH: function (props, propName, componentName) {
      if (typeof props.maxH !== 'function') {
        var _nr = props.maxH;
        props.maxH = function() { return _nr; };
      }
      React.PropTypes.func.apply(this, arguments);
...
```` 
This works for my particular case but breaks some validation and I'm wondering if this is the right way to solve this. Any suggestions would be nice!

**Comment by STRML** [comment]
I think it makes a lot more sense to do this restriction in the `onResize` handler.

I have added [a new example](https://github.com/STRML/react-grid-layout/blob/master/test/examples/10-dynamic-min-max-wh.jsx) that will only work on `master` as the callback signature has changed. Please let me know your comments.

**Comment by STRML** [comment]
See [this function](https://github.com/STRML/react-grid-layout/blob/master/test/examples/10-dynamic-min-max-wh.jsx#L57) in particular.

**Comment by eelkeh** [comment]
Yes, that would make more sense! Thanks a lot for the example, exactly what I need.

**Comment by STRML** [comment]
Cool. Please let me know if it works for you; if so, I will make a
release with the current changes.

**Comment by eelkeh** [comment]
Works for me, implemented the current master successfully, thanks!

**Comment by STRML** [comment]
Great. The new signatures are in `0.8.0`, just released.
