### ISSUE TITLE
Grid is changing defined layout width and hight

### ISSUE THREAD

**Issue by jonashartwig** [STRML/react-grid-layout#330]
Hi,

I have some issue which I need assistance with. 

I have an empty layout and I want to add a component to the grid. I do it as follows:

```
        currentLayout.lg.push({
            i: widgetCount.toString(),
            h: 2,
            w: 4,
            x: 0,
            y: 0
        });

        currentLayout.md.push({
            i: widgetCount.toString(),
            h: 2,
            w: 4,
            x: 0,
            y: 0
        });

        currentLayout.sm.push({
            i: widgetCount.toString(),
            h: 2,
            w: 2,
            x: 0,
            y: 0
        });
```

after the grid is rerendered the onLayoutChange callback is immediately called with:

```
layout: {
         lg: {
            i: "id",
            h: 1,
            w: 1,
            x: 0,
            y: 0
        }
    }
```

Why does that happen. If I resize my window and get to the md or sm breakpoint the component has correct size. Only for lg i have a problem.

**Comment by stewartduffy** [comment]
Any update on this?

**Comment by jonashartwig** [comment]
@stewartduffy do you have the same problem?

**Comment by STRML** [comment]
Can you check the status of this in 0.13.7?

**Comment by jonashartwig** [comment]
yepp, this seems to work now :)

**Comment by FrederikStenberg** [comment]
Experiencing this exact issue with GridLayout using the newest version
