### ISSUE TITLE
Collapsible items, with auto-collapse

### ISSUE THREAD

**Issue by IanMayo** [STRML/react-grid-layout#331]
If we imagine an executive dashboard using the layout component, it's possible to imagine that some elements can be collapsed to just a title bar (or other compact UI).

Further, if the user reduces the overall panel area, and responsive layout has to happens, some collapsible panels could automatically collapse to conserve space.

@STRML  - have you encountered any react-grid-layout users who have employed the above behaviour, or considered how such an behaviour would be implement?

**Comment by STRML** [comment]
You could do this with responsive layouts, or by having minimize controls call back to the main layout, modifying that layout item's height.
