### ISSUE TITLE
Disable vertical scroll while dragging on mobile

### ISSUE THREAD

**Issue by simonacca** [STRML/react-grid-layout#338]
On mobile (iPad, iOs 10) vertical dragging of grid items does not work due to the tap being interpreted as a vertical scroll of the page.

A possible solution could be to disable vertical scrolling on mobile while interacting with the grid (gridstack.js does this and it seems to solve the issue https://troolee.github.io/gridstack.js/).

**Comment by JaneCoder** [comment]
I have a [fix](https://github.com/JaneCoder/react-draggable) for this in react-draggable. It is awaiting acceptance as a [pull request.](https://github.com/mzabriskie/react-draggable/pull/183) My team is using our version of react-draggable by forking this project and pointing to it in package.json.

**Comment by derwaldgeist** [comment]
Has this pull request been merged into the code? The samples still show this behaviour on iOS. This would be a show-stopper for me.
