### ISSUE TITLE
RowHeight gets 10 additional pixels for more than one row

### ISSUE THREAD

**Issue by MarciD** [STRML/react-grid-layout#339]
I setup rowHeight: 40 and have an item which has (height) h: 1, everything is fine -> my item has a height of 40px...

if i set the height for this item to h: 2 -> it still uses RowHeight but puts 10px on top so my item has now a height of 90px.

its happening for each extra row except for the first one...
I mentioned the same behavior at the demos...

Is this an issue or does it belong to some logic?

Cheers, MarciD

**Comment by STRML** [comment]
Yeah, that's margin.
