### ISSUE TITLE
accessibility - tile highlighting/tabbing

### ISSUE THREAD

**Issue by tthamel** [STRML/react-grid-layout#340]
Hey so is there any core index of tile order i can access to tab through tiles in the order they are rendered and not the order of the DOM?  currently the dom renders off ID order but the grid layout might not match that leading to un-sequential tab highlighting among tiles

**Comment by STRML** [comment]
There is not - actually calculating this order would be possible by
reading the layout and iterating through each item. You could then set
`tabindex` on the individual divs.

**Comment by tthamel** [comment]
ok sweet, for what its worth this works perfectly : 

 x.items.sort(function (a, b) {
                if(a.gridStuff.y > b.gridStuff.y) {
                  return 1;
                } else if(a.gridStuff.y < b.gridStuff.y) {
                  return -1;
                } else {
                  if(a.gridStuff.x > b.gridStuff.x) {
                    return 1;
                  } else if(a.gridStuff.x < b.gridStuff.x) {
                    return -1;
                  } else {
                    return 0; // or do something
                  }
                }
              })
              return x;
