### ISSUE TITLE
Detect that the grid has changed in size

### ISSUE THREAD

**Issue by tiagocedrim** [STRML/react-grid-layout#348]
Hello everybody,

I have a chart that when I change the grid size , the size chart does not change.

How can I detect that the grid size changed? Detecting this, I can give a resize the chart .
# Current behavior

<img src="https://monosnap.com/file/Mvt872u1q2585BC8GpNK775rAZgZrj.png">
<img src="https://monosnap.com/file/UtLCV2Rxs0nk1KbAiw12BXI322Xotm.png">
# Expected behavior

<img src="https://monosnap.com/file/wHe3o6e5KzwPB7DrlMjddJ88frRc7n.png">

**Comment by cp** [comment]
The way I have solved this is by specifically keeping the `w` and `h` attributes of my grid items in state, then passing them down as props to whatever component actually renders the chart. That way, when the attributes change the chart component gets rerendered.

**Comment by t00f** [comment]
@cp looks like a good way to track the size and re-render the graph when necessary. `w` and `h` represent row and column size of the grid item. Any idea how it could be converted to pixels ?

**Comment by ns04stars** [comment]
@cp can you share an example, I am facing the same issue?

**Comment by STRML** [comment]
See also e.g. https://github.com/nrako/react-component-resizable which can help with this.

[This is a sensor](https://gist.github.com/STRML/437d90cc790c298817f3261e14088d5c) I use in another project. Have yet to clean it up & release it as a separate lib yet.

**Comment by mauron85** [comment]
I think GridItem component should pass calculated dimensions and dragging/resizing status to wrapped component as I'm suggesting in https://github.com/STRML/react-grid-layout/issues/506
