### ISSUE TITLE
Transform Scale Messes Up Dragging

### ISSUE THREAD

**Issue by turnerniles** [STRML/react-grid-layout#350]
I'm trying to add zooming functionality to my react-grid-layout using css transform scale. The zooming works but the dragging functionality gets messed up and you need to drag a lot to move an element. You can test this by adding `transform: scale(2);` to your react-grid-layout component.

I'm trying to implement the solution found here:
http://stackoverflow.com/questions/15467122/how-to-get-the-correct-mouse-position-in-relation-to-a-div-that-has-has-a-scale
http://jsfiddle.net/YzLHc/1/

Any help on how I can implement this in the react-grid-layout onDrag callback would be appreciated.

_onDrag(layout, oldItem, newItem, placeholder, e, element){

}

**Comment by turnerniles** [comment]
Here is what I have so far:

`	_onDrag(layout, oldItem, newItem, placeholder, e, element){

		const {zoom} = this.props;
		const gridItemCoords = element.style.getPropertyValue('transform').match(/[0-9]+/g);

		newItem.x = newItem.x/zoom;
		newItem.y = newItem.y/zoom;

		element.style.webkitTransform = `translate3d(${gridItemCoords[0]/zoom}px,${gridItemCoords[1]/zoom}px,0)`;
		element.style.MozTransform = `translate3d(${gridItemCoords[0]/zoom}px,${gridItemCoords[1]/zoom}px,0)`;
		element.style.msTransform = `translate3d(${gridItemCoords[0]/zoom}px,${gridItemCoords[1]/zoom}px,0)`;
		element.style.OTransform = `translate3d(${gridItemCoords[0]/zoom}px,${gridItemCoords[1]/zoom}px,0)`;
		element.style.transform = `translate3d(${gridItemCoords[0]/zoom}px,${gridItemCoords[1]/zoom}px,0)`;
	}`

This makes the animation of the dragging on the element and placeholder while zoomed in the right place and smooth. However, on initial click down the element will jump up the left and the final positioning will by off by the distance of the jump. Any ideas on how to fix it? I'm not sure why it is jumping up to the left on initial click while zoomed in.

**Comment by noahprince22** [comment]
@turnerniles Did you ever figure out how to fix this?
