### ISSUE TITLE
Basic usage questions

### ISSUE THREAD

**Issue by coriolanweihrauch** [STRML/react-grid-layout#351]
Hi,

This grid layout looks exactly like what I need, but not having experience with react or node I'm struggling a bit to get started... I'm trying to generate a .js file to use a script tag in a browser. This is what I did (following https://www.sitepoint.com/getting-started-browserify/0)

If someone could point me in the direction of what I'm missing, that would be great :)

I'm running this on a debian jessie machine.

- created a directory for my project
- created a index.js file with the first usage/example code:
```
var ReactGridLayout = require('react-grid-layout');

var MyFirstGrid = React.createClass({
  render: function() {
    // layout is an array of objects, see the demo for more complete usage
    var layout = [
      {i: 'a', x: 0, y: 0, w: 1, h: 2, static: true},
      {i: 'b', x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4},
      {i: 'c', x: 4, y: 0, w: 1, h: 2}
    ];
    return (
      <ReactGridLayout className="layout" layout={layout} cols={12} rowHeight={30} width={1200}>
        <div key={'a'}>a</div>
        <div key={'b'}>b</div>
        <div key={'c'}>c</div>
      </ReactGridLayout>
    )
  }
});
```
- created a package.json file containing
```
{
  "name": "mygrid",
  "main": "index.js",
  "browserify": {"transform": ["reactify"]},
  "scripts": {
    "build-js": "browserify index.js -o build/mygrid.js -d"
  },
  "dependencies": {
  	"react-grid-layout": "^0.13.0"
  }
}
```
- installed node, npm and browserify
- ran `npm install reactify`
- ran `npm install react-grid-layout`
- ran `npm run build-js`
- created an index.htm file in the build directory

```
<html>
	<head><title>MyGrid test</title></head>
	<body>
	<script src="mygrid.js"></script>
	</body>
</html>
```

My browser complained
ReferenceError: React is not defined

so I added 
`var React = require('react');`
below
`var ReactGridLayout = require('react-grid-layout');`
in index.js
and re-ran 
`npm run build-js`

Now I just get a blank window and nothing in the console
(except "Download the React DevTools for a better development experience: https://fb.me/react-devtools")

What am I missing to display the grid ?

**Comment by cp** [comment]
You're almost there. You created a `MyFirstGrid` component, which is great. Next you'll need to use `ReactDOM` to tell React exactly where to render that component into the dom. There's some more documentation on this here: https://facebook.github.io/react/blog/2015/10/01/react-render-and-top-level-api.html.

Don't forget to install `react-dom` separately.

**Comment by coriolanweihrauch** [comment]
Awesome - thank you @cp !
