### ISSUE TITLE
Quick question on local storage

### ISSUE THREAD

**Issue by AvaKathrynShaw** [STRML/react-grid-layout#352]
I'm new to react and I tried to recreate your examples from scratch (i.e not copy and pasting the examples but going off your documentation) and I've been able to do each one except the local storage. Is your other package 'react-localstorage' necessary for this? I noticed this line: 
```javascript
var PureRenderMixin = require('react/lib/ReactComponentWithPureRenderMixin');
```
in your example code and am assuming it is from this package, is this correct? Thanks!

**Comment by STRML** [comment]
PureRenderMixin is from React, as you can see in the import name. 

LocalStorage does depend on `react-localstorage`, or you can synchronize the state with `window.localStorage` yourself.

**Comment by AvaKathrynShaw** [comment]
@STRML Thanks for the quick response! My mistake, got it working now!
