### ISSUE TITLE
onResize item callbacks not supplying "element" argument

### ISSUE THREAD

**Issue by gewl** [STRML/react-grid-layout#354]
Hi! I'm fairly new to this, so it might be a problem on my end, but I've been working off a slightly-adapted version of the [Dynamic Add/Remove example](https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html), and I've been having trouble with the Resize callbacks.

I want my grid items to have a different background color depending on which column they're in. I've been accomplishing this by assigning classes on create and onDragStop, as you can see below: 
![screen shot 2016-09-24 at 12 14 11 pm](https://cloud.githubusercontent.com/assets/19766136/18809691/bc8e54c8-8250-11e6-8924-695fcdec3c6e.png)
![screen shot 2016-09-24 at 12 14 05 pm](https://cloud.githubusercontent.com/assets/19766136/18809693/cff04b20-8250-11e6-8d50-dc27329e5676.png)

However, every time I start to resize them, their class returns to what it was when they were created. If I drag them again, it responsively updates to reflect the column—if I resize them, it always returns to the original class.

I thought I could get around this by dynamically reassigning the class to the element on resize events too, but no element is supplied to the Resize functions—the console logs I posted above output:
![screen shot 2016-09-24 at 12 21 17 pm](https://cloud.githubusercontent.com/assets/19766136/18809698/3664f1e4-8251-11e6-9ba1-c89f59492543.png)

Is this intended? What's the preferred way to responsively update grid-item classes?

**Comment by STRML** [comment]
You shouldn't ever modify the elements themselves, this is antithetical to how React works. Once React runs another render pass, those changes will be lost.

Instead, listen to `onLayoutChange` and modify the classnames by updating component local state.

**Comment by STRML** [comment]
There is indeed a bug in the resize callback and I will fix that shortly.

**Comment by gewl** [comment]
Oh, great, thank you!

Not sure if this is the right place for this, but—as I said, very new to react, just started learning it yesterday morning. If I'm not supposed to manipulate the DOM directly, but shouldn't be putting anything unrelated to coordinates into layout (apropos of the creator's comments [here](https://github.com/STRML/react-grid-layout/issues/164)), how should I be manipulating the states on individual cells? I tried:
![screen shot 2016-09-24 at 1 40 00 pm](https://cloud.githubusercontent.com/assets/19766136/18810137/3b744828-825c-11e6-8663-26001a91d533.png)

Unfortunately, that doesn't seem to be having any effect.

**Comment by STRML** [comment]
The callback is fixed in 0.13.6.
