### ISSUE TITLE
React-router navbar causes issue when dragging elements.

### ISSUE THREAD

**Issue by FerusAndBeyond** [STRML/react-grid-layout#355]
I have a navbar with react-router and as a sub-route I tried to use react-grid-layout but there is one issue where when I click to drag an element the element will jump down, in the exact length of the height of the navbar. Any Idea why?

**Comment by STRML** [comment]
This sounds like a specific styling issue with react-router's navbar, not with this component. Without a working example I can't even begin to help you.

**Comment by FerusAndBeyond** [comment]
Was able to get around it, not by fixing the issue, but just rebuilding some stuff, i'll close.
