### ISSUE TITLE
onLayoutChange second param is messed up

### ISSUE THREAD

**Issue by DaveGee** [STRML/react-grid-layout#359]
Hello,

I just passed some good time debugging why my dashboard wasn't behaving well when resizing my windows and hitting breakpoints. I had widgets staying on screen (instead of disappearing) and vice-versa

I found out that we were using the second parameter of `onLayoutChange` for the component `ResponsiveReactGridLayout` too blindly : the parameter is indeed our layouts, but the keys/values are messed up.

I also found out you may have seen this bug in version [0.10.11](https://github.com/STRML/react-grid-layout/blob/cc8b405db25ad9857430f512fd7dbe15bb7ed0d1/CHANGELOG.md#01011) and 0.11 
I'm using 0.13.6 (previously 0.13.3) and apparently it's come back, or was never fixed

Below is a screenshot of some tests I did. You can see the `onLayoutChange` clearly messes up the layouts as it changed between the `render` and the call of the function. (yes we were updating some state with this second parameter...)

![screenshot at sep 30 14-16-08](https://cloud.githubusercontent.com/assets/1523011/18991749/af5368ec-871a-11e6-961c-699fb9da94ee.png)

Awesome work btw. Thanks.
Cheers

**Comment by STRML** [comment]
Could you give me more for a reproduction? Depending on what you're doing with the callback data in the interim, this may not be a bug.

**Comment by DaveGee** [comment]
To reproduce, check the second parameter of `onLayoutChange` when you're resizing the window and hitting breakpoints. Depending on how you configured your layouts, you should have "random" results appearing.
In my case : I have more widgets on big screens than small => **when I scale down the window, some widgets should disappear when hitting breakpoints**. Instead, they were still present in the second parameter with a height of 1 (e.g. that's the case of the screenshot above)

We where updating blindly our layouts with this second param, rendering the grid again with this `layouts` param through the state.
The goal was to save the layouts to the user profile after a layout change => now we check first that we're in editing mode before using this param.

If you still can't reproduce tell me I will try to find some time doing more tests.

**Comment by STRML** [comment]
Yes, the point is that I don't have enough about how your layout is constructed to reproduce this. Could you post some minimal code?

**Comment by STRML** [comment]
@DaveGee I have created an online example page you can edit to demonstrate this, if you are still interested in addressing this bug.

http://www.webpackbin.com/VymTE3zWG

**Comment by DaveGee** [comment]
Sorry I didn't have much time to investigate more. 
I tried to reproduce my problem in your example:
3 different widget configuration (3 widgets for `lg`, 2 for `md`, 1 for `sm`)

There's a `console.log` at `layoutChange`. You can see how the `layouts` argument behave when you resize the window (look at the number of widgets for `md` for instance)

![image](https://cloud.githubusercontent.com/assets/1523011/20433307/43736460-ada3-11e6-975d-f3ac812a4542.png)

Maybe I'm using this wrong, but if you update your state blindly on layout change, then you have unexpected, random behaviour..

**Comment by DaveGee** [comment]
I think I understood something: did you intend to support having different number and type of widget for each breakpoint ? or was it never a feature ?

I am working on our implementation right now and it seems the previous developer made it so we can have different number of widgets at each breakpoint. This is maybe why `layoutChange` is returning the wrong number of widget : when you reach the breakpoint, it returns all the widget it knows, and not only those that are configured for this particular breakpoint layout.

(not sure I'm perfectly clear here)

If I'm correct that leaves me with two question :
- What's *your* way of supporting different widgets/layout ? (if supported..)
- How can I know in which breakpoint I am if I want to support it myself ? (I need an `initial callback` to know what is the current breakpoint)

**Comment by joeferraro** [comment]
@DaveGee seeing the same. I was blindly taking the second argument `layouts` and updating my database which broke my responsive layouts.
