### ISSUE TITLE
Build for usage in a script tag

### ISSUE THREAD

**Issue by ivo-** [STRML/react-grid-layout#36]
It would be nice to have build for usage in a script tag. (export to a global variable)

**Comment by STRML** [comment]
I could post a dist build that stubs the React dependency, but still includes the React-Draggable and React-Resizable dependencies, as well as the other utilities. However, if you still have those in your project, they will be duplicated.

I highly recommend using a module loader like Browserify or Webpack in your project.

**Comment by NSinopoli** [comment]
+1 for dist build.

**Comment by STRML** [comment]
What kind of dist build would you be looking for? RGL + deps, excluding React?

**Comment by NSinopoli** [comment]
That would be perfect! Thanks so much!

**Comment by STRML** [comment]
See https://github.com/STRML/react-grid-layout/blob/master/dist/react-grid-layout.min.js, which comes with a source map for dev usage. Hope that works for you!

**Comment by NSinopoli** [comment]
Thank you _so_, so much. :+1:

**Comment by ivo-** [comment]
Thank you! This is useful for compile-to-js languages like ClojureScript. :+1:
