### ISSUE TITLE
Server side render workaround help

### ISSUE THREAD

**Issue by mrsufgi** [STRML/react-grid-layout#361]
Hey, I've been trying to work around the problem of "no viewport width available on server" so I decided to try rendering all layouts on the server and let css media queries to decide which one to show on initial render. 
Then, remove all the unnecessary markup (after we've got the actual height). 

I've trying forcing my grid to render a specific breakpoint using 'breakpoint' prop, but it seems like it will always use this prop, how can I restore the original behaviour ?

In addition, In order to properly solve SSR for good, we will probably have to use css media queries to determine which layout to use on initial render and do a cleanup when the client js kick in.

**Comment by STRML** [comment]
@mrsufgi: This is a complex problem and one that won't be solved completely until I integrate something like JSS / styled-components so we can just output CSS for all breakpoints at all times (or at least when `process.browser === false`).

Re: rendering a specific breakpoint, do something like this:

```jsx
<ResponsiveReactGridLayout
  ...
  breakpoint={process.browser ? null : SERVER_BREAKPOINT}
  />
```

**Comment by mrsufgi** [comment]
@STRML exactly, by mentioning JSS / styled components you meant something like Radium or Aphrodite? I guess going that way will actually solve SSR for good. 

Thank you for your help! I'll try that soon.
