### ISSUE TITLE
Can I use reac-grid-layout inside flex ?

### ISSUE THREAD

**Issue by pcompassion** [STRML/react-grid-layout#364]
I draw calendar with flex, and wonder if I can use react-grid-layout to layout the items inside each date rectangle in the calendar.

**Comment by STRML** [comment]
I wouldn't recommend this, unless you have a need to rearrange said items. But RGL has its own layout scheme, which uses fluid widths but does not have the same flex features (like flex-grow, flex-shrink, flex-basis).
