### ISSUE TITLE
data-grid prop written to dom as `[Object object]`

### ISSUE THREAD

**Issue by cp** [STRML/react-grid-layout#366]
I'm specifying the positioning and dimensions of my grid items via the `data-grid` prop. Functionally this works perfectly, but it looks bad when written to the DOM because it's in the form of an object. Since it's only read by RGL, does this even need to be rendered to the DOM or can it be stripped out before?

![image](https://cloud.githubusercontent.com/assets/1715618/19291529/a3c6e996-8fca-11e6-896e-b836cae2aa73.png)

**Comment by STRML** [comment]
This is actually why we switched to `data-grid` - because the old prop, `_grid`, would also get written to the child & we'd get a warning as of React 15.2.

This will be corrected as part of RGL v2 (#346) when I rework `<GridItem>`, but I don't plan to change it before then.

Thanks for the ticket.
