### ISSUE TITLE
grid-item classes /layouting not being rendered

### ISSUE THREAD

**Issue by Falieson** [STRML/react-grid-layout#367]
We're looking forward to getting RGL into production! But, setting it up for the first time I'm having some hangups, and hunting down the issue as far as I can I'm guessing I'm causing some issue. Hopefully you can point me to where it is. The symptom seems to be that "grid-item" className isn't being appropriately added to each of the GridItems. Checking my compiled CSS react-grid-* css files are being loaded. The result (I'm assuming grid-item missing is the symptom causing this) is that all of the items are stacking vertically, succumbing to the 100% width of the of the 'status-item-window' class - removing the 100% property doesn't fix anything (as I expected it wouldn't).

Ok - I hope this is enough to get some help!
 
--------

We have an xml feed that tells the "Status Block" what to render inside, which is StatusItems components. I'm defining some default width and height while figuring out RGL (more about my custom RGL stuff at the end of the post).
```js
   render() {
    const {
      config, title, id,
    } = this.props;
    let data = config.statuses; 

    const RGLpositions = new RGLposition();
    let content = [];
    function renderContent(obj) {
      const key = id + '_' + obj.title;
      const position = RGLpositions.get(key);
      const properties = {
        key: key,
        'data-grid': position,
        title: obj.title,
        value: obj.value,
        range: obj.range,
        theme: obj.theme,
      };

      console.log(`${obj.title}`, position);
      return (
        <StatusItemDashboardWidget {...properties} />
      );
    }
    data = _.sortBy(data, ['order']); // status ITEM order
    _.each(data, (item)=> {
      content.push(renderContent(item));
    });

    return (
      <div>
        <h2 className='h2-LandingPage' >{title}</h2>
        <Grid {...rglConfig}>
          {content}
        </Grid>
      </div>
    );
  }
```

Using React-debugger in chrome tools the output is below. Notice that there isn't a grid-item class being rendered on the GridItems
```html
<div class="react-grid-layout layout" style="height: 170px;">
  <GridItem key='.$...' containerWidth=925 cols=12 margin=[10, 10]...>
    <StatusItemDashboardWidget key='...' data-grid={x: 0, y: 0, w: 2, h: 4} title="..." value=0>
      <div className='status-item-window status-item-approved-border'> // here is where I would expect 'grid-item' className
        ...
      </div>
    </StatusItemDashboardWidget>
  </GridItem>
  <GridItem key='.$...' containerWidth=925 cols=12 margin=[10, 10]...>
    <StatusItemDashboardWidget key='...' data-grid={x: 2, y: 0, w: 2, h: 4} title="..." value=0>
      <div className='status-item-window  status-item-pending-border'> // here is where I would expect 'grid-item' className
        ...
      </div>
    </StatusItemDashboardWidget>
  </GridItem>
  ...
</div>
```

While testing RGL seemed easiest to build a little class that will change data-grid X based on the value. an improvement to this would check if X>12 and increment Y, then reset X, etc. hopefully you get the point.
```js
export function RGLposition() {
  // cid is the componentId
  this.layout = {};
  this.layoutKeys = [];
  this.layoutLength = 0;

  let {layout, layoutKeys, layoutLength} = this;

  this.get = function(cid) {
    if (layout[cid]) return layout[cid];

    layoutKeys = Object.keys(layout);
    layoutLength = Object.keys(layout).length;
    const lastLayoutIndex = layoutLength - 1;
    const lastLayout = layoutLength > 0 ? layout[layoutKeys[lastLayoutIndex]] : false;

    const defaultSize = {w: 2, h: 4}; // 200px x 120px

    if (lastLayout) {
      layout[cid] = {
        x: lastLayout.x +  defaultSize.w, y: lastLayout.y,
        w: defaultSize.w, h: defaultSize.h,
        // static: true,
        // dex: layoutLength++,
      };
    } else {
      layout[cid] = {
        x: 0, y: 0,
        w: defaultSize.w, h: defaultSize.h,
        // static: true,
        // dex: 0,
      };
    }

    return layout[cid];
  };
}

export const rglConfig = {
  className: 'layout',
  cols: 12,
  rowHeight: 30,
  width: 1200,
};
```

**Comment by STRML** [comment]
Make sure your child can accept a style and className prop.

**Comment by Falieson** [comment]
Thank you! just added it as propType and updated the 'window' container to
```
      <div className={ `ht-StatusItem-window ${theme}-border ${className}` } style={style}>
```

**Comment by mnemanja** [comment]
@STRML 
Could you please instruct me on how to "allow" my child component to take in the style and className prop?

**Comment by ashkank83** [comment]
Just as a hint for others: If you're trying to add your react components to be direct children of <ReactGridLayout> and it doesn't work make sure you add something like: 
className={this.props.className} style={this.props.style} on your parent html tag. This is how I got it work.
