### ISSUE TITLE
sortLayoutItemsByRowCol returning different results in Edge/IE 11-10

### ISSUE THREAD

**Issue by guntherjh** [STRML/react-grid-layout#369]
Hello,
First off, I'd like to say thanks for creating such a great library! It really has been quite fun to work with!

I noticed that I was getting inconsistent ordering of layout items across browsers, particularly in Edge/IE (11-10) vs Chrome/Firefox. After a couple of hours of debugging, I think I tracked down where the discrepancy is happening. It looks like the callback passed to sort() in [sortLayoutItemsByRowCol](https://github.com/STRML/react-grid-layout/blob/master/lib/utils.js#L339)() is returning different results based on browser. I recreated the problem here:

[https://codepen.io/guntherjh/pen/qaKLNY](https://codepen.io/guntherjh/pen/qaKLNY)

If you open the pen in Chrome vs Edge/IE 11-10, you'll see that the resulting array contains items in different order depending on browser. 

Once again, thanks for all your hard work in creating a such a great library and please let me know if you need any further details from me.

**Comment by STRML** [comment]
Very interesting! I believe the issue is the lack of an equality case.

This adjustment appears to produce consistent results:

https://codepen.io/anon/pen/bwKOJB

**Comment by STRML** [comment]
I can confirm this fixes the issue in IE10. Do you have other VMs or machines handy so you could check in IE11/Edge?

**Comment by guntherjh** [comment]
I am actually on a Windows machine. I confirmed your modification fixes the issue in Edge and IE 11. Thanks for the quick response!

**Comment by STRML** [comment]
Great. I'll merge it in.

**Comment by guntherjh** [comment]
Awesome! Thanks again for your help!
