### ISSUE TITLE
column widths don't automatically adjust when scrollbar (dis)appears

### ISSUE THREAD

**Issue by xanthousphoenix** [STRML/react-grid-layout#37]
Pretty much what the issue title is. Playing around with your demos, I noticed that when the scrollbar appears or disappears, the items don't autoadjust their size.

To repro what I'm talking about, open your basic demo and move things into the first column until the scrollbar appears (assuming you don't have it already). You should get an effect like this: 
![screenshot from 2015-03-16 14 15 20](https://cloud.githubusercontent.com/assets/4483846/6676668/ebf72fe0-cbe6-11e4-95f2-93c8d8c6cce5.png)
If you then resize the window manually, they autoadjust the width and the effect goes away. If you then make the scrollbar disappear by moving things out of the first column, the reverse effect happens: 
![screenshot from 2015-03-16 14 19 24](https://cloud.githubusercontent.com/assets/4483846/6676753/787ce2c0-cbe7-11e4-93b2-d9ad8fb985ad.png)
For reference, this is what it should look like:
![screenshot from 2015-03-16 14 18 51](https://cloud.githubusercontent.com/assets/4483846/6676736/664838f2-cbe7-11e4-877e-4123348c97f3.png)

**Comment by STRML** [comment]
Yes, this is true - I'd like to avoid polling `scrollWidth` on every move because it causes a layout, but I am not sure how else to detect the scrollbar.

**Comment by STRML** [comment]
Going to prioritize this; the `<WidthProvider>` HOC should use [ResizeSensor](https://github.com/marcj/css-element-queries/blob/master/src/ResizeSensor.js) which would detect this.

Could be fixed easily in userland with a custom width-listening HOC.

**Comment by codepunkt** [comment]
@STRML i want this fixed badly and i'm going to help with it.

From a first look, ResizeSensor seems rather convoluted. I've built my own solution first which fit the bill perfectly, but then realized i'd rather go with something i don't need to maintain, which i found in [react-resize-aware](https://github.com/FezVrasta/react-resize-aware).

Trying to get a PR ready.

**Comment by buzz** [comment]
Any news on this?
