### ISSUE TITLE
Zoomable

### ISSUE THREAD

**Issue by dovy** [STRML/react-grid-layout#370]
It would be awesome if this were zoomable for complex layouts.

http://jrowny.github.io/react-absolute-grid/demo/  has a feature like that. I think it would be really cool.

**Comment by STRML** [comment]
That's a nice feature, but no, I don't have any plans to implement this. Doing so would probably only work well using transform:scale, but this could have issues with text children and any positioning within the item. We support any kind of child so it's not so simple.
