### ISSUE TITLE
maxRows help needed

### ISSUE THREAD

**Issue by vpezeshkian** [STRML/react-grid-layout#372]
I'm trying to take advantage of `maxRows` property, but pushing out of the boundaries is issue for me. I tried to prevent it in `onDragStop` but it seems it's too late as `moveElement`  has already produced a new `layout`, which is passed to the callback.

Any suggestion on how to prevent pushing out of the boundaries?

Thanks.

**Comment by vpezeshkian** [comment]
Anything would be helpful...

**Comment by STRML** [comment]
There is not yet a solution for this, and I haven't had the time to add it. I would suggest taking a look inside the code; if you have a clean solution please consider opening a PR.
