### ISSUE TITLE
can a widge overlap another?

### ISSUE THREAD

**Issue by francisliyy** [STRML/react-grid-layout#373]
can i put a widget float or abusolue position on a specific place?

**Comment by STRML** [comment]
No, this is not supported - sorry!

**Comment by francisliyy** [comment]
Thanks a lot. Would you give me some advice about which will be the main problem if i want to fulfil this.

**Comment by nwlieb** [comment]
@STRML would you accept a pull request to add this feature (under a boolean prop)?
