### ISSUE TITLE
React warnings with 15.3.2

### ISSUE THREAD

**Issue by vijayst** [STRML/react-grid-layout#374]
I am getting react warnings after upgrading react to 15.3.2.
![screen shot 2016-10-14 at 7 31 36 pm](https://cloud.githubusercontent.com/assets/3457565/19390303/1f97a354-9245-11e6-9d34-9d73b6f30f74.png)

It is related to GridItem PropTypes. [React warning info](https://facebook.github.io/react/warnings/dont-call-proptypes.html)

**Comment by STRML** [comment]
This was fixed in 0.13.1.
