### ISSUE TITLE
How can I add maximum width to WidthProvider ?

### ISSUE THREAD

**Issue by iocat** [STRML/react-grid-layout#375]
I'm using nested ReactResponsiveGrid with width provided by the WidthProvider. When my app is rendered on a big desktop screen, it spans the entire screen. I don't know how to limit the root grid's width. Thank you for your help !

**Comment by STRML** [comment]
Read the source for widthprovider and use your own wrapper.

**Comment by iocat** [comment]
Thanks for pointing me to the right direction. 🙃 Much appreciate.
