### ISSUE TITLE
add support for fullscreenchange event to WidthProvider ?

### ISSUE THREAD

**Issue by iocat** [STRML/react-grid-layout#376]
App doesn't auto-resize when I changed the browser to fullscreen mode. It also doesn't resize when I switch the browser back to the normal mode. So it would be nice if the WidthProvider also listens to window's "fullscreenchange" event. I don't know if this is the intention of the library or not. I hope I didn't ask for too many things.

**Comment by STRML** [comment]
Yes, this is why I suggest to simply write your own if you need more
functionality. Watching the window's width and dealing with browser quirks
is not the domain of this module.

**Comment by iocat** [comment]
Oh. Okay, thank you very much! Now I see the WidthProvider becomes my real business now.
