### ISSUE TITLE
Margin between items

### ISSUE THREAD

**Issue by SergeyShablenko** [STRML/react-grid-layout#378]
How can i manage margin between grid items? I need to remove any margin between them, is it possible?

**Comment by jomasti** [comment]
Take a look at the [grid layout props](https://github.com/STRML/react-grid-layout#grid-layout-props) for a margin prop.

**Comment by babycannotsay** [comment]
@STRML  hello, grid layout props' margin set all gridItem.  I don't think the second floor solved the problem of the author. I have the same question.

**Comment by erahm** [comment]
It doesn't solve the OP's issue. RGL calculating absolute positions seems to make adding margin or padding to a single element almost impossible currently.
