### ISSUE TITLE
Changing isDraggable and isResizable reloads the children

### ISSUE THREAD

**Issue by karteek-gamooga** [STRML/react-grid-layout#379]
When the isDraggable or isResizable is changed in responsive grid layout it recreates the children every time. This is because the hierarchy is changed as react-draggable/react-resizable is inserted in the middle and react reloads all the child components. 

This issue can be fixed by always using the react-draggable/react-resizable components and passing isDraggable/isResizable over to the disabled prop of react-draggable/react-resizable. Would be happy to assist in the change.

And thanks for the wonderful library 👍

**Comment by daumann** [comment]
see  #371

**Comment by daumann** [comment]
Similar to that, if you remove one element , it recreates all elements in the set. @STRML do you have any idea how to circumvent this like the "hack" you mentioned in #371 ?

**Comment by STRML** [comment]
Yes, this is an unfortunate issue in the current architecture. I plan to fix this in #346.
