### ISSUE TITLE
Resizing item jumps both in w and h

### ISSUE THREAD

**Issue by vpezeshkian** [STRML/react-grid-layout#381]
What may cause this behavior? upon resizing the h and w increases more than 1 unit, resulting bad resize experience. 
This is not happening on forked branch, that's why I'm asking for the possible reasons to get this effect. I can't figure out where and what causes this. I'm sure my additional `setStates` are not the reason. 

![resize-issue](https://cloud.githubusercontent.com/assets/6642294/19578929/dcc9e5cc-96d2-11e6-9a76-4e1e14930272.gif)

**Comment by STRML** [comment]
I'm sorry but I can't reproduce this. If you can come up with a reliable reproduction at http://www.webpackbin.com/VymTE3zWG that would be very helpful.

**Comment by groenewaldd** [comment]
I'm not the original reporter but I did notice similar behaviour when I would choose to only show the resize handle on hover. Looking at the illustration it looks @vpezeshkian may be doing something similar?

Minimal reproduction here (try and resize box 1):
https://codesandbox.io/s/g59AgqK99

Removing this CSS resolves the issue:
```
.react-grid-item .react-resizable-handle {
  display: none;
}

.react-grid-item:hover .react-resizable-handle {
  display: block;
}
````

(using a horrible injectGlobal workaround as I couldn't work out how to get  codesandbox to include separate CSS files)
