### ISSUE TITLE
Initial render creates layout discrepancy

### ISSUE THREAD

**Issue by tquetano-r7** [STRML/react-grid-layout#388]
So ... I'll start by saying I can't quite pin down where this is occurring ... I've tried, but it looks like it SHOULD work. But it doesn't.

I'm using `Responsive` with `WidthProvider`, and it appears to be working fine, except on initial load. For some reason the initial load is passing in a width far lower than the window (like half), but then immediately it corrects itself to the proper width (I've seen it in props) ... the problem is that the cards layout does not re-render when this occurs. What this results in is something along the lines of this:

* Initial width from props = 1145, and therefore breakpoint of *lg*
* Cards render based on *lg* layout
* New width from props = 2547, and therefore breakpoint of *xl*
* ... nothing

I was able to solve this by using [remeasure](https://github.com/planttheidea/remeasure) on the container and only rendering the grid when the width is populated (and using the width provided from `remeasure` instead of `WidthProvider`), but I feel like this is something that the WidthProvider should be handling.

This appears only to happen on that initial load ... all other changes to the width are handled just fine. I even tried manually dispatching a window resize event and that didn't trigger the change. I also dived through your code a bit, and it looks like the width, breakpoints, etc. are all being updated correctly when that new width from props comes in ... but the cards don't get rendered to reflected the new breakpoint scheme.

Long-winded I know, but I wanted to provide as much detail as I could.

**Comment by STRML** [comment]
Did you try WidthProvider's `measureBeforeMount` option?

**Comment by tquetano-r7** [comment]
Bugger ... yeah that was totally it. I think I'll still stick to `remeasure` because it handles element resize instead of just window `resize`, but I'll close because it's not a bug. Sorry to bother!
