### ISSUE TITLE
How to call onDrag when the mouse is down?

### ISSUE THREAD

**Issue by rickyhan** [STRML/react-grid-layout#392]
How to trigger onDrag on a GridItem?

This is what I came up with:
Basically, it finds the new GridItem that just got created through refs, then it finds the DOM node to pass it to onDragHandler. I've been working on this all day and would really appreciate some pointers.

``` Javascript
//e is a synthetic event that is produced by dragging some other node
    var newGridItem = _this._grid.refs.rrgl.refs.rgl.state.griditems[name];//finds the new GridItem
    var newDomObj = ReactDOM.findDOMNode(newGridItem);
    var newEvent = new MouseEvent('mousemove', Object.assign({},{...e},{target: newDomObj}));
    newGridItem.onDragHandler('onDragStart')(newEvent, {node: newDomObj, deltaX: 0, deltaY: 0});
    newGridItem.onDragHandler('onDrag')(newEvent, {node: newDomObj, deltaX: 0, deltaY: 0});
```

The error is `GridItem.js:300 Uncaught Error: onDrag called before onDragStart.`

**Comment by ayousaf11** [comment]
Hi @rickyhan, were you able to fix this?
