### ISSUE TITLE
node.offsetParent is sometimes null and messes up with positioning

### ISSUE THREAD

**Issue by vpezeshkian** [STRML/react-grid-layout#395]
continuation of #381 , after doing lots of debugging I can see that `node.offsetParent` sometimes returns `null` in `getControlPosition()` helper function.

```javascript
console.log(node); // constantly returns `react-resizable-handle` dom element
console.log(node.offsetParent); // but this is null sometimes
```

<img width="774" alt="screen shot 2016-11-01 at 9 25 56 am" src="https://cloud.githubusercontent.com/assets/6642294/19897443/4b218746-a015-11e6-83a6-f1e726155d9c.png">

**Comment by STRML** [comment]
Can you track down when it is null?

**Comment by vpezeshkian** [comment]
I'm sure that `handleDragStart` picks it right, then on first px move `handleDrag` returns the correct values, but on 2nd px move it's `null`... how can I go deeper in debugging?

**Comment by STRML** [comment]
If you can get a jsfiddle going that replicates it, that would be best -
otherwise set some breakpoints & step through it.

**Comment by vpezeshkian** [comment]
This can be closed now... the issue was in css where i had touched placeholder z-index, so on resize it would sometimes be on top of the drag item and that's why `node.offsetParent` would be null. Reset the css to master and it's fine... 🏭
