### ISSUE TITLE
onLayoutChange not triggered when number of items in grid changes

### ISSUE THREAD

**Issue by tquetano-r7** [STRML/react-grid-layout#396]
As the title suggests, it appears that `onLayoutChange` is not triggered when the number of items changes. This makes it challenging to determine the "derived layout" of that specific item.

Or, asked a different way, is there a way to determine the derived layout of an item dynamically added to the grid?

**Comment by STRML** [comment]
Are you certain that you are on the latest build? It is a bug if `onLayoutChange` is not being fired.

**Comment by tquetano-r7** [comment]
I'm on 0.13.9 ... according to npm view thats the latest.

**Comment by STRML** [comment]
Could you reproduce this on http://www.webpackbin.com/VymTE3zWG?

**Comment by tquetano-r7** [comment]
Crap ... no, appreciate the webpack bin because that made me reexamine how we were checking for layout changes, and it was the implementation that was the problem. Sorry about that. :disappointed: . Closing.
