### ISSUE TITLE
TypeError: Cannot set property 'validated' of undefined

### ISSUE THREAD

**Issue by NSinopoli** [STRML/react-grid-layout#40]
Thanks for your great work with this library! I'm new to React and am unfortunately having some trouble getting things working. I [copied](https://github.com/STRML/react-grid-layout/blob/master/test/examples/1-basic.jsx) and slightly modified one of your examples:

```jsx
var BasicLayout = React.createClass({
  mixins: [React.PureRenderMixin],

  getDefaultProps: function() {
    return {
      className: "layout",
      items: 20,
      rowHeight: 30,
      cols: 12
    };
  },

  getInitialState: function() {
    var layout = this.generateLayout();
    return {
      layout: layout
    };
  },

  generateDOM: function() {
    return _.map(_.range(this.props.items), function(i) {
      return (<div key={i}><span className="text">{i}</span></div>);
    });
  },

  generateLayout: function() {
    var p = this.props;
    var layout = [];
    var y;
    for (i = 0; i <= p.items - 1; i++) {
      y = p['y'] || Math.ceil(Math.random() * 4) + 1;
      layout[i] = {x: i * 2 % 12, y: Math.floor(i / 6) * y, w: 2, h: y, i: i};
    }
    return layout;
  },

  onLayoutChange: function(layout) {
    this.props.onLayoutChange(layout);
  },

  render: function() {
    return (
      <ReactGridLayout layout={this.state.layout} onLayoutChange={this.onLayoutChange}
          {...this.props}>
        {this.generateDOM()}
      </ReactGridLayout>
    );
  }
});
```

Unfortunately, this triggers an error: `TypeError: Cannot set property 'validated' of undefined`. The relevant bit of code involves the line `node._store.validated = true;` within the following block:

```js
function validateChildKeys(node, parentType) {
  if (Array.isArray(node)) {
    for (var i = 0; i < node.length; i++) {
      var child = node[i];
      if (ReactElement.isValidElement(child)) {
        validateExplicitKey(child, parentType);
      }
    }
  } else if (ReactElement.isValidElement(node)) {
    // This element was passed in a valid location.
    node._store.validated = true;
  } else if (node) {
    var iteratorFn = getIteratorFn(node);
    // Entry iterators provide implicit keys.
    if (iteratorFn) {
      if (iteratorFn !== node.entries) {
        var iterator = iteratorFn.call(node);
        var step;
        while (!(step = iterator.next()).done) {
          if (ReactElement.isValidElement(step.value)) {
            validateExplicitKey(step.value, parentType);
          }
        }
      }
    } else if (typeof node === 'object') {
      var fragment = ReactFragment.extractIfFragment(node);
      for (var key in fragment) {
        if (fragment.hasOwnProperty(key)) {
          validatePropertyKey(key, fragment[key], parentType);
        }
      }
    }
  }
}
```

I'm not sure how helpful that is on its own; I can get you the full trace if needed. For what it's worth, I'm using [react-rails](https://github.com/reactjs/react-rails). The problem could lie within that, but I've tested some basic examples (not including RGL) and everything worked as expected.

Thanks!

**Comment by STRML** [comment]
Perhaps the full source would help. You can embed on jsfiddle by using the React CDN and this module via https://rawgit.com/STRML/react-grid-layout/master/dist/react-grid-layout.min.js

**Comment by NSinopoli** [comment]
Thanks. I reproduced it in this [JSFiddle](http://jsfiddle.net/69z2wepo/5595/).

**Comment by STRML** [comment]
Just wanted to verify, are you using the dist library from the CDN, or are you using webpack/browserify?

**Comment by NSinopoli** [comment]
Not sure which library you're referencing... If it's RGL, I'm using the rawgit link you referenced above. 

You can hover over each of the "External Resources" to see the origins of the other assets.

**Comment by STRML** [comment]
Yeah, I'm asking about the first time you saw the bug - were you using the
build or using browserify/webpack?

**Comment by NSinopoli** [comment]
Ah, I was using the build.

**Comment by STRML** [comment]
Cool. I think it might be a build error. Will investigate.

**Comment by STRML** [comment]
Okay - this is fixed, see [this fiddle](https://jsfiddle.net/69z2wepo/5864/).

Issue was the `react/lib/cloneWithProps` import, which imported `ReactElement` and a host of other garbage. React really doesn't play nice when there are duplicated imports of its modules. Using browserify or webpack fixes this automatically but the build was not quite as smart. 

This also shaves a few kb (about 25kb from the unminified build) as well.

Thanks for bringing this to my attention.

**Comment by NSinopoli** [comment]
Great, thanks **so** much! One last question... Which assets do I need to include so that the animations are as smooth as the ones found [here](https://strml.github.io/react-grid-layout/examples/1-basic.html)?

**Comment by STRML** [comment]
There appears to be another difference between the bundle and the original webpacked source - react-draggable is acting oddly and the `style` passed by the grid is overriding the style set when dragging, which isn't supposed to happen. I'll take a look at it.

React sure gets strange when you package it this way.

**Comment by NSinopoli** [comment]
Any luck?

**Comment by crispamares** [comment]
I have encountered the same problem while building an app using react-grid-layout for electron.
If I use webpack with `target: "atom"` then the error happens.

I really don't understand the problem but the solution was the same, adding this **to my** webpack.config.js: 

```
plugins: [
    new webpack.NormalModuleReplacementPlugin(/\/react\/lib\/cloneWithProps/, '../../react-clonewithprops/index.js'),
  ],
```
