### ISSUE TITLE
Not exactly an issue but a question

### ISSUE THREAD

**Issue by MaxJeong** [STRML/react-grid-layout#401]
Just curious, are you able to incorporate APIs into the widgets by any chance? I would like to know this before I incorporate react grid layout into my project.

I'm specifically looking into making widgets for games. For instance, a widget that shows a League of Legend player's game stats. That being said, if RGL is compatible with other APIs, I'm pretty sure I can work it out with game APIs.

To the devs who worked on this before, game related or not, some simple examples would be nice. Thanks in advance.

**Comment by STRML** [comment]
This is purely a layout library; this is like asking if a Material UI library can incorporate data from other sources.

The simple answer is, yes, of course, you can put any data you want in a grid.
