### ISSUE TITLE
Not able to call setState() inside onLayoutChange

### ISSUE THREAD

**Issue by ns04stars** [STRML/react-grid-layout#402]
I am using react-grid-layout to implement ResponsiveReactGridLayout and in onLayoutChange() function I am trying to do this.setState, but somehow its giving error saying setState is not a function. I already defined constructor.

Grid.js
import React, { Component } from 'react';
import ResizableAndMovable from 'react-resizable-and-movable';
import {Responsive, WidthProvider,ReactGridLayout} from 'react-grid-layout';
import Charts from './charts.js';

const ResponsiveReactGridLayout = WidthProvider(Responsive);

class Grid extends Component {
    constructor(props){
        super(props);
        this.state = {
            status :false
        };

    }

    onLayoutChange(layout) {
       console.log(layout);
        this.setState({status : true});
    }

    getCharts(){
        return (<div key="d" className = 'react-grid-item react-resizable'
                     data-grid={{x: 1, y: 0, w: 1, h: 3}} style={{ border:'1px solid green', borderStyle: 'groove'}}>
            <Charts  {...this.props} id={'Chart 1'}/>
        </div>);
    }

    render(){
        return (

            <div style={{borderStyle: 'groove'}}>
                <h2> Panel Header </h2>
                <ResponsiveReactGridLayout className="layout"
                     breakpoints={{lg: 1200, md: 996, sm: 768}}
                     cols={{lg: 5, md: 3, sm: 2}}
                     onLayoutChange={this.onLayoutChange}>
                    <div key="c" data-grid={{x: 0, y: 0, w: 1, h: 3}} style={{ border:'1px solid green', borderStyle: 'groove'}}>
                        <img src="http://image.slidesharecdn.com/pptsimile-140921093117-phpapp02/95/ppt-simile-3-638.jpg?cb=1411291995" style={{width:'inherit', height:'inherit'}} />
                    </div>
                    {this.getCharts()}

                </ResponsiveReactGridLayout>
            </div>
        )
    }
}

export default (Grid);

**Comment by STRML** [comment]
This is not an RGL problem, you are not binding your handler.

**Comment by ns04stars** [comment]
Sorry I am really new to react, can you please elaborate on my source code?

**Comment by STRML** [comment]
https://medium.com/@housecor/react-binding-patterns-5-approaches-for-handling-this-92c651b5af56#.p20iaae36

**Comment by ns04stars** [comment]
thanks for quick reply and help
