### ISSUE TITLE
Resize an grid item

### ISSUE THREAD

**Issue by TriPSs** [STRML/react-grid-layout#403]
Is it possible to programmatically resize an grid item?

**Comment by dmackerman** [comment]
Change it's props?

**Comment by STRML** [comment]
Yes, change the layout.

**Comment by ronidavelman** [comment]
@STRML "Yes, change the layout." What exactly does that mean?

**Comment by STRML** [comment]
Change the data in the prop called `layout`.

**Comment by ronidavelman** [comment]
@STRML I've tried implementing the solution you described. 

<ReactGridLayout rowHeight={100} layout={this.state.layout}></ReactGridLayout>

When the "h" propery of i: i, x: 0, y: 0, w: 1, h: h is updated to a new integer, the grid item doesn't update its height. The expected result would be that as h is increased from 1 to 2, 2.5, 3, 3.5, it would update based on the rowHeight. 

Any ideas?

**Comment by harleylang** [comment]
Any update? This seems like the simplest solution but as @ronidavelman mentioned, an integer change to the layout does not change that item's height.
