### ISSUE TITLE
Since 0.13.7 + manipulating layout in a function doesn't update actual layout

### ISSUE THREAD

**Issue by FerusAndBeyond** [STRML/react-grid-layout#406]
I have a ReactGridLayout looks like this:

`<ReactGridLayout ... onLayoutChange={this.layoutChange} className="layout" layouts={layouts} rowHeight={this.rowHeight} width={this.state.pageWidth}>`

I then have a function that manipulates layouts by setState. In 0.13.6 the "actual" layout is changed and works fine. But in 0.13.7 + the state will change and will be but as a prop in <ReactGridLayout> but the "actual" layout, the layout shown on the screen is NOT changed.

**Comment by tthamel** [comment]
can you post the function code?

**Comment by FerusAndBeyond** [comment]
Sure, here's the code:
```
    changeBoxSize: function (index, size) {
        var layout = this.state.wideLayout;
        var w = 0;
        var h = 0;
        var changeState = false;
        if (size.height !== undefined) {
            while (this.getHeightFromPixels(h) < size.height) {
                h++;
            }
            if (this.getHeightFromPixels(h) - size.height > this.columns.lg / 2) {
                h--;
            }
            if (layout[index].h !== h) {
                layout[index].h = h;
                changeState = true;
            }
        }
        if (size.width !== undefined) {
            while (this.getWidthFromPixels(w) < size.width) {
                w++;
            }
            if (layout[index].w !== w) {
                layout[index].w = w;
                changeState = true;
            }
        }
        if (changeState) {
            this.setState({
                wideLayout: layout
            });
        }
    },
```

**Comment by tthamel** [comment]
whats triggering the logic for changing the layout?   i didnt have an issue with layout but i was having an issue with ES6 and binding my click functions to this. layout changes appear to work in this version for me but they are API triggered, so thats why i thought maybe syntax

**Comment by FerusAndBeyond** [comment]
Its send from a component living inside a grid-item. It has specific width/heights and therefore I have to send info to the layout how big it is. Im able to change the layout, thats no problem, the thing is the actual layout I see on the screen isnt the same as the layout Ive set.

**Comment by STRML** [comment]
Can you reproduce this in http://www.webpackbin.com/VymTE3zWG?

**Comment by jeremymlane** [comment]
Here you go: http://www.webpackbin.com/Nk5cKsEPM

**Comment by STRML** [comment]
Would you care to explain how to replicate it within that example?

**Comment by jeremymlane** [comment]
@STRML Sorry. I've updated it to be a little more clear (http://www.webpackbin.com/Nk5cKsEPM). Let me explain what happens.

1. The grid renders it's items which are `<MyComponent />` elements and passes them a `didUpdate` callback. 
2. The item checks its internal height and then runs the `didUpdate` callback.
3. The `didUpdate` callback finds that the component is taller than its assigned height, and so updates the layout to give it an appropriate height and then uses `setState` to set the layout to the updated version.
4. The grid re-renders, but somehow still uses the original layout. You can verify this by looking at the contents of the item. The text will show the height that the item is supposed to be while the actual height of the item will be too short.

**Comment by jeremymlane** [comment]
@STRML @FerusAndBeyond Turns out it was how the layout was being cloned that was the issue. I was doing this:

```
let layouts = _.clone(this.state.layouts);
layouts.lg[i].h = newHeight
this.setState({layouts: layouts});
```

But since `_.clone` clones the outer object but keeps the references within the object, when the `componentWillReceiveProps` function on`ResponsiveReactGridLayout` does an `_.isEqual` call, it found that they were actually equal since I had already modified the reference. 

What I ended up doing was using https://www.npmjs.com/package/clone to do a deep clone instead of only cloning the outer object, so my final solution looks like: 

```
const clone = require('clone');
let layouts = clone(this.state.layouts);
layouts.lg[i].h = newHeight
this.setState({layouts: layouts});
```

**Comment by FerusAndBeyond** [comment]
That's right, it does work (I use $.extend instead of lodash)
