### ISSUE TITLE
support for Immutable Map type of data-grid

### ISSUE THREAD

**Issue by johnsiu2016** [STRML/react-grid-layout#407]
![image](https://cloud.githubusercontent.com/assets/17636906/20237312/53c59f98-a909-11e6-9a8e-b81dc0e42152.png)

As I use ImmutableJS for my state, I need to convert the state back to JS Object for each item every time re-rendering. I think the overhead is quite high, so
are there any ways to achieve the same result without converting the state back to JS object?

**Comment by STRML** [comment]
Hi - no, there is no support nor is any planned. Internal code would need to adapt for an individual library which is unprecedented and unmaintainable.
