### ISSUE TITLE
Is this package maintained?

### ISSUE THREAD

**Issue by RaymondLC92** [STRML/react-grid-layout#408]
I'm curious about moving from Blaze + Susy to React + React-Grid-Layout.

Is this package going to be supported for the foreseeable future? If not, does it have a replacement?

**Comment by STRML** [comment]
Hi Raymond,

Yes, although I am looking for help with the maintenance. I plan to do a v2 (#346) that will address many of the open issues & create extension points.

**Comment by RaymondLC92** [comment]
@STRML 

Good to hear, I'll see what leveraging it in my project does for me experience wise.
