### ISSUE TITLE
rowHeight inconsistencies question (with example)

### ISSUE THREAD

**Issue by caguthrie** [STRML/react-grid-layout#410]
Take a look at this webpackbin: http://www.webpackbin.com/EkuNBGQbM

rowHeight is 50.

The first element (element 1) has ```h: 1```, therefore, the height should be 50.  Which it is.
The second element (element 2) has ```h: 2```, therefore, the height should be 100.  It is actually 110.  Why is that?

Am I missing something here?

**Comment by STRML** [comment]
Yeah, the issue is the `margin`; an item of `h:2` is equal to `heightPx * h + (marginH * (h - 1))`, or 110.

The reason being, without this margin adjustment, the grid would look ragged if any items had a height or width over 1.

**Comment by caguthrie** [comment]
Thanks for the quick response
