### ISSUE TITLE
Widgets keep snapping to the upper left when first clicked [Bug]

### ISSUE THREAD

**Issue by MeteorGuy** [STRML/react-grid-layout#411]
Hello, so whenever I first click on a widget to drag it, it will snap in the upper left corner instead of staying in its original spot when first clicked to be dragged. Any suggestions?

**Comment by Rus-Cosmin** [comment]
Same here.....when state changes or any other modification the widget goes to the left corner and animates to it intended position

**Comment by hluedeke** [comment]
Has anyone figured this out?
