### ISSUE TITLE
[Bug] Do not re-render when position is unchanged

### ISSUE THREAD

**Issue by alexkvak** [STRML/react-grid-layout#413]
GridItem re-renders even if it's position is unchanged.

Probably you need to store current element position in the element state.

See https://github.com/STRML/react-grid-layout/blob/master/lib/GridItem.jsx#L354

**Comment by Flui** [comment]
I think I have got a problem that is related to this issue. I my scenary every GridElement consists of a Header to drag the element and a ContenFrame. The header includes a button to make the element static. but I do not want to rerender the content if I toogle static.
When I am changing the static value of a specific element in the layout provided to a ResponsiveReactGridLayout, the GridElement will be unmounted and therefore the ContentFrame will be updated to. I there a way to get around this issue.

**Comment by m7luffy** [comment]
I meet the same problem as @Flui mentioned. Changing the 'static' property will lead the element be unmounted and re-mounted again. Re-mount will lead some data loading in my app. Is there any way to switch between draggable and not draggable status without re-mount the element?
