### ISSUE TITLE
[bug]    tile rendering and draggability issues with react 15.4

### ISSUE THREAD

**Issue by tthamel** [STRML/react-grid-layout#414]
not sure if others are seeing this but tiles are not rendering content and draggability is broken on react 15.4

**Comment by STRML** [comment]
Will take a look

**Comment by STRML** [comment]
I'm not seeing this; must be something else in your application or a dependency that is choking on the upgrade. Any deps that rely on React internals probably broke with 15.4.

See https://strml.github.io/react-grid-layout/examples/0-showcase.html which is upgraded to 15.4 and works fine (call `React.version` in the console).

**Comment by tthamel** [comment]
thanks man for taking a clean look... yeah three deps have been effected and yesterday was a cluster coordinating with the teams to give them feed back.

**Comment by STRML** [comment]
Yeah, was a pain for us as well, but these kind of things are good in the end; FB devs are cleaning up the ecosystem a bit. One nice thing about forcing lib devs to not rely on `/lib` imports is the ease of switching to, say, preact.

**Comment by tthamel** [comment]
so true, im glad FB is forcing devs to the future (kicking and screaming).  would love to use preact but the no IE support is a non starter :/
