### ISSUE TITLE
[Question] Is there a width equivalent to rowHeight?

### ISSUE THREAD

**Issue by MaxJeong** [STRML/react-grid-layout#415]
Title.

**Comment by STRML** [comment]
There aren't fixed widths, but width is always a function of `(width - (cols - 1 ) * margin) / cols`.

**Comment by MaxJeong** [comment]
Thanks for the fast response. What is that function supposed to equate too though? And if I tinker with the function, can I modify the width? Because right now, when I move widgets horizontally, its moving a bit too far for our taste so that's why I asked if there is something like a rowHeight for width.

**Comment by STRML** [comment]
That's the width of one col unit, in pixels.

I'm not sure what you're referring to when you say "moving a bit too far for our taste", but play with the following items and I'm sure you'll get what you want:

* `cols`
* `margin`
* The width of the RGL container
