### ISSUE TITLE
[Question] Does ResponsiveReactGridLayout support static and setting minimum/maximum width?

### ISSUE THREAD

**Issue by MaxJeong** [STRML/react-grid-layout#418]
It doesn't seem to work for responsive widgets. Is there another way to set them then?

**Comment by Flui** [comment]
I am sure it does. I am using a ResponsiveReactGridLayout and some of the items are static and do have a minW. how does the layout look like you are providing to the ResponsiveReactGridLayout?

**Comment by h3adache** [comment]
I was wondering the same.

Using the example from the readme and all I did was replace `ReactGridLayout` with the `ResponsiveReactGridLayout` from the [providing-grid-width](https://github.com/STRML/react-grid-layout#providing-grid-width) example. It seems that static / w/h / minW/minH are all ignored.

The [example](https://strml.github.io/react-grid-layout/examples/9-min-max-wh.html) just uses the non responsive RGL?

**Comment by h3adache** [comment]
Sorry I was using it incorrectly. I left the layout the same as the example but looking at [0-showcase.jsx](https://github.com/STRML/react-grid-layout/blob/master/test/examples/0-showcase.jsx) I see now that I should have sent a layout for the breakpoint.

Changing `layout` to `layouts` and using:

```
    this.layouts = {
      lg: [
        {i: 'pg', x: 0, y: 0, w: 8, h: 12, minW: 4, minH: 6},
        {i: 's', x: 8, y: 0, w: 4, h: 1, static: true},
        {i: 'ev', x: 8, y: 1, w: 4, h: 6},
      ]
    }
```

Works
