### ISSUE TITLE
Bug: Do not save order GridItems in ResponsiveGridLayout when breakpoint changed 

### ISSUE THREAD

**Issue by artem-kushal** [STRML/react-grid-layout#419]
You can see this bug in action in a video (http://www.screencast.com/t/khNXuhDMv0T). I think that is a bug.

**Comment by larrydahooster** [comment]
Well isn't that exactly what the demo is supposed to do? Save the layout per breakpoint in the Localstorage. When you go from breakpoint X to breakpoint Y and change it and then go back to X, it should show the unmodified layout of breakpoint X.

**Comment by chadd1783** [comment]
any solutions here that someone came up with? I see why you would want to preserve order per breakpoint but also makes sense to have order carry across while maintaining sizes respectively.  Tried a few approaches so far but this library doesn't want it to happen...
