### ISSUE TITLE
Reorganize elements after changing layout in props

### ISSUE THREAD

**Issue by duranb** [STRML/react-grid-layout#42]
Is there a way to have the grid move around elements to fit again if the layout is changed by other means than dragging?

For example, if I have two elements side by side:

![leftright](https://cloud.githubusercontent.com/assets/5290214/6954476/0fcdadca-d887-11e4-8f31-2f2452617612.png)

and I change the `w` of the left one to span the maximum number of columns, right now the left element then overlaps the right element: 

![overlap](https://cloud.githubusercontent.com/assets/5290214/6954486/1c2945d4-d887-11e4-8454-ac24f233aa98.png)

If the grid is remounted with the same exact layout, it recognizes this overlapping and properly moves down the right element under the left one:

![fixed](https://cloud.githubusercontent.com/assets/5290214/6954488/26fb1050-d887-11e4-8fcb-d6dc9b70bed8.png)

Is there a way to do this without having to remount the grid?

**Comment by STRML** [comment]
If you change an existing element without going through the normal resize handlers, I see how this could happen.

When you change the `layout` prop, it should be recompacting the layout. How are you changing the `w`?

**Comment by duranb** [comment]
The layout is a state in the parent component of the grid.  I'm basically throwing an event when someone clicks the `expand` in the grid elements that the parent component is listening for.  Right now the parent is just picking the first layout and setting it's `w` to max columns and forceUpdate is called.

**Comment by STRML** [comment]
That should call [this line](https://github.com/STRML/react-grid-layout/blob/master/lib/ReactGridLayout.jsx#L147), which will re-compact the grid and resolve the conflict.

**Comment by duranb** [comment]
Thank you!  Your comment led me to find a bug in how I was setting the layout.
