### ISSUE TITLE
[ Question ] Defining GridItem props on children

### ISSUE THREAD

**Issue by chrisdrackett** [STRML/react-grid-layout#421]
I'm pretty new to RGL so I might be missing something. We're building a dashboard and want our custom grid items to be able to define if they are resizable or not and in what way. For example, say we have a `List` that we want to set to be fixed at one grid unit wide and can be as many grid units tall as it wants.

I think my issue is that `List` is a subcomponent of `CustomGridItem` (handles our global gird item styles). So while we set `data-grid` on `List`, this component isn't the direct child of the grid. 

I'm thinking this might be a pretty normal use case and I'm just missing something, but figured it can't hurt to ask!

**Comment by STRML** [comment]
Don't use `data-grid` in that case - use the top-level `layout` prop and keep all your grid layouts in a single object.

**Comment by chrisdrackett** [comment]
right, I was just hoping to have control over a grid item's resizability in the custom grid item. We can make this work using the top level layout, but it is potentially more error prone as you could set values that a grid item component can't actually support.
