### ISSUE TITLE
[Bug] IE 11 Scroll Bar Handler for Inner Grid

### ISSUE THREAD

**Issue by chuangbanLS** [STRML/react-grid-layout#422]
For IE11, if grid has scroll bar. RGL triggers onDrag event when clicking on scroll bar.

**Comment by tuhins** [comment]
@chuangbanLS did you have any luck figuring this out?

**Comment by SujitGadkari** [comment]
Facing same issue. I tried to disable this behavior by passing "::-webkit-scrollbar-thumb" and other scrollbar related DOM elements to "draggableCancel" property, but that just disables the dragging for the whole tile as if you are passing the prop "isDraggable = false".
