### ISSUE TITLE
BUG: layout issue with const breakpoint

### ISSUE THREAD

**Issue by jonashartwig** [STRML/react-grid-layout#428]
Hi, I found an issue: If I do not send in breakpoints like this:  breakpoints={{ lg: 1200, md: 996, sm: 768 }} but instead I do:

`
import { WidthProvider, Responsive } from "react-grid-layout";
const ResponsiveReactGridLayout = WidthProvider(Responsive);
const breakPoints = { lg: 1200, md: 996, sm: 768 };

<ResponsiveReactGridLayout ... breakpoints={breakPoints} >...</ResponsiveReactGridLayout>
`

and after I put in some children and layout I immediately get an onLayoutChange call with all x, y, h and w reset to other values.

Any idea why?

Regards.

**Comment by STRML** [comment]
There must be another error in your code - those two snippets are
equivalent.

**Comment by STRML** [comment]
This could be a bug with https://github.com/STRML/react-grid-layout/blob/master/lib/ResponsiveReactGridLayout.jsx#L141 - it should be using `isEqual`, not checking reference equality.

**Comment by jonashartwig** [comment]
if i have time i can try to write some test and maybe fix it. no promises though.

**Comment by jonashartwig** [comment]
Hi, I investigated a bit. I could not reproduce the issue with a clone from the repo. I also have 2 projects using react grid layout. Only one shows the issue:

As soon as i render the grid layout with updated values i get a callback with replaced values for lg ONLY. This does not appear if i set breakpoints as non constant. I do not quite understand why. Any further ideas?

**Comment by jonashartwig** [comment]
Hi, I found the issue:

1. I render ResponsiveReactGridLayout with layout: { lg: [], md: [], sm: [] }, and [] as children. So empty basically
2. I try to rerender with a layout: { lg: [11], md: [11], sm: [11] } and [11] children.
3. It goes into componentWillReceiveProps and i see children is now [11] but layout is still unchanged
4. ResponsiveReactGridLayout does its magic and created a new layout
5. it calles onLayoutChanged
6. I update my layout
7. I update ResponsiveReactGridLayout with new layout prop
8. stuff is smooshed together on the left

Though i have no idea why 3 happens in the first place. react is ^15.4.0.

Regards

**Comment by jonashartwig** [comment]
https://github.com/STRML/react-grid-layout/pull/430

**Comment by jonashartwig** [comment]
Can we get this in there? It would make my life easier :)

**Comment by jonashartwig** [comment]
@STRML ping =)

**Comment by joeferraro** [comment]
bump @STRML i'm running into the same issue. will this PR be merged?

**Comment by STRML** [comment]
This PR doesn't fix the issue. It should be checking deep equality of `breakpoints`, reference equality of `layouts` has nothing to do with it.

**Comment by jonashartwig** [comment]
true, but this fixed the issue it breakPoints in deed is a const :)

**Comment by jonashartwig** [comment]
I updated the PR to use isEqual instead
