### ISSUE TITLE
The Dragging function not working in tablet

### ISSUE THREAD

**Issue by sumikoabe** [STRML/react-grid-layout#429]
Thanks for all of your great job of this library. I am trying several demo samples on ipad. The dragging operation dose not work as control. The whole demo page moves at same time when dragging... Any ideas?

Thanks!

Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [x] Feature Request
- [ ] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/VymTE3zWG)
to demonstrate. It is much easier for us to help you if you do.

**Comment by sumikoabe** [comment]
[Video_1.zip](https://github.com/STRML/react-grid-layout/files/632538/Video_1.zip)
Please refer the video for the operation... Thank you!

**Comment by STRML** [comment]
Hi @sumikoabe - we recently fixed some ipad issues, but they didn't yet make it into the demo. Could you please clear your cache and try the demo now?

**Comment by sumikoabe** [comment]
Hi, thanks for your prompt response. I tried again and it is still not work....

**Comment by jonashartwig** [comment]
hej,

we addressed ipad drag issues with this:

    _handletDragStart () {
        document.ontouchmove = e => e.preventDefault();

        this.setState({
            containerClass: "no-overflow"
        });
    }

    _handleDragStop () {
        document.ontouchmove = () => true;

        this.setState({
            containerClass: ""
        });
    }

**Comment by sumikoabe** [comment]
Hi Jonashartwig,
Thank you so much for sending me the information!
could you please tell me where those code  should be located?

**Comment by jonashartwig** [comment]
you send this as properties to the grid.

**Comment by sumikoabe** [comment]
Thanks! I tried to added on prototype but it not work. Do you have any exaples? thank you...
