### ISSUE TITLE
synchronizeWithChildren fails with child.key undefined error

### ISSUE THREAD

**Issue by eschiebel** [STRML/react-grid-layout#43]
In utils.js function synchronizeWithChildren starts off

        children = [].concat(children); // ensure 'children' is always an array

If the incoming `children` argument to this function is undefined, which it will be if you create a `ReactGridLayout` with none, then the result of this statement is an array, length 1 with `children[0] === undefined`. The loop over `children` sets `child` to this undefined, and throws an exception as soon as it tries to access a property of `child`.

**Comment by STRML** [comment]
Thanks for the catch. I'll add a check for this.
