### ISSUE TITLE
[Question] Merge Dynamic Add/Remove with Responsive save to LocalStorage

### ISSUE THREAD

**Issue by yyynnn** [STRML/react-grid-layout#432]
Hi, y'all!

I want to implement the dynamic add/remove for grid items with saving all current data about position at all breakpoints to local storage.

Dynamic add/remove and how it works, i get it. Same with Responsive save to LocalStorage example.
But i cant seem to get them working together. 

Add/remove forms an array without breakpoints separation.
Responsive saves multiple arrays to json "object", one array for each breakpoint to localstorage.

I want to know how can item be added/removed to/from this "object".
Maybe someone out there already got it going.

Thanks in advance!

**Comment by lallen-6** [comment]
Hello,
Did you manage to solve this issue? I am facing a similar one now.

Thanks
