### ISSUE TITLE
Add/Removing example throws Uncaught TypeError: this.props.onLayoutChange is not a function(…)

### ISSUE THREAD

**Issue by sureshsg82** [STRML/react-grid-layout#433]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [* ] Question

http://www.webpackbin.com/N1qPihb7z is the webpackbin template

I am trying to implement Add/Removing the grid item. The issue I am facing is

Uncaught TypeError: this.props.onLayoutChange is not a function(…)
Uncaught Error: onDrag called before onDragStart.(…)
bundle.js:33 Uncaught Error: onDrag called before onDragStart.(…)

Could you please let me know what I am missing here?

Thanks

**Comment by gdad-s-river** [comment]
[This stackoverflow answer](http://stackoverflow.com/questions/33622665/react-grid-layout-example-not-working/33633440#33633440) might be helpful for the first Uncaught TypeError
