### ISSUE TITLE
don't move element away

### ISSUE THREAD

**Issue by micheletedeschi** [STRML/react-grid-layout#435]
How can I avoid other element to move away when dragging or resizing an element and cancel the action at the end if collide with some element?

P.S. other elements cannot be static and I have a layout with fixed height

**Comment by nikolas** [comment]
You could use my branch I've opened a PR for here: https://github.com/STRML/react-grid-layout/pull/385

Does that solve your problem? You would then initialize ReactGridLayout with `preventCollision={true}`, like this: https://github.com/ccnmtl/juxtapose/blob/master/src/Track.jsx#L105
