### ISSUE TITLE
Override .react-grid-item.react-grid-placeholder 

### ISSUE THREAD

**Issue by fsalamida** [STRML/react-grid-layout#449]
Hello,

Sorry for stupid question but how do I override .react-grid-item.react-grid-placeholder ?
I do

import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';

But haven't find a way to override it.

Thx,
F

**Comment by onsta** [comment]
import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';
import './overridden-placeholder.css';

Content of overridden-placeholder.css:
.react-grid-item.react-grid-placeholder {
    background-color: lime;
  }

**Comment by yael-screenovate** [comment]
@onsta im getting in the command-line "Module not found: Error: Can't resolve './overridden-placeholder.css' in ... (my file name and path)" can you help on this?

**Comment by diodimi** [comment]
> @onsta @fsalamida im getting in the command-line "Module not found: Error: Can't resolve './overridden-placeholder.css' in ... (my file name and path)" can you help on this?

A bit late, use your css file there

**Comment by kaviyarasank** [comment]
.react-grid-item.react-grid-placeholder {
    background-color: lime;
  }
  
  Its worked

**Comment by kirilchristov** [comment]
sometimes you need to use something like:
```
:global(.react-grid-item.react-grid-placeholder) {
  background: var(--color-secondary-700) !important;
}
```
