### ISSUE TITLE
Delay layout update on resize item.

### ISSUE THREAD

**Issue by oreynaldocl** [STRML/react-grid-layout#450]
- [x] Feature Request

While I resize an item in grid layout all layout is updated inmediatly.
Is it posible to delay the update of layout like this example of packery: 
http://codepen.io/desandro/pen/cyvra?css-preprocessor=scss

Or only update layout after resizeStop.

![image](https://cloud.githubusercontent.com/assets/1781538/21701422/dedee386-d37b-11e6-98ef-9f3d5c5e8004.png)

**Comment by STRML** [comment]
Sorry, this is not supported. I hope to support such extensions in v2.
In the meantime a fork would probably serve you nicely.

**Comment by ilacyero** [comment]
Thx. Yes I am createing a fork for my requirements.
