### ISSUE TITLE
ResponseReactGridLayout's optional width prop vs. ESLint 

### ISSUE THREAD

**Issue by batjko** [STRML/react-grid-layout#455]
- [ ] Bug
- [ ] Feature Request
- [X] Question

When using the ResponsiveReactGridLayout without setting a `width` prop, ESLint complains saying that it is required.
However, the docs [here](https://github.com/STRML/react-grid-layout#providing-grid-width) mention expressly that it would not be required when using WidthProvider. And it does seem to work just fine.

Now, I can see that the prop itself is still always required, it's just that ESLint looks at my usage of the component and notes that width is missing.

What shall be done, I ask thee?

**Comment by STRML** [comment]
Just just comments to ignore the error - it is "required", but if a HOC is providing it, there's no way to tell ESLint that.

**Comment by batjko** [comment]
Thanks for the quick response!

Actually, I just noticed that it was an IntelliJ issue: It wasn't ESLint that complained, but one of those pesky pre-defined inspections IntelliJ does.

The warning goes away once I disabled it.
