### ISSUE TITLE
How can I set row height automatically according the set point 

### ISSUE THREAD

**Issue by golinmarq** [STRML/react-grid-layout#457]
So, I have an electron application, I use RGL as the initial window. I want the height of my grid will be the same as the height of the window until my sm breakpoint, and then for my xs and xxs the height could be auto. 

How can I reach this using rowHeight?

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

**Comment by twils0** [comment]
I'm also interested in something along these lines. The width of the grid can be managed automatically, but not the height of the grid.
