### ISSUE TITLE
Setting custom props to the Grid Item object

### ISSUE THREAD

**Issue by vladislavprokopenko** [STRML/react-grid-layout#458]
There is no ability to set custom props to the Grid Item object.
For example:
{i: 'somekey', w: 2, h:5, contentLink: 'http://google.com'}

Property 'contentLink' will be deleted after changing layout.

Thanks!

**Comment by antfenech** [comment]
would love this feature, or to know how others are getting around this to set tile type.

**Comment by xtforgame** [comment]
+1

It would be convenient if the Grid Item object provide a ```data``` or ```customData``` property

**Comment by Jero786** [comment]
+1 In the old versions, this feature was enabled :(

**Comment by kumarharsh** [comment]
+1 
My use case is that I'd like to restrict the sizing of different components on the grid depending upon the `type` of the component. I imagined that in the `onResize` callback, I'd be able to use the `type` property of each layout item to decide which layouts are possible (1x1, 2x2, not 3x1, etc).

@STRML is there a way to do this? Going through the library, I see that the `cloneLayoutItem` function discards any props not needed by it. Maybe we can allow a custom `data` prop on each layout entry to be cloned too, for consumption in the userland?

**Comment by MaxBuodnik** [comment]
+1 
I also need this feature

**Comment by dmitriyK1** [comment]
Would be useful to have it, because in my case ids of items of different types are not unique and I need to guarantee their uniqueness by storing some custom identifier in a custom property and also this will allow to map grid items to specific data models

**Comment by snax4a** [comment]
I also need this. I need to store it in database each grid item need to have a type attribute so i can render it as different component when loading a layout

**Comment by Zelenetska** [comment]
+1
I also need this feature

**Comment by matronator** [comment]
Wow, okay, so now we're closing unresolved issues automatically, just because they're ignored?

**Comment by STRML** [comment]
@matronator This is how we've been doing it for years. If you want to make a PR go for it. This is a volunteer project.
