### ISSUE TITLE
Multiple grids

### ISSUE THREAD

**Issue by razvanip** [STRML/react-grid-layout#459]
- [ ] Bug
- [x] Feature Request
- [x] Question

Hello,

- Is it possible to have multiple grids and keep the same functionality with drag & drops between the grids ( moving one ```GridItem``` from one grid to the other)?

**Comment by elcsiga** [comment]
+1

**Comment by razvanip** [comment]
@STRML any plans regading a grouping solution with multiple layouts, beeing able to drag between different layout sections?

Will 2.0 include features like this?

I want to make a pr for this feature but not sure if to do it in 1.0 or 2.0 if it's not going to land in 2.0

Thank you,
R

**Comment by STRML** [comment]
I don't plan to implement this in 1.0 or 2.0, but the 2.0 API will make it much simpler to create and maintain these sort of features as plugin repos rather than as part of core.

**Comment by razvanip** [comment]
That's great if the api for 2.0 will allow it!
Any insights when 2.0 will come out?

Also thank you, for the hard work!

**Comment by STRML** [comment]
No insights yet - I'm swamped beyond belief at my day job so I don't
have much time for full-scale rewrites.

**Comment by elcsiga** [comment]
@STRML  I'm currently experimenting with this. It was fairly simple to remove a widget from a grid and add it to another, but I'm struggling with stopping and starting dragging without sending fake mouseup/down events. Can you please give me some hints about starting/stopping drag by code? Thnx.

**Comment by ericgibb** [comment]
@elcsiga did you ever make progress on this?

**Comment by razvantomegea** [comment]
+1

**Comment by funkytek** [comment]
+1 any developments here?

**Comment by williaster** [comment]
@STRML any developments on this? 

@elcsiga I was checking out your fork but can't see that [your `multiple` example](https://github.com/elcsiga/react-grid-layout/commit/82473a9cd5586b7fd2c956e4afc467edc4f62d2d) had any additional functionality, just demo boilerplate?

**Comment by STRML** [comment]
No. I don't have any plans to implement this.

**Comment by Ahmett65** [comment]
https://github.com/STRML/react-grid-layout/issues/459#issue-200490560

Hi @STRML 
Is there any update for this issue ?

**Comment by daynin** [comment]
We added an ability to drop elements from outside of a grid (see https://github.com/STRML/react-grid-layout/pull/980). Maybe this feature can help you

**Comment by eric-burel** [comment]
Hi guys, do you encounter issues when displaying multiple grids on the same page (without speaking of drag and drop between the grids)? In my app the multiple grids seems to offset one another. Eg if Grid 1 is 4 rows high, then when I drag an item in Grid 2, it's y is offseted by 4.



See this screenshot. First item is in Grid 1, second item in grid 2. Red point is the mouse, dragging the item. The second item should be 4 rows higher.
![bug multipel grids](https://user-images.githubusercontent.com/7983005/73449104-bfaf1580-4362-11ea-9d10-b09a31193f70.png)

Might be a bug in my code, it's a first draft, but it could also be a side effect in the grid layouts.
