### ISSUE TITLE
Customize drag selector

### ISSUE THREAD

**Issue by ilacyero** [STRML/react-grid-layout#461]
- [ ] Bug
- [x] Feature Request
- [ ] Question

Currently all component mananger the drag. I need to start the drag only in an specific part of my item.

By now I think is enought pass a handler property in grid and grid item.

**Comment by MaxJeong** [comment]
I'm trying to figure out if that's doable actually. Any luck?

**Comment by ilacyero** [comment]
There is a property to enable drag in all items:
```
// A CSS selector for tags that will act as the draggable handle.
// For example: draggableHandle:'.MyDragHandleClassName'
// If you forget the leading . it will not work.
draggableHandle: ?string = '',
```
In grid layout items I require different place to start the drag. Playing with class names is possible.
