### ISSUE TITLE
Breakpoints,bootstrap and sorting in react grid layout

### ISSUE THREAD

**Issue by niteeshravi** [STRML/react-grid-layout#462]
- [ ] Bug
- [ y] Feature Request
- [ y] Question

I am a newbie to RGL and trying to implement a grid layout. I have 3 questions here

1. I was trying to understand the breakpoints in RGL, are they the same as what we have in Material Design?.Sorry if it is a basic question. My intention is to have a responsive layout .

2. How does this gel up with bootstrap? Our application is developed using bootstrap, i am curious to understand how this goes with bootstrap.Can you give us an example on how we can consume bootstrap in RGL

3. We want to implement  sorting and filtering on the tiles. Can you give us an example on how we can implement this?

Apologize if these questions were already addressed, i could not find them.
Thanks in Advance,

**Comment by pxljoy** [comment]
As for 3.
Have a look at this, https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

I'd say you could sort the layout object by this and then feed it back to the ReactGridLayout component

**Comment by dynnt27** [comment]
Yes, I have some issues on bootstrap too. Checkboxes seem to disappear when I hover them.. very unusual. Google chrome debug tool seem not to detect anything at :hover . Any thoughts? Im trying to create a widget inside those boxes
