### ISSUE TITLE
[ ] BugError c.defalut.component undefined when using react-grid-layout.min.js without webpack

### ISSUE THREAD

**Issue by sadimula** [STRML/react-grid-layout#467]
Hi,

We are using ES5 without webpack to integrate react-grid-layout and followed as specified in readme.md to use react-grid-layout.min.js  when compiled the js file throws error component undefined .

we also used /tree/dist/react-grid-layout.min.js which uses "exports" which is part of Webpack .
Could you also please suggest on using react-grid-layout without ES6 & Webpack.

**Comment by daynin** [comment]
I think it still can be reproduced in IE
