### ISSUE TITLE
Element's width problem

### ISSUE THREAD

**Issue by mnemanja** [STRML/react-grid-layout#470]
If the screen has a vertical scroll when refreshing the page the full width elements (12 cols) flow out of the screen for the amount of the scroll's width (approximately).

If I open the dev toolbar the size gets recalculated and the width is okay. Then if I hit refresh again the width again gets wrongly calculated.

After the refresh:
![image](https://cloud.githubusercontent.com/assets/1423218/22369795/5a6532c6-e48e-11e6-9794-ff97cb313e47.png)

After opening the dev toolbar:
![image](https://cloud.githubusercontent.com/assets/1423218/22369772/4224f2b4-e48e-11e6-973b-e46d5468116d.png)

**Comment by mnemanja** [comment]
As this behavior is no longer present in my application I will close the issue. Unfortunately I haven't been able to determine the source of the problem.

**Comment by roychoo** [comment]
i am currently seeing this problem. @mnemanja did you have any more insights on why this is happening?

**Comment by mnemanja** [comment]
Hi @roychoo, I believe it was due to some elements flowing outside of the widgets, but I can't say for sure. Sorry.
