### ISSUE TITLE
"npm run dev" failed on Windows 10

### ISSUE THREAD

**Issue by ydeng1** [STRML/react-grid-layout#471]
Thanks for submitting an issue to RGL!

When I run "npm run dev", I got following error, how to resolve it? Thanks!

> react-grid-layout@0.13.9 dev F:\Grid\react-grid-layout
> make dev

echo 'Open http://localhost:4002'
process_begin: CreateProcess(NULL, echo "Open http://localhost:4002", ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [dev] Error 2

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "F:\\Program Files\\nodejs\\node.exe" "C:\\Users\\yingdeng\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! react-grid-layout@0.13.9 dev: `make dev`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the react-grid-layout@0.13.9 dev script 'make dev'.

Please mark the type of this issue:

- [] Bug
- [ ] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by nywooz** [comment]
WebpackBin Template Link is not working
