### ISSUE TITLE
How do you return the current number of columns?

### ISSUE THREAD

**Issue by SangYi** [STRML/react-grid-layout#472]
Is there a way return the current number of 'cols' at the time the component renders?

Currently on load, the 'onWidthChange' doesn't fire unless a new breakpoint is triggered.

Or, is there an easier to set a widget to take 75% of the width on the responsive component?

What I'm trying to do is make 2 widgets that take half of the containers width at say lg: md: sm: ,then take the whole width at xs: xxs:

Thanks in advance!
- [ ] Question

**Comment by BradfordMedeiros** [comment]
Seems like an oversight that there is a mechanism to respond to column count changes, but not a mechanism to get the number of columns upon initial mount.  

Seems like onWidthChange needs to be called on componentDidMount.  Need to bypass the check comparing the new props to the old props though, so needs a bit of modification.

**Comment by developer94404** [comment]
If you are using ResponsiveGridLayout, I think upon initial mount the breakpoint is set automatically.  You would then just do something like numCols = this.state.breakpoitns[this.currentBreakpoints]
