### ISSUE TITLE
Unwanted item transition when React component updates

### ISSUE THREAD

**Issue by hepiyellow** [STRML/react-grid-layout#473]
Hi,

I am seeing a gris item transition (200ms) when My React component (which renders `<ReactGridLayout />`) is updated (`componentWillUpdate()` called).

I tried a simple Grid with 2 items (A and B), in a 2 column, 1 row Grid. 
And when a key is pressed,  they change order (A goes to column 2, B goes to column 1).
 When I press a key, I see immediately A in column 2, and I see a transition of item B into column 1 (which takes 200ms, and I can control the transition time with the `react-grid-item` style).

How do I disable this? (without totally disabling transitions)
I mean, I guess I should disable this only when a `componentDidUpdate()` occurred.

Thank,
Erez

**Comment by k4st0r42** [comment]
did you find a solution ?
