### ISSUE TITLE
[Bug] Add notes about custom components to the documentation?

### ISSUE THREAD

**Issue by pixelpax** [STRML/react-grid-layout#483]
This component is EXCELLENT now that I have it working!

I just wanted to mention that I struggled for quite a few hours tracing through the source code trying to render CustomComponent children into a react grid. I'm probably not the only developer swapping out an existing layout component with RGL, I imagine this is a very common situation, and most of us already have self-contained components which we're trying to place in the grid. In hindsight, it's obvious, but I had a very hard time figuring out that custom components _must receive props from parents_ ([issue 397](https://github.com/STRML/react-grid-layout/issues/397)). 

The documentation is already really good for this project, I think an ALL CAPS NOTE about nested custom components would save a lot of people a lot of time-- almost everyone will be putting custom components in one way or another. It might even be worth mentioning that we have two options: wrapping in plain divs or passing props through.  All of the examples seem to work directly with divs, so it didn't even occur to me as a relatively green react user that there might be a difference. It might even be useful to have an example too if you can think of any other nuances to using custom components.

Note that I've tagged this as a bug, because, at least for me, it was a failure in documentation which prevented me from adapting the plugin gracefully. I apologize if my definition of a bug isn't correct, I was on the fence about it.

**Comment by amit-coditas** [comment]
+1 . i just figured it out myself and came here to see if someone else had the same problems.

**Comment by SpOOnman** [comment]
+1

I've found this post to be useful: https://github.com/STRML/react-grid-layout/issues/397#issuecomment-261930222
