### ISSUE TITLE
[Bug] put RGL into a scaled elements then click grid looks weird

### ISSUE THREAD

**Issue by imlgm** [STRML/react-grid-layout#484]
![feb-15-2017 18-47-57](https://cloud.githubusercontent.com/assets/5555305/22971076/688997fe-f3af-11e6-82e9-fd29e6870003.gif)

if I removed the scale style from the parent element then it will be normal. any suggestion to solve the problem?

**Comment by IsaackRasmussen** [comment]
I think at this point its not properly supported but here is a workaround that works okay.

https://github.com/STRML/react-grid-layout/issues/350

**Comment by SnailJason** [comment]
Is it solved?why mine still act like this

**Comment by SnailJason** [comment]
@imlgm how did you solve this problem?
