### ISSUE TITLE
[Question] Floating behaviour

### ISSUE THREAD

**Issue by tarelli** [STRML/react-grid-layout#487]
Is free floating behaviour something planned? 
See this as an example: https://react-tiles.firebaseapp.com/
Thanks!

**Comment by vpezeshkian** [comment]
I'm working on such a behavior, I will open a PR

**Comment by tarelli** [comment]
@vpezeshkian have a look at this as well, might be convenient to reuse? http://mzabriskie.github.io/react-draggable/example/

**Comment by DaveyEdwards** [comment]
Is there a way to do something similar to react-draggable's functionality since this project uses it? or do you need to install it as well? I am also trying to do a floating drag behaviour.

**Comment by dmk255** [comment]
I also am considering to use this package but floating behavior is a must. Is there a way to add a "z-axis" concept?

**Comment by nitesh619** [comment]
@tarelli Is the floating behavior added yet?? any workarounds?
