### ISSUE TITLE
[Bug] Unexpected warning: `Failed prop type: minWidth larger than item width/maxWidth`

### ISSUE THREAD

**Issue by dvoaviarison** [STRML/react-grid-layout#493]
This is my child component
```html
<MyWidget ... layout={{ x: 0, y: 0, w: 5, h: 5, minW: 3 }}>
```

I am getting this warning just because I put **minW: 3**

> Warning: Failed prop type: minWidth larger than item width/maxWidth
>     in GridItem (created by ReactGridLayout)
>     in ReactGridLayout (created by ResponsiveReactGridLayout)
>     in ResponsiveReactGridLayout (created by Measure)
>     in Measure (created by ResponsiveReactGridLayout)
>     in ResponsiveReactGridLayout (created by Dashboard)

When I investigated I discovered that it arrives to  `GridItems.js` with `w=2` (even if I explicitly set it to 3).

**Comment by jeghers** [comment]
+1 - This is happening to me too.  Has anyone learned what is happening here?

**Comment by wzup** [comment]
Same here. 
Any solution?

**Comment by pratik-chakravorty** [comment]
any updates on this yet?

**Comment by MarcDAFrame** [comment]
Anyone found a solution? 

I'm getting a very similar error
```
Failed prop type: maxHeight smaller than item height/minHeight
```

**Comment by nicholaus1** [comment]
Same here, any updates?

**Comment by faizhameed** [comment]
Same here any updates. I have the same issue
```
index.js:1375 Warning: Failed prop type: minHeight larger than item height/maxHeight
    in GridItem (created by ReactGridLayout)
    in ReactGridLayout (created by ResponsiveReactGridLayout)
    in ResponsiveReactGridLayout (created by WidthProvider)
    in WidthProvider (at table-large.jsx:24)
    in CSSTransitionGroupChild (created by TransitionGroup)
    in span (created by TransitionGroup)
    in TransitionGroup (created by CSSTransitionGroup)
    in CSSTransitionGroup (at table-large.jsx:15)
    in TableLarge (at table-leadbox.component.jsx:50)
    in div (at table-leadbox.component.jsx:58)
    in TableLeadBox (at lead-box-container.component.jsx:24)
    in div (at lead-box-container.component.jsx:15)
    in div (at lead-box-container.component.jsx:13)
    in div (at lead-box-container.component.jsx:12)
    in LeadBoxContainer (at App.js:18)
    in div (at App.js:11)
    in App (created by ConnectFunction)
    in ConnectFunction (at src/index.js:11)
    in Provider (at src/index.js:10)
```

**Comment by mikefordweb** [comment]
I am encountering the same issue.

**Comment by WaqqarSuleman** [comment]
Same issue. Has anyone found the solution yet?

**Comment by eamaya2008** [comment]
Same issue. Has anyone found the solution yet?

**Comment by zhanghaifeng213** [comment]
`public static defaultProps = {
    className: 'layout',
    cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 3 },
    rowHeight: 100
  }`

xxs set to be larger than minW

**Comment by radu-dragan** [comment]
I have the same issue, does anyone have a solution for it?

**Comment by siddharth-kaushik** [comment]
This happens when the `width` and `height` of `DataGrid` are not set. Due to which DataGrid collapses and GridItem width becomes less than 1 resulting in this error.

**Comment by subtyping** [comment]
I ran into this (or something similar) and resolved it by explicitly setting minWith = 0, preventing it from ever being larger width/maxWidth (as long as width is not a negative number)

Explicitly set **minWidth = 0** fixed it for me.
