### ISSUE TITLE
[Question] Is it possible to do a ServerStorage?

### ISSUE THREAD

**Issue by MaxJeong** [STRML/react-grid-layout#496]
Save the position of the widgets on the server (i.e. mongodb or amazon web services) and load from it. Looking at the GitHub docs, examples and issues, I didn't find anything relevant so I assume this feature is not implemented yet.

Is there another way to accomplish this then?

**Comment by STRML** [comment]
Syncing any components props to external storage is relatively easy and
definitely outside the scope of the component itself. Simply update parent
state onLayoutChange and sync that anywhere.

**Comment by zaraustra** [comment]
Hi Max, I used this component to build my Admin Panel dashboard.
What I've done is to save each user "layout" in a field in the user record so I'm able to load it as the user log in and restore he's personal "widgets" binding the "block_id" to an hardcoded list of components.
As STRML said, just use the "onLayoutChange" to trigger your DB update query.
