### ISSUE TITLE
CSS Animations (with build script)

### ISSUE THREAD

**Issue by NSinopoli** [STRML/react-grid-layout#50]
Opening a formal issue for the css issue I stumbled across [here](https://github.com/STRML/react-grid-layout/issues/40#issuecomment-89355290).

I did some digging, and discovered that the issue is introduced by replacing `/react/lib/cloneWithProps/` with the `react-clonewithprops` library [here](https://github.com/STRML/react-grid-layout/blob/master/webpack.config.js#L36). As you [mentioned](https://github.com/STRML/react-grid-layout/issues/40#issuecomment-89299271), we can't use `/react/lib/cloneWithProps/`, because it'll just trigger the issue in #40 again. 

I poked around the source of `react-clonewithprops` and discovered [this](https://github.com/jquense/react-clonewithprops/blob/master/index.js#L35). My guess is that this is not exactly equivalent to the (now [deprecated](https://facebook.github.io/react/docs/clone-with-props.html)) `cloneWithProps` call. Facebook recommends using [React.cloneElement](https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement) instead, but I am having some trouble converting the two instances I found.

1) In [react-draggable](https://github.com/STRML/react-draggable/blob/master/lib/draggable.js#L547)
2) In [react-resizable](https://github.com/STRML/react-resizable/blob/master/lib/Resizable.jsx#L63)

Any insight would be tremendously appreciated.

Thank you so much!

**Comment by STRML** [comment]
I mean to convert `react-resizable` to `React.cloneElement`. I have push access to `react-draggable` and I've already updated it (see `0.5.0`).

**Comment by NSinopoli** [comment]
Great! 

I noticed that you previously converted `react-resizable` to `React.cloneElement`, but then undid it (because of problems with `style` and `className`). I tried my hand at it, passing in `style` and `className` manually, but I must be misunderstanding how `React.cloneElement` is different from `cloneWithProps` (maybe it's the way children are handled?).

Thanks again for all of your fabulous work on each of these libraries.

**Comment by STRML** [comment]
Yeah, the issue is that `cloneWithProps` actually properly merges `style` and `className`, but cloneElement does not. But cloneElement properly preserves `key` and `ref`.

I'm going to try converting again as I've been able to get `react-draggable` working properly. I'm building a simple helper that makes `React.cloneElement` behave properly again.

**Comment by STRML** [comment]
Looks like the latest updates I made to `react-draggable` and `react-resizable` have fixed the issues. I'm seeing the proper animations in [the old fiddle](https://jsfiddle.net/69z2wepo/5864/).

Please reopen if you have any other questions about it.

**Comment by NSinopoli** [comment]
Yes! Thank you **so** much! :+1:
