### ISSUE TITLE
Issue with nested RGL and draggable

### ISSUE THREAD

**Issue by hepiyellow** [STRML/react-grid-layout#502]
About what @RiiD wrote in https://github.com/STRML/react-grid-layout/issues/293: 
```
<RGL ... >
  <div> // If you add onMouseDown here react-draggable will override it. You will have to use nested element to capture clicks
    <div onMouseDown={ e => e.stopPropagation() }>
      ...
    </div>
  <div>
</RGL>
```

This doesn't work, because the `e.stopPropagation()` prevents react-draggable from working.
It happens in this `EventPluginUtils.js`:
```
if (Array.isArray(dispatchListeners)) {
    for (var i = 0; i < dispatchListeners.length; i++) {
      if (event.isPropagationStopped()) {
        break;
      }
```

My case is nested RGL with dragging, and when I drag a GridItem of the nested RGL , both RGL start dragging.
I would like to have only the inner RGL drag, so I need to stopPropagation. My GridItems are Custom Components which add a `<button>` child. As @RiiD wrote, if I put my `onMouseDown` event listener on the GridItem, react-draggable will override it, and it will not be called. I experienced that.

So How do I prevent propagation and still have react-draggable work?

**Comment by hepiyellow** [comment]
ok, have a solution.
`react-draggable`'s DraggableCore component can be passed a property `onMouseDown`.
So I suggest adding an `onMouseDown` property to RGL, and it to the GridItem in `ReactGridLayout.processGridItem()`, and in `GridItem.mixinDraggable()` pass that callback to `DraggableCore`.
I tried it, and it worked, and made it possible for me to call `stopPropagation()`  and have nested RGL working with drag.

**Comment by hepiyellow** [comment]
Any comments?

**Comment by gerahimanshu** [comment]
thanks a ton! @hepiyellow . Working perfectly fine.

**Comment by krajasekhar** [comment]
I solved this by having a different className for RGL at each level using the prop `draggableHandle`
