### ISSUE TITLE
What's the plan of "Resizable handles on other corners"

### ISSUE THREAD

**Issue by codTango** [STRML/react-grid-layout#503]
### Feature Request

I'm seeing `Resizable handles on other corners` on the TODO list for over a half year, and it seems still doesn't have such feature. So what's the plan for it?

**Comment by STRML** [comment]
I haven't implemented it yet. Would you like to?

**Comment by codTango** [comment]
@STRML I'd be happy to help if you can point me to where I shall start.

**Comment by STRML** [comment]
See https://github.com/STRML/react-resizable which does the actual resize handle placement and callbacks.

**Comment by codTango** [comment]
interesting, will take a look.

**Comment by iamraffe** [comment]
@codTango Have you had a chance to take a look at this? I def think this is something I would like to add to a current app I'm building so I'd like to be of help.

**Comment by codTango** [comment]
@iamraffe I was thinking to take a look at this, but got sidetracked by other stuff, then I just end up making the resize handler bigger and more visible. But you could go ahead if you want to implement this, I would help if need.

**Comment by emzero** [comment]
It would be awesome if we could have resize handles like this: http://bokuweb.github.io/react-rnd/

I'd certainly donate for it.

**Comment by funkytek** [comment]
Is anyone putting together a PR for this? cc @iamraffe @codTango

**Comment by iamraffe** [comment]
@funkytek I'll have to work on this at some point for a current project, but haven't gotten to that point just yet

**Comment by tginn** [comment]
I need this for a project I am doing as well. If no one else is actively working on it I can try a PR.

**Comment by TrySound** [comment]
@tginn Sure. PR is appreciated.

**Comment by iamraffe** [comment]
@tginn I probably won't get to this until Late Jan-Early Feb so go for it!

**Comment by pingbaohua** [comment]
我想问一下，这个功能实现了吗，拖动角落的其他手柄，改变大小@STRML
