### ISSUE TITLE
V-0.14.3: onLayoutChange called when layout didn't change

### ISSUE THREAD

**Issue by hepiyellow** [STRML/react-grid-layout#504]
I am experiencing calls to onLayoutChange, when the RGL mount (componentDidMount),
although the layout has not changed.
I saw that in version` 0.13.7` you added the `onLayoutMaybeChanged` method, which is supposed to fix it.
But it seems that it doesn't.
I see that the `loads.isEquals` call returns false, for layout arrays.
It fails on the first itemLayout, where the `oldLayout` has the usual `{i,x,y,w,h}` fields,
and the `newLayout` has also these fields: `{...moved, static, minH,minW,maxH,maxW,isDraggable,isResizable}.

**Comment by mnemanja** [comment]
+1

**Comment by stephenrs** [comment]
This one has also bitten me.

**Comment by damiangreen** [comment]
Yes, this is also a problem for me.

**Comment by hardvain** [comment]
Any updates on this? I am also facing this issue>?

**Comment by sondresj** [comment]
A workaround hack for this bug can be found here:
https://codesandbox.io/s/ol94lx21oy (in the ShowcaseLayout.js file).
This sandbox also reproduces the bug and warns the console each time it occurs. 

The workaround works by checking if the oldItem and newItem in the callbacks of onDragStop and onResizeStop are different (using _.isEqual for deep comparison). 
The _layoutCangeWorkaround property cannot reside in the state, as the onLayoutChange callback is invoked in the same callstack as onDragStop/onResizeStop, so unfortunately we have to mutatete it directly. This doesn't have any consequence to the React rendering of the component however, as we don't need to re-render when _layoutChangeWorkaround is modified.

**Comment by OrhanOzkercin** [comment]
I am facing the same issue, `onLayoutChange` method is triggered when the component is first mount.  Is this problem still continuing or am I missing something?

**Comment by hepiyellow** [comment]
I don’t know. I haven’t used this in years. On 2023. Jan 11., at 2:03, Orhan Özkerçin ***@***.***> wrote:﻿
I am facing the same issue, onLayoutChange method is triggered when the component is first mount.  Is this problem still continuing or am I missing something?

**Comment by moazzam-ali** [comment]
Any updates on this?
I'm facing the same issue.

**Comment by mohd-khan09** [comment]
> onLayoutChange

same here
