### ISSUE TITLE
[Feature request] Publish dist/ to npm

### ISSUE THREAD

**Issue by mliszcz** [STRML/react-grid-layout#505]
Hi!

I'm using [rollup](https://github.com/rollup/rollup) to bundle my app. I'd like to load react-grid-layout as an external dependency (window.ReactGridLayout). An UMD module is available (dist/ directory) but it's npm-ignored.

Currently I have two options: either use react-grid-layout as an unmanaged dependency or configure rollup to bundle react-grid-layout with my app (this complicates the build process and requires additional plugin for rollup to handle CJS modules).

How about publishing dist/ directory to npm, like many other libraries do (including react)?

**Comment by adamtaylor13** [comment]
Can we get some feedback on this? Seems kinda silly that it references using `/dist` in the docs, but then lo-and-behold you can't actually use that method using the npm package.

**Comment by SiddarthaAdusumalli** [comment]
Hi, is it possible to take this up? It's still a pain point
Thanks in advance
