### ISSUE TITLE
Feature Request: pass calculated dimensions to children

### ISSUE THREAD

**Issue by mauron85** [STRML/react-grid-layout#506]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [X] Feature Request
- [ ] Question

I understand that with current implementation it might be difficult to implement.

But my suggestion is:
Make ***GridItem*** component pass  height and width to its children.

Motivation:
Currently  ***GridItem***  class sets css dimensions directly, but doesn't propagate height or width to the wrapped child.
As result height or width if needed by child component has to be recalculated directly by the child (using for example react-sizeme). But this calculation can be avoided as GridItem already calculated its dimensions. Good example of child needing exact dimensions is scrollable table using react-virtualized, which is using height and width to render only "visible" rows/cols.

**Comment by torkelo** [comment]
Would be interesting to have version that has a render prop that passed props like height and width to each item. Could be called for each cell in the layout.

**Comment by valtism** [comment]
You can create your own grid item that will pass the calculated width and height to children.

```
function GridItem(props) {
  // RGL passes width and height directly to children as style props.
  const width = parseFloat(props.style.width)
  const height = parseFloat(props.style.height)

  // props.children[0] is our main children. RGL adds the drag handle at props.children[1]
  return (
    <div {...props}>
      {/* Pass width and height to children as render props */}
      {[props.children[0]({ width, height }), props.children.slice(1)]}
    </div>
  )
}
```

You use it like this

```
<GridItem
  key={data.id}
  className={"relative bg-white"}
>
  {({ width, height }) => (
    <XYChart
      title={data.title}
      color={data.color}
      width={width}
      height={height}
    />
  )}
</GridItem>
```

**Comment by valtism** [comment]
@STRML Would something like this be appropriate to provide from the library, either like this or as a hook? (not sure how it would work as a hook)
