### ISSUE TITLE
Support for safari 9 

### ISSUE THREAD

**Issue by larshelg** [STRML/react-grid-layout#509]
The css transforms are working great in safari 9 if I replace/hack the css property transform (directly in the browser) with -webkit-transform.

Is there a way to do this dynamically?

Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [X ] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by STRML** [comment]
This should work out of the box. See https://github.com/STRML/react-grid-layout/blob/master/lib/utils.js#L308 which sets all available transform styles. I believe React may be trimming these, can't recall.
