### ISSUE TITLE
Resize not working with react v15.4.2

### ISSUE THREAD

**Issue by OnlyRefat** [STRML/react-grid-layout#511]
- [x] Question
Thanks for the awesome library.

Followed the github readme. Everything is working fine except the ```isResizable``` feature. 
 
Found this code from your examples:

```
<div class="react-grid-item react-draggable cssTransforms react-resizable" style="width: 192px; height: 70px; position: absolute; touch-action: none; transform: translate(212px, 10px);">
  <span class="text">1</span>
  <span class="react-resizable-handle" style="touch-action: none;"></span>
</div>
```

The <span> tag with class ```react-resizable-handle``` is not generated when i have tried to use on my project and also the ```react-grid-item resizing``` class is not added when i try to resize?

i am confused if this is an issue with react v15.4.2? i have gone through all the issues and did not find anything similar to my issue. 

one thing it works when i try with react v14.6?

**Comment by OnlyRefat** [comment]
I have used preact in this project. which may caused the problem. Solved.

**Comment by mnemanja** [comment]
Hi @OnlyRefat,
I am really interested in hearing what is it that you think it was a problem and how you fixed it? I have the same problem right now. I use `create-react-app`.

I believe it's something else, not the preact problem.

**Comment by OnlyRefat** [comment]
The resize feature in react-grid-layout is provided by the resize module React-Resizable. 
I was using preact. and that was not completable with React-Resizable. I brought back react instead of react and all my problems were gone.

**Comment by mnemanja** [comment]
Thanks for the quick response @OnlyRefat.

I've managed to fix the issue I was having, and I've logged it [here](https://github.com/STRML/react-grid-layout) in case anyone else gets into the same kind of trouble and needs the reference to it.
