### ISSUE TITLE
ResponsiveGridLayout is not updating when changing the height of the widgets

### ISSUE THREAD

**Issue by Princezhm** [STRML/react-grid-layout#514]
Hello guys, 

if have the following code to create a RGL inside of a class called Dashboard:

```
render() {
        return (
            <div>
                <button onClick={this.minimize}>
                    minimize
                </button>
                <ResponsiveReactGridLayout
                    className="layout"
                    breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
                    cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}
                    layouts={this.state.layouts}
                    onLayoutChange={this.onLayoutChange}>
                    {this.getWidgetComponents(this.props.widgets)}
                </ResponsiveReactGridLayout></div>
        );
    }
```

as you can see, it is very simple, but it also has a button called minimize, which as you can tell, it minimizes the widgets.

```
minimize() {
        let layouts = this.state.layouts;
        Object.keys(layouts).forEach(function (key) {
            for (let j = 0; j < layouts[key].length; j++) {
                layouts[key][j].h = 1;
                layouts[key][j].w = 2;
                layouts[key][j].moved = true
            }
        });

        this.setState({
            layouts: layouts
        });
    }
```

this function is the on which minimizes the widgets, you can see I have to loop through the keys (sm, xs, lg, etc) and the throught the widgets, i'm assigning the height and width that I want but the page is not being re rendered.
the strange this it when I hit F5 or refresh the page, everything is minimized, so the process works, but it is not refreshing...

I found that if I hit the button to minimize and then change the width of the browser causing a breakpoint change it will render everything minimized.

if you are wondering, this is the function to create the widgets:

```
getWidgetComponents(widgets) {
        let components = [];
        let that = this;
        Object.keys(widgets).map(function (key) {
            let widget = widgets[key];
            components.push(
                <div key={widget.key}
                     data-grid={{
                                x: that.getWidgetPos(widget).x,
                                y: that.getWidgetPos(widget).y,
                                w: that.getWidgetPos(widget).w,
                                h: that.getWidgetPos(widget).h,
                                minW: that.getWidgetPos(widget).minW,
                                minH: that.getWidgetPos(widget).minH}}>
                    {widget.name}
                </div>)
        });
        return components;
    }
```
note1:  I changed the content of the widget for {widget.name} to have a shorter widget because in my implementation I'm using a panel and larger data.

note2: FYI i'm using the localstoraget and the function getWidgetPos(widget) returns just the pos from the LocalStorage (and I saw that the local storage has the correct data)

note3: my default data (when the position can not be calculated comes from another file)
```
{
        name: 'Settings',
        key: "f", x: 0, y: 16, w: 12, h: 4, minW: 2, minH: 1,
}
```

edit: 
I can add this image, as you can see, all the props from the RGL are in {w=1, h=1} but the widget is taking a lot of space(no, the rowHeight is no the problem)

<img width="1629" alt="screen shot 2017-03-14 at 10 08 07 pm" src="https://cloud.githubusercontent.com/assets/8930664/23929186/03866dd2-0903-11e7-9fcc-007bdfe43d40.png">

**Comment by williamgranli** [comment]
Not sure if key is allowed as identifier for each element in the grid. The examples state that 'i' should be used, e.g. { i: "f", x: 0, y: 16, w: 12, h: 4, minW: 2, minH: 1 }. Just started trying out this lib today though, so might be very wrong. :))
