### ISSUE TITLE
onResizeStop arguments not correct

### ISSUE THREAD

**Issue by eschiebel** [STRML/react-grid-layout#52]
For one, the signature for all the event handlers is undocumented.
Looking at the code for onResizeStop, I believe it should be calling my handler with 
0. the current grid layout
1. the previous layout of the box being resized
2. the new layout of the box being resized
3. null
4. the event
However,` oldL = utils.clone(l)`, so arguments 1 and 2 are always identical.

**Comment by STRML** [comment]
See the bottom of https://github.com/STRML/react-grid-layout#grid-layout-props, this is documented.

Unfortunately I am not caching the initial layout on resize or drag so it can be passed to the callbacks, but it makes sense to save it in state until stop is called. I would happily accept any PR that does so.
