### ISSUE TITLE
Question: editing default props of layout

### ISSUE THREAD

**Issue by Elliryanna** [STRML/react-grid-layout#520]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

Hello to all,
I have a little question:
I'd like to add some features to the layout and at the moment they are stored in own array's.  
This is not realy well, especially if you delete one item of the layout.
Is there anybody who know's where exactly are the default props of the layout object are, because in the ReactGridLayout.js there are around 4 or 5 different layout props.
I use the ResponsiveReactGridLayout module as "expansion" for the basic Grid Layout.

Also editing the "getInitialState" and "onAddItem" changes nothing.
Greetings Elli

**Comment by STRML** [comment]
This is all available [in the source](https://github.com/STRML/react-grid-layout/blob/master/lib/ResponsiveReactGridLayout.jsx#L72). Be sure not to actually modify any of these props (e.g. `Array#splice` et al), clone and modify the clone as to not affect other instances.

**Comment by Elliryanna** [comment]
Hey, 
thank you very much for your fast answer, I will take a look at this and will try it out.
I will be careful! Thanks for the advice :)
