### ISSUE TITLE
Default layout not recognized on render

### ISSUE THREAD

**Issue by williamgranli** [STRML/react-grid-layout#522]
I'm trying to set up a simple grid with two columns on large size and one column on small size. 

On large it should look like this:
ITEM ONE || ITEM TWO

And one small it should look like this:
ITEM ONE
ITEM TWO

However, for some reason, it doesn't recognize the initial x position of item two on large size (x=1). It does however work when I drag it there and the callback on layout change properly displays x=1. What instead happens is that it arranges the items like so:
ITEM ONE || (EMPTY)
ITEM TWO || (EMPTY)

I.e. x=0 for both items.

Here's my code: 
```
/* npm imports */
import React, { PropTypes } from 'react';
import { connect } from 'react-redux';
import { Responsive, WidthProvider } from 'react-grid-layout';
import { createStructuredSelector } from 'reselect';

/* component imports */
import PageWrapper from '../../components/PageWrapper';
import ContentWrapper from '../../components/ContentWrapper';

/* other imports */
import makeSelectDashboardPage from './selectors';

const Grid = WidthProvider(Responsive);

export class DashboardPage extends React.PureComponent { // eslint-disable-line react/prefer-stateless-function
  render() {
    const UPDATE = 'update';
    const DISK = 'disk';

    const sm = [
      {
        i: UPDATE,
        x: 0,
        y: 0,
        w: 1,
        h: 1,
        static: true,
      },
      {
        i: DISK,
        x: 1,
        y: 0,
        w: 1,
        h: 1,
        static: true,
      },
    ];

    const lg = [
      {
        i: UPDATE,
        x: 0,
        y: 0,
        w: 1,
        h: 1,
        static: true,
      },
      {
        i: DISK,
        x: 1,
        y: 0,
        w: 1,
        h: 1,
        static: true,
      },
    ];

    return (
      <PageWrapper>
        <ContentWrapper>
          <Grid
            onLayoutChange={(layout) => console.log(layout)}
            className="grid"
            layout={{ lg, sm }}
            breakpoints={{ lg: 1200, sm: 768 }}
            cols={{ lg: 2, sm: 1 }}
          >
            <div key={UPDATE} style={{ backgroundColor: 'red' }}>
              <h1>Update</h1>
            </div>
            <div key={DISK} style={{ backgroundColor: 'blue' }}>
              <h1>Disk</h1>
            </div>
          </Grid>
        </ContentWrapper>
      </PageWrapper>

    );
  }
}

```

From what I can see I have declared my default layouts according to the specifications (array of objects) and I'm using the same variable to identify the key/id of each grid item. 

Any idea what could be wrong?

Thanks!

**Comment by williamgranli** [comment]
Found the error after hours of pulling my hair out. I sent the prop "layout" instead of "layouts" (plural). Shouldn't there be props validation for that? @STRML 

Thanks for an awesome library btw!

**Comment by natew** [comment]
I'm actually having this problem and also have been trying a ton of variations. It only shows items as being in the first row.

If I drag them around and then go to React console and save the exact layout, then pass it in as a prop, it doesn't work. Tried about 10 different layouts and prop combos.
