### ISSUE TITLE
Unintuitive definition if `margin` (Or wrong documentation)

### ISSUE THREAD

**Issue by hepiyellow** [STRML/react-grid-layout#523]
In the README file the `margin` property is defined as such:
```javascript
// Margin between items [x, y] in px.
margin: ?[number, number] = [10, 10],
```

Looking at the code, and the actual behavior, the margin is **the margin between grid cells**.
So if an item spreads over 2 cells (say h=2), then it's height would include the margins.
Example:
```
rowHeight=50
margin=[0,10]
```
for an item with `h=2`, the actual height would be 110px.

**Comment by STRML** [comment]
Yes, but this must be so; a grid item that spans multiple rows or columns must also span the rowspan/colspan.

**Comment by hepiyellow** [comment]
So maybe just a fix in the README ? 
```
// Margin between grid cells [x, y] in px.
margin: ?[number, number] = [10, 10],
```

**Comment by kumarharsh** [comment]
For anyone still confused, the author has already clarified this many times about why the margin will be added to the height of multi-row items. See the comment here: https://github.com/STRML/react-grid-layout/issues/277
