### ISSUE TITLE
[Question] Responsive grid

### ISSUE THREAD

**Issue by mnemanja** [STRML/react-grid-layout#527]
Hi,
I need some assistance with making the responsive grid remember different breakpoints layouts.
I have tried several approaches, but they don't seem to work.

Here's what I know so far:
1. `layouts` property should contain breakpoints with items objects i.e. `{lg: {w: 2, h: 3, x: 0, y: 0}...}`
2. `data-grid` property should look like this: `{w: 2, h: 3, x: 0, y: 0}`, basically one item.
3. The `width` has to be provided
4. `cols` has to be provided and the breakpoint names should be persisted throughout the layouts and cols properties

What's the correlation between `layouts` and `data-grid`?

In this example, the `data-grid` property has been used together with `layouts` property on the parent.
https://github.com/STRML/react-grid-layout/blob/master/test/examples/8-localstorage-responsive.jsx

In this example, the `data-grid` property has been omitted:
https://github.com/STRML/react-grid-layout#responsive-usage

I'm uncertain on which buttons I should push to make my layout remember the widgets configuration across the breakpoints.

Could you please give me an example on how exactly should the `ResponsiveReactGridLayout` be configured so that this can work?

Thanks.

**Comment by yeou** [comment]
@mnemanja Did you find an answer to your questions?

**Comment by mnemanja** [comment]
@yeou Unfortunately I haven't. We've postponed that feature to a feature release so I'll need it at some point, but at the moment I have no time to invest.

**Comment by vmwchuj** [comment]
From my crude understanding:
In example 8, data-grid "fixes" the width of each div to w=2.  As breakpoints change, the num of cols change. At xss, cols=2, and at this point each div (w=2) will extend to full width.
In the usage example, data-grid is not used. So the grid solely relies on each layout array specified in the "layouts" map, e.g. {lg: [{w: 2, h: 3, x: 0, y: 0}, {...}, {...}, ...], md: [...], ...}

**Comment by mnemanja** [comment]
I'm not working on this anymore (no longer on that project) so I cannot test and confirm any more. Sorry.
