### ISSUE TITLE
How to structure fixed card sizes based on number of rows/columns? 

### ISSUE THREAD

**Issue by ShillyChak** [STRML/react-grid-layout#529]
Hi there! 

I am a BA working with our dev team to leverage your reac-grid-layout library. Wanted to run the following minimum requirements past you to see if you could lend some initial thoughts around this: 

- All cells should maintain the same sizes based on the # of rows and columns of the grid. Once, I create a grid, by default all cells should have the same H/W. Think of opening an excel spreadsheet. (Unfortunately)

- Grid should support all cells in a single fixed view. ie: The size of the grid cell should decrease based on the number of rows/columns selected by the user. 
For example, If a grid has 4 rows and 4 columns, then the standard uniform cell size of h and w will obviously be larger than a grid which has 20 rows and 20 columns, since there is more cards to accommodate in a single fixed view. We do not want to have a scroll view.

- In addition to each cell being the same size based on the rows/columns, the cell should always maintain the same position and never change. 

Any thoughts on how to do this?

**Comment by STRML** [comment]
I wouldn't recommend this library for you if you are looking to maintain the same position and not have them move. It's overkill. RGL's main purpose is draggable, resizable cells.

There are a number of spreadsheet-style components you might find useful, like [this one](https://react.rocks/example/react-spreadsheet). Maybe search around on https://react.rocks a bit to see what you like.
