### ISSUE TITLE
issue when cloning 

### ISSUE THREAD

**Issue by chrisdrackett** [STRML/react-grid-layout#530]
So I'm trying to add a class (or prop) to all the children of my grid similar to suggestions in https://github.com/STRML/react-grid-layout/issues/103

to do this I'm mapping over my children before passing them into ReactGridLayout. 

```js
    children={return React.Children.map(this.props.children, (child) => {
      return React.cloneElement(child, {
        shouldAnimate: this.state.mounted,
      })
    })}
```
The problem that I am running into is that when I do this vs. passing children directly I seem to lose all my layout (set on the ReactGridLayout component).

Am I missing something here? I'm guessing this might be key related, but my understanding is that `React.cloneElement` should keep the key intact.

**Comment by arvindkumarpal** [comment]
@chrisdrackett what was the fix for this , I am running in the same issue. losing  all my layout (set on the ReactGridLayout component).

**Comment by danimaxi54** [comment]
> @chrisdrackett what was the fix for this , I am running in the same issue. losing all my layout (set on the ReactGridLayout component).
> 
> my code
> 
> ```
>  {
>  React.Children.map(this.props.children, (child) => {
>       return React.cloneElement(child, {
>         newProp: "red",
>       })
>     })
> }
> ```

Hey! Did you solve this?

**Comment by basickarl** [comment]
Still not fixed?
