### ISSUE TITLE
Anyway to do auto expand?

### ISSUE THREAD

**Issue by whitneyland** [STRML/react-grid-layout#531]
Is there a straightforward approach to achieving the auto-expand functionality shown in this demo?
http://dsmorse.github.io/gridster.js/demos/expandable-widgets.html

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [**X**] Question

**Comment by STRML** [comment]
Could be possible; add `mouseenter`/`mouseleave` handlers keyed by the index of each grid item and use that to regenerate the layout. You might be able to use some CSS transforms to animate it smoothly. I don't know how well it would work and I don't plan to officially support it in-module, but if you have success it could make a nice demo.
