### ISSUE TITLE
Negative Positioning When Using Non-Integer Grid Units

### ISSUE THREAD

**Issue by DonnyLi** [STRML/react-grid-layout#535]
- [x] Bug (or documentation error)
- [ ] Feature Request
- [ ] Question

There's a _potential_ bug or documentation error with the positioning of the grid items.

According to the Grid Layout Props, layout is an array of objects with this format:
```
// Layout is an array of object with the format:
// {x: number, y: number, w: number, h: number}
```

Seeing that there's nowhere in the usage docs that specifically mention to use integer values, I started using non-integer values with positioning and heights.

The bug I ran into happens when the y value is between 0 and 1. In the `compactItem` function inside `utils.js` we can see the following code: 

```
// Move the element up as far as it can go without colliding.
while (l.y > 0 && !getFirstCollision(compareWith, l)) {
    l.y--;
}
```

This can actually cause the y value to dip below 0 and cause the grid item to break out of the grid layout area.

A possible solution I see here is either do a `l.y = Math.max(l.y, 0)` check after this line or update the usage docs to specifically mention using integer values for grid layout.

Thanks for your time and making this layout system!

**Comment by FredFuras** [comment]
I noticed this was happening to me too. A simple Math.round() on any heights I was using solved it, but good to know.

**Comment by kirandash** [comment]
Any update on this please. Even I am facing the same issue. The item is getting positioned with negative y value.
