### ISSUE TITLE
Is it possible to have overlay element

### ISSUE THREAD

**Issue by tianhaoz95** [STRML/react-grid-layout#537]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [x] Feature Request
- [ ] Question

I am working on a workshop panel. react-grid-layout has been great so far. I am thinking that if there is a way to overlay elements.

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by fedwu** [comment]
Excuse me ,I have the same problems with you, have you achievede the goal?

**Comment by tianhaoz95** [comment]
no, I think it is impossible unless you stack each element with its own grid.

**Comment by fedwu** [comment]
thank you ,I will try
