### ISSUE TITLE
[Question] Why does my grid rerender every time i move an item?

### ISSUE THREAD

**Issue by tilds** [STRML/react-grid-layout#541]
Can someone explain what I am doing wrong here: https://jsfiddle.net/p2v6azyp/
Every time i drag and drop an item, the whole grid re-renders and animates.
The code is copied from the example here: https://strml.github.io/react-grid-layout/examples/7-localstorage.html which doesn't behave like this.
I suspect i have overlooked something when i coverted to ES6 but I cant figure out what it is.

FYI the webpackbin you are linking to appears to have been moved:
 (http://www.webpackbin.com/EJF48h_rz)

**Comment by sabarnix** [comment]
Did you figure out why it was happening?
