### ISSUE TITLE
layout not rendered properly- i have left menu when i opend menu layout moving to right and not adjusted properly. Please help us

### ISSUE THREAD

**Issue by Viswanath588** [STRML/react-grid-layout#544]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [x] Bug
- [ ] Feature Request
- [ ] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by STRML** [comment]
I have no idea where to even start with this issue. This is not application support, this is for reporting bugs. If you can't take the time to tell me what the bug even is, I certainly can't help you.

**Comment by pkibbey** [comment]
At a guess, I'd say that the basic widthProvider is not being triggered because an element is resizing, instead of the window.

Use a different widthProvider like react-size me and I have a feeling this will fix your issue.

And I agree, this is not a bug, but a question.

**Comment by vibhor-mungee** [comment]
Facing similar issue, I have a left menu when I open it RGL is moved to the right but doesn't resize. Any idea how to fix this?
