### ISSUE TITLE
[BUG] Type errors in WidthProvider.jsx when using with latest version of Flow

### ISSUE THREAD

**Issue by matthewbpt** [STRML/react-grid-layout#545]
- [x ] Bug
- [ ] Feature Request
- [ ] Question

When using flow version v0.41.0+ and including react-grid-layout in the project, you get type errors on this line

https://github.com/STRML/react-grid-layout/blob/master/lib/components/WidthProvider.jsx#L50

```
 49:     this.setState({width: node.offsetWidth});
                                    ^^^^^^^^^^^ property `offsetWidth`. Property cannot be accessed on possibly null value
 49:     this.setState({width: node.offsetWidth});
                               ^^^^ null
```

because of the updated internal React libdef https://github.com/facebook/flow/releases/tag/v0.41.0

> The internal React libdef for findDOMNode has been updated to include null in its return-type now (since this function can, indeed, return null).

 Changing to method to this would fix the issue:

  ``` javascript
onWindowResize = (_event: ?Event) => {
    if (!this.mounted) return;
    const node = ReactDOM.findDOMNode(this); // Flow casts this to Text | Element
    if (node !== null && node instanceof HTMLElement) this.setState({width: node.offsetWidth});
  }
```

**Comment by STRML** [comment]
@matthewbpt I believe you are using an older version of the library. The `if (node instanceof HTMLElement)` check is enough to also check if it is null, and there are not errors thrown in `master` or the latest release.
