### ISSUE TITLE
Getting layout[i].x === NaN when onLayoutChange is called

### ISSUE THREAD

**Issue by ThePainnn** [STRML/react-grid-layout#55]
Hi,

I copied your basic example, putting my own layout with draggable and resizable to true (super simple layout: 4x4 grid with width and height to 1). Everything render fine at the first run, but when I click on an item to drag it, onLayoutChange get called and the layout get mess up. I've noted that I receive NaN on the x value of the item I clicked on. If i ignore this, it will never happen again, but it's kind of glitchy.

Also, I never see the actual resize icon at the lower right corner, I'm I missing something in the CSS?, I've copied most of your example.

Thanks

**Comment by jeaye** [comment]
@ThePainnn Did you resolve this? I'm seeing the same exact issue now.

**Comment by ThePainnn** [comment]
Sorry no. I sto investigating this issue since I also had some serious performance issue when combining it with D3 charts content.

I've change my grid to gridstack.js (JQuery) which needed more work to make it work with React, but got great performance without

**Comment by jeaye** [comment]
I found that this was due to not specifying the `width`, `cols`, and other properties (shown in the examples) properly. For those finding this in the future, compare your code against the examples and make sure you didn't leave any properties out.
