### ISSUE TITLE
How are people handling the sizing of the content within items?

### ISSUE THREAD

**Issue by dadamssg** [STRML/react-grid-layout#550]
I see the gif from BitMex and everything looks sized so perfectly. I try to create some simple markup for the interior of an item and I run into overflow when the grid breaks into a new layout. How are people typically managing this? Hopefully this is a common problem with a common solution. 

Looks good now
![screen shot 2017-04-28 at 11 35 57 am](https://cloud.githubusercontent.com/assets/881986/25538083/e3b88298-2c06-11e7-8012-0f172468d79c.png)

Shorten the width of my browser window and i get overflow
![screen shot 2017-04-28 at 11 37 07 am](https://cloud.githubusercontent.com/assets/881986/25538130/0dee76da-2c07-11e7-9d71-7e5fb0dbe486.png)

**Comment by STRML** [comment]
This is more of a general CSS problem. You'll want to use fluid widths, maybe flexbox and flex-wrap.

**Comment by aditya-padhi-kbl** [comment]
Hi @dadamssg how did you solve this issue.
