### ISSUE TITLE
Do you support snap on resize and drag?(like this    resizeGrid: [number, number];)

### ISSUE THREAD

**Issue by edwardfhsiao** [STRML/react-grid-layout#552]
- [ ] Bug
- [ ] Feature Request
- [x] Question

I would like to have an effect of snapping to the certain grid point when resizing and dragging.

For instance, 1 and 2 combined.

1, the "I snap to a 50 x 50 grid" example of http://mzabriskie.github.io/react-draggable/example/ 
2, the "Resizable box that snaps to even intervals of 25px." of https://strml.github.io/react-resizable/examples/1.html

Thanks in advance.

**Comment by mustefa** [comment]
Hey, did anything happen with this? @edwardfhsiao what did you end up doing?

**Comment by edwardfhsiao** [comment]
@mustefa absolutely nothing at all
