### ISSUE TITLE
RTL Layout

### ISSUE THREAD

**Issue by dodzin** [STRML/react-grid-layout#557]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [x] Feature Request
- [ ] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.
Hi.
Are there any plans to support RTL layout?

**Comment by STRML** [comment]
This is not planned for this version. See #346 for what might come next in a pluggable architecture.
