### ISSUE TITLE
onLayoutChange triggered by componentWillReceiveProps

### ISSUE THREAD

**Issue by TheLudd** [STRML/react-grid-layout#558]
- [X] Bug
- [ ] Feature Request
- [X] Question

Hello. I see that there are a lot of issues regarding `onLayoutChange` but I did not find anyone directly addressing this so I am asking...

I can see from the [code](https://github.com/STRML/react-grid-layout/blob/f3e4a57766707e87886588cf2c0fb267ce33207c/lib/ReactGridLayout.jsx#L193) that `onLayoutChange` is triggered by `componentWillReceiveProps` and this causes some issues for us.

In our listener for `onLayoutChange` we assume that the user has moved or resized an element and we therefore send an update request to our backend. However, sometimes we also update the props programatically with a new layout. This again triggers `onLayoutChange` and a request to our backend that the user has made a change even if it is not so. 

Is the behavior above intended or could it be considered a bug?
Either way, we need a way to determine when the user has made a change manually. Is there any way to go about it with the current implementation?

**Comment by stevewillard** [comment]
@TheLudd I'm running into the exact same issue. Did you find a workaround for this?

**Comment by TheLudd** [comment]
@stevewillard We solved it in our app by setting a timeout in the component that wraps the grid layout. 

Before we change the props on the grid layout we set a variable that indicates that the listener should ignore any calls from `onLayoutChange`. Then we change the props and set a timeout to reset that variable. 
It works but it does not feel like an optimal solution.

**Comment by stevewillard** [comment]
@TheLudd Ah, nice.

I ended up with a slightly different solution. Instead of relying on `onLayoutChange`, I just sync a change when either `onResizeStop` or `onDragStop` happens.

**Comment by eric-burel** [comment]
Note that `onResizeStop` and `onDragStop` won't give you the full layouts in Responsive mode, as `onLayoutChange` would do.

**Comment by jflayhart** [comment]
I also have this issue, and it was quite infuriating. `onLayoutChange` was sending OLD layout to my dispatch chain and ultimately the server request saved the wrong layout; this therefore overwrote the selected dashboard's responsive layout config with the previous one. Basically, the layout would never be able to save correctly when switching layouts around (AKA dashboards).

Here was my workaround, which seems to be working OK for now (as opposed to doing the save event inside `onLayoutChange`):
```
onLayoutChange(layout, layouts) {
    // this fires too many times and unreliably when switching between dashboards, so we have to build our own dashboard layout
    // https://github.com/STRML/react-grid-layout/issues/558
    this.setState({ layout, layouts });
  }

  onWidgetLayoutChange(item) {
    const { dashboard, updateDashboard } = this.props;
    const { currentBreakpoint, layouts } = this.state;
    // build our own dashboard layout
    const dashLayout = {
      ...layouts,
      [currentBreakpoint]: item,
    };
    updateDashboard(dashboard.id, { layout: dashLayout });
  }
```

**Comment by shprink** [comment]
@jflayhart thanks I ended up doing something similar to you but I set `currentBreakpoint` and `layouts` as class properties instead of state to avoid unecessary rerenders
