### ISSUE TITLE
RowHeight not working as expected

### ISSUE THREAD

**Issue by dekkofilms** [STRML/react-grid-layout#559]
Please mark the type of this issue:

- [x] Bug
- [ ] Feature Request
- [x] Question

I have set my rowHeight in the ResponsiveReactGridLayout to 70, and the height of one of my elements right before the last has a height of 5 ... so I am expecting 350 + 10 for the margin that I'm reading in the other issues, so 360 total.

But right now the height of that draggable item is 390. Am I misunderstanding how rowHeight works?

Here is the specific key item below, and my other question is ... is it a problem to have a set height inside of the draggable item children? (seen below in the div with `styles.dashboardBody`

```
<div key={'g'}>
  <div style={styles.card}>
    <div style={styles.dashboardHeader}>
      Trending Searches
      <span className="dragHandle" style={{cursor: 'move'}}>
        <FontAwesome
          border={false}
          name="align-justify"
          style={{color: 'white'}}
        />
      </span>
    </div>
    <div style={Object.assign({}, styles.dashboardBody, {padding: 30, height: 270, backgroundColor: 'white'})}>
      {!this.state.gettingTrending ?
        <div>
          {this.state.trendingSearches.length > 0 ?
            <div>
              {this.state.trendingSearches.slice(0, 5).map((item, index) => (
                <p key={index}>{item.term}</p>
              ))}
            </div> :
            <div>
              <p>Nothing found.</p>
            </div>
          }
        </div> : <div><p>Fetching...</p></div>}
    </div>
  </div>
</div>
```

And here is one of the layouts I'm using:

```
lg: [
  {i: 'a', x: 0, y: 0, w: 4, h: 3, isResizable: false}, //net profit
  {i: 'b', x: 4, y: 0, w: 4, h: 3, isResizable: false}, //orders made as of tday
  {i: 'c', x: 8, y: 0, w: 4, h: 5, isResizable: false}, //average mobile users

  {i: 'd', x: 0, y: 3, w: 8, h: 5, isResizable: false}, //recent order graph
  {i: 'e', x: 8, y: 5, w: 4, h: 3, isResizable: false}, //orders as of yesterday

  {i: 'f', x: 0, y: 8, w: 6, h: 5, isResizable: false}, //trending products
  {i: 'g', x: 6, y: 8, w: 6, h: 5, isResizable: false}, //top searches

  {i: 'h', x: 0, y: 13, w: 12, h: 5, isResizable: false}, //order history
],
```

And here is a dev tools screenshot for further clarity:

![screen shot 2017-05-17 at 2 22 32 pm](https://cloud.githubusercontent.com/assets/14862852/26171974/64ccc3f8-3b0c-11e7-8c71-0b17772769af.png)

**Comment by STRML** [comment]
Hi - in order for all elements of different row heights to align, (height -
1)*margin is applied to the row height.

**Comment by dekkofilms** [comment]
@STRML Interesting, thanks for the response. Would there be any way to override that formula, or another recommended solution for having the issue of too much space in between your rows?

**Comment by STRML** [comment]
There's no other way to do it, if you want margin. Otherwise the rows would end up haggard. You could just not use `margin` at all.

**Comment by dekkofilms** [comment]
Ok ... i'll have to look into this a bit further. I do like the margin, and it is generally working ... it's just that second to last row that has been bothering me ha. I'll share the full layout, maybe I'm not doing something correctly with the layout object or something. 

![screen shot 2017-05-17 at 4 29 24 pm](https://cloud.githubusercontent.com/assets/14862852/26177159/36609834-3b1e-11e7-826e-9475add96a48.png)

**Comment by dekkofilms** [comment]
Anyways thanks @STRML  for the insight to rowHeight ... it's definitely good to know that extra little formula calculating that total height. Helped with some confusion.
