### ISSUE TITLE
Set the height of RGL when maxRows is given

### ISSUE THREAD

**Issue by EmrysMyrddin** [STRML/react-grid-layout#565]
- [ ] Bug
- [x] Feature Request
- [ ] Question

It could be great if the height RGL could be calculated when the `maxRows` prop is given.

You can view a draft on my fork https://github.com/EmrysMyrddin/react-grid-layout/tree/fix/height_maxRows
In this draft, the height is calculated with `maxRows` only if `autosize` is off and `maxRows` is given. 

If this behaviour is acceptable, I can make a pull request.

**Comment by STRML** [comment]
I understand why you may want to do this, but the name of the prop is `maxRows`, not `rows`, so it is unintuitive to stick to a certain count. Thanks for the proposal though.
