### ISSUE TITLE
Detect which column a div is on

### ISSUE THREAD

**Issue by jimmybnguyen** [STRML/react-grid-layout#566]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [X] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

Working on a thing to help roommates coordinate chores. 

![alt](http://i.imgur.com/VQeoRSZ.png)
Is there a way to see which column a particular chore is on? For example, I have three chores under the "deck" column/column 0, and five chores under the "sunday" column/column 1. I would like to be able to detect which chore is assigned to which day based on the column number. 

Thanks!

**Comment by STRML** [comment]
Yes, use the callbacks as described [here](https://github.com/STRML/react-grid-layout#grid-layout-props). In particular, you can listen to `onLayoutChange` and correlate an item's `i` (which is an id) to its position.
