### ISSUE TITLE
Upgrade react-resizable, prop-types warning

### ISSUE THREAD

**Issue by tibotiber** [STRML/react-grid-layout#567]
This is a question.

I'm getting a `Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`. This comes from `react-resizable` which has switched to `react-props` and requires a dependency upgrade.

Is there a plan to upgrade this dependency? Are there blockers?

Thanks for your excellent work by the way :)

**Comment by STRML** [comment]
You need to update your sub-dependencies. Remove the module then re-install it. This will download new versions of subdeps, including resizable.

**Comment by tibotiber** [comment]
Perfect! Thank you for the super fast help.
