### ISSUE TITLE
Event where we have a collection of changed panels (items) and currentBreakpoint

### ISSUE THREAD

**Issue by pinkynrg** [STRML/react-grid-layout#569]
- [x] Bug
- [x] Feature Request
- [ ] Question

It happens that if I'm dragging and dropping an item that changes the position of other items I have no way of knowing which are the other items that changed position. This feature would be very handy to have in order to know whenever I need to update size/position of items on database (where traffic matter). 

Currently I see the package has a onLayoutChange that returns current updated layout and current updated layouts collection. Here though there is no way to know for sure which is the current breakpoint.

the package also has onDragStop and onResizeStop, where we have current layout, oldPanel, newPanel. Unfortunately here I don't have list of passively moved items.

**Comment by STRML** [comment]
You should be comparing the old and new layout on your own, I don't see why the library should have to provide that. Each layout item is uniquely identified.

As for the breakpoints, the first argument to `onLayoutChange` in RRGL is the current layout. You could easily do an identity check to figure out which is which, or just listen to `onBreakpointChange` and store it.

**Comment by pinkynrg** [comment]
Thanks. I ended up doing something like this, hope this is more or less what you meant:

```javascript
  onDragStop(layout) {
    this.updatePanel(layout); 
  }

  onResizeStop(layout) {
    this.updatePanel(layout);
  }

 updatePanel(layout) {
    // loop through all panels with updated x,y,w,h
    layout.forEach(newPanel => {
      // loop all the panels saved in local state
      this.props.dashboard.layouts[this.props.dashboard.size].forEach((oldPanel) => {
        // check if the 2 panels about to be compared are the same ones 
        if (oldPanel.i == newPanel.i) {
          let needToSave = false;
          // for every value check when at least one changes
          ["x","y","h","w"].forEach((variable) => {
            // whenever one changes set needToSave = true
            if (oldPanel[variable] != newPanel[variable]) {
              needToSave = true;
            }
          });
          // if need to save call update API for that panel
          if (needToSave) {
            let panel = {};
            panel[this.props.dashboard.size + "_x"] = newPanel.x
            panel[this.props.dashboard.size + "_y"] = newPanel.y
            panel[this.props.dashboard.size + "_h"] = newPanel.h
            panel[this.props.dashboard.size + "_w"] = newPanel.w
            this.props.updatePanel(newPanel.i, panel);
          }     
        }
      });
    });
  }
```
