### ISSUE TITLE
Typescript definition file for react-grid-layout

### ISSUE THREAD

**Issue by shadowfax92** [STRML/react-grid-layout#57]
Hi,
Does anyone here created a d.ts file for react-grid-layout?

**Comment by huodon** [comment]
Here  https://gist.github.com/huodon/b73962bf606a28913e0c

But it seems that some error. 

```typescript
import * as ReactGridLayout;

console.log(ReactGridLayout); // This not a ReactComponent. 

console.log(ReactGrideLayout.Responsive); // is valid

```

**Comment by erfangc** [comment]
@huodon Works fine for me, weird that I didn't even need the legacy cjs import syntax of `import ReactGridLayout = require('react-grid-layout');`

What does your `tsconfig.json` file look like?

mine is:

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es3",
        "noImplicitAny": false,
        "sourceMap": false
    },
    "exclude": [
        "node_modules",
        "jspm_packages"
    ]
}
```

the transpiled ES3 looks like:

```js
var ReactGridLayout = require('react-grid-layout');
console.log(ReactGridLayout);
```

**Comment by erfangc** [comment]
@huodon btw, there are compilation errors in the definition file, specifically, we `React.Component` and `React.ReactElement` etc needs to be parametrized i.e. replace `React.Component` with `React.Component<T>`

**Comment by STRML** [comment]
We now have Flow typing - please reopen as a PR if you have a `.d.ts` you'd like to contribute.
