### ISSUE TITLE
lockAspectRatio in Grid Item

### ISSUE THREAD

**Issue by thiennam1311** [STRML/react-grid-layout#570]
- [ ] Bug
- [x] Feature Request
- [ ] Question
Can I use `lockAspectRatio` in ResponsiveReactGridLayout like [react-resizeable](https://strml.github.io/react-resizable/examples/1.html)??

**Comment by STRML** [comment]
No, this is not supported. There is not yet a way to pass properties directly to the draggable or resizable implementations. PR welcome if you have the time.
