### ISSUE TITLE
Fading in/out grid items on add/remove (CSSTransitionGroup?)

### ISSUE THREAD

**Issue by nwlieb** [STRML/react-grid-layout#571]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

Is there any way to use CSSTransitionGroup from [reactjs/react-transition-group](https://github.com/reactjs/react-transition-group) on the grid items? I currently cannot do this because RGL expects an array of items as children so I cannot wrap them in a CSSTransitionGroup container in order to transition them.

The use-case is to fade the items in and out on addition and removal, and there is no other way as far as I can see..

Thank you for the great library!

edit: once **facebook/react#2127** is resolved in react 0.16 an array of elements could be rendered from the ReactGridLayout component, then wrap it in the CSSTransitionGroup component... Thoughts?

**Comment by STRML** [comment]
At this time I don't have any plans to support this, but I am hoping that in RGL v2 the plugin system will allow it. I'll add a note to #346.
