### ISSUE TITLE
Drag element onto grid

### ISSUE THREAD

**Issue by webchaz** [STRML/react-grid-layout#572]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [X] Question

Is it possible to drag an outside element into the grid? As oppose to just adding a new item to state by clicking a button as in the add/remove example.

Thanks!

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by STRML** [comment]
No. It would need to be in the React tree to begin with. That kind of interaction would only be possible with direct DOM manipulation i.e. jQuery.
