### ISSUE TITLE
drag multiple

### ISSUE THREAD

**Issue by matt-erhart** [STRML/react-grid-layout#574]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x ] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

Is there currently a way to drag multiple boxes? If not, could I get a bit of guidance on how to add this feature?

**Comment by Eatwhiterabbit** [comment]
hi, have u figure out a way to drag multiple items now? looking forward to ur answer
