### ISSUE TITLE
RGL dosn't work with react component

### ISSUE THREAD

**Issue by Maybe009** [STRML/react-grid-layout#576]
I have two files,that WorksBox.js wraps WorksCards.js.
**WorksBox.js**

`import WorksCard from './WorksCard';
```
<ResponsiveReactGridLayout className="layout" 
          breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
          cols={{lg: 12, md: 12, sm: 12, xs: 4, xxs: 2}}
          autoSize={false}
          rowHeight={250}
          onResizeStop={this.ItemCallBack}
         >
          <WorksCard key="d"/>
          <div key="c"  data-grid={{x: 1, y: 0, w: 6, h: 2}}>test</div>
</ResponsiveReactGridLayout>
```

**WorksCard.js**

```
return <div key="b" data-grid={{x: 0, y: 0, w: 6, h: 2}}>test</div>
```

![image](https://user-images.githubusercontent.com/13706726/27028994-266de348-4f99-11e7-8286-50d327a8e1ad.png)

Did i do sth wrong or it acturlly can not use like this.

**Comment by nickswope** [comment]
the data-grid attribute has to be on a direct child of the grid, so move the data-grid attribute from WorksCard.js to <WorksCard key="d" data-grid={...} />

it took me way too long to figure that out

**Comment by Maybe009** [comment]
@nickswope  Really thx . It really do helps me a lot,and i solved it by wrap WorksCard with div like this.`<div key="d" data-grid={...} <WorksCard/> </div>`.

**Comment by the-noob** [comment]
@STRML had the same issue and the only workaround was to wrap my component in a div as @Maybe009 suggested.
Are we missing something ? 
If not, I feel it should be added to the docs (I don't mind creating a PR)

**Comment by jflayhart** [comment]
I got this working per @Maybe009 suggestion, but also using bootstrap Cards, and followed what was suggested in #219. Not very BS friendly, but this plugin saved me so much time from rolling my own and also used in conjunction with ReactDnD. Thanks!

**Comment by rscott78** [comment]
I have the same focus problem that @jflayhart mentioned. Did you find a fix for it?
