### ISSUE TITLE
Is there a way to have a grid item with a auto height?

### ISSUE THREAD

**Issue by mhanger** [STRML/react-grid-layout#580]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [x ] Feature Request
- [ ] Question

I have a chart that can have a variable height, but how do I make a grid item for it that will expand in height? There doesn't seem to be a H: auto type functionality.

**Comment by Subhash9325** [comment]
i'm not sure but in my opinion answer is Nope... cause right now we have only width-provider  which will change handle our children containers a/c to our widths. So for auto height u have to build JSX file  similar way u can refer :  node_modules/react-grid-layout/build/components/WidthProvider.js

**Comment by Ajayghoshm** [comment]
Does this have a proper solution?
