### ISSUE TITLE
Onclick of grid item is triggering onresizestop in Griditem or onlayoutchange , why is it so, what needs to be done to avoid so

### ISSUE THREAD

**Issue by sourabhlk** [STRML/react-grid-layout#582]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by Subhash9325** [comment]
Even i want to know the answer!!
