### ISSUE TITLE
Set space between grid items (without changing size of grid items)

### ISSUE THREAD

**Issue by oyshan** [STRML/react-grid-layout#583]
- [X] Bug
- [ ] Feature Request
- [X] Question

Is there a way to set the space (margin) between the grid items (in pixels) without changing the size of the grid items? One should think that margin is applicable for this, but changing the margin also changes the size (width and height) of the grid items, which is unfortunate.

**Comment by STRML** [comment]
Just increase the size to compensate.

**Comment by oyshan** [comment]
Thansk for your reply! :) I'm sure this is a stupid question, but how do I do that?

E.g. if I change the margin from [10,10] to [0,0] or [13,13], what should be increased/decreased to avoid changing the size of the grid items?

Grid setup:
* breakpoints = { lg: 768, sm: 0 }
* cols = { lg: 72, sm: 1 }
* rowHeight = {10}

A grid item's layout can be e.g.:
* h:10
* minH:2
* minW:4
* w:24
* x:0
* y:0

**Comment by Subhash9325** [comment]
surely, you can put x and y values such that u can generate minimum gap b/w them.... i hope this will solve ur issue but yes this will affect on container's width and height !! but still u can set your data-grid in such way that u will have desire spaces b/w ur boxes....

**Comment by vmwchuj** [comment]
My hack is to set rowHeight to 0, and let the margin values alone added to the item height.

E.g. let's say spacing among items is 12px.  react-grid-layout will compute the height to be:
rowHeight * h + margin * (h - 1)

So setting rowHeight to 0 will let margin alone contribute to the actual height.

**Comment by gaurav-pantelwar** [comment]
> Thanks for your reply! :) I'm sure this is a stupid question, but how do I do that?
> 
> E.g. if I change the margin from [10,10] to [0,0] or [13,13], what should be increased/decreased to avoid changing the size of the grid items?
> 
> Grid setup:
> 
> * breakpoints = { lg: 768, sm: 0 }
> * cols = { lg: 72, sm: 1 }
> * rowHeight = {10}
> 
> A grid item's layout can be e.g.:
> 
> * h:10
> * minH:2
> * minW:4
> * w:24
> * x:0
> * y:0

Hi @oyshan 
Did you get any success on this issue?

> * [x]  Bug
> * [ ]  Feature Request
> * [x]  Question
> 
> Is there a way to set the space (margin) between the grid items (in pixels) without changing the size of the grid items? One should think that margin is applicable for this, but changing the margin also changes the size (width and height) of the grid items, which is unfortunate.

Hi @oyshan 
Did you get any success on this issue?
