### ISSUE TITLE
how can I use both horizontal and vertical compacting

### ISSUE THREAD

**Issue by uc-rpr** [STRML/react-grid-layout#585]
![img1](https://user-images.githubusercontent.com/25339883/27720362-1254f1f8-5d0e-11e7-819a-7d361e3ecb17.png)
![img2](https://user-images.githubusercontent.com/25339883/27720365-19a58940-5d0e-11e7-8040-85f3bfbf3d55.png)

Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [ ] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by uc-rpr** [comment]
Please give the solution fast.

**Comment by jackharding** [comment]
I'd like to explain the behaviour that I'm after, as I think it's the same as OP.

![Screen recording](https://media.giphy.com/media/6baQjtfJrPTHo0AxD7/giphy.gif)

In the example above, I would like for the blue and green squares to swap places. If there are three items, I would like them to only be able to move between those 3 positions, not the bottom right. I'd also not want them to be able to move to a new row, under the blue.

After reading the docs and checking out the demos, it looks like this isn't currently possible? Apologies if I've overlooked something.

**Comment by nitesh619** [comment]
Maybe this can help to achieve the required behaviour
https://github.com/STRML/react-grid-layout/issues/1100#issuecomment-583741129
