### ISSUE TITLE
How to drag and drop between two grids or from outside the grid (dashboard)

### ISSUE THREAD

**Issue by razvantomegea** [STRML/react-grid-layout#586]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by razvantomegea** [comment]
It seems this question was already mentioned
https://github.com/STRML/react-grid-layout/issues/459

**Comment by daynin** [comment]
@razvantomegea we added an ability to drag some elements from outside of the grid
