### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by dmoskovtsov** [STRML/react-grid-layout#587]
- [✅ ] Question

Hi, 
Is this project alive? Seems like there is lot's of open pull requests and very few changes in code lately. 
Thanks

**Comment by STRML** [comment]
It's alive in the sense that I am using it in production, as are a few other organizations, but it is not actively being improved or developed at this time as my day job now takes up nearly *all* my time. See #573.

**Comment by STRML** [comment]
Closing in favor of #573.
