### ISSUE TITLE
Click to add items on empty space in the grid layout, is this supported?

### ISSUE THREAD

**Issue by bytewiz** [STRML/react-grid-layout#588]
- [x] Feature Request (maybe)
- [x] Question

So the question is: is it currently possible to track click events on the layout / grid where there is no items positioned?

My idea is to be able to click on an empty space in the grid system and add an item to the grid layout.

is this supported in anyway or do I have to PR my way out of this challenge?

I guess a "hack" could be to overlay all the empty space with grid items which handles the click event though would like something more lean if possible 👍 

Thanks in advance!!!

**Comment by dmcfarland930** [comment]
Came to this board looking for this exact request.

**Comment by STRML** [comment]
That's surely something you could implement on your own (set an event listener on your grid items and the grid itself, check if the same event bubbles through them or not). It is out of the scope of this project.
