### ISSUE TITLE
Slow drag on svg element

### ISSUE THREAD

**Issue by ThePainnn** [STRML/react-grid-layout#59]
Hi,

I've been using the grid-layout to display a grid of svg elements representing various metrics. Each grid element contain a button for options and the svg element which fill the remaining space. If I click and drag a grid element it can be fast or very slow. To drag if I click on my button it's fast and responsive, but when I click on my svg element it's suddenly very slow (even if my svg element is just an empty white rectangle of 300x300 pixels).

Any idea on what's causing the sudden drop in performance?

Thanks a lot!

**Comment by STRML** [comment]
Could you post a jsfiddle?

**Comment by ThePainnn** [comment]
No problem... I'll try as soon as I can (my work schedule is rather super full right now)

**Comment by ThePainnn** [comment]
It's almost an exact copy of my code. Except that I load more css and dependence (which I removed just to test it). Unfortunately, can't reproduce it...

https://jsfiddle.net/7aco26pq/

I profiled it with chrome profiler and I get very strange result.

![dragging_svg](https://cloud.githubusercontent.com/assets/12285830/7773064/f8c980de-006f-11e5-875e-7af47e87a47d.png)
![dragging_button](https://cloud.githubusercontent.com/assets/12285830/7773067/fa854a84-006f-11e5-86c9-4f81bd99ad99.png)

When dragging svg, there almost nothing going on in the graph compare to dragging a button. All the processing end up in the other section.

In the profiler tree view:

![dragging_svg_treeview](https://cloud.githubusercontent.com/assets/12285830/7773147/9e452ebe-0070-11e5-88b1-a2136dccfee0.png)
![dragging_button_treeview](https://cloud.githubusercontent.com/assets/12285830/7773155/a332385e-0070-11e5-84e7-fc674ae94c1b.png)

80% idle when dragging button, 30% when dragging svg.

**Comment by STRML** [comment]
With pure css translations, the draw calls get offloaded to the GPU and should be very, very fast. My estimation is that clicking the button is involving a more primitive part of the layout engine and the profile you're seeing above is the context switching between maintaining that `:active` state on the button and recalculating the layout for the drag. Just a guess though.

So it appears in the fiddle, you're actually getting better performance clicking on the svg than on the button?

**Comment by ThePainnn** [comment]
In the fiddle the perf are almost the same either dragging the svg or the button, both are fast. Both runs on the profiler yield the same kind of result as dragging a button in my application. The only one that differ greatly is the dragging of the svg element in my application where the % of idle time drop to 30%.

I tried to disable the useCSSTransforms flag to see what happen, but there are no differences.

**Comment by STRML** [comment]
In general I see a lot worse perf from RGL if the inspector is open;
perhaps it has something to do with that. Otherwise I would suspect
there are some styles on your page that are putting the browser in an
unoptimized state. Something to look for.

**Comment by ThePainnn** [comment]
Ok, I'll check it out to make sure it's not the case.

One thing I cames up with the profiler:

![tim_diff](https://cloud.githubusercontent.com/assets/12285830/7773987/e5f9bd9c-0075-11e5-8f4c-a2dab8d23e19.png)

There is a difference of 305ms between the 2 paint calls (925ms 1230ms), which cause massive lag.

I'll keep you posted if I find something.

**Comment by STRML** [comment]
I don't think that's what this profile is telling you; it just looks like its firing on requestAnimationFrame, which is every 16ms.

**Comment by ThePainnn** [comment]
After gutting out most of my code just to keep code related to react-grid-layout. It was still slow. I thus remove almost all css ref, and still slow. So I move to my gulp build, remove dependencies. Which look like:

  bundler.require('react')
  bundler.require('react-bootstrap')
  bundler.require('react-widgets')
  bundler.require('react-color-picker')
  bundler.require('griddle-react')
  bundler.require('d3')
  bundler.require('underscore')
  bundler.require('deferred')
  bundler.require('events')
  bundler.require('flux')
  bundler.require('object-assign')
  bundler.require('keymirror')
  bundler.require('react-grid-layout')
  bundler.require('react-simpletabs')

The more I remove, the faster it is. I've kept, react, react-bootstrap, react-grid-layout, events and object-assign. The speed is almost on par with dragging a button. I don't see the link between the size of my deps.js file and the speed of dragging an svg element vs button.

**Comment by STRML** [comment]
That's very odd. Maybe you can isolate it down to a few dependencies in particular? It's possible that, for instance, react-bootstrap is adding global event handlers that could be slowing you down.

**Comment by STRML** [comment]
Please update if you have found anything else. For now I will close because we cannot replicate.

**Comment by Puffton** [comment]
I have found something causing really slow dragging in Chrome on OS X, this:
.react-grid-item.cssTransforms {
    transition-property: transform;
}

Might be something I have messed up with my custom CSS though.

**Comment by franckamayou** [comment]
Hello, I started using ReactGridLayout a few days ago and I am having the exact same performance issues. Dragging and resizing is extremely slow in Chrome (os x, windows), but performs fine in Firefox and Safari. I tried disabling the transition-property mentioned above to no avail. This also happens with empty divs.

**Comment by franckamayou** [comment]
I was able to figure out what my issue was. On the page, I had a built in `<select>` element with about 5000 `<option>` within it. Anytime I would initiate a drag or resize, the ReactDraggable and ReactResizable  elements would set the pointer events on the `<body>` tag to `user-select:none` (to prevent text selection). Since the `<body>` tag is a parent of my `select` tag, My guess is that 
A possible work around for this issue is to create a `<div style="position:fixed;width:100%;height:100%;user-select:none"/>`  when the drag and resize events are initiated and remove the div at the end of mouse event.
