### ISSUE TITLE
how to set the rowHeight before render?

### ISSUE THREAD

**Issue by Maybe009** [STRML/react-grid-layout#591]
Actually i have a question about how RGL responsive to the width of the browser,and i read the code about the widthprovider but i just cannot figure it out.Cause it just bind a event when componentDidMount but it should doesn't works before render.So if i wanna init the rowHeignt before render,it doesn't works.
What i want is to init the rowHeight to fill the height of my div box.But if bind resize events in didMount it will not work until u resize the window or refresh.

**Comment by emzero** [comment]
My grid items load data from an API and they can end up being pretty short or veeeery long. How can I set the item height based on its contents once the data has been loaded ?

**Comment by STRML** [comment]
Set a handler on your custom components (or wrap them in some HOC), call back after render by measuring a ref'd DOM element, and set `rowHeight`.
