### ISSUE TITLE
How can I disable the dragging of image inside the layout in mozila firefox.

### ISSUE THREAD

**Issue by uc-rpr** [STRML/react-grid-layout#592]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [ ] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by ylacaute** [comment]
This is not stackOverflow. You even not checked "question".
What you are looking for is **draggable="false"**
You can close this issue.
