### ISSUE TITLE
`onResizeStop` not firing `onLayoutChange` reliably

### ISSUE THREAD

**Issue by thomb** [STRML/react-grid-layout#593]
- [x] Bug
- [ ] Feature Request
- [ ] Question

I've run into a situation where `onResizeStop` doesn't trigger `onLayoutChange` all the time.

The `layout` as returned by the `onResizeStop` handler reflects the changes to the layout, but `oldLayout` and `newLayout` are equal. meaning on that `onLayoutMaybeChanged` never fires `onLayoutChange`.

Apologies for the lack of a test case, the `webpackBin` link in the ticket wasn't working.

**Comment by al-fyodorov** [comment]
Hey @thomb, you can send steps for reproduce this bug?

**Comment by STRML** [comment]
#1289 needs more explanation, but I can see where there may be an issue here if `state.layout` is mutated.
