### ISSUE TITLE
Drag items between two scrollable lists

### ISSUE THREAD

**Issue by nodefiend** [STRML/react-grid-layout#595]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [X] Feature Request
- [X] Question

### Is there a way to create a list / trello board / where you can drag items between two lists, both of these lists?

![scroll](https://camo.githubusercontent.com/e05c455315e05d4b013777c888a38e35bd2ce55b/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6c3446476d30367a4f6576796c316478362f67697068792e676966)

I want to be able to scroll each list independently...

ive tried a couple of implementations with your library, but havent been successfull..

Please help!

**Comment by nodefiend** [comment]
## please 
### please 
# please

**Comment by STRML** [comment]
This is not something RGL is built for, nor do I plan to. 

https://github.com/react-dnd/react-dnd is probably what you want.
