### ISSUE TITLE
Constrain grid within a fixed height

### ISSUE THREAD

**Issue by bonham000** [STRML/react-grid-layout#596]
- [x] Question

This is a great library, really enjoying it! I've looked through the issues and haven't found a clear answer to this question, but if there is already an issue discussing it please just point me there.

I'm looking to have a grid with a fixed height, where, if you try to drag a grid item in a way that would expand the overall height of the grid it won't be allowed. Exactly how the width is fixed and you cannot drag a grid item in a way that expands it past the width of the container. Is there some way to do this?

Thank you!

**Comment by STRML** [comment]
Hi - this question [has been asked many times](https://github.com/STRML/react-grid-layout/search?q=fixed+height&type=Issues&utf8=%E2%9C%93).

Unfortunately I don't have a lot of time to maintain this library so I haven't implemented such a thing, but would be open to a PR.
