### ISSUE TITLE
How should I get grid item width in pixel?

### ISSUE THREAD

**Issue by alishir** [STRML/react-grid-layout#597]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by STRML** [comment]
Divide by the width of the container, subtract by margin, or get the DOM element directly and measure it.
