### ISSUE TITLE
Infinite

### ISSUE THREAD

**Issue by jrock17** [STRML/react-grid-layout#598]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [ ] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by STRML** [comment]
?

**Comment by jrock17** [comment]
Sorry didn't mean to submit. Feel free to delete.
