### ISSUE TITLE
React-Grid D3 resizing help? Child divs are overlapping the parent

### ISSUE THREAD

**Issue by 87maza** [STRML/react-grid-layout#599]
<img src="http://i.imgur.com/znAFcbm.png">

Hey guys,

Having an issue with divs overlapping in d3 and react-grid.  As you can see on the image, the child divs seem to overlap its parent.  I'm having a hard time isolating the cause of this.

I want to create some sort of responsive wrapper for each container without any overlap from the child divs.

I'm wondering if its a d3 or react-grid issue? Or maybe my poor css skills?

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

**Comment by ylacaute** [comment]
@87maza
Try to encapsulate your SCG in a div with this style :
  display: flex;
  flex: 1;

**Comment by ylacaute** [comment]
@87maza
Did the display flex solved the problem ?
I think this issue should be closed. I currently use a D3 graph (Victory framework) and the SVG graph squale perfectly on resize(even during the resize).

**Comment by 87maza** [comment]
i just used

`position:absolute` on the parent 

All good
