### ISSUE TITLE
How to cancel the action after started?

### ISSUE THREAD

**Issue by WellerQu** [STRML/react-grid-layout#600]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

How to cancel the action after started? such as DragStart was triggered, but I want to stop and revert to before.

**Comment by dcworldwide** [comment]
https://github.com/STRML/react-grid-layout/issues/786

Did you find a solution? @WellerQu
