### ISSUE TITLE
Gridster link is leading to a malware site

### ISSUE THREAD

**Issue by derwaldgeist** [STRML/react-grid-layout#604]
The link to gridster.net is leading to a weird malware site that pretends there was a virus on my Mac. Could you please correct this to http://dsmorse.github.io/gridster.js/, which seems to be the correct repo for gridster. Thanks

**Comment by STRML** [comment]
Thanks for the info, replaced it.

**Comment by derwaldgeist** [comment]
Always glad to help :)

**Comment by jwt1143** [comment]
There are still two links to gridster.net on the npm module site that lead to the malware page.

**Comment by STRML** [comment]
Which ones?

**Comment by jwt1143** [comment]
https://www.npmjs.com/package/gridster

Here:
<img width="788" alt="screen shot 2017-09-04 at 11 37 41 am" src="https://user-images.githubusercontent.com/15367855/30035295-e4d9b07e-9165-11e7-9c0b-f144f65a694a.png">

And here:
<img width="426" alt="screen shot 2017-09-04 at 11 40 35 am" src="https://user-images.githubusercontent.com/15367855/30035297-e7365ff2-9165-11e7-8884-2b1277dca555.png">

**Comment by STRML** [comment]
That's for the gridster module, which is not this module.
