### ISSUE TITLE
How to calculate height of grid items based on viewport height?

### ISSUE THREAD

**Issue by emzero** [STRML/react-grid-layout#605]
I have a full page RGL and I want to set the height (`h` of layout items) to be as close as possible (without generating scrollbars) to the viewport height.
So, when generating the layout array I set the h as `window.innerHeight / rowHeight` which should return the number of rows needed to take the full window height. But the rendered grid is a bit taller than expected (generating scrollbars).

How can I achieve this? Is there a specific formula that take margins/paddings into account that I'm not aware of?

Thanks

**Comment by STRML** [comment]
See https://github.com/STRML/react-grid-layout/issues/233#issuecomment-319995357
