### ISSUE TITLE
Manual trigger onWidthChange functionality

### ISSUE THREAD

**Issue by JimVercoelen** [STRML/react-grid-layout#607]
Hello,

I was wondering if there is a way to manually trigger the onWidthChange functionality?

The grid items width is slightly of on the initial render (initialize?).

But after resizing the browser it calculates the correct width...
![initial-width](https://user-images.githubusercontent.com/13642402/29486061-b354a246-84dd-11e7-997b-c909215f9398.png)

It also occurs when for instance a parent's containers width changes. The items won't grow until a manually resize the browser.

![parent-width-change](https://user-images.githubusercontent.com/13642402/29486062-b70c75d0-84dd-11e7-8c99-b14dd4e871a7.png)

**Comment by JimVercoelen** [comment]
Btw I am using the WidthProvider

`import { WidthProvider, Responsive } from 'react-grid-layout';`
`const ResponsiveReactGridLayout = WidthProvider(Responsive);
`

**Comment by JimVercoelen** [comment]
Fixed the issue by creating our own WidthProvider

**Comment by STRML** [comment]
That's fine, the WidthProvider itself is not meant to have a lot of functionality - every application is different.

**Comment by andrewhathaway** [comment]
@JimVercoelen Out of curiosity what changes did you make in your own width provider?

**Comment by rococtz** [comment]
I would be interested to see that, too. Any chance you can share some info, please?

**Comment by JimVercoelen** [comment]
Hi guys I am so sorry for the late response.

I found out you can set it up like this, it's a bit depending on our project tho but I am sure you are able to modify it to yours :)

`import React, { Component } from 'react'
import PropTypes from 'prop-types'
import ReactDOM from 'react-dom'

const initialState = {
  width: 1280
}

const WidthProvider = ComposedComponent => class extends Component {
  static propTypes = {
    measureBeforeMount: PropTypes.bool
  }

  static defaultProps = {
    measureBeforeMount: false
  }

  mounted = false

  onSidebarChange = () => {
    setTimeout(() => {
      this.calculateWidth()
    }, 0)
  }

  onWindowResize = () => {
    this.calculateWidth()
  }

  calculateWidth = () => {
    if (!this.mounted) return
    const node = ReactDOM.findDOMNode(this)

    if (node instanceof HTMLElement) {
      this.setState({ width: node.offsetWidth })
    }
  }

  componentDidMount () {
    this.mounted = true

    window.addEventListener('resize', this.onWindowResize)
    window.addEventListener('sidebarChange', this.onSidebarChange)

    this.onWindowResize()
  }

  componentWillUnmount () {
    this.mounted = false

    window.removeEventListener('resize', this.onWindowResize)
    window.removeEventListener('sidebarChange', this.onSidebarChange)
  }

  constructor (props) {
    super(props)

    this.state = initialState
  }

  render () {
    if (this.props.measureBeforeMount && !this.mounted) {
      return <div className={this.props.className} style={this.props.style} />
    }

    return <ComposedComponent {...this.props} {...this.state} />
  }
}

export default WidthProvider
`

**Comment by CWSites** [comment]
@STRML, This seems like a common request for `WidthProvider` would it be possible to add this functionality to it out of the box?

**Comment by bardiarastin** [comment]
@JimVercoelen In my case I was able to get it done by a little change (setTimeout) on your code

```
componentDidMount () {
  this.mounted = true

  window.addEventListener('resize', this.onWindowResize)
  window.addEventListener('sidebarChange', this.onSidebarChange)
  setTimeout(() => {
    this.onWindowResize()
  }, 500)
}
```

**Comment by stopsopa** [comment]
In my case this was ok:
from: https://stackoverflow.com/a/43846782/5560682

    if (typeof(Event) === 'function') {
        // modern browsers
        window.dispatchEvent(new Event('resize'));
    } else {
        // for IE and other old browsers
        // causes deprecation warning on modern browsers
        var evt = window.document.createEvent('UIEvents'); 
        evt.initUIEvent('resize', true, false, window, 0); 
        window.dispatchEvent(evt);
    }

Work to me on:

macOS Mojave Version 10.14.1 (18B75):
- Chrome: Version 70.0.3538.110 (Official Build) (64-bit)
- Safari: Version 12.0.1 (14606.2.104.1.1)
- Opera: Version:56.0.3051.116
- Firefox: Quantum 63.0.3 (64-bit)

Windows 10:

**Comment by zoeykk** [comment]
you can use the <Responsive width={this.state.width}> with the prop width injected manually
`
          <Responsive
            width={responseWidth}
...
          >
            ...
          </Responsive>
`

**Comment by gknapp** [comment]
To elaborate on other comments. I came here wondering why RGL would resize items to fit the page width if I adjusted the window size but toggling my sidebar width was ignored by the out-of-the-box `WidthProvider` HOC.

Once I dropped `WidthProvider`, I found the grid would resize when toggling my sidebar, all I needed was a couple of hooks.

```js
...
const [rglWidth, setWidth] = React.useState(calcGridWidth(theme))

React.useEffect(() => { // resize grid on window resize
  function setGridWidth() {
    setWidth(calcGridWidth(theme))
  }
  
  window.addEventListener("resize", setGridWidth)

  return () => {
    window.removeEventListener("resize", setGridWidth)
  }
}, [setWidth, theme])

React.useEffect(() => { // resize grid items on sidebar toggle
  const gridWidth = calcGridWidth(theme)

  if (rglWidth !== gridWidth) {
    setWidth(gridWidth)
  }
}, [rglWidth, props.sidebarOpen, theme])
```

Pass the `width` prop: `width={rglWidth}`

(I pass the `theme` to `calcGridWidth()` as I reference `theme.spacing` (Material UI) - do whatever suits your app)
