### ISSUE TITLE
The transform position dose not follow cursor immediately when dragging 

### ISSUE THREAD

**Issue by kyoyadmoon** [STRML/react-grid-layout#61]
Hi,
I included the  "react-grid-layout.min.js" in my project(Rails v4.2 & React.JS v0.12.2). And I can use the ReactGridLayout Component without error, but it doesn't work as perfect as the demo on the github.
When i was dragging the item, the x,y in property "transform: translate(x,y);" doesn't change immediately with my cursor's position. It changed when the cursor dragged the item into another grid column.It seems the javascript dose not work as expected.

**Comment by STRML** [comment]
This is usually an issue with missing styles from the project. Please check on that.

**Comment by kyoyadmoon** [comment]
I have checked twice before open this issue and found nothing different.
but I will checked again to make sure it.
I include these files :  react-grid-layout.min.js , lodash.js , styles.css , resize_styles.css

I recorded the screen to show the problem. 
https://youtu.be/J_qSZxKR7DE
The property "transform: translate(x,y);" doesn't change immediately , I still think the problem is about javascript.
Thank you.

**Comment by Puffton** [comment]
What if you try a scaled back version without your custom styling? Personally I scaled back on everything: I wrote my own CSS and got rid of lodash, and it behaves like the demo.

**Comment by kyoyadmoon** [comment]
I include resize_styles.css  because the /dist/simple-include.html  include this https://rawgit.com/STRML/react-resizable/master/css/styles.css 

I use react-grid-layout v0.8.0 with React.JS v0.12.2

**Comment by Puffton** [comment]
That is styles.css, not resize_styles.css?

**Comment by JaneCoder** [comment]
Hi kyoyadmoon, I was wondering what else you had to do to make the grid layout work in a rails app?
When I just put the react-grid-layout.min.js file in my assets, I get errors that 'require is not defined'. Do I need to do something with webpack? Or need other files? Thanks for any pointers.
