### ISSUE TITLE
webpackbin url is broken

### ISSUE THREAD

**Issue by john-hu** [STRML/react-grid-layout#610]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [x] Bug
- [ ] Feature Request
- [ ] Question

If you have a question or bug report, please use the [WebpackBin Template](http://www.webpackbin.com/EJF48h_rz)
to demonstrate. It is much easier for us to help you if you do.

I cannot use above link or any link at the readme.md.

**Comment by STRML** [comment]
https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI
