### ISSUE TITLE
react-draggable update dependency

### ISSUE THREAD

**Issue by Billy-** [STRML/react-grid-layout#612]
Type of this issue:

- [ ] Bug
- [x] Feature Request
- [ ] Question

I just reported this issue in react-draggable: https://github.com/mzabriskie/react-draggable/issues/272

You may want to update your dependency once a new version is released.

**Comment by kumarharsh** [comment]
The dependencies specify `^3.0.3`, and this issue was fixed in `3.0.2`, so I guess the issue can be closed?
