### ISSUE TITLE
Your Webpack demo does not work

### ISSUE THREAD

**Issue by holzfelix** [STRML/react-grid-layout#613]
can you please provide a working webpack example in es6?

**Comment by STRML** [comment]
https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI

**Comment by holzfelix** [comment]
Hi can you maybe provide a working example on https://codesandbox.io/s/

Webpackbin is offline.

I tried your examples in codesandbox, but the don't work.
https://codesandbox.io/s/42m0q6oxy7
