### ISSUE TITLE
[Bug] in 0.15.0 I cant focus layout-item with inputs/textareas. In 0.14.7 this works.

### ISSUE THREAD

**Issue by FerusAndBeyond** [STRML/react-grid-layout#615]
Upgraded to 0.15.0 and I can't focus inputs or textareas inside a layout-item. What happens is it focuses it for like 0.1s and then its unfocused.

**Comment by STRML** [comment]
Likely related to https://github.com/mzabriskie/react-draggable/pull/261

**Comment by 11111000000** [comment]
I fix this with custom draggable handlers

**Comment by saaditkhan** [comment]
@11111000000 Could you please provide more info on your solution?

**Comment by msambarino** [comment]
@11111000000 Same here, could you provide some more info?

**Comment by SuperDJ** [comment]
Still not working in 0.16.0. Has anyone already found/ made a fix for it? 

When clicking on a label of the corresponding input the focus does stay.

**Comment by jflayhart** [comment]
I think what @11111000000 was getting at is https://github.com/STRML/react-grid-layout#grid-layout-props "draggableHandle" prop. If you create a more focused draggable area, it doesn't seem to mess with other input elements. My guess is that when the entire area is draggable, the browser can't differentiate between mouse, focus, and drag events. If we make a specific area draggable, then the input is able to function as normal. I think this might still be a bug, but for now the only way seems to be to make a cutom draggableHandle away from any input fields.

**Comment by idanbeker** [comment]
Hey guys ,
I had the same problem and I fixed it by using the draggableCancel prop, which accepts a CSS selector.
So if you would like textarea and input fields to act as expected when nested in draggable objects, you would use something like this:


```
<ReactGridLayout 
                                 onLayoutChange={ this.onLayoutChange }
                                 width={ 1920 }
                                 cols={ 4 }
                                 draggableCancel="input,textarea"
                                 margin={ [0, 0] }
                                 rowHeight={ 270 }
                                 isResizable={ false }
                                 useCSSTransforms={ true }>

```

**Comment by Ritorna** [comment]
Had the same issue when using Chrome. While using Firefox it worked as expected. 
The fix suggested by @idanbeker worked fine here.

**Comment by pungggi** [comment]
@STRML I think this can be closed? Solution> use draggableCancel

**Comment by msanchez-eutech** [comment]
draggableCancel works perfectly but having lost some hours on this kind of issue (i thought the problem was in how i handled onLayoutChange) i'm wondering why @idanbeker solution isn't the default ? 

I mean, shouldn't we expect basic inputs to gain focus when clicked in a draggable area ? Is there a case where we want to drag when clicking an input ? Seems weird to me
