### ISSUE TITLE
Unable to see resizable component.

### ISSUE THREAD

**Issue by vigneshuvi** [STRML/react-grid-layout#618]
Hi,

I am working on integrating react-grid for my demo. I am unable to see the grid resize component in my app. Please see the attached image.
![screen shot 2017-08-31 at 6 08 17 pm](https://user-images.githubusercontent.com/4980335/29923595-b93293fa-8e77-11e7-917e-f3b99c750c1e.png)

- Please find the demo source code: https://github.com/vigneshuvi/reactskeleton
- Demo: https://vigneshuvi.github.io/reactskeleton/

Note: Enter valid any valid email and just four characters for password.

**Comment by ProTip** [comment]
@vigneshuvi  For me the css was not being pulled it; it sets the position and other stuff of the handle.

Importing the css worked for me:
```
import 'react-grid-layout/css/styles.css'
```

**Comment by vigneshuvi** [comment]
Thanks, It is working fine now!
