### ISSUE TITLE
Set height 100% of page

### ISSUE THREAD

**Issue by bannik** [STRML/react-grid-layout#62]
How is it possible to set a div to cover 100% of height of a page? My div is:

"<   div key={1} _grid={{x: 0, y: 0, w: 4, h: 1, static: true}}></ div >"

should I do it through css?

**Comment by Puffton** [comment]
This question doesn't seem related to react-grid-layout per se but rather ReactJS, but yes. See:
https://facebook.github.io/react/tips/inline-styles.html
https://facebook.github.io/react/docs/class-name-manipulation.html

**Comment by dberardo-com** [comment]
is this possible to achieve using props of grdilayout component ??
