### ISSUE TITLE
way to use Components as Cell containers

### ISSUE THREAD

**Issue by 11111000000** [STRML/react-grid-layout#622]
I can't find a way to write like that:

```
        <ResponsiveGrid className="layout"
                        layouts={layouts}>          
          <Widget key={'header'}>
            ...
          </Widget>
```
- [ ] Bug
- [X] Feature Request
- [X] Question

**Comment by STRML** [comment]
This doesn't provide me any useful information to solve your problem.

**Comment by 11111000000** [comment]
now cells are only plain `divs`, we need to use custom components there

**Comment by STRML** [comment]
See https://github.com/STRML/react-grid-layout/issues/299#issuecomment-235635281

**Comment by 11111000000** [comment]
please add this to the docs
