### ISSUE TITLE
Get Current Layout after dragging and re-arranging the grid.  

### ISSUE THREAD

**Issue by nithyanv** [STRML/react-grid-layout#623]
- [ ] Bug
- [ ] Feature Request
- [X] Question

I wanted to persist and / display the current layout. I see in the demos, you have a component that displays the current layout structure. How is this done? I am not able to get the current layout on rearranging the components inside.

**Comment by STRML** [comment]
This code is all open source, there's no magic there. I just listen to the `onLayoutChange` callback. See https://github.com/STRML/react-grid-layout/blob/master/test/test-hook.jsx#L31 and https://github.com/STRML/react-grid-layout/blob/master/test/examples/0-showcase.jsx#L49.
