### ISSUE TITLE
Question about layout height and rowHeight

### ISSUE THREAD

**Issue by abhishekjindal** [STRML/react-grid-layout#628]
- [ ] Question

Hi,

I am trying to use the library to implement resizable panels with react. I am not sure how the height for the layouts work in grid units and how the rowHeight affects the grid elements. Can someone help me understand how these work? I am trying to scale a picture inside the grid element using the height and width of the container.

Thanks.

**Comment by stclairdaniel** [comment]
As far as I understand, rowHeight is a pixel value, and height in a multiple of rowHeight. For instance, if rowHeight=100 and a certain element has an h value of 2 in the layout, its height will end up being 200.

**Comment by abhishekjindal** [comment]
Thank you for your reply, that makes sense, I figured out the same thing.

**Comment by wzup** [comment]
@stclairdaniel 

Unfortunately that is not true. I have `rowHeight: 30`, and `h: 3`. So real height must be `3 x 30px = 90px`
But for some reason real height is `110px`. 

@STRML Why? Connected issue https://github.com/STRML/react-grid-layout/issues/800
```

element.style {
    color: white;
    background-color: rgb(221, 88, 38);
    width: 325px;
    height: 110px;
    position: absolute;
    touch-action: none;
    transform: translate(10px, 10px);
}
```

**Comment by ZachHaber** [comment]
I had an issue with this originally too, the reason for the issue is the margin that is set to 10 by default. The part of that that I think might actually be an issue is that for some reason it adds the margin again every time you resize the item. For instance in https://strml.github.io/react-grid-layout/examples/0-showcase.html, the rowHeight is 30, with a min height of 30, and they grow as follows: 30->70->110->150. Whereas if you set the margin to 0 manually, it grows like you'd expect: 30->60->90->120. What would make more sense is the growth with the margin to be more like 40->70->100->130, since I don't see a reason for the margin to increase in size so much.
From the docs:
// Margin between items [x, y] in px.
margin: ?[number, number] = [10, 10],

// Padding inside the container [x, y] in px
containerPadding: ?[number, number] = margin,

**Comment by rherms** [comment]
Is this not considered a bug? It seems weird to me that I go to specify my height in pixels (I am using a rowHeight of 1) and then that's not what actually is the height because of all this margin adding. Then I have to do a bunch of arithmetic to get my row heights correct.

**Comment by RaviDasari** [comment]
I think this is a bug and we should fix this.

**Comment by STRML** [comment]
It's not a bug.

**Comment by lonelydatum** [comment]
I found it in the docs:

static defaultProps = {
margin: [10, 10],
}

**Comment by mustak-tg** [comment]
Hi https://github.com/STRML,
      how can we give our own width to content as it is taking default width  and height as 
    width: 119px;
    height: 150px;

**Comment by danielecr** [comment]
this is from README.md
```
// Margin between items [x, y] in px.
margin: ?[number, number] = [10, 10],
```

where is explained that a multiplication of element's height * rowHeight * margin is made for calculation of margin?
and also, what kind of feature is it?
A margin is a margin, is not a factor of multiplication for getting a real margin, at very least the term does not fit well.

Anyway, this will lead to dynamic margins based on the size of an element, it is a kind of feature that is not really a feature

Maybe I would not browse the repository to check where is said, maybe I would not make a pull request for fixing this, but someone else maybe want. @STRML why close it and say is not a bug?

I try to explain my points with an example: I setted rowHeight to 1, then margin to 0, and everything look fine. But when I want to use a margin>0 I end up having all elements occupying the double.

Real sizes with margin =[0,1], height->whole height: 1 -> 2, 2 -> 4, 3 -> 6, 4 -> 8

Maybe you are experiencing something different, but for sure the only option as of now for me is to define the element height= real height + 10, and margin 0,0

**Comment by charlie0077** [comment]
setting margin y to 0 does not works for me. I don't understand why it is designed like this. Agreed that: a margin is a margin, we don't need magic.

**Comment by Hova25** [comment]
Hello,
I know this topic is 2 years old, but I found a solution for this problem.
For example my total screen height is 800px, I want to divide the height into 40 blocks so I do 800/40 do not forget to remove the margin from the total height times the number of blocks the margin is 10px .
So to sum up (800-(40*10))/40,
heightScreen - (heightBlocks*marginTop) / heightBlocks = rowHeight

**Comment by zhangwentao** [comment]
about Row px height calculation logic , can see this code https://github.com/react-grid-layout/react-grid-layout/blob/2e1387bcf598c98bffd3eb149cd670c7e5990e96/lib/calculateUtils.js#L25

**Comment by parsoman** [comment]
I am also facing the above issue while resizing the layout. Is there any workaround?

**Comment by OrhanOzkercin** [comment]
This is bizarre behavior. I did not get the reason and I also think this is a bug

**Comment by STRML** [comment]
This is not a bug.

If you have 10 HTML elements, each 100px high, and 10px margin between them, you will get a total height of:

`(100px * 10) + (10px * 9) = 1090px`

This is how RGL works as well.

**Comment by OrhanOzkercin** [comment]
@STRML Thank you very much for your quick response. 
What I don't understand is that let's say my `rowHeight` is 25 and my `h` is 4 for my element and my margin is 25 as well. As far as what I think my height of element should be 100. What am I missing here?

**Comment by STRML** [comment]
Imagine four elements next to it of h=1. Each one will be 25px high and have a margin between them of 10. 

Therefore, unless we want the grid to become ragged, the height at h=4 must be (25x4 + 10x3).

Play with it in the demo and you'll see.

**Comment by danielecr** [comment]
Oh well the math is correct, but what kind of feature is RGL providing?
I have box to arrange in a div, there is code controlling their size, I just need RGL accept their size and add margin to each box. Is it so strange as expectation?
I want to say: box1 is 100 of height, box2 is 230, margin is 20px.
What is "line height"? Is it an RGL topic? Why is the component interested in insight like that? What is for that math?
I can't understand your use case.
Sorry, I am not on front end anymore, but I am interested on hearing about the reason behind this weirdness

**Comment by STRML** [comment]
You are free to fork it, change the math, and have a grid where none of the items line up. I don't know what to tell you if you still aren't getting it. Try it out in the demo as I explained in my last comment. 

Heights are in grid units/spans, not pixels. There is a difference and it's an important one.

**Comment by danielecr** [comment]
Not me, but a collegue of me is using it, I am still not completely out of mind, really.

**Comment by STRML** [comment]
.....okay? Why are you asking questions again and again on someone else's behalf, but then also refusing to do bare minimum to discover the answer yourself? 

I'm going to lock this issue. I'll update the README with a visual representation of why it works this way.
