### ISSUE TITLE
cdnjs - Distribution for v0.11.2

### ISSUE THREAD

**Issue by extend1994** [STRML/react-grid-layout#631]
Hi!
I am a member of cdnjs and recently in charge of adding this lib.
I noticed that there is no library distribution (`dist` folder) in v0.11.2. But there are distributions before and after v0.11.2. Could you provide distribution for v0.11.2?
If there should be distribution in v0.11.2, please also let me know :)
Thank you.

By the way, you can see the progress of the pull request by https://github.com/cdnjs/cdnjs/pull/11696

**Comment by extend1994** [comment]
Hello, any infos?

**Comment by STRML** [comment]
0.11.2 was a broken publish, please just ignore it.

**Comment by extend1994** [comment]
Thanks! @STRML :+1:
