### ISSUE TITLE
Bug : IE11 error 800a025e on toggle of resize, resize icon not immediately removed

### ISSUE THREAD

**Issue by jwhooper** [STRML/react-grid-layout#633]
I apologize if this isn't formatted correctly, I don't understand the instructions for markup and webpack because I don't usually work in this area.

Anyway, so I have a ReactGridLayout with:

isDraggable={this.props.toggleLockOpen}
isResizable={this.props.toggleLockOpen}

I have a complex dashboard in a organization that is 100% IE11 at this time, no options.  This component has been fantastic by the way.  Anyway, I used to toggle the state on and off no problem, and it fact it does still function perfectly, however, after 0.15.1 this error started appearing when the isResizable state is toggle off.  I believe it has something to do with the resize icon removal, because the icon remains until something else forces a redraw.

SCRIPT606: Could not complete the operation due to error 800a025e.

I did some research, and it is related to removeAllRanges, found in the code as:
window.getSelection().removeAllRanges()

I am sorry that in my highly constrained environment I can't run the tools that would pinpoint this further.

The IE9,10,11 bug is know, and this was suggest to remediate:

      if (doc.body.createTextRange) { // All IE but Edge
        var range = doc.body.createTextRange();
        range.collapse();
        range.select();
      }
      else {
        doc.getSelection().removeAllRanges();
      }

I hope this is helpful.  It isn't really a big deal, because it still functions.  I rolled back to 0.15.0 and I hide the icon myself.

Thanks for the great tool!

**Comment by STRML** [comment]
Could you see https://github.com/mzabriskie/react-draggable/pull/292/files and confirm patching your local lib fixes the issue?

**Comment by jwhooper** [comment]
That works perfectly, thank you.  If you have a moment, maybe you could explain how I could have made my create-react-app application re-render my changes to domFns.  I didn't have time to mess with it, so I just edited the squished main.js output, which was slightly tedious but it worked.  Anyway, that works for now, so thanks again!
