### ISSUE TITLE
touch-action: none is added to items that use a draggable handle

### ISSUE THREAD

**Issue by danbovey** [STRML/react-grid-layout#637]
Type of this issue:

- [x] Bug
- [ ] Feature Request
- [ ] Question

`touch-action: none` is good for grid items where the whole area is draggable - this prevents a mobile browser from scrolling when you're moving a grid item. 👍 But if you're using a drag handle, only the drag handle element should have this CSS applied, otherwise an area on a mobile screen that the user would usually be able to use to touch and drag to scroll the page prevents them from doing so. This is definitely a problem on mobile browsers as grid-items may take up 100% width and height of the window.

Here's CSS I'm applying in my own app to circumvent this:

```sass
.react-grid-item {
    touch-action: initial !important;

    .drag-handle {
        touch-action: none;
    }
}
```

But the lib could fix this by only applying `touch-action: none` when `draggableHandle` is not set, and potentially using the `draggableHandle` CSS selector to apply the style to the item's drag handle.

**Comment by ifokeev** [comment]
same issue here
