### ISSUE TITLE
Weird behaviour when grid is under a div with height

### ISSUE THREAD

**Issue by patrickmesana** [STRML/react-grid-layout#639]
Maybe it's not a bug and I don't understand how to make it work but a div with height shifts the draggable item position (by the same heights), why?
Here's some basic code 

import React from 'react';
import ReactDOM from 'react-dom';
import RGL, { WidthProvider } from 'react-grid-layout';

const ReactGridLayout = WidthProvider(RGL);

const WordClouds = () => {
    let layout = [
        {i: 'a', x: 0, y: 0, w: 1, h: 1},
        {i: 'b', x: 1, y: 0, w: 1, h: 1},
        {i: 'c', x: 2, y: 0, w: 1, h: 1}
    ];
    return (
        <div>
            <div style={{height:100}}/>
            <ReactGridLayout className="layout" layout={layout}>
                <div key="a"  style={{backgroundColor:"black"}}>a</div>
                <div key="b"  style={{backgroundColor:"black"}}>b</div>
                <div key="c"  style={{backgroundColor:"black"}}>c</div>
            </ReactGridLayout>
        </div>
    )
};

ReactDOM.render(<WordClouds/>, document.getElementById('root'));

**Comment by patrickmesana** [comment]
reproducible on Chrome and Firefox on Linux

**Comment by STRML** [comment]
I really have no idea what you mean and this code is not runnable.

Please reproduce this in WebpackBin - once you have something going that accurately reproduces the issue out of the box, I'll take a look at it.

**Comment by patrickmesana** [comment]
Sorry my bad, I copied the wrong thing. Here's a StackBlitz with the problem https://stackblitz.com/edit/react-nhce3x?file=index.js
When you drag a block you will see a height shift. Remove <div style={{height:100}}></div> and there's no problem.
As I said, it's probably I am not understanding.

**Comment by STRML** [comment]
It's because you haven't included the CSS with the project. 

See https://react-x5w5qx.stackblitz.io

**Comment by patrickmesana** [comment]
Ah i see, missed that part of the doc, thanks :)
