### ISSUE TITLE
Responsive grid and verticalCompact false

### ISSUE THREAD

**Issue by Puffton** [STRML/react-grid-layout#64]
Using a modified version of your example 6-dynamic-add-remove.jsx, by setting "verticalCompact: false", the components all end up on top of one another in the upper left corner as they are added in both Chrome and FF, and they are not draggable. Does the responsive component not support "verticalCompact: false" or am I missing initial parameters?

I have tried comparing to 11-no-vertical-compact.jsx but it's not using the responsive control, so its use seems slightly different.

**Comment by Puffton** [comment]
For anyone else with this problem: If the items y-property is set to "Infinity", it causes the verticalCompact: false setting on the grid to crash.

**Comment by STRML** [comment]
Is this still an issue?
