### ISSUE TITLE
Support for 'square' grid cells?

### ISSUE THREAD

**Issue by kumarharsh** [STRML/react-grid-layout#644]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [x] Feature Request

Hi. I am using RGL to create a dashboard with square grids, and it seems that setting a rowHeight the same as colWidth requires some pretty complex code to be written for anyone who needs it. For reference: https://github.com/STRML/react-grid-layout/issues/399.

I'd like to propose something like a `rowHeightAspectRatio` prop which would let users define the height as a ratio of the column width. So, for a 'square' grid, they'll set the ratio as `1`.

@STRML Would this be something you'd like to be included in the library? I can submit a PR if you find this interesting.

**Comment by STRML** [comment]
Considering this can be done outside the library, I'd rather not include it
inside and bloat the options.

**Comment by jackie-benowitz** [comment]
You can calculate what your cell width will be by dividing `viewportWidth / numOfCols` and provide rowHeight accordingly

**Comment by kumarharsh** [comment]
Yes, that is what I'm doing currently. I was asking if it'd be worth it to include support in core where such a change would be far simpler than everyone maintaining a separate copy of similar code to create square grids.

**Comment by xeloader** [comment]
I would love to see this feature included in RGL.
