### ISSUE TITLE
onResizeStop, onResize not working properly

### ISSUE THREAD

**Issue by 0x6c23** [STRML/react-grid-layout#648]
I am using onResizeStop and onResize to determine the size of the item after resizing. Problem: onResizeStop fires when the mouse is released. After releasing the mouse, the item snaps to the grid, thus changing the size. 

Expected behaviour:
onResizeStop firing after the item snaps back to the grid

Actual behaviour:
onResizeStop fires after the mouse has been released, before the item snaps to the grid.

- [x] Bug
- [ ] Feature Request
- [ ] Question

**Comment by STRML** [comment]
You're looking for `onLayoutChange` then, which will reflect the size in
grid units.

0x6c23 wrote:

**Comment by 0x6c23** [comment]
Thanks for that blazing fast answer. I will use onLayoutChange then, but I have to calculate the size now.

I can get the height with:
