### ISSUE TITLE
Dynamic add/remove demo hangs on window resize

### ISSUE THREAD

**Issue by TheoRyley** [STRML/react-grid-layout#65]
After adding an item resizing the window causes the browser to hang on Chrome, Firefox and Safari.

**Comment by Puffton** [comment]
Can you be a little more specific? I tried the demo just now in Chrome and adding an item and resizing the browser window worked just fine.

**Comment by TheoRyley** [comment]
Sometimes I can't reproduce it myself. Try adding an item and then resizing the window a couple of items. Repeating this eventually causes the issue to appear for me.

**Comment by STRML** [comment]
I'll confirm, I've seen it too.

Working through some oddities right now with the new versions of draggable and resizable. Coming to terms with how stateful dragging is, and how awful it can be to work with if you hide the state. I'll come back around to these issues soon. Until then stick with `0.9.1`.

**Comment by rucryan** [comment]
Has this issue been fixed?

**Comment by STRML** [comment]
Fixed in `0.10`.
