### ISSUE TITLE
Resize is broken for grids with prevent collision = true

### ISSUE THREAD

**Issue by betalb** [STRML/react-grid-layout#655]
- [x] Bug
- [ ] Feature Request
- [ ] Question

Resize is broken for grids with prevent collision = true

Issue can be reproduced here
https://www.webpackbin.com/bins/-KxN4nBeFwFPVEwOnnj7

**Comment by tsnevillecom** [comment]
Any idea when this will be fixed?

**Comment by vincenzocaruso** [comment]
Same issue tracked here
https://github.com/STRML/react-grid-layout/issues/663
