### ISSUE TITLE
Add pinch to resize

### ISSUE THREAD

**Issue by BradfordMedeiros** [STRML/react-grid-layout#659]
- [ ] Bug
- [x] Feature Request
- [ ] Question

I have used a couple of applications using react grid layout. 

Really great library, one of the best!
You guys are doing a great job, probably the best job for a html based grid layout library.   Really great.

One thing that I find most people who use an app with grid layout find to work very poorly, is being able to resize tiles on mobile devices.  People expect to be able to use  pinch to zoom gestures.  Not being able to pinch to zoom, results in a poor user experience.  Everyone expects to be able to pinch to resize tiles!  Can't even resize tiles with fat fingers!

Can we make an effort to get this feature going?  If this is added via a PR, would it be merged?
I think this is the way react-grid-layout can be the greatest  grid library with no reason to consider elsewhere!

**Comment by codepunkt** [comment]
At the moment, tiles are resized in bottom/right direction. Pinch to resize would either do that aswell (and might feel strange) or resize in all directions, which might screw your layout in more ways than you might imagine.

@BradfordMedeiros Help is appreciated. Please implement a prototype comparing the two options. Doesn't necessarily have to be based on react-grid-layout. I'd just love to see/feel the differences to decide what might be right.
