### ISSUE TITLE
[Question] Dragging widgets across different browser windows

### ISSUE THREAD

**Issue by pavle-lekic-htec** [STRML/react-grid-layout#661]
I'd like to extend this library to be able to open few browser windows on different monitors, and then to be able to drag widgets from one browser window (monitor) to another.

Can you give me some advice on what is the best way to make changes to enable this behaviour?

From what I see, this library uses mousedown, mousemove and mouseup events to handle dragging. I'd need to change those to use dragstart, drag and dragend events. Probably few more things, not sure.

Thanks.

**Comment by STRML** [comment]
Multiple windows is a far more complicated action. It's not just about events, you have to open windows and translocate widgets through those windows. It actually can (kind of) be done (https://hackernoon.com/using-a-react-16-portal-to-do-something-cool-2a2d627b0202) but it is far from being supported officially by this or any other library.

**Comment by STRML** [comment]
I'll keep this open for a while in case you want to discuss that article, because it is actually pretty fascinating.

**Comment by pavle-lekic-htec** [comment]
I've read the article, and it's amazing. Thanks for sharing it! :) It could simplify things a lot since I don't need to think about synchronizing app state across different browser windows, it's the same app with the same props and state (and also same redux instance, since redux is passed down as props).

So I don't think it will be much more complicated than a regular (single window) app. We all wrote apps with modals, those modals were implemented with the portal pattern, this is very similar.

Concerning changes:
Currently you keep layouts as a two dimensional array (for each responsive breakpoint you have an array of widget positions), and now it will be a three dimensional array (browser windows x breakpoints x layout). Moving widget from one window to another would just mean moving it's position object from one place in three dimensional array to another.

I saw that you use DraggableCore, so I need to make a replacement lib that does the same thing but with html5 drag events. Also the code that makes the widget follow the mouse cursor as you drag is not needed now since browser is doing that for you. For a quick fix, I can just hide it for now on dragstart and show it again on dragend event.

Next I need to track dragenter and dragleave events on the whole window, because I need to know when dragging leaves one window and enters another.

Thanks for your input so far, it's been very helpful, and I'd highly appreciate any further tips on how to best proceed with these changes.

**Comment by pavle-lekic-htec** [comment]
Here is an update of the progress, I made the library work with html5 drag events with not much effort (I had to change DraggableCore a bit). I made it so that the handler for events fires on reqestAnimationFrame, otherwise the performance was really bad. For some reason the drag events fire at a much higher rate than mousemove events.

Now the portal thing from the article above is flawed, it doesn't work once you remove the setInterval(), there is no response on events in child windows. So the workaround that I'm thinking about now is to share the app state between browser windows through redux. So it will pretty much be the same solution like the portals thing, except the state will be in redux. I haven't tried this yet, but I believe it can work, since there is a way to call functions from either place, from child windows you can call functions from parent using parent.someFunction(); and from parent as soon as you call window.open() you will get back a reference to the child window window obj. So I should be able to call store.getState() from child windows and fire actions from them.
