### ISSUE TITLE
preventCollision doesn't allow the tile resize 

### ISSUE THREAD

**Issue by vincenzocaruso** [STRML/react-grid-layout#663]
- [ ] Bug
When this option is set true the resize doesn't work.
You can check this issue on the demo page
https://strml.github.io/react-grid-layout/examples/12-prevent-collision.html

**Comment by noahlange** [comment]
Problem is in the `getFirstCollision` function in `utils.js`.

A resizing object doesn't have the same dimensions as its previous incarnation, so it fails the strict equality check and reports a collision.

Potential solution: check if item indexes match; I'm not sure if these are usable as unique identifiers or not.

```js
export function getFirstCollision(layout: Layout, layoutItem: LayoutItem): ?LayoutItem {
  for (let i = 0, len = layout.length; i < len; i++) {
    const indexMatches = layoutItem.i === layout[i].i;
    const itemsCollide = collides(layout[i], layoutItem); 
    if (itemsCollide && !indexMatches) {
      return layout[i];
    }
  }
}
```

**Comment by betalb** [comment]
I've created PR to fix this long time ago https://github.com/STRML/react-grid-layout/pull/656
