### ISSUE TITLE
Store additional layout data

### ISSUE THREAD

**Issue by rakeen** [STRML/react-grid-layout#665]
Hi, great component you made here. kudos :+1: 

Please mark the type of this issue:

- [ ] Bug
- [x] Feature Request
- [x] Question

I was wondering if you have any plans to store additional data inside react-grid-layout?

By additional I mean some extra fields in the layout object. e.g.
`{i: 'c', x: 4, y: 0, w: 1, h: 2, data: 'myAdditionalData'}`

Currently if we add additional data, it gets removed when the layout is changed.
```js
onLayoutChange = (layout) => {
    // layout doesn't have data
}
```

One workaround is to append the extra data on **every** `onLayoutChange` event!

**Comment by codepunkt** [comment]
One workaround is to have an array or dictionary with a unique identifier string that you use as each layout object's `i`. Store the data somewhere else and reference it.

**Comment by Asif-Saheer-k** [comment]
const onLayoutChange = (oldLayout, newLayout) => {
    const updateLayout = newLayout.map((item, key) => ({
      ...item,
      name: oldLayout[key]?.name,
      display: oldLayout[key]?.display
    }));
    setLayout(updateLayout);
    if (!block) {
      setPreLayout(prevLayouts => [...prevLayouts, newLayout]);
    } else {
      setBlock(false);
    }
  };
  
  
     onLayoutChange={newItem => onLayoutChange(layout, newItem)}
     
     
     above problem i handled this way
