### ISSUE TITLE
Update GridItems before layout properties with Redux

### ISSUE THREAD

**Issue by grrseguin** [STRML/react-grid-layout#667]
Hello,

I use RGL (v0.16.0) with Redux and i note that if you use `layout` attribute of `ReactGridLayout`, when you update the component with a different number of `GridItems`, the layout could be broken!

Because [`ReactGridLayout` expect that its children are rendered before their layout](https://github.com/STRML/react-grid-layout/blob/v0.13.9/lib/utils.js#L366-L389).

**So the children (`GridItems`) of the `ReactGridLayout` component should always be rendered before their layout (or in the same time)**.

Maybe just a note in the Readme file should be added to explain that?

> I think that it's not the same if you use to set layout properties directly on the children.

> On demo code, the command "Generate New Layout" [fire a new layout in first](https://github.com/STRML/react-grid-layout/blob/v0.13.9/test/examples/0-showcase.jsx#L62), then [the `GridItems` are updated](https://github.com/STRML/react-grid-layout/blob/v0.13.9/test/examples/0-showcase.jsx#L73).

[Demo](https://www.webpackbin.com/bins/-KzyFapfub0dBQt22tgP)

**Comment by frantic0** [comment]
Hi @grrseguin  

I was wondering if you passed the redux store to the child components of the GridItems and how? 

Thanks

**Comment by grrseguin** [comment]
Hi @frantic0 

First the redux store fire a render into the `layouts` prop of `ResponsiveReactGridLayout` component, then to the child component of `ResponsiveReactGridLayout`.

Look at my [demo]((https://www.webpackbin.com/bins/-KzyFapfub0dBQt22tgP)) to see the problem. Press on "Generate New Layout disordered" to break the layout when the number of Griditems is less than before.
