### ISSUE TITLE
Question about grid items being other React components

### ISSUE THREAD

**Issue by Surreal9** [STRML/react-grid-layout#67]
I notice all the examples are rendering div's inside of the ReactGridLayout component. We've tried putting in references to a component instead (a Widget component), and it didn't work. I see that by going into my Widget component and adding {...this.props} into the wrapper Div which is returned by my Widget's render method, it seems to work again. 

Just wondering if this a good idea, or is there something else I'm missing?

**Comment by STRML** [comment]
That seems okay. RGL needs to set some classes and styles on the items,
and if they’re not listening for |className| and |style| the updates
will get ‘lost’.

You could also put the widget inside a div.

On 6/1/15 5:59 PM, John Arnold wrote:

> I notice all the examples are rendering div's inside of the
> ReactGridLayout component. We've tried putting in references to a
> component instead (a Widget component), and it didn't work. I see that
> by going into my Widget component and adding {...this.props} into the
> wrapper Div which is returned by my Widget's render method, it seems
> to work again.
>
> Just wondering if this a good idea, or is there something else I'm
> missing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/STRML/react-grid-layout/issues/67>.
>
​

**Comment by Surreal9** [comment]
Ok sounds good, thanks!
