### ISSUE TITLE
Link click prevention on drag release.

### ISSUE THREAD

**Issue by frazboyz** [STRML/react-grid-layout#679]
In the grid items that I am currently developing, there is a link to another location on the site. The link spans the entire size of the grid item. On occasion, when the drag event finishes the link click event is triggered, this seems to happen more often on shorter drag events.

This is the HTML structure of the grid.
```html
<div class="grid">
    <div class="grid-item">
        <a href="/">content</a>
    </div>
    <div class="grid-item">
        <a href="/">content</a>
    </div>
</div>
```

- [x] Bug
- [ ] Feature Request
- [x] Question

**Comment by frazboyz** [comment]
On further investigation, it looks like the onClick event is triggered when the widget is dragged to a grid position that is not available.

**Comment by art-mironoff** [comment]
Have you found how to fix this?

**Comment by frazboyz** [comment]
@art-mironoff I ended up timing the duration the user's mouse was pressed down on the grid item, if longer than x long, I manually instantiated the click even(url change for example).
