### ISSUE TITLE
Is it possible to build a jsfiddle-like layout using react-grid-layout?

### ISSUE THREAD

**Issue by mylake** [STRML/react-grid-layout#68]
hi, I want to implement a jsfiddle-like layout which divides the screen into 4 blocks, and I can resize each block by moving the horizontal or vertical handler. I'm not sure if I can use this lib or have to implement it by myself. Could you give me some hints? Thanks a lot.

**Comment by STRML** [comment]
I would recommend not using this library, and instead simply using four divs with resize handlers. RGL is not made for this use case and will get in your way.
