### ISSUE TITLE
Any support for dragging items between different RGL?

### ISSUE THREAD

**Issue by gerahimanshu** [STRML/react-grid-layout#688]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [x] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI)
to demonstrate. It is much easier for us to help you if you do.

**Comment by TrySound** [comment]
Not yet. There is [proposal pr](https://github.com/STRML/react-grid-layout/pull/684) for dragging to rgl, I'd like to improve it later.

**Comment by gerahimanshu** [comment]
I have a layout in such a way that there is a parent RGL along with 2 child RGL's. I want to drag items from 1st child RGL to 2nd child RGL. Is there any other way to do it?
