### ISSUE TITLE
Dynamic rowHeight

### ISSUE THREAD

**Issue by sasha240100** [STRML/react-grid-layout#691]
Is there a way to provide "relative" height? I want to update layout to fit 100% of window height **without rerendering/mounting components** on each resize callback.

Something like making `rowHeight` a function that returns a value would work nice.

Thanks in advance!

- [ ] Bug
- [x] Feature Request
- [x] Question

**Comment by GGAlanSmithee** [comment]
Is there any information available regarding this feature request? Is this something that is likely to be implemented? Is there any work-around available? I've seen some issues touching on this, but nothing conclusive.

I have a general idea on how to somewhat implement this myself, but an integrated solution would be preferable. Seems to me that this issue has quite a large impact on the usability of this framework when it comes to creating actual page layouts. Being able to fit content on the y-axis is quite crucial for the user experience IMO.

Thanks in advance.

**Comment by kartik2014** [comment]
hi @GGAlanSmithee  : I have a similar requirement where I want to fit individual grid items to the viewport height. Could you please share your solution?
