### ISSUE TITLE
In my app using reactabular responsive grid layouts, 1) Currently app opens three window, I am saving layouts after dragging , resizing and reducing window size,(even saving window size). If i reload the app, the windows getting opened with whatever last save window size, but react grid layouts are not getting accomplished to window sizes, 

### ISSUE THREAD

**Issue by sourabhlk** [STRML/react-grid-layout#695]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [ ] Question

If you have a question or bug report, please use the [WebpackBin Template](https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI)
to demonstrate. It is much easier for us to help you if you do.

**Comment by TrySound** [comment]
Please move description of your problem to issue description. Long title is not readable.
