### ISSUE TITLE
React-Grid-Layout and HighChart Drag-Drop and Resizing not working

### ISSUE THREAD

**Issue by jainvizz** [STRML/react-grid-layout#696]
I am trying to implement React-Grid-Layout in my application and I want to use high charts as grid items.

    <ResponsiveReactGridLayout margin={[20, 10]} containerPadding={[10,0]} rowHeight={20} className="layout" layouts={layouts} breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
          cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}>
    <SmallPieChart key={self.state.multiLangMsgs.NOTIFICATIONS} title={self.state.multiLangMsgs.NOTIFICATIONS}
                                                       chartHeight = "80" innerSize="70%"
                                                       iconClass={this.state.topChartData.icons[1]}
                                                       colors={this.state.topChartData.colors[5]}
                                                       otherStyleClass={this.state.topChartData.otherStyleClass[1]}
                                                       data={this.state.NOTIFICATIONS}
                                                       mulitple="true"
                                                       onDrillDown={this.notificationReport.bind(this, 3)}
                                                       totalEquips={this.state.topChartData.ALL_EQUIPMENT_COUNT}
                                                       multiLangMsgs={self.state.multiLangMsgs}/>
                                        <SmallPieChart key={self.state.multiLangMsgs.UTIL} title={self.state.multiLangMsgs.UTIL}
                                                       chartHeight = "80" innerSize="70%"
                                                       iconClass={this.state.topChartData.icons[2]}
                                                       colors={this.state.topChartData.colors[7]}
                                                       mulitple="true" type="column"
                                                       otherStyleClass={this.state.topChartData.otherStyleClass[2]}
                                                       data={this.state.UTILIZATION}
                                                       onDrillDown={this.utilizationEquipmentChartsReport.bind(this, 4)}
                                                       totalEquips={this.state.topChartData.ALL_EQUIPMENT_COUNT}
                                                       multiLangMsgs={self.state.multiLangMsgs}/>
    
    </ResponsiveReactGridLayout>

Here SmallPiechart is my custom component which is responsible for creating high chart.

Below is the code of SmallPiechart component

    <div key={this.props.key} style={this.props.style} className={this.props.className} >
    	                <a href="javascript:void(0);" onClick={this.showDrillDownList.bind(this, null)}
    	                tabNameAtt="Low Battery"  className="dashBoardItemSmall">
    	                  <div className={otherStyleClass}>
    	                    <i className={this.state.iconClass}></i>
    	                    <span style={{"margin-top" : (this.props.textTwoLines == "true") ? "-20px" : "0px"}}>{this.state.title}</span>
    	                  </div>
    	                  <div className="chart pull-right">
    	                  	<ReactHighcharts config={chartConfig}/>
    	                  </div>
    	                  <div className="clearfix"></div>
    	                </a>
    	            </div>

I am not getting what I am doing wrong here can any one please help. I am not able to drag-drop and resizing as well.

Thanks in advance.

**Comment by STRML** [comment]
It is likely that the chart is intercepting drag events. You might want to put a header bar on each widget and make it draggable from there.

**Comment by spredemann** [comment]
@STRML I have a different but related problem where I cannot focus on an input inside the grid. How can I specify an element/component/region to be the drag handle instead of the whole div?

**Comment by spredemann** [comment]
Nevermind. Solution is here: https://github.com/STRML/react-grid-layout/issues/615

**Comment by jainvizz** [comment]
I tried wrapping my child components using a new div and it is working as expected now.

**Comment by abelkbil** [comment]
@jainvizz can you please share the updated code ?
Thanks

**Comment by jainvizz** [comment]
@abelkbil sorry for delayed response. Here is the updated code:

<ResponsiveReactGridLayout margin={[20, 17]} containerPadding={[10,0]} rowHeight={25} className="layout" layouts={this.state.layouts}
                                  cols={{lg: 12, md: 12, sm: 12, xs: 1, xxs: 1}} onLayoutChange={(layout, layouts) => this.onReactGridLayoutChange(layout, layouts)} onResizeStop={this.onReactGridResizeStop.bind(this)}>
                                    <div key={self.state.multiLangMsgs.LOW_BATTERY}>
                                      <SmallPieChart title={self.state.multiLangMsgs.LOW_BATTERY}
                                                     chartHeight = "80" innerSize="70%"
                                                     iconClass={this.state.topChartData.icons[0]}
                                                     colors={this.state.topChartData.colors[0]}
                                                     otherStyleClass={this.state.topChartData.otherStyleClass[0]}
                                                     data={this.state.lowBatteryWidget}
                                                     onDrillDown={this.equipmentChartsReport.bind(this, 2)}
                                                     totalEquips={this.state.topChartData.ALL_EQUIPMENT_COUNT}
                                                     multiLangMsgs={self.state.multiLangMsgs}/>
                                    </div>
                                    {/*<SmallPieChart title="Maintenance" iconClass={this.state.topChartData.icons[1]}
                                                                                            colors={this.state.topChartData.colors[5]}
                                                                                            otherStyleClass={this.state.topChartData.otherStyleClass[1]}
                                                                                            data={this.state.DORMANCY}
                                                                                            mulitple ="true"
                                                                                            onDrillDown={this.maintenceReport.bind(this,3)}
                                                                                            totalEquips={this.state.topChartData.ALL_EQUIPMENT_COUNT}/>*/}
                                    <div key={self.state.multiLangMsgs.NOTIFICATIONS}>
                                      <SmallPieChart title={self.state.multiLangMsgs.NOTIFICATIONS}
                                                     chartHeight = "80" innerSize="70%"
                                                     iconClass={this.state.topChartData.icons[1]}
                                                     colors={this.state.topChartData.colors[5]}
                                                     otherStyleClass={this.state.topChartData.otherStyleClass[1]}
                                                     data={this.state.NOTIFICATIONS}
                                                     mulitple="true"
                                                     onDrillDown={this.notificationReport.bind(this, 3)}
                                                     totalEquips={this.state.topChartData.ALL_EQUIPMENT_COUNT}
                                                     multiLangMsgs={self.state.multiLangMsgs}/>
                                    </div>
                                    <div key={self.state.multiLangMsgs.UTIL}>
                                      <SmallPieChart title={self.state.multiLangMsgs.UTIL}
                                                   chartHeight = "80" innerSize="70%"
                                                   iconClass={this.state.topChartData.icons[2]}
                                                   colors={this.state.topChartData.colors[7]}
                                                   mulitple="true" type="column"
                                                   otherStyleClass={this.state.topChartData.otherStyleClass[2]}
                                                   data={this.state.UTILIZATION}
                                                   onDrillDown={this.utilizationEquipmentChartsReport.bind(this, 4)}
                                                   totalEquips={this.state.topChartData.ALL_EQUIPMENT_COUNT}
                                                   multiLangMsgs={self.state.multiLangMsgs}/>
                                    </div>

</ResponsiveReactGridLayout>

SmallpPieChart code:

<div>
	                <a href="javascript:void(0);" onClick={this.showDrillDownList.bind(this, null)}
	                tabNameAtt="Low Battery"  className="dashBoardItemSmall">
	                  <div className={otherStyleClass}>
	                    <i className={this.state.iconClass}></i>
	                    <span style={{"margin-top" : (this.props.textTwoLines == "true") ? "-20px" : "0px"}}>{this.state.title}</span>
	                  </div>
	                  <div className="chart pull-right">
	                  	<ReactHighcharts ref={ chart => { this.objHighChart = chart; } } config={chartConfig}/>
	                  </div>
	                  <div className="clearfix"></div>
	                </a>
	            </div>

Hope it will help.
