### ISSUE TITLE
help~~~

### ISSUE THREAD

**Issue by neove** [STRML/react-grid-layout#697]
when i use react-grid-layout in my project ,i have a problem :  the new item should be added by dragging rather than clicking a button. and the position of the new item should be update with the moving mouse, just like this:

![react-grid-layout](https://user-images.githubusercontent.com/18530075/34408708-7297da68-ec00-11e7-906a-0fe8713bf2fd.gif)

To achieve this effect, i modify the source code of the react-grid-layout, adding some method , and in my project ,i call this method by refs . i know this may not a good way , so i came here and ask for some help.  

thanks ~~

**Comment by TrySound** [comment]
Here's poposal for similar api https://github.com/STRML/react-grid-layout/pull/684
Maybe it should be regular ref with public methods.

**Comment by CWSites** [comment]
Please update your title to something more meaningful :)

**Comment by STRML** [comment]
Sorry, this is a general question and I wouldn't know where to begin helping you. Please take questions like this to IRC or Gitter.
