### ISSUE TITLE
[Question] Using RGL with Redux

### ISSUE THREAD

**Issue by frantic0** [STRML/react-grid-layout#699]
Hello, 

I'm using react-grid-layout (RGL) to implement this use case with two considerations 
* to keep the state of the app including GridItems' child components 
* enable communication between GridItems' child components (events, streams of data, etc)

Inspecting the RGL tree on React Dev tools I can see that there are many intermediate components.

I was wondering if anyone has implemented a similar scenario, and if theres a way to use a Redux store and pass it down the RGL tree to GridItems' child components.

```
<ResponsiveReactGridLayout
<ReactGridLayout
<div
<GridItem
<DraggableCore
<Resizable
<div
<UserChildComponent
```

Many thanks, 
FØ

**Comment by STRML** [comment]
There's nothing about this that is Redux-specific; you can simply persist state back to the tree by firing actions on `onLayoutChange`, or you can pass props directly down to your child components however you like. I am unsure what you are asking.

**Comment by frantic0** [comment]
> you can simply persist state back to the tree by firing actions on onLayoutChange, or you can pass props directly down to your child components however you like.

Thanks Samuel, I just did. Every thing is connected to the store now! Sorry if this is obvious, I'm doing a spike on the react/redux ecosystem. 

Great work on the library, this is really handy!

**Comment by GuacheSuede** [comment]
@frantic0 could you explain how you did it ?
