### ISSUE TITLE
Draggable ClientY is Null

### ISSUE THREAD

**Issue by rothnic** [STRML/react-grid-layout#7]
I was trying to integrate your examples into a [react webpack starter](https://github.com/webpack/react-starter) with routing. I added a new route, which I can get to show up as expected. However, on each drag event, I get the following error:

```
Uncaught TypeError: Cannot read property 'clientY' of nulldraggable.js:11
createUIEventdraggable.js:449 
module.exports.React.createClass.handleDragEnd
```

This occurs at draggable's:

```Javascript
function createUIEvent(draggable) {
	return {
		element: draggable.getDOMNode(),
		position: {
			top: draggable._pendingState.clientY,
			left: draggable._pendingState.clientX
		}
	};
}
```

PendingState is always null. It seems like a lifecycle issue, so i've tried a few different approaches, all with the same result (including using the example with no modifications).

[Gist with files](https://gist.github.com/rothnic/74f0a7f32dc321051801)

**Comment by STRML** [comment]
Hey Nick - I ran into this also about an hour ago as well. If you `npm
install` you should see this fixed in my newest push to react-draggable.

**Comment by rothnic** [comment]
Great, that was fast... works now. Thanks, nice job btw.
