### ISSUE TITLE
Setting breakpoints, cols and layouts properly

### ISSUE THREAD

**Issue by jainvizz** [STRML/react-grid-layout#700]
I am working on an application in which for dashboard page 25% of the page is covered by a div and another 75% is by another div.

I need to implement React-Grid-Layout on the second div which is having width of 75%. I am not able to understand how to provide breakpoints. I tried giving it like this

<ResponsiveReactGridLayout margin={[20, 10]} containerPadding={[10,0]} rowHeight={20} className="layout" layouts={layouts} breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
                                  cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}>

and layout is like this
  var layouts = {lg: [
          {i: 1, x: 0, y: 0, w: 2.5, h: 4.5, isDraggable: true},
          {i: 2, x: 2.5, y: 0, w: 2.5, h: 4.5, isDraggable: true},
          {i: 3, x: 5, y: 0, w: 2.5, h: 4.5, isDraggable: true},
          {i: 4, x: 7.5, y: 0, w: 2.5, h: 4.5, isDraggable: true}
        ]}; 

but this is not working properly. I want all the 4 child elements to have same width and height.

Previously I was using bootstrap and using col-md-3 was working fine but don't know how to make it work with react-grid-layout for the initial load after that user can make resize and drag-drop.

I have removed col-md-3 now from all 4 divs and trying to use the layouts property only.

Basically I am not getting how to set breakpoints, cols and layouts property.

Any help will be very much appreciated.

Thanks
I am working on an application in which for dashboard page 25% of the page is covered by a div and another 75% is by another div.

I need to implement React-Grid-Layout on the second div which is having width of 75%. I am not able to understand how to provide breakpoints. I tried giving it like this

<ResponsiveReactGridLayout margin={[20, 10]} containerPadding={[10,0]} rowHeight={20} className="layout" layouts={layouts} breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
                                  cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}>

and layout is like this
  var layouts = {lg: [
          {i: 1, x: 0, y: 0, w: 2.5, h: 4.5, isDraggable: true},
          {i: 2, x: 2.5, y: 0, w: 2.5, h: 4.5, isDraggable: true},
          {i: 3, x: 5, y: 0, w: 2.5, h: 4.5, isDraggable: true},
          {i: 4, x: 7.5, y: 0, w: 2.5, h: 4.5, isDraggable: true}
        ]}; 

but this is not working properly. I want all the 4 child elements to have same width and height.

Previously I was using bootstrap and using col-md-3 was working fine but don't know how to make it work with react-grid-layout for the initial load after that user can make resize and drag-drop.

I have removed col-md-3 now from all 4 divs and trying to use the layouts property only.

Basically I am not getting how to set breakpoints, cols and layouts property.

Any help will be very much appreciated.

Thanks

**Comment by goldensunliu** [comment]
dude this is not an issue. post it stackoverflow please.
