### ISSUE TITLE
 this.props.onLayoutChange is not a function - error when working with demo

### ISSUE THREAD

**Issue by petervkay** [STRML/react-grid-layout#701]
Hello,

The Webpack link included in the question template is not working for me.

I am new to React and am working on modifying your "[dynamic-add-remove](https://github.com/STRML/react-grid-layout/blob/master/test/examples/6-dynamic-add-remove.jsx)" example for my own purposes.  However, when I copy the code, I'm getting an error message in the console, "Uncaught TypeError: this.props.onLayoutChange is not a function". This is coming from what is line 95 in the example.  If I disable this line, mine works just like the example, but this looks like an event trigger to me that I might want to utilizat [https://amaxalaus.bigriverwebdesign.co know if you have an idea how to resolve it.

**Comment by STRML** [comment]
I can't help you if I don't see the code you're writing.

**Comment by petervkay** [comment]
I've hardly changed a thing from the example, just plugged it into my application, replacing what was already there.

**App.js**

    import React from "react";
    import _ from "lodash";
    import { WidthProvider, Responsive } from "react-grid-layout";
    const ResponsiveReactGridLayout = WidthProvider(Responsive);
   

    class AddRemoveLayout extends React.PureComponent {
      static defaultProps = {
        className: "layout",
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        rowHeight: 100
      };    

      constructor(props) {
        super(props);    

        this.state = {
          items: [0, 1, 2, 3, 4].map(function(i, key, list) {
            return {
              i: i.toString(),
              x: i * 2,
              y: 0,
              w: 2,
              h: 2,
              add: i === (list.length - 1).toString()
            };
          }),
          newCounter: 0
        };    

        this.onAddItem = this.onAddItem.bind(this);
        this.onBreakpointChange = this.onBreakpointChange.bind(this);
        this.onLayoutChange = this.onLayoutChange.bind(this);
      }    

      createElement(el) {
        const removeStyle = {
          position: "absolute",
          right: "2px",
          top: 0,
          cursor: "pointer"
        };
        const i = el.add ? "+" : el.i;
        return (
          <div key={i} data-grid={el}>
            {el.add ? (
              <span
                className="add text"
                onClick={this.onAddItem}
                title="You can add an item by clicking here, too."
              >
                Add +
              </span>
            ) : (
              <span className="text">{i}</span>
            )}
            <span
              className="remove"
              style={removeStyle}
              onClick={this.onRemoveItem.bind(this, i)}
            >
              x
            </span>
          </div>
        );
      }    

      onAddItem() {
        /*eslint no-console: 0*/
        console.log("adding", "n" + this.state.newCounter);
        this.setState({
          // Add a new item. It must have a unique key!
          items: this.state.items.concat({
            i: "n" + this.state.newCounter,
            x: (this.state.items.length * 2) % (this.state.cols || 12),
            y: Infinity, // puts it at the bottom
            w: 2,
            h: 2
          }),
          // Increment the counter to ensure key is always unique.
          newCounter: this.state.newCounter + 1
        });
      }    

      // We're using the cols coming back from this to calculate where to add new items.
      onBreakpointChange(breakpoint, cols) {
        this.setState({
          breakpoint: breakpoint,
          cols: cols
        });
      }    

      onLayoutChange(layout) {
        /*this.props.onLayoutChange(layout);*/
        this.setState({ layout: layout });
      }    

      onRemoveItem(i) {
        console.log("removing", i);
        this.setState({ items: _.reject(this.state.items, { i: i }) });
      }    

      render() {
        return (
          <div>
            <button onClick={this.onAddItem}>Add Item</button>
            <ResponsiveReactGridLayout
              onLayoutChange={this.onLayoutChange}
              onBreakpointChange={this.onBreakpointChange}
              {...this.props}
            >
              {_.map(this.state.items, el => this.createElement(el))}
            </ResponsiveReactGridLayout>
          </div>
        );
      }
    }    

    module.exports = AddRemoveLayout;    

    export default AddRemoveLayout;    
    
**Index.js**
    // -------------------------------------------------------------------------------    

    ReactDOM.render(
      <AddRemoveLayout />,
      document.getElementById('amaxalaus_container')
    );

**Comment by petervkay** [comment]
Thanks, I figured it wasn't a bug, but I'm not knowledgeable enough to
figure that out. Thanks a lot!

**Comment by petervkay** [comment]
I'm still having trouble with this same issue. I'm sure it's my fault, but I'm not seeing how this component is fed the properties from the "test-hook.jsx" file.  It seems like in my version, it's not getting anything from the file, so it's not loading the function or the top bar above the grid.

I added back in the require(test-hook.jsx') code block at the bottom and that isn't producing any errors, so the file is being found.

What is the code that I'm missing that should be loading properties from the parent?

Here's my code: the app.js file is literally pasted from the example.  The only adjustment I made was the path for the test-hook file.

Thank you for looking at this. I've been trying really hard to understand this on my own.

**App.js**
    import React from "react";
    import { WidthProvider, Responsive } from "react-grid-layout";
    import _ from "lodash";
    const ResponsiveReactGridLayout = WidthProvider(Responsive);    

    /**
     * This layout demonstrates how to use a grid with a dynamic number of elements.
     */
    class AddRemoveLayout extends React.PureComponent {
      static defaultProps = {
        className: "layout",
        cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
        rowHeight: 100
      };    

      constructor(props) {
        super(props);    

        this.state = {
          items: [0, 1, 2, 3, 4].map(function(i, key, list) {
            return {
              i: i.toString(),
              x: i * 2,
              y: 0,
              w: 2,
              h: 2,
              add: i === (list.length - 1).toString()
            };
          }),
          newCounter: 0
        };    

        this.onAddItem = this.onAddItem.bind(this);
        this.onBreakpointChange = this.onBreakpointChange.bind(this);
      }    

      createElement(el) {
        const removeStyle = {
          position: "absolute",
          right: "2px",
          top: 0,
          cursor: "pointer"
        };
        const i = el.add ? "+" : el.i;
        return (
          <div key={i} data-grid={el}>
            {el.add ? (
              <span
                className="add text"
                onClick={this.onAddItem}
                title="You can add an item by clicking here, too."
              >
                Add +
              </span>
            ) : (
              <span className="text">{i}</span>
            )}
            <span
              className="remove"
              style={removeStyle}
              onClick={this.onRemoveItem.bind(this, i)}
            >
              x
            </span>
          </div>
        );
      }    

      onAddItem() {
        /*eslint no-console: 0*/
        console.log("adding", "n" + this.state.newCounter);
        this.setState({
          // Add a new item. It must have a unique key!
          items: this.state.items.concat({
            i: "n" + this.state.newCounter,
            x: (this.state.items.length * 2) % (this.state.cols || 12),
            y: Infinity, // puts it at the bottom
            w: 2,
            h: 2
          }),
          // Increment the counter to ensure key is always unique.
          newCounter: this.state.newCounter + 1
        });
      }    

      // We're using the cols coming back from this to calculate where to add new items.
      onBreakpointChange(breakpoint, cols) {
        this.setState({
          breakpoint: breakpoint,
          cols: cols
        });
      }    

      onLayoutChange(layout) {
        this.props.onLayoutChange(layout);
        this.setState({ layout: layout });
      }    

      onRemoveItem(i) {
        console.log("removing", i);
        this.setState({ items: _.reject(this.state.items, { i: i }) });
      }    

      render() {
        return (
          <div>
            <button onClick={this.onAddItem}>Add Item</button>
            <ResponsiveReactGridLayout
              onLayoutChange={this.onLayoutChange}
              onBreakpointChange={this.onBreakpointChange}
              {...this.props}
            >
              {_.map(this.state.items, el => this.createElement(el))}
            </ResponsiveReactGridLayout>
          </div>
        );
      }
    }    

    module.exports = AddRemoveLayout;    

    if (require.main === module) {
      require("./hooks/test-hook.jsx")(module.exports);
    }

**Comment by STRML** [comment]
Just remove the part that calls `this.props.onLayoutChange(layout)`.

**Comment by petervkay** [comment]
I'm getting very close to implementing this module to do what I'd like.  I'm trying to build a system where I can recall previously saved layouts, modify them by adding/removing elements and dragging, and then resave them to the database as JSON.   I have not been successful in getting my layouts to update when I drag items.  I made a stripped down example at [amaxalaus.bigriverwebdesign.com
](amaxalaus.bigriverwebdesign.com) which uses a pre-defined layout.  I'm studying your local storage example and see that, when you drag an item, the layouts property changes accordingly.  However, I can't get this to happen on mine.  It looks like my onLayoutChange() function is not getting called at all, which is where I assume that this happens.  


Here is my current code:

     import React from "react";
     import RGL, { WidthProvider } from "react-grid-layout";
     import _ from "lodash";
     const ReactGridLayout = WidthProvider(RGL);
     const entities = require('html-entities').XmlEntities;    
    
    

    // -------------------------------------------------------------------------------    

    export class Grid extends React.PureComponent {
            static defaultProps = {
              isDraggable: true,
              rowHeight: 30,
              onLayoutChange: function() {},
              cols: 12,
            };        

          constructor(props) {
            super(props);
            var grid=this.props.currentGrid.acf.grid;
            
            grid = JSON.parse(entities.decode(grid));
      
            this.state = {
              items:grid,
              newCounter: grid.length + 1,
            };    

            this.onAddItem = this.onAddItem.bind(this);
            this.onBreakpointChange = this.onBreakpointChange.bind(this);
                

          }    

          generateDOM() {
            // Generate items with properties from the layout, rather than pass the layout directly
            return(this.state.items.map(function(item){
                return(
                  <div key={item.i}>
                    {<img src={item.source.source_url} alt={item.source.title.rendered} />}
                  </div>
                )
              })
            )
          }    

          createElement(el) {    

              const removeStyle = {
                position: "absolute",
                right: "2px",
                top: 0,
                cursor: "pointer"
              };
            
            const i = el.i;
            return (
              <div key={i}>
                
                  <img src={el.source.source_url} alt={el.source.title.rendered} />
                     <span
                      className="remove"
                      style={removeStyle}
                      onClick={this.onRemoveItem.bind(this, i)}
                    > 
                      x
                    </span>    

              </div>
            );
          }    
    

          onAddItem(image) {
            
            this.setState({
               newCounter: this.state.newCounter + 1,
              // Add a new item. It must have a unique key!
              items: this.state.items.concat({
                i: "n" + this.state.newCounter.toString(),
                x: 0,  // can build function later to insert it more smartly
                y: 0, // puts it at the bottom
                w: Number(image.acf.width),
                h: 2,
                source: image
              }),    

             
              // Increment the counter to ensure key is always unique.
              
            });
          }    

          onLayoutChange(layout) {
            this.props.onLayoutChange(layout);
            this.setState({ layout: layout });
            console.log('test');
          }    

          // We're using the cols coming back from this to calculate where to add new items.
          onBreakpointChange(breakpoint, cols) {
            this.setState({
              breakpoint: breakpoint,
              cols: cols
            });
          }         

          onRemoveItem(i) {
            console.log("removing", i);
            this.setState({ items: _.reject(this.state.items, { i: i }) });
          }    

          saveGrid() {
            const url = "window.handle_directions_post_url";
            const body = JSON.stringify({
              "title":"internet",
              "content":"teapot"
            });
            fetch(url, {
              method: 'POST',
              headers: {
                'Accept': 'application/json',
                'Content-Type': 'application/json',
                'X-WP-Nonce': window.nonce
              },
              body:body
              
            });
          }        

          render() {
            var layout = [
              {i: 'n1', x: 0, y: 0, w: 1, h: 2, static: true},
              {i: 'n2', x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4},
              {i: 'n3', x: 4, y: 0, w: 1, h: 2}
            ];    
    

            return (
              <div id='grid'>
                <ReactGridLayout
                  onLayoutChange={this.onLayoutChange}
                  onBreakpointChange={this.onBreakpointChange}
                  {...this.props}
                  layout={layout}
                >
                  {_.map(this.state.items, el => this.createElement(el))}
                </ReactGridLayout>
             <form action="/wp-admin/admin-post.php" method="post" target='dummyframe'>
                   <input type="hidden" name="grid" id="items" required="" value={JSON.stringify(this.state.items)}/>
                  <input type="hidden" name="action" value="handle_directions_post" />
            <input type="submit" value="Save" />
            </form>
              </div>
            );
          }
        }    
    
    
    

    export default Grid;
