### ISSUE TITLE
Fix resizing state issue with react-resizable on 0.4.0

### ISSUE THREAD

**Issue by STRML** [STRML/react-grid-layout#71]
There is an odd state issue caused by the new versions, but we need to upgrade b/c of IE support.

`0.9.2` is a broken version as a result and has been unpublished. If you need IE support, please wait. If not, use `0.9.1`.

**Comment by Surreal9** [comment]
How can I install 0.9.1? npm install puts in 0.8.3

**Comment by STRML** [comment]
You can't. I unpublished it because it was too unstable. You can always
install via github url and tag if you really want it.
