### ISSUE TITLE
What are grid units?

### ISSUE THREAD

**Issue by wzup** [STRML/react-grid-layout#710]
From here https://github.com/STRML/react-grid-layout#grid-item-props
```
// These are all in grid units, not pixels
```

What are `grid units`? How to map them to px?

**Comment by TrySound** [comment]
@wzup `props.rowHeight` and `props.width / props.cols`

**Comment by XeniaSiskaki** [comment]
@TrySound could you maybe provide an example?

**Comment by XeniaSiskaki** [comment]
@STRML I think this should be documented and maybe explained with a simple example? The examples are very helpful but I'm working with custom components and still cannot find out how those units work

**Comment by Semro** [comment]
@STRML Is there any way to control the size of grid unit? I want to make grid items with the same static width and height. Is it possible?

**Comment by parksj10** [comment]
> @wzup `props.rowHeight` and `props.width / props.cols`

If this were true, I think this example

```ts
<GridLayout
      className="layout"
      cols={100}
      rowHeight={10}
      width={1000}
      isDraggable={false}
      isResizable={false}
    >
```

would result in grid units of 10x10 px. However, as you can see [this sandbox](https://codesandbox.io/s/react-grid-layout-example-xy-m491bv?file=/src/layout.tsx:1841-1992), that is not the case...

@STRML and @TrySound , can you lend any light on this?

**Comment by parksj10** [comment]
for anyone else's reference.... I figured out the thing that was making it not work was the `margin` setting... so setting the following worked

```ts
<GridLayout
      className="layout"
      cols={100}
      rowHeight={10}
      width={1000}
      isDraggable={false}
      isResizable={false}
      margin={[0,0]}
    >
```

working example here: [Sandbox
](<GridLayout
      className="layout"
      cols={100}
      rowHeight={10}
      width={1000}
      isDraggable={false}
      isResizable={false}
    >)
