### ISSUE TITLE
When you create  a class to create grid Item, the css style does not get applied to the DOM

### ISSUE THREAD

**Issue by nywooz** [STRML/react-grid-layout#713]
Thanks for submitting an issue to R
![capture](https://user-images.githubusercontent.com/8634090/35513614-9b58c16a-04fb-11e8-8738-40f903cd9367.PNG)
GL!

Please mark the type of this issue:

- [ *] Bug
- [ ] Feature Request
- [*] Question

If you have a question or bug report, please use the [WebpackBin Template](https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI)

Sandbox:    https://www.webpackbin.com/bins/-L41DR7suQoPBVVo7IWX

to demonstrate. It is much easier for us to help you if you do.

**Comment by STRML** [comment]
You have not provided any useful information to debug this. Please read the docs & examples thoroughly and try again.

**Comment by nywooz** [comment]
Do you know(can you suggest) how i could access the DOM of  a GridItem on "draggableHandle" click ?

**Comment by STRML** [comment]
You don't, it's a selector. Read the draggable docs.
