### ISSUE TITLE
Unexpected behavior with verticalCompact  enabled in version 16.02

### ISSUE THREAD

**Issue by michal-lipski** [STRML/react-grid-layout#714]
- [X ] Bug
- [ ] Feature Request
- [ ] Question

There is some weird behavior when moving widgets introduced in the new version.
I have verticalCompact enabled. In version 15.03 it works ok:

Version 15.03 [example](https://drive.google.com/file/d/1DFYsTWNpsYzoHd03D94Xngx-vGxpSUmA/view?usp=sharing)

But in version 16.02 when I want to move one element the other is unexpectedly taking free space and jumps to the top and stays there. See example:

Version 16.02 [example](https://drive.google.com/file/d/1HDoc_Pxbd9sz0ite7ETIYZ_QvL6WtxO6/view?usp=sharing)

**Comment by michaelroevievictoria** [comment]
Can you guide how to it mate ? :) I have an issue in [#720](https://github.com/STRML/react-grid-layout/issues/720)
