### ISSUE TITLE
Linter balks at use of reserved word for key.

### ISSUE THREAD

**Issue by cmelion** [STRML/react-grid-layout#72]
<div className="column-group" key={1} _grid={{x: 0, y: 0, w: 2, h: 1, static: true}}>
                    <span className="pull-left column-header">CATEGORIES</span>
                </div>

src/pages/index/template.jsx
  14:61  error  Reserved word 'static' used as key  no-reserved-keys

**Comment by STRML** [comment]
There's nothing technically wrong with using a reserved word as a key. If your linter won't be quiet about it, just quote the key.
