### ISSUE TITLE
ResponsiveGridLayout not taking the Layout options passed through state to layout prop

### ISSUE THREAD

**Issue by kailashvele** [STRML/react-grid-layout#724]
ResponsiveGridLayout is not taking the layout options provided through layout props.

All the child falls one below the other instead of aligning on row basis.

Demo can be found here: https://codesandbox.io/s/mqq7vjrnzp

Default values to layouts is passed but not rendered as expected, expected sequence is: ABC3, ABC2, ABC1

**Comment by kailashvele** [comment]
Hey, any update on this?

**Comment by Tim152** [comment]
I got the same

**Comment by Tim152** [comment]
The same..

**Comment by kailashvele** [comment]
Hey Guys, I guess I made some mistake in implementing it the first time. Second time I copied the example provided and it worked for me. So m closing this. Anybody wants to get their problem resolved please send your code snippet via https://codesandbox.io/ I will try to check if you made the same mistake as I did. Thanks!

**Comment by Tim152** [comment]
Oh, you are right) I did mistake too
