### ISSUE TITLE
Cannot read property 'onLayoutChange' of undefined

### ISSUE THREAD

**Issue by msimonian77** [STRML/react-grid-layout#726]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [x ] Bug
- [ ] Feature Request
- [ ] Question

I'm trying to get any of the demo examples to work but keep getting this error in the browser.
Cannot read property 'onLayoutChange' of undefined.
In this function:
onLayoutChange(layout) {
    this.props.onLayoutChange(layout);
I have the following versions installed and working on windows:
"react": "^16.2.0",
"react-dom": "^16.2.0",
"react-grid-layout": "^0.16.3",
"react-scripts": "1.1.0"

Thank  you

**Comment by Geo1290** [comment]
Seems the code is intended to get onLayoutChange function prop from parent(Probably should add a check for this particular prop exist)
Try removing the line "this.props.onLayoutChange(layout);"

**Comment by msimonian77** [comment]
this fixed it:
onLayoutChange={() => this.onLayoutChange}
onBreakpointChange={() => this.onBreakpointChange}

But there is no resizing. How do I turn that on? I literally used the exact code from this sample:
https://github.com/STRML/react-grid-layout/blob/master/test/examples/6-dynamic-add-remove.jsx

but there is no resizing widget on the bottom right corner as they are showing it.

**Comment by nochkin** [comment]
I know I'm late on this, but I hope it will help someone else who may stumble upon that.
Besides removing the line "this.props.onLayoutChange(layout);", I also had to bind "onLayoutChange" in the constructor just after "this.onAddItem" line:
`this.onLayoutChange = this.onLayoutChange.bind(this);`
