### ISSUE TITLE
shrink adjacent element when no space for sizeup.

### ISSUE THREAD

**Issue by audriu** [STRML/react-grid-layout#728]
- [ ] Bug
- [ ] Feature Request
- [X] Question

Can I have on size increase of an element reduce size of an adjacent element if there is no space instead of compacting them.

**Comment by STRML** [comment]
I have no plans to support this and it would be very difficult to pull off - many questions to answer, like:

* Which elements are eligible for a resize?
* What is the minimum size an element can be automatically resized to?
* Does the direction of the resize affect auto-shrink?
* Should elements have priority over one another?
* Should a move also trigger a shrink, or just a resize?

Answering all of those questions will take a long amount of time and I don't intend to introduce that kind of complexity into this library.
