### ISSUE TITLE
Full width grid items in responsive grid

### ISSUE THREAD

**Issue by Puffton** [STRML/react-grid-layout#73]
This is using RGL 0.9.1 with the latest version of React. Despite the following settings on my GridItems:

    minH: 1,
    minW: 1,
    maxH: Infinity,
    maxW: Infinity

I cannot stretch them across the entire width of the responsive grid layout. Is this a bug or a feature (full width items might make responsive layout hard)?

EDIT: A more coarse grid (less cols) alleviates the problem to some extent, allowing me to use one full-width GridItem, but any items after that cannot be full with (and the more items I add, the less wide the most recently added GridItem is allowed to grow).

EDIT 2: Setting the xxs-grid to 0 cols solves it with certain col sizes for the other grid sizes, but then I have pretty much lost the responsive functionality.

**Comment by STRML** [comment]
This no longer appears to be an issue.
