### ISSUE TITLE
[Bug] Changing Grid Item "height" doens't change Resizable Height

### ISSUE THREAD

**Issue by retromime** [STRML/react-grid-layout#731]
Hi.
I have a problem with Grid Item.
They started with specific configuration taken from DB. An action above every Grid Item, allow user to collpase the GridItem. 

![screen00](https://user-images.githubusercontent.com/36157490/36381634-89c17f64-1586-11e8-80db-b7692df89ea2.png)
As you can see, height attribute is 5 (I printed it on header too). The height of resizable is 190.

When tapping on the icon to collapse, I change the state of item to force rewrite. As you can see on the second image, The height is now 1. I choose 1 because the final result is like the other item on the left (titled "Primo"). Unfortunally, as you can see from debugger, the height parameter is correctly "1" but the height of Resizable component remain 190.

![screen01](https://user-images.githubusercontent.com/36157490/36381446-e19694fa-1585-11e8-97d8-0ff9b42c76f7.png)

Is this a bug or I'm missing something?

Thanks you!

**Comment by jan0991** [comment]
Same, any solution?
