### ISSUE TITLE
Scrollbar inside a DIV causes the widget to be dragged

### ISSUE THREAD

**Issue by derwaldgeist** [STRML/react-grid-layout#735]
If a widget contains a scrollable DIV, it sometimes happens that dragging the scrollbar also causes the widget to change its position, especially if you drag the scrollbar quite quick and far (and also drag a vertical scrollbar along the x axis at the same time).

On my Mac with Google Chrome, the widget moves to another position once I release the mouse.

On Windows 7 and IE 11, however, the widget will stick to the mouse once you click on a scrollbar. You have to click the right mouse button to release the widget from dragging. Interestingly, this doesn't happen on Windows 10 and IE11.

Probably a problem with `react-draggable`, but not sure.

**Comment by raki1238** [comment]
Iam using this option draggableHandle='.card-header' so that we can drag the widget when clicked on header.

**Comment by derwaldgeist** [comment]
I had recently a report that this also happens if you click inside a textbox and try to mark text with the mouse. In this case, the widget is dragged around instead of marking the text.

**Comment by developersamim** [comment]
I am facing this issue on Windows 7 and IE11. Whenever I click on scrollbar inside div, the whole div sticks to the mouse.

**Comment by derwaldgeist** [comment]
I had to disable dragging on Win7/IE11 completely.
