### ISSUE TITLE
Is there a way to disable resize but keep move functionality?  (It seems static=true fuses both.)

### ISSUE THREAD

**Issue by JohnVLinton** [STRML/react-grid-layout#737]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI)
to demonstrate. It is much easier for us to help you if you do.

**Comment by sbrichardson** [comment]
Instead of using `static` you can separate into `resizable` and `draggable`

**Comment by JohnVLinton** [comment]
Thanks that worked great!
