### ISSUE TITLE
Collision cascades cause rearrangement

### ISSUE THREAD

**Issue by STRML** [STRML/react-grid-layout#739]
See https://github.com/STRML/react-grid-layout/pull/729#issuecomment-368576689

Imagine a collision like in this example:

![draggable-compact-cascade](https://user-images.githubusercontent.com/1197375/36684687-c520dffe-1ae6-11e8-847e-2d471be43371.gif)

When 9 intersects with 12, we don't move 12 down because it would immediately compact back up. *However*, the code actually does move 12, and by extension, 16 and 19, down temporarily, then compacts them back. You don't see this visually, but it can manifest in certain low-height items switching position.

It will take some work to write test cases for this to ensure we don't regress. Happily accepting PRs for failing test cases that demonstrate this behavior, so we can move forward on fixing.

**Comment by torkelo** [comment]
seems my fixes in https://github.com/STRML/react-grid-layout/pull/650 are no longer effective after this commit, 

https://github.com/STRML/react-grid-layout/commit/15503084fb7b0af826427c8c0706901e5745a39f

**Comment by STRML** [comment]
I refactored those changes and all the original test cases are passing, perhaps you can add another failing test case?

**Comment by torkelo** [comment]
@STRML when you refactored the tests I think you changed what the tests actually tested, when I restore the tests to how they looked after my PR they fail in current master as they the scenarios they test for are not handled correctly again

**Comment by torkelo** [comment]
your https://github.com/STRML/react-grid-layout/commit/15503084fb7b0af826427c8c0706901e5745a39f commit changes so much so it's' very hard to see the changes (the test file moved for example),

I managed to restore one important test (there are more) this is just an example:
https://github.com/grafana/react-grid-layout/commit/a5caad51bffad5ed213bea3b030dc1fd452989bb 

Those changes competently changes the scenario. If I restore the test it very accurately breaks (in current master) as it shows the buggy movement is now back. if I go back to the commit before https://github.com/STRML/react-grid-layout/commit/15503084fb7b0af826427c8c0706901e5745a39f  the test passes and all the buggy behavior is gone. 

The sad part is that that commit was done before 0.16.1 so there is no published version that works. I should have spotted this early but have been using yarn linked local version with a commit before yours so had not noticed this until after we started to get bug reports in Grafana v5 beta. 

I do not have time right now to figure out what went wrong but your change of refactoring resolveCompactionCollisionByMovingItemDown to resolveCompactionCollision seems to miss a lot of logic and restore many of the bugs as well as the revert of some of my changes to  moveElementAwayFromCollision that  also seems to restore the buggy behavior. 

I would suggest reverting that refactoring and starting the refactoring a new.

**Comment by STRML** [comment]
From https://github.com/grafana/react-grid-layout/commit/a5caad51bffad5ed213bea3b030dc1fd452989bb#commitcomment-27815320, it appears the changed tests are correct, but I am unsure of what causes the new movement bugs.

Can anyone capture a GIF of some bad behavior so we can start building test cases?
