### ISSUE TITLE
Resize Constraint Glitch When Grid Width Changes

### ISSUE THREAD

**Issue by NSinopoli** [STRML/react-grid-layout#74]
Using this [jsfiddle](https://jsfiddle.net/69z2wepo/10018/), here are the steps to reproduce:

1. Find the bottom-most grid item and resize it to its maximum possible width.
2. Click the "Toggle Grid Width" link at the top.
3. Find the same grid item (from step 1) and try to resize it. Watch how the grid item instantly reduces in size, and how it cannot be expanded to the full width of the grid anymore.

**Comment by STRML** [comment]
Thanks for the good reproduction. A similar bug has caused me to unpublish 0.9.2 from npm.

There is some state lying inside react-resizable and react-draggable that can make this difficult to deal with. I would like to make them more stateless or at least have the option to be 100% stateless and rely on the user to properly set left/top and width/height via the parent component.

This will require some reworking of those projects.

**Comment by NSinopoli** [comment]
Hm. Do you mean that you'd rather have the parent component pass in the mouse coordinates?

**Comment by STRML** [comment]
Basically, [this state from react-draggable](https://github.com/mzabriskie/react-draggable/blob/master/lib/draggable.js#L512) and [this state from react-resizable](https://github.com/mzabriskie/react-draggable/blob/master/lib/draggable.js#L512) causes issues. I've tried some hacks to allow external resetting of this state but it's all bad hacks. I need to rearchitect it.

**Comment by NSinopoli** [comment]
Do you mean [this state from react-resizable](https://github.com/STRML/react-resizable/blob/master/lib/Resizable.jsx#L36)?

What can I do, if anything, to help?

**Comment by STRML** [comment]
Revert back to `0.8.3`, which [doesn't exhibit this bug](https://jsfiddle.net/69z2wepo/10020/).

Unfortunately I will have to unpublish all of `0.9`. A fixed version will be `0.10.x`.

**Comment by NSinopoli** [comment]
Great, thanks. Any idea of when `0.10.x` will be released?

**Comment by STRML** [comment]
I have a few other projects that are taking up all of my time right now so RGL can't be a priority (I don't use it in any of my projects yet). If you're brave, you could fork react-draggable and resizable and take a crack at it. Otherwise I would expect to get to it this weekend.

**Comment by NSinopoli** [comment]
Okay, thanks for letting me know. And thanks again for all of your great work with these libraries!

**Comment by NSinopoli** [comment]
Any luck with this?

**Comment by lklesch** [comment]
This would be extremely helpful.

**Comment by marcneuwirth** [comment]
Any updates on this bug?

**Comment by STRML** [comment]
This is fixed in `0.10`.
