### ISSUE TITLE
Feature Request: Toolbox

### ISSUE THREAD

**Issue by jhob** [STRML/react-grid-layout#740]
It would be great if we could dynamically add/remove widgets from RGL by dragging them into a toolbox widget.

**Comment by STRML** [comment]
Know anybody with the skills to :shipit:?

**Comment by jhob** [comment]
I have a work in progress [in this fork](https://github.com/jhob/react-grid-layout), with a [demo viewable here](https://jhob.github.io/react-grid-layout/examples/14-toolbox.html).

I'm currently working through two pesky issues:
- Items can reappear after being moved into toolbox, occurs primarily on non-default responsive sizes. Can be resolved by skipping the recovery of a 1x1 widget within `synchronizeLayoutAndChildren`, called in `ReactGridLayout::componentWillReceiveProps`, although a tidier solution might exist.
- Switching between responsive breakpoints with items in the toolbox can create issues. In particular, items can exist both in the grid layout and in the toolbox. A responsive toolbox solution is in progress.

**Comment by JLindwick** [comment]
I really love the repo, i'm simply trying to use this without the generate dom and random elements. I want to use the components I have in place of them and i can't figure out how to allow for ontake and onput and the toolbox item itself without the ._map and item.i ... sorry if its a noob question

**Comment by pinesh** [comment]
> I really love the repo, i'm simply trying to use this without the generate dom and random elements. I want to use the components I have in place of them and i can't figure out how to allow for ontake and onput and the toolbox item itself without the ._map and item.i ... sorry if its a noob question

6 years later I have this exact challenge too!
