### ISSUE TITLE
Add class to Item being dragged

### ISSUE THREAD

**Issue by Fuasmattn** [STRML/react-grid-layout#744]
I'd like to add some css styling to it while it is moving. 
Is there an easy way to get the currently dragged item object? 

- [ ] Bug
- [ ] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI)
to demonstrate. It is much easier for us to help you if you do.

**Comment by 0x6c23** [comment]
On default an item will have the classname `react-grid-item react-draggable`, if you drag an item the classname `react-draggable-dragging` gets added. 

If you want to do things like scale, it wont work with just css. You would need to change the translate given by the library and divide x and y values by the scale factor, you can do that easily if you fork the repo.

In `/lib/utils.js` add the scale factor to the translate in the function `setTransform`
Also, in `/lib/GridItem.jsx ` add your scale factor to the `calcPosition` function

You should add something along the lines of:
```

out.scale = scaleFactor;
out.top = out.top / scaleFactor;
out.left = out.left / scaleFactor;
```

to the  `(state && state.dragging)` condition.
