### ISSUE TITLE
Input is not accessable in dragn drop

### ISSUE THREAD

**Issue by holzfelix** [STRML/react-grid-layout#747]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [x] Bug
- [ ] Feature Request
- [ ] Question

When I add input fields into a draggable object I'm not able to type into the inputs with an onchange handler.

What could be the problem?

**Comment by SchroederChris** [comment]
I just encountered the same issue. If you don't need dragging on the complete grid element, you can specify a css selector as the grid-layout's `draggableHandle` property. That way, dragging doesn't influence the rest of your element. I didn't dig deeper to find out what exactly happens that breaks the input though.

**Comment by holzfelix** [comment]
@SchroederChris can you maybe show a code snipped how you use draggableHandle.

I tried this: `draggableHandle={`panel`}` as attribute on `ResponsiveReactGridLayout` ... but full div is draggable and not onle the class called panel

**Comment by SchroederChris** [comment]
It's just a string property where you specify a regular css selector. My code looks like this:
`draggableHandle=".card-view > header"`

**Comment by jog39** [comment]
@holzfelix did you manage to make it work? I found that the example with draggableHandle doesn't work (you can drag from anywhere inside your GridItem) and thus the input is still bugged.

**Comment by holzfelix** [comment]
yes it works now. 

this worked for me:

` draggableHandle=".dragMe"`

**Comment by jog39** [comment]
Not working for me, my item is:

`<div key="param" data-grid={{x: 0, y: 0, w: 2, h: 2, draggableHandle: ".drag-handle"}} >
                        <span className="drag-handle">Drag Here</span>
                        <br/>
                        <label>Name :<input type="text"/></label>
                    </div>`

The whole item remains draggable and input don't keep focus..

**Comment by holzfelix** [comment]
for me that looks not correct! 

why do you add those stuff to a div?
you have to call the react component


```
 <ResponsiveReactGridLayout className={`layout`}
                                                           breakpoints={{
                                                               lg: 0,
                                                           }
                                                           }
                                                           cols={{
                                                               lg: 12,
                                                           }
                                                           }
                                                           layouts={this.state.layouts}
                                                           draggableHandle=".dragMe"
                                                           onBreakpointChange={this.onBreakpointChange}
                                                           onResizeStop={this.onResize}
                                                           onLayoutChange={this.onLayoutChange}>
                                    {
```

and inside the react component you have elements with css class

**Comment by jog39** [comment]
I got it working, thanks. I was following the example which does it the way I showed it (directly on layout or item properties).

**Comment by hedibertosilva** [comment]
thanks, it worked for me.

**Comment by Distil62** [comment]
It's work for me too thanks !

**Comment by renakim** [comment]
It's working! Thanks!

**Comment by yousefkhan** [comment]
You can also use `draggableCancel=".dontDragMe"`
For me it was more appropriate.

**Comment by fesaza** [comment]
Using the `draggableHandle` property fixed if you don't need draggable behaviour. How can I fix that if I need my component to be draggable? Thanks in advance

**Comment by speckJ8** [comment]
I had this same problem but neither `draggableCancel` nor `draggableHandle` were working for me. 
I don't know why, maybe because I had nestedd `GridLayout`s.
I solved the problem by using `onMouseDown={(e) => e.stopPropagation()}` in my text box.
Hope this helps someone.

**Comment by balatvm** [comment]
My component has input field and this component needs to be draggable. any solution?
Currently it's working. (unable to type in in the input box)
