### ISSUE TITLE
Versions 9.x have disappeared from npmjs.com

### ISSUE THREAD

**Issue by simondean** [STRML/react-grid-layout#75]
Hi. The 9.x versions of react-grid-layout seem to have disappeared from npmjs.com.  The registry is now showing 0.8.3 as the latest version: 

```
strml published a month ago
0.8.3 is the latest of 33 releases
```
https://www.npmjs.com/package/react-grid-layout

It's also affecting installing the module from the command line via npm. The npm command is also showing 0.8.3 as the latest version. 

I already have 0.9.1 installed from a few days ago but now 0.9.1 will no longer install because of the above issue

Thanks

**Comment by STRML** [comment]
Yes, this was intentional. The 0.9.x versions have a major bug in the resizable component. No new features were introduced in 0.9.x so rather than expect my users to live with the bug until I fix it, I unpublished the version.

**Comment by STRML** [comment]
Use 0.8.3.

**Comment by simondean** [comment]
Thanks for the information @STRML
