### ISSUE TITLE
With no vertical compaction, can't drag past some boxes to top, and bugs resolving collisions

### ISSUE THREAD

**Issue by brian-eightsolutions** [STRML/react-grid-layout#750]
- [x] Bug
- [ ] Feature Request
- [ ] Question

When vertical compaction is turned on, some boxes can't be dragged through. If you try to drag one tile through another to the top of the screen nothing happens.

Also, when moving a box in a way that will push another box down, the collision resolving logic sometimes pushes the box far too far down. (This one is mentioned by jackie-benowitz 
in another issue: https://github.com/STRML/react-grid-layout/issues/720).

The following example is from the example page "React-Grid-Layout Demo 11 - No Vertical Compacting (Free Movement)":
![no_compaction_collision_bug](https://user-images.githubusercontent.com/34519927/37065932-e7e80c7a-2157-11e8-91d1-a7de9d2756fc.gif)

**Comment by brian-eightsolutions** [comment]
The one line fix I have submitted actually fixes both of the issues. That line (in `moveElementAwayFromCollision()`) is supposed to move the box away from the collision, but when vertical compaction is on, doesn't move it at all. This causes bugs further downstream when `resolveCompactionCollision()` runs.

**Comment by FoxxMD** [comment]
Looking forward to a solution for this...
