### ISSUE TITLE
Resizable handles on other corners

### ISSUE THREAD

**Issue by zhangzhike** [STRML/react-grid-layout#758]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [x] Feature Request
- [ ] Question

If you have a question or bug report, please use the [WebpackBin Template](https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI)
to demonstrate. It is much easier for us to help you if you do.
![image](https://user-images.githubusercontent.com/20389990/37500355-05bd5cce-2904-11e8-9a06-ccea3d27f6c6.png)

**Comment by luminaxster** [comment]
Perhaps allowing a similar behavior to ```draggableHandle``` will be faster.

**Comment by zhangzhike** [comment]
Yes, but I still want to support the drag of other anchor points in my use.

**Comment by cannc4** [comment]
As you closed the other issue, do you have any updates on this feature?

**Comment by pingbaohua** [comment]
你上面的功能实现了吗，可以讲解一下吗，需要做此功能

**Comment by zhangzhike** [comment]
没有实现，只是做了四周的描点，没支持拖拽

**Comment by btargac** [comment]
any updates on 2019 ?

**Comment by mankinchi** [comment]
Any update would be nice

**Comment by abenhamdine** [comment]
needs https://github.com/STRML/react-resizable/pull/76 to be merged in react-resizable first

**Comment by MilesMorel** [comment]
@abenhamdine looks like it was merged recently. How can we pass resize handle placement (n/w/s/e/se/sw/ne/nw)? I need this for a project and so do a few others on #503 it appears. Happy to help if it isn't already in the works.

**Comment by mankinchi** [comment]
and @abenhamdine, will there be a plan to push this onto npm version? I think the npm version is a bit behind compared to this.

**Comment by MilesMorel** [comment]
@abenhamdine Is there any news on this? Otherwise, will plan to submit a PR soon.

**Comment by abenhamdine** [comment]
> and @abenhamdine, will there be a plan to push this onto npm version? I think the npm version is a bit behind compared to this
> @abenhamdine Is there any news on this? Otherwise, will plan to submit a PR soon.

Unfortunately, I can't talk on behalf of the maintainer which I assume is very very busy.

**Comment by MilesMorel** [comment]
@STRML I understand you're very busy. Do you know if this is already in progress? Would you support a PR for this? Will try to get something up soon if no one else is working on it.

**Comment by bhumi0901** [comment]
Hello
I need to show resizable handles at every corner of the component. Is there any way I can achieve this using react-grid-layout?

**Comment by eheu** [comment]
Example of overriding CSS rules to position handle center south:
`/* Overriding css rules to allow the resize handle to be positioned center south.
   Will be deprecated once this feature is implemented in react-grid-layout.
   See: https://github.com/STRML/react-grid-layout/issues/758 */
.react-resizable-handle {
  background-image: initial;
}

.react-resizable-handle-se {
  /* bottom: 0 !important; */
  left: 50%;
  transform: rotate(45deg);
}

.react-grid-item > .react-resizable-handle {
  cursor: s-resize;
  bottom: -6px;
}

.react-grid-item > .react-resizable-handle::after {
  right: initial;
}`

**Comment by n1ghtmare** [comment]
@MilesMorel Go ahead, your PR would be much welcomed. If you need us to review your PR, tag me and @daynin

**Comment by otisg** [comment]
@MilesMorel another +1 for your PR for this. Thanks!

**Comment by cannc4** [comment]
Is this merged now? :)

**Comment by MilesMorel** [comment]
My friend and I made these changes, added some more advanced handling for drop hints, and fixed a few subtle bugs in RGL in a fork we're using. It's quick and dirty but it works so let me see if we can put together some PRs and you guys can do what you like with them. Should have time in a few weeks.

**Comment by kaleem-elahi** [comment]
Hey @MilesMorel  Did you found any way to do?

Please,  Let me know, It may be helpful to all of us!

**Comment by rlgreen91** [comment]
I know this is closed, but I'm interested in this functionality as well.   Javascript isn't my strongest language, but if there's anything I can do to help @MilesMorel please let me know.
