### ISSUE TITLE
Restrict Dragging outside parent div

### ISSUE THREAD

**Issue by vpn1997** [STRML/react-grid-layout#761]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [x] Question

If you have a question or bug report, please use the [WebpackBin Template](https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI)
to demonstrate. It is much easier for us to help you if you do.

- Hey i want to restrict the Draggable component movement outside the parent div , like how (https://github.com/clauderic/react-sortable-hoc) provides lockoffset prop that defines the percent of component that can go outside the parent div boundary. Please  help me out . :smile: 

-Video (https://drive.google.com/file/d/1zAlrEu8gv0QgrntmXwOnvLEeVHZg51ym/view).
I dont want the component to go outside the scollable div.

**Comment by dev-end** [comment]
The dragging in your case can be solved by using css overflow : hidden(Property). But in your video it looks like after releasing the mouse your component still stays outside the div. This might be because your compact types are false.
