### ISSUE TITLE
Lose ability to drag and resize when the page is loaded again in a SPA

### ISSUE THREAD

**Issue by cmccar** [STRML/react-grid-layout#763]
- [ ] Bug
- [ ] Feature Request
- [ x] Question

I have a single page application website and I am trying to use RGL to create an admin dashboard type page.

When I first load the page which uses RGL, or when I click the refresh button and do a hard refresh, the RGL works great and as expected, all dragging and resizing works well.

However, when I navigate away from the page and then back to it via hyperlinks in the SPA, the grid items lose the ability to be dragged, and the resizing works only for the height dimension, cannot resize the width.

At the top of the dashboard component's .jsx file, I have the following defined:
`
const WidthProvider = ReactGridLayout.WidthProvider;
const Responsive = ReactGridLayout.Responsive;
const ResponsiveReactGridLayout = WidthProvider(Responsive);
`

I have done it this way because I am not using Node.js / Webpack, and this is the only way I seem to be able to use ResponsiveReactGridLayout.

I'm not sure if that may cause this issue, I only mention it because that is the main thing I have done that is a bit different than the documented use cases.

Appreciate any help in advance, thanks.

**Comment by ttamminen** [comment]
> However, when I navigate away from the page and then back to it via hyperlinks in the SPA, the grid items lose the ability to be dragged, and the resizing works only for the height dimension, cannot resize the width.

I have the same issue! I am also using the `WidthProvider`. 

The version I am using is 0.16.6, I haven't figured out yet what is causing this.

**Comment by ttamminen** [comment]
In my case, I have dashboards that can be switched using a tab control. Each dashboard has react-grid-layout instance. When I change from the initial dashboard to the second one the problem occurs.

It seems that the width is not calculated.

![image](https://user-images.githubusercontent.com/1038081/37707592-53e64bac-2d0c-11e8-88f6-d237f67b4f59.png)

As a test, I ran `window.dispatchEvent(new Event('resize'));` in the console and widget size and resize works correctly.
