### ISSUE TITLE
WidthProvider does not work in  0.16.6? 

### ISSUE THREAD

**Issue by ilovepumpkin** [STRML/react-grid-layout#765]
Please mark the type of this issue:

- [ x ] Bug
- [ ] Feature Request
- [ ] Question

I am using 0.16.6. If I use Responsive Grid Layout with WidthProvider, I got the following. 
```
import { Responsive, WidthProvider } from 'react-grid-layout';
const ResponsiveReactGridLayout = WidthProvider(Responsive);
...
<ResponsiveReactGridLayout
        className="layout"
        layouts={layouts}
        cols={cols}
        breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
        rowHeight={30}
      >
        <div key="a">...</div>
        <div key="b">...</div>
        <div key="c">...</div>
      </ResponsiveReactGridLayout>
```

![image](https://user-images.githubusercontent.com/11310645/37761143-d0fe5c64-2df3-11e8-8cbb-8cb0329590ff.png)

As you can see the blue line is actually a border, but looks like the width is 0 now. Then I change to use it without WidthProvider, and manually set width property - everything works fine now. 
```
import { Responsive, WidthProvider } from 'react-grid-layout';

...
<Responsive
        className="layout"
        layouts={layouts}
        cols={cols}
        breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
        rowHeight={30}
       width={1200}
      >
        <div key="a">...</div>
        <div key="b">...</div>
        <div key="c">...</div>
      </Responsive>
```

I am not sure if this is a bug since all your demos on your website are working well. Are they built with the latest version(i.e. 0.16.6)?

**Comment by ilovepumpkin** [comment]
@species-gh Thank you for confirming this! Since this is not a bug, let me close this issue and look into it further.

**Comment by webberwang** [comment]
Any reason why this issue has been closed? The error still persists, the referenced issue doesn't solve the problem either

**Comment by l0x0s** [comment]
could you give a code example of your bug ?

**Comment by webberwang** [comment]
@l0x0s my mistake it was some other issue
