### ISSUE TITLE
Issue horizontal compactType

### ISSUE THREAD

**Issue by mishaseniv** [STRML/react-grid-layout#767]
When I set compactType:"horizontal" and cols:2 started something very weird happening.

This is your example on the git repository

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/11869216/37796400-e0822b4e-2e1f-11e8-8a53-37dcd42cd533.gif)

**Comment by iamranjanbatra** [comment]
I also seems to have similar issue, where all the components are getting shuffled to random on setting compactType = "horizontal".
Did you find any solution to this issue?
