### ISSUE TITLE
On GridLayout re-render, GridItem unmount children 

### ISSUE THREAD

**Issue by Yorack** [STRML/react-grid-layout#768]
Hello,

Here is my issue: 
I have 2 mode for my `<GridLayout />`
  - EDIT MODE : component can be moved / resized
  - RUN MODE : component are static 

i do it like this : 
![image](https://user-images.githubusercontent.com/7511509/37823739-aa48cb94-2e8a-11e8-805f-d86a4ec94c5c.png)

When i switch between the 2 mode it **unmount** my children so i lose all their state and such.

i think it come from this : 
![image](https://user-images.githubusercontent.com/7511509/37823531-0c6ba540-2e8a-11e8-817f-38c4cdd4b51f.png)
=> In the GridItem render method.

So can i avoid this unmounting in any way ?

**Comment by hdwatts** [comment]
I am running into this issue as well, is there any way to avoid this re-mounting?

**Comment by Fensterbank** [comment]
This seems to be a duplicate of https://github.com/STRML/react-grid-layout/issues/721 where you also find an ugly workarround which I did not test.

For me this is a major issue of the library and it's very imperformant if you have lots of complex components like in my project.

**Comment by Yorack** [comment]
i've got some workaround too based on the `componentWillReceiveProps` function that may get my previous state on remounting but i prefer not to rely on it too much, if i find something stable i might post it but  i just expect they fix it :)

**Comment by Fensterbank** [comment]
Will be fixed by #892.

**Comment by sparkle777** [comment]
I am running into this issue as well, is there any way to avoid this re-mounting?
