### ISSUE TITLE
Resizable Handle

### ISSUE THREAD

**Issue by vagnervjs** [STRML/react-grid-layout#77]
As we have `draggableHandle`, will be great have a `resizableHandle` too.
I fast looked the code... there is some obstacle to implement? (I know that in fact this should be implemented in react-resizable)

**Comment by Puffton** [comment]
This is already mentioned in the README TODO, isn't it?

"Resizable handles on other corners"

**Comment by dmr** [comment]
First, thanks for this great project!
In the demos I can see and use the resize handle but if I install it in my own project it doesn't show up.
Anyone else with this problem?

**Comment by STRML** [comment]
@dmr You are likely missing the styles - make sure you are importing or copy/pasting https://github.com/STRML/react-grid-layout/blob/master/css/styles.css

**Comment by dmr** [comment]
That's what I thought at first also, but I included the styles and it's probably some weird CSS of my app around it ^^, I'll debug it tomorrow.

**Comment by nishanth83Ya** [comment]
Hi @dmr - were you able to debug and resolve the issue? I have the same.

**Comment by nishanth83Ya** [comment]
I figured it out. I needed the following two statements:

    <link href="../node_modules/react-grid-layout/node_modules/react-resizable/css/styles.css" rel="stylesheet" type="text/css" >
    <link href="../node_modules/react-grid-layout/css/styles.css" rel="stylesheet" type="text/css" >

**Comment by dmr** [comment]
If I remember correctly wie solved the issue by including the CSS manually
