### ISSUE TITLE
Show separator lines for grid empties

### ISSUE THREAD

**Issue by Jero786** [STRML/react-grid-layout#78]
How can I show the available grids? apply border css style.  Like I show the following example:

![image](https://cloud.githubusercontent.com/assets/1815487/8295199/b847121c-1918-11e5-8536-6af0cef91339.png)

I want to mark a grid empty to make a references rules.
Thanks!

**Comment by STRML** [comment]
This is outside the domain of this project - there are no actual elements there. I would recommend overlaying an element or draw with SVG to do so.
