### ISSUE TITLE
Cannot resize an item when "preventCollision" :  true

### ISSUE THREAD

**Issue by nywooz** [STRML/react-grid-layout#780]
- [ ] Question

`preventCollision: true`

This is your example from **https://strml.github.io/react-grid-layout/examples/12-prevent-collision.html** 

Is it possible to resize when "preventCollision" :  true . Is this the intended purpose or will that be considered a bug?

While i am here may I suggest to edit the following please
OLD:
If you have a question or bug report, please use the [WebpackBin Template](https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI)
![image](https://user-images.githubusercontent.com/8634090/38077682-baa73844-3331-11e8-8ef4-b037aaa08f23.png)

**Comment by SomethingSexy** [comment]
What version are you running? I had this issue in 0.16.3 but it seems to be working on 0.16.6.  It won't resize if it would collide with something below it but I am able to freely resize otherwise.

**Comment by nywooz** [comment]
I am running 0.16.2 at the moment. Tried upgrading to 0.16.6, working fine. Great, Thank you @SomethingSexy
