### ISSUE TITLE
What is the best way to migrate saved layouts for new rowHeight 

### ISSUE THREAD

**Issue by sridharAJ** [STRML/react-grid-layout#785]
Please mark the type of this issue:
- [x] Question
- [ ] Bug
- [ ] Feature Request

My application Type : Flexible Dashboard platform. 
react-grid-layout version: 0.14.7

Usage:
```
import { Responsive } from "react-grid-layout";
import WidthProvider from "../SizeMe";
const ResponsiveReactGridLayout = WidthProvider(Responsive);

<ResponsiveReactGridLayout 
    cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }},
    breakpoints={{ lg: 600, md: 600, sm: 450, xs: 300, xxs: 0 }} 
    margin={[13, 13]}
    layouts={layouts}
    onLayoutChange={this.onLayoutChange}>
{widgets}
</ResponsiveReactGridLayout>
```
Right now I am using `rowHeight=150px`, and storing layouts config in databased. 
So here `1unit = 150px`. 

Now I have a new requirement were rowHeight should be `30px`. So if I simply change rowHeight props to `30px` all the existing saved widgets height are less because now `1unit=30px`. It affect the user view.

So now I need a generic script to migrate the existing config directly in database without affecting the user view.

Any best and easy way to do this?

**Comment by wzup** [comment]
@STRML any update on this issue?

BTW, connected issue https://github.com/STRML/react-grid-layout/issues/800

OP uses `rowHeight` in `px`. But you do not provide unit measurements for `rowHeight`

**Comment by dtaub** [comment]
In case anyone is still looking for this, I had the same issue and did some algebra to come up with a migration function:

```js
function migrateGridItemHeight(oldItemH, oldRowHeight, newRowHeight, margin) {
  return Math.round(
    (oldItemH * (oldRowHeight + margin)) / (newRowHeight + margin)
  );
}
```

This is assuming the margin didn't change. If it did, I'm sure it's still possible to migrate but you'd need to figure out the conversion.
