### ISSUE TITLE
[BUG] Unable to load layouts when not including them inline with the divs react v 16. & 16.6

### ISSUE THREAD

**Issue by ibolton336** [STRML/react-grid-layout#791]
When tesing this from the docs:
```
var ReactGridLayout = require('react-grid-layout');
 
var MyFirstGrid = React.createClass({
  render: function() {
    // layout is an array of objects, see the demo for more complete usage
    var layout = [
      {i: 'a', x: 0, y: 0, w: 1, h: 2, static: true},
      {i: 'b', x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4},
      {i: 'c', x: 4, y: 0, w: 1, h: 2}
    ];
    return (
      <ReactGridLayout className="layout" layout={layout} cols={12} rowHeight={30} width={1200}>
        <div key="a">a</div>
        <div key="b">b</div>
        <div key="c">c</div>
      </ReactGridLayout>
    )
  }
});
```

I am unable to see the layouts being applied. 
HOWEVER, when I only have one div element and only one layout in the layouts array, the layout is applied. 

ALSO, the layouts apply fine when I am applying them inline without passing them in via the layout prop.

**Comment by CWSites** [comment]
Please check the [Usage Docs](https://github.com/STRML/react-grid-layout#usage) your sample is very different from what is shown there. I was able to copy paste directly and it works for me in React v16.3

**Comment by kalyanixraut** [comment]
Even I am facing the same issue. The layout is applied only when its inline when using <ResponsiveReactGridLayout> component. Whereas it works via the layout prop only when <GridLayout> is used as in Usage Docs.

How can layout be applied using the layout prop as in Usage docs(<GridLayout>) for <ResponsiveReactGridLayout>

**Comment by kalyanixraut** [comment]
I found the solution in this issue #
ResponsiveGridLayout does not honor the provided layouts #803
