### ISSUE TITLE
How to drag a item between two ReactGridLayout

### ISSUE THREAD

**Issue by SunXinFei** [STRML/react-grid-layout#792]
- [ ] Bug
- [ ] Feature Request
- [X] Question

`<ReactGridLayout   layout={this.state.layout1}>
        {this.generateDOM()}
</ReactGridLayout>
<ReactGridLayout layout={this.state.layout2} >
        {this.generateDOM()}
</ReactGridLayout>
`
anyone resolve this question?

**Comment by fairps** [comment]
If it can be done I'd love to know as well... it may be possible since this is based on react-draggable and that library allows dragging outside of the containing control.

**Comment by SunXinFei** [comment]
@fairps  thankyou, but react-beautiful-dnd is only for list , the ReadMe.md say
> 
> Not for everyone
> There are a lot of libraries out there that allow for drag and drop interactions within React. Most notable of these is the amazing react-dnd. It does an incredible job at providing a great set of drag and drop primitives which work especially well with the wildly inconsistent html5 drag and drop feature. react-beautiful-dnd is a higher level abstraction specifically built **for vertical and horizontal lists**. Within that subset of functionality react-beautiful-dnd offers a powerful, natural and beautiful drag and drop experience. However, it does not provide the breadth of functionality offered by react-dnd. So this library might not be for you depending on what your use case is.
so I will try to use react-dnd to ceate a wheel  project just like GridLayout.

**Comment by fairps** [comment]
I've looked at this much further after my last comment... maybe PR #682 that is waiting to be merged might allow react-grid-layout to act as a drop target for incoming objects.  Don't underestimate the amount of work that has been done in react-grid-layout and react-beautiful-dnd beyond what react-dnd is offering out of the box... both are using react-motion to provide a drag experience that feels natural.  For me, the only difference right now between react-grid-layout and react-beautiful-dnd with a series of side by side lists is the inability to resize elements and have them extend across those columns (lists).  If PR #682 will allow the drop target, then I will use react-beautiful-dnd to create a toolbox of sorts and drag items from it into my primary react-grid-layout... or at least that's how I am leaning at the moment.

**Comment by SunXinFei** [comment]
@fairps  Yeah, I had used react-dnd successfully to complete card grid layout and move card to other list, see this in my drag gif.
![drag2](https://user-images.githubusercontent.com/5847281/39296187-d4032eae-4972-11e8-9767-23bcc59e562d.gif)

**Comment by martinwebrant** [comment]
@SunXinFei got a sample for that? About to do that myself!

**Comment by SunXinFei** [comment]
@martinwebrant    [my code](https://github.com/glud123/demo-main/tree/master/src/workbench_front/pages/DesktopSetting), you can view this code, but sorry  I did not have a sample for that, maybe complete the project，free time will commit a sample templete.
 I have been optimizing drag and drop render performance these days，

**Comment by fairps** [comment]
@SunXinFei thanks for posting that link.  I Really appreciate it.

**Comment by SunXinFei** [comment]
@fairps ，recently I have been optimizing and modifying this code

**Comment by blizzerand** [comment]
@SunXinFei  Hey, I've run into some trouble starting your code. Does it still work?

**Comment by SunXinFei** [comment]
> @SunXinFei Hey, I've run into some trouble starting your code. Does it still work?

oh!   I create the project [react-grid-layout-between](https://github.com/SunXinFei/react-grid-layout-between). you can run it, maybe it can help you  . when i'm not busy , i will create the component.

**Comment by blizzerand** [comment]
@SunXinFei  Thank you! Works perfectly well :)

**Comment by SunXinFei** [comment]
> @SunXinFei Thank you! Works perfectly well :)

@blizzerand  yeah, just a moment ago,  I  added the logic about switch Compaction Type: horizontal || vertical.

**Comment by akshaygoyal88** [comment]
@SunXinFei Have you completed the awesome functionality?

> @fairps Yeah, I had used react-dnd successfully to complete card grid layout and move card to other list, see this in my drag gif.
> ![drag2](https://user-images.githubusercontent.com/5847281/39296187-d4032eae-4972-11e8-9767-23bcc59e562d.gif)

**Comment by SunXinFei** [comment]
> @SunXinFei Have you completed the awesome functionality?
> 
> > @fairps Yeah, I had used react-dnd successfully to complete card grid layout and move card to other list, see this in my drag gif.
> > ![drag2](https://user-images.githubusercontent.com/5847281/39296187-d4032eae-4972-11e8-9767-23bcc59e562d.gif)

you can view this project https://github.com/SunXinFei/react-grid-layout-between

**Comment by fairps** [comment]
Not stale just ignored

**Comment by siccoo** [comment]
Hi Good morning all, please I want to achieve this http://mmoinuddin.com/assets/img/grid-layout-dnd.gif, the goal is to extend the algorithm, so a module can move within the layout container. The module can't move outside of the top, right, and left edges of the layout container. The bottom edge behaves differently. When a module is moved downwards beyond the bottom edge, the bottom edge should also move downwards to extend the height of the layout container. Also, Module objects cannot overlap each other.

So how can I achieve that using React-typescript

**Comment by spedy** [comment]
I solved it by creating two grids with isDraggable to false and followed the "Drag from outside" example.

**Comment by siccoo** [comment]
@spedy please can I see the code of how you implemented it .

**Comment by galangel** [comment]
@spedy can you share please?

**Comment by Zregnateews** [comment]
Hello all! I'm late to the party, but maybe it will help some future devs with the same issue. I made a working example here. Take a look and use if it helps you out.
Can drag from react-grid-layout to another, and even if they are childs of each other.

https://codesandbox.io/p/sandbox/react-dnd-grids-4vc9gl
