### ISSUE TITLE
Cannot add items so that grid is wider on bottom than on top

### ISSUE THREAD

**Issue by petervkay** [STRML/react-grid-layout#794]
- [x ] Bug
- [ ] Feature Request
- [ ] Question

I have developed a grid layout using [RGL Example 6](https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html) as a basis.  I have noticed a problem that is present in both your and my version.  I attached a screenshot of yours to demonstrate.
![rgl](https://user-images.githubusercontent.com/1514488/39054394-25b69ef8-4477-11e8-8ea0-251a3dd3743b.png)  If I add another item to the two shown in the screenshot, I would like to be able to drag it so that it sits to the right of the bottom box "n1".  However, this is not possible.  If I add more boxes to the top row, now I can add a box to the bottom row.

As a workaround, I may try automatically adding invisible boxes to the top of every grid so that there is already a full row of boxes at the top.  I hope this will work, but this seems to me like the library should have this functionality available out of the box.  Or is there something that I'm missing in the features? Or a more elegant workaround?

**Comment by STRML** [comment]
You need to turn off compaction to do that. By default, everything floats up to the top.

**Comment by petervkay** [comment]
Thank you for the quick response!

**Comment by petervkay** [comment]
Is there a way to make it so when dragging grid items into a new position, it always pushes existing items to the right (rather than moving them vertically or left)?
