### ISSUE TITLE
Wrong behaviour of onLayoutChange for responsive

### ISSUE THREAD

**Issue by wzup** [STRML/react-grid-layout#799]
`onLayoutChange`  returns wrong value for layout when responsive.

Suppose I have this layout. Two grid items in every breakpoint.
Suppose current breakpoint is `lg`
```javascript
layout = {
    lg: [{}, {this item}], // watch this grid item below
    md: [{}, {this item}],
    xs: [{}, {this item}], 
    xxs: [{}, {this item}], 
    sm: [{}, {this item}]
}
```
If I remove a grid item in current breakpoints `lg`, guess what I get in a callback. For some reason `onLayoutChange` removes an item ONLY for current breakpoint and doesn't touch it for other breakpoints:
```javascript
layout = {
    lg: [{}], // BOOM! Grid item is removed here, but still exists in all other breakpoints.
    md: [{}, {this item}],
    xs: [{}, {this item}], 
    xxs: [{}, {this item}], 
    sm: [{}, {this item}]
}
```
Screenshot. Do you see `lg` is 2 and all others are 4?

![screenshot from 2018-04-30 16-46-04](https://user-images.githubusercontent.com/3880497/39430364-553af8dc-4c96-11e8-8df2-0259ee1ca4f0.png)

This is WRONG and error prone. If I remove a grid item in one breakpoint, it has to be removed for all other breakpoints! Otherwise we end up having gazillion useless layouts for grid items we don't have already.

**Comment by STRML** [comment]
@wzup, this is open source software free for use and free for modification. Please check your tone at the door.

Whether or not you actually want to remove an item for all breakpoints or not is really a decision best left up to the application, not the library. You can modify all other layouts yourself via the reference if you like.

**Comment by dalalRohit** [comment]
hello @STRML ,

Firstly, Thank you so much for this amazing lib. 
I am also facing the same issues:

1. when I remove item from layout, sometimes it is removed from other breakpoints and not the current breakpoint
2. item is not getting removed from all the breakpoints.

Can you please suggest me some ways where I can handle this scenario? What I want to have is, when item is added/removed, it should be synced for all breakpoints.
