### ISSUE TITLE
Breakpoints at or larger than the lg breakpoint don't save reliably

### ISSUE THREAD

**Issue by benoneal** [STRML/react-grid-layout#8]
Go to https://strml.github.io/react-grid-layout/examples/8-localstorage-responsive.html

Resize or move a grid element, then make the window wider, then narrower, or narrower then wider. The layout will not have been saved most of the time (seems to only actually save about 20% of the time).

However, once the layout *has* been saved, it seems to work consistently from then on. 

It *seems* that this issue isn't a problem when the page loads narrower than lg breakpoints.

**Comment by STRML** [comment]
I am seeing this as well, not quite sure why. Will look into it, thanks
for the report.

**Comment by STRML** [comment]
Fixed in demos and in `0.6.1`, thanks for the report.
