### ISSUE TITLE
Width resizing a dragged element

### ISSUE THREAD

**Issue by brion-fuller** [STRML/react-grid-layout#80]
It looks like the constraint on resize is not updating when an element is dragged from the far right to the far left.  It looks from example 2 below, that a property isn't being updated correctly in order to allow dragged elements to resize.  I didn't notice the _grid property doesn't get updated after placing an element in a new position but didn't know if that would be a reason.

### Ex 1: ###
- Open Demo 1. Basic 
- Move Element 5 over to were Element 0 is.
- Try to resize Element 5.

### Ex 2: ###
- Open Demo 8 Local Storage Responsive
- Move Element 5 over to were Element 0 is.
- Try to resize Element 5. (Same effect as Ex 1, the Element doesn't resize)
- Now, reload the page with the saved layout
- Element 5 is now able to resize.
- Move Element 4 over to were Element 5 is.
- Try to resize Element 4.

**Comment by Inbreakable** [comment]
Any update on this issue?

**Comment by STRML** [comment]
This is confirmed fixed in `0.10`.
