### ISSUE TITLE
Units of measure for "rowHeight"?

### ISSUE THREAD

**Issue by wzup** [STRML/react-grid-layout#800]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ] Bug
- [ ] Feature Request
- [*] Question

What unit of measure for `rowHeight`? px? em? %? etc? No info in docs
```
// Rows have a static height, but you can change this based on breakpoints
// if you like.
rowHeight: ?number = 150,
```

**Comment by STRML** [comment]
It's px.
