### ISSUE TITLE
LayoutItem type missing from import

### ISSUE THREAD

**Issue by drdgvhbh** [STRML/react-grid-layout#804]
- [ ] Bug
- [ X] Feature Request
- [ ] Question

There doesn't seem to be a `LayoutItem` type available when importing the `react-grid-layout` module. This would be useful to have since I'm using typescript.

**Comment by damiangreen** [comment]
It's actually called `Layout`
e.g. 
```
private onWidgetDragStart = (
    layout: Layout[],
    oldItem: Layout,
    newItem: Layout,
    placeholder: Layout,
    e: MouseEvent,
    element: HTMLElement,
  )
```
