### ISSUE TITLE
item is missing when div is returned by react component

### ISSUE THREAD

**Issue by lasso-codie** [STRML/react-grid-layout#806]
- [X] Bug
- [ ] Feature Request
- [ ] Question

Hey,
I today encountered a very strange effect. I've got a react component with a rendering method:

```js

class Home extends React.Component {

render() {

    return (
      <GridLayout className="layout"
        cols={max_cols}
        rowHeight={max_rows}
        width={window_width}
        draggableCancel="input,textarea">

        <div style={{
          backgroundColor: ui_colors["blue"][3],
          display: 'flex',
          flexDirection: 'column',
          borderTopLeftRadius: '20px',
        }}
          key="example"
          data-grid={{
            x: 1,
            y: 0,
            w: 8,
            h: 25,
          }}/>

      </GridLayout>
    )
}

}
```

Once I moved the div into another react component, it is not rendered anymore. Indeed it is not even present in the DOM and there is no error message.

```js

class ExamplePanel extends React.Component {

    render() {
        return (
            <div style={{
                backgroundColor: ui_colors["blue"][3],
                display: 'flex',
                flexDirection: 'column',
                borderTopLeftRadius: '20px',
            }}
                key="example"
                data-grid={{
                    x: 1,
                    y: 0,
                    w: 8,
                    h: 25,
                }}/>

        )
    }

}

class Home extends React.Component {
render() {

    return (
      <GridLayout className="layout"
        cols={max_cols}
        rowHeight={max_rows}
        width={window_width}
        draggableCancel="input,textarea">

        <ExamplePanel />

      </GridLayout>
    )
}
}
```

It's literally the same code so why is it missing? Can't think of a single thing.

**Comment by qd-codie** [comment]
not yet ...

**Comment by nicosampler** [comment]
I'm having the same Issue, I noticed that if a div is used, it receive as `props.children` an array with 2 elements (re-sizable and draggable) , but when you use a custom element, the first is undefined, and seems to be the one related with rendering the re-sizable item.

**Comment by senro** [comment]
same Issue, and if i set a component in div ,the component will be wraped in a blank div, the inner component can not resize with its parent.

**Comment by anze555** [comment]
Same here, took me a while to find the reason. :+1:

**Comment by hellosylvee** [comment]
I'm running into this issue, has this been resolved anywhere?

**Comment by attiqeurrehman** [comment]
Grid Item needs some important style that needs to be passed. Please check [this ](https://github.com/STRML/react-grid-layout/issues/293#issuecomment-237509996) out.

**Comment by Cherviakov** [comment]
This is really super bad design. Obviously people would like to divide view to custom components rather than write whole grid under one component.

**Comment by liran87** [comment]
Has this been resolved?

**Comment by CWSites** [comment]
@STRML a lot of eyes on this one, any ideas on how we can fix this?

**Comment by STRML** [comment]
See https://github.com/STRML/react-grid-layout/issues/299#issuecomment-328398196. You are not passing `className` and `style`.
