### ISSUE TITLE
Add draggable header

### ISSUE THREAD

**Issue by msimonian77** [STRML/react-grid-layout#807]
Is there a way to only drag a header of a data-grid component?
There is a problem as some thing like map inside the grid component instead of dragging inside the map it's dragging the whole grid component. 
I would like to create a header for each grid that will be the only way to drag the component.

Please let me know if that is possible. Thanks!

- [ ] Bug
- [x] Feature Request
- [X] Question

**Comment by STRML** [comment]
`draggableHandle` - https://github.com/STRML/react-grid-layout#grid-layout-props
