### ISSUE TITLE
What is, "Include the following stylesheets in your application"?

### ISSUE THREAD

**Issue by JimTheMan** [STRML/react-grid-layout#808]
From the README:

> Include the following stylesheets in your application:
> 
> /node_modules/react-grid-layout/css/styles.css
> /node_modules/react-resizable/css/styles.css

but why not explain how?

**Comment by STRML** [comment]
Including stylesheets in a project is a basic part of web development. This repository is not a training course, it's free code. Use it or don't, as you wish.
