### ISSUE TITLE
Input field doesn't take cursor inside even after getting focused

### ISSUE THREAD

**Issue by gauravatsit** [STRML/react-grid-layout#809]
Whenever I add any text field inside **ResponsiveReactGridLayout** component, and try to enter text inside it, it doesn't allow. 
Clicking inside the text field, made it focused but cursor doesn't appear inside.
If I move to another browser tab and return back to the app then only cursor appears.

**Comment by jog39** [comment]
This has been answered in [#747](https://github.com/STRML/react-grid-layout/issues/747), you need to define a draggableHandle for your component.

**Comment by CWSites** [comment]
This can be closed.
