### ISSUE TITLE
Column widths don't automatically adjust when container width is changed.

### ISSUE THREAD

**Issue by ronitgalani** [STRML/react-grid-layout#81]
Hi, 
The column widths change automatically when the window is resized, but they stay the same if the only the container of the grid is resized.

For example,
container width: 1024px, no of columns: 5
![screen shot 2015-07-09 at 4 00 01 pm](https://cloud.githubusercontent.com/assets/3243973/8609355/0fd2a6b6-2659-11e5-96a7-3aca9f5ed545.png)

container width: 200px, no of columns: 5
![screen shot 2015-07-09 at 4 00 19 pm](https://cloud.githubusercontent.com/assets/3243973/8609360/18e0ae10-2659-11e5-9a26-1f186da99c5e.png)

Can you take the changes in container width into account as well? Or is there a way to force the columns to readjust?

Thanks,
Ronit

**Comment by STRML** [comment]
This should be possible via mutation observers, however it appears this is [not a high priority](https://code.google.com/p/chromium/issues/detail?id=293948) for at least Chrome. I'm afraid there's really not a good way to implement it well.

I would recommend changing the `key` of the RGL container when you change its width, which will cause React to throw it out and build another. Alternatively, fire a window resize event.

**Comment by knapeto** [comment]
Hi,

any helps with this problem ?

Thanks..

**Comment by GregoryPotdevin** [comment]
I went with the resize event firing and it seems to work just fine : window.dispatchEvent(new Event('resize'));

**Comment by josesaranda** [comment]
I think will be better if someone implements a PR that handle width resize...
