### ISSUE TITLE
Events are passed inside modal with another DnD lib.

### ISSUE THREAD

**Issue by thedevelobear** [STRML/react-grid-layout#811]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [X] Bug
- [ ] Feature Request
- [ ] Question

If you have a question or bug report, please use the [WebpackBin Template](https://www.webpackbin.com/bins/-Kvr2qCxorvGMgVMxkmI)
to demonstrate. It is much easier for us to help you if you do.

Hey,
I've experienced the bug shown on the video. It doesn't happen when using versions below 0.15.0 (eg. on 0.14.6 it works great). In the modal I'm using react-dnd lib with HTML5-backend. Is it possible that events from react-dnd are seen by RGL?

![nimbus-record-video-2018-05-17-15-54-10](https://user-images.githubusercontent.com/29607890/40182588-0434fca4-59ec-11e8-93ed-ac14060083ee.gif)

**Comment by kenzouno1** [comment]
same issue

**Comment by kenzouno1** [comment]
set props `isDraggable={!this.state.openModal}`

**Comment by kenzouno1** [comment]
sam this issue.
try set props `isDraggable={!this.state.openModal}` but this event reRender grid item and remove modal

**Comment by fro3clr** [comment]
same problem with MUI Dialog. react-grid-layout "locks" the mouse after click on item.

**Comment by ludvigeriksson** [comment]
> same problem with MUI Dialog. react-grid-layout "locks" the mouse after click on item.

@fro3clr Did you find a workaround for this?
