### ISSUE TITLE
Scrollbar not appearing on Parent div.

### ISSUE THREAD

**Issue by Vishal1419** [STRML/react-grid-layout#815]
I don't know if its a bug or I am not finding the way to do it.

I am using material Dialog and inside the body of material Dialog, I have a div. Inside that I have another div which I want to drag.

When I drag the inner div, I want to have a scrollbar to appear on its parent.

Here is my code:

```
        <div id="set-print-area-dialog-description" className="cover-print-area-settings-container">
          <Draggable
            bounds={{
              left: 0,
              top: 0,
              right: 300,
              bottom: 150
            }}
          >
            <div className="cover-print-area-settings-content">
              <div className="contact-name">Contact Name</div>
              <div className="side-by-side-start-center">
                <PhoneIcon className="contact-detail-icon" />
                <span>Mobile No</span>
              </div>
              <div className="side-by-side-start-center email-wrapper">
                <EmailIcon className="contact-detail-icon" />
                <span>Email</span>
              </div>
              <div className="side-by-side-start-center">
                <LocationIcon className="contact-detail-icon contact-location-icon" />
                <div className="contact-address-wrapper">
                  <p className="contact-address"> Address Line 1 </p>
                  <span className="contact-address-details"> Address Line 2 </span>
                </div>
              </div>
            </div>
          </Draggable>
        </div>

```
Here is how my output looks like:

![react app](https://user-images.githubusercontent.com/19953475/40342181-c31ba13c-5da6-11e8-955e-15400f7a84d1.jpg)

After drag:

![react app_2](https://user-images.githubusercontent.com/19953475/40342187-c8f8cc9c-5da6-11e8-8dd0-9472dec83e5c.jpg)

**Comment by CWSites** [comment]
This isn't an issue with the library but the CSS of your popup. You should have a set `width` and `height` of your print area div. Even if your popup is only 300px wide you can set your `cover-print-area-settings-content` to be as large as you like and set `overflow: auto;` which will add the scrollbar.

Try something like this in your CSS...
```
.cover-print-area-settings-content {
    height: 600px; // adjust to whatever you like
    width: 600px; // adjust to whatever you like
    overflow: auto;
}
```

**Comment by Vishal1419** [comment]
@CWSites  Sorry to say that you are misunderstanding me. I want the .cover-print-area-settings-content to be variable height and width. I mean when I drag my card to the right edge, the width of the .cover-print-area-settings-content should increase resulting in a horizontal scrollbar. Similarly with vertical scrollbar.

**Comment by CWSites** [comment]
@Vishal1419 can you create a codepen or something as a sample so I can help?

**Comment by Vishal1419** [comment]
@CWSites  Sorry for the above comment, but somehow I got scrollbars. Thanks for help.

**Comment by sandeepemail71** [comment]
For me this was happening because i have not imported CSS file
`import 'react-grid-layout/css/styles.css';`
