### ISSUE TITLE
Bizzare calculation of grid height

### ISSUE THREAD

**Issue by ZachHaber** [STRML/react-grid-layout#816]
Thanks for submitting an issue to RGL!

Please mark the type of this issue:

- [ ✔️ ] Bug
- [ ] Feature Request
- [ ] Question

The issue is as follows, the documentation states that the margin is the "Margin between items [x, y] in px. margin: ?[number, number] = [10, 10]," This conflicts with what is observed in practice. The margin is placed between rowHeights rather than between items. This is showcased in the codepen below where the height of a grid element is h*margin[1]+h*rowHeight-margin[1]. The issue that I'm dealing with is that since I set my rowHeight to 1 in order to make the grid able to be resized to any arbitrary size, setting a margin causes the grid size to go haywire. This calculation is also what is causing the confusion as to what unit the rowHeight is in, since the margin actually directly affects the height of the elements.

The implementation I'd like to see is where the margin is only calculated into the height once per grid item rather than once per row height and grid item. Let me know if you have any questions about what I'm asking for. Thank you for your support! 😄

https://codepen.io/ZachHaber/pen/eroJdO

**Comment by STRML** [comment]
This is necessary, otherwise grid items of varying heights will not line up next to each other. This is brought up every few months, try it yourself. #233 #339 #410 #559 and so on.
