### ISSUE TITLE
GridItem isDraggable and isResizable props not being updated

### ISSUE THREAD

**Issue by nlucero** [STRML/react-grid-layout#819]
I have a flag on my app that controls whether the grid items can be dragged and resized. This flag is passed on the `isDraggable` and `isResizable` properties of the `data-grid` prop of each component inside the grid. The problem is that all `GridItems` won't update their internal `isDraggable` and `isResizable` props when it changes. They seem to always hold the original value that was set on first `render`.

Is this intended?

**Comment by rskarras** [comment]
Hi nlucero, I encountered a similar problem in which the data-grid functioned only based on the initial details. I was able to get around this issue by using the 'layout' method for generating the grid and it worked as expected. 

When I have more time I may look into a better fix for this, but for now using the 'layout' method works fine for my use case.

Hope this helps!
