### ISSUE TITLE
Any example on creating custom grid content?

### ISSUE THREAD

**Issue by andrasferenczi** [STRML/react-grid-layout#824]
- [X] Question
- [ ] Bug
- [ ] Improvement

So my question is if there is any demo where another react components are rendered inside the `ReactGridLayout`? Are there any open source codes out there I could look at?

I am stuck with this issue and cannot figure out what the proper way is to add components inside the grid and make them fit into their cell.

Thank you.

**Comment by chinmaydalvi** [comment]
May I know how did you create Custom grid content ?
