### ISSUE TITLE
Low performance during dragging and resizing

### ISSUE THREAD

**Issue by Zdend** [STRML/react-grid-layout#83]
Whenever I drag or resize a block, it plucks and its dropped shadow is blinking. I tried precise code from examples but with no luck. I use version 0.8.3 from NPM. I can get into a state where there is no plucking and it's fast. It is when I grab a block, move it on some input so that this input became focused and then during the time the input is focused, I can drag with the block with no plucking like in offical demo. What could be the cause of my problem?

This is my temporary solution:

    onDrag: this.fixDragWithFocus,
    onResize:this.fixDragWithFocus

    fixDragWithFocus: function(){
        jQuery('#fictive-input').focus();
    }

**Comment by Sawtaytoes** [comment]
I noticed this issue happening in Firefox, but not Chrome. What browser are you using?

**Comment by adambowles** [comment]
I also get very poor performance in Firefox (44). Chrome (48) unaffected.

Get this message in Firefox console: `Mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create`

**Comment by STRML** [comment]
@adambowles That's [this issue](http://stackoverflow.com/questions/33858349/fixing-mutating-the-prototype-of-an-object-in-babeljs-6), which is not affecting performance in any typical app.

Can you make a demo where there is bad performance? I can't replicate this.

**Comment by adambowles** [comment]
I'm getting the error in all [your examples](https://strml.github.io/react-grid-layout/examples/0-showcase.html)

**Comment by STRML** [comment]
Like I just mentioned, that's not the issue.

On FF, the issue appears to be a preponderance of time taken up by paint/render, not by JS.

**Comment by STRML** [comment]
Not much we can do about paint time in general. Closing.
