### ISSUE TITLE
Margin is added each row height

### ISSUE THREAD

**Issue by rherms** [STRML/react-grid-layout#831]
Bug: Margin is added each row height, resulting in unexpected heights.

If I have a row height of 1px and and margin between elements of 10px and I want to display my 200px tall element, setting the row height to 200px results in a height of 2190px (or something like that), because the margin is added each row height. This makes me have to do weird arithmetic to get the actual row height I want given this. It seems unintuitive and weird that it does this. Is there a reason?

**Comment by STRML** [comment]
https://github.com/STRML/react-grid-layout/issues?utf8=%E2%9C%93&q=is%3Aissue+margin+height+is%3Aclosed+
