### ISSUE TITLE
Get new Height and Width of Box on onResizeStop Event

### ISSUE THREAD

**Issue by chinmaydalvi** [STRML/react-grid-layout#833]
How to get new height and width of Box on `onResizeStop` on event.

In my current project as soon as resizing is complete on box I want to send the new height and width of box to API of Map to bring the Map of that size. 

How to get new height and width of box after resize is complete.

**Comment by chinmaydalvi** [comment]
Got the answer I set layout in state of component in  `onLayoutChange` callback

**Comment by AlainRo** [comment]
That is exactly my need.
Would you mind sharing the corresponding code fragments ? I got the idea but wonder how to do it.
