### ISSUE TITLE
Bug: When dragging, iOS devices also scroll vertically, making re-arranging impossible

### ISSUE THREAD

**Issue by FredFuras** [STRML/react-grid-layout#836]
Hi there,

First of all, thank you for your efforts on this library. I've tried a few grid libraries and this has been the best by far, so I'm really enjoying using it.

I did however run into an issue when testing on iPhones. This is an issue that is replicable using the demos, so it's not just my implementation. When the user drags to re-arrange components vertically, it also scrolls their page, making re-arrangement impossible.

It looks like there were some issues raised for this in 2016, such as [#338](https://github.com/STRML/react-grid-layout/issues/338), and looking at the comments they were fixed back then, so I guess this is a regression? Or perhaps Apple changed something with iOS. Either way, this is not working on iPhones anymore (I tested with 2 different models).

Is there any chance of getting this looked at? Thanks!

**Comment by rskarras** [comment]
Hi FredFuras, I don't believe that there has been a fix implemented for this. The following code works to disable the default scrolling behavior when dragging RGL elements and then reactivates it once the drag has completed.

  onDragStart = () => {
    // This disables default scrolls on touch screens when resizing or moving boxes
    document.ontouchmove = function(e){ e.preventDefault(); }
  };

  onDragStop = () => {
    // This reactivates default scrolling behavior on touch screens after resizing or moving boxes
    document.ontouchmove = function(){ return true; }
  };

Hope this helps!

**Comment by FredFuras** [comment]
Fantastic! Thanks so much, I just implemented and tested it and that solves my problem.
