### ISSUE TITLE
How can I override the resizable handle icon?

### ISSUE THREAD

**Issue by damiangreen** [STRML/react-grid-layout#839]
I'm working with a dark background and the image is black so its barely visible

**Comment by rskarras** [comment]
Are you referring to changes to the styling? If so it's a simple adjustment in the .css file as shown below. 
If this is not what you're looking for could you clarify what you mean by overriding the icon?

`.react-grid-item > .react-resizable-handle::after {
  content: "";
  position: absolute;
  right: 3px;
  bottom: 3px;
  width: 5px;
  height: 5px;
  border-right: 2px solid rgba(0, 0, 0, 0.4);
  border-bottom: 2px solid rgba(0, 0, 0, 0.4);  <-- adjust here for coloring and transparency
}`

You should be able to make any adjustments you need here. For color, change the rgba value of the border styling.

**Comment by damiangreen** [comment]
thanks @rskarras  that did it . I made it white
```
border-right: 2px solid rgba(255, 255, 255, 0.5);
border-bottom: 2px solid rgba(255, 255, 255, 0.5);

```

**Comment by jon1467** [comment]
@damiangreen Bit late to the party but I like to use [`mix-blend-mode: difference`](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) to change the colour of the handle to fit any background.

**Comment by rafaellichen** [comment]
My way of using custom resize icon is actually "hiding" the actual default resize handler itself.
```css
/* Hide React-Grid-Layout ResizeHandle for now */
.react-resizable-handle.react-resizable-handle-se {
    opacity: 0;
}
```
Then, you just position an element with `position: absolute; right: 0; bottom: 0;` to the bottom right corner.

**Comment by Winchester-cell** [comment]
> My way of using custom resize icon is actually "hiding" the actual default resize handler itself.
> 
> /* Hide React-Grid-Layout ResizeHandle for now */
> .react-resizable-handle.react-resizable-handle-se {
>     opacity: 0;
> }
> Then, you just position an element with `position: absolute; right: 0; bottom: 0;` to the bottom right corner.

i know its late , but best solution , thank u <3
