### ISSUE TITLE
onWidthChange mutates 'layouts' prop

### ISSUE THREAD

**Issue by sh3nan1gans** [STRML/react-grid-layout#845]
I've narrowed the issue down to this line - https://github.com/STRML/react-grid-layout/blob/3352c84515e587c2bb7ec7935e24be5705d33704/lib/ResponsiveReactGridLayout.jsx#L222

Please let me know if you'd like help with this issue.

**Comment by reanimatter** [comment]
Under some circumstances, the `layouts` prop may be passed frozen. The layout component tries to mutate it in `onWidthChange` and fails with

```
Cannot add property {breakpoint}, object is not extensible
```

Sample failure: https://codesandbox.io/s/l22r6jxqrl
