### ISSUE TITLE
All items stay aligned to one side

### ISSUE THREAD

**Issue by garethharding** [STRML/react-grid-layout#847]
Hi, no matter how I try and configure responsive RGL, all the items stay aligned to the left hand side.

What am I missing as it's driving me mad :p 

-----------

import * as React from "react";
import * as ReactDOM from "react-dom";

import * as GridLayout from "react-grid-layout";
import { Responsive, WidthProvider } from "react-grid-layout";

const ResponsiveReactGridLayout = WidthProvider(Responsive);

class MyResponsiveGrid extends React.Component {
  public render() {
    const largeLayout = [
      { i: "a", x: 0, y: 0, w: 3, h: 4 },
      { i: "b", x: 5, y: 0, w: 3, h: 4 },
      { i: "c", x: 0, y: 1, w: 3, h: 4 }
    ];

    const medLayout = [
      { i: "a", x: 0, y: 0, w: 3, h: 2 },
      { i: "b", x: 1, y: 0, w: 3, h: 2 },
      { i: "c", x: 4, y: 0, w: 3, h: 2 }
    ];

    const smallLayout = [
      { i: "a", x: 0, y: 0, w: 3, h: 2 },
      { i: "b", x: 1, y: 0, w: 3, h: 2 },
      { i: "c", x: 4, y: 0, w: 3, h: 2 }
    ];

    const xSmallLayout = [
      { i: "a", x: 0, y: 0, w: 3, h: 2 },
      { i: "b", x: 1, y: 0, w: 3, h: 2 },
      { i: "c", x: 3, y: 0, w: 3, h: 2 }
    ];

    const xsSmallLayout = [
      { i: "a", x: 0, y: 0, w: 3, h: 1 },
      { i: "b", x: 1, y: 0, w: 3, h: 1 },
      { i: "c", x: 2, y: 0, w: 3, h: 1 }
    ];

    const layouts = {
      lg: largeLayout,
      md: medLayout,
      sm: smallLayout,
      xs: xSmallLayout,
      xxs: xsSmallLayout
    };

    return (
      <div>
        <ResponsiveReactGridLayout
          className="layout"
          breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
          cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}
          layouts={layouts}
        >
          <div key="a">a</div>
          <div key="b">b</div>
          <div key="c">c</div>
        </ResponsiveReactGridLayout>

    </div>

    );
  }
}

ReactDOM.render(<MyResponsiveGrid />, document.getElementById("app"));

**Comment by garethharding** [comment]
FYI, this issue looks related to the width provider as if I exclude that and add an absolute width as a parameter for the component it works, albeit only at that width

**Comment by garethharding** [comment]
For anyone else with this issue, it's related to:

https://github.com/STRML/react-grid-layout/issues/765

In essence, add something in the order of 

style={{width: "100%"}}

to the parent element of RGL. E.g.:

      <div style={{width: "100%"}}>
        <ResponsiveReactGridLayout
          className="layout"
            //   width={800}
          breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
          cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}
          layouts={layouts}
        >
          <div key="a" className="grid-tile">a</div>
          <div key="b" className="grid-tile">b</div>
          <div key="c" className="grid-tile">c</div>
        </ResponsiveReactGridLayout>
    </div>

**Comment by LongicornYu** [comment]
Having the same issue, the values in layout don't work at all, all div inside the gridlayout are of the same size, and all aligned to left in one column.  The solution above doesn't work :(

**Comment by mnoster** [comment]
Also having the same issue

**Comment by webberwang** [comment]
Any reason why this issue has been closed? The error still persists

**Comment by noxalex** [comment]
> Any reason why this issue has been closed? The error still persists

try to use 100vw instead of %

**Comment by rajivsubra1981** [comment]
For anyone facing this issue in Material UI - this works with 100vw
