### ISSUE TITLE
Github versions and NPM versions different

### ISSUE THREAD

**Issue by andrewmclagan** [STRML/react-grid-layout#85]
Github: 0.9.2
NPM: 0.8.3

Any idea whats happening here?

**Comment by STRML** [comment]
Yes, that's intentional. 0.9.2 was a refactoring only and had some major bugs. I unpublished it to ensure npm users stayed on a functional version.

**Comment by dmr** [comment]
What is the status on this, npm still says 0.8.5 is the latest version although there is an older 0.9.2 in there as well

**Comment by STRML** [comment]
As above - 0.9.x is abandoned and we'll move to 0.10.x once the new versions of draggable and resizable are ready.

**Comment by dmr** [comment]
What can I do to help?
0.8.5 has a rependency to an old version of resizable which is breaking the installation in our software :(

**Comment by Enet4** [comment]
My +1 to the comment above, as I've become unable to build my project because of the same problem.
