### ISSUE TITLE
Setting margin to anything but [x,0] radically increases height of container.

### ISSUE THREAD

**Issue by plamenh** [STRML/react-grid-layout#856]
I am trying to get fixed size of grid items by fixing the width and height of the parent container.

Everything works, but height. For example, this is my grid definition:

```
layout: {
        0: {x: 0, y: 5, w: 50, h: 70, i: "0"},
        1: {x: 50, y: 0, w: 21, h: 30, i: "1"},
        2: {x: 71, y: 9, w: 15, h: 21, i: "2"},
        3: {x: 50, y: 30, w: 30, h: 40, i: "3"},
    },
    cols: 86,
    rowHeight: 5,
```

This should roughly equate to a height of 375 px ((layout[0].y + layout[0].h) * rowHeight). And, it works nicely when margin={[0,0]} or margin={[50,0]}.

However, if margin is anything but {[x,0]}, height gets completely out of hand (e.g. margin={[0,5]} messes with the height of all grid items (makes them much larger)) . Unfortunately, I need the margins.

Any ideas?

**Comment by finkbg** [comment]
+ One more bug - x margin eats into width of elements. Is that normal?

**Comment by AshishKumar94** [comment]
height:
        h === Infinity
          ? h
          : Math.round(rowHeight * h + Math.max(0, h - 1) * margin[1])

Above issue happening because of muliptlication of margin size into height grid units. and adding them into height.

what is the purpose of this?
