### ISSUE TITLE
Cannot scroll from the grid view on Android device

### ISSUE THREAD

**Issue by OshanAbeykoon** [STRML/react-grid-layout#857]
I have a responsive grid panel containing 6 grid items on it.
Each grid item has a draggable handle area defined via the draggableHandle prop.
code as follows,
Responsive Gird
 ```
<ResponsiveGridLayout
      className="layout"
      layouts={{lg:layout_lg, md: layout_md, sm: layout_sm}}
      breakpoints={{lg: 1200, md:  996,  sm:  756}}
      cols={{lg: 3, md: 2, sm: 1}}
      draggableHandle=".handle-dragable"
      rowHeight={450}
 >
```
Gird Item
```
<div key="a">
     <div>
         <div className="handle-dragable" > <b> Dragable Area</b> </div>
      </div>
      <p className="non-dragable">
         Some text
      </p>
 </div>
```
 
When i view the gird panel on an Android device i'm unable to scroll down by touching the **.non-dragable** area.
This works perfectly on an I Pad.

**Comment by RainGrid** [comment]
@OshanAbeykoon  same issue

**Comment by OshanAbeykoon** [comment]
@RainGrid 
This is due to inline style **touch-action: none** set in the each react grid item.
It did work on IPad because the **iOS Safari only supports auto and manipulation.**
