### ISSUE TITLE
Z-index is not working

### ISSUE THREAD

**Issue by Pardeep94** [STRML/react-grid-layout#858]
I am working with this grid layout and I also use react-date-picker for calendar.
I need to change z-index of react grid layout because it cover my calendar but I am able to do it.
I also do it with changing z-index of calendar and also by changing z-index of grid layout but nothing is working.
![screenshot from 2018-09-25 12-04-58](https://user-images.githubusercontent.com/18335284/45996934-979f0a80-c0bb-11e8-86fe-d2a34f88a780.png)

**Comment by rockyhuber** [comment]
I have the same problem!

**Comment by rockyhuber** [comment]
Mine will also not enable me to click on the calendar dates that overlap on the same grid that fired the calendar. If I click on a date off the the grid that fires the event, then it will select.

**Comment by rockyhuber** [comment]
<img width="601" alt="screen shot 2018-09-27 at 5 43 13 pm" src="https://user-images.githubusercontent.com/4715314/46130553-f069d100-c27c-11e8-9778-ea85df50e821.png">

**Comment by rockyhuber** [comment]
I got mine to display properly, however I still cant click on the swatches anywhere on the blue grid. I can click the color swatch on the items which are off the blue grid area.

So I set the zIndex of the 
`<GridLayout style={{zIndex:'0'}} ...`

Then for the grid boxes I applied a zIndex of -1 
`<div style={{zIndex:'-1'}} key="b">`

No idea why this works, but it does. Everything still moves as it should, except for the problem of not being able to click on the orange, yellow, light green, green, light blue, blue and gray swatches

<img width="693" alt="screen shot 2018-09-27 at 11 06 44 pm" src="https://user-images.githubusercontent.com/4715314/46147907-1e193f00-c2aa-11e8-9323-f2d64f94f868.png">

**Comment by Pardeep94** [comment]
your solution is also not working in my case

**Comment by mmesar** [comment]
Try with useCSSTransforms={false} grid property. worked for me.

![xyz](https://user-images.githubusercontent.com/24696326/46363457-5dada580-c673-11e8-8c39-6b4341f6aebd.png)

**Comment by zy410419243** [comment]
Try add a wrapper out of your dom and ban the drag event, like below
``` bash
    <div onDragStart={ e => {} }>
        <your tag>
    </div>
```
It works. for me.

**Comment by MrToph** [comment]
This happens because the grid items create a new stacking context and you use the color picker as a _child_ of that grid item.

@mmesar 's answer works because then it does not use `transform` property anymore, which previously [created the stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).
This fixes the issue but the documentation says that it's about 6x slower now.

**Comment by mmesar** [comment]
@MrToph I know the mechanics of my solution and what are tradeoffs, just wanted to point out quick and easy solution, as for the slowness, I don't think it is such an issue, IMHO most of the time users aren't resizing and moving frames in the grid, once they configure their view they stick with it and interact with functionalities inside grid items

**Comment by mishravinay112** [comment]
@mmesar I tried to useCSSTransforms grid property but it is not working for me.

**Comment by mmesar** [comment]
@mishravinay112 
did u set any overflow property on grid item? let's not play guessing game :) can you provide some code?

**Comment by mishravinay112** [comment]
@mmesar thanks for the prompt reply. here is the code:

export default class RenderComponent extends React.Component {

    constructor(props) {
        super(props);
        this.state={
            data: {},
            propsData: {},
        }
        this.onLayoutChange = this.onLayoutChange.bind(this);
    }

    render() {
        const data = this.state.data;
        return (
            <div className="grid chrPad-left-right chrGutter-horizontal--xs">

                {data.length>0 &&


                            <GridLayout className="layout"
                                        useCSSTransforms={true}
                                        cols={12}
                                        layout={this.props.layout}
                                        onLayoutChange={this.onLayoutChange}
                                        rowHeight={30}
                                        width={1405}
                                        style={{zIndex:'0'}}
                                        >
                                {data.map((element,index) => {
                                return(
                                <div style={{zIndex:'-1'}} key={index} className='content-border'>
                                    {element.displayType==="MAP" &&
                                      <MapContainer  element={element}/>
                                    }
                                    {element.displayType==="CHART" &&
                                      <ChartContainer /*dimension={elementHeight}*/ element={element}/>
                                    }
                                    {element.displayType==="STATS" &&
                                      <StatsContainer element={element} id={index} /*dimension={elementHeight}*//>
                                    }
                                    {element.displayType==="TABLE" &&
                                      <DataTableHandler data={element}/>
                                    }
                                </div>
                                )


                                })}
                            </GridLayout>


                }

            </div>
        );
    }

    onLayoutChange(layout) {
        this.props.onLayoutChange(layout);
    }

    componentWillReceiveProps(nextProps) {
        console.log(nextProps.data)

        this.setState({
            data: nextProps.data,
            propsData: nextProps.propsToPass
        })
    }
}

**Comment by mmesar** [comment]
@mishravinay112 
You just solved half of my project problems m8. Cos I figured somethings out. 

First of all loose zIndex properties on GridLayout and div enclosing your containers (MapContainer, ChartContainer, StatsContainer, DataTableHandler ) and put your useCSSTransforms to false. Things should work then. 

OR (and that is what i just figured out).
put your useCSSTransforms to true and  keep your zIndex: 0 on GridLayout and your zIndex: -1 on enclosing container that has dropdown and put zIndex: -2 on all other enclosing containers that dont have dropdown menu. Or if every enclosing div has dropdown menu every following enclosing div should have zIndex one point lower (so first enclosing div -1, second -2. third -3 and so on). There are drawbacks tho, some divs and their dropdown menus will always be over divs that are after them. 

For me, only some grid items have dropdown menus and this is perfect for my implementation. For you, if you have dropdown menus in every grid item this may or maynot be satisfactory.

Anyways, first solution should work.

I hope I helped.

**Comment by Pardeep94** [comment]
I solved my problem by giving z-index of parent div.
Thank you everyone for giving me your precious time.

**Comment by MicheleDolce11** [comment]
Hi all, I had the similar problem of @mishravinay112 , I had a lot of grid items with the dropdown so I set on CSS this:
.react-grid-item:hover{
    z-index: 10;
}
This is a good solution only if is not necessary that the dropdown remains in foreground also when not hovering the grid item

**Comment by dheerajsuthar** [comment]
> Hi all, I had the similar problem of @mishravinay112 , I had a lot of grid items with the dropdown so I set on CSS this:
> .react-grid-item:hover{
> z-index: 10;
> }
> This is a good solution only if is not necessary that the dropdown remains in foreground also when not hovering the grid item

worked like charm :) Thanks @MicheleDolce11

**Comment by Efury1** [comment]
> I solved my problem by giving z-index to parent div. Thank you everyone for giving me your precious time.

How would did you go about passing z-index to parent? Do you an example of the code?

**Comment by BishnuDahal** [comment]
I have trick for this solutions. Everytime you touch the grid item make sure its zIndex is higher. For Example, you can do:
.react-grid-items:hover {
z-index: 999 !Important;
}

**Comment by jarodsim** [comment]
> Eu tenho um truque para essas soluções. Cada vez que você tocar no item da grade, certifique-se de que seu zIndex seja maior. Por exemplo, você pode fazer: .react-grid-items:hover { z-index: 999 !Important; }

Lol hahahhahah

**Comment by ebrahimsaed** [comment]
> Hi all, I had the similar problem of @mishravinay112 , I had a lot of grid items with the dropdown so I set on CSS this: .react-grid-item:hover{ z-index: 10; } This is a good solution only if is not necessary that the dropdown remains in foreground also when not hovering the grid item

Worked for also, thanks man for this amazing idea!!!

**Comment by ArthurRuxton-DY** [comment]
Hi all, my grid items have tooltips (which render on hover). The tooltips appear to be at a lower zIndx than the neibouring grid items, almost exactly like @rockyhuber 's example. 

I'm using ResponsiveGridLayout, which may be why none of the formentioned solutions have worked for me. 

Any help would be greatly appreciated! Thanks!

<img width="389" alt="Screenshot 2024-05-09 at 12 44 48" src="https://github.com/react-grid-layout/react-grid-layout/assets/108678572/4e849646-ee92-4c03-ae13-c828d382c923">

**Comment by amsanket22** [comment]
@BishnuDahal it should be .react-grid-item instead of items
`.react-grid-item:hover {
  z-index: 999 !important;
}`

but yeah this really solves the problem
