### ISSUE TITLE
Updating layout on OnLayoutChange and/or onDragStop with ResponsiveGridLayout causes error

### ISSUE THREAD

**Issue by kylietmo** [STRML/react-grid-layout#859]
I'm trying to update the layout stored in my component's local state every time the layout changes, but I continually get the error "Can't call setState (or forceUpdate) on an unmounted component" when setting the state in the callback for onDragStop(), or a maximum depth exceeded error when setting the state in the callback for onLayoutChange().

I can update the layout without issue in my onResizeStop() callback, but for some reason when I try to do the same in the callbacks for onLayoutChange or onDragStop(), I have these issues. 

I've read related issues (#151 being quite similar), and am still at a loss. I assumed that the loop that resulted in the error for onLayoutChange() was a result of updating the same layout that I passed into the ResponsiveGridLayout, so I stored it in a different part of the state and the same issues arise. I've read that others had similar issues but they were resolved with updates years ago, so I'm not sure what is happening here.

Here is my stored layout:
```
      layouts : {
        lg: [
              {i: "a", x: 1, y: 0, w: 2, h: 3, minH: 1, maxH: 9},
              {i: "b", x: 1, y: 0, w: 2, h: 7, minH: 1, maxH: 9},
              {i: "c", x: 1, y: 0, w: 2, h: 3, minH: 1, maxH: 9},
              {i: "d", x: 1, y: 0, w: 2, h: 3, minH: 1, maxH: 9}
            ]
      },
```

Here is my render method:

```
  render() {
    const ResponsiveGridLayout = WidthProvider(Responsive);

    return (
      <div className="p-widgets h-100">
        <ResponsiveGridLayout className="layout" 
          layouts={this.state.layouts}
          breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
          cols={{lg: 12, md: 10, sm: 6, xs: 4, xxs: 2}}
          rowHeight={25}
          autoSize={false} //don't allow the grid to grow the window
          onResizeStop={(layout, oldItem, newItem) => this.setLastHeightandLayout(layout, newItem)}
          onDragStop={(layout) => this.setLayout(layout)}
        >
        {this.makeWidgets()}
        </ResponsiveGridLayout>     
      </div>
    );
  }
```

and here are the two callbacks used above:

```
  setLayout(layout) {
    this.setState({layouts: {lg: layout}}) //THIS THROWS THE ERROR
  }

  /**
   * On a resize event, saves new height of the specified item.
   * @param {*} item (object)
   */
  setLastHeightandLayout(layout, item) {
    let updatedWidgets = this.state.widgets;
    updatedWidgets[item.i].lastHeight = item.h;
    this.setState({widgets: updatedWidgets});
    this.setState({layouts: {lg: layout}}) //YET THIS WORKS FINE
  }
```

I'm still quite new to React and javascript in general so I apologize if I've missed something obvious even after hours of double-checking.

**Comment by GourabPaul007** [comment]
This is still an issue. Is there any update?

**Comment by GourabPaul007** [comment]
Ok so after some research and tinkering, I found out the root cause of the problem.
there are 2 states that comes into play(I'm referring to the original example), the `items` & `layout` states.
you only tinker with the items state e.g. addItem or removeItem, not the layout one.
when you pass `  onLayoutChange(layout) {
    this.setState({ layout: layout });
  }`

 on the ` <ResponsiveReactGridLayout onLayoutChange={this.props.onLayoutChange}>` component, it updates the layout array/state & then updates the layout of the grid without recursively calling itself.
as opposed to modifying `layout` array/state where it would call `onLayoutChange` everytime you add or update an item because the state will rebuild with `setState` recursively.

Therefore, use `items` to manage your own state(`addItem`, `removeItem`, `modifyItem`), not the `layout`.

**Comment by andyg-12** [comment]
I still get this error after updating the library to the latest version _v1.4.3_, it was working fine on version _v1.3.4_.
I don't know whether the commit in #1923 has something to do.

CC: @STRML

**Comment by amishaaggarwal** [comment]
i am facing the same issue....is there any solution to this?
