### ISSUE TITLE
How to set min and max grid item widths in pixels

### ISSUE THREAD

**Issue by davallen** [STRML/react-grid-layout#864]
I am unable to set the min/max width of grid items. Not understanding if I choose to only have limited breakpoints that it does not allow me this flexibility.

**Comment by Tekunalogy** [comment]
You can add it to your css styles for the component. `minWidth` and `minHeight` css properties.

The downside is that the gridItem boundary may still be resized below the min width and height, while the component itself remains at its fixed pixel size. Trying to figure out a way to dynamically calculate the min size, based on the layout size in pixels, and the breakpoint columns. Maybe it just as simple as setting the minWidth and minHeight css properties for the react-grid-layout grid item as well? Not sure.
