### ISSUE TITLE
set initial height and width to ResponsiveReactGridLayout

### ISSUE THREAD

**Issue by uditdubey** [STRML/react-grid-layout#865]
how to give initial height and width to ResponsiveReactGridLayout
below is my code,
<ResponsiveReactGridLayout
                    className={'layout'+ (currentSelection !== 'trade' ? ` ${styles.invisible}`: '')}
                     draggableHandle='.widgetheader'
                     breakpoints={{lg: 1200, md: 900, sm: 600, xs: 300, xxs:0}}
                     cols={{lg: 10, md: 10, sm: 10, xs:0,xxs:0}}
                     gutter={{ lg: 1, md: 1, sm: 1, xs:1,xxs:1}}
                     onBreakpointChange={this.onBreakpointChange}
                     rowHeight={35}
                     data-width = {this.state.width}
                     layouts={this.state.layout}
                     onLayoutChange={this.onLayoutChange}
                     onResize={this.onResize.bind(this)}
                     isResizable={true}
                     autoSize={true}
                     margin= {[4, 6]}
                     preventCollision={true}
                     useCSSTransforms={true}
                     compactType={`horizontal`}
                     id="dashBoardGrid"
                     >

**Comment by AlanLes** [comment]
Hello, I've managed this case by adding a `Wrapper` component with `min-height` and `width` defined. My code looks like this:

```
const GridLayoutWithWidth = WidthProvider(GridLayout);

<GridLayoutWithWidth
    className="layout"
    layout={layout}
    margin={[gridSize() * 2, gridSize()]}
    cols={12}
    rowHeight={13}
    onLayoutChange={bfContext.onLayoutChange}
>
    {renderLayout(layout)}
</GridLayoutWithWidth>
```

Does it solve your problem? :)

**Comment by mahathun** [comment]
i ended up adding minHeight style directly to the component. 
`<ReactGridLayout
                width="1000px"
                layout={this.state.layout}
                onLayoutChange={this.onLayoutChange}
                onDrop={this.props.onDrop.bind(this)}
                isDroppable={true}
                {...this.props}
                style={{minHeight: '500px'}}
            >
            {this.generateDOM()}
        </ReactGridLayout>`

**Comment by themattmayfield** [comment]
Found a great solution!
Using lodash I am getting the number of rows
`const [getHeight, setHeight] = useState(_.maxBy(yourLayout, 'y').y)
  
  const onLayoutChange = (layout, layouts) => {
    setHeight(_.maxBy(layouts.xxs, 'y').y)
  };`

onLayoutChange function is in the docs. But basically whenever you change the layout, it updates the row height.
Then...

`<ResponsiveGridLayout
       ...
        rowHeight={170}
        onLayoutChange={(layout, layouts) => onLayoutChange(layout, layouts)}        
        style={{minHeight: `calc(170px * ${getHeight})`}}
      >`
