### ISSUE TITLE
Uncaught TypeError: this.props.updateText is not a function

### ISSUE THREAD

**Issue by rainzetroc** [STRML/react-grid-layout#868]
Anyone help me with this issue:
/home/home
import React from "react";
import Styles from "./_styles.scss";
import Image from "../../img/download.png";

export default class Home extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      text: ""
    };
    this.handleChange = this.handleChange.bind(this);
  }

  handleChange(e) {
    this.setState(
      {
        text: e.target.textContent
      },
      function() {
        this.props.updateText(this.state.text);
      }
    );
  }

  render() {
    return (
      <div>
        <div className="header">
          <div>
            {" "}
            <img src={Image} />
          </div>
          <div className="msearch">
            <input
              type="text"
              value={this.props.storeText}
              role="textbox"
              placeholder="Search..."
            />

            <div className="svg">
              <svg
                role="button"
                focusable="false"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
              >
                <path d="M15.5 14h-.79l-.28-.27A6.471 6.471 0 0 0 16 9.5 6.5 6.5 0 1 0 9.5 16c1.61 0 3.09-.59 4.23-1.57l.27.28v.79l5 4.99L20.49 19l-4.99-5zm-6 0C7.01 14 5 11.99 5 9.5S7.01 5 9.5 5 14 7.01 14 9.5 11.99 14 9.5 14z" />
              </svg>
            </div>
          </div>

          <footer className="footer">Copyright © 2018 Rain Cortez </footer>
        </div>
        <div />
        <div className="ese-tlr-cont">
          <div
            className="ese-tlr-item ese-selected-tlr"
            rel="srchrefiners_toplevel"
            data-aid="all"
          >
            Everything
          </div>
          <div
            className="ese-tlr-item"
            rel="srchrefiners_toplevel"
            data-aid="ikn"
            data-title="KX Documents"
            aria-label="press enter for results from KX Documents"
            tabIndex="0"
            onClick={this.handleChange}
          >
            KX Documents
          </div>
          <div
            className="ese-tlr-item"
            rel="srchrefiners_toplevel"
            data-aid="ikn"
            data-title="Sites"
            aria-label="press enter for results from KX Documents"
            tabIndex="0"
            onClick={this.handleChange}
          >
            Sites
          </div>
          <div
            className="ese-tlr-item"
            rel="srchrefiners_toplevel"
            data-aid="ikn"
            data-title="People"
            aria-label="press enter for results from KX Documents"
            tabIndex="0"
            onClick={this.handleChange}
          >
            People
          </div>
          <div
            className="ese-tlr-item"
            rel="srchrefiners_toplevel"
            data-aid="ikn"
            data-title="Policies"
            aria-label="press enter for results from KX Documents"
            tabIndex="0"
            onClick={this.handleChange}
          >
            Policies
          </div>
        </div>
      </div>
    );
  }
}

/home.index

import Home from "./home";
import { connect } from "react-redux";
import { updateText } from "./actions";

const mapStateToProps = (state, props) => {
  return {
    storeText: state.text,
    storeAid: state.aid
  };
};

const mapDispatchToProps = dispatch => {
  return {
    updateText(val) {
      dispatch(updateText(val));
    }
  };
};

const Container = connect(
  mapStateToProps,
  mapDispatchToProps
)(Home);

export default Container;

/home/reducers

import C from "./constants";

export const updateText = (state = "", action) => {
  switch (action.type) {
    case C.UPDATE_TEXT:
      return action.payload;
    default:
      return state;
  }
};

export const updateAid = (state = "", action) => {
  switch (action.type) {
    case C.UPDATE_AID:
      return action.payload;
    default:
      return state;
  }
};

/home/actions

import C from "./constants";

export const updateText = value => (dispatch, getState) => {
  dispatch({
    type: C.UPDATE_TEXT,
    payload: value
  });
};

export const updateAid = value => (dispatch, getState) => {
  dispatch({
    type: C.UPDATE_AID,
    payload: value
  });
};

/home/constants

const constants = {
  UPDATE_TEXT: "UPDATE_TEXT",
  UPDATE_AID: "UPDATE_AID"
};

export default constants;

/store/appReducer

import { combineReducers } from "redux";
import { updateText } from "../home/reducers";
import { updateAid } from "../home/reducers";

export default combineReducers({
  text: updateText,
  aid: updateAid
});

/sore/index

import thunk from "redux-thunk";
import appReducer from "./appReducers";
import { createStore, applyMiddleware } from "redux";

const searchMiddleware = store => next => action => {
  let result;
  result = next(action);
  return result;
};
export default (initialState = {}) => {
  return applyMiddleware(thunk, searchMiddleware)(createStore)(
    appReducer,
    initialState
  );
};

app/index
import "babel-polyfill";
import React from "react";
import ReactDOM from "react-dom";
import { browserHistory, Route, Router } from "react-router";
//REDUX PART
import storeFactory from "./store";
import { Provider } from "react-redux";
import initialState from "./store/initialState.json";
const store = storeFactory(initialState);

//components
import Home from "./home/home";

var app = document.getElementById("app");

ReactDOM.render(
  <Provider store={store}>
    <Router history={browserHistory}>
      <title> Search Page</title>
      <Route path={"/home"} component={Home} tab="Home" />
      <Route path={"*"} component={Home} tab="Home" />
    </Router>
  </Provider>,
  app
);

**Comment by rainzetroc** [comment]
![image](https://user-images.githubusercontent.com/44025015/47402602-0c2b9e80-d779-11e8-84de-822335530ce4.png)

**Comment by STRML** [comment]
This is not an RGL bug, this is your own code. It appears you're not binding the setState callback function properly.
