### ISSUE TITLE
Bug with grid item moving on modal background

### ISSUE THREAD

**Issue by fro3clr** [STRML/react-grid-layout#869]
Hi! I'm using your library and I'v found a serious problem.
There are a problem with MUI Dialog (I think you can reproduce this with any similar modal dialog component). React-grid-layout "locks" the mouse event after click on item. There are no way to prevent this. I was tried e.stopPropagation, preventDefault, zIndexes, etc.

Demo: https://codesandbox.io/s/o5m028np2z
Bug demonstration: 
![react-grid-layout-material-bug](https://user-images.githubusercontent.com/15067262/47447997-8edb4a80-d7c7-11e8-8109-70ffc5d4a524.gif)

As you can see, only the pressed element moves.

**Comment by Rick83600** [comment]
Hey 

```javascript
  onMouseDown = ev => {

   // You have todo a condition here for example : 
   // if (this.props.openModal) {
   //   ev.stopPropagation();
   // }


    ev.stopPropagation();
  };

  render() {
    return (
      <ReactGridLayout
        layout={this.state.layout}
        onLayoutChange={this.onLayoutChange}
        {...this.props}
      >
        {_.map(_.range(this.props.items), i => {
          return (
            <div className="grid-item" key={i}>
              <div onMouseDown={this.onMouseDown}>
                <div className="text">{i}</div>
                <MaterialModal />
              </div>
            </div>
          );
        })}
      </ReactGridLayout>
    );
  }
```

**Comment by autohub7** [comment]
> Hey
> 
> ```js
>   onMouseDown = ev => {
> 
>    // You have todo a condition here for example : 
>    // if (this.props.openModal) {
>    //   ev.stopPropagation();
>    // }
> 
> 
>     ev.stopPropagation();
>   };
> 
>   render() {
>     return (
>       <ReactGridLayout
>         layout={this.state.layout}
>         onLayoutChange={this.onLayoutChange}
>         {...this.props}
>       >
>         {_.map(_.range(this.props.items), i => {
>           return (
>             <div className="grid-item" key={i}>
>               <div onMouseDown={this.onMouseDown}>
>                 <div className="text">{i}</div>
>                 <MaterialModal />
>               </div>
>             </div>
>           );
>         })}
>       </ReactGridLayout>
>     );
>   }
> ```

I have the same issue and tried your solution. It doesn't work for me

**Comment by autohub7** [comment]
@Rick83600 I've tried this. It doesn't work for me. Have you tried it?

**Comment by autohub7** [comment]
It's listening mouse event if you put Modal inside of ReactGridLayout. It happens with other draggable libraries. I resolved this by adding onClick() in ReactGridLayout and put Modals outside of ReactGridLayout and listen the state change of the onClick event

**Comment by natemwilson** [comment]
I'm seeing this as well.

**Comment by waldenylson** [comment]
@natemwilson Thanks bro, you save me!
