### ISSUE TITLE
Indirect reactify dependency

### ISSUE THREAD

**Issue by Puffton** [STRML/react-grid-layout#87]
Version: 0.8.5 (and earlier)

Error: Cannot find module 'reactify' from '.../node_modules/react-grid-layout/node_modules/react-draggable'

It can be fixed in the package rather than forcing me to directly depend on reactify. See troubleshooting at the bottom of the page: https://github.com/andreypopp/reactify

Also, react-tools and reactify are being replaced by babel and babelify, it seems. Although personally I don't use reactify/babelify for anything (except react-grid-layout).

**Comment by diffractometer** [comment]
+1

**Comment by carloct** [comment]
+1

**Comment by kuy** [comment]
+1

**Comment by kaspyyy** [comment]
+1

**Comment by Puffton** [comment]
This is fixed in 0.10.0-beta1.
