### ISSUE TITLE
Text input 

### ISSUE THREAD

**Issue by aha555** [STRML/react-grid-layout#876]
A text input (textarea or input type=text) inside a grid item doesn't work as expected. I cannot type or resize a textarea.

**Comment by aha555** [comment]
Ok, adding 'static: true' property to a grid item on an input focus solved the problem

**Comment by renakim** [comment]
Hi, I have the same problem.
Is there any way to get text input to work properly with 'static: false' option? (movable & resizable)

**Comment by renakim** [comment]
I find #747. It's working for me.

**Comment by pxFIN** [comment]
For those interested if you want to cancel dragging (and also get focus) for your input box you can also use draggableCancel=".yourinputboxselectorhere"
