### ISSUE TITLE
Making an element static triggers strange layout behaviour

### ISSUE THREAD

**Issue by kakato10** [STRML/react-grid-layout#878]
Here's a demo of the bug.  Just click the "Make static" button.

Thanks in advance!

https://codesandbox.io/s/q82ny8kx7j

**Comment by sr1977** [comment]
I'm experiencing something similar, did you find a cause/solution?

**Comment by daynin** [comment]
Perhaps this is somehow relates to https://github.com/STRML/react-grid-layout/issues/965

**Comment by daynin** [comment]
It can't be reproduced (see #965), so I'll close this issue for now
