### ISSUE TITLE
Difference between items and layout in state?

### ISSUE THREAD

**Issue by Puffton** [STRML/react-grid-layout#88]
I'm allowing the user to change background on a grid item, when that happens, I copy all items into a new array and set the new BgImage on the corresponding item in the copied list (going with React's "immutable state"-mindset). The problem is that the layout and the items-array go out of sync, in this case, the item position does not update:

    itemBgChanged: function (el, e) {
      this.setState({items: copySet(this.state.items, 'i', el.i, 'BgImage', e.target.value)});
    },
    layoutChange: function (layout) {
      this.setState({layout: layout});
    },

Whereas in the following case, the positions update, but not BgImage:

    itemBgChanged: function (el, e) {
      this.setState({items: copySet(this.state.items, 'i', el.i, 'BgImage', e.target.value)});
    },
    layoutChange: function (layout) {
      this.setState({items: layout});
    },

What am I doing wrong? Why is there both a list of items and a layout, consisting of seemingly the same list of items?

Doing something like this in itemBgChanged works (but is not recommended as far as I have understood):

    el.BgImage = e.target.value;
    this.setState(el);

**Comment by STRML** [comment]
I'm not sure what this is referring to, I don't recall RGL ever having an `items` state key.

Please reopen if this is still affecting you.
