### ISSUE TITLE
reupload to npm

### ISSUE THREAD

**Issue by cxdn0** [STRML/react-grid-layout#885]
Hi! Please, reupload current version (0.16.6) to npm.
Now the package in npm is different from that on github.
Specifically in utils.js must be a
`const compactV = compactType !== "horizontal";`
string instead
`var compactV = compactType === "vertical";`
in moveElementAwayFromCollision function.

This creates a problem when moving items when verticalCompact=false
![moving-on-major-item](http://g.recordit.co/n8JkC3zeyh.gif)

...and
```
  var itemIndex = layout
    .map(layoutItem => {
      return layoutItem.i;
    })
    .indexOf(item.i);
```
instead
`var itemIndex = layout.indexOf(item);`
in function resolveCompactionCollision
because
![jump-bottom-item](http://g.recordit.co/tD6ShwLydY.gif)

**Comment by sgordon3** [comment]
There are also merged changes since the last release that have not been published. The onWidthChange for example would be welcomed.

**Comment by CWSites** [comment]
@STRML any update here?
