### ISSUE TITLE
Best doc: Clicking a grid item causes that item to drop far below my mouse pointer

### ISSUE THREAD

**Issue by fadjer** [STRML/react-grid-layout#887]
Hi. 

I was struggling several hours before resolving like exactly this issue, related to simple CSS rewrite: 

https://github.com/STRML/react-grid-layout/issues/171

```
The only CSS you need in order to fix this problem is

.react-grid-layout {
  position: relative;
}

```

Please improve the official doc with that. And give examples (demos) with content inside cells, not only unselectable text...

Thanks

**Comment by deridara** [comment]
Thanks for this issue! Helped a lot.

**Comment by CWSites** [comment]
You're welcome to submit a PR with updates to the documentation and a CSS update @fadjer :)
