### ISSUE TITLE
onLayoutChange occurs before onBreakpointChange

### ISSUE THREAD

**Issue by sgordon3** [STRML/react-grid-layout#889]
In Responsive, the onBreakpointChange event occurs after the onLayoutChange event. So if the onLayoutChange event is used to save the layout based upon the current breakpoint, the save will overwrite the previous layout becuase the breakpoint you would be updating will be the previous layout before changing breakpoints.

When resizing the browser, the onBreakpointChange event should fire before the onLayoutChange.

**Comment by CWSites** [comment]
@sgordon3 you're welcome to create a PR for this :)

**Comment by sgordon3** [comment]
OK, I will try to do that. Thanks.

**Comment by sgordon3** [comment]
@EliMiX Thanks for creating a pull request for this. Aplogize for not handling this.

**Comment by ranbena** [comment]
+1 for this.

My dashboard is set to auto-save the layout as it is changed, but at a certain breakpoint the dashboard switches to single column mode and should not be saved (or else the single column layout would trample the "normal" layout).
For that, I must block `onLayoutChanged` from propagating when `onBreakpointChanged` occurs. Not possible till this lands 🤞

```js
onBreakpointChange(mode) {
  this.mode = mode;
}

onLayoutChange(layout) {
  if (this.mode === 'sm') {
    return; // exit in single column mode
  }

  this.props.onLayoutChange(layout); // goes on to save the layout
}
```

**Comment by soasuk** [comment]
Using EliMiX's PR solved this issue for me. No adverse effects encountered so far.

**Comment by gjhommersom** [comment]
What is currently blocking the proposed pull request from being merged and/or is this something that I could contribute to?

**Comment by EliMiX** [comment]
I believed this was fixed on latest master with `this.props.onLayoutChange(layout, newLayouts);`

**Comment by gjhommersom** [comment]
Thanks for the response. I wasn't aware of that additional value in the event. I have done a quick investigation and it seems like it contains enough information for us to make things work. 

In my opinion it would still be better to change the order of these callbacks. I understand not doing this because it would be a breaking change, but it might be worth it to keep this in mind when another breaking change occurs.
