### ISSUE TITLE
The content doesn't fit within the cell.

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [STRML/react-grid-layout#890]
https://codesandbox.io/s/61845m6k43
Please find the link attached.  The contents of the cell overflows & doesn't fit nicely.
It is getting distorted with long contents.

**Comment by CWSites** [comment]
@aditya-padhi-kbl, the items inside the grid do not respond to the content of them. You'll need to figure out how you want to handle that on your own. You can use CSS to hide the content which doesn't fit, or you can add some code to evaluate the contents and change the size of the items. Either way, it's not in the scope of this project.

**Comment by STRML** [comment]
Thanks @CWSites .
