### ISSUE TITLE
Spam link in README

### ISSUE THREAD

**Issue by adamtaylor13** [STRML/react-grid-layout#898]
The link in the README actually links out to spam sites now. Might want to just take it down considering I saw there were other issues where the link was broken.

**Comment by CWSites** [comment]
@adamtaylor13 which link is the spam link?

**Comment by CWSites** [comment]
FYI @STRML, this can be closed once PR #906 is merged.

**Comment by STRML** [comment]
Fixed in #906, thanks @CWSites.
