### ISSUE TITLE
draggable dependency is creating issues

### ISSUE THREAD

**Issue by georgzoeller** [STRML/react-grid-layout#9]
The custom react-draggable fork referenced in package.json is causing issues with npm on winx86

  npm http 304 http://registry.npmjs.org/react-draggable
  npm WARN `git config --get remote.origin.url` returned wrong result
  (git://github.com/strml/react-draggable) 
  npm http 304 http://registry.npmjs.org/react-resizable
  npm WARN `git config --get remote.origin.url` returned wrong result
  (git@github.com:strml/react-draggable) 
  npm ERR! notarget No compatible version found: react-draggable@'strm
  l/react-draggable'
  npm ERR! notarget Valid install targets:
  npm ERR! notarget ["0.1.0","0.1.1","0.2.0","0.2.1","0.3.0","0.4.0"]
  npm ERR! notarget
  npm ERR! notarget This is most likely not a problem with npm itself.

  npm ERR! notarget In most cases you or one of your dependencies are
  requesting
  npm ERR! notarget a package version that doesn't exist.

  npm ERR! System Windows_NT 6.1.7601
  npm ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Pr
  program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "inst
  all" "react-grid-layout" "--save"
  npm ERR! node -v v0.10.25
  npm ERR! npm -v 1.3.24
  npm ERR! code ETARGET
  npm ERR!
  npm ERR! Additional logging details can be found in:
  npm ERR! not ok code 0

**Comment by STRML** [comment]
Can you confirm this isn't a problem with your invocation of npm install
outside of git bash? https://github.com/npm/npm/issues/2333

**Comment by georgzoeller** [comment]
I can confirm this is not related to this bug. (GNU bash, version 3.1.0(1)-release (i686-pc-msys))

**Comment by STRML** [comment]
Can you upgrade your version of npm? Perhaps that was a version before they added the github shorthand. `1.3.24` is pretty old, even on the `1.x` branch.

**Comment by STRML** [comment]
@georgzoeller Could you please report back on what happens with an up-to-date `npm` so I can close this?

**Comment by georgzoeller** [comment]
Will do as soon as I am back at the computer that has the issue :)

**Comment by georgzoeller** [comment]
Latest npm fixes it.

**Comment by georgzoeller** [comment]
An additional note:

The actual problem is related to npm behind a proxy behaving troublesome with git urls on windows.

git config --global url."https://".insteadOf git://

fixes it reliably.
