### ISSUE TITLE
MouseClick on GridItem let move the Item - Why? :|

### ISSUE THREAD

**Issue by PirolA** [STRML/react-grid-layout#901]
Here is the link to reproduce the bug: https://codesandbox.io/s/r0kqjk8xq4

You have to open the resulting layout in a new window ("Open in new window") then resize the newly opened window to the half. After that you have to click on a griditem which has no neighbor to the right -> Here you go, the item jumps to the right.

**Comment by PirolA** [comment]
it has nothing to do with the fact that x is greater than y. The bug always occurs when the size of the windows has reached a multiple of x, then the problem is there. At an x-value of 70px, the bug appears starting from a window size of about 21 times, that is about window width of 1500px.

**Comment by bartoszkrawczyk2** [comment]
I'm experiencing the same issue. Any update on this? Have you managed to solve it @PirolA ?

**Comment by bartoszkrawczyk2** [comment]
@PirolA for me setting the same value ([20, 20]) for `containerPadding` as `margin` on `<GridLayout>` solved this issue.

**Comment by daynin** [comment]
maybe it relates to https://github.com/STRML/react-grid-layout/issues/866
