### ISSUE TITLE
Layouts (stored in local storage) are being reset every reload

### ISSUE THREAD

**Issue by hkKevin** [STRML/react-grid-layout#902]
Hi! Regarding [Demo 8 - Responsive with LocalStorage](https://strml.github.io/react-grid-layout/examples/8-localstorage-responsive.html),
 ### Is react-grid-item accept data(an array) fetched from Firebase?

Below is my class component of a memo app:
```
...
...
...
render(){
 return (
  <div>
    <ResponsiveReactGridLayout
        className="layout"
        breakpoints={{lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0}}
        cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 1 }}
        rowHeight={40}
        layouts={this.state.layouts}
        onLayoutChange={(layout, layouts) =>
            this.onLayoutChange(layout, layouts)
         }>
        {this.props.addedMemos.map(memo => (
            {/* 1st div */}
            <div key={memo.id}>
                <div onClick={() => this.memoClicked(memo)}>
                     <h3>{memo.title}</h3>
                     <hr />
                     <div>{memo.content}</div>
                </div>
            </div>

            {/* 2nd div */}
            <div key="1">
                <div>
                    <h3>Title</h3>
                    <hr />
                    <div>Content</div>
                </div>
            </div>
                ))}
    </ResponsiveReactGridLayout>
 </div>
 );
}
```

Because it seems that **the layouts(stored in local storage) for fetched data (from Firebase) are being reset every time I reload**. That means the postitions of those data are stack on the top-left corner in every reload. 

2nd div:
However, the **hard-coded 2nd div doesn't lost its layouts in local storage**. The position of the 2nd div memo remains after reload. That's why I am wondering if `react-grid-item` support data fetching from Firebase(or other online db).

1st div:
I have tried `axios` and `fetch()` to get the data(an array) from Firebase via Redux ( `this.props.addedMemos` is an array from Redux store ). The data from Firebase is fetched successfully tho. If I don't reload the page and resize the grid items, the layouts are changed successfully in local storage. The local storage functions `saveToLS` and `getFromLS` are working fine too.

Thank you for your time~

**Comment by CWSites** [comment]
The code you have above doesn't seem complete. I don't see where you are using `getFromLS` or `saveToLS` for your layouts. This is how I have mine coded and it works fine. The contents of each `div` do not have any impact on the layout which is stored. You just have to make sure to properly use `getFromLS` and `saveToLS`

**Component**
```
constructor(props) {
  super(props);
  this.onLayoutChange = this.onLayoutChange.bind(this);
  this.state = {
    layouts: getFromLS('unique_local_storage_key_for_layouts')
  }
}

// When layout is changed, save latest to localStorage
onLayoutChange(layout, newLayout) {
  saveLayoutToLS('unique_local_storage_key_for_layouts', newLayout);
  this.setState({ layouts: newLayout });
}

render() {
  return (
    <ResponsiveGridLayout
      layouts={this.state.layouts}
      onLayoutChange={(layout, newLayout) =>
          this.onLayoutChange(layout, newLayout)
      }>
      <div key="1">...</div>
      <div key="2">...</div>
    </ResponsiveGridLayout>
  );
}
```

**Local Storage Helpers**
```
export function getFromLS(layoutName) {
  if(global.localStorage) {
    let savedLayout = global.localStorage.getItem(layoutName);

    if(savedLayout && !emptyObject(savedLayout)) {
      return JSON.parse(savedLayout).layouts;
    } else {
      // defaultLayout is defined elsewhere, when nothing in LocalStorage it's how it should be.
      return defaultLayout;
    }
  }
}

// Save layout preference to localStorage
export function saveLayoutToLS(layoutName, value) {
  if(global.localStorage) {
    global.localStorage.setItem(layoutName, JSON.stringify({ layouts: value }));
  } else {
    console.error('localStorage is not supported');
  }
}
```

**Comment by hkKevin** [comment]
> The code you have above doesn't seem complete. I don't see where you are using `getFromLS` or `saveToLS` for your layouts. This is how I have mine coded and it works fine. The contents of each `div` do not have any impact on the layout which is stored. You just have to make sure to properly use `getFromLS` and `saveToLS`
> 
> **Component**
> 
> ```
> constructor(props) {
>   super(props);
>   this.onLayoutChange = this.onLayoutChange.bind(this);
>   this.state = {
>     layouts: getFromLS('unique_local_storage_key_for_layouts')
>   }
> }
> 
> // When layout is changed, save latest to localStorage
> onLayoutChange(layout, newLayout) {
>   saveLayoutToLS('unique_local_storage_key_for_layouts', newLayout);
>   this.setState({ layouts: newLayout });
> }
> 
> render() {
>   return (
>     <ResponsiveGridLayout
>       layouts={this.state.layouts}
>       onLayoutChange={(layout, newLayout) =>
>           this.onLayoutChange(layout, newLayout)
>       }>
>       <div key="1">...</div>
>       <div key="2">...</div>
>     </ResponsiveGridLayout>
>   );
> }
> ```
> **Local Storage Helpers**
> 
> ```
> export function getFromLS(layoutName) {
>   if(global.localStorage) {
>     let savedLayout = global.localStorage.getItem(layoutName);
> 
>     if(savedLayout && !emptyObject(savedLayout)) {
>       return JSON.parse(savedLayout).layouts;
>     } else {
>       // defaultLayout is defined elsewhere, when nothing in LocalStorage it's how it should be.
>       return defaultLayout;
>     }
>   }
> }
> 
> // Save layout preference to localStorage
> export function saveLayoutToLS(layoutName, value) {
>   if(global.localStorage) {
>     global.localStorage.setItem(layoutName, JSON.stringify({ layouts: value }));
>   } else {
>     console.error('localStorage is not supported');
>   }
> }
> ```

Hi @CWSites , here is my `getFromLS` and `saveToLS` functions (basically copy from [RGL Demo 8 - Responsive with LocalStorage](https://strml.github.io/react-grid-layout/examples/8-localstorage-responsive.html) cuz I'm still a rookie):
```
function getFromLS(key) {
   let ls = {};
   if (global.localStorage) {
     try {
        ls = JSON.parse(global.localStorage.getItem("memo")) || {};
      } catch (e) {
        /*Ignore*/
      }
   }
   return ls[key];
}

function saveToLS(key, value) {
   if (global.localStorage) {
     global.localStorage.setItem(
       "memo",
       JSON.stringify({
         [key]: value
       })
     );
   }
}
```

- Besides, I wonder what is this `emptyObject` in your code( `!emptyObject(savedLayout))`) ? Could u show me how and where to define `emptyObject`?

- Is it acceptable to declare `defaultLayout` like this `{ lg: { x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 } }` for an array of data? If not, could u teach me how to declare `defaultLayout` for an dynamic length of data?

- Lastly, have u tried to use your approach to get & show data from firebase? Does the layout remains after u change the layout for those fetched data and reload?

Thank you Matt.

**Comment by CWSites** [comment]
Can you post your entire code that you're working with? I'd like to see where you are using `getFromLS` and saving that to your `state.layouts`

When using localStorage for your layouts `key: value` you almost have it. `lg` needs to be an array of objects, and each object needs it's own unique identifier, in my case I'm using `i`. When you add another breakpoint such as `md` for medium it will have the same setup, and so on.

```
layouts: {
    lg: [
        { i: '1', x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 },
        { i: '2', x: 4, y: 0, w: 4, h: 4, minW: 4, maxW: 8 },
        { i: '3', x: 8, y: 0, w: 4, h: 4, minW: 4, maxW: 8 }
    ],
    md: [...]
}
```

For `emptyObject` I wrote a simple helper that checks to see if something is an empty object.

**emptyObject**
```
export const emptyObject = (data) => {
    let isEmpty = true;

    if(data && data !== 'undefined' && data !== null) {
        isEmpty = Object.keys(data).length === 0 && data.constructor === Object;
    }

    return isEmpty;
}
```

I haven't used firebase for this but it shouldn't matter where you are getting or saving your data to. If you can get it to work with localStorage then you can save/get that same `layouts` object to firebase. The difference would be inside your functions. Something like this...

```
function saveToFirebase(key, value) {
    let savedLayout = {};
    savedLayout.memo = JSON.stringify({ [key]: value });

    // code here to send an object to firebase
}
```

You'll probably want to use PATCH to update existing data without completely overwriting existing data. That way you are only updating your `memo` object and nothing else. https://firebase.google.com/docs/database/rest/save-data

**Comment by CWSites** [comment]
Hey @hkKevin, 

I looked at the code that you sent over and I believe the issue was with how you were saving the layout back to localStorage.

This is what you had
```
defaultLayout: {
    lg: { x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 },
    md: { x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 },
    sm: { x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 },
    xs: { x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 },
    xxs: { x: 0, y: 0, w: 2, h: 2, minW: 2, maxW: 8 }
}
```

The problem is, each of these need to be an array of objects like so
```
defaultLayout: {
    lg: [{ x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 }],
    md: [{ x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 }],
    sm: [{ x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 }],
    xs: [{ x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 }],
    xxs: [{ x: 0, y: 0, w: 2, h: 2, minW: 2, maxW: 8 }]
}
```

You were also doing the same thing in your `getFromLS()`. Just update anywhere you have `lg` being saved as an object to an array of objects.
```
function getFromLS(layoutName) {
    if (global.localStorage) {
        let savedLayout = global.localStorage.getItem(layoutName);
        if (savedLayout && !emptyObject(savedLayout)) {
            return JSON.parse(savedLayout).layouts;
        } else {
            // Not sure how to construct defaultLayout for dynamic numbers of memos
            return { lg: { x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 } };
        }
    }
}
```
It should be `return { lg: [{ x: 0, y: 0, w: 4, h: 4, minW: 4, maxW: 8 }] };`.  Make sure you fix line `180` as well, you had the same thing there.

**Comment by hkKevin** [comment]
Hi @CWSites ,
Thanks for letting me know the defaultLayout needs to be an array of objects, but it still doesn't work.

Here are some screenshots to demonstrate the problem:

- When I resize and drag memos to particular positions, the `onLayoutChange` and `saveToLS()` are working fine. The layout in local storage change instantly like [this](https://i.imgur.com/5xR065G.png).
- Once I reload the page, the memo fetched from **Firebase** tends to **lost its stored layout** and reset to `{w: 1, h: 1, x: 0, y: 0, i: "..."}`, even my defaultLayout is set to this:
```
static get defaultProps() {
    return {
      className: "layout",
      cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
      rowHeight: 30,
      onLayoutChange: function () { },
      defaultLayout: {
        lg: [{ x: 2, y: 0, w: 4, h: 4, minW: 4, maxW: 8 }],
        md: [{ x: 2, y: 0, w: 4, h: 4, minW: 4, maxW: 8 }],
        sm: [{ x: 2, y: 0, w: 4, h: 4, minW: 4, maxW: 8 }],
        xs: [{ x: 2, y: 0, w: 4, h: 4, minW: 4, maxW: 8 }],
        xxs: [{ x: 2, y: 0, w: 2, h: 2, minW: 2, maxW: 8 }],
      },
    };
  }
```
[screenshot](https://i.imgur.com/FRxYFIE.png)
- However, I had set `console.log` right after the constructor to display the layout on init (after reload):
```
constructor(props) {
    super(props);

    this.btnDropdownToggle = this.btnDropdownToggle.bind(this);
    this.btnDropdownSelect = this.btnDropdownSelect.bind(this);
    this.onLayoutChange = this.onLayoutChange.bind(this);
    this.state = {
      hasTitle: false,
      hasContent: false,
      dropdownOpen: false,
      db: null,
      //
      layouts: getFromLS('layouts'),

    };
    console.log(this.state.layouts);
  }
```
As u can see the [screenshot](https://i.imgur.com/msF8kek.png), layout element 0 (the memo fetched from Firebase) still retains the layout before reload. That means the `getFromLS()` works fine. It seems only one step from the goal but I can't figure out what's wrong. I'm not sure why the program ignores the saved layouts for memos fetched from **Firebase**.

Thanks again.

**Comment by CWSites** [comment]
Would it be possible to get a working version of your code somewhere? It's hard to troubleshoot something like this, let alone with screenshots and code snippets.

I recommend adding a lot of `console.log()` in various parts and try to pinpoint where it is being overwritten. 

From what I can gather you're saying that you are able to load the memo correctly from firebase with the correct layout, but as soon as you reload the page it changes to a different size... Do the values saved to firebase change to the wrong ones? Where do you grab the data from Firebase, because your code just shows that you're using local storage.

**Comment by hkKevin** [comment]
[Here ](https://drive.google.com/open?id=1gYOeJ5SD0l_xVRTx0PRW1CtaPLRo2I6S)is my current memo app from Google Drive that has the mentioned problem. Please execute `npm install` and `npm start` to investigate🙏.

In my current memo app:

All gridLayout is saved to localStorage.

There are two types of memo:
1. The title and content of memo are stored on Firebase.
2. The title and content of memo are stored on local array.

Both type of memo can store the layout to localStorage successfully while resizing or dragging.
However, Type 1 of the memo will lose the layout after reload, while Type 2 of the memo will NOT lose the layout after reload.

**Comment by CWSites** [comment]
Hey @hkKevin, I verified that when you modify your Firebase widget it does save to localStorage properly and is called back properly when your page reloads.

Here is what I've tracked down so far...

1. `mapStateToProps` is called immediately, even before `componentDidMount()` which returns an empty array for your `state.memos`
2. `onLayoutChange()` is being called before your component mounts, with your firebase widgets missing. This is causing the layout that you load from localStorage to be overwritten, thus the firebase widget isn't maintaining size & position.
3. I wouldn't return data from `mapStateToProps` until you know that you have a response from firebase. If you don't get a response from firebase then perhaps fallback on localStorage? **I believe this is the primary cause of your problem. You're trying to generate firebase widgets before you have a response. If you don't have a response yet then use the widget saved to localStorage and don't overwrite it with `onLayoutChange`** 
4. `this.props.onFetchMemos()` is being called in `componentDidMount()` I moved it up to `componentWillMount()`  so that it can get started in the process a little earlier.


Here are the changes I made to your code.
```
  componentWillMount() {
    console.log('componentWillMount');
    console.log(this.state.layouts);
    this.props.onFetchMemos();
  }

  componentDidMount() {
    console.log('componentDidMount');
    console.log(this.state.layouts); // layout is correct here
    ...
  }

  onLayoutChange(layout, newLayout) {
    console.log('onLayoutChange');
    console.log(this.state.layouts); // correct first time

    console.log(layout); // missing the firebase widget here
    saveToLS("layouts", newLayout);
    this.setState({ layouts: newLayout });
  }


  generateAddedMemos = () => {
    console.log('generateAddedMemos');
    console.log(this.props.addedMemos);
    if(this.props.addedMemos.length > 0) {
      return this.props.addedMemos.map(memo => (
        <div key={memo.id}>
          <div onClick={() => this.memoClicked(memo)}>
            <h3>{memo.title}</h3>
            <hr />
            <div>{memo.content}</div>
          </div>
        </div>
      ));
    } else {
      console.error('no firebase widgets available yet.');
    }
  }

  generateDummyMemos = (dummyMemos) => {
    console.log('generateDummyMemos');
    return dummyMemos.map(memo => (
      <div key={memo.id}>
        <div onClick={() => this.memoClicked(memo)}>
          <h3>{memo.title}</h3>
          <hr />
          <div>{memo.content}</div>
        </div>
      </div>
    ));
  }
```

I suggest breaking out your widget mapping into their own functions to clean up your component code. I included `generateAddedMemos()` and `generateDummyMemos()` above. Here is the modified component render code.

```
  <ResponsiveReactGridLayout
    className="layout"
    breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
    cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 1 }}
    rowHeight={40}
    layouts={this.state.layouts}
    onLayoutChange={(layout, newLayout) =>
      this.onLayoutChange(layout, newLayout)
    }>
      {this.generateAddedMemos()}
      {this.generateDummyMemos(dummyMemos)}
    </ResponsiveReactGridLayout>
```

**Comment by hkKevin** [comment]
I did it! Working great. 
Thank you very much @CWSites!!!
The solution is to execute the follow code until the memos are fetched successfully from Firebase.
```
<ResponsiveReactGridLayout
    className="layout"
    breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
    cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 1 }}
    rowHeight={40}
    layouts={this.state.layouts}
    onLayoutChange={(layout, newLayout) =>
      this.onLayoutChange(layout, newLayout)
    }>
      {this.generateAddedMemos()}
      {this.generateDummyMemos(dummyMemos)}
    </ResponsiveReactGridLayout>
```
Also, I fetch the memos in function `componentWillMount`.

**Comment by lallen-6** [comment]
Hi,
I am having a similar issue in getting my react-grid-layout to read from local storage when it loads. I want to save it and access the layouts using the username key which is specific to each different user. I can save the layouts into local storage, and have had no problem doing that, however when I try to 'getLayout' from LS, I get an error everytime. I was wonderign if you'd be able to help, my code for al is below:

``` 
const ReactGridLayout = WidthProvider(Responsive);

//Find username form localstorage (uuid string)
const username = localStorage.getItem('username')

const Dash = (props) => {
  //Variable used for id of grid component:
  const id = uuid()
   
  //Hook to set layout state
  const originialLayouts = getLayout("layouts") || {}
  const savedLayout = JSON.parse(JSON.stringify(originialLayouts))
  console.log(JSON.parse(JSON.stringify(originialLayouts)))

  //column size is static
  //layouts taken from local storage via function
  const [ state, setState ] = React.useState({
    cols: { lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 },
    rowHeight: 30,
    layouts: JSON.parse(JSON.stringify(originialLayouts)) || state.layout,
    layout: [].map(function(i, list) {
      return {
        i: i.toString(),
        x: i * 2,
        y: 0,
        w: 3,
        h: 3,
        add: i === (list.length - 1)
      }
    })
  })

  //function ammends layout array with additional grid item
  const addItem = (item) => { 
    console.log('adding: ' + id);
    const newLayout = state.layout;
    newLayout.push({
      i: `${id}`,
      x: (state.layout.length * 3) % (state.cols || 12),
      y: 0,
      w: 3,
      h: 3
    })
    setState({layout: newLayout})
  }

  //function to remove grid item on click
  const removeItem = (i) => {
    console.log(i)
    setState({ layout: _.reject(state.layout, { i:i }) })     
  }

  //function to save layout to LS everytime a grid item is moved.
  const onLayoutChange = (layout, layouts) => {
    console.log(layouts)
    saveLayout("layouts", layouts)
    console.log(state.layout)
  }


  return (
    <div>
      <button onClick={addItem}>Add Item</button>
        <ReactGridLayout
          className="layout"
          breakpoints={{ lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }}
          onLayoutChange={(layout, layouts) => onLayoutChange(layout, layouts)}
          cols={{ lg: 12, md: 12, sm: 6, xs: 4, xxs: 2 }}
          resizeHandles={['s', 'w', 'e', 'n', 'sw', 'nw','se', 'ne']}
          compactType={"vertical"}
          draggableHandle=".dragHandle"               
      >        
        {_.map(state.layout, (item, i) => (
          <div key={item.i} data-grid={state.layout[i]}>            
            <div className='dragHandle'>Drag From Here</div>                        
            <DashItem>
            <button onClick={() => removeItem(item.i)}>Remove Item</button>  
                 <CreateGraph key ={i} data={state.layout[i]}/>
            </DashItem>
            <div className='dragHandle'>Drag From Here</div>
          </div>
        ))}
        </ReactGridLayout>
    </div>
  );
}

//function to get user layout from LS
const getLayout = (key) => {
  let ls = {};
  if (global.localStorage) {
    try {
      ls = JSON.parse(global.localStorage.getItem(username)) || {};
    } catch (error) {
      console.log('error with getLayout')
    }
  }
  return ls[key]
}

//function to save user layout to LS
const saveLayout = ( key, value ) => {
  if (global.localStorage) {
    global.localStorage.setItem( username, JSON.stringify({ [key]: value}) );
  }
}

export default Dash;

``` 
Thanks in advance
