### ISSUE TITLE
HOw to get the height and width of reactjs grid layout

### ISSUE THREAD

**Issue by Henry667** [STRML/react-grid-layout#915]
Hi STRML,

Need help over how to get the height and width of reactjs grid layout so on basis of i can handle the container dimension..

For example..
I want to make card inside the grid layout, what is actually happening is card is not moved when i move that grid layout also the issue of height and width of card.

```x: 0, // minimum Width
            y: 0, // maximum Width
            w: 15, // minimum Height
            h: 10, // maximum Height```
All this value stand for minimum Width, maximum Width, minimum Height, maximum Height

**Comment by Henry667** [comment]
Here is a code. `
generateDOM() {

        return _.map(this.state.layouts.lg, (l, i) => {
            return (
                <div key={i}>
                    {(
                        <Card style={{ width: 'auto', height: 'auto' }} border="primary">
                            <Card.Body>
                                <Card.Header>{l.textData[i].text}</Card.Header>
                                <Card.Text>
                                    {l.textData[i].dataSource}
                                </Card.Text>
                            </Card.Body>
                        </Card>
                    )}
                </div>
            );
        });
    }
            <div>
                <ResponsiveReactGridLayout
                    {...this.props}
                    layouts={this.state.layouts}
                    onBreakpointChange={this.onBreakpointChange}
                    onLayoutChange={this.onLayoutChange}
                    measureBeforeMount={false}
                    useCSSTransforms={this.state.mounted}
                    compactType={this.state.compactType}
                    preventCollision={!this.state.compactType}
                >
                    {this.generateDOM()}
                </ResponsiveReactGridLayout>
            </div>`

**Comment by justdvl** [comment]
Hello Henry, I don't understand your English very well, but overall, this would be  a general way of how to get a dimensions of one layout grid item:

I will suppose you have already created a component for the grid item. This component should have a render method, where you are rendering it. It consists of some divs and spans, such as 
<div>
  <header>
  ...
  </header>
  ...
  <footer>
  ...
  </footer>
</div>

header and footer can be a div, span, or a styled components.
If you will find y coordinates of header and footer, you can easily calculate item's height.

Let's start with header:
In the constructor, add: 
`this.getHeader = HTMLElement;`

In the render return statement of your item, add ref to a div or span tag that is header:
```
                <header
                    ref={(header) => this.getHeader = header}
                >
```
if you are using styled components, replace ref with innerRef.

Now anywhere in the code, for example in ComponentDidMount method, you can get the x,y coordinates (and others) of that header ref:

`console.log(this.getHeader.getBoundingClientRect().height)`

Hovewer before you ask that, you should verify that this header div was rendered before you ask for it's height.. 

```
if(typeof this.getHeader === 'object' && this.getHeader) {
console.log(this.getHeader.getBoundingClientRect().height)
}
```
So you know how to get coordiates of header. Do the same for footer, and you have a height of your grid item..

**Comment by Henry667** [comment]
Thanks for help.
