### ISSUE TITLE
GridItem calcXY calculation is wrong

### ISSUE THREAD

**Issue by xiaobao66** [STRML/react-grid-layout#918]
Hi, thank you very much for this awesome grid system.
When the margin property and containerPadding property is not the same, dragging placeholder is far behind the dragging gridItem.
You can see the demo here: [https://codesandbox.io/embed/m94wn5k3y?autoresize=1&fontsize=14&hidenavigation=1&view=preview](https://codesandbox.io/embed/m94wn5k3y?autoresize=1&fontsize=14&hidenavigation=1&view=preview)
The cause of the problem is GridItem's calcXY function.The calculation of left and top value has a little wrong.It should be 

> left = colWidth * x + margin * x + **containerPadding**

 rather than

> left = colWidth * x + margin * x + **margin**

I have solved the problem and create a pull request. By any chance, could you help check the pr

**Comment by STRML** [comment]
Thanks for this. I'll find some time soon to check on it as it appears you are right.
