### ISSUE TITLE
Allow adding custom properties to layout items

### ISSUE THREAD

**Issue by snax4a** [STRML/react-grid-layout#929]
Hello,
I am making widgets page, each widget has its own settings which I need to store in the database, to be able to re-render these widgets with their custom settings on a grid layout.

@STRML Your library is really good for this purpose but there is one thing that I can't handle.
I have no idea how could I store each grid item custom properties.
When I try to add custom properties to grid item in layout array onLayoutChange event is automatically removing these my custom properties.
For example, I tried to add type to grid item:
`{"w":3,"h":3,"x":8,"y":0,"i":"n0", "type": "counter"},
  {"w":3,"h":3,"x":3,"y":0,"i":"n1r", "type": "list"}`

This would help me to determine which widget I should render on a grid because I want to have different widgets.

Do you guys have any ideas about how can I store my custom grid item properties in database if I cant add them to my layout json?

Thanks for your help.

**Comment by ranbena** [comment]
+1

I have a similar case, my grid items can have a certain custom feature which needs to be indicated in the layout array, but it gets lost on layout change.
`{ "w":3,"h":3,"x":8,"y":0,"i":"n0", "autoHeight": true }`

**Comment by STRML** [comment]
It is not intended or supported to put arbitrary data here. Store a map
elsewhere correlating grid ids with arbitrary data.

**Comment by ranbena** [comment]
Fair enough 👍

**Comment by ddtch** [comment]
Topic is close but htis question still relevant tbh. why not just keep prop like data. corelating in one more object witha data its just a double job that is redundand
