### ISSUE TITLE
Get the initial breakpoint?

### ISSUE THREAD

**Issue by tlrobinson** [STRML/react-grid-layout#93]
It would be nice if there were a way to get the initial breakpoint, perhaps by calling `onBreakpointChange`    in one of the initial lifecycle methods.

**Comment by STRML** [comment]
Since both the breakpoints and width are user-set I don't see this as an issue. Please reopen if you have more details.

**Comment by sylv3r** [comment]
@STRML in responsive mode, they are not.

So how to get the initial breakpoint RGL is selecting based on its initial width ? I don't see any methods or callbacks helping here. `onBreakpointChange` is not triggered during initial rendering.
