### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by mnemanja** [STRML/react-grid-layout#931]
There are some pretty old issues (almost 3 years old) in here, and the responses to the current ones are lacking.

Could @STRML provide some insight into the state of this project?

Much obliged.

**Comment by mankinchi** [comment]
I'm interested in this too. I'm planning to use this but nothing has been updated recently

**Comment by JSteeleAZ** [comment]
#following

**Comment by STRML** [comment]
I am not actively fixing issues or doing new features as I have not had enough time for open source lately. I am open to high-quality contributions and allowing new contributors. See #346 and so on where this is discussed at length.
