### ISSUE TITLE
Missing Donate or Buy Beer Button 

### ISSUE THREAD

**Issue by makis-spy** [STRML/react-grid-layout#932]
Seriously, we a s a community should be able to help and reward the authors as much as possible not only with PRs but financially. I know I'm down and I bet a lot of companies who use this awesome kit would be.

**Comment by STRML** [comment]
I appreciate the gesture. I would be open to a button, but not for myself - it would be better put toward funding new contributors.

**Comment by makis-spy** [comment]
I wonder if something like https://opencollective.com/ might be worth it something i came across with date-fns
