### ISSUE TITLE
resize items, when react-grid-layout(div) width is changed

### ISSUE THREAD

**Issue by MaksZhukov** [STRML/react-grid-layout#933]
For example, we have sider on the left and react-grid-layout(div) on the right.
We toggle the sider, then the width of the react-grid-layout(div) is changed, but items are not resized.
![image](https://user-images.githubusercontent.com/23615115/56433041-444f0c80-62d8-11e9-9e96-03895ca438d6.png)
![image](https://user-images.githubusercontent.com/23615115/56433050-4ca74780-62d8-11e9-94ad-76fb79210ef2.png)

**Comment by bartoszkrawczyk2** [comment]
You can trigger resize event when you expand/collapse sidebar:
```
window.dispatchEvent(new Event('resize'));
```

**Comment by mnemanja** [comment]
@MaksZhukov Can you please confirm that this solved your issue? Thanks!

**Comment by akritskiy** [comment]
@bartoszkrawczyk2 
This worked for me. If you have a transition on your sidebar, you can do a setTimeout at 0ms, 10ms, 20ms, etc. until the end of your transition to make the resize smooth.

```
for (let t = 0; t <= 300; t += 10) {
  setTimeout(() => {
    window.dispatchEvent(new Event('resize'))
  }, t)
}
```

**Comment by codersidprogrammer** [comment]
where should i place the `window.dispatchEvent(new Event('resize'))`?

**Comment by bartoszkrawczyk2** [comment]
> where should i place the `window.dispatchEvent(new Event('resize'))`?

Whenever you change something that will expand or shrink the width of element that contains your grid. For example in the thread author's case that would be `onClick` handler on the collapse/expand button in the sidebar

**Comment by kikkiraj** [comment]
Can you please share the code

**Comment by rizwansh-kore** [comment]
Worked for me too! Thanks!

**Comment by noams-unbiased** [comment]
Although the solution above works - it forces the surrounding applications to manually 'tell' react-grid-layout to by issuing a resize event on the entire window. 
If the parent component resizes - why won't the grid identify it and re-render on its own? a simple ResizeObserver on the root node should do the trick.
