### ISSUE TITLE
Grid item to with expand/collapse capability

### ISSUE THREAD

**Issue by tpham** [STRML/react-grid-layout#938]
Not a bug, just a question - I want to implement grid items to behave like window panels with expand and collapse buttons. When expand button is clicked, I'd like the targeted grid item to go on top of other grid items (which stay where they are without being re-positioned) and expands to full size within the container it is in. When collapse button is clicked, the grid item would go back to its original size and position. Is it possible? Any pointer is greatly appreciated.

**Comment by s-kris** [comment]
I'm looking for a similar functionality. Is there a way we can make the grid item take up all the available space in the canvas? 
Thanks.

**Comment by nitesh619** [comment]
Hi, @tpham 
I recently implemented the expand/collapse on the grid item when the user clicks the expand button.
To achieve this, I have set some height(say 30px) for grid item(i.e height when collapsed). and then the 'h' property in the layout is set to 1(i.e show 30px).  when user clicks on the expand button then we update the height to 2(if we want 60px) or any other value depending on your expanded area.

I hope, this will help you with your need.

Regards
Nitesh Jain

**Comment by nitesh619** [comment]
@s-kris , to make your gird item expand and cover the whole canvas area. You can set the w(width) and h(height) property of layout for that particular item to max value;
Max value for width will be: w = number of columns (depending on a current breakpoint) or try Infinity
h = this you need to find out by hit and trial I guess. or by mathematics.

Regards
Nitesh Jain

**Comment by josesaranda** [comment]
Use `window.dispatchEvent(new Event('resize'));` when you want that react-grid-layout resize dynamically. After you listen the collapse event from your awesome component run `window.dispatchEvent(new Event('resize'));` this will make to react-grid-layout to trigger a resize listener and will automatically resize the grid container.

Please close this issue if that work for you.

**Comment by gelyaa** [comment]
in the meantime does there exist a better solution to this problem? `window.dispatchEvent(new Event('resize'));` did not work for me.

**Comment by ncioj10** [comment]
Implmeneted a solution with ResizeObserver (so it automatically rescales the grid items):

`useResizeObserver()` Hook:
```

const {ResizeObserver} = window;

export const useResizeObserver: () => [(value: (((prevState: (Element | null)) => (Element | null)) | Element | null)) => void, ResizeObserverEntry] = () => {
  const [observerEntry, setObserverEntry] = useState<ResizeObserverEntry>({} as ResizeObserverEntry);
  const [node, setNode] = useState<Element | null>(null);
  const observer = useRef<ResizeObserver | null>(null);

  const disconnect = useCallback(() => observer.current?.disconnect(), []);

  const observe = useCallback(() => {
    observer.current = new ResizeObserver(([entry]) => setObserverEntry(entry));
    if (node) observer.current.observe(node);
  }, [node]);

  useLayoutEffect(() => {
    observe();
    return () => disconnect();
  }, [disconnect, observe]);

  return [setNode, observerEntry];
};

```

Use Intermediary Component for each grid item (so within grid <div>) which contains:

```

  const getContentRect = useCallback(
    () => {
      if(contentRect){
        // Set Layout State of grid with new height measured by ResizeObserver
        // ... Code to get new Layout state
        innerProps.setLayout(newLayout);
      }
      },
    [contentRect]
  );

  useEffect(() => getContentRect(), [getContentRect]);

```
