### ISSUE TITLE
Question about onLayoutChange and layout props

### ISSUE THREAD

**Issue by f15gdsy** [STRML/react-grid-layout#94]
Hi, thanks for the amazing plugin!
I want to make something like your add / remove grid items example.
But I don't really understand the use of onLayoutChange and layout props.
1. What should I write in onLayoutChange function?
2. How can I get the current layout props? Or do I need to keep track of it myself? How should I update it (like when resizing, dragging or adding new items)?

**Comment by STRML** [comment]
Sorry, this is really open-ended. If you need more help please go to IRC.
