### ISSUE TITLE
react-resizable-handle icon moving along with mouse move when we have more content inside react-grid-item div

### ISSUE THREAD

**Issue by rambabu14** [STRML/react-grid-layout#940]
Hi Team, 
           react-resizable-handle icon moving along with mouse move when we have more content inside react-grid-item div, Please verify in the below fiddle.

https://codesandbox.io/s/funny-flower-ito3p

Steps to reproduce : 
1) open above fiddle 
2) move scroll down in second grid item
3) Observe resizable icon also move along with scroll move

Thanks,
Rambabu

**Comment by serebrennikovalex** [comment]
the bug was in the library "react-resizable." It will be fixed after the changes are merged into the library ('react-resizable').

**Comment by STRML** [comment]
You should make the child of the `<GridItem>` have the `overflow: auto` style, not the GridItem itself. Then this will work naturally, and you can adjust the `right: 0` CSS as-needed if you want to avoid the scroll area.

https://codesandbox.io/s/unruffled-robinson-i8ejm

<img width="486" alt="Screen Shot 2019-10-22 at 5 21 10 PM" src="https://user-images.githubusercontent.com/1197375/67334570-61b39c00-f4f0-11e9-98f2-6bc9871ce6a3.png">
<img width="464" alt="Screen Shot 2019-10-22 at 5 21 14 PM" src="https://user-images.githubusercontent.com/1197375/67334571-61b39c00-f4f0-11e9-95af-8fbcf929f22b.png">
