### ISSUE TITLE
Cannot handle conditional children

### ISSUE THREAD

**Issue by mzogheib** [STRML/react-grid-layout#943]
We have something like the following:

```jsx
<ResponsiveReactGridLayout>
  <div>This child is always present</div>
  {someCondition && <div>This child is conditionally present</div>}
</ResponsiveReactGridLayout>
```

When the conditional child is falsey, the layout breaks with the following in the console:
`Warning: Failed prop type: Cannot read property 'key' of null`

My simple workaround is a ternary with an empty `div` instead:

```jsx
<ResponsiveReactGridLayout>
  <div>This child is always present</div>
  {someCondition ? <div>This child is conditionally present</div> : <div />}
</ResponsiveReactGridLayout>
```

An alternative, slightly more complex, workaround might be to manage the children in some kind of config array, filter on only the visible children then render the result. I think that's the recommendation in the response to https://github.com/STRML/react-grid-layout/issues/216.

However, that conditional render I'm using is a pretty common React pattern so I feel like it should be supported.

Happy to investigate and raise a PR later but I want to first confirm if this is indeed a bug?

I've recreated it [here](https://codesandbox.io/embed/green-tree-h8bbf) where I'm forcing a falsey value in the `generateDOM` function's map.

**Comment by mzogheib** [comment]
Oh there's this issue and associated fix too. https://github.com/STRML/react-grid-layout/issues/577

Perhaps the fix doesn't cover this scenario?

**Comment by daynin** [comment]
@mzogheib you can fix it by filtering your items before rendering:

```javascript
const items = [
  { text: 'This child is always present' },
 someCondition &&  { text: 'This child is conditionally present' }
].filter(Boolean)

<ResponsiveReactGridLayout>
  {items.map(item => <div>{item.text}</div>)}
</ResponsiveReactGridLayout>
```

But I think, we can try to fix it on the lib's side
