### ISSUE TITLE
Styles not being applied

### ISSUE THREAD

**Issue by ericjang96** [STRML/react-grid-layout#944]
I have
```
import "react-grid-layout.css"
import "react-resizable.css"
```
at the top of my JS file where my component is defined. I'm setting `className="layout"` as specified in the examples for my GridLayout element, but none of the styles are being applied. When I do `import styles from "react-grid-layout.css"` and `className=styles["react-grid-layout"]`, I can get the style to be applied to the grid, but of course none of the grid items take on their respective styles. Any idea why the styles aren't being applied when I'm doing as the examples show?

**Comment by hlthi** [comment]
I think you don't know how to work import. That's right way.
`
import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';
`

**Comment by ericjang96** [comment]
The issue was that my webpack configuration modularized the CSS. Turns out that you need these styles to be available globally for them to be applied.

**Comment by TejaswitaS** [comment]
Yes @ericjang96 you are correct. I had to manually add these files in my top level style.scss to make it work. However I didn't have to change my webpack configs, which still has css loader. Here is my import: 
```javascript
@import '../../../../node_modules/react-grid-layout/css/styles.css';
@import '../../../../node_modules/react-resizable/css/styles.css';
```
