### ISSUE TITLE
Widgets Remounted when Parent component Changes state

### ISSUE THREAD

**Issue by boomgetchopped** [STRML/react-grid-layout#945]
My parent component renders the ReactGridLayout.

As children to ReactGridLayout I loop through a widgets collection and render each widget.

The problem is if state change in my parent component, it will remount all widgets.

This is a problem because then each widget loses it's individual state.

**Comment by hlthi** [comment]
You can use codesandbox for better explain.

**Comment by n1ghtmare** [comment]
Can you please create a codesandbox, so that we can reproduce your issue? You can use [this one](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) as a base if it would help.

Meanwhile I'll close this issue, please open a new one that has the necessary details.
