### ISSUE TITLE
Grid Position Issue

### ISSUE THREAD

**Issue by ayushigaur001** [STRML/react-grid-layout#946]
Hi,

I want to create a n*n Array for arranging my items. n can 2, 3 or 4 for now so for this i expect my grids to come in form of matrix, but i can see they are not coming as x,y i have defined for instead they are coming in random order. please help me out 

https://codesandbox.io/s/adoring-thompson-5ywnx

Expected behavior - 
![Screenshot](https://user-images.githubusercontent.com/28855173/59337747-cbd85b00-8d1e-11e9-821e-7eab335393d2.png)

**Comment by kolev** [comment]
Your x values are wrong. When it starts from 0 and you want to be wide 4 positions next x position will be 4 not 5.

**Comment by ayushigaur001** [comment]
Yes this solved my issue
