### ISSUE TITLE
HeightProvider Help 

### ISSUE THREAD

**Issue by rayray93** [STRML/react-grid-layout#947]
Hi @STRML 
Is there option to handle grid items height?  ( make item height auto ) ?

**Comment by n1ghtmare** [comment]
A lot of people have requested this (also I've seen a lot of questions about how to achieve this). I think It's a good idea to work on this and have it as part of the API for future. I'll work on it when I get some time.

**Comment by atifsyedali** [comment]
Might be a good idea to just have this library wrap the provided items in something like https://github.com/nkbt/react-height and then do the layout on the callback of height calculation for these items.

**Comment by rogerfar** [comment]
@n1ghtmare have you ever been able to get anything off the ground? This would be a very useful feature. We use this library as a lean code GUI builder, but some contents need to be able to auto grow in height.
