### ISSUE TITLE
In no vertical compact mode, dragging a grid item could "break" the layout.

### ISSUE THREAD

**Issue by f15gdsy** [STRML/react-grid-layout#95]
In the [no vertical compact demo](https://strml.github.io/react-grid-layout/examples/11-no-vertical-compact.html), dragging a grid item would push another grid item to another position when overlapped, which is great. 
However, if the item is dragged continuously crossing other grid items, those grid items would return to then original position. I know it's not a bug but more like a behaviour. But I think providing an option to make the other grid items move back when the dragged item leaves the overlap position would be very useful too.

**Comment by cmelion** [comment]
+1

**Comment by Fruko** [comment]
Is there any progress on this? I am also facing such issue when user decides to change layout, moving one item is breaking the whole layout. 

Thanks for any information

**Comment by dbrelovsky** [comment]
+1

**Comment by Entaum** [comment]
Would really love to see this fixed. :)

**Comment by equilerex** [comment]
+1 would be great to see this happening :)

**Comment by TrySound** [comment]
Is it fixed for you guys?
