### ISSUE TITLE
Cannot resize for the basic usage

### ISSUE THREAD

**Issue by seta-hungDang** [STRML/react-grid-layout#950]
Hi guys!

Thank you for such a wonderful library! It's just when I was playing around with the basic build, I ran into this issue. I wasn't be able to resize the c block like the documents say. 

Could you guys please have a look and tell me what I did wrong? Many thanks!

Here is the sandbox for it: https://codesandbox.io/s/loving-swirles-cvitn

**Comment by carolina-cascade** [comment]
You need to add the right styles to your sandbox. Once you do that, you'll see the small resize handlers on the bottom right corner.

```
<link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/react-grid-layout/0.16.6/css/styles.min.css"
/>
```

**Comment by seta-hungDang** [comment]
Hi @carolina-cascade, thank you for your reply. Is this the same with this instruction 
![image](https://user-images.githubusercontent.com/50004479/59732070-fb351d80-9272-11e9-91ce-778933b4ba07.png). I don't quite understand about the part of installing the style packages. Are they not applied when I type `npm install react-grid-layout`?

Your solution works very fine but is it any other alternatives for this approach. I can't access to the index.html file when it is built to add this tag.

**Comment by seta-hungDang** [comment]
I found the answer here in #944 so it is closed. Many thanks!
