### ISSUE TITLE
initial loading fly in positions

### ISSUE THREAD

**Issue by chrisdobler** [STRML/react-grid-layout#953]
I have been thinking that it would be awesome if you could fly in the grid items from different positions, like perhaps something similar to when you press the home button on an iphone. Is this a new idea? Is it something I could work on?

**Comment by guillaume86** [comment]
Slightly related, I'd like be able to disable fly-in animation when the component mounts.

**Comment by n1ghtmare** [comment]
Hey, @chrisdobler, do you have an API in mind? Wanna give it a shot and do a PR? Have a demo of what you mean? Tag me if you want a review, I'll do my best.

**Comment by olejorgenb** [comment]
> Slightly related, I'd like be able to disable fly-into-position animation when the component mounts.

I'd really want that too. Using the `measureBeforeMount` does not work. One realy use case is that it prevents usage of intersection observer to delay rendering of elements out of view.
