### ISSUE TITLE
change isDraggable is not work , still can drag ,but if move a position then change , it can work 

### ISSUE THREAD

**Issue by zhengwenf199000** [STRML/react-grid-layout#954]
import React from 'react';
import ReactDOM from 'react-dom';
import PropTypes from 'prop-types';

import _ from "lodash";
import { WidthProvider, Responsive } from "react-grid-layout";
//filters

import 'react-grid-layout/css/styles.css';
import 'react-resizable/css/styles.css';
import {getRandNumber,formateFilterLabel,formateDateFunLabel,isEmpty} from '../util/common';
import Logger from '../util/Logger';
const ReactGridLayout = WidthProvider(Responsive);

const defaultProps = {
    className: "layout",
    items: 20,
    rowHeight: 30,
    onLayoutChange: function() {},
    cols:  { lg: 32, md: 32, sm: 4, xs: 4, xxs: 4 },
};

const originalLayout = getFromLS("layout") || [];

export default class BasicLayout extends React.PureComponent {

    constructor(props) {
        super(props);

        this.state = {
            layout: [{ w: 2, h: 3, x: 0, y: 0, minW: 2, minH: 3 },{ w: 2, h: 3, x: 2, y: 0, minW: 2, minH: 3 },{ w: 2, h: 3, x: 6, y: 0, minW: 2, minH: 3 }],
        };

        this.onLayoutChange = this.onLayoutChange.bind(this);
        this.resetLayout = this.resetLayout.bind(this);
    }

    resetLayout() {
        let {layout} = this.state ,newLay = []
        layout.map(function (list,id) {
            if(id==0)
            list.isDraggable = false
            newLay.push(list)
        })
        this.setState({
            layout:newLay,
        });
    }

    onLayoutChange(layout) {
        /*eslint no-console: 0*/
        // saveToLS("layout", layout);
        this.setState({ layout });
        // this.props.onLayoutChange(layout); // updates status display
    }

    render() {
        let {layout} = this.state
        return (

            <div>
                <button onClick={this.resetLayout}>Reset Layout</button>
                <ReactGridLayout

                    {...this.props}

                    onLayoutChange={this.onLayoutChange}
                    layout={layout}
                >
                    {
                        layout.map(function (list,id) {
                            return(
                                <div key={id} data-grid={list}>
                                    <span className="text">id</span>
                                </div>
                            )
                        })
                    }

                </ReactGridLayout>
            </div>
        );
    }
}

function getFromLS(key) {
    let ls = {};
    if (global.localStorage) {
        try {
            ls = JSON.parse(global.localStorage.getItem("rgl-7")) || {};
        } catch (e) {
            /*Ignore*/
        }
    }
    return ls[key];
}

function saveToLS(key, value) {
    if (global.localStorage) {
        global.localStorage.setItem(
            "rgl-7",
            JSON.stringify({
                [key]: value
            })
        );
    }
}

BasicLayout.defaultProps=defaultProps

ReactDOM.render(
    <BasicLayout />,
    document.getElementById('root')
);

**Comment by n1ghtmare** [comment]
This is a very unclear issue. Please open a new issue, provide us with a [codesanbox](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js), so that we can reproduce it.

I'm closing this one for now.
