### ISSUE TITLE
CSS transform: translate makes the clicked component move

### ISSUE THREAD

**Issue by seta-hungDang** [STRML/react-grid-layout#955]
Hi guys,

Sorry that I can't recreate this bug on a SandBox because nowhere it shows this behavior.  My use case is quite simple, quite similar with [this example](https://github.com/STRML/react-grid-layout/blob/master/test/examples/1-basic.jsx). When I clicked on the draggable component in my app, its css value change from `transform: translate(10px, 10px)` to `transform: translate(20px, 355px)`. Pretty close to #640 and #171 

I tried the solution from [this one](https://github.com/STRML/react-grid-layout/issues/640#issuecomment-369204614) and also solutions from #171 . It improves a lot, now the component only changes to `transform: translate(20px, 20px)` but it is still quite annoying because users can't really click the right things in my component. If you guys have fixed this bug, please let me know.

Many thanks!

**Comment by seta-hungDang** [comment]
After playing with it for a while, I get it now. This strange behaviour appears because I add `margin: 10px` to my draggable components so when one of them is clicked, it will spontaneously add `10px` more to it. I don't really know how `transform` do that but removing `margin:10px` and every thing works as I want. Close the issue!

**Comment by agustin107** [comment]
I've fixed the same issue that you comment here, adding `useCSSTransforms={false}`.

I hope this helps the future people that are searching for the solution to this.
