### ISSUE TITLE
Safari randomly Crashes when moving/resizing grid around

### ISSUE THREAD

**Issue by bgold0** [STRML/react-grid-layout#957]
Very randomly, when I move my grid around or resize it, the entire Safari will crash and reload my page. This is the only logs I was able to find and I know it's hardly much but does anyone know why this could be happening?

Safari: 12.1 (14607.1.40.1.4)

If anyone knows anymore information I could give I'd gladly provide.

> Jun 26 12:00:56 Bryans-Mac com.apple.xpc.launchd[1] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
> Jun 26 12:00:57 Bryans-Mac com.apple.xpc.launchd[1] (com.apple.WebKit.WebContent.54E46551-28C4-4DC2-8725-4C40246587EA[73301]): Service exited due to SIGILL | sent by exc handler[73301]

**Comment by n1ghtmare** [comment]
I can't reproduce this. Can anyone else confirm that this is a bug?

**Comment by daynin** [comment]
I can't reproduce it too (safari: Version 12.1.2 (14607.3.9)). Maybe this is not a problem of the library.  @bgold0 does it happen on demo-pages or only in your app?
