### ISSUE TITLE
 react-grid-layout/test/examples/6-dynamic-add-remove.jsx 

### ISSUE THREAD

**Issue by mikeck1** [STRML/react-grid-layout#959]
**TypeError**
this.props is undefined

 92 | }
  93 | 
  94 | onLayoutChange(layout) {
> 95 |   this.props.onLayoutChange(layout);
     |  ^
  96 |   this.setState({ layout: layout });
  97 | }
  98 |

**Comment by n1ghtmare** [comment]
I'll be closing this issue as it doesn't have any details that we can work with. The referenced example works fine with no errors. If you're still facing a problem, please open a new issue and provide more details. A codesandbox would be great.
