### ISSUE TITLE
Get warning: "Failed propType: Invalid prop `x` of type `string` supplied to `Draggable`, expected `number`. Check the render method of `GridItem`.

### ISSUE THREAD

**Issue by f15gdsy** [STRML/react-grid-layout#96]
I got this warning when using ReactGridLayout

**Comment by Puffton** [comment]
The error is self-explanatory: you are using the variable "x" in the items as if it were a string, but it expects a number:

    x: "13" // incorrect
    x: 13 // correct

If you are getting the value from a html control, you have to parse it:

    x: parseInt(value)

**Comment by shenzekun** [comment]
@Puffton thank you

**Comment by tatsna** [comment]
@Puffto Thx . 
if i want size % .  
am use  {"90%"} is not work.

**Comment by MilosJo** [comment]
> @Puffton Thx .
> if i want size % .
> am use {"90%"} is not work.

If you want to use percentage, you have to make it a string
eg. `size="90%"`
This approach should work
