### ISSUE TITLE
Dynamic Row Height

### ISSUE THREAD

**Issue by anllyksell** [STRML/react-grid-layout#963]
Hi,

First of all, thanks for your effort to develope this library. I'm trying to make dynamic rowHeight. Not with px, maybe with percentage. Is there any way to make it responsive ??

**Comment by krajasekhar** [comment]
I was needed with similar feature, where I have list of accordions for draggable items and height of the item should increase when the accordion is opened.
Solved it by setting the `h` of `layout` object with the number equal to number of children inside accordion when an accordion is opened and back to 1 when it is closed.
Codesandbox url: [https://codesandbox.io/s/react-grid-layout-grouped-r5vip](url) 
hope it helps.
