### ISSUE TITLE
adding items with height > 1

### ISSUE THREAD

**Issue by StefanMermans** [STRML/react-grid-layout#965]
When adding items to the grid that have a height more than 1 they will leave a weird gap of 2 every 2 items. enabling vertical compact would fix this issue, however vertical compact doesn't work with my use-case. 

Is there something I can change in my code to prevent the gaps from happening while still maintaining a height of more than 1, or is this a bug in the library?

### Example of the issue on code sandbox
https://codesandbox.io/s/react-grid-layout-issue-25lx0?fontsize=14

### Recorded issue
[![Video demo on youtube](http://img.youtube.com/vi/UqPJ5Q3L8Ek/0.jpg)](http://www.youtube.com/watch?v=UqPJ5Q3L8Ek)

**Comment by daynin** [comment]
@StefanMermans looks like the library bug

**Comment by Spaider15** [comment]
@StefanMermans Hello, could not repeat this bug locally. It seems like that during the last build (two years ago) there was a bug in flow.

**Comment by daynin** [comment]
I'll close it for now
