### ISSUE TITLE
Newly adding grid item always should pick the first fit position from the grid

### ISSUE THREAD

**Issue by OshanAbeykoon** [STRML/react-grid-layout#968]
My Grid view as follows,
![image](https://user-images.githubusercontent.com/38980527/61514302-65311600-aa1d-11e9-92dd-c2196431a7ef.png)
I want to add a new grid item to the above grid dynamically. And i want that dynamically adding grid item to take the first fit position from the grid. Meaning that the new grid item should take place of **x: 1, y: 0** (between tile 1 and tile 2), as that position is available for another grid item to take place. likewise i want new grid item to always take the first fit position from the grid.
Is there a specific way to handle this behavior?

Currently if we add a new grid item taking coordinates **x: 0, y: 0** to the grid that new grid item will be always added to the **x: 0, y: 1** position. This will push existing grid item on that position (x: 0, y: 1) to be pushed to a new line if there is a one already.
Is this the expected behavior?

**Comment by rintala** [comment]
I am also interested in the behaviour as we add new grid items. Would make sense to prioritize filling the empty slots at the top first; especially in the vertical compacting context. This is not the current behaviour. Anyone got any ideas on where to change this?

**Comment by josesaranda** [comment]
I think you must have an ordered list of grid windows in which ordered list you must insert items comparing x and y position to the others items. After you will need to refresh the grid.

**Comment by rintala** [comment]
Yes, but then it seems we have to produce all the logic outside the component and send the correct x & y coordinates into the object we create in that case. I was hoping for a solution where we rewrite the component's own defined logic for this? I'm guessing it would be a change in `utils.js`.

**Comment by josesaranda** [comment]
I suggested to you to create a PR of this feature and try to merge it to master branch.

**Comment by daynin** [comment]
@OshanAbeykoon hi! I think you can do it by using an external array with items so you can push a new item in any position

https://codesandbox.io/s/react-grid-layout-d9n8q

This example is super simple, but it shows the idea

**Comment by daynin** [comment]
@OshanAbeykoon let me know pls, if it helps you

**Comment by daynin** [comment]
I close this issue for now
