### ISSUE TITLE
Make grid items not resize to width/height smaller than children

### ISSUE THREAD

**Issue by KMouratidis** [STRML/react-grid-layout#969]
Starting from the example code [no.11 from here](https://github.com/STRML/react-grid-layout/blob/master/test/examples/11-no-vertical-compact.jsx) I replace line 29 from:

`<span className="text">{i}</span>`

to:
```
<h1 className="text">{i}</h1>
<h1 className="text">{i}</h1>
<h1 className="text">{i}</h1>
<h1 className="text">{i}</h1>
```

Now, when I resize an item to make it as small as possible (i.e. 1 row). The result looks something like this:
![image](https://user-images.githubusercontent.com/26832680/61902029-d09d4b00-af29-11e9-8c14-70641fe92807.png)

How can I prevent the item from becoming smaller than the children element?

I tried using jquery with something like this (tried attaching it to `onResize`, `onResizeStop`, and even on the class `react-grid-item`):

`$(".react-grid-item").height($(".react-grid-item>span>div").height())`
or
```
$(".react-resizable-handle").click(function(){
	$(".react-grid-item").height($(".react-grid-item>span>div").height())
})
```

and other variants. The problem with this is that jQuery bugs with RGL and resizing does not always work properly (i.e. sometimes don't trigger the event).

**Comment by TheImpressionist** [comment]
If you are not sure how many children you can have per item you can create an HOC that calculates its own height and updates the minHeight of the element dynamically.

My solution is posted in this thread here: https://github.com/STRML/react-grid-layout/issues/971#issuecomment-519908732

**Comment by krajasekhar** [comment]
I was needed with similar feature, where I have list of accordions for draggable items and height of the item should increase when the accordion is opened.
Solved it by setting the `h` of `layout` object with the number equal to number of children inside accordion when an accordion is opened and back to 1 when it is closed.
Codesandbox url: [https://codesandbox.io/s/react-grid-layout-grouped-r5vip](url) 
hope it helps.

**Comment by daynin** [comment]
@KMouratidis did the answers above help you?

**Comment by KMouratidis** [comment]
@daynin I haven't gotten around implementing it fully yet, but TheImpressionist's suggestion was useful so far, solving the immediate problem. Feel free to close :)
