### ISSUE TITLE
When a grid item's width is small, its width cannot be resized to 1.

### ISSUE THREAD

**Issue by f15gdsy** [STRML/react-grid-layout#97]
In the [basic example](https://strml.github.io/react-grid-layout/examples/1-basic.html), if you resize the browser window to a smaller width, the grid items also resize accordingly, which is good. But when the width of a grid is too small and when you try to resize the grid to width 1, it fails to do so.

**Comment by f15gdsy** [comment]
It was due to the width passed to calcWH in GridItem.jsx is large, and the final width cannot be rounded to 1.

**Comment by STRML** [comment]
I can't replicate this anymore in `0.10`. Please reopen if you still have an issue.
