### ISSUE TITLE
Prevent compaction

### ISSUE THREAD

**Issue by N4COM** [STRML/react-grid-layout#970]
For preventing compaction, it is enough to set "verticalCompact = false" but if you do it, you get a warning:

`verticalCompact` on <ReactGridLayout> is deprecated and will be removed soon. Use `compactType`: "horizontal" | "vertical" | null.

Anyway, compactType doesn't actually support 'null' value due to propType, so when verticalCompat will be removed, there will no way to prevent compaction.

Please only submit bugs to this tracker. If you have a feature request, please implement it. This is free software and the author is busy with other projects.

Please use the [CodeSandbox Template](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js) to demonstrate your bug. It is much easier for us to help you if you do.

**Comment by n1ghtmare** [comment]
I'm not sure what you mean by `compactType` doesn't support `null`? It's not a required prop, so passing null is the same as not providing a value. It works fine even in the example [codesandbox](https://codesandbox.io/s/5wy3rz5z1x?module=%2Fsrc%2FShowcaseLayout.js). 

Perhaps, I'm misunderstanding you. What's your concern?

**Comment by N4COM** [comment]
What if I don't want a compaction? Currently I do `verticalCompact = false` but it is deprecated and there is no way to do the same effect with `compactType`.
So I'd like to have another compaction type or something similiar, for example `compactType: "horizontal"|"vertical"|"none"` so if I set `compactType: "null"`, I have the same effect of `verticalCompact = false` but with a non-deprecated API.

**Comment by n1ghtmare** [comment]
If you don't want compaction either don't set `compactType` or set it to `null`. Like in the codesandbox example `compactType={null}`.

**Comment by N4COM** [comment]
Oh, you're right, sorry. Anyway in my project it didn't work, maybe a typo. I tried again and it works.
