### ISSUE TITLE
Auto-Height (or similar) Layout Items

### ISSUE THREAD

**Issue by mperu92** [STRML/react-grid-layout#971]
Hi,
first of all i want to do congratulations for this library because it is really fantastic!
I just wanted to know if anyone had found a way to make the Layout Item dynamic in terms of height, based on the content that is in it

Thank you so much,
Matteo

**Comment by TheImpressionist** [comment]
If I understood you correctly, you want the content inside to adapt to the layout item size? In that case a simple CSS would take care of it `height: 100%;`

Alternatively if you want to have the actual layout wrapper adapt to the content height you can create an HOC component that would recalculate its own min-height of the content inside and then update the elements layout in the store somewhere.

Here's a basic example of what I use. Mine involves a few more things that are specific to my case, but this is the general idea of it: 
https://gist.github.com/TheImpressionist/083c729ca2b049ef6439f59461adc0c1

Hope this helps. Let me know if you have questions.

**Comment by eddyw** [comment]
@mperu92 
I'm rendering a component inside the grid item and keeping the `ref`. Then using:
```javascript
useLayoutEffect(() => {
  if (ref.current) {
       const height = ref.current.clientHeight
       const scroll = ref.current.scrollHeight
        if (scroll > height) {
          const newRowHeight = Math.ceil(scroll / GRID_ROW_SIZE)
          // –> update this grid item { h: newRowHeight }
        }
  }
}, [ref.current])
```
It's more or less that. My grid item component receives a prop named `updateHeight` which is called whenever the height of the `div` element changes and we need to resize the grid item in order to cover the overflow. It's actually wrapped in `setInterval` which checks every `200ms`. Not perfect but it works.

**Comment by nz-chris** [comment]
> @mperu92
> I'm rendering a component inside the grid item and keeping the `ref`. Then using:
> 
> ```js
> useLayoutEffect(() => {
>   if (ref.current) {
>        const height = ref.current.clientHeight
>        const scroll = ref.current.scrollHeight
>         if (scroll > height) {
>           const newRowHeight = Math.ceil(scroll / GRID_ROW_SIZE)
>           // –> update this grid item { h: newRowHeight }
>         }
>   }
> }, [ref.current])
> ```
> 
> It's more or less that. My grid item component receives a prop named `updateHeight` which is called whenever the height of the `div` element changes and we need to resize the grid item in order to cover the overflow. It's actually wrapped in `setInterval` which checks every `200ms`. Not perfect but it works.

@eddyw Could you please tell me/explain to me the value of GRID_ROW_SIZE?

**Comment by eddyw** [comment]
@nz-chris `GRID_ROW_SIZE` is a constant I use to set `rowHeight` prop on `GridLayout`
```javascript
<GridLayout rowHeight={GRID_ROW_SIZE} .... >
```
This line:
```
const newRowHeight = Math.ceil(scroll / GRID_ROW_SIZE)
```
Calculates how many rows we need in order to fit the content that is overflow. Then, you just need to update the layout item `h` prop to the new row height.

**Comment by nz-chris** [comment]
@eddyw Thanks. Interesting... We have a similar function to you, but we had to experiment with what number to divide the height of the component inside the grid item by. We use 10.897, despite our rowHeight prop set to 1. Do you know why this might be?
We use `const ResponsiveReactGridLayout = WidthProvider(Responsive);` as our grid layout component (WidthProvider and Responsive coming directly from the package).
Here's what our props look like 
![image](https://user-images.githubusercontent.com/37297133/63126034-13bb7d00-c003-11e9-9ca1-654065744d68.png)

**Comment by eddyw** [comment]
@nz-chris hm, `clientHeight` and `scrollHeight` includes padding but it neither includes border nor margin. So I'd check first if my grid item has border and/or margin. Maybe try setting the CSS attr `box-sizing: border-box;`

**Comment by eddyw** [comment]
@nz-chris yeah, I just noticed that you don't specify `margin` prop, so this by default falls back to (as in README.md):
```javascript
// Margin between items [x, y] in px.
margin: ?[number, number] = [10, 10],
```
In my case, it's set to `margin={[0, 0]}`, so I don't calculate top/bottom margin which is not includes in `clientHeight/scrollHeight`. The other `0.897` is .. my best guess, horizontal scrollbar which is also not included in `clientHeight/scrollHeight`

**Comment by TheImpressionist** [comment]
> @nz-chris hm, `clientHeight` and `scrollHeight` includes padding but it neither includes border nor margin. So I'd check first if my grid item has border and/or margin. Maybe try setting the CSS attr `box-sizing: border-box;`

You can get margins for your ref by using `getComputedStyle(node)`

```typescript
// Node is the HTMLElement that you need to get the margins/paddings/anything else of
const computedStyle = window.getComputedStyle(node);

// You need to cast the values though
const totalYMargin = parseInt(computedStyle.marginTop, 10) + parseInt(computedStyle.marginBottom, 10);
const totalXMargin = parseInt(computedStyle.marginLeft, 10) + parseInt(computedStyle.marginRight, 10);
...
```

Same can be done with borders. However, I think you'd want to use `offsetHeight`. It contains the padding and borders. Unless you can't for any reason. Then you can just calculate the total height using 

I'm not sure about the scrollbar. It's not part of the DOM nor the box model. Also they way to works is very browser/os specific too.

**Comment by mperu92** [comment]
> > @mperu92
> > I'm rendering a component inside the grid item and keeping the `ref`. Then using:
> > ```js
> > useLayoutEffect(() => {
> >   if (ref.current) {
> >        const height = ref.current.clientHeight
> >        const scroll = ref.current.scrollHeight
> >         if (scroll > height) {
> >           const newRowHeight = Math.ceil(scroll / GRID_ROW_SIZE)
> >           // –> update this grid item { h: newRowHeight }
> >         }
> >   }
> > }, [ref.current])
> > ```
> > 
> > 
> > It's more or less that. My grid item component receives a prop named `updateHeight` which is called whenever the height of the `div` element changes and we need to resize the grid item in order to cover the overflow. It's actually wrapped in `setInterval` which checks every `200ms`. Not perfect but it works.
> 
> @eddyw Could you please tell me/explain to me the value of GRID_ROW_SIZE?

Thank, but when I should call this function?

**Comment by eddyw** [comment]
@mperu92 that depends on what you're building. In my case, I have a RichText editor (built with SlateJS) inside a grid item, so this item needs to update its height (`h`) whenever the height of the RichText editor changes (new lines of text are added), so the react effect takes care of comparing the height and checking if it should resize. When resize is needed it calls `updateHeight` (in example code, it calls where comment is `// –> update this grid item { h: newRowHeight }`)

**Comment by daynin** [comment]
@mperu92 did you find the answer?

**Comment by kevinqiu92** [comment]
> 
> 
> If I understood you correctly, you want the content inside to adapt to the layout item size? In that case a simple CSS would take care of it `height: 100%;`
> 
> Alternatively if you want to have the actual layout wrapper adapt to the content height you can create an HOC component that would recalculate its own min-height of the content inside and then update the elements layout in the store somewhere.
> 
> Here's a basic example of what I use. Mine involves a few more things that are specific to my case, but this is the general idea of it:
> https://gist.github.com/TheImpressionist/083c729ca2b049ef6439f59461adc0c1
> 
> Hope this helps. Let me know if you have questions.

@TheImpressionist i tried using this but `componentDidUpdate` doesn't ever seem to trigger during a resize.

**Comment by kevinqiu92** [comment]
> 
> 
> If I understood you correctly, you want the content inside to adapt to the layout item size? In that case a simple CSS would take care of it `height: 100%;`
> 
> Alternatively if you want to have the actual layout wrapper adapt to the content height you can create an HOC component that would recalculate its own min-height of the content inside and then update the elements layout in the store somewhere.
> 
> Here's a basic example of what I use. Mine involves a few more things that are specific to my case, but this is the general idea of it:
> https://gist.github.com/TheImpressionist/083c729ca2b049ef6439f59461adc0c1
> 
> Hope this helps. Let me know if you have questions.

@TheImpressionist I tried using this and I can't seem to get `componentDidUpdate` to ever trigger during the resize. What state/props are supposed to change during the dragging?

**Comment by kevinqiu92** [comment]
It also seems that the HOC gets unmounted and remounted every time a resize happens, so I can see why `componentDidUpdate` isn't being called. Is anyone else seeing different behavior?

**Comment by TheImpressionist** [comment]
@kevinqiu92 That could be the issue. Although, it doesn't remount each time a resize or drag event happens for me. Are you doing anything with the `onResizeStop` or `onLayoutChange` callbacks?

**Comment by mperu92** [comment]
> @mperu92 did you find the answer?

Not yet, but I'm still trying

**Comment by kevinqiu92** [comment]
> 
> 
> @kevinqiu92 That could be the issue. Although, it doesn't remount each time a resize or drag event happens for me. Are you doing anything with the `onResizeStop` or `onLayoutChange` callbacks?
> 
> Or perhaps you're creating the HOC each time on a re-render? That would cause a remount, as the component is a new instance each time.

Yeah I believe the HOC is getting recreated each time. It might be because I have a `div` as a wrapper for the HOC? I'm pretty new to react so the lifecycle stuff isn't super clear for me yet.

**Comment by EdgarKisman** [comment]
@TheImpressionist  do you have a full example of your implementation.
My problem is: i have a widget which has the initial height of 2 and is displaying a spinner, after the data is loaded the widget should resize to the height of the fetched data. After i pass the new size, the widget does not resize, the correct size is displayed after i remount the widget.

**Comment by vikas-0** [comment]
> If I understood you correctly, you want the content inside to adapt to the layout item size? In that case a simple CSS would take care of it `height: 100%;`
> 
> Alternatively if you want to have the actual layout wrapper adapt to the content height you can create an HOC component that would recalculate its own min-height of the content inside and then update the elements layout in the store somewhere.
> 
> Here's a basic example of what I use. Mine involves a few more things that are specific to my case, but this is the general idea of it:
> https://gist.github.com/TheImpressionist/083c729ca2b049ef6439f59461adc0c1
> 
> Hope this helps. Let me know if you have questions.

Hi, can you give example that how this HOC is supposed to be used. I think it's for GridLayout but I think I am doing something wrong, maybe because I am using WidthProvider too.

**Comment by v1talii-dev** [comment]
are there any updates on this issue? maybe someone has found a solution to this problem and can post it here?

**Comment by nicolascampbell** [comment]
Hi! So I was having this problem. I have a grid of photos I want to be able to resize and move around. After seeing this and other issues I managed to piece a solution together that might help someone here.

This is my container:
```javascript
import Measure from 'react-measure'
import produce from 'immer'
import { Responsive, WidthProvider } from 'react-grid-layout'
const ResponsiveGridLayout = WidthProvider(Responsive)

const BREAKPOINTS = { lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }
const ImageGrid = () => {
  const [layouts, setLayouts] = React.useState(
    generateLayout(BREAKPOINTS, lastFilm.length)
  )
  const [breakpoint, setBreakpoint] = React.useState('lg')
  function handleItemSizeChange(size, index) {
    setLayouts(
      produce((draftState) => {
        // From formula pixelHeight = (rowHeight * h) + (marginH * (h - 1))
        // h = (pixelHeight + marginH) / (marginH + rowHeight)
        const newH = (size.height + 50) / (50 + 10)
        draftState[breakpoint][index].h = newH
        // This handles edge cases when container is on max width for screen
        // to not let it make is smaller or bigger
        draftState[breakpoint][index].minH = newH
        draftState[breakpoint][index].maxH = newH
      })
    )
  }
  function handleLayoutChange(layout) {
    setLayouts({ ...layouts, [breakpoint]: layout })
  }
  return (
    <ResponsiveGridLayout
      className="layout"
      layouts={layouts}
      breakpoints={BREAKPOINTS}
      cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }}
      rowHeight={10}
      margin={[50, 50]}
      onLayoutChange={handleLayoutChange}
      onBreakpointChange={(breakpoint) => setBreakpoint(breakpoint)}
    >
      {/* lastFilm is an array of objects with src and other stuff about the images*/}
      {lastFilm.map((item, index) => (
        <div key={index} className={'box'}>
          <MeasuredImage
            item={item}
            onSizeChange={(size) => handleItemSizeChange(size, index)}
          />
        </div>
      ))}
    </ResponsiveGridLayout>
  )
}

```

This is the grid item to which we measure the height:

```javascript
const MeasuredImage = ({ item, onSizeChange }) => {
  const getLink = (path) => `${path}`
  function handleResize(contentRect) {
    onSizeChange({
      width: contentRect.bounds.width,
      height: contentRect.bounds.height
    })
  }
  return (
    <Measure bounds onResize={handleResize}>
      {({ measureRef }) => (
        <div ref={measureRef}>
          <img
            src={getLink(item.src)}
            srcSet={getLink(item.src)}
            alt={'Picture of last film'}
            loading="lazy"
            className="preview-imgs"
            onClick={() =>
              window.open(getLink(item.src), '_blank', 'noopener,noreferrer')
            }
          />
        </div>
      )}
    </Measure>
  )
}
```

This is working for me currently. The only thing that I have problems with is that when I resize an element this red area(the placeholder) is not shown properly but I dont have time to find a solution for it.
Hope this helps someone :D

**Comment by igagandeep** [comment]
> Hi! So I was having this problem. I have a grid of photos I want to be able to resize and move around. After seeing this and other issues I managed to piece a solution together that might help someone here.
> 
> This is my container:
> 
> ```js
> import Measure from 'react-measure'
> import produce from 'immer'
> import { Responsive, WidthProvider } from 'react-grid-layout'
> const ResponsiveGridLayout = WidthProvider(Responsive)
> 
> const BREAKPOINTS = { lg: 1200, md: 996, sm: 768, xs: 480, xxs: 0 }
> const ImageGrid = () => {
>   const [layouts, setLayouts] = React.useState(
>     generateLayout(BREAKPOINTS, lastFilm.length)
>   )
>   const [breakpoint, setBreakpoint] = React.useState('lg')
>   function handleItemSizeChange(size, index) {
>     setLayouts(
>       produce((draftState) => {
>         // From formula pixelHeight = (rowHeight * h) + (marginH * (h - 1))
>         // h = (pixelHeight + marginH) / (marginH + rowHeight)
>         const newH = (size.height + 50) / (50 + 10)
>         draftState[breakpoint][index].h = newH
>         // This handles edge cases when container is on max width for screen
>         // to not let it make is smaller or bigger
>         draftState[breakpoint][index].minH = newH
>         draftState[breakpoint][index].maxH = newH
>       })
>     )
>   }
>   function handleLayoutChange(layout) {
>     setLayouts({ ...layouts, [breakpoint]: layout })
>   }
>   return (
>     <ResponsiveGridLayout
>       className="layout"
>       layouts={layouts}
>       breakpoints={BREAKPOINTS}
>       cols={{ lg: 12, md: 10, sm: 6, xs: 4, xxs: 2 }}
>       rowHeight={10}
>       margin={[50, 50]}
>       onLayoutChange={handleLayoutChange}
>       onBreakpointChange={(breakpoint) => setBreakpoint(breakpoint)}
>     >
>       {/* lastFilm is an array of objects with src and other stuff about the images*/}
>       {lastFilm.map((item, index) => (
>         <div key={index} className={'box'}>
>           <MeasuredImage
>             item={item}
>             onSizeChange={(size) => handleItemSizeChange(size, index)}
>           />
>         </div>
>       ))}
>     </ResponsiveGridLayout>
>   )
> }
> ```
> 
> This is the grid item to which we measure the height:
> 
> ```js
> const MeasuredImage = ({ item, onSizeChange }) => {
>   const getLink = (path) => `${path}`
>   function handleResize(contentRect) {
>     onSizeChange({
>       width: contentRect.bounds.width,
>       height: contentRect.bounds.height
>     })
>   }
>   return (
>     <Measure bounds onResize={handleResize}>
>       {({ measureRef }) => (
>         <div ref={measureRef}>
>           <img
>             src={getLink(item.src)}
>             srcSet={getLink(item.src)}
>             alt={'Picture of last film'}
>             loading="lazy"
>             className="preview-imgs"
>             onClick={() =>
>               window.open(getLink(item.src), '_blank', 'noopener,noreferrer')
>             }
>           />
>         </div>
>       )}
>     </Measure>
>   )
> }
> ```
> 
> This is working for me currently. The only thing that I have problems with is that when I resize an element this red area(the placeholder) is not shown properly but I dont have time to find a solution for it. Hope this helps someone :D

@nicolascampbell 

Thank you so much for providing this solution. I am trying to implment my code by following this code, i am wondering if you can provide me the code for generateLayout() , it would reallly help

**Comment by hafeyang** [comment]
I dev a adjust height layout demo [https://codesandbox.io/p/sandbox/react-grid-layout-adjust-height-ydt7t3](https://codesandbox.io/p/sandbox/react-grid-layout-adjust-height-ydt7t3) may helps.
