### ISSUE TITLE
How to insert the new item into the last item

### ISSUE THREAD

**Issue by Doobier** [STRML/react-grid-layout#983]
how to set the x, y

**Comment by josesaranda** [comment]
if you create a grid with two columns you can do it like this:

`{x : (index % 2 === 0 ? 0 : 6), y : Infinity, w : 6, h : 3}`

Where index is the index of the item in the array of items... Thus for each item you can switch between x to be 0 or 6.

**Comment by mankinchi** [comment]
I think you will need to provide more details. I can't understand what you are trying to achieve in this. And furthermore, I think you would get more attention in StackOverflow with these types of question.

**Comment by n1ghtmare** [comment]
@Doobier Further to what @josesaranda wrote, you can also check the examples, and more specifically [this one](https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html), with [this ](https://github.com/STRML/react-grid-layout/blob/master/test/examples/6-dynamic-add-remove.jsx#L69) being the relevant code.
