### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by n1ghtmare** [STRML/react-grid-layout#985]
Hi guys, there are 300+ issues and 54 pull requests and the last commit was in February (atm), is this project dead? Are you guys looking for maintainers? Anything we (the community) can do to help?

**Comment by TheImpressionist** [comment]
By the looks of it, the project owner is busy with other things in life currently.
The project has number of issues, or at least what looks like issues. The owner hasn't responded at all in a long time, so no way to know.

Would love to see this get resurrected.

I'd love to take up making a new grid layout system from scratch, but I'm currently under enough work as it is.

**Comment by n1ghtmare** [comment]
Yep, same here, I was entertaining the idea of creating my own project, however after discovering this one I don't feel the need to "reinvent the wheel", also it seems pretty good, it does a lot of things already and it has a nice API from what I see. Instead of creating a brand new project it would be good if I can help this one.

Right now I'm getting a bunch of warnings for the project using  `componentWillReceiveProps` which with the version of React that I use is considered "unsafe" and will soon be dropped completely from the API. I don't mind submitting a PR for this, but seeing that there are 54 PRs with no attention what so ever is... well, I'm not sure if I should waste my time.

I would love to help and I'm sure a lot of others would love to help too. It would be nice if we have a roadmap and some active maintainers.

**Comment by josesaranda** [comment]
> Yep, same here, I was entertaining the idea of creating my own project, however after discovering this one I don't feel the need to "reinvent the wheel", also it seems pretty good, it does a lot of things already and it has a nice API from what I see. Instead of creating a brand new project it would be good if I can help this one.
> 
> Right now I'm getting a bunch of warnings for the project using `componentWillReceiveProps` which with the version of React that I use is considered "unsafe" and will soon be dropped completely from the API. I don't mind submitting a PR for this, but seeing that there are 54 PRs with no attention what so ever is... well, I'm not sure if I should waste my time.
> 
> I would love to help and I'm sure a lot of others would love to help too. It would be nice if we have a roadmap and some active maintainers.

You can count on me!

**Comment by n1ghtmare** [comment]
@STRML Sorry, I didn't mean to sound like an asshole, I genuinely want to help with anything I can. I'm sure a lot of people in the community would like to contribute as well. The project is great.

I'm available for anything you guys need.

**Comment by josesaranda** [comment]
@STRML Same as @n1ghtmare. I will be available for anything you need

**Comment by mankinchi** [comment]
@STRML this is one of the coolest things I have ever used. Please show me how I can start working on some of the issues.

**Comment by daynin** [comment]
I want to help you as well. I think we should create some kind of project committee. You can enable PR settings which will require approves from 2 committee members. It'll allow us to control development vector of the project.

@STRML what do you think?

**Comment by STRML** [comment]
@n1ghtmare @daynin I have added you as collaborators. Please ping me if you'd like a re-review or if you would like to start cutting a release. Open a release PR and I'll do the final merge + npm push. Thank you for offering to help!

**Comment by daynin** [comment]
@STRML thank you!
