### ISSUE TITLE
Console warnings using react 16.9

### ISSUE THREAD

**Issue by gknapp** [STRML/react-grid-layout#988]
My app console warnings:
![image](https://user-images.githubusercontent.com/143027/64346913-ea32b780-cfea-11e9-9c5d-28ff0c93c63b.png)

From [code sandbox example](https://codesandbox.io/embed/headless-snow-nq18m) (with upgraded react 16.9.0 deps):
![image](https://user-images.githubusercontent.com/143027/64347130-4dbce500-cfeb-11e9-9a1b-e1abf9839a6d.png)

Using react-grid-layout 0.16.6

**Comment by daynin** [comment]
I'm working on it. I'll try to fix it as soon as possible

**Comment by n1ghtmare** [comment]
@daynin I briefly looked into it earlier today when I got some free time, but from the looks of it I had to change quite too many things in the internals to make it work with `getDerivedStateFromProps` and `componentDidUpdate`, perhaps you're on a better path than me. Let me know if you need any help with it.

**Comment by daynin** [comment]
> but from the looks of it I had to change quite too many things in the internals to make it work with getDerivedStateFromProps and componentDidUpdate

@n1ghtmare I think I did it the same way, check it out pls

**Comment by daynin** [comment]
I fixed it here #990
