### ISSUE TITLE
how can I move a grid in static grid

### ISSUE THREAD

**Issue by zhangwei900808** [STRML/react-grid-layout#989]
I want to set a big static grid other grid can move in the static grid，eg:
![image](https://user-images.githubusercontent.com/4385154/64397611-73ea8f80-d094-11e9-937e-f55548c9baa7.png)

**Comment by eddyw** [comment]
You need to do `event. stopPropagation()` on `onDrag` (and/or `onDragStart/onDragStop` on the grid), so it doesn't propagate to the current event.

This is more or less what I do:
```typescript
      const onDragEvt = React.useCallback<ItemCallback>((_l, _o, _n, _p, evt, _elem) => {
        evt.preventDefault()
        evt.stopPropagation()
      }, [])
```
