### ISSUE TITLE
WIP and IE11, touch does not work properly

### ISSUE THREAD

**Issue by Puffton** [STRML/react-grid-layout#99]
Placing a touch sensitive control (ionRangeSlider) within an item in the responsive grid layout prevents the control from registering touch on WIP IE11 (and on the new Windows 10 Phone Beta browser).

This is even for grids with drag and resize disabled, which is particularly tricky for me (since that's where I use them). Moving the control out of the grid layout, it works just fine. The problem seems unique to WIP.

RGL v0.8.5

**Comment by kumarharsh** [comment]
I'm a little confused by this.. Do you mean WP (Windows Phone) instead of WIP?

**Comment by Puffton** [comment]
Yes, I mean Windows Phone. I just saw "WIP" in the GIT history and figured it was the same, so I used the same terminology. What does WIP mean to you?

**Comment by kumarharsh** [comment]
Oh, I see :smile: Till now, the only common use I've seen for WIP is "Work In Progress". Even I had seen the commit log, but thought it was a work in progress (more commits will be made to fix the issue maybe).

**Comment by Puffton** [comment]
This is still an issue in 0.10.0-beta1.

**Comment by STRML** [comment]
@Puffton Please check with 0.10.2.
