### ISSUE TITLE
Toggling isResizable and isDraggable crashes.

### ISSUE THREAD

**Issue by pratikguru** [STRML/react-grid-layout#992]
I had a simple toggle event that toggles the state of a boolean for dynamically setting the isResizable and isDraggable props. But on change of the state the api crashes with  `index.js:95 Uncaught Error: No Delaunay triangulation exists for this input.`

1. A boolean state variable is set to default on componentDidMount callback.
2. The boolean is assigned to the props isResizable and isDraggable.
3. The boolean is toggled in a callback function linked to a button click. 

On the console I can see the value toggling, but once the props changes, the API crashes with the above written error.

Anyone else tried to dynamically change one of these props?

**Comment by KognitivnayaBuena** [comment]
Can you try repoduce it by yourself? I tried to, you can see it here https://codesandbox.io/s/amazing-rosalind-7hvf6 but there are no console errors

**Comment by n1ghtmare** [comment]
I can't reproduce it either. @pratikguru Any way you can setup a codesandbox with the issue?
