### ISSUE TITLE
Width and Height on layout items being ignored

### ISSUE THREAD

**Issue by clough360** [STRML/react-grid-layout#994]
My items are always displayed with the default width and height (1,1)

I create the layout array (direct extract from the docs) as follows:
  ```
this.state.layout = generateLayout() {
    return  [
      {i: 'a', x: 0, y: 0, w: 1, h: 2, static: true},
      {i: 'b', x: 1, y: 0, w: 3, h: 2, minW: 2, maxW: 4},
      {i: 'c', x: 4, y: 0, w: 1, h: 2}
    ];
```
and then render as follows:
```
render() {
      <ReactGridLayout
        layout={this.state.layout}
        {...this.props}
      >
        {this.generateDOM()}
      </ReactGridLayout>
    );
  }
```

If I log the layout at the start of the render method, it is correct:
![image](https://user-images.githubusercontent.com/12503052/64785791-042d4680-d565-11e9-9594-7457a896187f.png)

However, upon render, the onLayoutChange event, it is immediately called with 'reset' width and height of 1,1:
![image](https://user-images.githubusercontent.com/12503052/64785859-2de66d80-d565-11e9-8fa8-8a6c1ab7bf59.png)

What am I missing?

**Comment by MichaelFroeschen** [comment]
Unfortunately this is not a question, but actually a bug.
The issue is, that the layout is cached and re-used without merging any changes into the cached layout item.

See
https://github.com/STRML/react-grid-layout/blob/a0936f7ba5b6d88c324b4fa531ec6a54de06946e/lib/utils.js#L600-L603
Thus, if the layout changes programmatically, it will not be reflected by the grid.

An example of this issue can be found here: https://codesandbox.io/s/funny-borg-9nxt8

**Comment by MichaelFroeschen** [comment]
This i still an issue...

**Comment by MichaelFroeschen** [comment]
This i still an issue...

**Comment by kujohn** [comment]
> @clough360 pls, try to add "measureBeforeMount" prop into your React`GridLayout instance props
> 
> ```js
> <ReactGridLayout
>    layout={this.state.layout}
>    {...this.props}
>    measureBeforeMount
> >
>   {this.generateDOM()}
> </ReactGridLayout>
> ```
> 
> Let me know if it helps

This worked when working with passing `layout` to the GridLayout. It did not work with `data-grid` attribute.

**Comment by C-likethis123** [comment]
I was facing a similar issue, where the width and height on my layout items were being ignored on my `<ResponsiveGridLayout>`. I fixed this by specifying the `data-grid` attribute.

**Comment by andrey-babitsyn-jci** [comment]
Setting layout to `data-grid` also worked for me.
Make sure you pass this prop to `div` wrapping your component not to your component itself.
Like so:
    <div data-grid={layouts[i]}>
        <YourAwesomeComponent />
    </div>

**Comment by jt6677** [comment]
so the bug is ignored?  const onTakeItem = (item: ReactGridLayout.Layout) => {
    setLayouts((prevState) => {
      return {
        ...prevState,

        [currentBreakpoint]: [...prevState![currentBreakpoint], item],
      }
    })
  }    new Layouts ignore every property (w, h, y ,x minH,minW) but will take i

**Comment by jt6677** [comment]
<ResponsiveReactGridLayout
          cols={defaultProps.cols}
          rowHeight={defaultProps.rowHeight}
          measureBeforeMount={false}
          preventCollision={true}
          compactType="vertical"
          layouts={layouts}
          onBreakpointChange={onBreakpointChange}
          onLayoutChange={onLayoutChange}
          useCSSTransforms={true}
          isDraggable={isEditing}
          isResizable={isEditing}
          draggableCancel=".non-draggable">     measureBeforeMount needs to set false not true to get it to work.

**Comment by melvinchia3636** [comment]
Found a workaround here:

If you unmount the component, then update the layout and remount again, the width and height will be correctly rendered.
