### ISSUE TITLE
16-drag-outside

### ISSUE THREAD

**Issue by Marius8881** [STRML/react-grid-layout#996]
https://strml.github.io/react-grid-layout/examples/16-drag-outside.html the example is not present.

**Comment by Marius8881** [comment]
Can it also be commited to master, please. 
Thank you for the help.

**Comment by daynin** [comment]
@Marius8881 now you can find the example here https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html. (But this feature is still unpublished)
